### ISSUE TITLE
关于更新的问题

### ISSUE THREAD

**Issue by kgmxxfz** [lyswhut/lx-music-desktop#1]
![Snipaste_2019-08-19_19-54-13](https://user-images.githubusercontent.com/49973241/63263433-28299f00-c2bb-11e9-9ff4-5e889f240706.png)
 根据大佬的软件，软件启动时若发现新版本时会自动从GitHub下载安装包，下载完毕会弹窗提示更新，可是今天看见有跟新，打开软件大概三五分钟会出现如图这样，“A JavaScript error occurred in the main process     Uncaught Exception:Error:net::＿CONNECTION＿RESET”

电脑系统 win10 1903

**Comment by lyswhut** [comment]
@kgmxxfz 这个错误是发生在更新弹窗显示之前还是之后？重启软件试下还会不会报错？

**Comment by kgmxxfz** [comment]
> @kgmxxfz这个错误是发生在更新弹窗显示之前还是之后？重启软件试下还会不会报错？

没有显示更新窗口，知道更新是因为GitHub关注了大佬，今天中午没有更新的时候使用过程中就没有显示这个弹窗

**Comment by lyswhut** [comment]
你现在重启软件还会不会出现错误？你的版本号是多少？

**Comment by kgmxxfz** [comment]
[log.log](https://github.com/lyswhut/lx-music-desktop/files/3515876/log.log)
重启后还是这样，现在我软件的版本号是0.1.4，昨天是0.1.3的时候更新也是这样，现在的版本是我咋在GitHub上自己下载的

**Comment by lyswhut** [comment]
@kgmxxfz 日志显示软件已经发现有新版本，但是在下载差异文件阶段出错了，可能没有写入权限导致的，你尝试以管理员权限运行试下

**Comment by kgmxxfz** [comment]
管理员权限下还是这样

**Comment by lyswhut** [comment]
你到`%HOMEPATH%\AppData\Local\lx-music-desktop-updater`这个目录看下有没有文件，如果有的话看下文件大小，更新时下载的文件会放到这个目录下

**Comment by kgmxxfz** [comment]
![image](https://user-images.githubusercontent.com/49973241/63268232-48ab2680-c2c6-11e9-99ee-5f5f3a92ac01.png)
OK，有的，那既然是下载成功的，问题出在哪呀，大佬

**Comment by kgmxxfz** [comment]
不对，这还是0.1.4版的

**Comment by lyswhut** [comment]
我弄了个群：`830125506`，来群里说吧，这样交流不方便

**Comment by kgmxxfz** [comment]
ok

**Comment by wenzhi2020** [comment]
0.33版本,播放的歌曲跟显示歌曲的不一致,我不知道是不是缓存引起的误差.

**Comment by lyswhut** [comment]
@wenzhi2020 对于新问题请新开issue，这个问题经常出现吗？你的系统是什么？什么一般什么情况下会撤销该问题？

**Comment by lyswhut** [comment]
经过观察，安装版的软件更新失败一般是访问GitHub异常引起的，若无法自动更新，则手动下载安装包**覆盖安装**即可。
