### ISSUE TITLE
关于歌单问题

### ISSUE THREAD

**Issue by abel3839** [lyswhut/lx-music-desktop#10]
1、似乎不能创建歌单
2、试听歌单不能保存，并且歌曲不能排序，不能拖拽自定义播放顺序

**Comment by lyswhut** [comment]
目前还没有这些功能。
试听歌单不能保存是指什么？你想导出歌单？

**Comment by abel3839** [comment]
嗯，实际上2也是属于第一点了，就是歌单重命名而已，我是想讲试听歌单重命名为其他名字。
顺便说句：软件做的非常棒，如果皮肤能做成图片背景透明，自己更换图片就更棒了，像迅雷这样~
![Image of Yaktocat](http://chuantu.xyz/t6/702/1567496272x977013264.png)

**Comment by lyswhut** [comment]
你这是说多播放列表吧，软件内部已预留多播放列表扩展，后续可能会加，目前软件内置两个播放列表，即试听列表与下载管理列表，这两个列表互相独立



------------------ 原始邮件 ------------------
发件人: "abel3839"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 下午3:38
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com>; 
抄送: "落雪無痕"<lyswhut@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [lyswhut/lx-music-desktop] 关于歌单问题 (#10)




嗯，实际上2也是属于第一点了，就是歌单重命名而已，我是想讲试听歌单重命名为其他名字。
 顺便说句：软件做的非常棒，如果皮肤能做成图片背景透明，自己更换图片就更棒了，像迅雷这样~
