### ISSUE TITLE
v2.0.0 版本

### ISSUE THREAD

**Issue by lyswhut** [lyswhut/lx-music-desktop#1000]
大部分工作已经完成，可以去这里下载beta版体验：<https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml>

### 不兼容性变更说明

- 数据迁移，升级此版本时，会使用旧版本的我的列表、下载设置、快捷键设置、自定义源等数据会自动迁移到新的数据格式版本，旧的数据仍然会保留，但下载列表的数据不做迁移
- 备份文件，v2.0.0及以后版本导出的列表、配置不支持导入v2.0.0之前版本，但v2.0.0之前版本导出的列表、配置支持导入v2.0.0以及以后版本（移动端需v0.15.0起才支持导入PC端v2生成的备份数据）
- 同步功能，该功能不支持与移动端v1.0.0之前版本的使用，需等待后面的新版移动端，目前移动端v1的开发工作已在进行中

### 新增

- 新增自定义主题功能
- 新增歌单搜索功能
- 新增将本地歌曲添加到我的列表的支持，此功能可以在列表的右击菜单中使用（本地歌曲的歌词优先尝试读取相同路径下的同名歌词文件，若文件不存在则尝试读取歌曲文件内的歌词，若还是找不到歌词则尝试利用换源功能获取在线歌词，歌曲封面则是尝试读取歌曲文件内的封面，若不存在则利用换源功能获取在线封面）
- 启动软件时自动回到上次的界面，例如上次退出软件时在我的列表，下次启动软件时会自动进入我的列表
- 新增启动软件时自动播放音乐设置，默认关闭，可去设置-播放设置开启
- 新增“蛋雅深藍”、“近墨者黑”皮肤
- 新增下载歌词时是否同时下载歌词翻译、罗马音设置，默认关闭，可以去设置-下载设置开启（#344）
- 新增下载时，若目录存在同名的文件时是否跳过下载此任务的设置（默认跳过，可以去设置-下载设置更改）
- 新增界面字体大小设置
- 桌面歌词新增竖排歌词显示功能（#971）
- 桌面歌词新增歌词对齐方式、是否不允许歌词换行、歌词颜色、滚动对齐方式、歌词间距设置
- 桌面歌词新增歌曲频谱显示（得益于主窗口与桌面歌词进程通信的改进，可以将此功能以CPU使用率“相对较低”的方式带到桌面歌词中）
- 桌面歌词新增在任务栏显示歌词进程设置（此设置用于在录屏软件无法捕获歌词窗口时的变通解决方法）（#1063）
- 添加kg源罗马音歌词的支持（感谢@helloplhm-qwq）
- 支持打开波点音乐歌单（需在酷我源打开）
- 新增设置-基本设置-播放栏进度条样式设置（此版本默认使用迷你进度条样式，对于某些不喜欢该样式的人可以将其换成其他样式）
- 添加kg源评论图片展示（感谢@helloplhm-qwq）

### 优化（界面/交互/功能）

- 调整软件界面及配色，使其更加清爽
- 处于单曲循环、顺序播放、禁用切歌模式时，手动切歌将会按列表循环模式的逻辑处理切歌（#864）
- 歌单右键菜单的“重复歌曲”扫描功能现在会将歌曲名字内的括号内容移除再对比，这可以有效找出歌曲的变体，例如：`突然的自我`、`突然的自我(Live)`、`突然的自我（女生版）`、`突然的自我(DJ版)`等都会被找出来（#987）
- 允许更小的桌面歌词窗口高度，可以取消“不允许拖动到主屏幕之外”设置后，再启用“不允许歌词换行”、“置顶歌词”与“自动刷新置顶”等设置，把它拖动到任务栏上，当做任务栏歌词使用（具体可以按你想要的显示方式使用这些设置组合去调）

### 优化（程序）

- 优化程序启动性能，优化与程序交互的流畅度
- 重构整个程序，重新梳理了程序逻辑，使其更容易扩展及维护，将大部分代码从JavaScript迁移到TypeScript
- 重写配置管理、列表管理功能，列表、歌词数据从json文件迁移到sqlite3存储，这应该能解决因为意外的字符编码导致的数据文件损坏问题

### 变更

- 列表右侧的操作按钮栏默认不再显示，歌曲的操作可以使用右键菜单代替，若想恢复它们的显示，可以去设置-列表设置-启用操作按钮栏开启
- 窗口大小设置时不再自动调整字体大小，想要调整字体大小可以使用新增的字体大小设置调整

### 修复

- 修复Linux、macOS下若程序路径存在百分号时会导致软件无法启动的问题（#963）
- 支持单行多时间标签歌词解析，修复某些歌词会出现时间标签的问题

### 移除

- 移除“信口雌黄”皮肤（由于该皮肤的配色有点刺眼），若你正在使用该皮肤，可以使用自定义主题功能恢复它
- 移除Linux deb x86包构建，Electron/Chromium已不再支持 32-bit Linux（electron/electron#34787）
- 移除桌面歌词主题设置，改用桌面歌词字体颜色设置功能代替

### 其他

- 更新Electron到v19.1.9

**Comment by lyswhut** [comment]
没有严重问题的话，1.x.x版本应该不会再更新了

**Comment by shishamao** [comment]
目前版本的歌词字体没有粗体的选择，像思源黑体那种有 7 种粗细的字体也只能选择一种粗细，希望能添加**歌词字体粗体**的设置，谢谢！

**Comment by lianchengwu** [comment]
2.0 什么时候发布呢

**Comment by lyswhut** [comment]
目前大部分工作已经完成，可以去这里下载beta版体验：<https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml>

**Comment by shishamao** [comment]
> 如果不显示字体的变体出来那就证明现有的系统字体获取方法不支持，这个暂时无法解决
> 
> 目前大部分工作已经完成，可以去这里下载beta版体验：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

谢谢！

**Comment by lyswhut** [comment]
> 试了一下好像逐字歌词好像是粗体的，非逐字歌词是细体。

是的，由于逐字歌词的颜色填充与逐行歌词的实现不一样，在相同字体粗细下逐字歌词看起来会更细一些，所以我单独加粗了逐字歌词的字体，某些字体看起来可能比较明显，你可以尝试换一种桌面歌词字体，这是我用[霞鹜文楷屏幕阅读版](https://github.com/lxgw/LxgwWenKai-Screen)的效果：

![image](https://user-images.githubusercontent.com/20365169/198791015-44186f66-91c0-4168-9b52-571ffc224090.png)
![image](https://user-images.githubusercontent.com/20365169/198791166-473ebed5-c21a-4a02-b23b-3b810b1736a4.png)

这是未单独加粗的逐字歌词效果：
![image](https://user-images.githubusercontent.com/20365169/198792961-c6afe931-96de-45e8-becd-86b4f564ca50.png)

如果确实不想要单独加粗逐字歌词的话后面可以考虑提供一个设置去关掉它

**Comment by hmly720** [comment]
> > 目前版本的歌词字体没有粗体的选择，像思源黑体那种有 7 种粗细的字体也只能选择一种粗细，希望能添加歌词字体粗体的设置，谢谢！
> 
> 如果不显示字体的变体出来那就证明现有的系统字体获取方法不支持，这个暂时无法解决
> 
> 目前大部分工作已经完成，可以去这里下载beta版体验：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

老大，2.0版本 好像没有随机播放

**Comment by Josephzero5** [comment]
2.0正式版啥时候能出来啊~~期待了好久了~~

**Comment by lyswhut** [comment]
预计最迟过年的时候吧，可以先用beta版

**Comment by yafovo** [comment]
使用的版本，2.0 beta22
个人感受，一直以来易用性方面有待提升，比如说歌单和排行榜，数据源选择，一个在左侧一个在右侧，使用时有种割裂感。
1.能否考虑强化一下试听列表，这个功能，现在要删试听列表里面歌曲都麻烦，这是个常用功能，现在实际使用很糟糕。
升级成临时列表，并在主界面下面添加一个小图标，点开是个2级列表界面，可以直接，查看 选择 临时列表里面的歌曲 播放，添加到收藏列表，删除，一键清空临时列表。
2.对于排行榜的歌曲，添加一键全部（当页）添加到临时列表播放。
3.对于列表中的歌曲，可以右键直接搜索选择的歌曲名，歌手，专辑名（单独的去搜索，现在只能歌名+歌手一起搜索）。
4.列表中歌曲名字比较长的情况下，选择文字无法弹出右键。

**Comment by dlgkhouse** [comment]
冒昧的问一句，怎么下载

**Comment by lyswhut** [comment]
@yafovo 
> 1.能否考虑强化一下试听列表，这个功能，现在要删试听列表里面歌曲都麻烦，这是个常用功能，现在实际使用很糟糕。
> 升级成临时列表，并在主界面下面添加一个小图标，点开是个2级列表界面，可以直接，查看 选择 临时列表里面的歌曲 播放，添加到收藏列表，删除，一键清空临时列表。
> 2.对于排行榜的歌曲，添加一键全部（当页）添加到临时列表播放。

批量删除可以使用多选功能删除，排行榜一键播放等操作看常见问题。

> 3.对于列表中的歌曲，可以右键直接搜索选择的歌曲名，歌手，专辑名（单独的去搜索，现在只能歌名+歌手一起搜索）。
> 4.列表中歌曲名字比较长的情况下，选择文字无法弹出右键。

滑动选中列表内的歌曲名、歌手名后在选中文字处右击会快速复制选中的内容，所以不会弹出右键菜单，在搜索框右击可以快速粘贴复制的内容

**Comment by yafovo** [comment]
@lyswhut 我知道批量删列表里面的歌曲，这个批量添加排行榜歌曲，属实没想到，学到了  0 。0

**Comment by yafovo** [comment]
beta 22 现在的试听列表真的有问题，我先清空试听列表，然后各种方式 在排行榜添加，和歌单添加歌曲，试听列表一直为空，播放时正常的。

**Comment by lyswhut** [comment]
按<kbd>Ctrl</kbd>+<kbd>F12</kbd>打开开发者工具，切到控制台看看报错日志

**Comment by yafovo** [comment]
---start--- http://www.kuwo.cn/
renderer.main.worker.js:3456 hello main worker
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:73349 clear t
renderer.js:73359 setProgress 97.048913 121.965714
renderer.js:46340 ---start--- http://lyrics.kugou.com/search?ver=1&man=yes&client=pc&keyword=%E8%87%B3%E5%B0%91%E8%BF%98%E6%9C%89%E4%BD%A0&hash=E3E41A40C3C83C96B4FF36A408F5A345&timelength=119
renderer.download.worker.js:11227 hello download worker
renderer.js:46340 ---start--- http://lyrics.kugou.com/download?ver=1&client=pc&id=112763120&accesskey=DEB9208FC87B933F16BDAE7755EC66FF&fmt=krc&charset=utf8
renderer.js:71302 Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
renderer.js:71308 find otherSource Array(3)
renderer.js:71250 try toggle to:  tx 至少还有你 姚贝娜 undefined
renderer.js:46340 ---start--- https://raw.githubusercontent.com/lyswhut/lx-music-desktop/master/publish/version.json
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/1-8888.html
2renderer.js:73349 clear t
renderer.js:76712 setAllStatus 歌曲链接获取中...
renderer.js:46340 ---start--- http://media.store.kugou.com/v1/get_res_privilege
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/2-8888.html
renderer.js:46340 ---start--- http://ts.tempmusics.tk/url/kg/A2FE07559433EC66853A89FDD19DB180/128k
renderer.js:46340 ---start--- http://lyrics.kugou.com/search?ver=1&man=yes&client=pc&keyword=%E6%99%9A%E9%A3%8E%E5%91%8A%E7%99%BD%20(%E5%B9%B4%E5%BA%A6%E5%90%AC%E6%AD%8C%E6%8A%A5%E5%91%8A%E9%92%A2%E7%90%B4%E7%89%88)&hash=A2FE07559433EC66853A89FDD19DB180&timelength=73
renderer.js:71302 Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
renderer.js:46340 ---start--- http://search.kuwo.cn/r.s?client=kt&all=%E6%99%9A%E9%A3%8E%E5%91%8A%E7%99%BD%20(%E5%B9%B4%E5%BA%A6%E5%90%AC%E6%AD%8C%E6%8A%A5%E5%91%8A%E9%92%A2%E7%90%B4%E7%89%88)%20%E5%90%9E%E5%90%9E%E7%BA%AF%E9%9F%B3%E7%A4%BE&pn=0&rn=25&uid=794762570&ver=kwplayer_ar_9.2.2.1&vipver=1&show_copyright_off=1&newver=1&ft=music&cluster=0&strategy=2012&encoding=utf8&rformat=json&vermerge=1&mobi=1&issubtitle=1
renderer.js:46340 ---start--- https://u.y.qq.com/cgi-bin/musicu.fcg
renderer.js:46340 ---start--- http://interface.music.163.com/eapi/batch
renderer.js:46340 ---start--- http://pd.musicapp.migu.cn/MIGUM2.0/v1.0/content/search_all.do?ua=Android_migu&version=5.0.1&text=%E6%99%9A%E9%A3%8E%E5%91%8A%E7%99%BD%20(%E5%B9%B4%E5%BA%A6%E5%90%AC%E6%AD%8C%E6%8A%A5%E5%91%8A%E9%92%A2%E7%90%B4%E7%89%88)%20%E5%90%9E%E5%90%9E%E7%BA%AF%E9%9F%B3%E7%A4%BE&pageNo=1&pageSize=25&searchSwitch=%7B%22song%22%3A1%2C%22album%22%3A0%2C%22singer%22%3A0%2C%22tagSong%22%3A0%2C%22mvSong%22%3A0%2C%22songlist%22%3A0%2C%22bestShow%22%3A1%7D
renderer.js:73152 onLoadstart
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/3-8888.html
renderer.js:73148 onLoadeddata
renderer.js:73400 handleLoadeddata 0
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73156 onCanplay
renderer.js:73419 handleCanplay 0
renderer.js:73349 clear t
renderer.js:76712 setAllStatus 
renderer.js:73127 onPlaying
renderer.js:71308 find otherSource Array(2)
renderer.js:71250 try toggle to:  kw 晚风告白(年度听歌报告钢琴版) 吞吞纯音社 01:13
renderer.js:46340 ---start--- http://newlyric.kuwo.cn/newlyric.lrc?DBYAHlReXEpRUEAeCgxVEgAORRgLG0MXCRgaCwoRAB5UAwEaBAkEBhwaXxcAHVReSAsMAVEkOj0wJjpeXFpXQVNdXl5JAgsGHVFY
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:71278 Error: Get lyric failed
    at renderer.js:40382:72
    at async renderer.js:71307:16
    at async getLyricInfo (renderer.js:70931:12)
    at async music_getLyricInfo (renderer.js:71709:16)
renderer.js:71250 try toggle to:  tx 晚风告白 (年度听歌报告钢琴版) 吞吞纯音社 01:13
renderer.js:46340 ---start--- https://c.y.qq.com/lyric/fcgi-bin/fcg_query_lyric_new.fcg?songmid=000Da16n34AbkT&g_tk=5381&loginUin=0&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&platform=yqq
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/4-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/5-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/6-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/7-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/8-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/9-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/10-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/11-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/12-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/13-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/14-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/15-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/16-8888.html
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/rank/home/17-8888.html
renderer.js:73132 onPause
renderer.js:73349 clear t
renderer.js:73137 onEnded
renderer.js:76712 setAllStatus 
renderer.js:76712 setAllStatus 播放完毕
renderer.js:73160 onEmptied
3renderer.js:73349 clear t
renderer.js:76712 setAllStatus 歌曲链接获取中...
renderer.js:46340 ---start--- http://media.store.kugou.com/v1/get_res_privilege
renderer.js:73152 onLoadstart
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73148 onLoadeddata
renderer.js:73400 handleLoadeddata 0
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73156 onCanplay
renderer.js:73419 handleCanplay 0
renderer.js:73349 clear t
renderer.js:76712 setAllStatus 
renderer.js:73127 onPlaying
renderer.js:73132 onPause
renderer.js:73349 clear t
renderer.js:73137 onEnded
renderer.js:76712 setAllStatus 
renderer.js:76712 setAllStatus 播放完毕
renderer.js:73160 onEmptied
3renderer.js:73349 clear t
renderer.js:76712 setAllStatus 歌曲链接获取中...
renderer.js:46340 ---start--- http://media.store.kugou.com/v1/get_res_privilege
renderer.js:73152 onLoadstart
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73148 onLoadeddata
renderer.js:73400 handleLoadeddata 0
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73156 onCanplay
renderer.js:73419 handleCanplay 0
renderer.js:73349 clear t
renderer.js:76712 setAllStatus 
renderer.js:73127 onPlaying
renderer.js:73132 onPause
renderer.js:73349 clear t
renderer.js:73137 onEnded
renderer.js:76712 setAllStatus 
renderer.js:76712 setAllStatus 播放完毕
renderer.js:73160 onEmptied
3renderer.js:73349 clear t
renderer.js:76712 setAllStatus 歌曲链接获取中...
renderer.js:46340 ---start--- http://media.store.kugou.com/v1/get_res_privilege
renderer.js:73152 onLoadstart
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73148 onLoadeddata
renderer.js:73400 handleLoadeddata 0
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73156 onCanplay
renderer.js:73419 handleCanplay 0
renderer.js:73349 clear t
renderer.js:76712 setAllStatus 
renderer.js:73127 onPlaying
renderer.js:73132 onPause
renderer.js:73349 clear t
renderer.js:73137 onEnded
renderer.js:76712 setAllStatus 
renderer.js:76712 setAllStatus 播放完毕
renderer.js:73160 onEmptied
3renderer.js:73349 clear t
renderer.js:76712 setAllStatus 歌曲链接获取中...
renderer.js:46340 ---start--- http://media.store.kugou.com/v1/get_res_privilege
renderer.js:46340 ---start--- http://ts.tempmusics.tk/url/kg/C99989A620FC84796C95642EF40153E7/128k
renderer.js:46340 ---start--- http://lyrics.kugou.com/search?ver=1&man=yes&client=pc&keyword=%E4%B8%8D%E5%81%9A%E6%83%85%E4%BA%BA&hash=C99989A620FC84796C95642EF40153E7&timelength=205
renderer.js:46340 ---start--- http://lyrics.kugou.com/download?ver=1&client=pc&id=116702698&accesskey=C2AFDF44EEE9C0BE7CD4C986CA2112D0&fmt=krc&charset=utf8
renderer.js:73152 onLoadstart
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73148 onLoadeddata
renderer.js:73400 handleLoadeddata 0
renderer.js:76712 setAllStatus 音乐加载中...
renderer.js:73156 onCanplay
renderer.js:73419 handleCanplay 0
renderer.js:73349 clear t
renderer.js:76712 setAllStatus 
renderer.js:73127 onPlaying
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/special/getSpecial?is_smarty=1&
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/special/getSpecial?is_ajax=1&cdn=cdn&t=3&c=&p=1
renderer.js:46340 ---start--- http://www2.kugou.kugou.com/yueku/v9/special/getSpecial?is_smarty=1&
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
renderer.js:21944 handleRestoreScroll undefined false
renderer.js:21947 restoreScroll undefined false
3DevTools 无法加载来源映射：无法解析 file:///E:/Program%20Files/%E6%B4%9B%E9%9B%AA%E9%9F%B3%E4%B9%90/resources/app.asar/dist/comlink.mjs.map 的内容：Unexpected end of JSON input

-----------------------------------------------------
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

▼1 source
rendererjs:1


renderer.js:1这里面的内容有9万多行太长了，这里无法发表。

---------------------------------------------------------
看不懂，我把看着可能有问题的2个地方复制了

**Comment by lyswhut** [comment]
没报错的日志不用发出来啊，打开控制台，然后进行一下有问题的操作，看看有没有红色的报错日志，有的话截图那部分发出来就行了

**Comment by yafovo** [comment]
我又试了一下，在仅导入设置数据的情况下，试听列表就会异常，如果有需要我直接把设置数据发到你邮箱吧。

**Comment by lyswhut** [comment]
我没理解你说的“异常”是指什么，你去设置-关于那里加测试群具体说吧

**Comment by yafovo** [comment]
这个异常就是前面说的，正常情况是 双击左键播放歌曲，这首歌会自动添加到试听列表。
在升级到2.0的设置数据中，出现未知错误，导致双击左键播放歌曲，歌曲无法自动添加到试听列表。这个试听列表失效了。
-----------
找到的解决办法是，仅只导入列表数据，再根据自己喜好手动设置一下，这个问题不知道是不是个例，是个例就算了。。。

**Comment by lyswhut** [comment]
已发布🎉
