### ISSUE TITLE
[Bug]: 无法根据ID打开网易云歌单

### ISSUE THREAD

**Issue by TheEnd233** [lyswhut/lx-music-desktop#1001]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

输入ID打开网易云歌单，把歌曲添加到我的列表

### 实际行为

通过ID打开歌单，一直显示页面加载中

尝试通过浏览器无痕模式打开分享的歌单，发现需要登录才能查看歌单

### Lx Music 版本

1.22.3

### 操作系统版本

windows10

**Comment by lyswhut** [comment]
看常见问题：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist
