### ISSUE TITLE
[Feature]: 能否开发洛雪音乐tv版？

### ISSUE THREAD

**Issue by pangbobi** [lyswhut/lx-music-desktop#1002]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

当我在GitHub上发现lx–music这个宝藏项目后，移动端桌面端用的都是lxmusic，当我想在安卓tv上使用音乐APP时，同样很多官方APP需要付费，这是我想到了lx–music。当我再次进入此项目时，发现没有TV版，我想问一下能否开发安卓tv版lxmusic？

### 描述你想要的解决方案

能否开发安卓TV版的lx–music？

**Comment by lyswhut** [comment]
移动版就可以用，但是没适配遥控器，需要鼠标才能用，时间精力有限，不打算单独开发TV版

**Comment by pangbobi** [comment]
好的，非常感谢

lyswhut ***@***.***> 于 2022年10月1日周六 15:45写道：
