### ISSUE TITLE
[Bug]: 深色模式/黑暗模式还需完善

### ISSUE THREAD

**Issue by userzzzq** [lyswhut/lx-music-desktop#1003]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

增加对比度。

### 实际行为

![Snipaste_2022-10-01_08-18-56](https://user-images.githubusercontent.com/69742519/193375493-7214646e-a52a-4cb6-8422-482cd9dfdc57.jpg)

有些地方（如项目复选框）对比度太低，看不清。

### Lx Music 版本

1.22

### 最后正常的版本

1.22

### 操作系统版本

win11

**Comment by lyswhut** [comment]
这将在v2.0.0优化

**Comment by lyswhut** [comment]
已在v2.0.0优化
