### ISSUE TITLE
[Feature]: 希望可以用键盘上的按键控制

### ISSUE THREAD

**Issue by Kuzzi-A7** [lyswhut/lx-music-desktop#1007]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![1664793729232](https://user-images.githubusercontent.com/82040989/193558807-21c18bd9-b4ed-4512-a087-25e423e0e625.jpg)

### 描述你想要的解决方案

可以用键盘上的按键控制。

**Comment by lyswhut** [comment]
这应该是支持的，若无效则检查快捷键是否被占用
