### ISSUE TITLE
关于在线音乐-搜索-聚合搜索功能的优化建议

### ISSUE THREAD

**Issue by robot1d59cc305** [lyswhut/lx-music-desktop#101]
这个功能会出现很多重复的歌的情况,比如搜素许嵩.会出现非常多的重复的,在对于一些批量下歌的时候非常不方便.希望在这个聚合搜索中能自动去除重复名称歌曲中的时间一致的歌曲或是能提供一个条件筛选器获得特定结果.

**Comment by lyswhut** [comment]
不建议使用聚合搜索，那东西做好我就没用过，，搜索出来的结果只是进行了简单的按ASCII码排序，所以并不好用，我目前不打算研究这个，
如果谁有兴趣可以提交PR优化下，先在此谢过！

**Comment by lyswhut** [comment]
下个版本改进聚合搜索结果的排序，搜索结果将按照你所搜索内容的相似度排序~~🎉🎉

**Comment by lyswhut** [comment]
已在v1.0.0版本改进该功能，搜索时以 **歌曲名 歌手名** 搜索将会最大程度按照你的搜索词排序
