### ISSUE TITLE
[Bug]: 安装包下载安装完成后无法运行，报已损坏的错误。

### ISSUE THREAD

**Issue by jszjgqq** [lyswhut/lx-music-desktop#1011]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装完之后，程序可以正常运行，不报错。

### 实际行为

1、下载： https://github.com/lyswhut/lx-music-desktop/releases/download/v1.22.3/lx-music-desktop-1.22.3-arm64.dmg 安装包（我的电脑CPU是 M1 Pro的，所以选择下载arm64的包）。
2、计算验证md5值。
md5 lx-music-desktop-1.22.3-arm64.dmg 
MD5 (lx-music-desktop-1.22.3-arm64.dmg) = ed996855ccbcd665ec5400c3f2af5815
<img width="644" alt="iShot_2022-10-09_12 38 01" src="https://user-images.githubusercontent.com/2629994/194738352-3cc04879-24e2-48c2-b243-7697674d9e9e.png">
3、双击运行 dmg 文件，然后把 app 拖到Application目录。
4、运行lx-music-desktop.app 程序，报以下错误
<img width="260" alt="iShot_2022-10-09_12 34 13" src="https://user-images.githubusercontent.com/2629994/194738369-39290156-bedd-4dd2-a5c3-30d5c22f774e.png">

### Lx Music 版本

1.22.3

### 操作系统版本

macOs Monterey 12.6

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/install-failed

**Comment by jszjgqq** [comment]
> 看：https://lyswhut.github.io/lx-music-doc/desktop/faq/install-failed

`sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app
`

谢谢，已解决。
