### ISSUE TITLE
[Bug]: 歌曲上传到网易云音乐云盘后没有歌词只有封面

### ISSUE THREAD

**Issue by Mr-Nobody-li** [lyswhut/lx-music-desktop#1015]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

下载的音频，上传到网易云音乐云盘后有歌词

### 实际行为

使用的是桌面版lx music，设置中打开了歌词和封面嵌入，歌曲下载到本地后使用网易云音乐打开可以正常看到封面和歌词，当上传到云盘之后就不能正常看到歌词了，封面有。另外我用ios版网易云音乐打开云盘中的歌曲发现歌词和封面都没有了

### Lx Music 版本

1.22.3

### 最后正常的版本

没印象了刚开始用

### 操作系统版本

Windows 10 专业版 19043.2006

**Comment by lyswhut** [comment]
LX只负责嵌入歌曲封面、歌词到文件中，至于第三方应用支不支持读取则与LX无关
