### ISSUE TITLE
[Feature]: 添加启动软件时自动播放歌曲的功能

### ISSUE THREAD

**Issue by NONGSHENGBAO** [lyswhut/lx-music-desktop#1017]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

想要一个打开自动播放的功能

### 描述你想要的解决方案

可不可以加一个打开自动播放的功能呀

**Comment by lyswhut** [comment]
已在v2.0.0新增
