### ISSUE TITLE
[Feature]: 来个支持本地mp3播放吧

### ISSUE THREAD

**Issue by buzhidaoGH** [lyswhut/lx-music-desktop#1020]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

理论上应该不难吧...加一个本地播放;

### 描述你想要的解决方案

因为有下载的文件目录,可以重新扫描一遍目录内的所有mp3;这样间接应该可以实现本地播放

### 描述你考虑过的替代方案

替代方案的话,支持mp3拖拽到落雪.exe上面可以直接播放

### 附加信息

不知道这个小要求可以被实现吗?
不太了解 Electron 和 window的API调用结合,还是啥的,^_^
非常感谢大哥~

**Comment by 1466816641** [comment]
+1，我也想说这个问题。

**Comment by 2o181o28** [comment]
+1，也有这个需求。喜欢听的不少歌在这些国内平台上压根找不到，但是本地有mp3

**Comment by wuxinle4** [comment]
+1我自己更爱的风格在上面放不了

**Comment by a1191500** [comment]
刚刚研究了半天 还以为是BUG 原来是没有这个功能  求添加本地音乐 功能！！！！！！！！

**Comment by ren651382714** [comment]
同求 添加一个本地音乐的功能  类似点击+号 选择本地音乐添加到歌单里边 就可以

**Comment by Hugo342523** [comment]
同求。本地有一些来自其他渠道的无损音乐，如果洛雪能支持本地音乐管理，那就太棒了！

**Comment by weststarqp** [comment]
这要想加早加了，开发者不知道为啥不做这块T T

**Comment by lyswhut** [comment]
已在v2.0.0新增
