### ISSUE TITLE
[Feature]: 使歌曲的某些部分可以被跳过

### ISSUE THREAD

**Issue by wuxinle4** [lyswhut/lx-music-desktop#1022]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

部分歌曲只有live。个人认为欢呼声很影响我

### 描述你想要的解决方案

使歌曲的某些部分可以被跳过

### 描述你考虑过的替代方案

增加一些非live如录音室的歌

**Comment by lyswhut** [comment]
LX本身并不知道哪首歌的哪段是欢呼声，所以此功能目前无法实现
