### ISSUE TITLE
[Feature]: 增加一些非live如录音室的歌

### ISSUE THREAD

**Issue by wuxinle4** [lyswhut/lx-music-desktop#1023]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

增加一些非live如录音室的歌，部分歌曲只有live版，听着很难受

### 描述你想要的解决方案

增加一些非live如录音室的歌

**Comment by youheidesu** [comment]
这事你得和音乐平台说，在这说没用，lx-music不生产音乐，只是音乐的搬运工

**Comment by lyswhut** [comment]
软件内的歌曲全部来自于官方音乐平台，资源问题可以去相应官方平台反馈
