### ISSUE TITLE
[Feature]: 批量选择怎么没有了

### ISSUE THREAD

**Issue by z928187150** [lyswhut/lx-music-desktop#1024]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

批量选择怎么没有了

### 描述你想要的解决方案

批量选择怎么没有了

### 描述你考虑过的替代方案

批量选择怎么没有了

### 附加信息

批量选择怎么没有了

**Comment by wuxinle4** [comment]
按ctrl可以多选

**Comment by lyswhut** [comment]
https://lyswhut.github.io/lx-music-doc/desktop/faq/list-multiple-selection
