### ISSUE TITLE
[Feature]: 单击下载后不显示：普通音质 128k

### ISSUE THREAD

**Issue by nineloong** [lyswhut/lx-music-desktop#1027]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

单击+下载后显示：普通音质 128k，还要移动鼠标来单击一次。想下载感觉多了一步操作。

### 描述你想要的解决方案

单击 + 下载 后不显示：普通音质 128k。这样就不需要移动鼠标来单击一次（确认），直接下载。如有音质选项，可在设置里提前设置好。
使用洛雪音乐，肯定是为了下载。批量下载没解决前，怎么样能快速及方便地下载，我觉得是优先选项。
我是小白，还不太懂得怎么使用git。

### 附加信息

我遇到一个问题：下载一些歌曲时，试听发现有些歌曲是广播的形式，前面会有一段话。请问大家对这个问题怎么理解及处理呢？

**Comment by lyswhut** [comment]
批量下载使用多选下载即可，默认下载音质看这个：https://github.com/lyswhut/lx-music-desktop/issues/156
