### ISSUE TITLE
[Bug]: 网易平台歌曲失效

### ISSUE THREAD

**Issue by 353uea** [lyswhut/lx-music-desktop#1028]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![屏幕截图(410)](https://user-images.githubusercontent.com/116623118/197750196-eb8e1d7c-829d-49f6-bdb1-2c53b501e416.png)

### 实际行为

搜索网易云歌曲没有出现结果，并且网易云歌单排行榜无法加载。

### Lx Music 版本

1.22.3

### 操作系统版本

Windows11

**Comment by lyswhut** [comment]
接口本身并没有失效，是你所在网络无法连接到网易服务器的问题，尝试改DNS或者换网络
