### ISSUE TITLE
启动时自动将自己设为html文件的默认打开应用

### ISSUE THREAD

**Issue by inshallahzz** [lyswhut/lx-music-desktop#1030]
每次lx-music启动时会自动设为html文件的默认打开应用，请问有方法解决吗，谢谢

**Comment by lyswhut** [comment]
LX本身不会进行这些设置，与LX无关，你电脑的设置问题，找个浏览器去设置设置为默认浏览器试试

**Comment by SamLukeYes** [comment]
我在 NixOS 上可以复现这个问题，和默认浏览器无关。lx-music-desktop 每次启动之后，`~/.config/mimeapps.list` 的 '[Default Applications]' 中的 `text/html` 的值都会被更改为 `lx-music-desktop.desktop`。有一个 workaround 是在后面*额外添加*一行 `text/html=firefox.desktop`（或者其他浏览器），这样就能避免被修改，但这个修改 mimeapps.list 的行为恐怕还是和 LX 有关。
