### ISSUE TITLE
[Feature]:能否支持桌面歌词拖动到副屏

### ISSUE THREAD

**Issue by licheng1013** [lyswhut/lx-music-desktop#1031]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

打开桌面歌词，无法拖到到副屏。

### 描述你想要的解决方案

目前歌词只能在主屏幕显示，是否有办法移动到副屏上去。

**Comment by KiritoXF** [comment]
设置里有个选项是 **不允许歌词窗口拖出主屏幕之外** 默认是开启的，点掉就好了

**Comment by licheng1013** [comment]
> 

看到了

**Comment by ralphweni** [comment]
谢谢，我本来也想反馈这个问题的，现在会了

**Comment by licheng1013** [comment]
> 谢谢，我本来也想反馈这个问题的，现在会了
Nice
