### ISSUE TITLE
[Bug]: 有人在拼dd上面售卖

### ISSUE THREAD

**Issue by strawberry1018** [lyswhut/lx-music-desktop#1032]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

有人在拼dd上面售卖

### 实际行为

有人在拼dd上面售卖

### Lx Music 版本

1.5

### 操作系统版本

win10

**Comment by lyswhut** [comment]
给差评/申请退款
