### ISSUE TITLE
能在搜索歌单吗？比如我想搜索带“粤语”字眼的歌单，请问是否有这个功能呢？[Feature]: 

### ISSUE THREAD

**Issue by Cra2yChan** [lyswhut/lx-music-desktop#1034]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

是否有搜索歌单呢？能否实现？
首先承认每个平台的歌单都很好
但是最先映入眼帘的前几页皆是抖音热榜等
有时候想过滤一些歌单
比如我想搜索带“粤语”字眼的歌单，请问是否有这个功能呢？

### 描述你想要的解决方案

在歌单页面上面有一个搜索栏
是否能在该页面时，搜索出来的是过滤后的歌单

### 描述你考虑过的替代方案

在歌单页面上面有一个搜索栏
是否能在该页面时，搜索出来的是过滤后的歌单

### 附加信息

谢谢各位大佬的技术支持

**Comment by lyswhut** [comment]
已在v2.0.0添加
