### ISSUE TITLE
[Bug]: 32位WIN7,绿色版界面不停的闪烁,安装版无法安装

### ISSUE THREAD

**Issue by aDon0000** [lyswhut/lx-music-desktop#1035]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常使用

### 实际行为

打开后界面不停闪烁,设置全屏打开就不会,但是按了ESC后,恢复成正常界面,又会闪烁.
win7主题各种都换过了,还是闪

### Lx Music 版本

lx-音乐-桌面-v1.22.3-win_x86-green.7z

### 操作系统版本

win7 32位

**Comment by wuxian425** [comment]
[这儿有解决办法吧](https://lxmusic.toside.cn/desktop/faq/interface-abnormal)
