### ISSUE TITLE
[Bug]: macOS Ventura  已损坏，无法打开

### ISSUE THREAD

**Issue by zero3412** [lyswhut/lx-music-desktop#1036]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常启动

### 实际行为

无法启动
“lx-music-desktop.app”已损坏，无法打开。 你应该将它移到废纸篓。

### Lx Music 版本

1.22.3

### 操作系统版本

MacOS Ventura

**Comment by SteveSuv** [comment]
试试禁用运行检查
```shell
sudo spctl –master-disable
```

**Comment by daddywolf** [comment]
我也有一样的问题

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/602

**Comment by mushanlianshi** [comment]
我也有一样的问题
