### ISSUE TITLE
[Feature]: 希望增加每日推荐功能

### ISSUE THREAD

**Issue by Bulbbbb** [lyswhut/lx-music-desktop#1037]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

选择困难症用户，每天推荐规定数量的歌曲

### 描述你想要的解决方案

选择困难症用户，每天推荐规定数量的歌曲

**Comment by lyswhut** [comment]
个性化每日推荐功能不会有，你可以去听在线歌单或者排行榜，那些都是每日更新的
