### ISSUE TITLE
手机版本预计什么时候上线？

### ISSUE THREAD

**Issue by luoqiz** [lyswhut/lx-music-desktop#104]

**Comment by 709397578** [comment]
建议不要上线  一旦上线人数剧增 人怕出名猪怕壮的道理都懂吧  建议低调使用 一旦遭遇不测都没得听！------------------ 原始邮件 ------------------
发件人: "luoqiz"<notifications@github.com>
发送时间: 2019年12月25日(星期三) 晚上7:37
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [lyswhut/lx-music-desktop] 手机版本预计什么时候上线？ (#104)


 
&mdash;

**Comment by lyswhut** [comment]
时间不确定，之前只是有这个计划而已
由于基本不用手机听歌，所以开发兴致不大，移动版还没开始开发，或许哪天心血来潮就做了，再或许不会做

**Comment by jy05568536** [comment]
如果可以提供api，我可以开发移动版 😃

**Comment by liust15** [comment]
可以联合可发移动端

**Comment by lvyandev** [comment]
flutter全家桶包你满意
