### ISSUE TITLE
[Bug]: 歌词字体样式无法履行

### ISSUE THREAD

**Issue by VirtuosoZed** [lyswhut/lx-music-desktop#1040]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在**设定**里更改歌词字体样式后，在播放详情页面并未应用，还是**默认字体**，重启应用依旧如此。尝试多个字体无果。

### 实际行为

当我选择更改歌词字体后，歌词字体样式应该随之更改或在下次播放时更改。

### Lx Music 版本

1.22.3

### 最后正常的版本

none

### 操作系统版本

Windows 11 Pro 22H

**Comment by lyswhut** [comment]
目前没有单独更改播放详情页的歌词字体功能，要么更改软件的显示字体，要么更改桌面歌词字体

**Comment by VirtuosoZed** [comment]
了解
