### ISSUE TITLE
[Feature]: 请求添加本地单个音乐和整个文件夹到收藏列表功能

### ISSUE THREAD

**Issue by s192516** [lyswhut/lx-music-desktop#1041]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

本地很多音乐想要一键导入播放器播放

### 描述你想要的解决方案

本地很多音乐想要一键导入播放器播放

**Comment by lyswhut** [comment]
已在v2.0.0新增
