### ISSUE TITLE
[Bug]: ubuuntu18.04 下载的 x86版本的deb包，安装完成之后，不能打开，会报错

### ISSUE THREAD

**Issue by sdsafsdfsaf** [lyswhut/lx-music-desktop#1043]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望能够使用

### 实际行为

执行命令 lx-music-desktop后发生报错，结果为：
lx-music-desktop: error while loading shared libraries: libxshmfence.so.1: wrong ELF class: ELFCLASS64

### Lx Music 版本

1.22.3

### 最后正常的版本

未知

### 操作系统版本

Ubuntu

**Comment by lyswhut** [comment]
Electron/Chromium已不再支持 32-bit Linux（https://github.com/electron/electron/pull/34787）

**Comment by sdsafsdfsaf** [comment]
> Electron/Chromium已不再支持 32-bit Linux（[electron/electron#34787](https://github.com/electron/electron/pull/34787)）
我有点不太理解，可是我的系统是64位的，所以用不了这个软件吗

**Comment by lyswhut** [comment]
64位系统为什么不下x64包？

**Comment by sdsafsdfsaf** [comment]
谢谢，已经解决。
