### ISSUE TITLE
[Feature]: win11系统任务栏非常适合任务栏歌词

### ISSUE THREAD

**Issue by skwjzc** [lyswhut/lx-music-desktop#1044]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

win11系统任务栏非常适合任务栏歌词
![image](https://user-images.githubusercontent.com/103957763/200111896-a3da4fa9-cfcd-4756-84df-d0bff8ef2de6.png)

### 描述你想要的解决方案

有考虑加入吗

**Comment by lyswhut** [comment]
v2.0.0-beta已针对这个进行优化具体是：

> 桌面歌词新增歌词对齐方式、是否不允许歌词换行、歌词颜色、滚动对齐方式、歌词间距设置
> 允许更小的桌面歌词窗口高度，可以取消“不允许拖动到主屏幕之外”设置后，再启用“不允许歌词换行”、“置顶歌词”与“自动刷新置顶”等设置，把它拖动到任务栏上，当做任务栏歌词使用

**Comment by skwjzc** [comment]
> 

![屏幕截图 2022-11-13 134457](https://user-images.githubusercontent.com/103957763/201507761-1bbb7d50-1380-46e4-9773-f9d02da94e1c.png)
确实可以，这样的效果我就很满足了！

**Comment by lyswhut** [comment]
可以配合新增的那些桌面歌词设置，按自己喜好调整成单行、多行显示（通过字体大小、对齐方式、滚动位置、间距等设置）

**Comment by 006lp** [comment]
> 可以配合新增的那些桌面歌词设置，按自己喜好调整成单行、多行显示（通过字体大小、对齐方式、滚动位置、间距等设置）

任务栏播放单行歌词能不能实现原文和译文的显示为：
原文（译文），例如：
広い宇宙の数ある一つ（浩瀚的宇宙中有一个仅有的蓝色星球）
这样的形式呢
