### ISSUE TITLE
[Bug]: the song says sq but it can only download at 128 kbps

### ISSUE THREAD

**Issue by vehosah** [lyswhut/lx-music-desktop#1046]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

when it says sq its suposed to be flac

### 实际行为

but the download shows only 128 kbps

### Lx Music 版本

1.23.3

### 操作系统版本

windows 10 1511

**Comment by lyswhut** [comment]
Sound quality other than 128kbps is currently unavailable, https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749

**Comment by vehosah** [comment]
> Sound quality other than 128kbps is currently unavailable, [#180 (comment)](https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749)

And when it will be available?

**Comment by lyswhut** [comment]
Don't know, at least not in the short term, but you can use [third-party sources](https://github.com/lyswhut/lx-music-desktop/issues/703)
