### ISSUE TITLE
[Feature]: 外文歌名能加中文译名吗

### ISSUE THREAD

**Issue by xivi1839** [lyswhut/lx-music-desktop#1060]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

外文的歌名能加中文译名吗，比如 原韩文+[中文]，下载的歌曲也有显示，歌词也显示译文

### 描述你想要的解决方案

。

### 描述你考虑过的替代方案

。

### 附加信息

。

**Comment by helloplhm-qwq** [comment]
能拿到数据就行

**Comment by lyswhut** [comment]
不行，所有数据都来自官方音乐平台，没有那就是没有
