### ISSUE TITLE
[Feature]: OBS歌词捕捉问题

### ISSUE THREAD

**Issue by realfan-wing** [lyswhut/lx-music-desktop#1063]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

使用obs进行直播时想要捕捉透明底的歌词界面，但是选择之后
无论选择哪种捕捉方式均无法获取歌词的显示界面
![image](https://user-images.githubusercontent.com/78353224/204033933-278b9864-6fe7-4473-b36f-f28bb84b6e05.png)

**Comment by realfan-wing** [comment]
我的操作系统是
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.819
体验	Windows Feature Experience Pack 1000.22636.1000.0，
OBS的版本是28.1.2（64位）

![image](https://user-images.githubusercontent.com/78353224/204034206-442f4086-ff00-4341-92be-c0cea5c05e59.png)
如图所示，选择win10以上的采集方法时连歌词界面的边框形状也无法获取

**Comment by realfan-wing** [comment]
其实也找到了这个问题与我的需求类似https://github.com/lyswhut/lx-music-desktop/issues/451
但是在已经安装好的客户端下似乎无法进行修改，只能冒昧提出问题

**Comment by lyswhut** [comment]
据测试只有将歌词进程显示在任务栏才可以正常捕获，下个版本新增一个将歌词窗口显示在任务栏的设置：

![image](https://user-images.githubusercontent.com/20365169/204071244-73c6480f-026c-4bfd-86b7-cca83ff2fa7d.png)

启用后再任务栏会显示歌词窗口进程：
![image](https://user-images.githubusercontent.com/20365169/204071267-d5481400-87cd-4ca8-aa20-7dd9b9ced5c5.png)

然后录屏软件可以捕获窗口：

![image](https://user-images.githubusercontent.com/20365169/204071428-b55e0b58-95cc-421f-9596-d541bc196783.png)
