### ISSUE TITLE
[Bug]: 公司网络环境下，KG、KW的搜索、歌单、排行榜3项功能无法使用，相关歌曲列表无法搜索、加载。而秋、芸、蜜正常。

### ISSUE THREAD

**Issue by glamout** [lyswhut/lx-music-desktop#1065]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常加载排行榜歌曲

### 实际行为

无法加载，显示：啊，加载失败了。
分别尝试了测试、临时和六音音乐来源，均无法加载。
另：已知公司网络有过滤网关，会屏蔽一些网站：如游戏、视频等网站。

### Lx Music 版本

1.22.3

### 最后正常的版本

1.22.3

### 操作系统版本

MAC Ventura 13.0.1

**Comment by lyswhut** [comment]
所在网络环境问题导致的无法播放与软件本身无关，可以换网络（如开热点）或者使用代理
