### ISSUE TITLE
[Bug]: 软件关闭再开启，桌面歌词被关闭

### ISSUE THREAD

**Issue by hychuyin** [lyswhut/lx-music-desktop#1069]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

上次打开时歌词是开启状态，关闭软件后再次打开，歌词应该是打开并在原位置显示

### 实际行为

上次打开时歌词是开启状态，关闭软件后再次打开，歌词是关闭状态

### Lx Music 版本

2.0.0-beta.19

### 最后正常的版本

2.0.0-beta.16

### 操作系统版本

Windows 10 专业版 21H2

### 附加信息

卸载重新安装后，还是一样的问题

**Comment by lyswhut** [comment]
已在v2.0.0-beta.21修复
