### ISSUE TITLE
[Feature]: 能否添加命令行界面？

### ISSUE THREAD

**Issue by FHYQ-Dong** [lyswhut/lx-music-desktop#1070]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望将此项目部署到服务器上，请问能否完全通过命令行界面操作？

### 描述你想要的解决方案

一个只有CLI的release

**Comment by lyswhut** [comment]
这只是一个音乐软件，出于什么目的需要把此项目部署到服务器上？
如果是为了同步功能，则等一会有时间会做一个独立版的同步服务

**Comment by FHYQ-Dong** [comment]
事实上是希望能从多个设备上控制一台机器（如服务器或NAS）下载音乐，达到方便管理和存档的目的

**Comment by lyswhut** [comment]
这只是一个简单的听歌软件，即使是同步服务也只是仅同步列表数据，不会同步歌曲文件，目前没有将它做成音乐管理类软件的计划

**Comment by FHYQ-Dong** [comment]
> 这只是一个简单的听歌软件，即使是同步服务也只是仅同步列表数据，不会同步歌曲文件，目前没有将它做成音乐管理类软件的计划

**Comment by FHYQ-Dong** [comment]
> 这只是一个简单的听歌软件，即使是同步服务也只是仅同步列表数据，不会同步歌曲文件，目前没有将它做成音乐管理类软件的计划

好的，了解，感谢回复。
