### ISSUE TITLE
[Feature]: “我的列表”中的搜索功能

### ISSUE THREAD

**Issue by BOZHENG001** [lyswhut/lx-music-desktop#1073]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望可以在“我的列表”中添加一个搜索功能。

### 描述你想要的解决方案

比如说，进入“我的列表”-->“我的收藏”之后，在界面中可以显示一个搜索框用以搜索“我的收藏”中的歌曲。

**Comment by lyswhut** [comment]
重复：
- https://github.com/lyswhut/lx-music-desktop/issues/787
- https://github.com/lyswhut/lx-music-desktop/issues/976
- https://github.com/lyswhut/lx-music-desktop/issues/651
