### ISSUE TITLE
[Bug]: 标题栏突然没了，窗口大小调整选项全变成灰色了，卸载重装也没用

### ISSUE THREAD

**Issue by BIGMONK** [lyswhut/lx-music-desktop#1076]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

页面正常显示标题栏，软件窗口大小可调整

### 实际行为

标题栏突然没了，窗口尺寸调整选项全变成灰色了，卸载重装也没用

### Lx Music 版本

v1.22.3-x64

### 最后正常的版本

v1.22.3-x64

### 操作系统版本

windows10  20H2

### 附加信息

![2022-12-09_233803](https://user-images.githubusercontent.com/18308637/206739009-f5d28690-3fab-47a0-8457-d1dd13538f9e.png)

**Comment by hychuyin** [comment]
emm，你这是按F11进入全屏模式了吧，再按一次F11就退出了

**Comment by BIGMONK** [comment]
> emm，你这是按F11进入全屏模式了吧，再按一次F11就退出全屏了

原来如此，谢谢
