### ISSUE TITLE
[Feature]: 提供其他应用音量减弱功能的禁用选项

### ISSUE THREAD

**Issue by ljm12914** [lyswhut/lx-music-desktop#1078]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

lx-music 在播放时貌似会通知其他应用将音量减少（貌似是减少到 1/8），导致很多应用音量过小。

### 描述你想要的解决方案

在设置中提供一个禁用该功能的选项。

### 描述你考虑过的替代方案

可以通过音量合成器调整，但是这很麻烦。plus：这不能实际解决问题，在播放完毕后所有其他应用的音量都将突增。

### 附加信息

这应该不是 Chromium 内核的问题，因为在网页播放音乐时不会出现这种问题。

测试的全程 lx-music 应用内音量保持在 7%。

Windows 10 22H2 19045.2311（Windows Feature Experience Pack 120.2212.4190.0）

lx-music 1.22.3

**Comment by ljm12914** [comment]
使用的构建安装包：x64_setup

**Comment by hychuyin** [comment]
是不是这个问题？你可以先尝试一下
WIN10系统：右键任务栏的扬声器图标，在选项框中选择声音，在弹出的选项卡中选择通信，然后选择“不执行任何操作”试试
以上是我的理解，如果没能帮助到的话，很抱歉。

**Comment by ljm12914** [comment]
> 是不是这个问题？你可以先尝试一下 WIN10系统：右键任务栏的扬声器图标，在选项框中选择声音，在弹出的选项卡中选择通信，然后选择“不执行任何操作”试试 以上是我的理解，如果没能帮助到的话，很抱歉。

很可惜，调整设置后仍然不起作用。其他应用的音量仍然被减少了。

**Comment by hychuyin** [comment]
> > 是不是这个问题？你可以先尝试一下 WIN10系统：右键任务栏的扬声器图标，在选项框中选择声音，在弹出的选项卡中选择通信，然后选择"不执行任何操作"试试 以上是我的理解，如果没能帮助到的话，很抱歉。
> 
> 很可惜，调整设置后仍然不起作用。其他应用的音量仍然被减少了。

这种情况我没遇到过，主要是一边听音乐一边播放其他应用的这种情况很少，要是BUG的话就只能等修复啦

**Comment by lyswhut** [comment]
这应该是你电脑的声卡驱动/设置问题，其他人都没遇到这个问题，我这边也是正常的，重装下声卡驱动调整设置等操作，仍然不行的话尝试去声音取消自动减少音量

![image](https://user-images.githubusercontent.com/20365169/206829498-38838c3e-d247-4339-9179-c55718ad3b52.png)

**Comment by ljm12914** [comment]
鉴于这个问题不可复现且本人更换新电脑后并未出现该问题，现关闭此 Issue。
