### ISSUE TITLE
[Bug]: 1.22.3版本窗口四周有黑框

### ISSUE THREAD

**Issue by FHYQ-Dong** [lyswhut/lx-music-desktop#1079]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![image](https://user-images.githubusercontent.com/87631978/206823612-524c2662-09ee-48d2-8208-c5175d7493cb.png)

### 实际行为

![image](https://user-images.githubusercontent.com/87631978/206823575-a082d8a6-c81b-4170-bbb5-7addf464e133.png)

### Lx Music 版本

1.22.3

### 操作系统版本

Windows10 内部版本 19045.2251

### 附加信息

经检验是显卡问题。显卡型号 NVIDIA GeForce MX150 驱动版本 527.56

**Comment by lyswhut** [comment]
建议尝试更新显卡驱动看是否能解决，`-dha`会禁用硬件加速，降低了性能

**Comment by RAint0** [comment]
最近发现是electron的通病，可以尝试在Nvidia控制面板中关闭「平滑处理-FXAA」
