### ISSUE TITLE
希望添加本地播放器功能，也作为本地音乐听歌用。

### ISSUE THREAD

**Issue by Chilled-ops** [lyswhut/lx-music-desktop#108]
**描述您想要的解决方案**
最近在找本地播放器，替换来替换去，那么多年才发现其实没有一个好用的。

**描述您考虑过的替代方案**
考虑过所有的小而专的方案，但是都不好用。

**其他内容**
目前还存在电脑里的音乐播放器，就落雪的好用了，不想到处找本地播放器，已经找过好几次了，没有一个好用的。

**Comment by lyswhut** [comment]
本软件不适合做播放器使用，软件的播放功能设计的初衷是用于试听。
详情看常见问题第一条：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md
