### ISSUE TITLE
[Feature]: 请问http://ts.tempmusics.tk/url/tx/001QGcyU3RXtdA/flac这个接口如何使用呢

### ISSUE THREAD

**Issue by JieNiGui06** [lyswhut/lx-music-desktop#1080]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

http://ts.tempmusics.tk/url/tx/001QGcyU3RXtdA/flac是否已经失效，还是需要特殊headers，
我是这样的：
{
	"method": "get",
	"timeout": "15000",
	"lookup": "97.64.37.235",
	"family": "4",
	"User-Agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)",
	"624868746c": "624868746c"
}

### 描述你想要的解决方案

请大佬告知使用方法，每个参数的获取方法

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/359

而且此接口仅支持128k，最初的原因参考：https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749
