### ISSUE TITLE
[Bug]: 网易云歌单无法打开（非我喜欢的音乐）

### ISSUE THREAD

**Issue by sceraser** [lyswhut/lx-music-desktop#1081]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常打开https://music.163.com/#/album?id=89681455 歌单

### 实际行为

加载失败
![image](https://user-images.githubusercontent.com/42718757/206931904-f43e20b6-6ea2-4215-be0f-a0b727c31da9.png)

### Lx Music 版本

1.22.3

### 操作系统版本

Winodws 11 22H2

### 附加信息

怀疑是歌单中包含已下架歌曲导致无法加载

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/332

**Comment by sceraser** [comment]
明白了，希望未来能支持专辑和电台
