### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by kunkun0** [lyswhut/lx-music-desktop#1082]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

无损音质下载

### 描述你想要的解决方案

希望可以下载Flac或ape版本的歌曲

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749
