### ISSUE TITLE
[Feature]: 可以增加听歌识曲吗

### ISSUE THREAD

**Issue by xivi1839** [lyswhut/lx-music-desktop#1089]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有些曲子不错，但是不懂歌名，想用听歌识曲，可以增加这个功能吗
还有歌词搜歌

### 描述你想要的解决方案

如题

### 描述你考虑过的替代方案

如题

**Comment by lyswhut** [comment]
建议用其他音乐软件识曲，无加此功能的计划
