### ISSUE TITLE
[Feature]: 提供打开开发者工具的方法

### ISSUE THREAD

**Issue by ljm12914** [lyswhut/lx-music-desktop#1090]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

没有找到任何能打开开发者工具的路径，想调试只能自己构建修改后的安装包。

### 描述你想要的解决方案

在设置中提供一个按钮打开开发者工具。可以加 1024 层警告，没问题。

### 描述你考虑过的替代方案

自己构建修改后的安装包，安装

### 附加信息

需要开发者工具来对软件进行调试，以方便为软件做贡献。

例如，音频可视化只能用默认输出设备，可以用开发者工具验证 AudioContext 的情况或有没有用 AudioContext，没有的话我也许可以补上

**Comment by lyswhut** [comment]
以下方式都可以打开开发者工具：
- 按<kbd>ctrl</kbd>+<kbd>f12</kbd>
- 连续点击6-8次当前版本号
- 加启动参数`-odt`

据测试，音频可视化与输出设备切换功能冲突，只能开启其中一个，如果能找到解决方法欢迎讨论改进
