### ISSUE TITLE
增添【设置歌词最大行数】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#1091]
如下图，移动端支持【设置歌词最大行数】功能，而桌面端并没有该功能，希望桌面端也可以支持该功能。

![Screenshot_2022-12-31-12-27-15-102-edit_cn.toside.music.mobile.jpg](https://user-images.githubusercontent.com/69227436/210124752-eccb6189-a96f-40da-b7c6-be43c15cbb7c.jpg)

**Comment by lyswhut** [comment]
PC端暂不打算加行数设置，想要特定行数可以通过调整窗口大小、字体大小实现

**Comment by 1457384613gh** [comment]
> PC端暂不打算加行数设置，想要特定行数可以通过调整窗口大小、字体大小实现

调整了以后，歌词总是 半行半行地出现，像被横切中线了一样。

**Comment by lyswhut** [comment]
要配合间距大小、字体大小，滚动对齐方式调整
