### ISSUE TITLE
[Bug]: Win10系统下显示界面闪退

### ISSUE THREAD

**Issue by Mr-BeanSir** [lyswhut/lx-music-desktop#1092]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常启动运行

### 实际行为

双击启动后卡死几秒后闪退，运行如图 [https://img.hashx.cn/i/2022/12/31/we35ri.png](url)
之前运行正常，突然闪退卡死，已尝试使用附加命令无效，已尝试上级目录无中文、特殊字符

### Lx Music 版本

1.22.3

### 最后正常的版本

1.22.3

### 操作系统版本

Windows10 专业版 10.0.19044

### 附加信息

cmd运行输出如下
`20:00:45.304 > App starting...
init
20:00:45.501 > Register hot key failed: MediaPlayPause
20:00:45.502 > Register hot key failed: MediaPreviousTrack
20:00:45.503 > Register hot key failed: MediaNextTrack
20:00:45.503 > Register hot key failed: mod+alt+arrowleft
20:00:45.504 > Register hot key failed: mod+alt+arrowright
20:00:45.505 > Register hot key failed: mod+alt+arrowup
20:00:45.506 > Register hot key failed: mod+alt+arrowdown
20:00:45.507 > Register hot key failed: mod+alt+p
20:00:45.568 > Checking for update
20:00:45.570 > Checking for update...
20:00:45.572 > Error: Error: ENOENT: no such file or directory, open 'F:\lx\resources\app-update.yml'
20:00:45.573 > Error in auto-updater.
Unhandled Rejection at: Promise  Promise {
  <rejected> [Error: ENOENT: no such file or directory, open 'F:\lx\resources\app-update.yml'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'F:\\lx\\resources\\app-update.yml'
  }
}
 reason:  [Error: ENOENT: no such file or directory, open 'F:\lx\resources\app-update.yml'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'F:\\lx\\resources\\app-update.yml'
}
20:00:45.579 > Error: ENOENT: no such file or directory, open 'F:\lx\resources\app-update.yml'
(node:18780) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'F:\lx\resources\app-update.yml'
(Use `lx-music-desktop --trace-warnings ...` to show where the warning was created)
(node:18780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by lyswhut** [comment]
你贴的这些日志看起来是跟卡死闪退无关，同样是1.22.3之前可以正常运行？尝试下2.0.0？

**Comment by Mr-BeanSir** [comment]
尝试2.0.1已解决，感谢回复
