### ISSUE TITLE
[Feature]: 打开歌单点击后，增加点击淡化的背景也可以关闭窗口功能

### ISSUE THREAD

**Issue by Mr-BeanSir** [lyswhut/lx-music-desktop#1096]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

打开歌单点击后，仅能通过右上角X号关闭弹出窗口，如图： [https://img.hashx.cn/i/2023/01/02/shbpt1.png](https://img.hashx.cn/i/2023/01/02/shbpt1.png)

### 描述你想要的解决方案

增加点击淡化的背景也可以关闭窗口功能

**Comment by lyswhut** [comment]
已在v2.0.3优化
