### ISSUE TITLE
[Feature]: 显示当前列表

### ISSUE THREAD

**Issue by Bulbbbb** [lyswhut/lx-music-desktop#1100]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

切换到当前列表（歌单、排行榜）后，如果切换到其他页面，就无法查看当前列表了，要想听列表其他歌必须要记住以前的操作再点一遍，所以建议在播放栏增加一个显示当前歌曲列表的功能。

### 描述你想要的解决方案

在播放栏增加一个显示当前歌曲列表的功能

**Comment by lyswhut** [comment]
播放栏没有地方加这个，建议使用歌单、排行榜的“播放”功能或者开启“双击列表里的歌曲时自动切换到当前列表播放”功能播放，用这两种方式播放的歌曲，可以通过封面定位当前播放的歌曲，详情看：<https://lyswhut.github.io/lx-music-doc/desktop/faq/list-play-all>
