### ISSUE TITLE
[Bug]: 桌面歌词使用斜体出现截断

### ISSUE THREAD

**Issue by akschy** [lyswhut/lx-music-desktop#1106]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

无论什么字体，正常显示歌词

### 实际行为

当使用斜体（目前使用字体：得意黑）时，歌词的开始和结束有截断
<img width="392" alt="79162844564fdd5de28379a4ab01313" src="https://user-images.githubusercontent.com/44605406/210497394-ff2c3c2a-1ed8-419a-b0a9-0a9eab19c9e2.png">
顺便，可视化效果在浅色或者复杂颜色背景下基本不可见，希望把透明度调低一些或者开放自定义设置

### Lx Music 版本

2.0.2

### 操作系统版本

Windows 11  25267.1000

**Comment by akschy** [comment]
<img width="814" alt="506b6f0f21f2971e929870390483393" src="https://user-images.githubusercontent.com/44605406/210689161-63359014-d2e7-4d75-ae57-6be73685d1e3.png">
补充提交，这里更明显

**Comment by lyswhut** [comment]
我试了下没能重现这个问题，肯能在某些特定的配置下才会出现？
![image](https://user-images.githubusercontent.com/20365169/210691669-bed9a124-d552-4cd6-be18-4dbb28f37d3b.png)

**Comment by akschy** [comment]
系统显示设置 ： 分辨率2560*1600 150%缩放

桌面歌词设置开启项
  - 显示歌词
  - 锁定歌词
  - 使歌词总在其他窗口之上
  - 自动刷新歌词置顶
  - 不允许歌词窗口拖出主窗口之外
  - 不允许歌词换行
  - 缩放当前播放的歌词

歌词显示方向 
  - 水平方向

正在播放歌词滚动位置
  - 中心

歌词对齐方式
  - 居中

歌词间距 
  - 25

歌词字体
  - 得意黑

布局如下：
![image](https://user-images.githubusercontent.com/44605406/210764001-76991eaa-97ae-4234-ae42-c44913733152.png)

桌面歌词配置就是这样了，有没有可能是`缩放当前播放的歌词`引起的问题

**Comment by lyswhut** [comment]
那你这个问题不是靠近边缘导致的截断，可能是显示缩放导致的，你可以试试改回100%缩放注销后看看效果

**Comment by lyswhut** [comment]
已在v2.0.3修复
