### ISSUE TITLE
[Bug]: 歌曲后面没有显示下载按钮

### ISSUE THREAD

**Issue by sdfonesu** [lyswhut/lx-music-desktop#1109]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

歌曲后面没有显示下载按钮

### 实际行为

启用下载动能后，歌曲最后面没有显示播放、下载等小图标。

### Lx Music 版本

intel  2.02

### 最后正常的版本

应该是2.01之前的版本

### 操作系统版本

macOS ventura 13.1

**Comment by Heart-Breaker-Z** [comment]
相同问题，希望解答

**Comment by sdfonesu** [comment]
> **相同问题，希望解答** **只有酷我音乐可以正常下载** **操作系统版本**MacOS Monterey 12.0.1

设置里有个列表设置，里面有个显示列表操作按钮选项，勾选上就可以了。

**Comment by lyswhut** [comment]
引用自v2.0.0更新日志：

> 列表右侧的操作按钮栏默认不再显示，歌曲的操作可以使用右键菜单代替，若想恢复它们的显示，可以去设置-列表设置-启用操作按钮栏开启
