### ISSUE TITLE
[Bug]: 播放音乐后，下方面板不显示播放进度了，只能到播放详情里去调整

### ISSUE THREAD

**Issue by oneday219** [lyswhut/lx-music-desktop#1111]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在操控面板中显示播放进度

### 实际行为

下方面板不显示播放进度了，只能到播放详情里去调整

### Lx Music 版本

2.0.2

### 操作系统版本

macOS monterey

**Comment by lyswhut** [comment]
看：<https://github.com/lyswhut/lx-music-desktop/issues/1135>
