### ISSUE TITLE
[Feature]: 希望歌单列表添加排序或者拖动调整顺序功能(名称、变动时间等)

### ISSUE THREAD

**Issue by 26038874** [lyswhut/lx-music-desktop#1112]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在建完歌单以后顺序就不能变了，所以希望能增加一个排序或者拖动调整顺序功能。
或许这个功能很多人用不到，如果容易添加真心能加上，拜谢！！！
![image](https://user-images.githubusercontent.com/33414109/210952717-caf3a864-b747-40fc-8218-d382789490d7.png)

### 描述你想要的解决方案

我没做过类似功能，不知道难不难，没办法分析*.*

**Comment by lyswhut** [comment]
https://lyswhut.github.io/lx-music-doc/desktop/faq/hotkey

> 在我的列表按住<kbd>Ctrl</kbd>键可以进入列表拖动模式，此时可以用鼠标拖动列表调整列表的位置

**Comment by 26038874** [comment]
原来这样用的，感谢

**Comment by a81n9** [comment]
> https://lyswhut.github.io/lx-music-doc/desktop/faq/hotkey
> 
> > 在我的列表按住Ctrl键可以进入列表拖动模式，此时可以用鼠标拖动列表调整列表的位置

@lyswhut 移动端要如何操作才能调整歌单顺序呢

**Comment by lyswhut** [comment]
目前移动端不支持调整歌单顺序，临时方案是，连接同步服务后，在PC调整同步到移动端

**Comment by a81n9** [comment]
> 目前移动端不支持调整歌单顺序，临时方案是，连接同步服务后，在PC调整同步到移动端

好吧，感谢大佬解答
