### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by 17356282982** [lyswhut/lx-music-desktop#1113]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

2.0.2更新完之后，播放进度条虽然有三种样式可选，但希望留着1.几老版本那样的样式，增加“原始”这样的选项；另一个就是声音按钮，现在调声音需要两步，没有之前那样方便，鼠标右键静音也被取消了，希望有原始样式可选；最后很开心的就是在播放设置中加入了定时暂停，类似于移动端的定时，挺好的，就是有点难找，有点像隐藏功能的感觉，希望能够作为一个闹钟功能放在播放详情页。
最后祝洛雪在新的一年里越来越好用，感谢作者带给大家这么一款纯粹的听歌软件！

### 描述你想要的解决方案

希望能够优化

**Comment by lyswhut** [comment]
这里的界面改动相对较大，慢慢习惯就好，不打算添加旧的样式。
定时播放功能v1.18.0就加了
