### ISSUE TITLE
[Bug]: 播放设置 音频输出 重启后又恢复原来设置

### ISSUE THREAD

**Issue by tangseng8** [lyswhut/lx-music-desktop#1116]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

设置不能保存？

### 实际行为

由于我有多个声卡 在播放器内设置了卡1输出后，再设置卡2输出，在下次重新打开播放器时，仍会使用卡1输出。

### Lx Music 版本

2.0.2

### 操作系统版本

win11  22H2

**Comment by lyswhut** [comment]
已在v2.0.3修复
