### ISSUE TITLE
[Bug]: kali操作系统上仍无法正常打开lx-music

### ISSUE THREAD

**Issue by zhengrui2233** [lyswhut/lx-music-desktop#1117]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装正常后可以打开
(beta版)

### 实际行为

![390a6f1fd7b88eed](https://user-images.githubusercontent.com/113534080/211129089-709a723b-a007-45f2-865e-1a0525d8218c.png)
![-2b3b657a1669b0c0](https://user-images.githubusercontent.com/113534080/211129095-9306fa5e-95e6-472f-964b-8ad37044f00d.png)
无反应,无法正常打开
我并已确认读过uos及ubuntu那两篇文章其中的更新beta链接已安装，仍无法正常使用

### Lx Music 版本

2.0.3beta

### 操作系统版本

kali GNU/linux rolling arm64

**Comment by lyswhut** [comment]
我在虚拟机装的可以运行，x64 deb的包没问题，你系统问题，尝试用命令行启动看看输出的日志

![image](https://user-images.githubusercontent.com/20365169/211132740-b3161c19-6f63-4a93-96c0-9ee044154a9f.png)

**Comment by zhengrui2233** [comment]
> 
已解决问题原因，矛头指向Chrome的sandbox沙盒模式
在软件的工作目录后缀加上--no-sandbox 使用无沙盒模式运行即可

**Comment by zhengrui2233** [comment]
可以供其他的用户进参考

**Comment by lyswhut** [comment]
以root身份运行程序时需要 `--no-sandbox` 参数，解决了就关了吧

**Comment by zhengrui2233** [comment]
ok



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月07日 21:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [lyswhut/lx-music-desktop] [Bug]: kali操作系统上仍无法正常打开lx-music (Issue #1117) |

以root身份运行程序时需要 --no-sandbox 参数，解决了就关了吧
