### ISSUE TITLE
[Feature]: 希望能添加本地AIFF格式的音乐

### ISSUE THREAD

**Issue by Linqing0808** [lyswhut/lx-music-desktop#1119]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

AIFF和WAV是同一级别的音乐格式，相比WAV，AIFF因支持ID3标签而被广大音乐发烧友用此格式保存无损音乐

### 描述你想要的解决方案

希望在下一个版本支持这个格式，谢谢！

**Comment by lyswhut** [comment]
播放音乐使用的是web audio，其支持的格式我是参考百科的：https://en.wikipedia.org/wiki/HTML5_audio

**Comment by Linqing0808** [comment]
AIFF不在支持列表内，也就是说无法支持AIFF，可惜了，本人本地的音乐都是AIFF格式的

**Comment by 1551362798** [comment]
安卓版好像无法播放wav格式，请教以下
