### ISSUE TITLE
添加列表文字可选中复制的功能

### ISSUE THREAD

**Issue by JamesY-Jey** [lyswhut/lx-music-desktop#112]
能不能添加文字可复制的功能，方便搜索，就不用敲键盘啦 （懒人专用 0.0）

**Comment by lyswhut** [comment]
哪里的文章复制功能？
搜索框是可以复制粘贴文字的，点击下面正在播放的歌曲标题也可以复制当前播放歌曲名

**Comment by jyuan15** [comment]
同样情况，win10 64位版，搜索框内点右键不弹出菜单，只能ctrl+c操作，“点击下面正在播放的歌曲标题”也没有复制到内容。

**Comment by lyswhut** [comment]
搜索框只支持快捷键复制粘贴，点击播放进度条上的歌曲标题可以复制当前播放的歌曲名字

**Comment by JamesY-Jey** [comment]
> 哪里的文字复制功能？
> 搜索框是可以复制粘贴文字的，点击下面正在播放的歌曲标题也可以复制当前播放歌曲名

比如可以复制歌手名，可以在搜索列表中复制文字。这种更人性化一点

**Comment by lyswhut** [comment]
@JamesY-Jey 这主意不错，可以选中列表里的歌曲名、歌手名、专辑名来复制

**Comment by lyswhut** [comment]
该功能已在`0.12.0`加入
