### ISSUE TITLE
[Bug]: 2.0.3版本遇到的新问题

### ISSUE THREAD

**Issue by GoldTest** [lyswhut/lx-music-desktop#1124]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

1，原来已有的同步失效了，局域网无法同步，前几个版本都是好的，我还没试手机版卸载重试，一会儿试试

2，win11 任务栏鼠标悬浮，切换上下曲没有了

### 实际行为

如上

### Lx Music 版本

2.0.3

### 最后正常的版本

2.0.2

### 操作系统版本

win11

**Comment by lyswhut** [comment]
1、引用自v2.0.0更新日志：


> ### 不兼容性变更说明
> 
> - 数据迁移，升级此版本时，会使用旧版本的我的列表、下载设置、快捷键设置、自定义源等数据会自动迁移到新的数据格式版本，旧的数据仍然会保留，但下载列表的数据不做迁移
> - 备份文件，v2.0.0及以后版本导出的列表、配置不支持导入v2.0.0之前版本，但v2.0.0之前版本导出的列表、配置支持导入v2.0.0以及以后版本（移动端需v0.15.0起才支持导入PC端v2生成的备份数据）
> - 同步功能，该功能不支持与移动端v1.0.0之前版本的使用，需等待后面的新版移动端，目前移动端v1的开发工作已在进行中
> 

2、尝试重启软件，资源管理器被重启后按钮会消失，需要重启软件才能恢复，electron的bug，暂时无法解决
