### ISSUE TITLE
[Feature]: 增加调音器建议

### ISSUE THREAD

**Issue by OrbitGW** [lyswhut/lx-music-desktop#1127]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

已经Star了，用了快有3年了，很喜欢这款播放器，希望能增加调音功能。已经Star了

### 描述你想要的解决方案

已经Star了，用了快有3年了，很喜欢这款播放器，希望能增加调音功能。已经Star了

### 描述你考虑过的替代方案

已经Star了，用了快有3年了，很喜欢这款播放器，希望能增加调音功能。已经Star了

### 附加信息

已经Star了，用了快有3年了，很喜欢这款播放器，希望能增加调音功能。已经Star了

**Comment by liao1714** [comment]
我和你想法一样，不过我有自己的音效文件

**Comment by OrbitGW** [comment]
@liao1714 我现在找到替代方案了，其实可以使用FxSound，这个软件挺不错，只是原来要付费，现在免费了
