### ISSUE TITLE
对lx-music的几点建议

### ISSUE THREAD

**Issue by yzq0419** [lyswhut/lx-music-desktop#1128]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

1、设置页面，2.03的设置改版了，虽然可以更准确快速的到达需要的设置项，但是没有鼠标一直滚动时有感觉，
可否实现设置界面左侧为导航项，右侧为长的页面，像以前那样所有设置项在一个页面，鼠标滚轮可以从上一直滚到设置的最后，同时也可以鼠标点击左侧导航项，快速到达设置。
2、播放进度条隐藏，能否继续保留进度条一直显示，可以采用两种方式，允许用户选择设置。
3.版本2.几界面颜色有点浅，最左侧搜索、歌单那一列区域，建议像1.几版本时那样，背景颜色深点，现在选择绿意盎然，界面颜色不明显。

### 描述你想要的解决方案

1、设置页面，2.03的设置改版了，虽然可以更准确快速的到达需要的设置项，但是没有鼠标一直滚动时有感觉，
可否实现设置界面左侧为导航项，右侧为长的页面，像以前那样所有设置项在一个页面，鼠标滚轮可以从上一直滚到设置的最后，同时也可以鼠标点击左侧导航项，快速到达设置。
2、播放进度条隐藏，能否继续保留进度条一直显示，可以采用两种方式，允许用户选择设置。
3.版本2.几界面颜色有点浅，最左侧搜索、歌单那一列区域，建议像1.几版本时那样，背景颜色深点，现在选择绿意盎然，界面颜色不明显。

### 描述你考虑过的替代方案

1、设置页面，2.03的设置改版了，虽然可以更准确快速的到达需要的设置项，但是没有鼠标一直滚动时有感觉，
可否实现设置界面左侧为导航项，右侧为长的页面，像以前那样所有设置项在一个页面，鼠标滚轮可以从上一直滚到设置的最后，同时也可以鼠标点击左侧导航项，快速到达设置。
2、播放进度条隐藏，能否继续保留进度条一直显示，可以采用两种方式，允许用户选择设置。
3.版本2.几界面颜色有点浅，最左侧搜索、歌单那一列区域，建议像1.几版本时那样，背景颜色深点，现在选择绿意盎然，界面颜色不明显。

### 附加信息

1、设置页面，2.03的设置改版了，虽然可以更准确快速的到达需要的设置项，但是没有鼠标一直滚动时有感觉，
可否实现设置界面左侧为导航项，右侧为长的页面，像以前那样所有设置项在一个页面，鼠标滚轮可以从上一直滚到设置的最后，同时也可以鼠标点击左侧导航项，快速到达设置。
2、播放进度条隐藏，能否继续保留进度条一直显示，可以采用两种方式，允许用户选择设置。
3.版本2.几界面颜色有点浅，最左侧搜索、歌单那一列区域，建议像1.几版本时那样，背景颜色深点，现在选择绿意盎然，界面颜色不明显。

**Comment by lyswhut** [comment]
1、设置连续滚动有时间再看情况做，现在设置项太多了，一下子渲染太多内容会卡顿，所以做了设置单独分类，后面有时间做虚拟列表再说
2、看<https://github.com/lyswhut/lx-music-desktop/issues/1135>
3、通过自定义主题功能可以调出v1的皮肤，左侧的导航颜色可以通过将应用背景色调成之前的主题色，侧栏按钮颜色调浅，之前的主题色值可以在“主题色”的预置颜色中复制过去，具体需要你去摸索
