### ISSUE TITLE
[Bug]: 缓存信息似乎有bug

### ISSUE THREAD

**Issue by Hugo342523** [lyswhut/lx-music-desktop#1129]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在2.0更新日志中，本地歌曲的歌词是这样描述的：“优先尝试读取相同路径下的同名歌词文件，若文件不存在则尝试读取歌曲文件内的歌词，若还是找不到歌词则尝试利用换源功能获取在线歌词”。

### 实际行为

我升级到了2.0.3，清理了所有缓存，然后导入了一些本地歌曲文件（是之前在落雪下载的，嵌入歌词）到收藏列表，也添加了一些线上歌曲到收藏列表。
然后我播放了4首本地歌曲，1首线上歌曲，然后查看了缓存信息如下，这些缓存文件的数目似乎并不符合更新日志所述，或者说我我不是很理解。
![image](https://user-images.githubusercontent.com/52653052/211317653-f05992e4-f03a-4471-9f98-883c3e524dfa.png)
换源歌曲信息数量为4，意思是本地歌曲被换源了？是因为软件不能播放我的本地音乐，还是不能读取内嵌歌词，所以去匹配网络资源了？
歌曲URL数量：1，这里没毛病。
歌词数量：11，这里，我在刚播放4首本地歌曲的时候是歌词数量8，为什么会加倍？再播放1首线上歌曲，就变成了11，多出来3算不过来。

### Lx Music 版本

2.0.3

### 最后正常的版本

无

### 操作系统版本

版本	Windows 10 家庭中文版 版本号	22H2 安装日期	‎2020/‎12/‎18 操作系统内部版本	19045.2364 体验	Windows Feature Experience Pack 120.2212.4190.0

### 附加信息

当然了，这个小问题并不影响使用，只是强迫症的我，测试时很疑惑，不理解。大佬看心情回吧。

**Comment by lyswhut** [comment]
上面的所有数据都是统计的数据总数，不代表播放的歌曲数量
- 换源歌曲信息：指从其他源搜索匹配到的相同歌曲，每首歌能自动匹配到多少条数据完全取决于各平台歌曲与当前播放歌曲信息的匹配度，每首歌最多从单个源匹配一条数据
- 歌曲URL数量：获取成功的所有歌曲URL数量，若URL失效刷新后会替换旧的URL
- 歌词数量：每首歌包含四种类型的歌词（LRC歌词、翻译歌词、罗马音歌词、逐字歌词），这取决于播放歌曲所属源是否支持获取到相应歌词，若支持但歌词为空也会被记录在内，例如某个源支持同时获取四种歌词，但是这首歌没有翻译、罗马音歌词，这时缓存数量也将会增加四条记录
