### ISSUE TITLE
音乐无法播放

### ISSUE THREAD

**Issue by FrameJack** [lyswhut/lx-music-desktop#113]
**描述错误**
QQ音乐播放不了，网易云音乐搜索不了

**重现**
重现行为的步骤：
随便搜索歌曲都不行

**预期行为**
希望能击视修复

**Comment by lyswhut** [comment]
1、之前QQ源接口挂了，所以暂时屏蔽掉QQ的播放与下载
2、经测试网易是可以搜索的

**Comment by FrameJack** [comment]
哦哦，好吧，现在好像就酷我可以用了，其他的接口呀么只能搜，不能听或者下载

**Comment by lyswhut** [comment]
看https://github.com/lyswhut/lx-music-desktop/issues/78

**Comment by FrameJack** [comment]
ok，但是qq音乐和咕米啥时候能修复啊

**Comment by lyswhut** [comment]
预计下个版本，年前发布

**Comment by FrameJack** [comment]
好的，辛苦了，大佬
