### ISSUE TITLE
[Bug]: 个性化的背景图片无法完全显示

### ISSUE THREAD

**Issue by user12133** [lyswhut/lx-music-desktop#1130]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

个性化背景图片能正常完全显示，而不是仅仅左侧竖列区域显示

### 实际行为

基本设置-主题颜色-添加主题-背景图片  
个人添加的背景图片无法像前几个系统默认的主题（以新年快乐，近墨者黑等为例），个人选择的背景图片仅能在最左侧的竖列框区域显示，而剩下部分为默认颜色，无法显示个人选择的图片.详情图片显示。（个性化背景图片在选择保存后仅有一瞬间成功显示，随后变消失）

### Lx Music 版本

2.0.3

### 操作系统版本

windows10

### 附加信息

![正常背景情况](https://user-images.githubusercontent.com/122358012/211525681-b818d802-fe21-46ba-b87b-d1407aeddf25.png)
![个性化背景图仅仅瞬间正常，随后失效](https://user-images.githubusercontent.com/122358012/211525853-8d83d0b2-0f08-4d8b-8a8a-3ee702e569df.png)
![失效后的背景图情况](https://user-images.githubusercontent.com/122358012/211525906-342fdfb0-5997-4988-a5f7-5884833d7da8.png)

**Comment by lyswhut** [comment]
拖动调色盘右侧的透明度滑块即可调整透明度，自己慢慢摸索

**Comment by JinwangSang** [comment]
![8966b7e1ffb059beae271afbedd6bbf](https://github.com/lyswhut/lx-music-desktop/assets/65043588/76e97d87-e30e-45d1-a72f-4883dccb586a)
![a695fb12c44d2fd0dcd6862cd39ff19](https://github.com/lyswhut/lx-music-desktop/assets/65043588/51d4504a-2339-4cf2-8fa6-a77112cba41d)
调节到自己合适的就好啦
