### ISSUE TITLE
[Feature]: 添加本地歌曲到软件中

### ISSUE THREAD

**Issue by fxy591** [lyswhut/lx-music-desktop#1131]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有些歌曲搜索不到，希望可以播放本地文件夹中的歌曲

### 描述你想要的解决方案

有些歌曲搜索不到，希望可以播放本地文件夹中的歌曲

**Comment by lyswhut** [comment]
引用自v2.0.0更新日志：

> 新增将本地歌曲添加到我的列表的支持，此功能可以在列表的右击菜单中使用（本地歌曲的歌词优先尝试读取相同路径下的同名歌词文件，若文件不存在则尝试读取歌曲文件内的歌词，若还是找不到歌词则尝试利用换源功能获取在线歌词，歌曲封面则是尝试读取歌曲文件内的封面，若不存在则利用换源功能获取在线封面）
