### ISSUE TITLE
[Feature]: 体验优化

### ISSUE THREAD

**Issue by ygq-704292061** [lyswhut/lx-music-desktop#1133]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

搜索歌手不能在搜索列表进行列表播放，需要一个一个点

### 描述你想要的解决方案

类似加入歌单一样  加入列表播放按钮  或者列表右键加入列表播放

**Comment by lyswhut** [comment]
搜索列表可能会有几十上百页，而且里面的歌曲大多是重复的，一键添加意义不大，所以不会做一键播放功能，手动使用多选功能选取想要播放的歌曲添加到列表播放即可
