### ISSUE TITLE
[Feature]: 一美化相关的建议

### ISSUE THREAD

**Issue by hellobigbug** [lyswhut/lx-music-desktop#1134]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

播放背景随主题纯色

### 描述你想要的解决方案

使用高斯模糊的专辑封面取色

**Comment by lyswhut** [comment]
不打算实现播放背景随封面变换的功能，与LX的风格不符
