### ISSUE TITLE
[Feature]: 希望恢复在应用首页、搜索、设置等界面允许调整歌曲进度

### ISSUE THREAD

**Issue by wuai-ui** [lyswhut/lx-music-desktop#1135]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前不支持在首页拖动歌曲进度，还需要进入到歌曲详情页，不方便使用
目前的这个位置应该是被歌词占用，但在实际使用中，很少将此界面一直置顶，大部分时候想看歌词时，直接使用桌面歌词功能
目前的功能较为鸡肋，而且因此功能还取消了音乐拖动条，希望采纳优化。
![image](https://user-images.githubusercontent.com/83076773/212284259-087585d0-2361-4adc-a924-8984dcca83ae.png)

### 描述你想要的解决方案

希望可以恢复之前的音乐进度条展示，支持拖动。
![image](https://user-images.githubusercontent.com/83076773/212285089-a45969ff-86de-465a-a68a-c19d36e527ab.png)

### 描述你考虑过的替代方案

支持界面拖动音乐进度

**Comment by lyswhut** [comment]
引用自v2.0.0更新日志：

> 新增设置-基本设置-播放栏进度条样式设置（此版本默认使用迷你进度条样式，对于某些不喜欢该样式的人可以将其换成其他样式）

迷你进度条模式下会在播放时间下显示淡淡的小进度条，鼠标移动到播放时间上会弹出大的进度条

**Comment by 442712243** [comment]
我也是一样问题，哈哈原来在设置改为中等就好了

**Comment by freebomb110** [comment]
> 我也是一样问题，哈哈原来在设置改为中等就好了

哈哈，感谢！
