### ISSUE TITLE
[Feature]: 你好

### ISSUE THREAD

**Issue by NONGSHENGBAO** [lyswhut/lx-music-desktop#1137]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

就是希望可以有一个类似个性电台的功能，根据你听的歌推荐类似的歌曲的一个电台之类的东西，嗯，衷心的感谢！

### 描述你想要的解决方案

就是希望可以有一个类似个性电台的功能，根据你听的歌推荐类似的歌曲的一个电台之类的东西，嗯，衷心的感谢！

### 附加信息

再次衷心的感谢你们一直以来对洛雪付出的努力。

**Comment by lyswhut** [comment]
重复：
- https://github.com/lyswhut/lx-music-desktop/issues/915
- https://github.com/lyswhut/lx-music-desktop/issues/1037
