### ISSUE TITLE
[Feature]: 聚合搜索准确性有待提高

### ISSUE THREAD

**Issue by Alantemper** [lyswhut/lx-music-desktop#1138]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

聚合搜索中歌曲歌手往往不是原版在上，其他源则正常。

### 描述你想要的解决方案

可以参考Listen1整合搜索方案，提升搜索准确性，整合所有搜索结果

**Comment by lyswhut** [comment]
由于聚合搜索会对所有搜索结果进行排序，因此想要提高准确性则需要将歌曲名 歌手名都输进去搜索，不要单单搜歌曲名

**Comment by ifwlzs** [comment]
> 由于聚合搜索会对所有搜索结果进行排序，因此想要提高准确性则需要将歌曲名 歌手名都输进去搜索，不要单单搜歌曲名

聚合搜索按照【歌手名 歌曲名】搜索的结果没有【歌曲名 歌手名】的精准，有没有考虑支持【歌手名 歌曲名】的精准搜索


【歌手名 歌曲名】搜索

![image](https://github.com/lyswhut/lx-music-desktop/assets/49548316/98cae39e-6722-4f1e-9b54-50b99f999e24)

---

【歌曲名 歌手名】搜索

![image](https://github.com/lyswhut/lx-music-desktop/assets/49548316/7dc7b223-67bf-4dd6-a040-38695a10ae66)
