### ISSUE TITLE
deepin uos RC最新版安装报错，安装成功无法启动软件

### ISSUE THREAD

**Issue by hbhgwtf** [lyswhut/lx-music-desktop#114]
安装输出信息：

正在选中未选择的软件包 lx-music-desktop。
(正在读取数据库 ... 系统当前共安装有 199023 个文件和目录。)
准备解压 lx-music-desktop.v0.13.0.x64.deb  ...
正在解压 lx-music-desktop (0.13.0-44) ...
正在设置 lx-music-desktop (0.13.0-44) ...
Could not parse file "/usr/share/applications/screensavers/glitchpeg.desktop": Key file contains line ?several times a second.  After a while, finds a new image to corrupt. Written by Jamie Zawinski; 2018.? which is not a key-value pair, group, or comment
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 lastore-daemon (5.0.3-1) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-4) 的触发器 ...
正在处理用于 bamfdaemon (0.5.4-1) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 mime-support (3.62) 的触发器 ...

安装后双击图标无法启动软件。

**Comment by lyswhut** [comment]
问题解决了吗？如果已解决能否写下解决的方法呢？

**Comment by hbhgwtf** [comment]
我最开始是安装的v0.13.1.x64.deb 版本的，无法启动程序，后来覆盖安装v0.13.0.x64.deb 版本的还是无法启动，再后来我又试了一下把程序先卸载了，再安装v0.13.0.x64.deb 版本的，又可以正常启动和使用了。在以上安装过程中都会输出    Could not parse file "/usr/share/applications/screensavers/glitchpeg.desktop": Key file contains line ?several times a second. After a while, finds a new image to corrupt. Written by Jamie Zawinski; 2018.? which is not a key-value pair, group, or comment  这段文字。

**Comment by hbhgwtf** [comment]
> 问题解决了吗？如果已解决能否写下解决的方法呢？

我最开始是安装的v0.13.1.x64.deb 版本的，无法启动程序，后来覆盖安装v0.13.0.x64.deb 版本的还是无法启动，再后来我又试了一下把程序先卸载了，再安装v0.13.0.x64.deb 版本的，又可以正常启动和使用了。在以上安装过程中都会输出 Could not parse file "/usr/share/applications/screensavers/glitchpeg.desktop": Key file contains line ?several times a second. After a while, finds a new image to corrupt. Written by Jamie Zawinski; 2018.? which is not a key-value pair, group, or comment 这段文字。

**Comment by lyswhut** [comment]
@hbhgwtf `0.13.0`使用的electron版本是`7.1.5`，但该版本的更新有问题（仅影响windows安装版），而`0.13.1`的electron版本是`7.1.2`。
至于为什么显示那段文字我也不清楚，或许可以更新系统软件试试？

**Comment by hbhgwtf** [comment]
嗯嗯，目前这个系统还在内测阶段，还存在一些问题，估计后续会完善解决，目前0.13.0版本可以使用，问题不大，谢谢大佬啦！
