### ISSUE TITLE
[Bug]: 程序源代码中的一些英文单词拼写错误 ， Debian lintian 检查发现

### ISSUE THREAD

**Issue by atzlinux** [lyswhut/lx-music-desktop#1141]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

对 lx-music-desktop-v2.0.4-x64.deb 软件包进行 Debian 的 lintian 质量检查，就 源代码 单词拼写错误方面，有发现如下问题：

I: lx-music-desktop: spelling-error-in-binary "allow to" "allow one to" [opt/lx-music-desktop/libffmpeg.so]
I: lx-music-desktop: spelling-error-in-binary "allow to" "allow one to" [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary "allows to" "allows one to" [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary "an other" "another" [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Buil Build [opt/lx-music-desktop/libvk_swiftshader.so]
I: lx-music-desktop: spelling-error-in-binary Controll Control [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Futher Further [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary IiF If [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Inseperable Inseparable [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Messanger Messenger [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Nam Name [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Optio Option [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Pres Press [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Protoype Prototype [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Recevied Received [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Reciever Receiver [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Transciever Transceiver [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary UNKOWN UNKNOWN [opt/lx-music-desktop/libGLESv2.so]
I: lx-music-desktop: spelling-error-in-binary UNKOWN UNKNOWN [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary Unknow Unknown [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary abandonded abandoned [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary accessable accessible [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary adapater adapter [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary afterAll after all [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary aquisition acquisition [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary attachements attachments [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary avaliable available [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary befor before [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary commmited committed [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary convertor converter [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary dimentions dimensions [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary does't doesn't [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary dont don't [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary entrys entries [opt/lx-music-desktop/libvulkan.so.1]
I: lx-music-desktop: spelling-error-in-binary enty entry [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary explicitely explicitly [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary explict explicit [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary fullfilled fulfilled [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary implemention implementation [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary inconsistenly inconsistently [opt/lx-music-desktop/libGLESv2.so]
I: lx-music-desktop: spelling-error-in-binary inconsistenly inconsistently [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary ment meant [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary negotation negotiation [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary occured occurred [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary ofthe of the [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary overriden overridden [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary paramters parameters [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary poluting polluting [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary refered referred [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary reponse response [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary retrive retrieve [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary segement segment [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary seperator separator [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary specifed specified [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary suport support [opt/lx-music-desktop/libGLESv2.so]
I: lx-music-desktop: spelling-error-in-binary unrecogized unrecognized [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary upto up to [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary userA users [opt/lx-music-desktop/lx-music-desktop]
I: lx-music-desktop: spelling-error-in-binary vaule value [opt/lx-music-desktop/libGLESv2.so]
I: lx-music-desktop: spelling-error-in-binary withthe with the [opt/lx-music-desktop/lx-music-desktop]

建议全局搜索源代码，进行核实和修正。

谢谢！

### 实际行为

希望没有单词检查报错

### Lx Music 版本

2.0.4

### 操作系统版本

Debian 11 atzlinux 11.6

**Comment by lyswhut** [comment]
LX是基于Electron开发，这些问题是Chromium/Electron那边的问题，与本项目所写的代码无关
