### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by xivi1839** [lyswhut/lx-music-desktop#1142]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

排行榜可以添加Spotify的歌曲吗，希望多增加点海外和国际排行榜，

### 描述你想要的解决方案

.

### 描述你考虑过的替代方案

.

### 附加信息

.

**Comment by lyswhut** [comment]
目前仅支持国内的几大平台，其他平台暂不打算支持
