### ISSUE TITLE
[Bug]: 版本1.223中下载一栏可以显示已下载歌曲，2.04版本中下载一栏中所有歌曲都没有了

### ISSUE THREAD

**Issue by itok001** [lyswhut/lx-music-desktop#1144]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

如何找回已下载歌曲

### 实际行为

下载列表丢失，如何让已下载内容显示在列表中

### Lx Music 版本

2.04

### 操作系统版本

windows 10

**Comment by lyswhut** [comment]
应用自v2.0.0更新日志：

> ### 不兼容性变更说明
> 数据迁移，升级此版本时，会使用旧版本的我的列表、下载设置、快捷键设置、自定义源等数据会自动迁移到新的数据格式版本，旧的数据仍然会保留，但下载列表的数据不做迁移
> 备份文件，v2.0.0及以后版本导出的列表、配置不支持导入v2.0.0之前版本，但v2.0.0之前版本导出的列表、配置支持导入v2.0.0以及以后版本（移动端需v0.15.0起才支持导入PC端v2生成的备份数据）
> 同步功能，该功能不支持与移动端v1.0.0之前版本的使用，需等待后面的新版移动端，目前移动端v1的开发工作已在进行中

> ### 新增
> - 新增将本地歌曲添加到我的列表的支持，此功能可以在列表的右击菜单中使用（本地歌曲的歌词优先尝试读取相同路径下的同名歌词文件，若文件不存在则尝试读取歌曲文件内的歌词，若还是找不到歌词则尝试利用换源功能获取在线歌词，歌曲封面则是尝试读取歌曲文件内的封面，若不存在则利用换源功能获取在线封面）

自行使用添加本地歌曲功能添加到我的列表
