### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by yongbaoweiai** [lyswhut/lx-music-desktop#1145]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

下载功能显示空白

### 描述你想要的解决方案

希望能添加下载功能

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/980
