### ISSUE TITLE
[Bug]: 随机播放模式下,选择某首歌“稍后播放”,会进入单曲循环

### ISSUE THREAD

**Issue by moment00** [lyswhut/lx-music-desktop#1147]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

 “稍后播放”不影响到原本的播放模式

### 实际行为

随机播放模式下,选择某一首歌“稍后播放”,这首歌会进入单曲循环

### Lx Music 版本

2.04

### 操作系统版本

win10

**Comment by lyswhut** [comment]
已在v2.0.5修复
