### ISSUE TITLE
[Bug]: 无法退出app

### ISSUE THREAD

**Issue by glamout** [lyswhut/lx-music-desktop#1148]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

macOs Ventura 13.1，乐雪2.0.3/2.0.4.
点击退出菜单，或者使用CMD+Q，乐雪应该完全关闭退出。

### 实际行为

点击退出菜单，或者使用CMD+Q，乐雪只是隐藏并停止播放了，但是没有关闭退出窗口。
仍然驻留在launch pad上，点击即可切换到乐雪窗口。
只有通过内存管理工具杀掉乐雪进程才能完全退出乐雪。
此现象应该是在2.0.x的某个版本后出现的，之前没有这个问题。

### Lx Music 版本

2.0.4

### 最后正常的版本

不确定

### 操作系统版本

macOS Ventura 13.1 （M1）

**Comment by lyswhut** [comment]
已在v2.0.5修复

**Comment by glamout** [comment]
已更新2.0.5，谢谢，辛苦了，春节开心。

**Comment by marble-lai** [comment]
macOs 12.6.3更新到2.1.2仍存在cmd+q残留托盘/程序坞的问题，需在托盘/程序坞右键点击退出才能正常退出
