### ISSUE TITLE
[Bug]: 菜单内容浏览位置记忆不全

### ISSUE THREAD

**Issue by realSilasYang** [lyswhut/lx-music-desktop#1149]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在切换 “歌单”“排行榜”“下载”“设置”“搜索”“我的列表”菜单时，上次浏览到的位置应该被记忆

### 实际行为

菜单切换后只有“搜索”“我的列表”的上次浏览位置会保留， “歌单”“排行榜”“下载”“设置”菜单下内容刚才浏览到的进度将重置为最顶端，需要重新翻。

### Lx Music 版本

2.04

### 操作系统版本

Windows 11 专业版 22H2 22621.963

**Comment by lyswhut** [comment]
只有我的列表中的每个列表会有记住滚动位置功能，这是LX从 v0.x 版本一直延续到现在的功能，并且可以去设置-列表设置关闭这个特性，除此之外其他地方都没做过记住滚动位置的功能，现在也暂时不打算做
