### ISSUE TITLE
[BUG]:   只能下载小蜗里面的音乐，其他的下载不了啊 

### ISSUE THREAD

**Issue by sylAdmin** [lyswhut/lx-music-desktop#1152]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![image](https://user-images.githubusercontent.com/87472947/213437670-30a1a6b9-bdf7-4764-8753-0d8b826f805a.png)
只能下载小蜗里面的音乐，其他的下载不了啊

### 实际行为

![image](https://user-images.githubusercontent.com/87472947/213437670-30a1a6b9-bdf7-4764-8753-0d8b826f805a.png)
只能下载小蜗里面的音乐，其他的下载不了啊

### Lx Music 版本

2.0.5

### 操作系统版本

windows10

### 附加信息

![image](https://user-images.githubusercontent.com/87472947/213437892-c2a8f34d-fa3d-4545-b1b7-2652253da8b6.png)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/209
