### ISSUE TITLE
[Feature]: 可不可以增加多选，

### ISSUE THREAD

**Issue by GW00181018** [lyswhut/lx-music-desktop#1154]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

一个一个下载歌曲太麻烦，能不能增加一个多选，一键下载

### 描述你想要的解决方案

增加一个选择项

### 描述你考虑过的替代方案

无

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1024
