### ISSUE TITLE
[Bug]: 更新2.0.5 不让下载歌

### ISSUE THREAD

**Issue by PuraIgnis** [lyswhut/lx-music-desktop#1158]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

更新2.0.5 不让下载歌

### 实际行为

更新2.0.5 不让下载歌

### Lx Music 版本

2.0.5

### 最后正常的版本

我忘了

### 操作系统版本

Windows10

### 附加信息

我更新完突然什么歌都不能下载。下载按钮也不知道去哪儿了。 请你看看有什么问题。

https://imgur.com/a/gaH2vDo

**Comment by Tyer-GHM** [comment]
我的也是 可不可以回归到以前的版本呢

**Comment by NestorRay** [comment]
> #209 

参阅 #209，如无问题请关闭issue

**Comment by PuraIgnis** [comment]
> 

好的能下载了，不过我还是喜欢以前的 UI 

https://imgur.com/a/KzqszDL

**Comment by Tyer-GHM** [comment]
> > 
> 
> 好的能下载了谢谢，不过我还是喜欢以前的 UI
> 
> https://imgur.com/a/KzqszDL

可以问一下 您是怎么弄出来下载按钮的吗 我转到测试接口了 下载按钮还是出不来

**Comment by PuraIgnis** [comment]
> 
只有右键单击(right click)你要下载的歌才可以下载。以前的下载按钮好像被开发者移除了。

**Comment by Tyer-GHM** [comment]
刚刚发现了 谢谢嗷

**Comment by NestorRay** [comment]
> > 
> 
> 只有右键单击(right click)你要下载的歌才可以下载。以前的下载按钮好像被开发者移除了。

**未复现，边栏下载选项仍存在**

![Snipaste_2023-01-27_15-55-34](https://user-images.githubusercontent.com/63111566/215038495-590a2a23-9ee5-4c8b-a69c-4dafda244420.png)

**Comment by PuraIgnis** [comment]
问一下，您这是怎么弄的啊？是不是软件有问题？

![image](https://user-images.githubusercontent.com/120215268/215039194-1eacdf1f-b43e-4b1f-9dc1-315601321820.png)

**Comment by NestorRay** [comment]
> 问一下，您这是怎么弄的啊？是不是软件有问题？
> 
> ![image](https://user-images.githubusercontent.com/120215268/215039194-1eacdf1f-b43e-4b1f-9dc1-315601321820.png)


缓存文件夹内缺少设置和数据文件
可根据实际情况**备份歌单和设置数据后**，删除缓存目录并重新安装

> 设置--备份与恢复--所有数据--导出

**若仍无法解决，可开启issue等待开发者回复**

**Comment by PuraIgnis** [comment]
还是没那些按钮。我还是right click下载吧，也没那么多事。

**Comment by PuraIgnis** [comment]
> 引用自v2.0.0更新日志：
> 
> > 列表右侧的操作按钮栏默认不再显示，歌曲的操作可以使用右键菜单代替，若想恢复它们的显示，可以去 设置-列表设置-启用操作按钮栏 开启

Wow! 感谢！
