### ISSUE TITLE
Mac版本导入歌单后无法批量操作，只能一个个加入收藏

### ISSUE THREAD

**Issue by Ennan729** [lyswhut/lx-music-desktop#116]
**描述错误**
网易云歌单导入后，歌曲显示正常，但是无法批量操作。只可以一个一个加入收藏或者试听。

**重现**
1.歌单
2.打开网易云歌单
3.粘贴网址，进入
4.看到错误

**预期行为**
可以批量下载歌单歌曲以及添加收藏

**环境：**
  -操作系统及版本：macOS 10.15.2
  -软件安装包及版本：版本0.13.1 (0.13.1.46)

**Comment by lyswhut** [comment]
可以用批量添加功能，在左侧全选再添加即可

**Comment by Ennan729** [comment]
> 可以用批量添加功能，在左侧全选再添加即可
不好意思，解决了，因为在设置里开启了临时接口，改回测试接口功能就正常了
临时接口下不能批量操作
![截屏2020-01-19下午7.37.18.png](https://i1.wp.com/pic.acgflag.com/2020/01/19/439bb05bf8425.png)
