### ISSUE TITLE
[Bug]: 歌词显示问题

### ISSUE THREAD

**Issue by WSMTBG** [lyswhut/lx-music-desktop#1164]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

看着就很难受...试过调大小间距了没用...
![图片](https://user-images.githubusercontent.com/32087250/215973162-93da71d6-d57b-4d3b-88c0-86b7e2d28164.png)

### 实际行为

勾选显示歌词翻译+显示罗马音+桌面歌词缩放+正在播放歌词滚动位置，会出现第一行桌面歌词顶部一点在框外显示不了
![图片](https://user-images.githubusercontent.com/32087250/215972870-10b0c2dd-1125-4abd-a4d8-e4dfc1ccfbd0.png)
![图片](https://user-images.githubusercontent.com/32087250/215972932-408c7589-cd83-48c7-8524-9b6c373298ef.png)
![图片](https://user-images.githubusercontent.com/32087250/215972995-2f1ce3bc-22e5-4293-9ff5-c96cab661fad.png)

### Lx Music 版本

win 2.0.5

### 操作系统版本

win10 win11

**Comment by lyswhut** [comment]
开启延迟滚动或者关闭歌词缩放都可以解决该问题，出于什么原因不修改这些设的其中一项？

**Comment by WSMTBG** [comment]
> 开启延迟滚动或者关闭歌词缩放都可以解决该问题，出于什么原因不修改这些设置的其中一项？

。。。好看？

**Comment by lyswhut** [comment]
开启置顶不建议开启歌词缩放，歌词被缩放后行高度会变化，甚至被换行，下一句歌词被激活后需要马上触发滚动会导致滚动位置计算有偏移，这种冲突的情况目前不打算处理

**Comment by WSMTBG** [comment]
> 开启置顶不建议开启歌词缩放，歌词被缩放后行高度会变化，甚至被换行，下一句歌词被激活后需要马上触发滚动会导致滚动位置计算有偏移，这种冲突的情况目前不打算处理

好的吧，谢谢
