### ISSUE TITLE
 希望排序功能

### ISSUE THREAD

**Issue by ghl66866** [lyswhut/lx-music-desktop#1166]
点击顶栏歌曲名，艺术家、专辑可以进行排序。搜索出的结果点击歌曲名，艺术家、专辑可以自动搜索显示出相同歌名，艺术家、专辑所有结果。。其实这个功能各大音乐软件都有，参照网易云。

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/863

**Comment by aaaaaaaaaadsfdsfds** [comment]
我也是。
