### ISSUE TITLE
[Bug]: 软件有一圈黑框，字体时不时模糊

### ISSUE THREAD

**Issue by rumosky** [lyswhut/lx-music-desktop#1167]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在4K显示器下，字体清晰，软件背景无一圈黑色的框。

### 实际行为

在4K显示器下，字体模糊，软件背景有一圈黑色的框。

### Lx Music 版本

2.0.5

### 操作系统版本

Windows 11 22H2

### 附加信息

这个字体是时不时的糊，鼠标放上去之后，或者点击的部分，不会糊，但是别的地方会糊。有时候也很清晰，没问题，但只是偶尔，很少的时间。大部分时间都是糊的。

Windows控制面板上的启用ClearType我已经打开了，经测试，只有这个软件和阿里云盘这两个软件会模糊。但是背景有黑框只有落雪有。
![QQ截图20230201233957](https://user-images.githubusercontent.com/41993388/216091216-d0d6be79-7278-4b5e-9961-b400c37c9546.png)

**Comment by lyswhut** [comment]
建议尝试更新显卡驱动看是否能解决，或者你系统缺少了某些更新
重复：<https://github.com/lyswhut/lx-music-desktop/issues/1079>
