### ISSUE TITLE
多选操作问题

### ISSUE THREAD

**Issue by KB3146706** [lyswhut/lx-music-desktop#117]
**描述错误**
某页面多选几首歌后进入下一页，这一页所选的歌曲会取消多选

**重现**
1.随便选择几首歌
2.点击下一页
3.回到刚刚那一页
4.原本被选择的歌曲已没被选中

**预期行为**
搜索结果换页后仍可保留之前的多选记录

**环境：**
Windows 10 64位 18363.592
0.13.1 x64 win 绿版

**其它**
希望能在“多选下载”按钮上显示已选择几首歌曲的数字角标
如果能在合适的位置显示被选中的歌曲列表则更好

**Comment by lyswhut** [comment]
目前不支持跨页选歌，为什么要进行跨页选歌？选完一页后添加歌曲到播放列表，再切到下一页选不行吗？

**Comment by KB3146706** [comment]
> 目前不支持跨页选歌，为什么要进行跨页选歌？选完一页后添加歌曲到播放列表，再切到下一页选不行吗？

比方说需要大批量下同一歌手的歌曲时有跨页选歌就特别方便

**Comment by lyswhut** [comment]
还是没看懂为什么要跨页选，选完一页添加后再到下一页选不行吗？为什么要多页选完再添加呢？

**Comment by KB3146706** [comment]
> 还是没看懂为什么要跨页选，选完一页添加后再到下一页选不行吗？为什么要多页选完再添加呢？

不是添加到播放列表😂是下载

**Comment by lyswhut** [comment]
不也是同理，一页一页选来下跟全部选完后下有什么区别

**Comment by KB3146706** [comment]
> 不也是同理，一页一页选来下跟全部选完后下有什么区别

少点几次下载按钮跟音质按钮

**Comment by lyswhut** [comment]
这会引出怎样清除已选列表等问题，暂不考虑支持跨页选歌，就这样用着先吧
