### ISSUE TITLE
[Bug]: 播放任何歌曲没有响应，只能够搜索

### ISSUE THREAD

**Issue by YLEDE** [lyswhut/lx-music-desktop#1173]
安装之后只能搜索不能播放

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

本来预计可以正常安装就可以正常播放的，结果安装之后只能搜索不能播放
系统：macOS13.1
CPU：M1

### 实际行为

播放任何歌曲没有响应，只能够搜索！

### Lx Music 版本

2.5.0

### 最后正常的版本

2.5.0

### 操作系统版本

macOS13.1

### 附加信息

<img width="1006" alt="截屏2023-02-06 11 57 08" src="https://user-images.githubusercontent.com/103394626/216880686-c8348dba-ab20-479d-b650-985653cc64bb.png">

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1156

**Comment by lyswhut** [comment]
你是从1.x.x直接更新到2.0.5出现的问题吗？还是更新到2.0.0出现的问题？

**Comment by YLEDE** [comment]
@lyswhut 之前的1.22.3版本还能用，后面就用不了了，更新到2.0.0版本之后一直就用不了，都是如上情况！

**Comment by lyswhut** [comment]
你之前使用过2.0.0或2.0.1的版本吗？

**Comment by YLEDE** [comment]
1.x.x版本不行之后更新过，但是一直处于上述情况，这次我看能更新到2.0.5，试用一下，结果还是一样的

**Comment by lyswhut** [comment]
是不是之前刚出2.0.0你更新上去，发现布局退回1.x.x，然后再更新到2.0.5发现还是不行？
你可以将下面那个文件发一下到我的邮箱吗？我想再看看那个有问题的数据库
1. 打开终端输入 `cd ~/Library/Application Support/lx-music-desktop/LxDatas` 回车
2. 然后输入 `open .` 回车，这时应该会打开文件管理器，最后将里面的`lx.data.db`文件发给我邮箱`lyswhut#qq.com`（将#替换成@）

**Comment by YLEDE** [comment]
@lyswhut 你说的这个目录我没有找到

**Comment by lyswhut** [comment]
空格那里可能要加个反斜杠`cd ~/Library/Application\ Support/lx-music-desktop/LxDatas`

**Comment by YLEDE** [comment]
@lyswhut 原来的那个文件就一直是0KB，删除之后安装2.0.5就可以用了，感谢@!!@

**Comment by Alexprprpr** [comment]
同样的mac M1，也是同样的问题，同样通过删除lx.data.db文件解决了
