### ISSUE TITLE
[Bug]: 基本设置点击取消反复多次操作，顶栏出现多个个icon图标

### ISSUE THREAD

**Issue by gegewuwuwu** [lyswhut/lx-music-desktop#1174]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

基本设置中，点击最小化托盘显示不退出，点击取消，顶栏中仅仅显示一个。

### 实际行为

基本设置中，点击最小化托盘显示不退出，点击取消反复操作后，顶栏出现多个icon图标。

### Lx Music 版本

2.0.5

### 最后正常的版本

/

### 操作系统版本

ubuntu 22.04.1 LTS

### 附加信息

[![pSgy5r9.png](https://s1.ax1x.com/2023/02/07/pSgy5r9.png)](https://imgse.com/i/pSgy5r9)

**Comment by lyswhut** [comment]
这是electron的远古bug：

- https://github.com/electron/electron/issues/24976
- https://github.com/electron/electron/issues/34811

electron在v22重新实现了linux的托盘，好像修复了，计划下个版本更新到v22，到时候看看怎么样

**Comment by gegewuwuwu** [comment]
2.1.2 版本已修复
