### ISSUE TITLE
[Bug]: MacOS_M1 没有声音

### ISSUE THREAD

**Issue by Sarmay** [lyswhut/lx-music-desktop#1176]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

播放音乐应该有声音

### 实际行为

音乐播放中但是无声音

### Lx Music 版本

2.0.5

### 操作系统版本

MacOS11.7.3 M1芯片

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/902
