### ISSUE TITLE
[Bug]: macOS 在开启台前调度会导致应用动画掉帧

### ISSUE THREAD

**Issue by Jerry23011** [lyswhut/lx-music-desktop#1178]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

开启台前调度后可以有流畅动画

### 实际行为

在洛雪音乐从主屏幕返回到左边小窗时会出现动画掉帧的情况，在左边小窗口点洛雪音乐app图标也会出现动画掉帧，开启 ProMotion 之后比较明显，但是 60Hz 也能看出来
目前来看可能是 Electron 的问题？因为百度网盘和 Motrix 也有这个bug，但是同样用 Electron 的 Obsidian，阿里云盘和 GitHub Desktop 就没事

### Lx Music 版本

2.0.5

### 操作系统版本

macOS Ventura 13.2

### 附加信息

录屏 1

https://user-images.githubusercontent.com/89069957/218003675-35083582-6eab-4140-9ca7-4520e0f62459.mov

录屏 2

https://user-images.githubusercontent.com/89069957/218003731-df50f8cb-b71b-4fe8-a295-b75ee3c3cb35.mov

**Comment by lyswhut** [comment]
可以试试加启动参数`-dt`运行？

**Comment by Jerry23011** [comment]
❗️
真的不卡顿了，能请教一下这是什么原因吗？

**Comment by lyswhut** [comment]
electron透明窗口的问题，lx默认使用透明窗口启动：https://lyswhut.github.io/lx-music-doc/desktop/run-params

**Comment by Jerry23011** [comment]
> electron透明窗口的问题，lx默认使用透明窗口启动：https://lyswhut.github.io/lx-music-doc/desktop/run-params

非常感谢，那未来可以加一个默认以非透明窗口启动的设置吗？

**Comment by lyswhut** [comment]
没有计划，你可以查一下怎么给mac的快捷方式加启动参数

**Comment by Jerry23011** [comment]
好的，那我就把这个 issue 关掉了，谢谢

**Comment by Anandonzy** [comment]
> 

想问下是`台前调度`启动的时候加 `-dt`么,这个如何启动,又完整的命令么,现在是从顶部下拉框启动的`台前调度`.
非常感谢!
