### ISSUE TITLE
[Feature]:同步功能增添同步音乐源的选项

### ISSUE THREAD

**Issue by ViCh0rs** [lyswhut/lx-music-desktop#1179]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

默认音源均无法正常播放，查询问题列表说是宽带IP被封禁
刚开始出现问题时过几天或者重启光猫可以解决，现在都已行不通
但是我添加的其他音源在PC端可以正常使用

### 描述你想要的解决方案

希望给同步功能增加同步音源的选项
亦或者给手机端添加手动添加音源的选项均可

### 描述你考虑过的替代方案

给手机端添加手动添加音源的选项亦可

**Comment by lyswhut** [comment]
这涉及原生代码实现，我非专业安卓开发人员，目前暂无打算花时间去研究这个，移动端暂无法实现自定义源功能
