### ISSUE TITLE
无法显示UI

### ISSUE THREAD

**Issue by u8989332** [lyswhut/lx-music-desktop#118]
**描述错误**
更新至0.14版，无法显示UI

**重现**
重现行为的步骤：
1. 透过线上更新，无呈现任何UI
2. 透过GITHUB Release下载最新，仍一样状况

**预期行为**
呈现UI

**截图**
https://imgur.com/UOq9Fd4.jpg

**环境：**
  -操作系统及版本：[Windows 10 64位 18363.592]

**其他内容**

**Comment by lyswhut** [comment]
现在有个临时的解决方案：
打开%HOMEPATH%\AppData\Roaming\lx-music-desktop把config.json备份下，然后将其删除即可打开软件

**Comment by lyswhut** [comment]
该问题已在0.14.1修复
