### ISSUE TITLE
[Feature]: 最好增加一个车机版，供大家体验

### ISSUE THREAD

**Issue by junguoguo2017** [lyswhut/lx-music-desktop#1181]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

缺少一个车机版

### 描述你想要的解决方案

安卓版开一个分支，增加一个车机版

**Comment by lyswhut** [comment]
没有时间也没有打算再单独开发车机版，移动版已做了一些适配

**Comment by shwatty** [comment]
同问，移动版的试过了，在车机上无法安装，提示解析包失败，可能是安卓版本低的原因，能否考虑适配一下低版本的安卓呢
