### ISSUE TITLE
[Feature]: 大佬，加一个搜索结果一键播放功能

### ISSUE THREAD

**Issue by 591130877** [lyswhut/lx-music-desktop#1182]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

想听某个歌手的歌，搜索后只能一首一首播放，建议加一个一键播放搜索结果功能。

### 描述你想要的解决方案

无

**Comment by kang24247** [comment]
搜出来 owl city 的歌曲之后，只能点击搜索结果播放，放一首放完就停了，有点难受

**Comment by lyswhut** [comment]
看：<https://lyswhut.github.io/lx-music-doc/desktop/faq/list-play-all>
