### ISSUE TITLE
[Feature]: 在线播放音乐音质为128kbps

### ISSUE THREAD

**Issue by isDaKai** [lyswhut/lx-music-desktop#1183]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

纯萌新,想请教一下在线播放如何达到无损音质
软件内歌曲名称后缀会有24bit或者sq之类的音质提示，但实际播放只有128k
是需要自己更换音源吗？
谢谢了，望大佬能解惑一下

### 描述你想要的解决方案

无

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/180
