### ISSUE TITLE
[Bug]: 歌曲版本

### ISSUE THREAD

**Issue by cc6522992** [lyswhut/lx-music-desktop#1186]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

歌曲版本问题

### 实际行为

有些歌曲播放是说您正在使用的版本即将停止维护，请到应用商店下载最新版

### Lx Music 版本

2.0.5

### 操作系统版本

macOs

**Comment by lyswhut** [comment]
尝试清缓存重试

**Comment by lyswhut** [comment]
此问题应该已得到解决

**Comment by RyeJi43** [comment]
> 尝试去设置-清理歌曲URL保存重试
清理了还是不行

**Comment by RyeJi43** [comment]
之前只有一些歌曲会这样说，现在是所有歌曲都说您正在使用的版本即将停止维护，请到应用商店下载最新版，全部都听不了了
