### ISSUE TITLE
更新pc客户端后“数据同步”功能失效

### ISSUE THREAD

**Issue by LYYZZ** [lyswhut/lx-music-desktop#1188]
在将pc客户端更新到**2.1.0**后
无法与安卓客户端的最新版（即**0.15.5**）进行数据同步
显示连接服务失败“*Connect service failed*”
```
已排除网络连通性以及防火墙问题。
```
![image](https://user-images.githubusercontent.com/41326810/219850956-130b9322-114b-4683-846c-f850749d4dc8.png)
![09C88D8457BFD21B0120D05D3524C7D9](https://user-images.githubusercontent.com/41326810/219850993-643fa6bf-c954-42e7-9380-a40c5a610ae5.jpg)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1103

**Comment by LYYZZ** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1103
