### ISSUE TITLE
[Feature]: 后台播放

### ISSUE THREAD

**Issue by SHIGUANGLIUNIAN** [lyswhut/lx-music-desktop#1191]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

经常顺手按右上角X退出软件

### 描述你想要的解决方案

希望可以添加类似QQ音乐的关闭主面板最小化到托盘，不退出程序

**Comment by matlabsy** [comment]
开发人员 我同样有这样的需求 希望能在Electron应用关闭时 提示用户 是否最小化到托盘运行 希望能够开发此功能
