### ISSUE TITLE
[Bug]: 桌面歌词显示被遮挡

### ISSUE THREAD

**Issue by hongyanpumeng123** [lyswhut/lx-music-desktop#1196]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

桌面歌词正常显示，无遮挡

### 实际行为

桌面歌词显示不完全，在更改进度条时长后，接着的歌词会正常一下，然后就又被遮挡了，垂直方向没啥问题。更改歌词间距无果。
![屏幕截图 2023-02-21 234700](https://user-images.githubusercontent.com/54016193/220396401-edaf4577-b6fa-4c40-8393-6a18843c074d.png)
![屏幕截图 2023-02-21 234734](https://user-images.githubusercontent.com/54016193/220396406-f0905fbb-6c94-449e-b7a7-d694f3f859d7.png)

### Lx Music 版本

2.1.2

### 最后正常的版本

2.0.5

### 操作系统版本

Windows 11 专业版 22H2

### 附加信息

更新后，无进行任何设置更改，尝试换显示字体还是一样的问题。

**Comment by lyswhut** [comment]
完整的歌词设置是怎么样的

**Comment by hongyanpumeng123** [comment]
> 完整的歌词设置是怎么样的

完整的桌面歌词如下（开启项）

- 显示歌词
- 锁定歌词
- 使歌词总是在其他窗口之上
- 自动刷新歌词置顶
- 不允许歌词换行
- 缩放当前播放的歌词
- 逐字歌词
- 水平方向
- 顶部
- 居右（图中为居中）
- 歌词间距12
- 字体 思源黑体 CN

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1164

**Comment by hongyanpumeng123** [comment]
> 重复：#1164

OK，这样确实可以。
不过我将设置里的“正在播放歌词滚动位置”设置为中心，然后将歌词的显示框稍微调整了一下，让其与顶部刚好
对齐，可以暂时解决这个问题
感谢解答。
![屏幕截图 2023-02-23 224751](https://user-images.githubusercontent.com/54016193/220941073-dc56a22f-7773-4feb-8d80-9b9fe13279b8.png)
