### ISSUE TITLE
最小化需求

### ISSUE THREAD

**Issue by wangbaojin1993** [lyswhut/lx-music-desktop#1201]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我想要点击X最小化到后台或者关闭的选项
或者点击最小化到后台  不在任务栏显示

![image](https://user-images.githubusercontent.com/96604745/221072510-62d1ed15-b3b2-4736-a2f3-d0bcd62474f1.png)

### 描述你想要的解决方案

我想要点击X最小化到后台或者关闭的选项
或者点击最小化到后台  不在任务栏显示

### 描述你考虑过的替代方案

我想要点击X最小化到后台或者关闭的选项
或者点击最小化到后台  不在任务栏显示

### 附加信息

我想要点击X最小化到后台或者关闭的选项
或者点击最小化到后台  不在任务栏显示

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/288

**Comment by wangbaojin1993** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
