### ISSUE TITLE
[Bug]: 软件更新会删除portable目录，导致歌单和设置数据丢失

### ISSUE THREAD

**Issue by shana321** [lyswhut/lx-music-desktop#1203]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

从V2.0.5更新到v2.1.2。
方式是下载重新覆盖安装。
预期保留portable目录，继承2.0.5版本的数据

### 实际行为

portable目录被删除，新版本软件数据又重新开在%APPDATA%/lx-music-desktop
旧版本数据丢失

### Lx Music 版本

2.1.2

### 最后正常的版本

2.0.5

### 操作系统版本

WIN10 1909

**Comment by lyswhut** [comment]
你猜这个目录为什么叫 `portable` (
相关问题：
- https://github.com/lyswhut/lx-music-desktop/issues/933#issuecomment-1236259304
- https://github.com/lyswhut/lx-music-desktop/issues/744

**Comment by helloplhm-qwq** [comment]
portable目录是给绿色版用的啊，安装包就默认就行，更新包会清空安装目录再进行更新
