### ISSUE TITLE
[Bug]: 最新版本每次歌曲播放完都会提示当前版本将不提供维护，请更新版本

### ISSUE THREAD

**Issue by ll2016tju** [lyswhut/lx-music-desktop#1204]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

最新版本正常循环播放

### 实际行为

每次歌曲播放完后都会提示当前版本即将不提供维护，请更新版本。但使用版本已经是最新版本。

### Lx Music 版本

2.1.2

### 最后正常的版本

2.1.2

### 操作系统版本

windows11 22H2

**Comment by Trevo1** [comment]
我的是很多歌直接变成十秒钟的标题那句话 听不了

**Comment by ll2016tju** [comment]
> 

一般会重复提醒两次，每次十秒钟，然后才能正常听

**Comment by Trevo1** [comment]
> 

我的提醒完十秒钟直接切到下一首歌了

**Comment by YerongAI** [comment]
很明显是 wy 改 API 了，软件本身没有太大问题

**Comment by ylin3-learner** [comment]
我也是同样的问题，已经更新到最新的版本。

**Comment by Moemu** [comment]
能不能临时改变或禁止这些有问题的源来解决此问题？

**Comment by Byl1992** [comment]
设置把六音音源改回测试接口就好了

**Comment by lyswhut** [comment]
已应该已经恢复，去设置清空缓存后重试

**Comment by HotRockit** [comment]
> 我的是很多歌直接变成十秒钟的标题那句话 听不了

我也是这样的问题，但是现在正常了，这不是软件的问题，是音源的问题，我用的另一个音乐软件也碰到了这样的问题

**Comment by Trevo1** [comment]
> > 我的是很多歌直接变成十秒钟的标题那句话 听不了
> 
> 我也是这样的问题，但是现在正常了，这不是软件的问题，是音源的问题，我用的另一个音乐软件也碰到了这样的问题

我的还没有好
