### ISSUE TITLE
[Feature]: 桌面端下载优化

### ISSUE THREAD

**Issue by MisakaNo-114514** [lyswhut/lx-music-desktop#1207]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

桌面端2.0版本以后移除了下载键，试听键，需要右键点击再点击下载
点击下载后有需要再次点击“歌名 - 128k” 才能下载

### 描述你想要的解决方案

非常不方便，尤其是大量下载的情况，如果可以，能否加入多选键？重新添加回下载键，并取消再次确认的步骤。
我认为可以带来一定的便利。
谢谢

**Comment by helloplhm-qwq** [comment]
下载键可以在这个设置中恢复
![image](https://user-images.githubusercontent.com/94218819/221393833-fa31be2c-448f-4ea7-a6d1-49691fdf296a.png)
多选逻辑与文件管理器多选文件逻辑相同，按住Ctrl选单个，Shift选首尾
再次确认的步骤是为支持高品质的自定义音源准备的，类似于这种
![image](https://user-images.githubusercontent.com/94218819/221393884-aea3834f-fd5c-4d8b-a547-f721828430d7.png)
所以直接删掉并不好，可以多选，然后右键同时下载多首歌
![image](https://user-images.githubusercontent.com/94218819/221393914-5f02b695-3c8c-44f6-a7c1-9f9027283275.png)

**Comment by EkkoKin** [comment]
现在不能下载无损格式了吗？

**Comment by huoshihi** [comment]
> 现在不能下载无损格式了吗？

同問

**Comment by helloplhm-qwq** [comment]
> 现在不能下载无损格式了吗？

可以用第三方音源支持~

**Comment by MisakaNo-114514** [comment]
谢谢大佬！

从 Windows 版邮件发送

发件人: 彭狸花喵
发送时间: 2023年2月26日 13:26
收件人: lyswhut/lx-music-desktop
抄送: MisakaNo-114514; Author
主题: Re: [lyswhut/lx-music-desktop] [Feature]: 桌面端下载优化 (Issue #1207)

下载键可以在这个设置中恢复

多选逻辑与文件管理器多选文件逻辑相同，按住Ctrl选单个，Shift选首尾
再次确认的步骤是为支持高品质的自定义音源准备的，类似于这种

所以直接删掉并不好，可以多选，然后右键同时下载多首歌

**Comment by ichigomikako** [comment]
> 下载键可以在这个设置中恢复 ![image](https://user-images.githubusercontent.com/94218819/221393833-fa31be2c-448f-4ea7-a6d1-49691fdf296a.png) 多选逻辑与文件管理器多选文件逻辑相同，按住Ctrl选单个，Shift选首尾 再次确认的步骤是为支持高品质的自定义音源准备的，类似于这种 ![image](https://user-images.githubusercontent.com/94218819/221393884-aea3834f-fd5c-4d8b-a547-f721828430d7.png) 所以直接删掉并不好，可以多选，然后右键同时下载多首歌 ![image](https://user-images.githubusercontent.com/94218819/221393914-5f02b695-3c8c-44f6-a7c1-9f9027283275.png)

您这个透明度在搜索时候是不是搜索联想也是透明的，看起来很花呀？

**Comment by helloplhm-qwq** [comment]
> 

不会太离谱
![image](https://user-images.githubusercontent.com/94218819/236651570-4906651b-32fe-4a5d-a29e-26b38c060ffd.png)

**Comment by oliver-xie666** [comment]
> > 现在不能下载无损格式了吗？
> 
> 可以用第三方音源支持~

除了六音那个，哪里还有第三方音源了呀
