### ISSUE TITLE
[Feature]: 希望能够增加手表端的支持，适应安卓手表的UI界面

### ISSUE THREAD

**Issue by luoyufeihuo** [lyswhut/lx-music-desktop#1208]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望能够增加手表端的支持，适应安卓手表的UI界面

### 描述你想要的解决方案

添加类似QQ音乐手表版，网易云音乐手表版的UI

**Comment by lyswhut** [comment]
sorry，时间精力有限，目前没有适配手表端的计划
