### ISSUE TITLE
请求异常

### ISSUE THREAD

**Issue by jiansite** [lyswhut/lx-music-desktop#121]
音乐不能下载，
[下载截图](https://picabstract-preview-ftn.weiyun.com/ftn_pic_abs_v3/3f76db58aa73e78076e869471f4e313b6814bee43e28b10bfe9363fa8698854a84798b8e45083a5db7e2141cb3229078?pictype=scale&from=30113&version=3.3.3.3&uin=1340582309&fname=QQ%E6%88%AA%E5%9B%BE20200201180141.png&size=750]![Uploading%20image.png)

**Comment by lyswhut** [comment]
耐心等待酷狗接口修复，晚点应该可以吧

**Comment by lyswhut** [comment]
经测试已恢复正常
