### ISSUE TITLE
[Bug]: 在linux下运行报错

### ISSUE THREAD

**Issue by wjztwjzt** [lyswhut/lx-music-desktop#1210]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

怎么能恢复呢

### 实际行为

在llinux下运行，报错：error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory。是缺少libgbm.so文件吗？

### Lx Music 版本

2.1.2

### 最后正常的版本

2.1.2

### 操作系统版本

Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Comment by lyswhut** [comment]
这是你的系统环境确实相关依赖导致的，自己Google相关问题解决：
- https://stackoverflow.com/questions/67407104/error-while-loading-shared-libraries-libgbm-so-1-cannot-open-shared-object-fil
- https://www.google.com/search?q=error+while+loading+shared+libraries%3A+libgbm.so.1%E2%80%A6&ie=utf-8&oe=utf-8
