### ISSUE TITLE
[Bug]: 内置API不返回有效数据

### ISSUE THREAD

**Issue by myrelease** [lyswhut/lx-music-desktop#1216]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常通过内置API获取音频资源

### 实际行为

使用移动宽带网络，无法获取任何音频资源，**接口只会返回404 Not Found**，使用一些其它IP，如手机流量，可以获得有效音频资源链接

![截图](https://user-images.githubusercontent.com/93897839/222673410-d295d7c3-a3fe-45d7-9816-3a98c7b403f4.png)

不知道是不是对IP有所限制，希望解决！

### Lx Music 版本

2.1.2

### 操作系统版本

windows10

**Comment by helloplhm-qwq** [comment]
全部404是IP被封了，七天后会自己解封~
