### ISSUE TITLE
[Bug]: 在聚合大会栏目下搜索，跳转到最后一页显示空，且页码组建消失

### ISSUE THREAD

**Issue by Arthuring** [lyswhut/lx-music-desktop#1217]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在聚合大会栏目下搜索，点击跳转到最后一页，显示出搜索结果的最后几条

### 实际行为

在聚合大会栏目下搜索，点击跳转到最后一页，会显示列表是空的，且页码组建消失，无法返回，只能重新点击搜索恢复
![搜索列表空](https://user-images.githubusercontent.com/95556856/222190411-04178e89-ea6c-4d6c-a123-370440ec7e7e.gif)

### Lx Music 版本

2.1.2

### 操作系统版本

 Windows 10 家庭中文版 19044.2604

**Comment by lyswhut** [comment]
已在v2.2.0修复
