### ISSUE TITLE
[Feature]: 快捷键调整音量步进调大一点

### ISSUE THREAD

**Issue by p-eng** [lyswhut/lx-music-desktop#1220]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

快捷键调整音量按一下调整0.02

### 描述你想要的解决方案

快捷键调整音量按一下调整0.05

### 描述你考虑过的替代方案

音量百分之二的变化不明显，快捷键调整音量需要按几下才达到想要的效果

**Comment by lyswhut** [comment]
下版本改为0.04

**Comment by lyswhut** [comment]
已在v2.2.0修改
