### ISSUE TITLE
求问是否付费音乐已经无法下载

### ISSUE THREAD

**Issue by Kingsleyooo** [lyswhut/lx-music-desktop#124]
音乐显示为灰色无法下载
**环境：**
Windows 10 64位 18363.592
软件安装包及版本：Windows 64位绿色版 0.15.0

![截图](https://user-images.githubusercontent.com/40708301/73836602-9ef72c00-484a-11ea-994f-72782cfa74fd.png)

**Comment by Kingsleyooo** [comment]
发现是所有音乐都无法下载，请问是流程操作哪里出了问题吗

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/78
