### ISSUE TITLE
[Bug]: win11安装包无法正常运行

### ISSUE THREAD

**Issue by xksamuro** [lyswhut/lx-music-desktop#1247]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常启动安装程序

### 实际行为

![image](https://user-images.githubusercontent.com/57165991/226081856-00c895b1-cd3f-4f2c-9275-2addf8ff7b45.png)
win11的新笔记本，尝试了三种安装包均无法正常运行安装程序，双击setup_exe后没有任何反应，电脑是64位的，R7-7735H+RTX4060L

### Lx Music 版本

2.1.2

### 操作系统版本

win11 22H2  22621.1413

**Comment by xksamuro** [comment]
用管理员启动也是无效的

**Comment by xksamuro** [comment]
试了下2.1.0的安装程序打开了

**Comment by lyswhut** [comment]
在文件右击菜单进入属性，解除限制

**Comment by zhongjun96** [comment]
> 在文件右击菜单进入属性，解除限制

你好，请问是哪里解除限制？win11。双击安装包没反应
![Clip_2024-07-18_15-17-59](https://github.com/user-attachments/assets/fc45053e-ba5f-4ebe-8d32-f7b9402265f5)

**Comment by Soroas** [comment]
我现在是win11安装2.9.0，双击没效果。
解决方法：右击->属性->兼容性->以兼容模式运行这个程序：我选择了win7->再次双击安装，正常！
