### ISSUE TITLE
[Feature]: 使用系统标题和边框

### ISSUE THREAD

**Issue by Crany-web** [lyswhut/lx-music-desktop#1249]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

使用系统+桌面：Arch Linux+KDE
希望能出一个像Google chrome浏览器(Linux版)的设置--->外观--->使用系统标题栏和边框的功能，因为Linux用户有的不像是Windows那样，但软件目前没有此类开关以至于使用软件时有种跟系统不合拍的感觉
![lx样式建议.png](http://img.crany.fun/i/2023/03/19/64163ace935dd.png)

### 描述你想要的解决方案

能使用系统标题栏和边框

**Comment by qxqzx3489** [comment]
大哥,关闭了是解决了吗?

**Comment by Crany-web** [comment]
> 大哥，关闭了解决了吗？

没有，但是软件的设置中有替代方式(尽管我觉得还是跟系统边框不一样，但总归体验不是很割裂)
<img src="http://img.crany.fun/i/2023/07/30/64c5d8a72b7a2.png" alt="洛雪音乐按钮位置.png" title="洛雪音乐按钮位置.png" />
