### ISSUE TITLE
所有歌单中的歌曲无法播放, 版本0.15.0 macos 15.1, 谢谢🌹

### ISSUE THREAD

**Issue by earthNoah** [lyswhut/lx-music-desktop#125]
所有歌单中的歌曲无法播放, 版本0.15.0 macos 15.1, 
谢谢🌹

![image](https://user-images.githubusercontent.com/23658298/74000639-c6add780-49a3-11ea-9f7c-164de7e77ac5.png)
![image](https://user-images.githubusercontent.com/23658298/74000649-d3cac680-49a3-11ea-9152-71e394b013ef.png)
![image](https://user-images.githubusercontent.com/23658298/74000663-de855b80-49a3-11ea-87ac-bb90b54723d9.png)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/78
