### ISSUE TITLE
[Bug]: 多屏歌词拖动问题

### ISSUE THREAD

**Issue by road2coder** [lyswhut/lx-music-desktop#1252]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

歌词可在多个显示器下自由拖动

### 实际行为

在双显示下，歌词存在拖动问题，此问题在linux（arch）和windows下均出现，不确定是否是相同原因导致，具体表现为：
1. 在 **windows** 上无法拖动到副屏上，**只能在主屏范围内拖动**
2. 在 **linux(arch)** 上，只可以在主屏及副屏的指定范围内拖动，大概是左侧的1/3。即可拖动范围是**主屏 + 副屏左侧1/3**

### Lx Music 版本

2.1.2

### 操作系统版本

windows11 22H2

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/1031

**Comment by road2coder** [comment]
> #1031

感谢。请问是否有赞助渠道，想简单地支持一下开源作品，在github及官网均没有找到。

**Comment by lyswhut** [comment]
无，心意领了 :)
