### ISSUE TITLE
[Bug]: 修复全局快捷键下Media Session冲突的问题 [Feature]: 设置优化

### ISSUE THREAD

**Issue by CottonCandy2004** [lyswhut/lx-music-desktop#1258]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

- 希望增加对Media Session的支持以便和[其它软件](https://nvg.dev/core/sao-utils/issues/287#issuecomment-1341)联动
- 希望在设置里增加一个搜索设置项的功能

### 描述你想要的解决方案

- 增加对Media Session的支持
- 在设置里增加一个搜索设置项的功能

**Comment by lyswhut** [comment]
你是否启用了全局快捷键？
这是一个Bug，下个版本会修复，事实上Media Session已经支持，之所以不生效是因为启用全局快捷键后会默认注册媒体按键，导致与Media Session冲突

现在有两种临时的解决方案：

1. 关闭全局快捷键后，重启软件或切一首歌试试
2. 退出软件，去[数据目录](https://lyswhut.github.io/lx-music-doc/desktop/datapath)`%APPDATA%/lx-music-desktop/LxDatas`编辑`hot_key.json`文件，删除`global.keys`下的`MediaPlayPause`、`MediaPreviousTrack`、`MediaNextTrack`及内容后保存，再启动软件即可

**Comment by lyswhut** [comment]
已在v2.2.1修复；
设置项搜索暂不考虑。
