### ISSUE TITLE
酷狗音乐搜索无效

### ISSUE THREAD

**Issue by zw1127** [lyswhut/lx-music-desktop#127]
**环境：**
  -操作系统及版本： windows7 64位
  -软件安装包及版本：0.15.0

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
我这边测试是可以正常搜索的，可能是你那边的网络问题，可以尝试切换网络试试

**Comment by zw1127** [comment]
今天好了，是网络的问题，谢谢了。
