### ISSUE TITLE
[Bug]: mac arm64 安装失败

### ISSUE THREAD

**Issue by SCHLLLLLL** [lyswhut/lx-music-desktop#1274]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

mac pro M1 安装2.2.0失败, 安装包: arm64.dmg

### 实际行为

<img width="323" alt="image" src="https://user-images.githubusercontent.com/32814785/228429248-6db74013-4761-45a3-b850-858f01c97295.png">

### Lx Music 版本

2.2.0

### 操作系统版本

mac os

**Comment by huanghonghao** [comment]
mac萌新吧🤔
打开终端输入`sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app`, 输入密码回车就行了

**Comment by byewind1** [comment]
谢谢，就是这么解决的，怎么好多软件需要这段代码？

**Comment by helloplhm-qwq** [comment]
> 谢谢，就是这么解决的，怎么好多软件需要这段代码？

这个给你说一下，这些软件没有签名，Mac在打开app时会验证软件签名，没有签名的就会弹这个
这行代码是信任这个包用的似乎

**Comment by 3093511189** [comment]
> mac萌新吧🤔
> 打开终端输入`sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app`, 输入密码回车就行了

可以了，谢谢🙏
