### ISSUE TITLE
无法导入本地音乐

### ISSUE THREAD

**Issue by dabu680** [lyswhut/lx-music-desktop#128]
**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by lyswhut** [comment]
本软件不是音乐播放器，所以不支持导入本地音乐，原因详见常见问题第一条：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md
