### ISSUE TITLE
[Bug]: 打开桌面歌词系统卡死，重启系统后打开LX-MUSIC系统依旧卡死

### ISSUE THREAD

**Issue by huguangquan** [lyswhut/lx-music-desktop#1288]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常使用

### 实际行为

打开桌面歌词系统卡死，重启系统后打开LX-MUSIC系统依旧卡死。卸载重装，卸载降版本后都是一样的问题。

### Lx Music 版本

Linux 2.2.0

### 最后正常的版本

Linux 2.1.2

### 操作系统版本

deepin社区版20.7

**Comment by lyswhut** [comment]
你的意思是在升级到2.2.0之前，2.1.2的桌面歌词可以正常使用？升级之后就出现这个问题，降级回2.1.2仍然会出现这个问题是吗？

**Comment by lyswhut** [comment]
似乎安装了最新的系统更新后这个问题已经解决：
![image](https://user-images.githubusercontent.com/20365169/230753342-974250bf-d12e-4873-9533-a9bcdd6adbda.png)

**Comment by crownclownwl** [comment]
我也遇到这个问题了 最新版，只要点击一次桌面歌词，就会导致系统卡死，我也是deepin v20.9
![image](https://github.com/lyswhut/lx-music-desktop/assets/11539526/3ce68509-d330-4bdc-8099-ad27cdcf1dc0)

**Comment by crownclownwl** [comment]
@lyswhut 我是deepin v20.9 的6.1.12内核 也是卡死，会直接导致系统开始，不开启桌面歌词就可以用

**Comment by lyswhut** [comment]
最新的beta版应该已经修复该问题：<https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml>

**Comment by lyswhut** [comment]
已在v2.3.0修复
