### ISSUE TITLE
可以添加一个倍速播放的功能吗?

### ISSUE THREAD

**Issue by zsedcbm** [lyswhut/lx-music-desktop#13]
现在看视频喜欢倍速播放, 有些时候觉得倍速的音乐别有一番滋味.

**Comment by lyswhut** [comment]
个人不推荐使用本软件作为常用播放器使用，本软件是为了查找歌曲
可以用其他播放器播放

**Comment by GTian5418** [comment]
> 个人不推荐使用本软件作为常用播放器使用，本软件是为了查找歌曲 可以用其他播放器播放

可是现在用的很方便啊，完全当主力在用，可以加上倍速功能吗😘

**Comment by lyswhut** [comment]
已在v2.1.0新增

**Comment by GTian5418** [comment]
> 已在v2.1.0新增

感谢大佬
