### ISSUE TITLE
不能添加本地音乐播放

### ISSUE THREAD

**Issue by lnt21** [lyswhut/lx-music-desktop#130]
刚试了下，这软件真心不错，平时下载都要用嗅擦器来下。这下就爽了，
但是有一个问题，比如刚找一首歌没找到《世界美好与你环环相扣》柏松 版的。下载不了，通过网上其它方法下载到本地了，想用这个软件来听，就不知道怎么加载，把它拉到界面也无效。希望改进，谢谢！

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/108
