### ISSUE TITLE
[Feature]: 增加在线听音质调节功能

### ISSUE THREAD

**Issue by fh1584023325** [lyswhut/lx-music-desktop#1301]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

增加在线听音质调节功能 添加其他音源 可以下载无损音乐 但在线听的时候无法选择无损音质

### 描述你想要的解决方案

在线听允许用户自己调节音质

### 描述你考虑过的替代方案

当用户安装了其他音源 允许用户在线听的时候调节音质

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749
