### ISSUE TITLE
[Bug]: deepin 系统 ，点击显示歌词按钮后死机

### ISSUE THREAD

**Issue by lqqkk** [lyswhut/lx-music-desktop#1307]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

点击LRC后，显示歌词。

### 实际行为

点击LRC后，桌面进入死机状态，无法进行任何操作。

电脑型号为：hp elitebook 840 G6 。

操作系统为：deepin 20.8 版  Linux 系统。

软件版本：lx-music-desktop-v2.2.0-x64.deb

### Lx Music 版本

2.2.0

### 操作系统版本

Linux 5.18.17-amd64-desktop-community

### 附加信息

深度操作系统社区版20.8

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1288

**Comment by JiakaiYang** [comment]
> ### 解决方案检查
> * [x]  我已阅读常见问题(https://lyswhut.github.io/lx-music-doc/desktop/faq)，并没有找到解决方案
> * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=))，并没有发现类似的问题
> 
> ### 预期行为
> 点击LRC后，显示歌词。
> 
> ### 实际行为
> 点击LRC后，桌面进入死机状态，无法进行任何操作。
> 
> 电脑型号为：hp elitebook 840 G6 。
> 
> 操作系统为：deepin 20.8 版 Linux 系统。
> 
> 软件版本：lx-music-desktop-v2.2.0-x64.deb
> 
> ### Lx Music 版本
> 2.2.0
> 
> ### 最后正常的版本
> _No response_
> 
> ### 操作系统版本
> Linux 5.18.17-amd64-desktop-community
> 
> ### 附加信息
> 深度操作系统社区版20.8

请问你用 #1288的方法解决了吗？我也遇到这个问题了

**Comment by JiakaiYang** [comment]
> 

你好，我的情况并不是左面歌词导致的死机， 是一打开LX 还没有任何操作就死机了，只能强行关机。。

**Comment by lyswhut** [comment]
解决方案看：<https://github.com/lyswhut/lx-music-desktop/issues/1288>
