### ISSUE TITLE
[Feature]: 希望添加快速搜索歌手作品和关闭时自动后台播放功能

### ISSUE THREAD

**Issue by xiaoqiangclub** [lyswhut/lx-music-desktop#1308]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望添加2个功能：
①在当前歌曲上右键点击可以快速搜索该同名歌曲和该歌手的歌手作品
②第二个建议主要是为了像和我有同样强迫症的人，我习惯点右上角的 X 按钮来关闭，但是我希望的是关闭当前页面后程序继续在后台播放音乐（很多软件都有这个功能，当然现在的界面也有一个缩小的功能），只需要多一个选项：第一次点击 X 按钮设置，是否完全退出还是关闭当前页面继续在后台播放。（这个功能很常见）仅仅是针对我这种强迫症用户。

### 描述你想要的解决方案

希望添加2个功能：
①在当前歌曲上右键点击可以快速搜索该同名歌曲和该歌手的歌手作品
②第二个建议主要是为了像和我有同样强迫症的人，我习惯点右上角的 X 按钮来关闭，但是我希望的是关闭当前页面后程序继续在后台播放音乐（很多软件都有这个功能，当然现在的界面也有一个缩小的功能），只需要多一个选项：第一次点击 X 按钮设置，是否完全退出还是关闭当前页面继续在后台播放。（这个功能很常见）仅仅是针对我这种强迫症用户。

**Comment by helloplhm-qwq** [comment]
都有啊
![image](https://user-images.githubusercontent.com/94218819/236655667-ad6fd325-5213-474b-998b-8209242384e0.png)
![image](https://user-images.githubusercontent.com/94218819/236655671-b1c85230-f6c6-43ab-a775-d78aec89b128.png)
