### ISSUE TITLE
[Bug]: 软件更新question

### ISSUE THREAD

**Issue by Esmge** [lyswhut/lx-music-desktop#1309]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

洛雪发布新版本，自动更新触发，然后重启变为新版本，下次打开依旧是新版本

### 实际行为

洛雪发布新版本，自动更新触发，然后重启变为新版本，但是下次打开是老版本

### Lx Music 版本

2.1.2

### 最后正常的版本

无

### 操作系统版本

win10 21h2

### 附加信息

其实不止这个版本，很多歌版本我都遇到过此问题，并且此问题在两个电脑上都出现过，我没有测试他是否每次出现，但确实出现过，然后我就必须下载压缩包然后解压覆盖才可以

**Comment by lyswhut** [comment]
看：<https://lyswhut.github.io/lx-music-doc/desktop/faq/update>卸载重装

**Comment by magicdawn** [comment]
> 注意：Mac版、Linux版不支持自动更新！

https://lxmusic.toside.cn/desktop/faq/update
所以 mac 不支持这个功能? 那建议标注一下, 同时禁用下载更新按钮

![01](https://github.com/lyswhut/lx-music-desktop/assets/4067115/d6402d2a-9b49-4962-b96e-62987ab3d160)
