### ISSUE TITLE
win7 在绿色安装包0.15目录覆盖安装exe安装版导致升级失败，界面变成一块一块的

### ISSUE THREAD

**Issue by yyfcc17** [lyswhut/lx-music-desktop#131]
**解决方案检查**

[x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
[x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：win7
  -软件安装包及版本：0.15绿色版 升级 0.16安装版

**其他内容**
卸载0.16，重新用绿色版0.15，点进去后显示升级失败

**Comment by lyswhut** [comment]
绿色版切换到安装版的话直接把绿色版删除，然后安装安装版即可。

软件数据存储位置：%HOMEPATH%\AppData\Roaming\lx-music-desktop

**Comment by yyfcc17** [comment]
谢谢，我试了一下，还是会出现那种鼠标指向的地方UI才会出来，鼠标没有指向的UI块就不显示，或者说是透明的问题，回退到0.15绿色版可以用，就是0.16不管是绿色版还是安装版都会出现这种问题

**Comment by lyswhut** [comment]
你确定你已经阅读常见问题比你并没有找到解决方案？

**Comment by yyfcc17** [comment]
不好意思，确实没有看文档，现在解决了，多谢
