### ISSUE TITLE
[Feature]: 播放本地音乐的能力

### ISSUE THREAD

**Issue by wuai-ui** [lyswhut/lx-music-desktop#1312]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

在远古版本的时候LX Music是可以播放本地音乐的，但后期不知道为什么不可以播放本地音乐了
本地音乐使用LX Music打开没有反应，设置为默认音乐播放器依然没有反应，拖入音乐无效。

![image](https://user-images.githubusercontent.com/83076773/230716299-521c2e8e-d616-4a68-884e-2dcbfbb0ff36.png)

### 描述你想要的解决方案

希望可以在后期版本中使LX Music可以播放本地音乐，这样LX Music就成为了完整的音乐播放器，希望大佬能如愿。
感谢大佬的付出，也希望LX Music越来越好！

### 描述你考虑过的替代方案

希望可以在后期版本中使LX Music可以播放本地音乐，这样LX Music就成为了完整的音乐播放器

**Comment by Kingjue2** [comment]
是的，而且一些歌明明下载了，但是播放的时候还是会使用网络音源，而不会自动播放本地音乐

**Comment by qingyelinjiatenghui** [comment]
是的，同求，很希望有这个功能

**Comment by road2coder** [comment]
同求+1呀

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/1107

**Comment by wuai-ui** [comment]
> 恢复：#1107
感谢！
