### ISSUE TITLE
排行榜-网易音乐源无限加载

### ISSUE THREAD

**Issue by Huansheng1** [lyswhut/lx-music-desktop#132]
QQ等正常，问题是切到网易音乐无限加载中却无法切回去，导致榜单功能彻底失灵动不了了。

**Comment by lyswhut** [comment]
我这边测试正常，尝试切换网络，并且提供截图看看

**Comment by pharaoh741** [comment]
我有同样的问题，重置网络没有帮助

**Comment by lyswhut** [comment]
我这边无法重现，说明重现步骤及附上相关截图

**Comment by mob890302** [comment]
同问题，排行榜，右上角切换音源，切换至QQ音乐提示“列表加载中”，列表加载是否有超时时间？功能是否正常？从卡住的情况来看无限期加载，且加载过程中无法切换音源。

**Comment by lyswhut** [comment]
目前列表加载失败时也会显示列表加载中，切换音源后会自动加载新的音源列表

**Comment by mob890302** [comment]
> 目前列表加载失败时也会显示列表加载中，切换音源后会自动加载新的音源列表

现在情况是 点击切换音源没有效果，不会弹出选择音源的下拉菜单

**Comment by lyswhut** [comment]
截图看看，重现步骤说明下

**Comment by Huansheng1** [comment]
QQ等其他源头正常
![image](https://user-images.githubusercontent.com/33859558/77156888-48cd0800-6adb-11ea-91f0-eeb84f9dd9ca.png)
 只有网易不行
![image](https://user-images.githubusercontent.com/33859558/77156940-613d2280-6adb-11ea-979f-7fabb6c44232.png)

![image](https://user-images.githubusercontent.com/33859558/77156959-6ac68a80-6adb-11ea-816f-2e245a460bc9.png)
不过 现在新版本不会像之前一样卡住无法换其他的源
歌单和排行榜都是这现象
直接下载安装打开切换源
没进行其他操作
无代理等软件在运行
网络是 江苏移动/江西移动都不行

**Comment by lyswhut** [comment]
@Huansheng1 只有网易的排行榜打不开吗？
你试下可以打开这个：`https://music.163.com/discover/toplist?id=19723756`

**Comment by Huansheng1** [comment]
![image](https://user-images.githubusercontent.com/33859558/77598649-57814800-6f3d-11ea-91c3-b7bcca78cd50.png)
可以打开

**Comment by Huansheng1** [comment]
换了台电脑+江苏电信，绿化版打开榜单正常，看来可能是个人网络或者电脑问题，晚点我再回去看看那电脑绿化版能不能打开。
