### ISSUE TITLE
[Feature]: 希望添加“猜你喜欢”功能

### ISSUE THREAD

**Issue by pandayqw** [lyswhut/lx-music-desktop#1322]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

该功能根据个人喜欢的音乐单曲，推荐给用户喜欢该音乐的人同时还会喜欢的其他音乐，这一点，个人觉得酷狗音乐的该功能做的很好，可以参考

### 描述你想要的解决方案

真的希望考虑一下该建议

**Comment by mrkoalaz** [comment]
这个功能，对于“这个软件”来说有点难以实现，原因有几个：
1，分析用户的喜好和偏好需要记录用户习惯，然后把曲库里的每首歌做标签，然后用大量的服务器资源来匹配用户习惯和对应标签的歌曲，再推送给用户。而这里面的几个条件，任何一个都没办法仅仅靠着一个软件完成。需要人的参与。
2，从现在这个软件的设计风格来看，作者做这个软件最主要的目的是做个可以免费下载和听歌的软件，本身就有巨大的法律风险，没办法加服务器资源更进一步提升体验的。
3，这个软件纯粹是作者和一帮志同道合的朋友用爱发电做的，资金、成本、法律风险，都是难以逾越的大山。

所以，且用且珍惜吧。

**Comment by lyswhut** [comment]
<https://github.com/lyswhut/lx-music-desktop/issues/915>
