### ISSUE TITLE
[Feature]: 在播放页添加定位和搜索功能

### ISSUE THREAD

**Issue by Tomspar** [lyswhut/lx-music-desktop#1323]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望作者可以在播放页添加一个**定位的按钮**，以及一个**搜索**的功能，以便在很多歌曲中快速找到正在播放的歌曲。求求啦awa

### 描述你想要的解决方案

希望作者可以在播放页添加一个**定位的按钮**，以及一个**搜索**的功能，以便在很多歌曲中快速找到正在播放的歌曲。求求啦awa

**Comment by lyswhut** [comment]
看：<https://lyswhut.github.io/lx-music-doc/desktop/faq/hotkey>
