### ISSUE TITLE
[Bug]: Mac最新版2.2歌词里面阴影怎么去掉

### ISSUE THREAD

**Issue by terwer** [lyswhut/lx-music-desktop#1325]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

最新版2.2的Mac Intel版，歌词出现背景阴影，尝试各种设置都不能去掉

预期是只出现歌词即可，看了设置没有效果。

我的配置如下

![image](https://user-images.githubusercontent.com/3259282/232187151-66cc8c59-4bcc-4a29-a005-0100f6b61f35.png)

### 实际行为

背景有黑影

![image](https://user-images.githubusercontent.com/3259282/232187122-dc0a8485-6a22-4dc8-8d7f-f52d61486712.png)

### Lx Music 版本

2.2.0

### 操作系统版本

Mac 13.2.1

**Comment by cddehsy** [comment]
Intel ，12.6 ，软件2.2.0也有这个

**Comment by lyswhut** [comment]
已在2.8.0修复
