### ISSUE TITLE
[Feature]: 关于本地音乐

### ISSUE THREAD

**Issue by qq2161392192** [lyswhut/lx-music-desktop#1327]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望在本地音乐中增加本地搜索功能

### 描述你想要的解决方案

不然音乐多了很难找想要的音乐

**Comment by Wanzhou-114514** [comment]
移动端识别不了mp3文件

**Comment by lyswhut** [comment]
列表内搜索用`ctrl + f`，更多信息看：<https://lyswhut.github.io/lx-music-doc/desktop/faq/hotkey>
