### ISSUE TITLE
无法播放除了酷我音乐以外的搜索结果

### ISSUE THREAD

**Issue by alexss369** [lyswhut/lx-music-desktop#133]
同一个网络，家中一台笔记本可以播放但装在新购买的台式机上却是这样，不清楚是什么问题。
![QQ图片20200220001702](https://user-images.githubusercontent.com/43944593/74851569-65f4a680-5376-11ea-8141-ff2b3e38fecf.jpg)
![QQ图片20200220001456](https://user-images.githubusercontent.com/43944593/74851332-0dbda480-5376-11ea-934d-7c7bba1194e4.jpg)
![QQ图片20200220001532](https://user-images.githubusercontent.com/43944593/74851389-2037de00-5376-11ea-8184-c5c3792c524a.jpg)
![QQ图片20200220001605](https://user-images.githubusercontent.com/43944593/74851446-35ad0800-5376-11ea-8c0a-097717f87197.jpg)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/78
