### ISSUE TITLE
[Bug]: 点击播放一直提示换源失败无法播放

### ISSUE THREAD

**Issue by Triste-OT** [lyswhut/lx-music-desktop#1332]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望能解决换源失败的问题，使播放器能正常播放音乐

### 实际行为

我打开开发者工具查看调试界面，就是这个样子，我也不确定哪里有问题，我试过卸载重装，清理用户数据，都没用
![image](https://user-images.githubusercontent.com/31840845/233099730-fb22e2f2-8ccf-4da3-8546-6e9c9626cb00.png)

### Lx Music 版本

2.2.0

### 最后正常的版本

2.2.0

### 操作系统版本

Windows 11 专业版 22H2

**Comment by Triste-OT** [comment]
> 我也是，用国内网听所有歌曲都出现换源失败，但用VPN就可以正常听了。

我昨天是在win10上使用的，正常没问题，今天重装系统到win11就这样了

**Comment by WouuYoauin** [comment]
我也有这个问题，估计是源有问题？

**Comment by vvsvv-cmd** [comment]
换源失败+1

**Comment by chengjiewulx** [comment]
手机端 也一样。提示换源失败。VPN翻墙后正常
版本1.0.4.

**Comment by wydistance** [comment]
找到了一个第三方源 测试了一下 貌似可以 
https://github.com/lyswhut/lx-music-source

**Comment by nsnake** [comment]
我也遇见这样的问题。估计是域名被墙或者怎么了

**Comment by wydistance** [comment]
> 找到了一个第三方源 测试了一下 貌似可以 https://github.com/lyswhut/lx-music-source

![image](https://user-images.githubusercontent.com/14065515/233766416-fb844b72-d317-4045-8dc7-e8ad43fc2781.png)

**Comment by CaimFxp** [comment]
经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试

**Comment by WouuYoauin** [comment]
> 经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试

神了，真的可以

**Comment by Triste-OT** [comment]
> 经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试

确实可以了，厉害啊

**Comment by emiyaice** [comment]
> 经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试

直呼6

**Comment by Kingjue2** [comment]
> 经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试

经测试，可行。这DNS污染太多了

**Comment by 465515119** [comment]
> 经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试

我刚尝试了一下，失败了，试了一下8.8.8.8和百度云的都不行，2023/06/27

**Comment by lyfZhixing** [comment]
> > 经排查为国内运营商对ts.tempmusics.tk的DNS解析进行污染或劫持导致，修改IPV4的DNS为223.5.5.5 223.6.6.6和IPV6的DNS为2400:3200::1和2400:3200:baba::1可以解决该问题。上述DNS皆为阿里公共DNS，其他公共DNS可以自行测试
> 
> 我刚尝试了一下，失败了，试了一下8.8.8.8和百度云的都不行，2023/06/27

试下手动导入作者写的这个源： https://github.com/lyswhut/lx-music-source 我刚试了下可行

**Comment by 465515119** [comment]
Received. Thanks a lot. 
谢谢我已收到您的邮件，稍后回复。

**Comment by cey137** [comment]
今天还是换源头失败的一天

**Comment by 465515119** [comment]
Received. Thanks a lot. 
谢谢我已收到您的邮件，稍后回复。

**Comment by ougato** [comment]
> > 找到了一个第三方源 测试了一下 貌似可以 https://github.com/lyswhut/lx-music-source
> 
> ![image](https://user-images.githubusercontent.com/14065515/233766416-fb844b72-d317-4045-8dc7-e8ad43fc2781.png)

谢谢

**Comment by 465515119** [comment]
Received. Thanks a lot. 
谢谢我已收到您的邮件，稍后回复。

**Comment by SuQiANQAQ** [comment]
dns方法试过了，还是不行，换源失败，但是网站会显示404

**Comment by 465515119** [comment]
Received. Thanks a lot. 
谢谢我已收到您的邮件，稍后回复。
