### ISSUE TITLE
[Bug]: linux下2.2.0版开启桌面歌词会导致软件卡死崩掉

### ISSUE THREAD

**Issue by lowy** [lyswhut/lx-music-desktop#1333]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

启用软件自带的桌面歌词功能

### 实际行为

设置界面的桌面歌词设置选项勾选显示歌词立刻就会导致软件卡死

### Lx Music 版本

2.2.0

### 操作系统版本

Linux Mint 21.1 x86_64

**Comment by shenqian5337** [comment]
系统deepin 20.9    用   2.2.0  2.1.2 同样问题

**Comment by coci713** [comment]
一样的遇到了，只有在Ubuntu下才是正常的，CPU的占用率超高

**Comment by lyswhut** [comment]
已在v2.3.0修复
