### ISSUE TITLE
有没有音质标签，知道自己当前听的歌曲是什么音质的呢

### ISSUE THREAD

**Issue by Y2hhbw** [lyswhut/lx-music-desktop#134]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
搜索的歌曲带有无损的小标签。下载的时候 无损是灰色的不能下载，那么自己试听时播放的是无损音质的

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
灰色的音质证明不支持下载，鼠标移上去会有提示。
重复：https://github.com/lyswhut/lx-music-desktop/issues/65#issuecomment-547538013
