### ISSUE TITLE
[Bug]: 酷我音乐源 开始报 维护了  测试接口

### ISSUE THREAD

**Issue by SpaceTimeMadman** [lyswhut/lx-music-desktop#1343]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

11

### 实际行为

11

### Lx Music 版本

2.2.0

### 操作系统版本

win

**Comment by LinkLeong** [comment]
突然间就不能听了

**Comment by ygq-704292061** [comment]
看样子是要开始收费了

**Comment by SpringLukeyi** [comment]
还有没有音源，现在六音的用不了

**Comment by lyswhut** [comment]
出现该问题尝试清理资源缓存、URL缓存，
测试接口现在应该已经恢复，临时接口还需要等一段时间

**Comment by lyswhut** [comment]
问题应该已经解决
