### ISSUE TITLE
[Feature]: 希望更新一个批量操作功能

### ISSUE THREAD

**Issue by ymhzrzzz** [lyswhut/lx-music-desktop#1347]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望更新一个批量操作功能，能够批量移动歌曲至另一个 歌单谢谢

### 描述你想要的解决方案

希望更新一个批量操作功能，能够批量移动歌曲至另一个 歌单谢谢

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/list-multiple-selection

**Comment by ymhzrzzz** [comment]
谢谢 找到了
