### ISSUE TITLE
希望能保存搜索记录

### ISSUE THREAD

**Issue by sanmaodo** [lyswhut/lx-music-desktop#135]
RT,
这样会方便很多，有些英文名字太长，记不住。

**Comment by lyswhut** [comment]
这个可以有，可以做成设置项选择是否保存搜索记录

**Comment by sanmaodo** [comment]
这毫无疑问省去了一堆麻烦，谢谢！

**Comment by lyswhut** [comment]
刚才我想了下，这个功能有必要吗？
一般能搜到的歌曲，搜索完后就会直接添加到我的列表中了，一般情况下之后应该都不需要二次搜索了吧？

**Comment by sanmaodo** [comment]
确实有必要，比如：我常用 “Suzanne Teng”(作曲人) 的歌曲来做背景音乐，“Suzanne Teng”的歌曲有很多，试听后会选择一首合适的收藏，下次做其它视频的时候，就又要再次把她的歌曲搜索出来试听

**Comment by lyswhut** [comment]
这看起来大多数用户都不会有这样的需求，很少人会用到搜索记录这个功能，但在某些情况下可能确实很有用；
还有一个问题是这个功能放到搜索框下的话与搜索提示的显示有冲突。
综上，该功能可能不会那么快添加，到时候如果在“搜我所想”几个字的下面添加热搜词的话，顺便再加上它

**Comment by sanmaodo** [comment]
确实会有冲突

**Comment by wanglio** [comment]
有必要

**Comment by lyswhut** [comment]
已在`0.17.0`添加历史搜索记录功能，默认关闭，需到设置手动开启
