### ISSUE TITLE
[Bug]: 音频嵌入的歌词 原歌词与翻译歌词顺序错乱

### ISSUE THREAD

**Issue by xzhzhaowendao** [lyswhut/lx-music-desktop#1358]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在下载设置中勾选“同时迁入翻译歌词（如果有）”时，嵌入的歌词出现原歌词与翻译歌词顺序错乱的情况。并不是个例，望修复。
![QQ截图20230430223546](https://user-images.githubusercontent.com/132211598/235358832-c55aa2c0-ac7f-4925-b85a-809463c39945.png)
![QQ截图20230430223200](https://user-images.githubusercontent.com/132211598/235358710-9af65abb-f430-47e3-b120-0e0672755b10.png)

### 实际行为

在下载设置中勾选“同时迁入翻译歌词（如果有）”时，嵌入的歌词出现原歌词与翻译歌词顺序错乱的情况。望修复。
![QQ截图20230430223200](https://user-images.githubusercontent.com/132211598/235358794-377ff33e-5b78-4cf6-b4bb-edfe156335b9.png)

### Lx Music 版本

2.2.0

### 操作系统版本

Windows 7 旗舰版

**Comment by helloplhm-qwq** [comment]
这个是lrc协议的问题，似乎无解

**Comment by lyswhut** [comment]
你提供下什么源的什么歌曲吗？

**Comment by xzhzhaowendao** [comment]
![qq](https://github.com/lyswhut/lx-music-desktop/assets/132211598/846ba205-e433-4a55-b43c-13b6fb97f452)
![wy just like fire](https://github.com/lyswhut/lx-music-desktop/assets/132211598/6e3583eb-bc89-41dc-acab-f4c62da650ec)
![wy viva la vida](https://github.com/lyswhut/lx-music-desktop/assets/132211598/c26dce65-c12c-491b-9135-abe2b39c2ba9)
![wy in the end'](https://github.com/lyswhut/lx-music-desktop/assets/132211598/5df3c654-fee5-4432-8efa-0c31dddb79a5)
wy源和qq源都有这种情况，总体来说wy源更多一些。用的是测试接口。

**Comment by xzhzhaowendao** [comment]
更新2.3.0后此问题尚未解决，不知道是不是我的问题？
![wy1](https://github.com/lyswhut/lx-music-desktop/assets/132211598/52c93d82-65ad-4a5a-8303-4de59710bb3f)

![wy2](https://github.com/lyswhut/lx-music-desktop/assets/132211598/198b7de8-134d-4ae0-b1c6-fe000caa2b68)
补充一下，wy源居多，tx源很少有。

**Comment by lyswhut** [comment]
什么源的什么歌曲？重现步骤说明下

**Comment by xzhzhaowendao** [comment]
https://github.com/lyswhut/lx-music-desktop/assets/132211598/9ddb7645-47ab-4e7e-b777-3b33ec9cd171

**Comment by lyswhut** [comment]
这是你所用播放器的问题，你下载下来再通过添加本地文件的方式导入到lx中播放，可以看到歌词顺序是正常的

![image](https://github.com/lyswhut/lx-music-desktop/assets/20365169/4c26de8e-6b72-4f6d-b960-f20a83984034)

**Comment by cestbon-cestbon** [comment]
<img width="391" alt="企业微信截图_51ae39ae-d8ef-4b04-b69b-fa7c52202e62" src="https://github.com/lyswhut/lx-music-desktop/assets/65571550/ed475a10-7d5e-4b7b-9df1-aa450617c3ae">
桌面歌词显示存在问题。
系统：mac os
版本：lx-music-desktop-2.3.0.dmg
操作：显示歌词 && 固定歌词
复现路径：必现

**Comment by helloplhm-qwq** [comment]
> 
> <img width="378" alt="企业微信截图_fd69d774-9cee-43a9-a9d1-3f65bf717cf6" src="https://github.com/lyswhut/lx-music-desktop/assets/65571550/f9cfc19a-91fb-4ac9-9629-b6585e2536ad">
> 
> 
> 桌面歌词显示存在问题。
> 系统：mac os
> 版本：lx-music-desktop-2.3.0.dmg
> 操作：显示歌词 && 固定歌词
> 复现路径：必现

这是上游依赖electron的问题，无法解决

**Comment by helloplhm-qwq** [comment]
> > 
> > <img width="378" alt="企业微信截图_fd69d774-9cee-43a9-a9d1-3f65bf717cf6" src="https://github.com/lyswhut/lx-music-desktop/assets/65571550/f9cfc19a-91fb-4ac9-9629-b6585e2536ad">
> > 
> > 
> > 桌面歌词显示存在问题。
> > 系统：mac os
> > 版本：lx-music-desktop-2.3.0.dmg
> > 操作：显示歌词 && 固定歌词
> > 复现路径：必现
> 
> 这是上游依赖electron的问题，无法解决

上游依赖修复了我们自然也就修复了

**Comment by xzhzhaowendao** [comment]
> 这是你所用播放器的问题，你下载下来再通过添加本地文件的方式导入到lx中播放，可以看到歌词顺序是正常的
> 
> ![image](https://user-images.githubusercontent.com/20365169/259315989-4c26de8e-6b72-4f6d-b960-f20a83984034.png)

是的，PotPlayer问题，也是麻烦你了
