### ISSUE TITLE
[Bug]: 网易云热门评论无法加载

### ISSUE THREAD

**Issue by hexadecimal233** [lyswhut/lx-music-desktop#1363]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

最近更新了热门评论翻页，发现部分歌曲的热门评论看不到了

### 实际行为

热门评论正常显示

### Lx Music 版本

2.2.2

### 最后正常的版本

2.2.0

### 操作系统版本

Windows

**Comment by helloplhm-qwq** [comment]
例如？什么歌？

**Comment by Soda5601** [comment]
这首看一下
https://music.163.com/#/song?id=2014481148
显示有一条热门评论但是显示暂无

**Comment by hexadecimal233** [comment]
此问题无法在最新版复现，暂且当修复处理
