### ISSUE TITLE
能否添加功能：批量去除音乐配置信息

### ISSUE THREAD

**Issue by snowoneyebrow** [lyswhut/lx-music-desktop#137]
作者你好 你的软件很好用！
但有个小问题 我把下载的音乐放到手机里 网易云音乐识别出来 有些音乐的名字是乱码 比如从酷我源下载的音乐 音乐名就显示为kuwo 还有些音乐的名字是？？？（问号）
我在网上查了一下 发现删除音乐本身的配置信息即可 但只能手动地右键属性一个个删除 效率较低
请问作者能否加上批量去除音乐配置信息的功能 不胜感激！

**Comment by lyswhut** [comment]
mp3格式可以自动编辑音乐标签信息，无损不支持，详情看：https://github.com/lyswhut/lx-music-desktop/issues/85
