### ISSUE TITLE
[Feature]: 在MacOS希望能够隐藏右上角软件图标

### ISSUE THREAD

**Issue by you-hengh** [lyswhut/lx-music-desktop#1372]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

刘海屏的Macos因为众所周知的原因，菜单栏图标位置十分紧张，所以希望能够隐藏的的图标尽量隐藏，不要占据菜单栏图标空间

所以期望软件可以提供隐藏菜单栏图标的功能（可以做成开关）

### 描述你想要的解决方案

在设置中新增一个隐藏选择框

### 描述你考虑过的替代方案

<img width="540" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/34816426/7d6da3f2-ec5d-477c-ae08-b9384ca21f01">

**Comment by lyswhut** [comment]
去基本设置关闭系统托盘图标

**Comment by you-hengh** [comment]
> 去基本设置关闭系统托盘图标

<img width="920" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/34816426/444f37b7-97a3-4445-85e3-a86ae48576dc">

不好意思我没找到是什么位置？ 能指明一下吗？

**Comment by lyswhut** [comment]
定时暂停上面那个，关闭托盘图标后，点击软件的关闭时将直接退出软件，
不打算支持在开启该功能的情况下单独隐藏托盘图标，不然隐藏软件后会导致无法重新显示界面的问题，只能使用再次启用软件的方式重新打开界面

**Comment by you-hengh** [comment]
> 定时暂停上面那个，关闭托盘图标后，点击软件的关闭时将直接退出软件， 不打算支持在开启该功能的情况下单独隐藏托盘图标，不然隐藏软件后会导致无法重新显示界面的问题，只能使用再次启用软件的方式重新打开界面

原来如此，现在已经隐藏图标了 非常感谢
