### ISSUE TITLE
0.16.0版本，QQ音乐歌单搜索功能无法使用

### ISSUE THREAD

**Issue by myzhulin** [lyswhut/lx-music-desktop#138]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤：
歌单的搜索功能点击搜索之后会一直卡在正在加载无法返回

**预期行为**
正常返回歌单列表

**截图**
![image](https://user-images.githubusercontent.com/42506908/75106413-5071cc00-5657-11ea-911b-26a48f236d52.png)

**环境：**
  -软件安装包及版本：windowx64 0.16.0

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by myzhulin** [comment]
额，不好意思，我发现要将从客户端里的链接到浏览器里面打开之后，重新复制浏览器的链接就可以打开了。

**Comment by lyswhut** [comment]
这是即将补上的FAQ：

无法打开外部歌单
目前软件仅支持打开从网页粘贴过来的歌单，或者如果你知道歌单 id 也可以直接输入歌单 id 打开；
事实上输入歌单链接时软件做的只是自动匹配出链接里的歌单 id 去打开，如果链接不包含歌单 id，将无法打开歌单；
对于移动端分享出来的歌单，建议先在浏览器中打开后，再从浏览器复制歌单地址到软件打开；
目前不支持打开酷狗用户自定义歌单。
