### ISSUE TITLE
[Bug]: fedora38打开软件后，界面一直闪，不稳定

### ISSUE THREAD

**Issue by yjb152-yjb** [lyswhut/lx-music-desktop#1392]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

appimage和rpm都试过了，电脑是64位系统

### 实际行为

界面一直闪，有时候变透明

### Lx Music 版本

2.2.2

### 操作系统版本

fedora38

### 附加信息

![截图 2023-06-01 15-30-35](https://github.com/lyswhut/lx-music-desktop/assets/63338034/a0841d2f-2c81-446e-90a8-5ba6dfe43256)

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/interface-abnormal
