### ISSUE TITLE
[Bug]: 感觉这软件挺**的

### ISSUE THREAD

**Issue by huke3014** [lyswhut/lx-music-desktop#1396]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

所见即所得，不管软件界面处于何种状态，播放列表就是我所见到的，就是我现在看到的列表就是现在我希望播放的列表.

### 实际行为

例如我切换到不同的频道看到的不同的列表，那么它就是现在的播放列表。而这个软件的播放列表除了自定义的列表能正常播放外，其他列表完全乱播放的，我不认为我有什么错，我检出认为所见即所得这一原则没有错误，我不会更改自己的操作习惯，也不会研究这个软件的播放设置，我任然坚持我的原则：所见即所得

### Lx Music 版本

2.0.4

### 最后正常的版本

2.0.4

### 操作系统版本

WIN10

**Comment by lyswhut** [comment]
那这确实不适合你，卸载不用就好了

**Comment by Folltoshe** [comment]
乐
