### ISSUE TITLE
UI显示异常

### ISSUE THREAD

**Issue by czghzc** [lyswhut/lx-music-desktop#14]
Win7 32位系统 下载 lx-music-desktop-v0.5.0-win_x86-green
打开程序后,界面没有规律的显示不出来,或者部分显示
请查看下面的动画截图
![界面显示异常](https://user-images.githubusercontent.com/23645596/64317621-dab36e80-cfea-11e9-9495-c7025424c8e9.gif)

**Comment by lyswhut** [comment]
win7需要开启**透明效果**，不然界面将会异常，开启方法请自行百度

**Comment by czghzc** [comment]
哦,是的,确实这样,开启Aero主题效果后就没问题了,谢谢你
