### ISSUE TITLE
【界面一会显示一会不显示的，显示不全】

### ISSUE THREAD

**Issue by Crazyalllife** [lyswhut/lx-music-desktop#140]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

【界面有时候显示，有时候不显示，鼠标点过的地方显示 不点的不显示】

**预期行为**
【界面一会显示一会不显示的，显示不全】

**截图**
![image](https://user-images.githubusercontent.com/22719751/75307536-eccde580-5886-11ea-9180-fe2a1f954ef1.png)
![image](https://user-images.githubusercontent.com/22719751/75307566-01aa7900-5887-11ea-9e20-af3d853e8dcc.png)
![image](https://user-images.githubusercontent.com/22719751/75307598-11c25880-5887-11ea-976c-f117427ff668.png)

**环境：**
  -操作系统及版本：【Windows 7 64位 pack1】
  -软件安装包及版本：【lx-music-desktop-v0.16.0-win_x64-green.7z】

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lsyyktv** [comment]
切换AERO主题就行了

**Comment by lyswhut** [comment]
提问前请先完成**解决方案检查**
