### ISSUE TITLE
[Bug]: Mac OS Monterey Apple M1无法安装2.2

### ISSUE THREAD

**Issue by liuchangfitcloud** [lyswhut/lx-music-desktop#1408]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装成功

### 实际行为

文件已损坏

### Lx Music 版本

2.2

### 最后正常的版本

2.2

### 操作系统版本

Mac OS Monterey 12.2.1

### 附加信息

提示文件已损坏无法安装

**Comment by fengxingxiang** [comment]
me too

**Comment by wangkang375** [comment]
刚试了下
  **lx-music-desktop-2.3.0.dmg**
你是否下错版本
