### ISSUE TITLE
[Bug]: 自己列表中已经存在的歌曲，再次搜索添加，还是可以加进去。

### ISSUE THREAD

**Issue by thanksDay** [lyswhut/lx-music-desktop#1412]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

当我添加了该音乐之后，再次搜索并添加的时候，不能再继续添加到相同列表

### 实际行为

当我添加了该音乐之后，再次搜索并添加的时候，还可以继续添加到相同列表

### Lx Music 版本

2.2.2

### 操作系统版本

Windows 10 家庭版

**Comment by helloplhm-qwq** [comment]
请问两次是不是不在同一个源
如果是同一个源的同一首歌是不能重复添加的

**Comment by thanksDay** [comment]
> 

 啊对，不是同一个源。。。

**Comment by thanksDay** [comment]
不过三克油了 我晓得 选中一个源就好 嘿嘿

**Comment by helloplhm-qwq** [comment]
提醒一句，不同源的相同歌曲可以右键列表中的`重复歌曲`功能手动剔除

**Comment by thanksDay** [comment]
> 提醒一句，不同源的相同歌曲可以右键列表中的`重复歌曲`功能手动剔除

好滴好滴 三克油 哈哈哈哈
