### ISSUE TITLE
[Bug]: Mac端部分音乐可以加载，但没有声音

### ISSUE THREAD

**Issue by york2333** [lyswhut/lx-music-desktop#1423]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

所有歌曲都能正常加载并正常播放

### 实际行为

部分源的歌曲（大部分为酷狗）在Mac端上**可以加载，但没有声音**，音频可视化没有一丝波动，但歌词、专辑封面正常运作，**已尝试过清缓存、卸载重装但无果**，而且**这些歌在安卓端（亦为最新版）上可以正常播放**，两端均使用测试接口
虽然可以通过手动换酷我源解决，但这样真的很麻烦，而且由于不能手动改歌词，一些外文歌翻译都没了，加之某些歌某一平台独占，其他平台听不到，麻烦改进，谢谢🙏

### Lx Music 版本

2.2.2

### 操作系统版本

macOS Ventura 13.4.1 (22F82)

### 附加信息

目前发现出此问题的歌曲（均为酷狗源）：刘德华《恭喜发财》，米津玄师《Lemon》，周杰伦《牛仔很忙》《听妈妈的话》，高橋優《ヤキモチ》，松任谷由実《ルージュの伝言》（这应该只是一部分，我没有办法每首歌都查过去，或许因为这些歌要收费？）
<img width="492" alt="截屏2023-06-24 09 27 27" src="https://github.com/lyswhut/lx-music-desktop/assets/78467289/0bf72d21-1d25-4e8d-b8cf-171db6de22f1">

**Comment by lyswhut** [comment]
没声音的时候处于播放状态且进度条在动？试试最新的beta版 https://github.com/lyswhut/lx-music-desktop/actions

**Comment by york2333** [comment]
> 没声音的时候处于播放状态且进度条在动？试试最新的beta版 https://github.com/lyswhut/lx-music-desktop/actions

非常感谢，修好了，但是Beta版可能有其他稳定性问题，肯定不是长久之计，建议先发一个正式版把这个bug修了，谢谢🙏

**Comment by york2333** [comment]
由于2.3.0正式版已发布，先把这个issue close了
