### ISSUE TITLE
希望下载列表可以倒序排列或添加按不同方式进行排序的功能

### ISSUE THREAD

**Issue by EquinoxFlowerJG** [lyswhut/lx-music-desktop#143]
如题，希望可以添加下载列表按下载时间倒序排列功能（既最新下载的在最上方）。

或者直接添加多种排序方式，比如按歌曲名和品质排序。

**Comment by lyswhut** [comment]
什么情况下要用到该功能？

**Comment by EquinoxFlowerJG** [comment]
在查看下载记录时，最新下载的歌曲每次都要把滚动条拖到最后才能看到。一般的软件下载目录都是最新的在最上面。









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyswhut"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 中午11:42
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;; 
抄送: "　"<958539194@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lyswhut/lx-music-desktop] 希望下载列表可以倒序排列或添加按不同方式进行排序的功能 (#143)




什么情况下要用到该功能？

**Comment by EquinoxFlowerJG** [comment]
> 什么情况下要用到该功能？

或者也可以按照不同条件各加个排序功能，可以正序排列，也可以倒序排列。

**Comment by lyswhut** [comment]
考虑到排序功能用处不大，下个版本的下载列表将改为倒序显示

**Comment by EquinoxFlowerJG** [comment]
嗯，加上倒序之后查看下载列表的时候就会好多了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyswhut"<notifications@github.com&gt;; 
发送时间: 2020年3月12日(星期四) 晚上11:22
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;; 
抄送: "　"<958539194@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lyswhut/lx-music-desktop] 希望下载列表可以倒序排列或添加按不同方式进行排序的功能 (#143)





 
考虑到排序功能用处不大，下个版本的下载列表将改为倒序显示

**Comment by lyswhut** [comment]
已在`0.17.0`将任务的添加方式改为顶部插入
