### ISSUE TITLE
[Feature]: 建议增加设置总是显示音量控制条

### ISSUE THREAD

**Issue by yzq0419** [lyswhut/lx-music-desktop#1442]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议增加设置总是显示音量控制条，像1.22.3以前那样在播放区域总是显示音量控制条。

### 描述你想要的解决方案

建议增加设置总是显示音量控制条，像1.22.3以前那样在播放区域总是显示音量控制条。

### 描述你考虑过的替代方案

建议增加设置总是显示音量控制条，像1.22.3以前那样在播放区域总是显示音量控制条。

### 附加信息

建议增加设置总是显示音量控制条，像1.22.3以前那样在播放区域总是显示音量控制条。

**Comment by lyswhut** [comment]
新的UI需要去习惯，鼠标移上去音量条就会弹出来，若实在不习惯可使用旧版本
