### ISSUE TITLE
[Feature]: 功能建议

### ISSUE THREAD

**Issue by ThisVant** [lyswhut/lx-music-desktop#1443]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议app端添加定时关闭功能

### 描述你想要的解决方案

建议app端添加定时关闭功能

**Comment by lyswhut** [comment]
设置-基本设置-定时暂停
