### ISSUE TITLE
[Bug]: 刚检出运行就报错

### ISSUE THREAD

**Issue by aliciz** [lyswhut/lx-music-desktop#1447]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

npm install

npm run dev

### 实际行为

`
WARNING
[eslint] ]1337;CurrentDir=E:\vscode_workspace\lx-music-desktop

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\components\layout\PlayDetail\components\MusicComment\CommentFloor.vue:14:65
     12 |               div(:class="$style.metaInfo")
     13 |                 time(v-if="item.timeStr" :class="$style.label") {{ timeFormat(item.timeStr) }}
   > 14 |                 div(v-if="item.location" :class="$style.label") {{$t('comment__location', { location: item.location })}}
        |                                                                 ^
     15 |             div(v-if="item.likedCount != null" :class="$style.likes")
     16 |               svg(:class="$style.likesIcon" version="1.1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" space="preserve")
     17 |                 use(xlink:href="#icon-thumbs-up")

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\components\layout\PlayDetail\components\MusicComment\CommentFloor.vue:14:119
     12 |               div(:class="$style.metaInfo")
     13 |                 time(v-if="item.timeStr" :class="$style.label") {{ timeFormat(item.timeStr) }}
   > 14 |                 div(v-if="item.location" :class="$style.label") {{$t('comment__location', { location: item.location })}}
        |                                                                                                                       ^
     15 |             div(v-if="item.likedCount != null" :class="$style.likes")
     16 |               svg(:class="$style.likesIcon" version="1.1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" space="preserve")
     17 |                 use(xlink:href="#icon-thumbs-up")

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\components\layout\PlayDetail\components\MusicComment\CommentFloor.vue:18:17
     16 |               svg(:class="$style.likesIcon" version="1.1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" space="preserve")
     17 |                 use(xlink:href="#icon-thumbs-up")
   > 18 |               | {{item.likedCount}}
        |                 ^
     19 |           p.select(:class="$style.comment_text") {{ item.text }}
     20 |           div(v-if="item.images?.length" :class="$style.comment_images")
     21 |             img(v-for="(url, index) in item.images" :key="index" :src="url" loading="lazy" decoding="async")

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\components\layout\PlayDetail\components\MusicComment\CommentFloor.vue:18:34
     16 |               svg(:class="$style.likesIcon" version="1.1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" space="preserve")
     17 |                 use(xlink:href="#icon-thumbs-up")
   > 18 |               | {{item.likedCount}}
        |                                  ^
     19 |           p.select(:class="$style.comment_text") {{ item.text }}
     20 |           div(v-if="item.images?.length" :class="$style.comment_images")
     21 |             img(v-for="(url, index) in item.images" :key="index" :src="url" loading="lazy" decoding="async")

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\components\layout\PlayDetail\components\MusicComment\index.vue:36:9
     34 |               material-pagination(:count="newComment.total" :btn-length="5" :limit="newComment.limit" :page="newComment.page" @btn-click="handleToggleCommentPage")
     35 |     div(v-else :class="$style.unavailable")
   > 36 |       p {{$t('comment__unavailable')}}
        |         ^
     37 | </template>
     38 | 
     39 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\components\layout\PlayDetail\components\MusicComment\index.vue:36:37
     34 |               material-pagination(:count="newComment.total" :btn-length="5" :limit="newComment.limit" :page="newComment.page" @btn-click="handleToggleCommentPage")
     35 |     div(v-else :class="$style.unavailable")
   > 36 |       p {{$t('comment__unavailable')}}
        |                                     ^
     37 | </template>
     38 | 
     39 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\components\layout\PlayDetail\index.vue:47:70
     45 |             p {{ $t('player__music_name') }}{{ musicInfo.name }}
     46 |             p {{ $t('player__music_singer') }}{{ musicInfo.singer }}
   > 47 |             p(v-if="musicInfo.album") {{ $t('player__music_album') }}{{musicInfo.album}}
        |                                                                      ^
     48 | 
     49 |       transition(enter-active-class="animated fadeIn" leave-active-class="animated fadeOut")
     50 |         LyricPlayer(v-if="visibled")

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\components\layout\PlayDetail\index.vue:47:87
     45 |             p {{ $t('player__music_name') }}{{ musicInfo.name }}
     46 |             p {{ $t('player__music_singer') }}{{ musicInfo.singer }}
   > 47 |             p(v-if="musicInfo.album") {{ $t('player__music_album') }}{{musicInfo.album}}
        |                                                                                       ^
     48 | 
     49 |       transition(enter-active-class="animated fadeIn" leave-active-class="animated fadeOut")
     50 |         LyricPlayer(v-if="visibled")

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\PlayTimeoutModal.vue:12:11
     10 |         base-checkbox(id="play_timeout_end" :model-value="appSetting['player.waitPlayEndStop']" :label="$t('play_timeout_end')" @update:model-value="updateSetting({'player.waitPlayEndStop': $event})")
     11 |       div(:class="[$style.row, $style.tip, { [$style.show]: !!timeLabel }]")
   > 12 |         p {{$t('play_timeout_tip', { time: timeLabel })}}
        |           ^
     13 |     div(:class="$style.footer")
     14 |         base-btn(:class="$style.footerBtn" @click="handleCancel") {{ $t(timeLabel ? 'play_timeout_stop' : 'play_timeout_close') }}
     15 |         base-btn(:class="$style.footerBtn" @click="handleConfirm") {{$t(timeLabel ? 'play_timeout_update' : 'play_timeout_confirm')}}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\PlayTimeoutModal.vue:12:56
     10 |         base-checkbox(id="play_timeout_end" :model-value="appSetting['player.waitPlayEndStop']" :label="$t('play_timeout_end')" @update:model-value="updateSetting({'player.waitPlayEndStop': $event})")
     11 |       div(:class="[$style.row, $style.tip, { [$style.show]: !!timeLabel }]")
   > 12 |         p {{$t('play_timeout_tip', { time: timeLabel })}}
        |                                                        ^
     13 |     div(:class="$style.footer")
     14 |         base-btn(:class="$style.footerBtn" @click="handleCancel") {{ $t(timeLabel ? 'play_timeout_stop' : 'play_timeout_close') }}
     15 |         base-btn(:class="$style.footerBtn" @click="handleConfirm") {{$t(timeLabel ? 'play_timeout_update' : 'play_timeout_confirm')}}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\PlayTimeoutModal.vue:15:68
     13 |     div(:class="$style.footer")
     14 |         base-btn(:class="$style.footerBtn" @click="handleCancel") {{ $t(timeLabel ? 'play_timeout_stop' : 'play_timeout_close') }}
   > 15 |         base-btn(:class="$style.footerBtn" @click="handleConfirm") {{$t(timeLabel ? 'play_timeout_update' : 'play_timeout_confirm')}}
        |                                                                    ^
     16 | </template>
     17 | 
     18 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\PlayTimeoutModal.vue:15:132
     13 |     div(:class="$style.footer")
     14 |         base-btn(:class="$style.footerBtn" @click="handleCancel") {{ $t(timeLabel ? 'play_timeout_stop' : 'play_timeout_close') }}
   > 15 |         base-btn(:class="$style.footerBtn" @click="handleConfirm") {{$t(timeLabel ? 'play_timeout_update' : 'play_timeout_confirm')}}
        |                                                                                                                                    ^
     16 | </template>
     17 | 
     18 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingBackup.vue:9:61
      7 |     base-btn.btn.gap-left(min @click="handleExportPlayList") {{ $t('setting__backup_part_export_list') }}
      8 |     base-btn.btn.gap-left(min @click="handleImportSetting") {{ $t('setting__backup_part_import_setting') }}
   >  9 |     base-btn.btn.gap-left(min @click="handleExportSetting") {{$t('setting__backup_part_export_setting')}}
        |                                                             ^
     10 | dd
     11 |   h3#backup_all {{ $t('setting__backup_all') }}
     12 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingBackup.vue:9:104
      7 |     base-btn.btn.gap-left(min @click="handleExportPlayList") {{ $t('setting__backup_part_export_list') }}
      8 |     base-btn.btn.gap-left(min @click="handleImportSetting") {{ $t('setting__backup_part_import_setting') }}
   >  9 |     base-btn.btn.gap-left(min @click="handleExportSetting") {{$t('setting__backup_part_export_setting')}}
        |                                                                                                        ^
     10 | dd
     11 |   h3#backup_all {{ $t('setting__backup_all') }}
     12 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingBackup.vue:14:61
     12 |   div
     13 |     base-btn.btn.gap-left(min @click="handleImportAllData") {{ $t('setting__backup_all_import') }}
   > 14 |     base-btn.btn.gap-left(min @click="handleExportAllData") {{$t('setting__backup_all_export')}}
        |                                                             ^
     15 | dd
     16 |   h3#backup_other {{ $t('setting__backup_other') }}
     17 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingBackup.vue:14:95
     12 |   div
     13 |     base-btn.btn.gap-left(min @click="handleImportAllData") {{ $t('setting__backup_all_import') }}
   > 14 |     base-btn.btn.gap-left(min @click="handleExportAllData") {{$t('setting__backup_all_export')}}
        |                                                                                               ^
     15 | dd
     16 |   h3#backup_other {{ $t('setting__backup_other') }}
     17 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingBackup.vue:19:67
     17 |   div
     18 |     base-btn.btn.gap-left(min @click="handleExportPlayListToText") {{ $t('setting__backup_other_export_list_text') }}
   > 19 |     base-btn.btn.gap-left(min @click="handleExportPlayListToCsv") {{$t('setting__backup_other_export_list_csv')}}
        |                                                                   ^
     20 | </template>
     21 | 
     22 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingBackup.vue:19:112
     17 |   div
     18 |     base-btn.btn.gap-left(min @click="handleExportPlayListToText") {{ $t('setting__backup_other_export_list_text') }}
   > 19 |     base-btn.btn.gap-left(min @click="handleExportPlayListToCsv") {{$t('setting__backup_other_export_list_csv')}}
        |                                                                                                                ^
     20 | </template>
     21 | 
     22 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingBasic.vue:23:37
     21 |           div(:class="$style.bgContent")
     22 |             svg-icon(:class="$style.icon" name="plus")
   > 23 |         span(:class="$style.label") {{$t('theme_add')}}
        |                                     ^
     24 | 
     25 | dd
     26 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingBasic.vue:23:54
     21 |           div(:class="$style.bgContent")
     22 |             svg-icon(:class="$style.icon" name="plus")
   > 23 |         span(:class="$style.label") {{$t('theme_add')}}
        |                                                      ^
     24 | 
     25 | dd
     26 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingBasic.vue:46:60
     44 |         need :model-value="appSetting['common.apiSource']" :disabled="item.disabled" :value="item.id" :label="item.label" @update:model-value="updateSetting({'common.apiSource': $event})")
     45 |     .p.gap-top
   > 46 |       base-btn.btn(min @click="isShowUserApiModal = true") {{$t('setting__basic_source_user_api_btn')}}
        |                                                            ^
     47 | 
     48 | dd
     49 |   h3#basic_window_size {{ $t('setting__basic_window_size') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingBasic.vue:46:102
     44 |         need :model-value="appSetting['common.apiSource']" :disabled="item.disabled" :value="item.id" :label="item.label" @update:model-value="updateSetting({'common.apiSource': $event})")
     45 |     .p.gap-top
   > 46 |       base-btn.btn(min @click="isShowUserApiModal = true") {{$t('setting__basic_source_user_api_btn')}}
        |                                                                                                      ^
     47 | 
     48 | dd
     49 |   h3#basic_window_size {{ $t('setting__basic_window_size') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingDesktopLyric.vue:63:51
     61 |     .p
     62 |       base-btn.btn(min @click="changeLineGap(-1)") {{ $t('setting__desktop_lyric_line_gap_dec') }}
   > 63 |       base-btn.btn(min @click="changeLineGap(1)") {{$t('setting__desktop_lyric_line_gap_add')}}
        |                                                   ^
     64 | dd
     65 |   h3#desktop_lyric_color {{ $t('setting__desktop_lyric_color') }}
     66 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingDesktopLyric.vue:63:94
     61 |     .p
     62 |       base-btn.btn(min @click="changeLineGap(-1)") {{ $t('setting__desktop_lyric_line_gap_dec') }}
   > 63 |       base-btn.btn(min @click="changeLineGap(1)") {{$t('setting__desktop_lyric_line_gap_add')}}
        |                                                                                              ^
     64 | dd
     65 |   h3#desktop_lyric_color {{ $t('setting__desktop_lyric_color') }}
     66 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingDesktopLyric.vue:79:45
     77 |           div(:class="$style.label") {{ $t('setting__desktop_lyric_shadow_color') }}
     78 |     .p.gap-top
   > 79 |       base-btn.btn(min @click="resetColor") {{$t('setting__desktop_lyric_color_reset')}}
        |                                             ^
     80 | dd
     81 |   h3#desktop_lyric_font {{ $t('setting__desktop_lyric_font') }}
     82 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingDesktopLyric.vue:79:87
     77 |           div(:class="$style.label") {{ $t('setting__desktop_lyric_shadow_color') }}
     78 |     .p.gap-top
   > 79 |       base-btn.btn(min @click="resetColor") {{$t('setting__desktop_lyric_color_reset')}}
        |                                                                                       ^
     80 | dd
     81 |   h3#desktop_lyric_font {{ $t('setting__desktop_lyric_font') }}
     82 |   div

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingDesktopLyric.vue:89:53
     87 |   div
     88 |     .p.gap-top
   > 89 |       base-btn.btn(min @click="resetWindowSetting") {{$t('setting__desktop_lyric_reset_window')}}
        |                                                     ^
     90 | 
     91 | </template>
     92 | 

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingDesktopLyric.vue:89:96
     87 |   div
     88 |     .p.gap-top
   > 89 |       base-btn.btn(min @click="resetWindowSetting") {{$t('setting__desktop_lyric_reset_window')}}
        |                                                                                                ^
     90 | 
     91 | </template>
     92 | 

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingDownload.vue:15:55
     13 |       span.auto-hidden.hover(:class="$style.savePath" :aria-label="$t('setting__download_path_open_label')" @click="openDirInExplorer(appSetting['download.savePath'])") {{ appSetting['download.savePath'] }}
     14 |     .p
   > 15 |       base-btn.btn(min @click="handleChangeSavePath") {{$t('setting__download_path_change_btn')}}
        |                                                       ^
     16 | dd
     17 |   h3#download_use_other_source
     18 |     | {{ $t('setting__download_use_other_source') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingDownload.vue:15:96
     13 |       span.auto-hidden.hover(:class="$style.savePath" :aria-label="$t('setting__download_path_open_label')" @click="openDirInExplorer(appSetting['download.savePath'])") {{ appSetting['download.savePath'] }}
     14 |     .p
   > 15 |       base-btn.btn(min @click="handleChangeSavePath") {{$t('setting__download_path_change_btn')}}
        |                                                                                                ^
     16 | dd
     17 |   h3#download_use_other_source
     18 |     | {{ $t('setting__download_use_other_source') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingOther.vue:18:94
     16 |       span.auto-hidden {{ cacheSize }}
     17 |     .p
   > 18 |       base-btn.btn(min :disabled="isDisabledResourceCacheClear" @click="clearResourceCache") {{$t('setting__other_resource_cache_clear_btn')}}
        |                                                                                              ^
     19 | 
     20 | dd
     21 |   h3#other_other_source {{ $t('setting__other_other_cache') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingOther.vue:18:141
     16 |       span.auto-hidden {{ cacheSize }}
     17 |     .p
   > 18 |       base-btn.btn(min :disabled="isDisabledResourceCacheClear" @click="clearResourceCache") {{$t('setting__other_resource_cache_clear_btn')}}
        |                                                                                                                                             ^
     19 | 
     20 | dd
     21 |   h3#other_other_source {{ $t('setting__other_other_cache') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingOther.vue:35:100
     33 |       base-btn.btn(min :disabled="isDisabledOtherSourceCacheClear" @click="handleClearOtherSourceCache") {{ $t('setting__other_other_source_clear_btn') }}
     34 |       base-btn.btn(min :disabled="isDisabledMusicUrlCacheClear" @click="handleClearMusicUrlCache") {{ $t('setting__other_music_url_clear_btn') }}
   > 35 |       base-btn.btn(min :disabled="isDisabledLyricRawCacheClear" @click="handleClearLyricRawCache") {{$t('setting__other_lyric_raw_clear_btn')}}
        |                                                                                                    ^
     36 | 
     37 | dd
     38 |   h3#other_lyric_edited {{ $t('setting__other_lyric_edited_cache') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingOther.vue:35:142
     33 |       base-btn.btn(min :disabled="isDisabledOtherSourceCacheClear" @click="handleClearOtherSourceCache") {{ $t('setting__other_other_source_clear_btn') }}
     34 |       base-btn.btn(min :disabled="isDisabledMusicUrlCacheClear" @click="handleClearMusicUrlCache") {{ $t('setting__other_music_url_clear_btn') }}
   > 35 |       base-btn.btn(min :disabled="isDisabledLyricRawCacheClear" @click="handleClearLyricRawCache") {{$t('setting__other_lyric_raw_clear_btn')}}
        |                                                                                                                                              ^
     36 | 
     37 | dd
     38 |   h3#other_lyric_edited {{ $t('setting__other_lyric_edited_cache') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingOther.vue:44:106
     42 |       span.auto-hidden {{ lyricEditedCount }}
     43 |     .p
   > 44 |       base-btn.btn(min :disabled="isDisabledLyricEditedCacheClear" @click="handleClearLyricEditedCache") {{$t('setting__other_lyric_edited_clear_btn')}}
        |                                                                                                          ^
     45 | 
     46 | dd
     47 |   h3#other_lyric_edited {{ $t('setting__other_listdata') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingOther.vue:44:151
     42 |       span.auto-hidden {{ lyricEditedCount }}
     43 |     .p
   > 44 |       base-btn.btn(min :disabled="isDisabledLyricEditedCacheClear" @click="handleClearLyricEditedCache") {{$t('setting__other_lyric_edited_clear_btn')}}
        |                                                                                                                                                       ^
     45 | 
     46 | dd
     47 |   h3#other_lyric_edited {{ $t('setting__other_listdata') }}

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingOther.vue:50:54
     48 |   div
     49 |     .p
   > 50 |       base-btn.btn(min @click="handleClearListData") {{$t('setting__other_listdata_clear_btn')}}
        |                                                      ^
     51 | 
     52 | </template>
     53 | 

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingOther.vue:50:95
     48 |   div
     49 |     .p
   > 50 |       base-btn.btn(min @click="handleClearListData") {{$t('setting__other_listdata_clear_btn')}}
        |                                                                                               ^
     51 | 
     52 | </template>
     53 | 

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingUpdate.vue:22:61
     20 |         span {{ $t('setting__update_new_version') }}
     21 |       .p
   > 22 |         base-btn.btn.gap-left(min @click="showUpdateModal") {{$t('setting__update_open_version_modal_btn')}}
        |                                                             ^
     23 |     .p.small(v-else-if="versionInfo.status =='checking'") {{$t('setting__update_checking')}}
     24 | </template>
     25 | 

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingUpdate.vue:22:107
     20 |         span {{ $t('setting__update_new_version') }}
     21 |       .p
   > 22 |         base-btn.btn.gap-left(min @click="showUpdateModal") {{$t('setting__update_open_version_modal_btn')}}
        |                                                                                                           ^
     23 |     .p.small(v-else-if="versionInfo.status =='checking'") {{$t('setting__update_checking')}}
     24 | </template>
     25 | 

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space after '{{', but not found

     src\renderer\views\Setting\components\SettingUpdate.vue:23:59
     21 |       .p
     22 |         base-btn.btn.gap-left(min @click="showUpdateModal") {{$t('setting__update_open_version_modal_btn')}}
   > 23 |     .p.small(v-else-if="versionInfo.status =='checking'") {{$t('setting__update_checking')}}
        |                                                           ^
     24 | </template>
     25 | 
     26 | <script>

  ⚠  https://google.com/search?q=vue%2Fmustache-interpolation-spacing

     Expected 1 space before '}}', but not found

     src\renderer\views\Setting\components\SettingUpdate.vue:23:91
     21 |       .p
     22 |         base-btn.btn.gap-left(min @click="showUpdateModal") {{$t('setting__update_open_version_modal_btn')}}
   > 23 |     .p.small(v-else-if="versionInfo.status =='checking'") {{$t('setting__update_checking')}}
        |                                                                                           ^
     24 | </template>
     25 | 
     26 | <script>

✘ 42 problems (0 errors, 42 warnings)

Warnings:
  42  https://google.com/search?q=vue%2Fmustache-interpolation-spacing
`

### Lx Music 版本

2.3.0

### 操作系统版本

win11

### 附加信息

node:  v16.20.1

**Comment by lyswhut** [comment]
不知道出于什么原因，我这边的环境没有报这个错，正常情况应该会报这个错才对 :(
对于有这个问题的人可以执行下 `npm run lint:fix` 即可修复

**Comment by aliciz** [comment]
还是不行，这次报这个：
`
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.
`

**Comment by lyswhut** [comment]
这个只是警告，不用管它，直接忽略

**Comment by aliciz** [comment]
可以了，谢谢
