### ISSUE TITLE
[Feature]:  关于本地文件歌词搜索的建议

### ISSUE THREAD

**Issue by ChenKe404** [lyswhut/lx-music-desktop#1448]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

本地音乐中没有作品信息的文件无法获取到歌词。

### 描述你想要的解决方案

从文件名中获取歌手和歌名，两者用"-"分割，但有些歌手名在前，有些在后，所以当前一种情况获取失败再换后一种获取，都失败的话，那就失败吧。

建议先从文件名获取歌手和歌名，其次再从文件中读。因为文件名一般都是正确的信息，而文件中的信息往往因为文件来源可能包含不重要或错误的信息。如从酷我上下载的很多音乐作者和歌名都是“kuwo”。

**Comment by lyswhut** [comment]
暂无计划这样处理，建议使用 mp3tag 重新编辑歌词标签信息，它可以批量从文件名取信息写入标签
