### ISSUE TITLE
[Bug]: Arm64下无法运行lx-music-desktop

### ISSUE THREAD

**Issue by fos236** [lyswhut/lx-music-desktop#1451]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

可以正常运行lx-music-desktop

### 实际行为

无法运行lx-music-desktop，命令行下运行报错:
./lx-music-desktop: symbol lookup error: ./lx-music-desktop: undefined symbol: gbm_bo_map

### Lx Music 版本

2.3.0

### 操作系统版本

Linux hw-liu 4.19.71-arm64-desktop #5500.57055.1 SMP PREEMPT Thu May 18 11:05:23 CST 2023 aarch64 GNU/Linux

**Comment by lyswhut** [comment]
这不是LX的问题，是你系统环境问题导致，自行检索 ` undefined symbol: gbm_bo_map` 找解决方案

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/1215
