### ISSUE TITLE
[Bug]: 2.3.0版本安装包安装之后文件内只有卸载安装包文件

### ISSUE THREAD

**Issue by moonlightlang** [lyswhut/lx-music-desktop#1457]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

windows10 2.3.0正常安装完成

### 实际行为

2.3安装包执行完成，目录里面只留下了 Uninstall lx-music-desktop.exe，其他一个文件都没有

### Lx Music 版本

2.3.0-arm64

### 操作系统版本

Windows10

**Comment by safarishi** [comment]
我也遇到了同样能的问题

**Comment by safarishi** [comment]
我知道我我啥不行了，因为选择的下载文件不对
1 下载了 lx-music-destop-v2.3.0-arm64-Setup.exe 安装后运行只剩下 卸载文件 也无法正常打开
1 下载了 lx-music-destop-v2.3.0-x64-Setup.exe 安装后运行可正常使用了
