### ISSUE TITLE
[Feature]: 建议为自动更新增加加速源

### ISSUE THREAD

**Issue by LSP0123** [lyswhut/lx-music-desktop#1459]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

当前自动更新从github的release拉取，更新速度极慢，建议添加加速源，例如：

`https://gh.con.sh/https://github.com/lyswhut/lx-music-desktop/releases/download/v2.3.0/lx-music-desktop-v2.3.0-x64-Setup.exe`

或者

`https://cors.isteed.cc/github.com/lyswhut/lx-music-desktop/releases/download/v2.3.0/lx-music-desktop-v2.3.0-x64-Setup.exe`

### 描述你想要的解决方案

为自动更新添加CloudflareCDN或其它CDN

**Comment by Reminiserces** [comment]
可以考虑，但是不保证会实现。

**Comment by LSP0123** [comment]
> 可以考虑，但是不保证会实现。

感谢
