### ISSUE TITLE
希望增加下载管理选项

### ISSUE THREAD

**Issue by lymmmx** [lyswhut/lx-music-desktop#146]
希望增加下载管理选项，仅下载任务而不删除文件。目前删除下载任务会删除已下载的MP3文件。谢谢！

**Comment by lyswhut** [comment]
详情看`0.16.0`的[更新日志](https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md#0160---2020-02-16)
> 修复移除暂停、错误的任务时不删除未下载完成的文件的问题

如果该机制未按预期工作，你可以说明系统、重现步骤、截图等相关信息
