### ISSUE TITLE
[Bug]: 如果安装路径包含特殊符号：'#'，软件会打开失败

### ISSUE THREAD

**Issue by YSun-Top** [lyswhut/lx-music-desktop#1461]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

软件正常启动

### 实际行为

软件启动后没有出现UI界面

### Lx Music 版本

2.3.0

### 操作系统版本

Windows10

### 附加信息

如果安装路径包含特殊符号：'#'，软件会打开失败

失败场景：
E:\#Software\lx-music-desktop

成功场景：
E:\Software\lx-music-desktop

**Comment by lyswhut** [comment]
已在v2.4.0修复
