### ISSUE TITLE
一边听一边下载在听的歌

### ISSUE THREAD

**Issue by linzzzzllll** [lyswhut/lx-music-desktop#1468]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

一边听一边下载在听的歌

### 描述你想要的解决方案

一边听一边下载在听的歌

### 描述你考虑过的替代方案

一边听一边下载在听的歌

### 附加信息

一边听一边下载在听的歌

**Comment by lyswhut** [comment]
按目前的播放器实现方式，该功能无法实现，而且该功能意义不大，无计划实现
