### ISSUE TITLE
[Feature]: 软件的更新窗口添加隐藏按钮

### ISSUE THREAD

**Issue by SeaRat** [lyswhut/lx-music-desktop#1469]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

软件内的更新窗口目前只有关闭按钮，点击关闭按钮后可能停止下载更新

### 描述你想要的解决方案

增加隐藏按钮，隐藏更新窗口后在后台继续下载更新

**Comment by Reminiserces** [comment]
![QQ截图20230714191227](https://github.com/lyswhut/lx-music-desktop/assets/87899500/bd902939-b6d8-4692-a1b4-1de6dfb83a59)关闭此选项  使用仓库或者网盘更新

**Comment by lyswhut** [comment]
那个关闭按钮的功能只是隐藏窗口，关闭窗口后下载任务仍会继续，可到设置-软件更新重新打开
