### ISSUE TITLE
希望增加修改字体大小的功能

### ISSUE THREAD

**Issue by ilikeulinux** [lyswhut/lx-music-desktop#147]
我现在用的是2K高分辨率显示器，列表里的字很小，看着非常费眼。希望作者可以考虑增加一个修改字体大小的功能，方便我们这些视力不好的人，谢谢啦～～

**Comment by lyswhut** [comment]
下个版本将新增软件内的包括字体在内的界面内容大小调整，**当窗口大小切换到“大”时**，软件内的元素将会适当加大。

窗口大小的“小”与“中”内的元素将保持之前的大小暂不做改变

**Comment by lyswhut** [comment]
已在`0.17.0`中包含相关功能，详情看更新日志：https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md
