### ISSUE TITLE
[Bug]: 搜索栏输入后回车自动清空

### ISSUE THREAD

**Issue by hinatamiyabi** [lyswhut/lx-music-desktop#1472]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

搜索栏输入后回车搜索

### 实际行为

搜索栏输入后回车输入内容自动清空

### Lx Music 版本

2.3.0

### 最后正常的版本

我不知道，这个bug好久了一直没修复

### 操作系统版本

win11 25309.1

### 附加信息

搜索框输入后，无论是回车还是点击右边的搜索按钮都会清除我的输入内容，目前一直的解决方法是先复制一遍输入内容，再粘贴到搜索框，再按搜索按钮才能搜索生效，我不知道为什么这么一个严重的bug能存活这么多个版本

**Comment by lyswhut** [comment]
我这边无法重现你这个问题

**Comment by hinatamiyabi** [comment]
> 我这边无法重现你这个问题
我录了个视频可以看一下，貌似这个问题只会出现在日语输入法上
<iframe src="//player.bilibili.com/player.html?bvid=BV1ax4y1o7qQ&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>

**Comment by hinatamiyabi** [comment]
> 我这边无法重现你这个问题

我录了个视频可以看一下，貌似这个问题只会出现在日语输入法上
https://www.bilibili.com/video/BV1ax4y1o7qQ/

**Comment by lyswhut** [comment]
这是什么输入法？换个输入法会这样吗？

**Comment by hinatamiyabi** [comment]
> 这是什么输入法？换个输入法会这样吗？在我的列表`ctrl+f`打开的搜索框输入的内容会这样吗？

就是系统自带的微软日语输入法，Windows上日语输入法就这一个、
另外在我的列表ctrl+f打开的搜索框输入后回车虽不会清除输入内容，但是也无法显示搜索内容

**Comment by lyswhut** [comment]
歌曲搜索框会自动清空的问题下个版本修复，这是软件处理上下方向键事件中存在bug导致的，
在使用输入法的过程中你应该使用了上下方向键选字，当前版本的临时解决方案是不要使用方向键选字，使用`tab`键选

`ctrl+f` 打开的搜索框无法显示搜索内容的问题我这边未能重现

**Comment by lyswhut** [comment]
可以试试最新beta版是否已修复：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by hinatamiyabi** [comment]
> 可以试试最新beta版是否已修复：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

已经解决了，感谢

**Comment by lyswhut** [comment]
已在v2.4.0修复
