### ISSUE TITLE
音量键能否标示清楚些

### ISSUE THREAD

**Issue by baifalaoweng** [lyswhut/lx-music-desktop#148]
音量键能否标示清楚些，目前配色下，音量键关到最小，我都找不到音量在哪里了

**Comment by lyswhut** [comment]
就在下一首按钮的左侧啊，鼠标移上去会显示出来，之前调整过音量就证明你是知道音量条在哪的，这个应该影响不大吧

**Comment by lyswhut** [comment]
已在v0.18.0略微加深音量条背景颜色

**Comment by baifalaoweng** [comment]
好的
