### ISSUE TITLE
[Feature]: 希望增加系统托盘功能

### ISSUE THREAD

**Issue by mi0e** [lyswhut/lx-music-desktop#1484]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

想要歌曲播放控制的相关功能，比如暂停下一首，上一个issue在2020年 https://github.com/lyswhut/lx-music-desktop/issues/283#issue-675412716 

### 描述你想要的解决方案

1

**Comment by lyswhut** [comment]
去基本设置启用托盘，定时暂停按钮上面那个
