### ISSUE TITLE
[Feature]: 点击歌词跳转进度

### ISSUE THREAD

**Issue by fangyuan99** [lyswhut/lx-music-desktop#1492]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

点击某行歌词后，从这句开始播放

### 描述你想要的解决方案

是否可以根据歌词文件里的时间信息实现？

**Comment by orbitgw** [comment]
Same feature wanted

**Comment by realSilasYang** [comment]
+1 希望实现这个跳转功能

**Comment by fangyuan99** [comment]
设置里面有
![image](https://github.com/lyswhut/lx-music-desktop/assets/62874116/da1e889b-b9f1-4396-aeba-5fe3ef8e1430)
