### ISSUE TITLE
[Feature]: 由于不同平台lrc文件格式问题，部分平台音乐包含翻译的，在原歌词没有翻译时副歌词处显示“//”

### ISSUE THREAD

**Issue by xzhzhaowendao** [lyswhut/lx-music-desktop#1499]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

部分平台音乐包含翻译的，在歌曲没有副歌词时显示“//”，目前发现有tx、kw和mg。
tx：![egtx](https://github.com/lyswhut/lx-music-desktop/assets/132211598/4e77325f-15e2-453b-b390-4a158b2fab9a)
kw：![kw](https://github.com/lyswhut/lx-music-desktop/assets/132211598/6a21f2fc-6429-48c9-818e-9040da0e58ef)
tx：![tx2](https://github.com/lyswhut/lx-music-desktop/assets/132211598/ea709479-4d4f-444e-aaa8-b1506c7194c4)
mg：![mg](https://github.com/lyswhut/lx-music-desktop/assets/132211598/5cb60644-9f77-4f64-8f80-5172dbd71aba)

### 描述你想要的解决方案

希望可以实现对“//”空歌词一行的过滤，使之在播放时不显示“//”一行。
e.g.
Before:![compartx](https://github.com/lyswhut/lx-music-desktop/assets/132211598/877d7869-6f3e-46ae-a570-ef0089ef39f9)
After:![comparwy](https://github.com/lyswhut/lx-music-desktop/assets/132211598/287bd0c7-eca1-4ab4-8016-c1b675a97c63)

**Comment by lyswhut** [comment]
已在v2.4.0新增
