### ISSUE TITLE
是否有计划添加安卓手机端的支持？

### ISSUE THREAD

**Issue by linux0ne-su** [lyswhut/lx-music-desktop#150]
1、如题。这么好的软件，没有理由不在手机端存在呀，比如在酷安里投放呢？  强烈建议。

2、关于“源码使用”
npm run dev
npm run pack:dir
npm run pack

我不是太懂npm的使用规则，比如我要从源码构建在linux和windows下使用的最终程序，如何写命令？

3、Appimage是linux下的使用格式，这在安装的时候，用gdebi xx.Appimage么可以么？

**Comment by lyswhut** [comment]
1、移动端的问题看：https://github.com/lyswhut/lx-music-desktop/issues?q=%E7%A7%BB%E5%8A%A8%E7%AB%AF

2、构建程序的话，你需要配置相关环境，然后在项目目录下：
```bash
# 安装依赖
npm install

# 构建windows包
npm run pack 

# 构建Linux包
npm run publish:gh:linux
```
其他构建配置说明参见：https://www.electron.build/configuration/configuration
暂不提供其他技术支持，遇到问题需要你自行百度或Google

3、建议使用deb格式的包安装
