### ISSUE TITLE
[Feature]: 提议希望可以增加一下网易云的每日推荐

### ISSUE THREAD

**Issue by ichenshy** [lyswhut/lx-music-desktop#1505]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

感觉每日推荐还是不错的 不知道有没有可行性

### 描述你想要的解决方案

感觉每日推荐还是不错的 不知道有没有可行性

**Comment by JiZhiLieShou** [comment]
这个想法太赞了，不过怕不好实现

**Comment by 2630898337** [comment]
每日推荐感觉真不好整，私人雷达感觉也挺好的，我现在是用那个私人雷达代替每日推荐，网易云全部私人雷达导入进去然后设置每次启动软件更新就行，对了私人雷达每人网易云账户都不一样，复制分享链接后记得后面+###+token。根网易云“我喜欢”的导入一样的操作

**Comment by Lin-Ye-Ye** [comment]
> 每日推荐感觉真不好整，私人雷达感觉也挺好的，我现在是用那个私人雷达代替每日推荐，网易云全部私人雷达导入进去然后设置每次启动软件更新就行，对了私人雷达每人网易云账户都不一样，复制分享链接后记得后面+###+token。根网易云“我喜欢”的导入一样的操作

可以问问具体怎么操作嘛。。。

**Comment by sddpszz** [comment]
> > 每日推荐感觉真不好整，私人雷达感觉也挺好的，我现在是用那个私人雷达代替每日推荐，网易云全部私人雷达导入进去然后设置每次启动软件更新就行，对了私人雷达每人网易云账户都不一样，复制分享链接后记得后面+###+token。根网易云“我喜欢”的导入一样的操作
> 
> 可以问问具体怎么操作嘛。。。

先找到自己的雷达链接，比如这个：`https://music.163.com/#/playlist?id=3136952023`

然后按照[这个操作](https://lxmusic.toside.cn/desktop/faq/cannot-open-songlist)，找到自己的`MUSIC_U`

比如你找到的是`XXXXXXXXXXXX`

手动拼接成新的链接：``https://music.163.com/#/playlist?id=3136952023###XXXXXXXXXXXX`

把这个链接按照正常导入歌单的方式导入即可
