### ISSUE TITLE
添加Home, End功能的小建议

### ISSUE THREAD

**Issue by ricepeak** [lyswhut/lx-music-desktop#151]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
列表太长（下载管理和试听列表），只能用滚轮和右侧滚动条。能否添加home和end键的支持😂

**描述您考虑过的替代方案**
或者添加一个时间倒序

**其他内容**

**Comment by lyswhut** [comment]
为什么想要这样的功能？

**Comment by lyswhut** [comment]
点击封面可快速定位当前播放的歌曲，不知道你知不知道这个功能
