### ISSUE TITLE
[Feature]: 希望加一个一键打乱列表歌曲的功能

### ISSUE THREAD

**Issue by oohu123** [lyswhut/lx-music-desktop#1521]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前有自己手动移动歌曲位置，还有一键按照名字时长等排序歌曲的功能，但是自己手动去调又要很久，歌单有点大
用排序功能又不能完全打算，听的时候还是很多连续几首歌都是同一个歌手的
我想尽量避免连续三四首歌全是同一个歌手唱
这时候有的人可能会说用自带的随机播放功能，但是随机播放老是重复放啊
比如我上一首刚听完告白气球，第三首可能又随机到告白气球，而且重复率还挺高的
![QQ截图20230813161514](https://github.com/lyswhut/lx-music-desktop/assets/38876236/fec574f7-dd02-41a7-8488-65fc0809f627)

### 描述你想要的解决方案

出一个一键随机打乱歌曲播放顺序的功能就行

**Comment by lyswhut** [comment]
已在v2.4.0新增
