### ISSUE TITLE
没有序号显示，不知道列表里有多少项

### ISSUE THREAD

**Issue by homer-zhang** [lyswhut/lx-music-desktop#153]
建议增一个序号显示，尤其是下载的时候，没有序号不知道还有多少没有下载完成。
另外音量那个建议弄个小喇叭，鼠标放上去的时候用竖线来显示音量

**Comment by lyswhut** [comment]
1、显示序号的用处不大吧，等就完事了。。
2、暂不计划改进音量调节UI
