### ISSUE TITLE
[Feature]: 软件全局屏蔽功能

### ISSUE THREAD

**Issue by 52ifx** [lyswhut/lx-music-desktop#1538]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

你好，我平时喜欢在各大平台排行榜里听歌，但是经常听又会腻。

### 描述你想要的解决方案

所以，希望能够有一个能全局屏蔽功能。
能够屏蔽某个歌手
屏蔽某个歌曲

**Comment by lyswhut** [comment]
已在v2.4.0新增
