### ISSUE TITLE
下载出错的在下载任务里删除后无法再次添加下载

### ISSUE THREAD

**Issue by homer-zhang** [lyswhut/lx-music-desktop#154]
**描述错误**
下载出错的任务删除后无法再次添加下载

**重现**
重现行为的步骤：
1.转到“出错”的下载列表
2.点击“ 移除”
3.在搜索页面搜索到前面下载出错的歌曲
4.点击下载，选择音质
5.在下载任务列表里找不到刚添加的下载任务

**预期行为**
下载错误没什么，但是应该可以删除后重新下载。

**Comment by lyswhut** [comment]
正常情况下出错的歌曲移除后是可以正常重新添加下的，我无法重现出来，如果你知道怎么样重现，请描述得详细一点，比如下的哪首歌，软件版本是多少，什么情况下会出现该情况

**Comment by homer-zhang** [comment]
软件版本0.17.0
歌曲 偏爱  -  张芸京 无损音质
只有这一个我现在点击下载之后，下载列表里找不到
其他歌曲也有下载出错，我重试一下就好了、
就这个当时一直不行，就点了删除，后面就再也加不进来了
高品音质的可以正常下载
其他音乐也都没有问题

**Comment by lyswhut** [comment]
我试了没有发现问题，那你现在可以下载了吗

**Comment by homer-zhang** [comment]
还是不行，点了下载，任务没添加到下载列表，可能是个例吧，反正也没什么影响。

**Comment by lyswhut** [comment]
你是从列表点的下载吗？
如果是的话，你可以尝试从列表删除那首歌，然后重新搜索添加
