### ISSUE TITLE
[Bug]: 在Arch Linux上播放歌曲没有声音

### ISSUE THREAD

**Issue by PILIHU2022** [lyswhut/lx-music-desktop#1540]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望可以播放声音

### 实际行为

我试过将声音线重新插拔了，将系统和该应用的音量调到最大，但是仍无法播放声音

### Lx Music 版本

2.3.0

### 操作系统版本

Arch Linux Linux-zen 6.4.12

**Comment by lyswhut** [comment]
尝试关闭音频可视化及音效设置里的所有功能后重启软件

**Comment by PILIHU2022** [comment]
已经解决，是少装了pipewire-pulse的问题
