### ISSUE TITLE
[Feature]: 歌曲无法添加到下载列表

### ISSUE THREAD

**Issue by xivi1839** [lyswhut/lx-music-desktop#1544]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

这首歌可以试听，但是点击下载歌曲，没下载文件，请求解决。WIN10

【已解决】

### 描述你想要的解决方案

如内容

**Comment by bbfoxx** [comment]
没有复现到你这个问题

**Comment by xivi1839** [comment]
我找到原因了，我以前下载过有下载记录，但是没删除下载记录，我现在再来点击下载，下载才没反应的，我只要把以前下载记录删除就可以下载了。

**Comment by lyswhut** [comment]
可以使用多选功能清空列表
