### ISSUE TITLE
[Feature]: 增加前端网页版，解决不做苹果的问题，“自己提供服务器”

### ISSUE THREAD

**Issue by Enigma-Soul** [lyswhut/lx-music-desktop#1554]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

支持所有平台，包括苹果

### 描述你想要的解决方案

增加前端网页版，给出网页源码

### 描述你考虑过的替代方案

制作落雪IPA自签版

### 附加信息

没了

**Comment by muyiacc** [comment]
加1，我也想部署在网页端，随时随地可以访问，不受设别限制

**Comment by lyswhut** [comment]
虽然这是可行的，但是除了IOS外，常用操作系统都有对应版本的LX，从实用性及有限的个人时间精力来考虑，目前没有打算去做

**Comment by Enigma-Soul** [comment]
....1年可不可以

**Comment by zibingo** [comment]
我也想部署在网页版

**Comment by hcppxgit** [comment]
我也想部署在网页端，如果有人愿意做的话，我可以赞助一台VPS，至于服务器被打的问题，套CF就完事了。

**Comment by Enigma-Soul** [comment]
啊
我才想起来
Electron是套壳浏览器
快点吧
