### ISSUE TITLE
[Bug]: ARM64架构MAC系统2.4.1版本打开提示文件损坏，无法使用

### ISSUE THREAD

**Issue by LiaoLianyu** [lyswhut/lx-music-desktop#1555]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

软件可以正常打开使用。

### 实际行为

打开软件提示文件损坏。

### Lx Music 版本

2.4.1

### 最后正常的版本

2.3.0

### 操作系统版本

macos Ventura  版本13.5.1

### 附加信息

![WX20230910-111142@2x](https://github.com/lyswhut/lx-music-desktop/assets/28888505/1a50d98b-1969-4e02-95ad-a6d0b8b4750b)

**Comment by LiaoLianyu** [comment]
补充：机器是M1芯片。

**Comment by nimhc** [comment]
这是因为软件没有签名，被系统阻止运行

在终端里输入 sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app，然后输入你的电脑密码即可

**Comment by LiaoLianyu** [comment]
> 这是因为软件没有签名，被系统阻止运行
> 
> 在终端里输入 sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app，然后输入你的电脑密码即可

多谢，问题已解决，
