### ISSUE TITLE
[Feature]: 播放时禁止休眠

### ISSUE THREAD

**Issue by CNumber** [lyswhut/lx-music-desktop#1563]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

播放时电脑休眠以后就没声音了

### 描述你想要的解决方案

在播放时禁止系统休眠

### 描述你考虑过的替代方案

禁用系统休眠

**Comment by day0xy** [comment]
如果你是sway或者hyprland等wayland窗口管理器，可以尝试这个程序      https://github.com/ErikReider/SwayAudioIdleInhibit

**Comment by lyswhut** [comment]
已在v2.6.0新增
