### ISSUE TITLE
[Feature]: 能不能增加一个歌单内部的搜索

### ISSUE THREAD

**Issue by Alcohol233** [lyswhut/lx-music-desktop#1565]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在的搜索只能直接搜索曲库里的，我想要的是直接在创建的歌单里面搜索想听的歌曲。

### 描述你想要的解决方案

如题，在自己创建或者导入的歌单内加入一个搜索的框，可以搜索歌单内的歌曲。

**Comment by Fiz-Victor** [comment]
ctrl+f即可

**Comment by Alcohol233** [comment]
OK， 感谢
