### ISSUE TITLE
[Bug]: 音频输出设备设置后重启软件无法保存设置

### ISSUE THREAD

**Issue by BigOrange666** [lyswhut/lx-music-desktop#1568]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

能够正常保存设置。重启软件无需修改音频设备

### 实际行为

设置中修改了音频设备后重启软件，该设置会被恢复默认，期间不进任何界面，不修改其他设置等（不开启音频可视化）
![image](https://github.com/lyswhut/lx-music-desktop/assets/22251672/c53a8734-63c7-4587-8bd8-0a170c787bcc)
![image](https://github.com/lyswhut/lx-music-desktop/assets/22251672/45fb02d0-bcdc-47d1-96f5-b586565192ac)

### Lx Music 版本

2.4.1

### 操作系统版本

Windows 11 专业工作站版

**Comment by lyswhut** [comment]
按`ctrl + f12`打开开发者工具，切到 `console`，输入`navigator.mediaDevices.enumerateDevices().then(info => info.map(d => console.log(d.deviceId, d.label)))` 回车后截图输出的内容，重启后再次操作一遍，看看重启前后两次输出的内容是否一致

**Comment by BigOrange666** [comment]
> 点击`ctrl + f12`打开开发者工具，切到`console`，输入`navigator.mediaDevices.enumerateDevices().then(info => info.forEach(d => console.log(d.deviceId, d.label)))`回车后截图输出的内容，重启后再次操作一遍，看看重启前后两次输出的内容是否一致

不一样，每次启动都在变
![QQ截图20230917110120](https://github.com/lyswhut/lx-music-desktop/assets/22251672/f3b0648c-cb78-4e84-ac12-81a4348e6ee6)

![QQ截图20230917110236](https://github.com/lyswhut/lx-music-desktop/assets/22251672/ca6dc08b-9394-4b8b-a824-d1ad37957fec)

**Comment by lyswhut** [comment]
试试最新beta版是否已修复：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by BigOrange666** [comment]
OK了，已修复
