### ISSUE TITLE
[Feature]: 增加播放本地ape格式音乐的功能

### ISSUE THREAD

**Issue by Panda-logic** [lyswhut/lx-music-desktop#1572]
- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

无法播放本地的ape格式的音乐

**Comment by lyswhut** [comment]
目前播放器是使用Chromium提供的API实现的，它不支持APE格式，APE格式私有格式，LX也不支持对其标签的编辑，目前也无计划支持该格式，若要使用需自行想办法将其转换成flac
