### ISSUE TITLE
[Feature]: 可以为试听列表添加清空选项吗?

### ISSUE THREAD

**Issue by Soil5** [lyswhut/lx-music-desktop#1576]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

试听列表内试听歌曲太多,只能逐一删除,很不方便

### 描述你想要的解决方案

可以为试听列表添加清空选项

**Comment by lyswhut** [comment]
使用多选功能选中所有歌曲删除，详情看文档
