### ISSUE TITLE
[Bug]: 配置 fish shell 时自动运行lx-music

### ISSUE THREAD

**Issue by liutun** [lyswhut/lx-music-desktop#1577]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在银河麒麟操作系统 v10 （SP1）2303  ARM64  安装了 [fish shell ](https://github.com/fish-shell/fish-shell)，终端运行 `fish config` 配置 fish 时，提示将自动打开网址 http://localhost:8000/XXX ，结果自动启动了 lx music，猜测是 lx 开放了 8000端口，系统就直接调用了，但我在 lx 设置里没看到有任何配置 8000端口的地方，不知道什么原因。

![image](https://github.com/lyswhut/lx-music-desktop/assets/47649455/c60c5d95-21dc-42ab-8531-413929874cae)

### 实际行为

同上

### Lx Music 版本

2.4.1

### 操作系统版本

银河麒麟 V10 （SP1）2303 ARM64

**Comment by lyswhut** [comment]
你系统错误认为LX是一个浏览器，所以在打开URL时使用了LX打开，按住`ctrl`后点击终端中的链接是否也会这样？
给系统指定一个默认浏览器看是否可以解决

**Comment by liutun** [comment]
按住 `Ctrl `点终端里的链接直接打开浏览器了，而且是系统默认的浏览器。
