### ISSUE TITLE
[Feature]: 添加恢复窗口按钮来支持 windows snap 功能

### ISSUE THREAD

**Issue by roachsinai** [lyswhut/lx-music-desktop#1584]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241

windows snap 功能使得对 app 进行布局。

但是这个功能好像是依赖于 app 窗口右上角的 `最大化/还原窗口按钮` 按钮。但是 lx-music 并没有提供。

### 描述你想要的解决方案

能支持对 lx-music 的布局。

### 描述你考虑过的替代方案

没有找到可代替的。powertoys 的 fancy toys 同样需要这个按钮。

**Comment by lyswhut** [comment]
你说的是窗口排版？
LX的窗口大小不可调整，所以该功能无法在LX上使用

**Comment by roachsinai** [comment]
窗口大小不能调整时 by-design 嘛？

**Comment by lyswhut** [comment]
算是吧，也有另一部分的原因，LX的圆角窗口基于透明窗口实现，electron的透明窗口设置为可调整大小时在某些平台会[有问题](https://www.electronjs.org/docs/latest/tutorial/window-customization#limitations)

**Comment by roachsinai** [comment]
好的，感谢回复。
