### ISSUE TITLE
[Feature]: 导入第三方平台歌单

### ISSUE THREAD

**Issue by a1385679569** [lyswhut/lx-music-desktop#1586]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

能否添加一键转换功能，比如把QQ音乐喜欢或者歌单直接导入使用？

### 描述你想要的解决方案

比如截图，或者音乐的导出工具？

**Comment by lyswhut** [comment]
该功能在歌单界面右上角，有问题看常见问题

**Comment by a1385679569** [comment]
感激不尽。
---- 回复的原邮件 ----
发件人 lyswhut ***@***.***> 发送日期 2023年09月25日 12:41 收件人 lyswhut/lx-music-desktop ***@***.***> 抄送人 Norko ***@***.***>,
Author ***@***.***> 主题 Re: [lyswhut/lx-music-desktop] [Feature]: 导入第三方平台歌单 (Issue #1586)  

该功能在歌单界面右上角，有问题看常见问题
