### ISSUE TITLE
优化播放功能

### ISSUE THREAD

**Issue by LasyIsLazy** [lyswhut/lx-music-desktop#159]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
播放功能目前还比较简单，很多常用的功能都没有。
- 最小化到托盘
- 桌面歌词
- mini 模式
- 快捷键
- ……

**其他内容**
我有注意到播放器最初定位是查找歌曲，但我觉得大部分使用者还是同时想把它作为播放器的。希望作者可以考虑下完善播放功能。

**Comment by lyswhut** [comment]
目前暂不考虑改进播放相关的功能，详情看常见问题第一条：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md
