### ISSUE TITLE
[Bug]: Wayland environment, hyprland synthesizer, launch lx-music will appear around the application transparent background, I do not lack whether this is a bug

### ISSUE THREAD

**Issue by 0a00** [lyswhut/lx-music-desktop#1590]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

Wayland environment, hyprland synthesizer, launch lx-music will appear around the application transparent background, I do not lack whether this is a bug
![图片](https://github.com/lyswhut/lx-music-desktop/assets/59482058/8fc07d4c-1751-4110-b8f1-a7601c0a0356)

### 实际行为

As shown
![图片](https://github.com/lyswhut/lx-music-desktop/assets/59482058/baba6dbf-936f-4e1e-9c9f-8b07fd461d45)

### Lx Music 版本

lx-music-desktop-git 2.5.0.ac7daa70-1

### 最后正常的版本

no

### 操作系统版本

archlinux wayland hyprland

**Comment by lyswhut** [comment]
Electron 对 Wayland 的支持仍然存在问题，为了缓解主窗口的边框问题，你可以添加启动参数 `-dt` 来启动软件，桌面歌词则暂时无解

**Comment by 0a00** [comment]
谢谢,边框问题解决了
