### ISSUE TITLE
[Bug]: 某些第三方字体应用后无效果

### ISSUE THREAD

**Issue by SacredDreams** [lyswhut/lx-music-desktop#1596]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

修复此问题，第三方字体库可以正常显示

### 实际行为

- 2.2.2版本，在“设置 → 基本设置 → 字体”中，选择已安装在电脑的 第三方字体都可以正常显示

- **覆盖安装后**

- 2.5.0版本，在“设置 → 基本设置 → 字体”中，选择已安装在电脑的 某些第三方字体无法正常显示

### Lx Music 版本

2.5.0

### 最后正常的版本

2.2.2

### 操作系统版本

Windows 10 专业版 22H2

### 附加信息

**以下演示字体均为第三方字体**

- 2.2.2版本，字体正常显示 `lx-music-desktop-v2.2.2-x64-Setup.exe`
![image](https://github.com/lyswhut/lx-music-desktop/assets/113202184/d09dece4-cb5f-4414-b5ca-1f90547856a9)
![image](https://github.com/lyswhut/lx-music-desktop/assets/113202184/1f98b115-0c89-4966-801a-a0dc79ee3458)

- 2.5.0版本，图一字体无法正常显示，图二字体正常显示 `lx-music-desktop-v2.5.0-x64-Setup.exe`
![image](https://github.com/lyswhut/lx-music-desktop/assets/113202184/547f2606-1ab7-4b24-ba3a-c6d4b3d3f09a)
![image](https://github.com/lyswhut/lx-music-desktop/assets/113202184/e192aaa7-0346-4c24-b836-745a890f386a)

**Comment by Shaoyu742698** [comment]
该Bug修复了吗

**Comment by lyswhut** [comment]
测试版修了，下载测试版或者等下个正式版发布

**Comment by Shaoyu742698** [comment]
谢谢～

**Comment by Shaoyu742698** [comment]
好像也没有啊，2.6.0-beta8没错吧🤔
<img width="1431" alt="截屏2024-01-23 11 48 14" src="https://github.com/lyswhut/lx-music-desktop/assets/96671426/ef552e6d-bc19-422a-b905-1ba9b8605133">

**Comment by lyswhut** [comment]
更新后重新选择字体，
若还是不行那就连续点击当前版本号 6 次打开开发者工具，
切到`console`，输入`lxData.updateSetting({ 'common.font': 'xxx' })`，将`xxx`替换成你想要设置的字体名字，
如果字体名字有空格需要使用`lxData.updateSetting({ 'common.font': '"xxx xxx"' })`的形式

**Comment by Shaoyu742698** [comment]
我试试

**Comment by Shaoyu742698** [comment]
哦好了，谢谢～

**Comment by Shaoyu742698** [comment]
那桌面歌词呢

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/blob/ac7daa70f7c7dcc5e4369159abaab649afe7fd0b/src/common/types/app_setting.d.ts#L375

**Comment by Shaoyu742698** [comment]
这个要怎么改？定位到吗？

**Comment by lyswhut** [comment]
已在v2.6.0修复

**Comment by SacredDreams** [comment]
感谢作者，问题已解决！
