### ISSUE TITLE
[Bug]: 随机播放不是真随机

### ISSUE THREAD

**Issue by youwei997** [lyswhut/lx-music-desktop#1597]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望每次播放某一首歌时，下一首歌都是不同的。比如播放歌曲1时，下一首是歌曲6，然后又点击歌曲1时，再点击下一首歌会是歌曲3这样

### 实际行为

随机播放下一首的随机，是有序的。比如有10首歌，从1播放，一直下一首顺序是1->4->7->9，然后一直上一首，顺序会是9->7->4->1，有序的倒上去。上一首可能不是重点，重点是一直上一首到第一首歌时，然后再一直下一首还是之前的1->4->7->9顺序随机下来。

### Lx Music 版本

2.5.0

### 操作系统版本

windows11 22H2

### 附加信息

感谢大佬

**Comment by IButterfieldI** [comment]
哥们，真随机有可能会导致你听歌变成1 -> 3 -> 2 -> 3 ->2 ……最后其他的歌一直听不到。
当年Apple Music就是真随机，然后被用户投诉改成了伪随机。
也许作者可以实现在用户手动选择歌曲时就更新一个随机的播放列表，但是真随机还是千万不要啊。

**Comment by lyswhut** [comment]
看：<https://github.com/lyswhut/lx-music-mobile/issues/304#issuecomment-1712828963>
