### ISSUE TITLE
[Bug]: arm64 m1芯片电脑打开文件包损坏

### ISSUE THREAD

**Issue by trifolium-wang** [lyswhut/lx-music-desktop#1599]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常打开，和x86一样

### 实际行为

报错
<img width="260" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/49668053/b627f30f-fb8f-4f37-a7aa-baa093609a17">

### Lx Music 版本

2.5.0

### 操作系统版本

macOS 14

**Comment by TimorYang** [comment]
参考 #1555

**Comment by halejohn** [comment]
这不是一个软件bug，mac电脑的扩展属性导致的这个问题，当你从网站下载一个文件时，mac os从安全考虑会给每一个文件添加一个附加属性，使用 xattr filename可以查看附件属性，xattr -d attribute_name filename删除附加属性，xattr -c filename清除附件属性。
 xattr 命令的 -c 和 -r 清除文件附加属性，终端输入xattr -c -r 将应用程序中的lx -music拖入，可解决问题。它们的功能如下：

-c : 清除所有扩展属性。这将从指定的文件或目录中删除所有扩展属性。

-r : 递归地处理指定目录和其子目录中的所有文件和子目录。

**Comment by trifolium-wang** [comment]
> 这不是一个软件bug，mac电脑的扩展属性导致的这个问题，当你从网站下载一个文件时，mac os从安全考虑会给每一个文件添加一个附加属性，使用 xattr filename可以查看附件属性，xattr -d attribute_name filename删除附加属性，xattr -c filename清除附件属性。
> 
>  xattr 命令的 -c 和 -r 清除文件附加属性，终端输入xattr -c -r 将应用程序中的lx -music拖入，可解决问题。它们的功能如下：
> 
> 
> 
> -c : 清除所有扩展属性。这将从指定的文件或目录中删除所有扩展属性。
> 
> 
> 
> -r : 递归地处理指定目录和其子目录中的所有文件和子目录。
> 
> 

你的意思是这个软件只针对程序员。普通老百姓不能用是吧？一个软件无法通过常规操作安装，说这是系统问题，你却说不是bug，用户只需要拖曳安装就可以打开，不管是签名问题还是附加属性问题这个问题解决一下总归是好的吧？

**Comment by CherryRum** [comment]
@trifolium-wang 
使用mac最最基本的常见问题。这跟作者没太大关系。
别乱扣帽子

**Comment by trifolium-wang** [comment]
> @trifolium-wang 
> 
> 使用mac最最基本的常见问题。这跟作者没太大关系。
> 
> 别乱扣帽子

你是不是喜欢碰着什么都上去舔两下？作者打包软件有缺陷提醒一下怎么出现这么多舔狗啊，我说国内最近这么多沸羊羊，典型的民粹主义分子，二极管，说华为就是遥遥领先，说苹果就是远远落后，发个issue就乱扣帽子了？种花家的任何东西就算是屎也必须得舔，外部的东西一概就得喷是吧？

**Comment by CherryRum** [comment]
你在这叫，不如看看别人咋说的，还有多投投简历，别找不到工作，还喜欢喷这个那个？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月21日(周六) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lyswhut/lx-music-desktop] [Bug]: arm64 m1芯片电脑打开文件包损坏 (Issue #1599)




  
@trifolium-wang
 
使用mac最最基本的常见问题。这跟作者没太大关系。
 
别乱扣帽子
  
你是不是喜欢碰着什么都上去舔两下？作者打包软件有缺陷提醒一下怎么出现这么多舔狗啊，我说国内最近这么多沸羊羊，典型的民粹主义分子，二极管，说华为就是遥遥领先，说苹果就是远远落后，发个issue就乱扣帽子了？种花家的任何东西就算是屎也必须得舔，外部的东西一概就得喷是吧？

**Comment by CherryRum** [comment]
系统安全问题，您感觉你能绕过去？还是我能拿到你的root密码？我做开源应该比你这强多了吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月21日(周六) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lyswhut/lx-music-desktop] [Bug]: arm64 m1芯片电脑打开文件包损坏 (Issue #1599)




  
@trifolium-wang
 
使用mac最最基本的常见问题。这跟作者没太大关系。
 
别乱扣帽子
  
你是不是喜欢碰着什么都上去舔两下？作者打包软件有缺陷提醒一下怎么出现这么多舔狗啊，我说国内最近这么多沸羊羊，典型的民粹主义分子，二极管，说华为就是遥遥领先，说苹果就是远远落后，发个issue就乱扣帽子了？种花家的任何东西就算是屎也必须得舔，外部的东西一概就得喷是吧？

**Comment by trifolium-wang** [comment]
> 你在这叫，不如看看别人咋说的，还有多投投简历，别找不到工作，还喜欢喷这个那个？
> 
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 
> 发件人: ***@***.***&gt;
> 
> 发送时间: 2023年10月21日(周六) 下午3:10
> 
> 收件人: ***@***.***&gt;;
> 
> 抄送: ***@***.******@***.***&gt;;
> 
> 主题: Re: [lyswhut/lx-music-desktop] [Bug]: arm64 m1芯片电脑打开文件包损坏 (Issue #1599)
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> @trifolium-wang
> 
>  
> 
> 使用mac最最基本的常见问题。这跟作者没太大关系。
> 
>  
> 
> 别乱扣帽子
> 
>   
> 
> 你是不是喜欢碰着什么都上去舔两下？作者打包软件有缺陷提醒一下怎么出现这么多舔狗啊，我说国内最近这么多沸羊羊，典型的民粹主义分子，二极管，说华为就是遥遥领先，说苹果就是远远落后，发个issue就乱扣帽子了？种花家的任何东西就算是屎也必须得舔，外部的东西一概就得喷是吧？
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you commented.Message ID: ***@***.***&gt;

浪费口舌，出门右转，(;｀O´)o滚，

**Comment by trifolium-wang** [comment]
@CherryRum 出去出去，浪费口舌，出门右转。

**Comment by VampireAchao** [comment]
> > 这不是一个软件bug，mac电脑的扩展属性导致的这个问题，当你从网站下载一个文件时，mac os从安全考虑会给每一个文件添加一个附加属性，使用 xattr filename可以查看附件属性，xattr -d attribute_name filename删除附加属性，xattr -c filename清除附件属性。
> > xattr 命令的 -c 和 -r 清除文件附加属性，终端输入xattr -c -r 将应用程序中的lx -music拖入，可解决问题。它们的功能如下：
> > -c : 清除所有扩展属性。这将从指定的文件或目录中删除所有扩展属性。
> > -r : 递归地处理指定目录和其子目录中的所有文件和子目录。
> 
> 你的意思是这个软件只针对程序员。普通老百姓不能用是吧？一个软件无法通过常规操作安装，说这是系统问题，你却说不是bug，用户只需要拖曳安装就可以打开，不管是签名问题还是附加属性问题这个问题解决一下总归是好的吧？

基本上都可以通过下面的命令解决：
```bash
xattr -cr /Applications/xxx.app
```
https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes

要求开源软件解决这个问题可以采取：

https://github.com/marktext/marktext/issues/2983#issuecomment-1031396465

> This requires registration of an apple developer account before code sign, which costs about $99/year

扪心自问，凭什么让开源作者因为apple的限制，掏出*99美元一年*的费用？开源作者很难的！有时候找找自己的原因，这么多年素质涨没涨，有没有认真支持开源。

针对"这个软件只针对程序员。普通老百姓不能用"这一点，我相信普通老百姓也可以做到执行这一段命令来解决这个问题。而且这个问题本身并不是由开源软件造成的

最后，己所不欲，勿施于人

**Comment by xiazhichao** [comment]
安装完成后,先不要打开,打开终端,复制命令 xattr -cr /Applications/lx-music-desktop.app ,点回车,再打开软件,就可以了;
老实说安装个软件还需要敲命令,就不是太友好,特别对女生而已
