### ISSUE TITLE
是否可以增加代理设置功能

### ISSUE THREAD

**Issue by zuohl** [lyswhut/lx-music-desktop#16]
公司网络默认访问不了音乐站点,急需代理配置啊

**Comment by lyswhut** [comment]
- 目前已支持音乐搜索、播放的代理（需要到设置-网络设置-代理设置配置代理地址）
- 图片加载、音频加载会自动走系统配置的代理
- 暂不支持**下载代理**

**Comment by joebnb** [comment]
目前代理还是有问题，我设置了代理，不是所有的资源走代理，尤其是音频加载无法走到代理去
