### ISSUE TITLE
[Feature]: 下载合并的图片能否进行压缩处理

### ISSUE THREAD

**Issue by Ghd-0802** [lyswhut/lx-music-desktop#1609]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

下载合并的图片能否进行压缩处理,一个3M的歌 合并完图片 23M, 不要图片,播放器又成了破图, 能否加入压缩选项 高倍率压缩一下图片

### 描述你想要的解决方案

希望下载选项增加一个图片压缩功能

### 附加信息
参考音乐 
网易云
    "乐园 - 沧桑Cang333、虎皮蛋、曲甲.mp3",
    "还是会想你 - 林达浪、h3R3.mp3",
    "病态 - 薛之谦.mp3",
    "陪你去流浪 - 薛之谦.mp3",
    "慢半拍 - 薛之谦.mp3",
    "失眠飞行 - 接个吻，开一枪、沈以诚、薛黛霏.mp3",
    "我想念 - 汪苏泷.mp3",
    "以爱为囚 - 满舒克.mp3",
    "荒诞学家 - 尤长靖.mp3",
_No response_

**Comment by lyswhut** [comment]
已在v2.6.0采用临时的方式针对wy源图片优化

**Comment by xzhzhaowendao** [comment]
> 已在v2.6.0采用临时的方式针对wy源图片优化

我用2.6.0版本测试结果是压缩后的图片为500*500大小。感觉对于一些人（比如我）来说，下载全屏播放时感觉压缩后的专辑图有点糊。作者可不可以考虑在Beta版甚至下一个正式版里，加入一个可以自定义平台专辑图片最大像素的功能？或者可以考虑将压缩画质增强（例如Mp3tag的“调整封面”功能），这样就可以在最大限度保存画质的同时，还能兼顾文件大小适度。
![QQ截图20240205222933](https://github.com/lyswhut/lx-music-desktop/assets/132211598/a5df34f2-64a9-4c91-8c2c-add365a1743a)
