### ISSUE TITLE
网易音乐及聚合搜索无结果

### ISSUE THREAD

**Issue by Wuhao1627003** [lyswhut/lx-music-desktop#161]
**解决方案检查**
- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
网易音乐及聚合搜索无论什么关键词都无结果，其它接口没问题

**重现**
重现行为的步骤：
1.转到“ 搜索”
2.输入任何关键词
3.点击“ 网易音乐”或“聚合搜索”
4.看到“搜我所想~~
![image](https://user-images.githubusercontent.com/25204397/77809165-eb99ff00-7064-11ea-8d41-74ff66ebaf8a.png)”，无其他结果

**预期行为**
有搜索结果

**截图**
![image](https://user-images.githubusercontent.com/25204397/77809190-0e2c1800-7065-11ea-9638-5b6271fcc19f.png)

**环境：**
Win64 19592.1001, 64位绿色版0.17.0

**Comment by lyswhut** [comment]
只有网易云是这样吗？试过切换网络（比如用手机热点）没有？

**Comment by Wuhao1627003** [comment]
网易音乐和聚能搜索都是~后来发现开vpn就好了~

**Comment by lyswhut** [comment]
那应该是你那边网络的问题导致的，打不开尝试切换网络即可
