### ISSUE TITLE
[Bug]: 重新打开软件后全局快捷键失效，必须手动重新关闭再打开

### ISSUE THREAD

**Issue by Banana-energy** [lyswhut/lx-music-desktop#1615]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

重新打开软件全局快捷键依然生效

### 实际行为

重新打开软件后全局快捷键失效，必须手动重新关闭再打开

### Lx Music 版本

2.5.0

### 操作系统版本

Windows 11 企业版 22H2

**Comment by lyswhut** [comment]
未能重现你的问题，检查是否有其他软件占用快捷键的注册

**Comment by Banana-energy** [comment]
应该是占用了😀
