### ISSUE TITLE
[Bug]: 现在很多歌曲都找不到播放源要咋搞？

### ISSUE THREAD

**Issue by not-lsj** [lyswhut/lx-music-desktop#1617]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

歌曲都提示换源失败找不到url播放源，但是是以前版本都能播放的歌曲

### 实际行为

歌曲都提示换源失败找不到url播放源，但是是以前版本都能播放的歌曲

### Lx Music 版本

2.5.0

### 操作系统版本

win10

**Comment by SamuelChann** [comment]
same problem
