### ISSUE TITLE
[Bug]: 是凉了吗

### ISSUE THREAD

**Issue by mengruobaobao** [lyswhut/lx-music-desktop#1618]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

能正常播放

### 实际行为

播放不了了

### Lx Music 版本

2.5.0

### 最后正常的版本

2.5.0

### 操作系统版本

Windows 10

**Comment by wenliyang** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/1614

**Comment by mengruobaobao** [comment]
自动回复：您好！我是庞光保，我已经收到您的来信，阅读后我会尽快给您回信，祝您生活愉快，身体健康！

**Comment by DOOMS0** [comment]
凉了吗

**Comment by WangLun9527** [comment]
手机版本的可以支持换源吗？

**Comment by SeanXiao1207** [comment]
估计是凉了，全部无法播放

**Comment by WangLun9527** [comment]
1楼老哥已经把更换源的方式 以及第三方源发不出来了,最起码可以解决pc端的音源问题

**Comment by mengruobaobao** [comment]
#1613

**Comment by uaena-lx** [comment]
电脑端换个源就行了，作者不是发了吗，几秒钟就解决了，手机端我换了一个叫“试听接口(这是最后的选择。。。)”这个源也可以听了

**Comment by WangLun9527** [comment]
试听接口(这是最后的选择。。。)  这个源还是不行的

**Comment by WangLun9527** [comment]
再次试了下，更换 试听接口(这是最后的选择。。。) 这个源之后，重启软件就可以了

**Comment by uaena-lx** [comment]
> 再次试了下，更换 试听接口(这是最后的选择。。。) 这个源之后，重启软件就可以了

是的，但是app端好像有些歌还是听不了

**Comment by wuzhengqiang** [comment]
经验证，2.5版本很多不能播放了，直接删了退回老版本吧，老版本都可以播放！期待作者修复问题！

**Comment by zhyd1204** [comment]
> #1613 这里有大佬换音源之后解决了PC端的，但是APP端无法换音源，看谁来重新编译一个了

感谢老哥  六音音源确实可以用

**Comment by wuzhengqiang** [comment]
> > 经验证，2.5版本很多不能播放了，直接删了退回老版本吧，老版本都可以播放！期待作者修复问题！
> 
> 老版本也不能播放

好像是耶。刚退回老版本发现，之前收藏的能正常播放了，但是搜别的还是不能播放，全部播放失败了。之前2.5版本时之前收藏的也不行，会不会是播放服务器被端了？

**Comment by envlearner** [comment]
> > > 经验证，2.5版本很多不能播放了，直接删了退回老版本吧，老版本都可以播放！期待作者修复问题！
> > 
> > 
> > 老版本也不能播放
> 
> 好像是耶。刚退回老版本发现，之前收藏的能正常播放了，但是搜别的还是不能播放，全部播放失败了。之前2.5版本时之前收藏的也不行，会不会是播放服务器被端了？

估计是作者把音乐源换掉了吧。没办法，个人开发者面对这种事还是太无力了

**Comment by a1173197570** [comment]
这有一篇教程，可以替换音乐源解决[https://mp.weixin.qq.com/s/lsVLYjuXIyd3mKym0mV7UQ](https://github.com/lyswhut/lx-music-desktop/issues/url)

**Comment by a1013798622a** [comment]
作者被律师函警告了，解决办法在这里
https://www.sixyin.com/8498.html

**Comment by dick-su-3** [comment]
继上次团灭“李跳跳”等跳广告软件后，南山必胜客再次出手，律师函警告开源音乐“洛雪音乐助手”。

音乐有版权。我觉得大部分人应该尊重版权。版权是一种社会秩序，大部分情况人都应该遵守秩序。

但社会是有秩序的，现实却可能不合理。人本天生具备违反秩序能力，在面对不合理的现实世界时，为什么要放弃这种能力。

在知识和文化等无形资产的领域，侵犯版权去获利100%违法。但也存在一个灰色区域，比如出于学习目的个人破解软件等行为，你可以说合理也可以说不合理。这并不是当下才存在的行为和话题，因为很早就“有盗火的普罗米修斯”这样的神话，这是人打破无形之墙的一种原始冲动。

知识文化是人区别于其它动物的重要原因之一，如果知识文化等可以被垄断，那么就是最坚硬的圈养围墙。尊重版权尊重知识尊重文化，但并非是让版权筑起围墙让一部分人最大化获利，另一部分人却因为这堵围墙对文化触不可及。

在这个唯利是图的时代，我们需要一点人文主义思想，去思考我们为什么活着！最后无奈地说一句：开源不是法外之地，请大家且行且珍惜！
（但是我还是忍不住想喷：我XXX，狗TX，那么嚣张吃相那么丑是有动物协会保护你吗，别和我谈人生，你都不是人生的）

**Comment by dick-su-3** [comment]
继上次团灭“李跳跳”等跳广告软件后，南山必胜客再次出手，律师函警告开源音乐“lx音乐助手”。

音乐有版权。我觉得大部分人应该尊重版权。版权是一种社会秩序，大部分情况人都应该遵守秩序。

但社会是有秩序的，现实却可能不合理。人本天生具备违反秩序能力，在面对不合理的现实世界时，为什么要放弃这种能力。

在知识和文化等无形资产的领域，侵犯版权去获利100%违法。但也存在一个灰色区域，比如出于学习目的个人破解软件等行为，你可以说合理也可以说不合理。这并不是当下才存在的行为和话题，因为很早就“有盗火的普罗米修斯”这样的神话，这是人打破无形之墙的一种原始冲动。

知识文化是人区别于其它动物的重要原因之一，如果知识文化等可以被垄断，那么就是最坚硬的圈养围墙。尊重版权尊重知识尊重文化，但并非是让版权筑起围墙让一部分人最大化获利，另一部分人却因为这堵围墙对文化触不可及。

在这个唯利是图的时代，我们需要一点人文主义思想，去思考我们为什么活着！最后无奈地说一句：开源不是法外之地，请大家且行且珍惜！
（但是我还是忍不住想喷：我XXX，狗TX，那么嚣张吃相那么丑是有动物协会保护你吗，别和我谈人生，你都不是人生的）
