### ISSUE TITLE
希望能添加Hi-Res音源或DSD格式的下载功能

### ISSUE THREAD

**Issue by guykjy** [lyswhut/lx-music-desktop#162]
现在玩音乐的众多人群都转向了超高品质音乐Hi-Res24bit_96khz（高解析音频）及以上更高的体验，尤其是母带音乐的体验，在此希望作者也能开发并添加下载Hi-Res或DSD音源的功能，方便更多对音质追求完美的发烧友，谢谢。

**Comment by lyswhut** [comment]
抱歉，目前接口不支持这些格式的下载

**Comment by guykjy** [comment]
Hi-Res24bit_96khz的格式依然是flac，希望作者提供采样率更佳高的音源

**Comment by lyswhut** [comment]
目前接口那边已经关闭对高品质音乐的支持，开放时间未知，对于更高品质的音乐建议去对应平台下载
