### ISSUE TITLE
[Feature]: 新建列表重名提示

### ISSUE THREAD

**Issue by Eyion** [lyswhut/lx-music-desktop#1621]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前在我的列表中新建列表，重名是不会有任何提示的，这会造成已经建了某歌手的列表，时间久了列表多了，又再次建表。

### 描述你想要的解决方案

希望增加重名弹窗或者其他明显的提示方式，并为我的列表增加搜索功能和次序调整功能。

### 描述你考虑过的替代方案

无

### 附加信息

无

**Comment by a1173197570** [comment]
这有一篇教程，可以替换音乐源解决[https://mp.weixin.qq.com/s/lsVLYjuXIyd3mKym0mV7UQ](https://github.com/lyswhut/lx-music-desktop/issues/url)

**Comment by Eyion** [comment]
> 这有一篇教程，可以替换音乐源解决[https://mp.weixin.qq.com/s/lsVLYjuXIyd3mKym0mV7UQ](https://github.com/lyswhut/lx-music-desktop/issues/url)

链接打不开，而且我的问题是关于新建列表，而非音乐源，所以不太理解你的回答。

**Comment by lyswhut** [comment]
新列表搜索用ctrl+f，重名的问题下个版本新增一个提示

**Comment by lyswhut** [comment]
已在v2.6.0添加重名提示
