### ISSUE TITLE
请先看痕哥置顶的issue然后看这

### ISSUE THREAD

**Issue by liaofulong** [lyswhut/lx-music-desktop#1655]
不要在群（测试，交流）里讨论LX Music不能播放的问题，给管理整烦了直接踢，TM不会看公告吗
不要在群（测试，交流）里讨论LX Music不能播放的问题，给管理整烦了直接踢，TM不会看公告吗
不要在群（测试，交流）里讨论LX Music不能播放的问题，给管理整烦了直接踢，TM不会看公告吗
重要的事情说三遍！
关于为何无法播放;
前几天痕哥被tx警告了，所有内置源（包括测试接口，试听接口）以及Moonsea公共版本，不包括试听接口，均停止任何服务，不要在群里显摆自己缓存了，能听，不然挨踢就永远别想重进了

**Comment by showyoulove1990** [comment]
之前退了群，现在我想进都进不了了，可能再把我拉进去一下？503362549
