### ISSUE TITLE
致敬洛雪音乐

### ISSUE THREAD

**Issue by songpengkang** [lyswhut/lx-music-desktop#1662]
长期以来，洛雪音乐在互联网资本的压榨下，提供了一片清凉的栖息之地。可惜，好用的平台不能做大，做大了必然会被资本主义注意到，这么好用的软件可惜了。
最后向洛雪音乐致敬！

**Comment by trifolium-wang** [comment]
致敬作者，感谢一直以来的付出，现在换到sptify了，只能出墙听歌了。

**Comment by liux123** [comment]
感恩作者，向洛雪音乐致敬！

**Comment by hnxiaoyuan** [comment]
向洛雪音乐致敬，瑞思拜！

**Comment by lvbibir** [comment]
致敬

**Comment by 451706022** [comment]
感恩作者，向洛雪音乐致敬！

**Comment by Leima0214** [comment]
向洛雪致敬

**Comment by LLKawi** [comment]
> 致敬作者，感谢一直以来的付出，现在换到sptify了，只能出墙听歌了。

Spotify在墙内有14天的

**Comment by zuogaocan** [comment]
感恩作者，向洛雪音乐致敬！

**Comment by ren651382714** [comment]
感谢作者

**Comment by Mdgas** [comment]
致敬！

**Comment by dick-su-3** [comment]
致敬！respect

**Comment by Ravanla** [comment]
致敬作者

**Comment by GiveStar** [comment]
留念
![image](https://github.com/lyswhut/lx-music-desktop/assets/86779955/f47addbc-1322-4443-a983-85c28e50bd62)
lx刚传开的时候用过，中间两年多没用，23年再用，只用了1个月，就倒了

**Comment by kanjianjiuhao** [comment]
> 留念 ![image](https://user-images.githubusercontent.com/86779955/278791380-f47addbc-1322-4443-a983-85c28e50bd62.png) lx刚传开的时候用过，中间两年多没用，23年再用，只用了1个月，就倒了

那哥们之前还有类似经历吗 ？挺硬的命呀 🐶 🌜

**Comment by GiveStar** [comment]
> > 留念 ![image](https://user-images.githubusercontent.com/86779955/278791380-f47addbc-1322-4443-a983-85c28e50bd62.png) lx刚传开的时候用过，中间两年多没用，23年再用，只用了1个月，就倒了
> 
> 那哥们之前还有类似经历吗 ？挺硬的命呀 🐶 🌜

嗯。。。为了留个言我去注册发现邮箱已注册又重置密码，满怀感慨留念，结果收到兄弟你这，理解这么偏的回复。。。

**Comment by jsshNY** [comment]
> 致敬作者，感谢一直以来的付出，现在换到sptify了

手机版有没有能用的

**Comment by TodayYoHoHo** [comment]
致敬

**Comment by YuanScott** [comment]
致敬

**Comment by Y-tim** [comment]
致敬！幸苦了各位大大

**Comment by zangqianglei** [comment]
致敬大佬，无私奉献

**Comment by libasten** [comment]
致敬！

**Comment by lovelipanpan** [comment]
致敬作者！

**Comment by isDaKai** [comment]
致敬，感谢作者！

**Comment by kestrelbright** [comment]
感谢

**Comment by He1Ping** [comment]
感谢作者

**Comment by lngcheqng** [comment]
感谢作者

**Comment by Bald-youth** [comment]
感谢作者，lx陪伴了我两年！

**Comment by awjd007** [comment]
感谢作者，一直在用，明知道前路漫漫还能坚持这么久，瑞思拜

**Comment by Aurelius84** [comment]
向洛雪音乐致敬，瑞思拜！

**Comment by kestrelbright** [comment]
谢谢大佬！
