### ISSUE TITLE
无法下载与试听

### ISSUE THREAD

**Issue by xavier1933** [lyswhut/lx-music-desktop#167]
无法下载与试听

**Comment by xavier1933** [comment]
![Uploading image.png…]()
无法下载与试听

**Comment by leon-hw** [comment]
昨天可以试听和下载，今天就不行了，显示connect ECONNREFUSED

**Comment by mm24qin** [comment]
看下今天的日期，作者说明了的。就差这一天啊

**Comment by xavier1933** [comment]
什么差一天

**Comment by mm24qin** [comment]
不好意识，我是说要下载歌曲也不急差这一天吧。

**Comment by xavier1933** [comment]
http://music.ifkdy.com/?name=midsummer%20madness&type=netease

**Comment by fanqianger** [comment]
我也遇到了同样的问题 除了酷我源 别的源都不能下载和试听

**Comment by lyswhut** [comment]
2020/04/04那天API接口被作者关闭一天
