### ISSUE TITLE
[Feature]: English translations? 

### ISSUE THREAD

**Issue by chase-west** [lyswhut/lx-music-desktop#1673]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

English translations

### 描述你想要的解决方案

English translations

### 描述你考虑过的替代方案

English translations

### 附加信息

English translations

**Comment by maxfong** [comment]
<img width="761" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/3784855/76c3ac13-4851-4788-a9a2-98020587ad37">
