### ISSUE TITLE
[Feature]: 有一个小小的问题，移动端后续会有更新嘛。

### ISSUE THREAD

**Issue by canlang0** [lyswhut/lx-music-desktop#1677]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

主要是我手机上的版本还是1.0.6的-。-

### 描述你想要的解决方案

之前添加的有的不能听了，比较蛋疼Orz...

**Comment by sparkssssssssss** [comment]
https://github.com/lyswhut/lx-music-mobile/issues/347
