### ISSUE TITLE
添加自动为下载歌曲写入 id3 标签和封面的功能

### ISSUE THREAD

**Issue by necan** [lyswhut/lx-music-desktop#169]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
下载的歌曲没有 id3 标签和封面信息，导致播放时体验不佳，希望增加此功能

**描述您考虑过的替代方案**
缺失此功能，增加即可。

**其他内容**
看了下，所有的歌曲都没有 id3 标签和封面信息

![image](https://user-images.githubusercontent.com/25315125/78498849-7672ac00-777f-11ea-88a2-750a23834356.png)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/85
