### ISSUE TITLE
致敬这么牛的播放器，但是关闭有最小化功能吗？ 现在关闭就直接关闭了[Feature]: 

### ISSUE THREAD

**Issue by gaodeyang** [lyswhut/lx-music-desktop#1691]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

致敬这么牛的播放器，但是关闭有最小化功能吗？ 现在关闭就直接关闭了

### 描述你想要的解决方案

致敬这么牛的播放器，但是关闭有最小化功能吗？ 现在关闭就直接关闭了

**Comment by yangex** [comment]
设置里面有吧
