### ISSUE TITLE
[Feature]: 好像不能听了。。。。。。。

### ISSUE THREAD

**Issue by dellshan** [lyswhut/lx-music-desktop#1705]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

好像不能听了。。。。。。。所有歌曲都显示连不上网， 源错误， 切换源错误。

### 描述你想要的解决方案

好像不能听了。。。。。。。所有歌曲都显示连不上网， 源错误， 切换源错误。

**Comment by Sayaka617** [comment]
我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=))，但没有发现类似的问题

https://github.com/lyswhut/lx-music-desktop/issues/1695

**Comment by luxiuqi0124** [comment]
我这也一样，换源也无法加载

**Comment by coderwing** [comment]
解决了：安装音源插件，播放音源有问题
可以参考这篇文章进行设置：http://mp.weixin.qq.com/s?__biz=MzU2MDQ3MDg0NQ==&mid=2247485894&idx=1&sn=ff0d20cfdfc77a56709b5a42c3826ad1&chksm=fc06c794cb714e82597bb8b0c044cee447dcfd29a33737cae05cbcd2271dd887c108efe05dd4#rd

**Comment by O3OTZ** [comment]
感谢兄弟

**Comment by O3OTZ** [comment]
> 解决了：安装音源插件，播放音源有问题 可以参考这篇文章进行设置：http://mp.weixin.qq.com/s?__biz=MzU2MDQ3MDg0NQ==&mid=2247485894&idx=1&sn=ff0d20cfdfc77a56709b5a42c3826ad1&chksm=fc06c794cb714e82597bb8b0c044cee447dcfd29a33737cae05cbcd2271dd887c108efe05dd4#rd

感谢兄弟
