### ISSUE TITLE
[Bug]: MAC上版本桌面歌词有一个固定的灰色残影

### ISSUE THREAD

**Issue by goadsth** [lyswhut/lx-music-desktop#1707]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望能修复

### 实际行为

希望能修复

### Lx Music 版本

2.5.0

### 操作系统版本

macOS

**Comment by tangye1** [comment]
macOS??哪里下载啊
