### ISSUE TITLE
[Bug]: 2.5.0版本 基本上不能播放所有音乐

### ISSUE THREAD

**Issue by dddachui** [lyswhut/lx-music-desktop#1721]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

2.5的版本，可以搜到音乐但不能播放

### 实际行为

2.5的版本，可以搜到音乐但不能播放

### Lx Music 版本

2.5.0

### 最后正常的版本

2.5.0

### 操作系统版本

windows10

**Comment by Eric1894yyds** [comment]
其实之前的版本也是这样，我都是把音乐下载下来，用电脑播放器播放。

**Comment by ashleycolton** [comment]
我也是一样，落雪的源全寄了。从来没下载过，但是源没了TAT

**Comment by ryanzhaorx** [comment]
可以使用六音的音源(虽然已经被下架但是网上还有的比如 : https://xiaozhongjishu.lanzouy.com/ivLKb1cvu0oj)

**Comment by dddachui** [comment]
我就是下载诶 现在没法下载

**Comment by dddachui** [comment]
大佬们牛逼
