### ISSUE TITLE
[Bug]: 所有音乐不能下载，也不能播放

### ISSUE THREAD

**Issue by iskohl** [lyswhut/lx-music-desktop#1723]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

所有音乐不能下载，也不能播放

### 实际行为

随便搜索什么，都不能下载和播放

### Lx Music 版本

2.5.0

### 操作系统版本

Win 11

### 附加信息

依稀记得，1,2个月前还好用

**Comment by tianlinszs** [comment]
不仅是2.5.0版本，几乎所有版本都无法正常使用

**Comment by NOknow95** [comment]
估计是源都被...

**Comment by swift-fs** [comment]
眼不好使就捐了吧，置顶的两个issue你是一个都看不到。

**Comment by iskohl** [comment]
六音的源可以使用
