### ISSUE TITLE
[Feature]: 能加一个歌词展示的进程在后台应用吗?

### ISSUE THREAD

**Issue by yc-css** [lyswhut/lx-music-desktop#1729]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

`linux`桌面系统下，开启桌面歌词功能，且将其置顶于其他应用上，每次`ctrl + tab`切换应用, 落雪应用都会在第一个展示，这样切换有些不便。

### 描述你想要的解决方案

可以仍将歌词置顶，但是在切换应用时，不展示吗？

**Comment by lyswhut** [comment]
electron 在linux上不再支持将显示的窗口隐藏任务栏 https://github.com/electron/electron/pull/35123

**Comment by yc-css** [comment]
明白，3Q
