### ISSUE TITLE
[Feature]: 桌面歌词似乎不能拉到另一台显示器上

### ISSUE THREAD

**Issue by LGXHTM** [lyswhut/lx-music-desktop#1731]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

桌面歌词似乎不能拉到另一台显示器上

### 描述你想要的解决方案

笔记本接显示器时，桌面歌词只能在笔记本上显示

**Comment by zaolune** [comment]
需要在设置里面打开。

**Comment by LGXHTM** [comment]
设置里面我似乎没有找到相关设置，请问是在哪个具体设置部分@zaolune

**Comment by zaolune** [comment]
@LGXHTM 桌面歌词设置->不允许歌词窗口拖出主屏幕之外 取消勾选即可。

**Comment by LGXHTM** [comment]
@zaolune  非常感谢
