### ISSUE TITLE
[Feature]: 希望增加播放本地音乐功能。

### ISSUE THREAD

**Issue by licheng1013** [lyswhut/lx-music-desktop#1737]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前桌面端 Lx 貌似没看到导入本地音乐目录的功能。 

### 描述你想要的解决方案

希望在侧栏多加一个选项，用于显示本地音乐目录，选中某个目录，则显示某个目录下(所有音乐-包括子/子子目录)
![image](https://github.com/lyswhut/lx-music-desktop/assets/46236080/224c7e14-fef2-48e9-b149-1e3092f5ef9c)

**Comment by Dev-Wiki** [comment]
![image](https://github.com/lyswhut/lx-music-desktop/assets/12946956/27222c4d-6ae7-47ea-ada2-c2d37e144386)
 
收藏添加一个本地歌单 邮件添加本地歌曲

**Comment by licheng1013** [comment]
> ![image](https://private-user-images.githubusercontent.com/12946956/293310735-27222c4d-6ae7-47ea-ada2-c2d37e144386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MjgxNDgsIm5iZiI6MTcwMzgyNzg0OCwicGF0aCI6Ii8xMjk0Njk1Ni8yOTMzMTA3MzUtMjcyMjJjNGQtNmFlNy00N2VhLWFkYTItYzJkMzdlMTQ0Mzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA1MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzRjOGY3MTc1OTViZGZmZDAzZmI1MmNiNjBiOTg3YWFlMWE3YmZiMzE2MmYyZGFkYjUzMDFmZjVmMjc4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aywuh1YZyiJ1Eh7QH8QJzzGjMo431LGo1qRP75jLKyE)
> 
> 收藏添加一个本地歌单 邮件添加本地歌曲

谢谢
