### ISSUE TITLE
添加：在播放按钮旁边加入切换单曲循环等的按钮，会方便许多

### ISSUE THREAD

**Issue by ganyuanzhen** [lyswhut/lx-music-desktop#174]
**解决方案检查**

- [ x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

***建议描述***
在使用这款软件一段时间后，觉得各方面不错，希望可以在播放按钮附近增加类似功能的按钮，避免在设置界面频繁切换
**描述您考虑过的替代方案**
类似于其他音乐软件

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
已在v1.1.0新增该功能
