### ISSUE TITLE
收藏列表可以导入歌单就好啦

### ISSUE THREAD

**Issue by hh1217855703** [lyswhut/lx-music-desktop#175]
单有一个收藏列表的话可能什么时候出现了问题,不能恢复了呀,虽然可以备份,但是就怕问题出在备份之前
可以用两种情况代替
**1:添加登录功能,把用户收藏的信息添加到数据库(可能会增加成本)
2:增加歌单导入功能**

**Comment by lyswhut** [comment]
1、不计划开发登录功能，可自行定期去设置备份数据
2、歌单导入一直以来都支持
