### ISSUE TITLE
添加快捷键控制播放暂停功能

### ISSUE THREAD

**Issue by Adam520Eve** [lyswhut/lx-music-desktop#176]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by Adam520Eve** [comment]
如果能加入快捷键随时暂停就好了😘

**Comment by lyswhut** [comment]
已在v1.0.0新增该功能
