### ISSUE TITLE
[Bug]: 添加六音音源1.0.7版本，一直初始化失败。

### ISSUE THREAD

**Issue by iridescentll** [lyswhut/lx-music-desktop#1762]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

能否提供版本解决这个初始化失败的问题。

### 实际行为

2.6.0-beta.10 我用的这个版本，绿色版，安装版都试了，都是初始化失败。六音源 手机添加源是可以用的。我的CPU是12th Gen Intel(R) Core(TM) i5-1240P   1.70 GHz

### Lx Music 版本

2.6.0-beta.10

### 操作系统版本

Windows 11 家庭中文版 22631.3007

### 附加信息

手机使用六音1.0.7的源可以，桌面版本不行，所以我推断是lx软件问题。

**Comment by ryanzhaorx** [comment]
我刚刚升级了也是初始化失败
显示 Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')

**Comment by ryanzhaorx** [comment]
初步判断，我刚刚看了一下作者昨天的Bata版本的提交，发现他修改了音源加载的程序(支持本地了)。可能是因为这个修改。我感觉他修改了加载模块，出现了BUG(或者是不支持了)

**Comment by ryanzhaorx** [comment]
先退版本吧

**Comment by ryanzhaorx** [comment]
先退版本吧

**Comment by lyswhut** [comment]
移动端 1.2.0-beta.27 及 桌面端 2.6.0-beta.10 开始移除了旧版源的兼容垫片代码：

https://github.com/lyswhut/lx-music-mobile/commit/4db5f0394c225cd8d8e276b75d7cb1bb43718483#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511

https://github.com/lyswhut/lx-music-desktop/commit/7893814da47516507a86d5e74eed80ec289efe90#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328

可以尝试在源的代码之前补上垫片代码：
```js
"undefined"==typeof window&&(window=globalThis),
window.document||(window.document={}),
Object.defineProperty(window.document,"getElementsByTagName",
{value:e=>"script"==e?[Object.freeze({innerText:globalThis.lx.currentScriptInfo.rawScript}),]:null});

```

**Comment by hzq21** [comment]
![image](https://github.com/lyswhut/lx-music-desktop/assets/33676678/f3d0f97e-5141-450c-9bd4-79201abbac7a)
好啦

**Comment by huio** [comment]
> > ![image](https://private-user-images.githubusercontent.com/33676678/301394867-f3d0f97e-5141-450c-9bd4-79201abbac7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjY1MDIsIm5iZiI6MTcwNjc2NjIwMiwicGF0aCI6Ii8zMzY3NjY3OC8zMDEzOTQ4NjctZjNkMGY5N2UtNTE0MS00NTBjLTliZDQtNzkyMDFhYmJhYzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA1NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYzNlNjIyZWMzOWI3YjYzOTZlNDc2ODdhNjEyNDM5ZjY3ZjJkM2M2MDA4MzAzNzU1YjU2OTgxYjI1YTAwYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PFJZnFPfRjiYaOSlmcPPQaB6LImngHPg_FxzYRF_iCE) 好啦
> 
> 老哥能分享下么。下载不到了

[Uploading sixyin-music-source-v1.0.7_副本.txt…]()
请自行修改后缀为js

**Comment by TomLiu-GitHub** [comment]
已退回2.5,并决定永不更新

**Comment by laosunmaker** [comment]
洛雪2.6.0可使用我修改的六音脚本，https://github.com/laosunmaker/New_lxmusic_source，方法参照了 @hzq21 的代码，我在分析自定义音源的原理，这个仓库就先贴出来给大家用吧

**Comment by laosunmaker** [comment]
洛雪2.6.0可使用我修改的六音脚本，[https://github.com/laosunmaker/New_lxmusic_source](https://github.com/laosunmaker/New_lxmusic_source)，方法参照了 @hzq21 的代码，我在分析自定义音源的原理，这个仓库就先贴出来给大家用吧

**Comment by Azrael-W** [comment]
为什么改了以后每次打开会弹窗developer tools

**Comment by HuaChung** [comment]
> 洛雪2.6.0可使用我修改的六音脚本，https://github.com/laosunmaker/New_lxmusic_source，方法参照了 @hzq21 的代码，我在分析自定义音源的原理，这个仓库就先贴出来给大家用吧

导入后不报错，但是音源加载不出来，歌曲无法播放。
@huio  输出js脚本导入后可以正常使用

**Comment by ggb6070** [comment]
如果使用六音修改后无法正常播放，大概率是因为修改了名称，需要使用原来的名称：“@name 六音音源”

**Comment by dq77** [comment]
亲测添加垫片代码后可用，移动端1.2.0版本。

**Comment by jaylin0085** [comment]
大哥  厉害啊  能用了   最新版本：2.6.0

**Comment by jaylin0085** [comment]
大哥  厉害啊  能用了   最新版本：2.6.0

**Comment by loginzhou** [comment]
> 移动端 1.2.0-beta.27 及 桌面端 2.6.0-beta.10 开始移除了旧版源的兼容垫片代码：
> 
> [lyswhut/lx-music-mobile@4db5f03 #diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511](https://github.com/lyswhut/lx-music-mobile/commit/4db5f0394c225cd8d8e276b75d7cb1bb43718483#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511)
> 
> [7893814 #diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328](https://github.com/lyswhut/lx-music-desktop/commit/7893814da47516507a86d5e74eed80ec289efe90#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328)
> 
> 可以尝试在源的代码之前补上垫片代码：
> 
> ```js
> "undefined"==typeof window&&(window=globalThis),
> window.document||(window.document={}),
> Object.defineProperty(window.document,"getElementsByTagName",
> {value:e=>"script"==e?[Object.freeze({innerText:globalThis.lx.currentScriptInfo.rawScript}),]:null});
> ```
这个是最终答案，或者直接使用这个版本修改后缀名

**Comment by haili0715** [comment]
lx社区是真的强，感谢各位大佬的音源及时修改！

**Comment by linjiashu857** [comment]
感谢大家的帮助，2.6.0版本重新导入了v1.0.7成功了

**Comment by johnnyeecker** [comment]
> > 移动端 1.2.0-beta.27 及 桌面端 2.6.0-beta.10 开始移除了旧版源的兼容垫片代码：
> > [lyswhut/lx-music-mobile@4db5f03 #diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511](https://github.com/lyswhut/lx-music-mobile/commit/4db5f0394c225cd8d8e276b75d7cb1bb43718483#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511)
> > [7893814 #diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328](https://github.com/lyswhut/lx-music-desktop/commit/7893814da47516507a86d5e74eed80ec289efe90#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328)
> > 可以尝试在源的代码之前补上垫片代码：
> > ```js
> > "undefined"==typeof window&&(window=globalThis),
> > window.document||(window.document={}),
> > Object.defineProperty(window.document,"getElementsByTagName",
> > {value:e=>"script"==e?[Object.freeze({innerText:globalThis.lx.currentScriptInfo.rawScript}),]:null});
> > ```
> 
> 这个是最终答案，或者直接使用这个版本修改后缀名https://github.com/lyswhut/lx-music-desktop/files/14120996/sixyin-music-source-v1.0.7_.txt

这个有效,赞一个!

**Comment by helloplhm-qwq** [comment]
have a see in #1769

**Comment by GetStart13** [comment]
> 洛雪2.6.0可使用@huio 修改的六音脚本，https://github.com/laosunmaker/New_lxmusic_source，我把那个脚本收录进这个仓库便于大家下载，如果介意我可以删掉。一开始我自己想搞，但是有bug不能用。我在分析自定义音源应当如何实现，研究明白后，可能会写一个新音源。

研究明白后踢我一脚

**Comment by ws19** [comment]
> 移动端 1.2.0-beta.27 及 桌面端 2.6.0-beta.10 开始移除了旧版源的兼容垫片代码：
> 
> [lyswhut/lx-music-mobile@4db5f03#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511](https://github.com/lyswhut/lx-music-mobile/commit/4db5f0394c225cd8d8e276b75d7cb1bb43718483#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511)
> 
> [7893814#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328](https://github.com/lyswhut/lx-music-desktop/commit/7893814da47516507a86d5e74eed80ec289efe90#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328)
> 
> 可以尝试在源的代码之前补上垫片代码：
> 
> ```js
> "undefined"==typeof window&&(window=globalThis),
> window.document||(window.document={}),
> Object.defineProperty(window.document,"getElementsByTagName",
> {value:e=>"script"==e?[Object.freeze({innerText:globalThis.lx.currentScriptInfo.rawScript}),]:null});
> ```
> 
> **注意：修改它头部注释的原始内容可能会导致它失效**

你好，大佬，我手机用的是1.20-beta.25版本，安装上面的修改后，初始化报这个错误

**Comment by ws19** [comment]
> 移动端 1.2.0-beta.27 及 桌面端 2.6.0-beta.10 开始移除了旧版源的兼容垫片代码：
> 
> [lyswhut/lx-music-mobile@4db5f03#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511](https://github.com/lyswhut/lx-music-mobile/commit/4db5f0394c225cd8d8e276b75d7cb1bb43718483#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511)
> 
> [7893814#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328](https://github.com/lyswhut/lx-music-desktop/commit/7893814da47516507a86d5e74eed80ec289efe90#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328)
> 
> 可以尝试在源的代码之前补上垫片代码：
> 
> ```js
> "undefined"==typeof window&&(window=globalThis),
> window.document||(window.document={}),
> Object.defineProperty(window.document,"getElementsByTagName",
> {value:e=>"script"==e?[Object.freeze({innerText:globalThis.lx.currentScriptInfo.rawScript}),]:null});
> ```
> 
> **注意：修改它头部注释的原始内容可能会导致它失效**

你好，大佬，我手机用的是1.20-beta.25版本，安装上面的修改后，初始化报这个错误               property is not configurable at defineProperty(native) at <aval>(unknown.js 9)    该怎么处理，谢谢

**Comment by Noah17434** [comment]
> > 移动端 1.2.0-beta.27 及 桌面端 2.6.0-beta.10 开始移除了旧版源的兼容垫片代码：
> > [lyswhut/lx-音乐-mobile@4db5f03 #diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511](https://github.com/lyswhut/lx-music-mobile/commit/4db5f0394c225cd8d8e276b75d7cb1bb43718483#diff-295f4678042580afcf5d308058a274e4a4a2ddd3eb5aba86bfcc859419a58fb2L499-L511)
> > [7893814 #diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328](https://github.com/lyswhut/lx-music-desktop/commit/7893814da47516507a86d5e74eed80ec289efe90#diff-f8933e345c3bbf0b69c5a756bb048c9909a7f268841c0d51b6b96f0240ab2b39L317-L328)
> > 可以尝试在源的代码之前补上垫片代码：
> > ```js
> > "undefined"==typeof window&&(window=globalThis),
> > window.document||(window.document={}),
> > Object.defineProperty(window.document,"getElementsByTagName",
> > {value:e=>"script"==e?[Object.freeze({innerText:globalThis.lx.currentScriptInfo.rawScript}),]:null});
> > ```
> 
> 这个是最终答案，或者直接使用这个版本修改后缀名 https://github.com/lyswhut/lx-music-desktop/files/14120996/sixyin-music-source-v1.0.7_.txt

这个答案可以解决问题，2024年6月9日

**Comment by iridescentll** [comment]
谢谢，大佬。
