### ISSUE TITLE
[Bug]: 继lx 2.6.0 正式版之后有一些音源导不进去

### ISSUE THREAD

**Issue by sushmakab** [lyswhut/lx-music-desktop#1764]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

我在 [HuaChung](https://github.com/HuaChung) 的 开源项目中 https://github.com/laosunmaker/New_lxmusic_source 找到了ta对于六音音源的修改，但是ta修改了六音音源的描述，虽然初始化成功，但是歌曲始终无法加载，自己有突然想到六音音源是不能修改描述的，于是我手动把ta写的描述改成了原版，想导入进去，让歌曲加载。

### 实际行为

我修改了 [HuaChung](https://github.com/HuaChung) 在 https://github.com/laosunmaker/New_lxmusic_source 之后，发现修改后的源导入不进去了，因此我想请求各位大佬想想办法。

### Lx Music 版本

2.6.0 正式版

### 最后正常的版本

2.5.0 正式版

### 操作系统版本

Microsoft Windows 7 旗舰版

**Comment by sushmakab** [comment]
不好意思，各位大佬们，[HuaChung](https://github.com/HuaChung)，昨晚又把ta修改的源进行了二次修改，现在行了，但是目前知道的是还有一些源导不进去，这类源在 2.5.0 正式版是可以正常导入的，导入完之后卡在“正在初始化”或“初始化中”。

**Comment by 360faker** [comment]
我的win11设备上这源是可以正常使用的

**Comment by 360faker** [comment]
> 不好意思，各位大佬们，[HuaChung](https://github.com/HuaChung)，昨晚又把ta修改的源进行了二次修改，现在行了，但是目前知道的是还有一些源导不进去，这类源在 2.5.0 正式版是可以正常导入的，导入完之后卡在“正在初始化”或“初始化中”。

有哪些源无法导入？我在这边也试一下

**Comment by sushmakab** [comment]
> > 不好意思，各位大佬们，[HuaChung](https://github.com/HuaChung)，昨晚又把ta修改的源进行了二次修改，现在行了，但是目前知道的是还有一些源导不进去，这类源在 2.5.0 正式版是可以正常导入的，导入完之后卡在“正在初始化”或“初始化中”。
> 
> 有哪些源无法导入？我在这边也试一下

唉，可能是我修改的方式有问题。对 .js 文件也不熟悉，然后导致导入失败的。
但是我修改的源在 2.5.0 又可以倒进去，2.6.0 在导入这个源之前显示“这里竟然是空的”，导入完之后还是显示“这里竟然是空的”，当时我也很懵。。。
