### ISSUE TITLE
[Feature]: 更新 electron 版本

### ISSUE THREAD

**Issue by SamLukeYes** [lyswhut/lx-music-desktop#1776]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前 lx-music-desktop 使用的 electron 25 已于去年 12 月 5 日 EOL，该版本已经不再收到安全更新

### 描述你想要的解决方案

更新到最新的 electron 版本

### 附加信息

https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline

**Comment by StarVase** [comment]
如果你是开发者的话，你其实可以开一个pull request

**Comment by SamLukeYes** [comment]
抱歉，我并不熟悉 electron 开发，只是在为 NixOS 打包时发现无法简单地让 lx-music-desktop 使用尚未 EOL 的 electron 版本。我也尝试过从源码构建，但仍然没有找到升级 electron 版本并使构建产物能够正常运行的方法，不知道这个项目在更新 electron 版本时具体要做什么工作。

**Comment by lyswhut** [comment]
下个版本会升级到 v27
由于项目内包含预构建的二进制依赖，跨大版本更新时需要重新编译它们

**Comment by hwxlikemi** [comment]
> 下个版本会升级到 v27 由于项目内包含预构建的二进制依赖，跨大版本更新时需要重新编译它们

既然已经收到了腾讯律师函，却还在坚持更新，不怕被告吗？
