### ISSUE TITLE
添加 播放位置增加“歌曲添加到收藏列表 "功能

### ISSUE THREAD

**Issue by heimu360** [lyswhut/lx-music-desktop#178]
详见图片

![Image of Yaktocat](https://s1.ax1x.com/2020/04/14/GxsaLV.png)

**Comment by heimu360** [comment]
https://s1.ax1x.com/2020/04/14/GxsaLV.png

**Comment by lyswhut** [comment]
暂不计划加收藏按钮，作为代替方案，可鼠标右击（v0.18.0以前的版本为左击）播放封面定位歌曲后手动添加
