### ISSUE TITLE
[Bug]: mg的歌词下载不下来

### ISSUE THREAD

**Issue by zhengqwe** [lyswhut/lx-music-desktop#1783]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

mg的歌词正常下载

### 实际行为

从mg下载的歌都没有歌词，但播放界面能显示歌词，其他音源正常

### Lx Music 版本

2.6.0

### 操作系统版本

win

**Comment by lyswhut** [comment]
试试2.6.1-beta

**Comment by lyswhut** [comment]
已在v2.7.0修复
