### ISSUE TITLE
在我的列表中添加一个搜索功能

### ISSUE THREAD

**Issue by 13147334** [lyswhut/lx-music-desktop#1787]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

列表中不能搜索，找保存的歌麻烦

### 描述你想要的解决方案

在我的列表中添加一个搜索功能，在每一个列表（歌单）可以搜索保存到歌

### 描述你考虑过的替代方案

无

### 附加信息

无

**Comment by Georges6324** [comment]
Ctrl+F

**Comment by 13147334** [comment]
@Georges6324 
感谢感谢

**Comment by 13147334** [comment]
感谢感谢




星辰幻变
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月18日(星期天) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] 在我的列表中添加一个搜索功能 (Issue #1787)





 
Ctrl+F
