### ISSUE TITLE
[Feature]: 提供增强型LRC歌词下载

### ISSUE THREAD

**Issue by BnqDzj** [lyswhut/lx-music-desktop#1792]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在下载的歌词（无论是内嵌的还是单独的）都是普通的LRC歌词，普通LRC歌词时间不精确到单词，放到其他的本地听歌软件里无法开启卡拉OK模式

### 描述你想要的解决方案

提供增强型LRC歌词下载

**Comment by xzhzhaowendao** [comment]
逐字歌词受众不广，适配也较差，如果个人需要可以去https://github.com/jitwxs/163MusicLyrics这里下载

**Comment by lyswhut** [comment]
逐字歌词的语法没有一个统一的标准，各播放器的语法不一样，所以这个没法做
