### ISSUE TITLE
win版本缓存位置

### ISSUE THREAD

**Issue by Cody-Travers** [lyswhut/lx-music-desktop#1795]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

您好，可不可以把win版本资源和其他缓存不保存在c盘，我c盘只有100多G，时间长了占空间太大。

### 描述你想要的解决方案

比如提供一个开关，可以设置这两种缓存的存放位置

**Comment by Cody-Travers** [comment]
大佬可以细说下吗，我在常见问题中没有找到

**Comment by lyswhut** [comment]
目前没有计划提供自定义数据路径存储设置，数据存储说明看 https://lyswhut.github.io/lx-music-doc/desktop/datapath

使用便携数据存储方式需注意使用绿色版，不要使用安装板，否则自动更新时你的数据可能会被删除。
同时，手动更新时注意备份便携目录

**Comment by Cody-Travers** [comment]
不太了解便携存储方式，我主要是听一首新歌的时候缓存总是在"C:\Users\Administrator\AppData\Roaming\lx-music-desktop"这个里面，c盘没那么大容量，大佬没时间就算了。
