### ISSUE TITLE
[Bug]: 播放页面歌词区域鼠标光标不可见

### ISSUE THREAD

**Issue by Js2Hou** [lyswhut/lx-music-desktop#1798]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

播放界面，鼠标从歌曲封面专辑区域移动到右边歌词区域时，鼠标光标应该正常跟随移动显示

### 实际行为

播放界面，鼠标从歌曲封面专辑区域移动到右边歌词区域时，鼠标光标被歌词区域覆盖，不可见

### Lx Music 版本

2.6.0

### 操作系统版本

win11专业版 24H2 26058.1100

### 附加信息

https://github.com/lyswhut/lx-music-desktop/assets/45846642/73375917-bdb0-47e3-9144-f108a83455b4

视频中光标在歌词区域时变成了小手掌，是录取视频的原因，实际录制过程中是没有小手掌的。

最后正常的版本不知道。

**Comment by lyswhut** [comment]
![GIF](https://github.com/lyswhut/lx-music-desktop/assets/20365169/bea0e0b1-e367-4d78-8d1a-91f51739c6c6)

正常情况下歌词区域鼠标就是会变成手型，至于你电脑为什么不行就不清楚了

**Comment by Js2Hou** [comment]
好的，感谢！刚换了台电脑重新下载安装，确实是ok的，我自己再研究一下
