### ISSUE TITLE
[Feature]: 关于自定义背景下大部分情况，因为歌曲名是灰色的，所以看不太清楚地问题

### ISSUE THREAD

**Issue by Yuzuki0330** [lyswhut/lx-music-desktop#1799]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

因为我这边比较喜欢用自定义背景，如图所示，发现歌曲名是灰色的，在很多自定义图片背景下看的不太清楚，还不如歌词的颜色明显，想跟您请教一下有没有什么方法把歌曲名也改成白色的。

### 描述你想要的解决方案

把歌曲名也修改为白色，跟歌词一个颜色。

### 附加信息

![01](https://github.com/lyswhut/lx-music-desktop/assets/102216513/6f8c9cbc-8579-417e-9272-9b855b53d6bd)
![02](https://github.com/lyswhut/lx-music-desktop/assets/102216513/373e1626-d6d2-49b5-9e74-5056c9dfaf71)

**Comment by lyswhut** [comment]
可以安装最新测试版后再主题编辑器勾上深色字体选项看看效果

**Comment by Yuzuki0330** [comment]
您好，我这边更新到2.6.0版本了没有看到这个选项。是会在下次更新版本的时候增加这个选项么？

**Comment by lyswhut** [comment]
最新测试版：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by Yuzuki0330** [comment]
真的可以，非常感谢！
