### ISSUE TITLE
界面显示消失问题（几个版本都有）

### ISSUE THREAD

**Issue by virusmaster** [lyswhut/lx-music-desktop#18]
![2019-09-11 (1)](https://user-images.githubusercontent.com/54160944/64660006-1af27100-d471-11e9-929b-3a60b6e3a0ee.gif)

界面显示总是不稳定，界面元素总是喜欢消失，不知道啥问题。我上传了动画。

**Comment by virusmaster** [comment]
win7 64bit 环境，下载的X64和X86版本都这样，是缺少什么组件吗？

**Comment by lyswhut** [comment]
问题重复，解决方法参见：https://github.com/lyswhut/lx-music-desktop/issues/14

**Comment by virusmaster** [comment]
为了系统优化，AERO等效果都是关闭的。请问这个能做入选项吗？这样可以选择。

**Comment by lyswhut** [comment]
AERO效果都不想开。。电脑是有多老，后面看情况考虑添加支持吧

**Comment by lyswhut** [comment]
从0.14.0版本起，在不开启AERO效果时，可通过添加运行参数`-nt`来运行程序即可，
问题详情请查看常见问题：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#windows-7-%E4%B8%8B%E7%95%8C%E9%9D%A2%E5%BC%82%E5%B8%B8
