### ISSUE TITLE
希望添加qq音乐源

### ISSUE THREAD

**Issue by ygq-704292061** [lyswhut/lx-music-desktop#1801]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

添加qq音乐

### 描述你想要的解决方案

添加qq音乐

**Comment by justhzd** [comment]
你确定你搜索过issue，但凡看一下置顶issue也不会问这个。。。
