### ISSUE TITLE
[Bug]: Tray icon menu hardcoded to Simplified Chinese

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#1802]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

The tray icon menu text should follow the language settings in the software. For example, if the language in the software is English, the tray icon menu text should also be in English.

### 实际行为

Regardless of the language, the tray icon menu text is in Simplified Chinese.

### Lx Music 版本

2.7.0-beta.0

### 操作系统版本

Windows 11, version 23H2

### 附加信息

The tray icon menu text displays very poorly when the display language of Windows is set to English (or another language).

I have looked at the code within the repo and the related code seems to have it hardcoded to Simplified Chinese.

**Comment by lyswhut** [comment]
Added i18n to v2.7.0
