### ISSUE TITLE
请求异常，测试、临时接口都不行

### ISSUE THREAD

**Issue by jiansite** [lyswhut/lx-music-desktop#181]
![image](https://user-images.githubusercontent.com/33872552/79634965-6c4da600-81a0-11ea-9268-4d9afa3aab15.png)

**Comment by ncihnegn** [comment]
搜索tx不行了，搜索到的kw又请求异常。

**Comment by sheng-chen** [comment]
有同样的问题。

**Comment by liaohongdong** [comment]
有同样的问题。

**Comment by xavier1933** [comment]
是的有相同问题，求修复🌹🌹🌹

**Comment by heyapei** [comment]
同样问题 网易倒是挺好的

**Comment by marcusshen** [comment]
估计320Kbps的那些地址被封了吧

**Comment by jun9** [comment]
全都听不了了。

**Comment by heyapei** [comment]
你们把那个 优先播放高品质音乐 选项 勾选掉 就好了 好像是因为高品质音源问题
![image](https://user-images.githubusercontent.com/35768030/79931625-fbe3a500-847d-11ea-9460-8b2ca1b19d94.png)

**Comment by heyapei** [comment]
![image.png](https://i.loli.net/2020/04/22/zePdMnm8acljO7h.png)

**Comment by whbd1999** [comment]
无法下载，320K

**Comment by Funny0129** [comment]
听不了+1
下载高品质也不行了

**Comment by ncihnegn** [comment]
是不是@messoer的接口关了

**Comment by xiaocila** [comment]
也是这个问题

**Comment by byhooi** [comment]
同样的问题。优先播放高品质音乐默认是勾掉的

**Comment by lyswhut** [comment]
已在v0.18.0屏蔽不可播放的音质
