### ISSUE TITLE
[Feature]: 能否增加可以直接粘贴音源js文件的功能

### ISSUE THREAD

**Issue by learnerYan** [lyswhut/lx-music-desktop#1819]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

本地文件传输比较繁琐，且在汽车车机上出现了导入不了的问题，如果可以直接粘贴音源js文件的代码到软件里（或者输入网络地址），会方便很多

### 描述你想要的解决方案

音源js代码 可以直接粘贴到软件里

**Comment by lyswhut** [comment]
最新beta版已经支持：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml
