### ISSUE TITLE
[Bug]: 部分企鹅歌曲无法播放，有错误提示

### ISSUE THREAD

**Issue by ub007** [lyswhut/lx-music-desktop#1825]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常播放以及下载

### 实际行为

使用六音1.1.0和1.0.7音源在客户端2.6.0及2.5.0上，尝试播放企鹅音乐，部分歌曲无法播放，提示
Error invoking remote method 'winMain_request_user_api': Error: failed
![1](https://github.com/lyswhut/lx-music-desktop/assets/94854640/83039498-e4af-43e5-b081-16b25a68ff5c)

### Lx Music 版本

2.6.0

### 最后正常的版本

2.6.0

### 操作系统版本

Windows 11 22621.3296

**Comment by lyswhut** [comment]
音源的问题，与软件无关
