### ISSUE TITLE
[Feature]: 希望开放式api加入局域网的监听

### ISSUE THREAD

**Issue by skyworldp** [lyswhut/lx-music-desktop#1828]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我尝试在单片机上开发一个能够实时显示lx播放的歌词的功能,但是lx只提供了本地localhost的监听 

### 描述你想要的解决方案

希望可以加入局域网监听 或者开放开关是否监听0.0.0.0全部

**Comment by lyswhut** [comment]
可以试试 2.7.0-beta.5

**Comment by skyworldp** [comment]
> 可以试试 2.7.0-beta.5

感谢你的帮助和更新 作者大大牛逼

**Comment by lyswhut** [comment]
已在v2.7.0新增
