### ISSUE TITLE
[Bug]: 播放列表没有下载按钮

### ISSUE THREAD

**Issue by xiaofeng789** [lyswhut/lx-music-desktop#1831]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

播放列表应该有显示下载按钮

### 实际行为

播放列表没有下载按钮
![Uploading image.png…]()

### Lx Music 版本

2.6.0

### 操作系统版本

win11

### 附加信息

无

**Comment by xiaofeng789** [comment]
嗷嗷，知道啦，需要右击。。。

**Comment by ryanzhaorx** [comment]
<img width="1248" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/103013573/7502e3c7-64c4-4f5b-ae32-56a309b0d09a">
<img width="1248" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/103013573/e0c9d637-d0b1-486d-9b60-b936b496a7d9">
<img width="913" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/103013573/5366d566-aa5f-40a6-bee2-83ed875ccf20">
