### ISSUE TITLE
[Feature]: 建议优化一下托盘图标，目前的图标观感有点瑕疵

### ISSUE THREAD

**Issue by CkiRhub** [lyswhut/lx-music-desktop#1842]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前版本（2.7.0）的托盘图标有三种：白色与背景混在一起不易识别；黑色和彩色容易识别，但图标不够清晰，图标边缘不够顺滑。总体来看三种图标都有改进空间。

### 描述你想要的解决方案

建议更换更清晰美观的托盘图标，希望洛雪越来越好：）

### 附加信息

![屏幕截图 2024-04-16 114036](https://github.com/lyswhut/lx-music-desktop/assets/167158230/fa82c980-58e4-4fa0-9bbe-adb8c2966c50)
![屏幕截图 2024-04-16 114102](https://github.com/lyswhut/lx-music-desktop/assets/167158230/6627cd8d-9db3-43f0-8b60-2dd8f940e0b5)
![屏幕截图 2024-04-16 114116](https://github.com/lyswhut/lx-music-desktop/assets/167158230/4309a8dd-c802-4e02-9b87-fa3fbc20b953)
![屏幕截图 2024-04-16 114152](https://github.com/lyswhut/lx-music-desktop/assets/167158230/85481da3-25f8-498f-8e3d-4ecdf72813df)

**Comment by lyswhut** [comment]
试试 2.8.0-beta，优化了windows托盘图标的显示
