### ISSUE TITLE
[Bug]: MAC 版本 cmd+w 会自动中断播放

### ISSUE THREAD

**Issue by alminchen** [lyswhut/lx-music-desktop#1844]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

MAC 版本 cmd+w 会不中断播放

### 实际行为

MAC 版本 cmd+w 会自动中断播放

### Lx Music 版本

 2.7.0

### 操作系统版本

14.5

**Comment by lyswhut** [comment]
已在2.8.0-beta中修复，可以试试：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by SmallMousePP** [comment]
14.4.1 M1 pro 测试通过

**Comment by lyswhut** [comment]
已在 v2.9.0 修复
