### ISSUE TITLE
[Feature]: 歌单列表无法自定义排序，期待能添加该功能

### ISSUE THREAD

**Issue by 569432638** [lyswhut/lx-music-desktop#1851]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

歌单列表无法自定义排序，期待能添加该功能

### 描述你想要的解决方案

歌单列表无法自定义排序，期待能添加该功能

**Comment by Yarbin** [comment]
+1
