### ISSUE TITLE
在线导入自定义源提示 too large script，无法导入脚本过大的音源

### ISSUE THREAD

**Issue by chrisdong** [lyswhut/lx-music-desktop#1857]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

野花、野草在线导入都能成功，六音1.1.0和1.0.7改版两个都提示  too large script
![PixPin_2024-04-23_15-34-06](https://github.com/lyswhut/lx-music-desktop/assets/3366796/d831c08c-c813-4648-9d85-8cfd9bd965b6)

### 实际行为

我把常见的几个音源都上传到服务器，获取直链后，在lxmusic Windows客户端上导入，除了 六音两个音源无法导入，其他的都可以导入，提示脚本过大，能否修复这个bug
![1](https://github.com/lyswhut/lx-music-desktop/assets/3366796/73c44480-713f-480c-b5a5-3c11c950db98)

### Lx Music 版本

2.7.0

### 操作系统版本

Windows11

**Comment by ChloeKurumi** [comment]
兄弟，哪找的这么多音源，能分享下嘛？

**Comment by kabakao** [comment]
> 兄弟，哪找的这么多音源，能分享下嘛？

https://www.123pan.com/s/rFwDjv-Vbhb3.html

**Comment by lyswhut** [comment]
已在2.8.0-beta中修复，可以试试：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by GitHubWebb** [comment]
兄弟 求音源

**Comment by chrisdong** [comment]
在线导入https://lxmusic.ikunshare.com:9763/script?key=lxmusic 


音源作者https://github.com/ikun0014/

给上面的大佬来个关注[doge]【LX Music修改版教程（内置ikun音源+播放音质修改）-哔哩哔哩】 https://b23.tv/Ygla8yl

**Comment by GitHubWebb** [comment]
> 在线导入https://lxmusic.ikunshare.com:9763/script?key=lxmusic
> 
> 音源作者https://github.com/ikun0014/
> 
> 给上面的大佬来个关注[doge]【LX Music修改版教程（内置ikun音源+播放音质修改）-哔哩哔哩】 https://b23.tv/Ygla8yl
> 
> 或者https://wwp.lanzouq.com/b02fq9w8d 密码 lxmusic
感谢兄弟 已关注

**Comment by ikun0014** [comment]
> 在线导入https://lxmusic.ikunshare.com:9763/script?key=lxmusic
> 
> 音源作者https://github.com/ikun0014/
> 
> 给上面的大佬来个关注[doge]【LX Music修改版教程（内置ikun音源+播放音质修改）-哔哩哔哩】 https://b23.tv/Ygla8yl
> 
> 或者https://wwp.lanzouq.com/b02fq9w8d 密码 lxmusic

6
