### ISSUE TITLE
[Feature]: Mac版本，能和网易云音乐一样的，在顶部状态栏显示歌词就--完美了！

### ISSUE THREAD

**Issue by nogoo** [lyswhut/lx-music-desktop#1859]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

Mac版本歌词不支持在顶部，状态栏显示

### 描述你想要的解决方案

能和网易云音乐一样的，在顶部状态栏显示歌词就--完美了！

**Comment by ad1095445** [comment]
我问chatgpt写了swift代码，想用接口获取歌词，但是一直不显示，很烦

**Comment by ad1095445** [comment]
引用下别人的，这个软件可以实现，在设置里选择自动音乐播放器，他会根据歌名自己去网上拉歌词，有时候可能不匹配但已经很好了。https://github.com/ddddxxx/LyricsX

**Comment by ad1095445** [comment]
<img width="801" alt="截屏2024-08-20 17 33 48" src="https://github.com/user-attachments/assets/4e59a05b-7c38-4811-a837-1d6d144a15eb">

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/pull/1940
https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by lyswhut** [comment]
已在 v2.9.0 新增
