### ISSUE TITLE
[Bug]:音乐无法播放， api is not found

### ISSUE THREAD

**Issue by StupidMuggle** [lyswhut/lx-music-desktop#1861]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![WechatIMG1](https://github.com/lyswhut/lx-music-desktop/assets/56352506/c66570bc-4244-4ce8-8cb4-3270b60e3759)

### 实际行为

音乐无法播放， api is not found

### Lx Music 版本

2.7.0

### 最后正常的版本

2.7.0

### 操作系统版本

macos 13.0.1 (22A400)

### 附加信息

（*）

**Comment by StupidMuggle** [comment]
已解决

**Comment by Danielzzy51** [comment]
如何解决的？

**Comment by ihaoljy** [comment]
怎么弄的？

**Comment by loyea927** [comment]
同问，怎么解决的
