### ISSUE TITLE
[Feature]: 增加导入m4a格式音乐的功能

### ISSUE THREAD

**Issue by XYZscratcher** [lyswhut/lx-music-desktop#1864]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

是否可以增加导入m4a格式音乐的功能？

### 描述你想要的解决方案

![image](https://github.com/lyswhut/lx-music-desktop/assets/108533817/dad9c095-09ea-4a3f-837b-f575e0e04fbd)
本地的音乐目前并不支持导入m4a文件

**Comment by lyswhut** [comment]
试试 2.8.0-beta 版：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml
