### ISSUE TITLE
[Bug]: 在移动/触控设备上的体验欠佳

### ISSUE THREAD

**Issue by StarVase** [lyswhut/lx-music-desktop#1865]
在歌曲播放详情页，在开启允许通过歌词调整进度后，使用鼠标拖拽可以调整进度，但对于触控设备，在歌词位置拖动并不会有任何反馈。
希望项目桌面端能进一步针对触控设备的使用体验进行优化。

**Comment by san-ren** [comment]
开发者重心在桌面端，人家也说过，移动端”能用就行“

**Comment by StarVase** [comment]
> 开发者重心在桌面端，人家也说过，移动端”能用就行“

不过我针对的更倾向于不能移动但只能用触控的桌面端
交互式显示器

**Comment by lyswhut** [comment]
这是一个bug，歌词的拖动是支持触摸屏的，但是播放详情页的歌词忘了监听手指触摸事件，试试最新测试版，应该已经修复
