### ISSUE TITLE
关于请求异常，测试，临时接口都不行的问题

### ISSUE THREAD

**Issue by 45her** [lyswhut/lx-music-desktop#187]
![79931625-fbe3a500-847d-11ea-9460-8b2ca1b19d94](https://user-images.githubusercontent.com/64181914/80056229-5bad7f00-8556-11ea-9818-a675e35cef42.png)
把钩去掉就好了

**Comment by Qukkii** [comment]
以前一直勾了也可以播放，這問題他會自動修復嗎

**Comment by lyswhut** [comment]
已在v0.18.0屏蔽不可播放的音质
