### ISSUE TITLE
[Feature]: 可不可以像KMP或者potplayer那样，允许自主选择2.1声道和5.1声道的播放

### ISSUE THREAD

**Issue by tctw678** [lyswhut/lx-music-desktop#1873]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我用的电脑音箱是5.1声道的，就是蓝色绿色红色三条音频线插主板上面，声卡就是主板的瑞昱声卡，驱动是realtek的音频驱动，一般用KMP或者potplayer播放电影或者已经下载的音频文件，环绕音箱是会播放各种背景音乐的，但是用洛雪只有2.1声道也就是前置两个音箱中置一个音箱响而已，环绕的两个音箱是没声音，请问能加入5.1声道的功能么，实现类似KMP或者potplayer播放器那样，自由选择2.1或者5.1输出？

### 描述你想要的解决方案

请问能加入5.1声道的功能么，实现类似KMP或者potplayer播放器那样，自由选择2.1或者5.1输出？

**Comment by lyswhut** [comment]
5.1声道需要设备支持，我这边没有设备去测试这个功能，现在的默认输出通道数固定是2，晚些时候我会加一个 _是否使用接入的最大输出通道输出音频_ 的设置项，并将它默认启用，但我无法测试它是否有用

**Comment by lyswhut** [comment]
可以试试最新beta版是否有效：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by StarIICraft** [comment]
> 可以试试最新beta版是否有效：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

我这里测试无效，播放依然是中置和后置双环绕音箱不响，我用AIMP播放就是所有音箱都响

**Comment by lyswhut** [comment]
添加启动参数 `--disable-audio-output-resampler` 与 `--try-supported-channel-layouts` 启动试试？
