### ISSUE TITLE
[Bug]: 歌曲超长文件名下载本地的时候就会卡住不动

### ISSUE THREAD

**Issue by 1124714647** [lyswhut/lx-music-desktop#1877]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

Finale (feat. Zach Callison, Deedee Magno Hall, Estelle, Michaela Dietz, Grace Rolek, Uzo Aduba, Jennifer Paz, Shelby Rabara, Kate Micucci, Mathew Moy, Tom Scharpling & Toks Olagundoye) - Steven Universe、Deedee Magno Hall、Estelle、Grace Rolek、Jennifer Paz、Kate Micucci、Mathew Moy、Michaela Dietz、Shelby Rabara、Toks Olagundoye、Tom Scharpling、Uzo Aduba、Zach Callison

### 实际行为

![微信截图_20240503160256](https://github.com/lyswhut/lx-music-desktop/assets/44636698/bce7d94a-f3cb-4139-a74e-ffaa0686dcf6)
或者显示ENOENT: no such file or directory, open

### Lx Music 版本

2.8.0b3

### 操作系统版本

win10

**Comment by lyswhut** [comment]
文件名超出了系统对名字的长度限制导致的文件写入失败，现在加了文件名长度检查，过长会截取调超出的部分
之所以没显示下载失败是因为再次重试时内部事件冲突了，现在给重试加了一些延迟，可以试试 2.8.0-beta.4
