### ISSUE TITLE
[Feature]: win10，多媒体控制键调节音量，就会出现音量悬浮窗，如何关闭。[Feature]: 

### ISSUE THREAD

**Issue by xx777** [lyswhut/lx-music-desktop#1878]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![QQ截图20240503163235](https://github.com/lyswhut/lx-music-desktop/assets/13215485/015bc893-9b3e-4275-b5c2-7e073afcdfde)
chrome类浏览器已经关闭media控制。
开着lxmusic听歌，用键盘fn快捷键增加减少音量时就会出现上图的悬浮窗。关闭lxmusic就没这个问题。

### 描述你想要的解决方案

如何在lxmusic里关闭这个功能，我在设置里找不到相关功能的关闭按钮。

**Comment by lyswhut** [comment]
LX 内部用的就是与Chrome一样的media控制，你可以添加启动参数 `-dhmkh`试试，但这也将会禁用媒体快捷键的切歌支持

**Comment by xx777** [comment]
> LX 内部用的就是和 Chrome 一样的媒体控制，你可以添加启动参数`-dhmkh`尝试，但也不会禁止媒体快捷键的切歌支持
谢谢 已解决
