### ISSUE TITLE
希望添加安卓端

### ISSUE THREAD

**Issue by Jrebort** [lyswhut/lx-music-desktop#188]
希望开发者添加安卓端，我可以帮忙

**Comment by lyswhut** [comment]
谢谢好意，由于现有的代码基本无法重用，需要重写，但为什么现在仍然没有开始写，详情看：https://github.com/lyswhut/lx-music-desktop/issues/104

**Comment by zleiwang** [comment]
有卸载方法么

**Comment by lyswhut** [comment]
移动端已发布：https://github.com/lyswhut/lx-music-mobile
