### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NONGFUSPRING** [lyswhut/lx-music-desktop#1881]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

Mac版本 2.7.0可以正常安装使用

### 实际行为

安装完成后，点击打开，弹框提示“LX Music”已损坏，无法打开。

### Lx Music 版本

2.7.0

### 最后正常的版本

新用户安装

### 操作系统版本

macOS  14.4.1

### 附加信息

<img width="279" alt="截屏2024-05-05 22 58 49" src="https://github.com/lyswhut/lx-music-desktop/assets/8274996/45174910-910f-4ee8-9abc-ffb452118290">

**Comment by yangxuefei18** [comment]
我也是，一样的问题
