### ISSUE TITLE
[Bug]: 初始化源失败(sixyin 1.10)(Cannot read properties of null (reading 'statusCode'))

### ISSUE THREAD

**Issue by why2357** [lyswhut/lx-music-desktop#1882]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

1、本地导入 sixyin-music-source-v1.1.0
2、初始化成功

### 实际行为

1、本地导入 sixyin-music-source-v1.1.0
2、报错：Cannot read properties of null (reading 'statusCode')
![image](https://github.com/lyswhut/lx-music-desktop/assets/111210934/72f0dbe6-0846-4673-af24-a112837563cc)
![image](https://github.com/lyswhut/lx-music-desktop/assets/111210934/501b400a-4764-44f7-89d8-dce41b155e57)

### Lx Music 版本

2.7.0

### 操作系统版本

win11 23h2 22631.3527

### 附加信息

仅在本机出现问题，其他电脑均未出现此现象（包括同系统版本号win11）

**Comment by nkxingxh** [comment]
是不是装了**火绒6.0**

**Comment by why2357** [comment]
> 是不是装了**火绒6.0**

已解决，十分感谢

**Comment by Lengzixi** [comment]
好像是被火绒的web扫描给拦了，加个白名单好像就行了qwq
