### ISSUE TITLE
[Feature]: 通过api调用播放器功能

### ISSUE THREAD

**Issue by xuan06zyx** [lyswhut/lx-music-desktop#1886]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我在开发自用的直播点歌机，能否做到调用api从而达到播放、切歌、删除列表中的某首歌之类的功能？我已经有一个仅有点歌功能的项目了，如果可以的话我还是希望能有一个播放器样式的（但是我对前端一窍不通又不会做T-T）

### 描述你想要的解决方案

通过api调用播放函数（应该是这样的吧？）或修改如播放列表之类的

**Comment by lyswhut** [comment]
你是指开放API吗？你想要新增哪些API？

**Comment by xuan06zyx** [comment]
是的，目前来讲仅对我个人而言能做到播放/暂停、切歌就够用了，播放列表我自己可以解决，我具体想要实现的功能是这样的：我的程序调用开放api在当前播放列表中添加下一首歌曲，

**Comment by lyswhut** [comment]
如果是本地程序调用的话，可以通过已经有的 [Scheme URL](https://lyswhut.github.io/lx-music-doc/desktop/scheme-url) API去调用

**Comment by xuan06zyx** [comment]
我抄文档里issue别人的代码进行测试发现基本上没问题，只是自定义源该怎么填？不过添加歌曲到下一首、切换歌曲之类的功能没有，以及只传歌名，通过搜索列表默认选择播放第一首歌曲的功能（类似功能做到只传歌名点歌的）有没有？
![QQ截图20240513005427](https://github.com/lyswhut/lx-music-desktop/assets/126635659/f92c3886-beb5-4477-bcee-92afe14fdc26)
`#python
from urllib.parse import quote
import webbrowser
import json

func = "播放歌曲"  # 功能名，支持打开歌单、播放歌单、搜索歌曲、播放歌曲
name = "希望有羽毛和翅膀"  # 歌曲名
singer = ""  # 艺术家名
source = "tx"  # 源，支持kw/kg/tx/wy/mg
func_list = {
    "打开歌单": "songlist/open",
    "播放歌单": "songlist/play",
    "搜索歌曲": "music/search",
    "播放歌曲": "music/play",
}
data = {
    "打开歌单": {
        "source": "tx",  # 支持 kw/kg/tx/wy/mg
        "id": "",
        "url": "",  # id和url必须传一个
    },
    "播放歌单": {
        "id": "",
        "url": "",  # id和url必须传一个
        "index": 0,  # 播放第几首，从0开始
    },
    "搜索歌曲": {
        "keywords": name,
        "source": source,
    },
    "播放歌曲": {
        "name": name,  # 歌曲名，必须
        "singer": singer,  # 艺术家，必须
        "source": source,  # 源，必须
        "songmid": "",  # 歌曲id，必须
        "img": "",  # 歌曲图片了解，选传
        "albumId": "",  # 歌曲专辑id，选传
        "interval": "",  # 格式化后歌曲时长，选传，例如 03:55
        "albumName": "",  # 歌曲专辑名称，宣传
        "types": [{"type": "flac", "size": "", "hash": ""}],  # type 128k/320k/flac/flac24bit
        "hash": "",  # kg必须
        "strMediaMid": "",  # tx必传
        "copyrightId": "",  # tx选传
        "lrcUrl": "",  # mg选传
    },
}
url = f"lxmusic://{func_list[func]}?data=" + quote(f"{json.dumps(data[func], ensure_ascii=False)}")
print("编码后的url:", repr(url))

webbrowser.open(url=url)
`

**Comment by lyswhut** [comment]
> 不过添加歌曲到下一首、切换歌曲之类的功能没有。

这个之前开那个issue的时候没有，但现在已经有了，看文档

> 只传歌名，通过搜索列表默认选择播放第一首歌曲的功能（类似功能做到只传歌名点歌的）会出吗？

现在确实没有这个，也是那个issue后面我提的，但一直没有加，我在下个版本加上

**Comment by xuan06zyx** [comment]
非常感谢！另外播放器本身以及各个API可以加一个搜索&播放专辑的功能吗？就像歌单一样

**Comment by lyswhut** [comment]
软件本身不支持歌手、专辑的获取，这些功能没有实现，所以这两块功能的api无法提供，现在也没有添加它们的计划

**Comment by xuan06zyx** [comment]
> 软件本身不支持歌手、专辑的获取，这些功能没有实现，所以这两块功能的api无法提供，现在也没有添加它们的计划

好的

**Comment by ThermalEX** [comment]
![屏幕截图 2024-12-16 164805](https://github.com/user-attachments/assets/16bf907e-6fcd-4314-9a8d-8657c602b4b3)
![屏幕截图 2024-12-16 164853](https://github.com/user-attachments/assets/609fb202-af8f-48b2-a4c5-5a57d45b2474)
![image](https://github.com/user-attachments/assets/bee669fb-aa8f-4ea1-9553-fdcdaeb636e0)
![image](https://github.com/user-attachments/assets/133b2fa5-e06b-4d32-84ce-35387546d6b9)

简单做了一个qi前端😋效果挺好的哈哈哈哈
