### ISSUE TITLE
[Bug]: 可以播放音乐但是没有声音，歌词再走但下面进度条不动

### ISSUE THREAD

**Issue by JnanftWr** [lyswhut/lx-music-desktop#1891]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![屏幕截图 2024-05-11 151902](https://github.com/lyswhut/lx-music-desktop/assets/155878710/c74795a7-9d57-4674-bdac-4797f3270911)

### 实际行为

![屏幕截图 2024-05-11 151902](https://github.com/lyswhut/lx-music-desktop/assets/155878710/c73bb459-8899-48b0-b3d0-7708fb181609)

### Lx Music 版本

2.7

### 最后正常的版本

2.7

### 操作系统版本

2.7

### 附加信息

![屏幕截图 2024-05-11 151902](https://github.com/lyswhut/lx-music-desktop/assets/155878710/a549f73d-a793-4016-9c0e-758d3287d90d)

**Comment by lyswhut** [comment]
是否所有歌曲都这样？
https://github.com/lyswhut/lx-music-desktop/issues/1540#issuecomment-1703015119

**Comment by JnanftWr** [comment]
![屏幕截图 2024-05-12 224542](https://github.com/lyswhut/lx-music-desktop/assets/155878710/9837068a-6931-4c1b-a649-6c44cdce36c5)
![屏幕截图 2024-05-12 224615](https://github.com/lyswhut/lx-music-desktop/assets/155878710/561cb15a-273a-4136-83fe-7d3848167739)
是没有音频输出吗
