### ISSUE TITLE
[Bug]: 没有音频输出

### ISSUE THREAD

**Issue by JnanftWr** [lyswhut/lx-music-desktop#1896]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![屏幕截图 2024-05-12 224542](https://github.com/lyswhut/lx-music-desktop/assets/155878710/7486680a-0733-4326-89ad-105ab6b49d95)

### 实际行为

![屏幕截图 2024-05-12 224615](https://github.com/lyswhut/lx-music-desktop/assets/155878710/6dde8a07-8c71-46aa-ba1e-98fd5c227271)

### Lx Music 版本

2.7

### 最后正常的版本

2.7

### 操作系统版本

2.7

**Comment by lyswhut** [comment]
你电脑环境问题，程序没找到输出设备，检查声卡驱动？或者重装下声卡驱动？

**Comment by qu17666103117** [comment]
这个是电脑问题了，驱动大师扫描一下硬件
