### ISSUE TITLE
linux系统下桌面配置文件.desktop的几个小问题

### ISSUE THREAD

**Issue by lowy** [lyswhut/lx-music-desktop#19]
系统是linuxmint19.2 安装的是0.5.4-22的deb
安装之后出现的问题有: 系统菜单分类里找不到 图标不显示等问题
我自行修改了下  /usr/share/applications/lx-music-desktop.desktop：
[Desktop Entry]
Name=lx-music-desktop
Name[zh_CN]=洛雪音乐助手                                                                             #添加了中文名称显示
Exec=/opt/lx-music-desktop/lx-music-desktop %U
Terminal=false
Type=Application
Icon=/usr/share/icons/hicolor/0x0/apps/lx-music-desktop.png #这个"0x0"默认不显示图标 最好改成"24x24"或"32x32"
StartupWMClass=lx-music-desktop
Comment=一个免费的音乐下载助手
Categories=Utility;AudioVideo;Audio;Player;Music;                             #添加了菜单项方便查找和启动

**Comment by lyswhut** [comment]
感谢反馈！

Linux的包确实有些问题，之前我发现的图标不显示的问题一直没有解决，不过也不怎么影响使用，然后最近在忙其他的就忽略了😅，后面再抽时间研究下。。

**Comment by grassvalley** [comment]
是的，这个问题在0.6.1版本依然存在。其实在gnome环境下，Categories的Audio;Player;Music;分类好像都没有用。

**Comment by lyswhut** [comment]
这个问题在0.6.1没有做任何修复工作，对使用影响不大的bug暂时延后先。。

**Comment by warmscar** [comment]
最新的0.7也还没有修复，不过不影响使用。

**Comment by lyswhut** [comment]
@lowy @grassvalley @warmscar 
该问题已在0.12.0修复，感谢反馈！
