### ISSUE TITLE
Linux版开启托盘的情况下无法退出程序

### ISSUE THREAD

**Issue by lyswhut** [lyswhut/lx-music-desktop#191]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
Linux版开启托盘的情况下无法退出程序，需要取消托盘才可退出程序

**重现**
重现行为的步骤：
1. 设置-勾选开启托盘
2. 从左上角菜单或dock退出程序
3. 看到问题

**预期行为**
开启托盘的情况下，点左上角菜单的退出或dock退出可退出程序，点程序右上角的关闭按钮不退出程序。

**环境：**
- 操作系统及版本：Ubuntu 18.10
- 软件安装包及版本：0.18.2

**Comment by zleiwang** [comment]
你是安装的deb文件吧？APPimage那个也是，开启托盘。左键或右键托盘的图标都没响应，即无法退出。

**Comment by lyswhut** [comment]
由于这只是Linux版的问题，目前不打算再向所有平台推送更新，我将在`dev`分支发布 `v0.18.3` 修复这个问题，修复该问题的安装包下载地址：
<https://bintray.com/lyswhut/lx-music-desktop/lx-music-desktop/0.18.3#files>

**Comment by lyswhut** [comment]
已在v1.0.0修复该问题
