### ISSUE TITLE
[Feature]:主题背景图片透明化

### ISSUE THREAD

**Issue by scghe114** [lyswhut/lx-music-desktop#1918]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

添加新主题和背景图片后背景图片只有侧边栏区域有显示
![Snipaste_2024-06-01_02-51-06](https://github.com/lyswhut/lx-music-desktop/assets/171331486/719710a9-08f7-4b7f-9d04-c9531bf2ee72)
只有在某些特定情况下背景图片才能完全显示
![Snipaste_2024-06-01_02-52-08](https://github.com/lyswhut/lx-music-desktop/assets/171331486/9d4dbb57-428c-451a-b340-d7c51b890203)
这导致了该功能处于一个几近无法使用的状态

### 描述你想要的解决方案

让自定义主题的背景图片能和LX Music自带的主题背景图片一样显示
![Snipaste_2024-06-01_02-58-54](https://github.com/lyswhut/lx-music-desktop/assets/171331486/aa567890-6a64-415b-9c90-705024db6afa)

### 描述你考虑过的替代方案

我不到啊

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/1190

**Comment by scghe114** [comment]
已解决，多谢大大
![Snipaste_2024-06-01_17-24-18](https://github.com/lyswhut/lx-music-desktop/assets/171331486/910a6c91-987c-4c59-bd68-154f4962b154)
