### ISSUE TITLE
聚合搜索功能失效

### ISSUE THREAD

**Issue by u8989332** [lyswhut/lx-music-desktop#192]
描述错误
更新至0.18.2版，聚合搜索功能失效

重现
重现行为的步骤：

1. 透过线上更新，聚合搜索功能无呈现任何结果
2. 透过GITHUB Release下载最新，仍一样状况
3. 其他搜索功能正常

预期行为
聚合搜索功能呈现任何结果

截图
聚合搜索功能失效截图
https://imgur.com/a2xxqQk

其他搜索功能正常截图
https://imgur.com/vPUVeFQ
https://imgur.com/cuLda6r

环境：
  -操作系统及版本：[Windows 10 64位 18363.592]

其他内容

**Comment by lyswhut** [comment]
因百度源的搜索失效导致其搜索失败，最终导致聚合搜索失败

**Comment by lyswhut** [comment]
经测试，千千音乐官网也无法搜索，应该是官方的问题，等待官方修复吧

**Comment by u8989332** [comment]
今日可使用

**Comment by lyswhut** [comment]
确实已经恢复
