### ISSUE TITLE
[Bug]: 右键单击Dock图标或菜单栏图标选择“退出”无反应

### ISSUE THREAD

**Issue by JonyChuh** [lyswhut/lx-music-desktop#1923]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望能像Mac上其他APP一样，右键单击Dock图标或者菜单栏图标选择“退出”，就能完全退出APP。

### 实际行为

右键单击Dock图标选择“退出”无反应，右键单击菜单栏图标选择“退出”，只是退出了菜单栏图标，但Dock图标并未退出。此时，点击Dock图标会显示主界面，再次右键单击Dock图标选择“退出”，APP才真正地完全退出。

### Lx Music 版本

2.8.0

### 最后正常的版本

2.8.0

### 操作系统版本

macOS Ventura 13.6.7

**Comment by 1751105638** [comment]
我也遇到了同样的问题

**Comment by lyswhut** [comment]
试试 2.8.1-beta.0
https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by 1751105638** [comment]
> 试试 2.8.1-beta.0 https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

2.8.1-beta.0 解决了关闭不掉的问题，同时之前被修复的问题又恢复了，command+w 会暂停播放
https://github.com/lyswhut/lx-music-desktop/issues/1844

**Comment by lyswhut** [comment]
再试试beta1

**Comment by 1751105638** [comment]
> 再试试beta1

更新后未发现明显异常，已解决

**Comment by lyswhut** [comment]
也就是说还有异常？什么异常呢？

**Comment by 1751105638** [comment]
> 也就是说还有异常？什么异常呢？

不不不，意思就是暂时看得到很明显的问题已经没有了，其它待测试。 没有问题了，待我继续使用 有问题在反馈，谢谢Thanks♪(･ω･)ﾉ

**Comment by JonyChuh** [comment]
> 再试试beta1

谢谢

**Comment by zhoupeng260641663** [comment]
找到解决方法了  在基本设置中 取消 关闭软件时不退出软件将其最小化到系统托盘 就行

**Comment by lyswhut** [comment]
已在 v2.9.0 修复

**Comment by JonyChuh** [comment]
已更新到v2.9.0，谢谢！
