### ISSUE TITLE
[Bug]: "lyricLineAllText"在无歌词音乐时没有及时更新

### ISSUE THREAD

**Issue by Lengzixi** [lyswhut/lx-music-desktop#1925]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

"lyricLineAllText"在有歌词音乐切换到无歌词音乐后及时更新

### 实际行为

"lyricLineAllText"在有歌词切换到无歌词后仍显示上一首音乐的歌词内容，此时"lyricLineText"显示为空。

### Lx Music 版本

2.8.0

### 操作系统版本

Windows 11

### 附加信息

![屏幕截图 2024-06-04 134022](https://github.com/lyswhut/lx-music-desktop/assets/102642534/64705378-24fe-4627-b24c-f9f615bd827c)

**Comment by lyswhut** [comment]
试试 2.8.1-beta.2

**Comment by Lengzixi** [comment]
没有问题了，非常感谢作者qwq
