### ISSUE TITLE
[Feature]: Bump Electron to 29.0.0

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#1929]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

According to the release cadence and version support policy of the Electron team, the currently used 28.0.0 is about to enter EOL.

[Electron Releases](https://www.electronjs.org/docs/latest/tutorial/electron-timelines)

### 描述你想要的解决方案

Considering that the software is still being maintained and the `dev` branch has new bug fixes, should we consider upgrading Electron?

Judging from the commit history of the repo, you are trying to strike a balance between maintaining version updates and stability. Visual Studio Code just released [version 1.90](https://code.visualstudio.com/updates/v1_90). In this milestone they bumped Electron to 29.0.0. Now that they have done this, I think now is the best time to bump Electron.

**Comment by lyswhut** [comment]
Yes, in fact, we are basically following the pace of vs code to upgrade the electron version.

**Comment by lyswhut** [comment]
Updated to v30.4.0 in v2.9.0
