### ISSUE TITLE
小秋小云小杜搜索没有结果

### ISSUE THREAD

**Issue by ncihnegn** [lyswhut/lx-music-desktop#193]
**解决方案检查**
- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
小秋小云小杜搜索没有结果，其它几个都可以

**重现**
重现行为的步骤：
1、使用测试接口
2、搜索

**预期行为**
所有音源都返回结果。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -macOS Catalina 10.15.4
  -0.18.2

**其他内容**

**Comment by lyswhut** [comment]
经测试除了千千音乐，其他都正常，千千音乐的问题看：https://github.com/lyswhut/lx-music-desktop/issues/192
