### ISSUE TITLE
[Bug]: 下载音乐后，都是6秒音频，内容为：您所播放的内容需开通会员后免费畅听，如已是会员，请到应用商店更新最新版本

### ISSUE THREAD

**Issue by Heartbreaker16** [lyswhut/lx-music-desktop#1936]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

下载mp3文件即为歌曲原文件

### 实际行为

实际下载的mp3文件的内容都是6秒的音频：内容为：您所播放的内容需开通会员后免费畅听，如已是会员，请到应用商店更新最新版本

### Lx Music 版本

2.8.0 、2.7.0

### 最后正常的版本

 --

### 操作系统版本

macOS Sonoma 14.5

### 附加信息

1. 已安装所有能搜索到的源，在各个平台搜索下载的音乐都是以上结果
2. 下载的是320k音频

**Comment by laonuodr** [comment]
咱俩一样

**Comment by ikun0014** [comment]
这个音效我不知道是不是kw独有的，但不是LX Music本身的问题

**Comment by LQZ100** [comment]
音源的问题，音源的酷我源失效了就出现这个

**Comment by lunawei888** [comment]
换了音源还是这样，换了好几个了

**Comment by laolaoali** [comment]
> 换了音源还是这样，换了好几个了
换完音源清理歌曲缓存试试看

**Comment by Heartbreaker16** [comment]
后来经本人添加源的方式解决了，确实是源的问题，附上目前正在用的源列表：<img width="225" alt="image" src="https://github.com/user-attachments/assets/49ef5114-9535-4d13-b497-a5998d55659f">

**Comment by Heartbreaker16** [comment]
后来经本人添加源的方式解决了，确实是源的问题，附上目前正在用的源列表：

**Comment by Heartbreaker16** [comment]
后来经本人添加源的方式解决了，确实是源的问题，附上目前正在用的源列表：

**Comment by Heartbreaker16** [comment]
后来经本人添加源的方式解决了，确实是源的问题，附上目前正在用的源列表：
<img width="225" alt="image" src="https://github.com/user-attachments/assets/1a40967c-5d08-432a-ad7a-e938230ae697">
如果切换源还不行，可以试试以下方法：
1. 更换平台搜索；
2. 同一歌曲的同一制作版本可能会多次收录在不同专辑中，原版的下不到可以在搜索结果的其他专辑收录版里找平替；
3. 非中文的歌曲，可能会因为歌名翻译问题而有多个不同名版本，而实际上都是同样的内容。留意一下歌曲的原名和所有可能翻译；

只要一首歌稍微有点人气，因为不同翻译、不同收录专辑、不同平台的而产生的所有副本，好歹也能有10个了吧。所有这些组合在全部音源中都能挂的概率实在太低。

**Comment by ikun0014** [comment]
😊😊😊
