### ISSUE TITLE
试听列表中的批量删除不见了？

### ISSUE THREAD

**Issue by jindx0713** [lyswhut/lx-music-desktop#194]
**描述错误**
更新0.18.2后，试听列表中批量删除、批量下载的浮动按钮不见了。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。
![image](https://user-images.githubusercontent.com/30382973/80958042-ed5e9b80-8e36-11ea-8151-c1c71287c05c.png)
![image](https://user-images.githubusercontent.com/30382973/80958140-1c750d00-8e37-11ea-9fcb-79bf13b7344e.png)

**环境：**
  -操作系统及版本：OSX 10.15.4
  -软件安装包及版本：0.18.2

**Comment by lyswhut** [comment]
详情看更新日志0.18.0的更变部分：<https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md#0180---2020-05-01>
