### ISSUE TITLE
[Feature]: 如何从洛雪的歌单导出链接到别的软件

### ISSUE THREAD

**Issue by Txinkang** [lyswhut/lx-music-desktop#1947]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

可以从别的软件导入歌单链接来洛雪听，反过来洛雪导出到别的软件怎么做

### 描述你想要的解决方案

也出一个分享链接呗

**Comment by lyswhut** [comment]
不支持导到其他平台
