### ISSUE TITLE
更新时会删除原安装文件但是新版安装包没有继续安装怎么回事？

### ISSUE THREAD

**Issue by wolffy1998** [lyswhut/lx-music-desktop#196]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
你安装的时候是以管理员身份安装的吧？运行软件的时候没有以管理员身份运行，所以卸载后无法再装上。

**Comment by wolffy1998** [comment]
我安装在所有用户上progammer目录更新时卸载后不会重新安装，但是安装在个人用户上更新就可以了
---原始邮件---
发件人:"lyswhut"<notifications@github.com>;
发送时间:2020年5月8日(星期五) 晚上9:03
收件人:"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com>;
抄送人:"·|梁聪"<1192128500@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [lyswhut/lx-music-desktop] 更新时会删除原安装文件但是新版安装包没有继续安装怎么回事？ (#196)



 
你安装的时候是以管理员身份安装的吧？运行软件的时候没有以管理员身份运行，所以卸载后无法再装上。
 
&mdash;
