### ISSUE TITLE
[Bug]: 左侧功能图标显示异常

### ISSUE THREAD

**Issue by CkiRhub** [lyswhut/lx-music-desktop#1960]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

左侧功能图标显示异常

### 实际行为

左侧功能图标显示异常：图标的右侧和下侧显示不完整，被裁切了。

### Lx Music 版本

2.8.0

### 操作系统版本

Windows11

### 附加信息

![屏幕截图 2024-06-26 120739](https://github.com/lyswhut/lx-music-desktop/assets/167158230/03dc6b95-acbc-4ab8-b128-d60770710883)

**Comment by lyswhut** [comment]
已在 v2.9.0 优化
