### ISSUE TITLE
[Bug]: 关于lx-music开发 vue-devtools无法打开的情况

### ISSUE THREAD

**Issue by Elawen-Carl** [lyswhut/lx-music-desktop#1969]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

一般运行之后会有vue devtools工具在控制台打开

### 实际行为

在了解整个项目之后，我尝试添加自己的代码上去，并没有什么太大的错误，可是当我用vue-devtools工具时发现并没有，我翻阅了项目issue并没有相关的东西，我尝试了在项目的·src\main\index-dev.ts·文件中修改成vue3的vue devtools，也尝试了查询electron官方文档的方法启用vue devtools工具，并且也尝试了询问gpt解答的解决方法，还是没有解决这个小小的问题。
![image](https://github.com/lyswhut/lx-music-desktop/assets/81508974/b31b122f-3a40-4f03-8d64-7b4046b712fb)
这是我在开发时她能够正常添加vue-devtools但是在项目运行时却没有
![image](https://github.com/lyswhut/lx-music-desktop/assets/81508974/00385a95-440b-4c8a-a1e8-875063187dc0)

### Lx Music 版本

2.8.0

### 操作系统版本

windows 10 22H2

**Comment by lyswhut** [comment]
拉下 dev 分支最新的代码试试
