### ISSUE TITLE
更新到0.18.2版本后批量功能健没有了

### ISSUE THREAD

**Issue by youtwo999** [lyswhut/lx-music-desktop#197]
0.18.2版本更新后，从排行榜搜出的歌曲没有批量添加到试听列表，试听列表里面的歌曲没有批量删除功能了？

**Comment by youtwo999** [comment]
如题

**Comment by RUKDGME** [comment]
改成键盘快捷键了，参考[194](https://github.com/lyswhut/lx-music-desktop/issues/194#issue-611775344)
