### ISSUE TITLE
[Bug]: macOS 无法退出软件

### ISSUE THREAD

**Issue by Isaaclzg** [lyswhut/lx-music-desktop#1979]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

退出软件

### 实际行为

无法退出，只能强制关闭

### Lx Music 版本

2.8.0

### 操作系统版本

macOS ventura 13.5

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/1923
