### ISSUE TITLE
移除蓝牙耳机等设备时,音乐暂停

### ISSUE THREAD

**Issue by dangfei1024** [lyswhut/lx-music-desktop#198]
**解决方案检查**

- [x]  我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x]  我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
带着蓝牙耳机走出蓝牙连接范围外,音乐还在播放.希望能暂停播放

**Comment by dangfei1024** [comment]
移除蓝牙耳机等设备时,音乐暂停

**Comment by dangfei1024** [comment]
移除蓝牙耳机等设备时,音乐暂停

**Comment by lyswhut** [comment]
现在有两种暂停机制：
1. 所选音频输出设备被移除时，将暂停播放
2. 当前音频输出设备改变时将暂停播放

你接入蓝牙后，有手动指定过音频输出设备吗？

**Comment by lyswhut** [comment]
已在v1.0.0新增该功能
