### ISSUE TITLE
[Bug]: 存在api连接错误的情况(自定义源：sixyin1.07ver)

### ISSUE THREAD

**Issue by haili0715** [lyswhut/lx-music-desktop#1980]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

同源歌曲匹配，同一歌曲的api调用保持各平台一致（猜测自定义源原因）

### 实际行为

同源歌曲连接错误，产生歌词lrc以及模糊搜索匹配

### Lx Music 版本

2.8.0

### 最后正常的版本

2.8.0

### 操作系统版本

win10

### 附加信息

使用为第三方音源：sixyin1.07ver

**Comment by haili0715** [comment]
/

**Comment by steve88552** [comment]
被警告后让我自己导入播放源，怎么找阿好哥哥教教吧
