### ISSUE TITLE
[Feature]: 为歌曲详情页添加更多选项

### ISSUE THREAD

**Issue by MMagine** [lyswhut/lx-music-desktop#1985]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![屏幕截图 2024-07-26 145016](https://github.com/user-attachments/assets/fe2da652-5895-45a8-9e44-f84d8ffbedec)
![屏幕截图 2024-07-26 145020](https://github.com/user-attachments/assets/6937fafe-d79b-4333-8196-beec4e3904e4)
真心希望能够增加与桌面歌词同等的功能。 

### 描述你想要的解决方案

**### 歌词不延迟滚动**这个真的是刚需
**有些时候正在播放的歌词不在最中间**对于有强迫症的人士而言，这种情况可能难以忍受

**Comment by MMagine** [comment]
爱你哦

**Comment by lyswhut** [comment]
已在 v2.9.0 新增 歌词不延迟滚动
