### ISSUE TITLE
[Feature]: 搜索歌曲

### ISSUE THREAD

**Issue by MMagine** [lyswhut/lx-music-desktop#1986]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![屏幕截图 2024-07-26 150114](https://github.com/user-attachments/assets/dda79d82-c2b0-4493-b7f5-2e3d7165c6d2)
移动版具备搜索歌曲的功能，桌面版却没有

### 描述你想要的解决方案

烦请为桌面版落雪增添正规的歌曲搜索功能，而不是在搜索框中重复进行搜索操作

**Comment by ikun0014** [comment]
？没看懂

**Comment by MMagine** [comment]
> ？没看懂

um其实就是在收藏的歌曲列表中查找想要的歌曲，只是目前现有的“搜索”功能仅仅是在搜索框里搜索同名歌曲罢了

**Comment by OMhero1** [comment]
CTRL+F

**Comment by MMagine** [comment]
> CTRL+F

wc真的谢谢

**Comment by Momoko12138** [comment]
MacOS是command+F
