### ISSUE TITLE
[Bug]: 选择音源时一直卡在初始化中

### ISSUE THREAD

**Issue by TealLymn** [lyswhut/lx-music-desktop#1988]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

选择音源时初始化快速完成

### 实际行为

https://github.com/user-attachments/assets/5529aa0a-5781-4739-a4e2-5dbf14239914

选择音源时，无论什么音源，一直卡在初始化中

### Lx Music 版本

2.9.0-beta.5

### 最后正常的版本

2.9.0-beta.2

### 操作系统版本

Windows 7

**Comment by lyswhut** [comment]
试试 2.9.0-beta.6

**Comment by TealLymn** [comment]
已成功解决，感谢洛雪大大
