### ISSUE TITLE
[Feature]: 关于windows x64版桌面歌词相关的问题

### ISSUE THREAD

**Issue by SSuperBBoy** [lyswhut/lx-music-desktop#1995]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![屏幕截图 2024-08-02 142129](https://github.com/user-attachments/assets/484590a9-c470-4fae-9fa5-5f5003e28f28)
我把桌面歌词放在屏幕右下角，歌词就会遮挡住所在屏幕区域，如果我想打开右下角的文件，就必须把歌词移动到其他地方才能打开文件

### 描述你想要的解决方案

希望桌面歌词不会遮挡所在区域的互动按钮，并且把桌面歌词窗口大小，文字大小，减小或增加透明度等设置转移到主界面设置中

**Comment by akiirokaede** [comment]
![e86485dc2dffe2968a9a623fcfaf895](https://github.com/user-attachments/assets/2e81e6e1-96da-4daa-9937-1160023a5252)

可以试试点一下红框框住的「锁定歌词」按钮
