### ISSUE TITLE
[Bug]: green解压路径包含特殊符号 # 或 % 时，软件启动后，自定义音源会卡在“初始化中”

### ISSUE THREAD

**Issue by crnkv** [lyswhut/lx-music-desktop#1997]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

1.软件正常启动
2.基本设置 > 音乐来源 > 六音音源 v1.1.0 或 v1.2.0 状态切换至“初始化成功”
3.搜索音乐双击播放

### 实际行为

1.软件能正常启动
2.基本设置 > 音乐来源 > 六音音源 v1.1.0 和 v1.2.0 状态卡在了“初始化中”阶段
3.搜索音乐双击后提示“source init failed”
经测试，至少确定了当路径里包含井号 # 或百分号 % 的时候（windows的合法路径符号），会出现这个问题，删掉特殊符号就正常了。
不清楚是否和 #1461 有关。
不清楚是洛雪的问题还是六音音源代码的问题，姑且先这里报告一下。

### Lx Music 版本

2.8.0

### 最后正常的版本

无

### 操作系统版本

Windows 10 版本 22H2

**Comment by lyswhut** [comment]
试试 2.9.0-beta.7

**Comment by crnkv** [comment]
确认 2.9.0-beta.7 修好了
