### ISSUE TITLE
[Bug]: LX Music会启用摄像头

### ISSUE THREAD

**Issue by Eternity070628** [lyswhut/lx-music-desktop#1999]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

每次开软件，火绒都会有启用摄像头的提示，不知是软件的问题还是火绒的问题

### 实际行为

-

### Lx Music 版本

2.9.0 beta6

### 操作系统版本

Windows 11 24H2 26257.5000

**Comment by weavers1f** [comment]
火绒好像现在很多软件都有这个提示，每次浏览器开一些网页的时候也会有这个提示不知道什么原因

**Comment by TealLymn** [comment]
#1978 #551
