### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by klm88069** [lyswhut/lx-music-desktop#2]
缓存是保存在哪里呢？可以修改吗？

**Comment by lyswhut** [comment]
软件不会缓存歌曲数据，
软件数据存储目录：`%HOMEPATH%\AppData\Roaming\lx-music-desktop`
软件更新文件下载目录：`%HOMEPATH%\AppData\Local\lx-music-desktop-updater`

目前这些目录暂不支持修改。
