### ISSUE TITLE
更新18.2後就不能下載flac和高品質如320kb的音樂檔了

### ISSUE THREAD

**Issue by leotim68** [lyswhut/lx-music-desktop#200]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by leotim68** [comment]
你好開發者.......首先很感謝你編寫這個程式.
小第發現更新18.2後就不能下載flac和高品質如320kb的音樂檔了.
不知是否程式的bug還是什麼呢,所以想問一下站長是小第的問題還是別的問題........
再三感謝你的開發........THANKS

**Comment by lyswhut** [comment]
问题重复：https://github.com/lyswhut/lx-music-desktop/issues/180
