### ISSUE TITLE
[Feature]: 快捷增减音量

### ISSUE THREAD

**Issue by mhzun** [lyswhut/lx-music-desktop#2000]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

可不可以添加一个功能：鼠标悬停在音量按钮上时可通过鼠标滚轮增减音量

### 描述你想要的解决方案

判断鼠标是否在音量按钮上，然后使用 scroll_event 监听鼠标滚轮，判断前滚增大音量后滚减小音量

**Comment by lyswhut** [comment]
已在 v2.9.0 新增
