### ISSUE TITLE
[Bug]: 克隆下来的项目无法启动

### ISSUE THREAD

**Issue by 2kailsy** [lyswhut/lx-music-desktop#2003]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

运行项目

### 实际行为

git clone项目后用vscode打开
cnpm i后运行npm run dev
electron的窗口可以出现同时也伴随着一大堆的errors
![image](https://github.com/user-attachments/assets/eeab8fd4-bf82-41df-bdf1-ac108e6c9c04)
![image](https://github.com/user-attachments/assets/50749c9c-2b47-492f-ab6c-e97cb7ad1bdb)
看上去都是@typescript-eslint这个的问题
我该怎么解决

### Lx Music 版本

2.8.0

### 操作系统版本

win10教育版 22H2

**Comment by 2kailsy** [comment]
cnpm i执行结果如下
![image](https://github.com/user-attachments/assets/15b58d4d-4321-4b1b-a92f-cdb3a1d33105)
![image](https://github.com/user-attachments/assets/416eb4cb-ea98-4724-96e3-259dc5275a20)
![image](https://github.com/user-attachments/assets/38cf2b88-92ea-4320-b573-b1b6a60e21f9)

**Comment by 2kailsy** [comment]
npm i运行结果如下
![image](https://github.com/user-attachments/assets/14d6d601-d9c7-4deb-acf7-2103d07f105e)

**Comment by 2kailsy** [comment]
![image](https://github.com/user-attachments/assets/318a7ee9-0fd2-4986-ad1b-032d0e39d105)
点击y右上角的×后项目正常运行

**Comment by lyswhut** [comment]
重新克隆代码，用npm安装

**Comment by 2kailsy** [comment]
![image](https://github.com/user-attachments/assets/00885a3f-0437-4e54-b4d7-d2feda80c07d)
![image](https://github.com/user-attachments/assets/16c54c62-10c2-4527-a3ba-50b55b7d2ee0)
本地有python
![image](https://github.com/user-attachments/assets/37f51afd-875d-446d-a485-32c819312210)

**Comment by 2kailsy** [comment]
![image](https://github.com/user-attachments/assets/af9fadb0-3d82-4b96-8dc9-5928e43387ff)
![image](https://github.com/user-attachments/assets/da7e9026-13a0-4e33-b162-e62e6469f203)

**Comment by lyswhut** [comment]
这是网络问题，配置代理或者使用electron的中国镜像，详情看electron安装文档
