### ISSUE TITLE
英文ui翻译，及加google 引擎的..

### ISSUE THREAD

**Issue by LJWxyz** [lyswhut/lx-music-desktop#201]
我想要帮，先在这问下如何有效的推这些功能。
~ps，我不会用electron。会Java及python。
~我想确认，结果只可以是“MP3，flac”？是的话，Google就不太可能了？

**Comment by lyswhut** [comment]
原谅我没看懂你想要表达什么。。。？
你是想参与软件的翻译吗？如果是的话：

翻译文件都放在`src\renderer\lang`文件夹下，每种语言都以一个文件夹分类，例如里面的`cns、en`等文件夹。
如果你觉得哪门语言的翻译不对，可以直接改对应语言文件夹里面的文件。
如果你想新增一门语言，那么可以以`cns`文件夹内的文件为模板复制一份，然后改成想要新增语言的简写名字，然后将里面的中文翻译成目标语言即可，最后还要编辑`src\renderer\lang\languages.json`，在里面按照`en`的格式新增对应数据即可。

**Comment by LJWxyz** [comment]
ok,了解。：）
