### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by WENMINGZHUFAN** [lyswhut/lx-music-desktop#2015]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望增加一个歌单内歌曲搜索功能，歌收多了有点难找，本地的就更难了

### 描述你想要的解决方案

分为全歌单搜索和歌单内搜索，可以方便播放收藏和本地歌曲

### 附加信息

感谢作者维护

**Comment by 2kailsy** [comment]
> ctrl+f可以搜索

但是只能是单个歌单搜索

**Comment by WENMINGZHUFAN** [comment]
> > ctrl+f可以搜索
> 
> 但是只能是单个歌单搜索

感谢，够用了

**Comment by Ceale** [comment]
如果问题已经解决可以把issue关掉
