### ISSUE TITLE
[Bug]: 设置里面为什么没有“音乐来源”这一功能

### ISSUE THREAD

**Issue by FUthrone** [lyswhut/lx-music-desktop#2019]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

无法导入音乐源

### 实际行为

无法导入音乐源

### Lx Music 版本

2.9

### 最后正常的版本

2.9

### 操作系统版本

win10

### 附加信息

![image](https://github.com/user-attachments/assets/ac49b76b-cfd4-413a-81ff-b97397760f2e)

**Comment by FUthrone** [comment]
已经解决；

**Comment by Ceale** [comment]
如果已经解决可以将issue关闭

**Comment by 248904407** [comment]
您好，我和你的情况是一样的，请问你是怎么解决的

**Comment by Ceale** [comment]
可在`设置 > 基本设置 > 音乐来源 > 自定义源管理`处添加/移除音乐源，添加后在`音乐来源`启用
