### ISSUE TITLE
给详情页加上滚轮，鼠标是真的麻烦

### ISSUE THREAD

**Issue by hyn-2020** [lyswhut/lx-music-desktop#202]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
鼠标滚轮一直都可用于滚动列表，没看懂你想表达什么

**Comment by hyn-2020** [comment]
> 鼠标滚轮一直都可用于滚动列表，没看懂你想表达什么

额，我说的是详情页，就是显示歌词的地方，现在好像只能用鼠标拖哦

**Comment by lyswhut** [comment]
已在v1.0.0新增该功能
