### ISSUE TITLE
为什么我只能下载普通音质了？

### ISSUE THREAD

**Issue by Sterling4869** [lyswhut/lx-music-desktop#203]
<img width="759" alt="微信截图_20200511232633" src="https://user-images.githubusercontent.com/65173186/81567622-e5c36780-93df-11ea-8892-609b412278ad.png">

**Comment by Aiden510** [comment]
对啊，我更新了最新版，也变成这样子了

**Comment by cy920820** [comment]
应该是接口限制了吧

**Comment by Sterling4869** [comment]
> 应该是接口限制了吧

那怎么解开限制呢..

**Comment by zleiwang** [comment]
只能在线听了

**Comment by loweets** [comment]
已经玩不了了，大家散了吧，除非作者开源全部代码，大家自己搭服务端

**Comment by lyswhut** [comment]
详情看：https://github.com/lyswhut/lx-music-desktop/issues/224

**Comment by lxtxlcr** [comment]
确实，为啥只能下载普通音质了？

**Comment by lxtxlcr** [comment]
确实，为啥v1.4.1版本只能下载普通音质？？
