### ISSUE TITLE
[Feature]: 希望能用单独下载歌词的功能

### ISSUE THREAD

**Issue by homerLL** [lyswhut/lx-music-desktop#2031]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我现在是企鹅直接下载的音乐，然后转换成flac格式，但是他下载的歌词不带翻译，用了下音乐标签，歌词翻译也有问题，翻译和原文同一行的，现在能用的翻译就只有洛雪这里下载的了，但是基本所有音源都做了下载限制，我想着我不下歌曲只下歌词行不？这样不封我ip了吧？

### 描述你想要的解决方案

1

**Comment by AyTsaoIce** [comment]
或许可以尝试下https://github.com/kafuumi/ltc，刚刚测试过，目前仍然能够使用。
还支持把lrc格式转换成ass字幕文件格式或srt字幕文件格式。
