### ISSUE TITLE
[Feature]: 请问我想把三个歌单合并成一个，有什么办法吗？

### ISSUE THREAD

**Issue by 123123-GitHub** [lyswhut/lx-music-desktop#2039]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

想把三个歌单合并成一个

### 描述你想要的解决方案

把三个歌单合并成一个

### 描述你考虑过的替代方案

出一个全选的功能，现在只能按住ctrl一个一个点

### 附加信息

或者把洛雪的歌单导出到第三方合并，再导回来

**Comment by xzhzhaowendao** [comment]
Ctrl+A试试呢
