### ISSUE TITLE
添加单独下载歌词的功能

### ISSUE THREAD

**Issue by gledos** [lyswhut/lx-music-desktop#205]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

lx-music 之前下载歌曲可以自动下载 lrc 格式歌词，但现在由于 Messoer 已关闭，网易云音乐以及大量的有歌词的歌曲都无法下载，因此歌词也无法下载。

所以我希望能够提供只下载歌词的单独功能

**Comment by lyswhut** [comment]
目前不计划添加单独下载歌词的功能
