### ISSUE TITLE
[Feature]: 搜索框英文语法错误

### ISSUE THREAD

**Issue by MMagine** [lyswhut/lx-music-desktop#2050]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![屏幕截图 2024-09-22 130611](https://github.com/user-attachments/assets/3aff20f1-a85e-4b36-80d0-be43b6dc4a5d)
“find” 本身就有 “找到” 的意思，后面直接跟宾语，不需要再加介词 “for”。

### 描述你想要的解决方案

改为 look for something

### 附加信息

（无聊的发现）

**Comment by xzhzhaowendao** [comment]
个人觉得，比起"Look for something."，改为"Search for something."更好

**Comment by xzhzhaowendao** [comment]
几个备选
1. What are you looking for?
2. Start your search!
3. Ready to explore?

**Comment by lyswhut** [comment]
改成 `Search for something` 了
