### ISSUE TITLE
添加试听列表内歌曲搜索功能

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#206]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
希望能在试听列表内添加**列表内歌曲搜索**功能

**Comment by lyswhut** [comment]
已在v1.0.0新增该功能，详情看更新日志
