### ISSUE TITLE
[Bug]: 音频输出为空

### ISSUE THREAD

**Issue by RaySun367** [lyswhut/lx-music-desktop#2062]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

音频输出

### 实际行为

就只有这个没有声音,其他都能正常播放声音,而且重新安装了声音驱动也不好使,卸载重新安装了软件也还是不行

### Lx Music 版本

2.8.0

### 操作系统版本

win11

**Comment by lyswhut** [comment]
卸载软件，安装时选“仅为我安装”，并将软件安装到到默认位置试试？
https://github.com/lyswhut/lx-music-desktop/issues/1928
