### ISSUE TITLE
添加选择的当前歌单或者搜索结果列表播放

### ISSUE THREAD

**Issue by Fcscanf** [lyswhut/lx-music-desktop#208]
一般在歌单或者搜索结果中播放一首后，然后又从试听音乐开始播放，希望能够直接在当前歌单进行顺序循环播放

**Comment by lyswhut** [comment]
不支持直接播放歌单中的歌曲，若想播放歌单中的全部歌曲，需要将当前歌单的所有歌曲添加到播放列表播放
