### ISSUE TITLE
mac 使用 cpu发热严重。

### ISSUE THREAD

**Issue by hanchongsky** [lyswhut/lx-music-desktop#21]

**Comment by lyswhut** [comment]
提供下系统版本、使用什么功能下发热严重，把软件最小化后是否还这样？

**Comment by hanchongsky** [comment]
10.14.6 (18G95) 对比了下比qq音乐温度高了7度左右。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyswhut"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月17日(星期二) 中午11:59
收件人:&nbsp;"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送:&nbsp;"韩冲"<503257261@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] mac 使用 cpu发热严重。 (#21)




提供下系统版本、使用什么功能下发热严重，把软件最小化后是否还这样？

**Comment by VINCENTCHEN94** [comment]
首先感谢 `lyswhut`大佬，发热大应该是最大化cpu占用过高导致（Mac上多个WindowServer的进程）亲测软件最小化cpu占用降低。

**Comment by lyswhut** [comment]
目前已经对播放功能做了些优化，下个版本更新后可以看下效果明不明显。

**Comment by lyswhut** [comment]
你们试下0.6.1版本看下有没有好一点

**Comment by VINCENTCHEN94** [comment]
好嘞

**Comment by lyswhut** [comment]
在`0.10.0`版本中修复了一个播放性能问题，你们更新试下，看下这个问题有没有修复！

**Comment by lyswhut** [comment]
@hanchongsky @VINCENTCHEN94 @xirenyi 麻烦测试下该问题是否已经解决！

**Comment by lyswhut** [comment]
经反馈该问题已在0.10.0修复
