### ISSUE TITLE
建议将mac版的退出和最小化button放在左上角

### ISSUE THREAD

**Issue by Jechin** [lyswhut/lx-music-desktop#210]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
建议将mac版的退出和最小化button放在左上角

**描述您考虑过的替代方案**
建议将mac版的退出和最小化button放在左上角

**其他内容**
建议将mac版的退出和最小化button放在左上角

**Comment by lyswhut** [comment]
已在v1.0.0新增该功能，详情看更新日志
