### ISSUE TITLE
添加：用户自定义某源

### ISSUE THREAD

**Issue by linux0ne-su** [lyswhut/lx-music-desktop#211]
https://www.hifini.com/

1、这个网站上的音乐很多，都是高品质的。
2、每下载一首需要一枚金币，这只是这个站的表象，运行方式而已
3、我觉得它真正的目的在于“收集”，它用各种包装方式收集了N多的歌曲
4、未来它肯定会用这些歌曲实现某种赢利目的，有可能是在知识产权保护的大范围下吧。

现在有两个建议：
1、咱们的软件可否将这个网站设置成一个可选的“源”
2、如果软件本身由于某种限制不便于做这个事的话，那么能不能开一个接口，并有一个教程，告诉用户怎么将某种音乐类网站的资源变成“源”来使用？

**Comment by lyswhut** [comment]
无法使用这种网站作为歌曲源，只有支持根据音乐平台对应的歌曲ID获取歌曲链接的源才能受软件支持。

用户自定义歌曲来源以后或许会添加，目前先暂时搁置

**Comment by lyswhut** [comment]
该功能已在v1.8.0中添加，源编写规则可以去常见问题查看
