### ISSUE TITLE
[Feature]: 希望能够批量修改列表中本地音乐对应的本地路径

### ISSUE THREAD

**Issue by Evsdrg** [lyswhut/lx-music-desktop#2112]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

音乐只存在于D盘一个文件夹中，软件中有两个音乐列表，1是本地音乐，2是从全部本地音乐中挑出来的一部分音乐，现因为一些原因导致D盘变成E盘，并且新的D盘空间不足以容纳整个存放音乐的文件夹，这就导致了两个音乐列表中的音乐均无法播放/需要联网播放。

### 描述你想要的解决方案

研究了一番并没有找到软件是在数据路径的哪里放着播放列表相关信息，备份出来的音乐列表文件lxmc也不知道如何解析，希望有什么方法能够修改本地音乐的路径，比如操作备份出来的音乐列表文件

### 描述你考虑过的替代方案

目前使用mklink创建了目录联结，从而使得软件访问D盘时候实际访问到E盘的音乐，但这样比较蛋疼，并且会显得文件目录很乱

**Comment by lyswhut** [comment]
可以将歌曲删除再添加
lxmc是一个gz文件，重命名为gz后解压是一个json文件，批量替换里面的路径也行，替换完了重命名到`.json`扩展名后导入

**Comment by Evsdrg** [comment]
> 可以将歌曲删除再添加 lxmc是一个gz文件，重命名为`.gz`后解压是一个json文件，批量替换里面的路径也行，替换完了重命名到`.json`扩展名后导入

这下懂了，删除再添加不太方便，对于列表1可以，但是列表2是从1中挑选出来的，删了再加非常麻烦，改路径这个操作就没问题了
