### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by timpulver** [lyswhut/lx-music-desktop#212]
Would be great if the player was localized, preferably in English.
When starting the player for the first time it could check the language of the operating system and use a specific translation file then.

**Comment by CPCer** [comment]
Actually, it was... Here's the instruction
![image](https://user-images.githubusercontent.com/8787958/83643430-963d1980-a5e2-11ea-8b8c-6f37606dfec9.png)

**Comment by timpulver** [comment]
Ah, thanks! This is good to know.
But people who cannot read Chinese will not find this setting.

I would propose that you check what operating system the user uses (see [How to get a user’s system language in Electron?](https://discuss.atom.io/t/how-to-get-a-users-system-language-in-electron/23095)). 

```
if user language is chinese
then set chinese as language
else set english
```

**Comment by lyswhut** [comment]
Although the application can set the language to English, the data source is still Chinese, and I cannot solve this problem at present.

**Comment by lyswhut** [comment]
Added in v1.0.0
