### ISSUE TITLE
[Feature]: 希望歌词支持从第一屏幕拖拽到第二屏幕

### ISSUE THREAD

**Issue by rento666** [lyswhut/lx-music-desktop#2122]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我使用的是Windows平台，目前连接了两块屏幕，我发现歌词无法拖动到第二个屏幕上。

### 描述你想要的解决方案

由于我不懂Electron开发，以下是AI关于如何开发此功能的解释：
------------------------------------------------------------------------------

Q：利用 electron开发音乐软件，如何让歌词可以拖拽到第二屏幕？

A：
## 理解 Electron 的窗口和屏幕相关概念
- Electron 应用是基于 Chromium 和 Node.js 构建的。在 Electron 中，BrowserWindow是用于创建应用窗口的主要模块。要实现歌词拖到第二屏幕，首先需要了解如何获取和操作多个屏幕。
- 可以使用`electron.screen`模块来获取有关屏幕的信息。例如，`electron.screen.getAllDisplays()`方法可以返回一个包含所有可用屏幕信息的数组，每个元素包含屏幕的尺寸（bounds属性）、缩放因子等信息。
## 创建可拖动的歌词组件
- 在 HTML 部分，为歌词创建一个独立的 DOM 元素，例如一个<div>标签，并设置其样式为可拖动。可以使用 CSS 的`position: absolute;`样式，这样就可以通过改变元素的`left`和`right`属性来移动它。
- 在 JavaScript 部分（通常是在 Electron 的渲染进程中），可以使用 HTML5 的拖放 API 来实现拖动功能。首先，需要为歌词元素设置draggable = "true"属性。然后，为dragstart事件添加一个监听器，在这个监听器中，可以设置要拖动的数据，例如歌词的文本内容或者相关的标识符。
- 示例代码如下：
```html
<div id="lyricsDiv" draggable="true" style="position: absolute; top: 100px; left: 100px; width: 200px; height: 200px; background - color: #f0f0f0;">
    <p>这是歌词内容</p>
</div>
```
```js
const lyricsDiv = document.getElementById('lyricsDiv');
lyricsDiv.addEventListener('dragstart', (e) => {
    e.dataTransfer.setData('text/plain', 'lyricsData');
});
```
## 检测第二屏幕并移动歌词组件到第二屏幕
- 当开始拖动歌词组件时，在dragstart事件的处理函数中，可以获取所有的屏幕信息。使用electron.screen.getAllDisplays()来获取屏幕数组。
- 确定第二屏幕的位置和尺寸。通常，第一个屏幕的索引是 0，第二屏幕的索引是 1（如果存在的话）。可以通过访问屏幕数组元素的bounds属性来获取屏幕的位置和尺寸信息。
- 当拖放事件结束（drop事件）时，将歌词组件的位置设置到第二屏幕的合适位置。可以通过修改歌词组件的style.left和style.top属性来实现。需要注意的是，位置的计算要考虑到屏幕的坐标系统和歌词组件本身的大小。
- 以下是一个简单的示例代码片段（假设这是在 Electron 的渲染进程中）：
```js
const { screen } = require('electron');
lyricsDiv.addEventListener('drop', (e) => {
    const displays = screen.getAllDisplays();
    if (displays.length > 1) {
        const secondScreen = displays[1].bounds;
        lyricsDiv.style.left = secondScreen.x + 50 + 'px';
        lyricsDiv.style.top = secondScreen.y + 50 + 'px';
    }
});
```
- 同时，不要忘记在dragover事件中阻止默认行为，以允许拖放操作在目标区域（第二屏幕）生效：
```js
document.addEventListener('dragover', (e) => {
    e.preventDefault();
});
```
在实际开发中，还需要考虑到窗口的缩放、歌词组件的样式调整以及不同操作系统和屏幕配置的兼容性等问题，可能需要进一步优化和完善代码。

**Comment by Landidi666** [comment]
如果你看过软件设置，你会发现在 **桌面歌词设置** 中有个选项叫 **不允许歌词窗口拖出主屏幕之外**
