### ISSUE TITLE
[Feature]: 可以在快播放完的时候提前加载url

### ISSUE THREAD

**Issue by IZRINO** [lyswhut/lx-music-desktop#2126]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![Snipaste_2024-11-22_16-52-15](https://github.com/user-attachments/assets/af8c7244-c9e3-45b2-a14b-e7983ea95f01)
![Snipaste_2024-11-22_16-52-31](https://github.com/user-attachments/assets/106c0e7e-4b1a-42f7-ac5d-eb8dda9d23ff)
如图，每次加载url会停一下

### 描述你想要的解决方案

我想在当前播放的歌快结束时提前加载url，这样不会停一下优化体验。

**Comment by lyswhut** [comment]
在歌曲即将 **正常** 播放结束时将预获取下一首歌曲的播放链接，减少自动切歌时的等待时间
可以试试最新beta版：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by IZRINO** [comment]
好的
