### ISSUE TITLE
打开网易云音乐歌单时无法加载歌单内全部歌曲

### ISSUE THREAD

**Issue by kdufv** [lyswhut/lx-music-desktop#214]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)
网易云音乐已经无法查看歌单中的全部歌曲了，建议支持从本地文本导入歌单，格式例如：你还要我怎样 - 薛之谦

**Comment by lyswhut** [comment]
网易云歌单、排行榜无法加载所有歌曲是其接口的问题，下个版本修复

本地文件导入以后再说

**Comment by lyswhut** [comment]
已在v1.0.0修复
