### ISSUE TITLE
[Bug]: Process name in Task Manager

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#2147]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

Displayes as *LX Music* or similar — the name of the software itself.

### 实际行为

Displayed as a long and inappropriate "description" —

`一个免费的音乐查找助手`

### Lx Music 版本

2.10.0-beta.7

### 操作系统版本

Windows 11, version 24H2

### 附加信息

![process-name-in-task-manager](https://github.com/user-attachments/assets/a72d62b0-4f7f-4df5-b642-312542fe642f)

**Comment by lyswhut** [comment]
Related to https://github.com/electron-userland/electron-builder/issues/8599

**Comment by lyswhut** [comment]
Try the latest beta: https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml
