### ISSUE TITLE
Migrate tray icon menu text i18n to `src\lang`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#2157]
All translations related to the tray icon menu text are now in the `src\main\modules\tray.ts` file. Is it possible to integrate with the language files within `src\lang`.

*Sorry for not using a template, but I think the description above is clear and concise enough.*

**Comment by lyswhut** [comment]
Currently only the renderer process supports i18n, and the main process does not have i18n integrated.
Currently tray's i18n is just a simple solution, so I don't plan to migrate it
