### ISSUE TITLE
请问如何导出音源

### ISSUE THREAD

**Issue by rdcyuxi** [lyswhut/lx-music-desktop#2165]
有个很好的音源，不记得在哪里下载的了，换了新电脑想导入这个音源，请问在老电脑上如何导出？

**Comment by lyswhut** [comment]
去数据存储（看常见问题）目录，把 `LxDatas` 中除了 `sync` 以外的内容复制到新电脑就行了

**Comment by rdcyuxi** [comment]
好的，谢谢大佬，看到了，在user_api.json

**Comment by manzuiquanshijiaya** [comment]
> 有个很好的音源，不记得在哪里下载的了，换了新电脑想导入这个音源，请问在老电脑上如何导出？

导出来了吗  导出来了把你的好音源分享一下

**Comment by wheelhorse** [comment]
Check the path in Linux as below:
~/.config/lx-music-desktop/LxDatas
