### ISSUE TITLE
希望添加排行榜全选顺序播放功能

### ISSUE THREAD

**Issue by dovsay** [lyswhut/lx-music-desktop#217]
旧版本排行榜歌曲前有多选框，全选点播放就可以了
取消了多选框，用ctrl 和shift实现不了啊

**Comment by dovsay** [comment]
感觉多选框更符合用户使用习惯，建议

**Comment by lyswhut** [comment]
现在的版本你`Ctrl+a`全选后，右下角的悬浮按钮播放也是一样的

**Comment by itsleehon** [comment]
我也有层主的这个疑惑，看了上面作者的话，还困惑了挺长时间真没想起来这个操作。好吧，可以用但不够直观

**Comment by dangfei1024** [comment]
Ctrl+a全选后，右下角的悬浮按钮播放也是没按顺序播放吧 也是随机的

**Comment by lyswhut** [comment]
播放在线列表内的歌曲需要将它们都添加到我的列表才能播放，你可以全选列表内的歌曲然后添加到现有列表或者新创建的列表，然后去播放改列表内的歌曲。
