### ISSUE TITLE
[Bug]: An error occurs when creating an empty list after opening the app for the first time and removing it

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#2175]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

No errors will occur when operating as described in the title

### 实际行为

1. Open a clean instance (`npm run dev` or delete the old data and reinstall it)
2. Create a list in *Your Library* (我的列表) with any name you want
3. Right-click on this list and select *Remove*
4. Confirm removing it

### Lx Music 版本

2.9.0/2.10.0-beta.9

### 操作系统版本

Windows 11, version 24H2

### 附加信息

This is very distressing for me being in development mode — I wonder if it's a bug from my previous PRs.

*v2.9.0 also has this problem.*
*The following prompt will not appear in the production environment, but will be logged in the developer tools console.*

![lx-music-desktop-remove-empty-list-error](https://github.com/user-attachments/assets/2e36a27b-fce0-48c8-82aa-dfae397ac5f3)

**Comment by 14Kay** [comment]
It's not your problem. It is a bug

**Comment by lyswhut** [comment]
fixed: https://github.com/lyswhut/lx-music-desktop/pull/2178
