### ISSUE TITLE
优化主题背景功能

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#218]
**解决方案检查**

-  [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
-  [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
月里嫦娥 主题背景替换时，希望将右边的歌曲列表的背景也替换掉，像木叶之村或新年快乐背景主题一样，同时字体颜色也改为白色，播放的歌曲为灰色
如果可以，希望能实现自定义背景图片和字体颜色

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
尝试增加过该主题的透明度，发现并不那么好看，还是维持原样吧
