### ISSUE TITLE
[Bug]: Preset theme options English name is partially hidden due to excessive length

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#2183]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

It is hoped that a more aesthetically pleasing way of showing their English names fully without requiring the user to mouse over the item to view it.

### 实际行为

A portion of the item name is shown as an ellipsis.

### Lx Music 版本

2.10.0-beta.9

### 操作系统版本

Windows 11, version 24H2

### 附加信息

![lx-music-desktop-theme-item-name](https://github.com/user-attachments/assets/806e5593-1102-4ad7-9a06-5e952197d051)

**Comment by lyswhut** [comment]
What suggestions do you have?

**Comment by lyswhut** [comment]
"100px" spacing is too large.
I'd be inclined to remove `.mixin-ellipsis-1;`
