### ISSUE TITLE
明明选择下载ape无损音乐，得到的却是只有几兆的.ape文件

### ISSUE THREAD

**Issue by nokia790** [lyswhut/lx-music-desktop#22]
Mac 10.13.6版本系统

软件也是用最新版的0.5.5版

但是每次选择ape格式时，下载到的都是只有几兆的.ape文件，用播放器播放，实际的码率就是128kps的mp3编码。。。只是挂了个.ape的后缀名

**Comment by lyswhut** [comment]
当歌曲没有ape音质时，就会返回128k的音质，而软件误以为该音质就是ape，所以把它命名为ape格式

这是接口作者搞的机制，。。。想要避免该情况的话，无损的话推荐下载flac格式
