### ISSUE TITLE
DeepinV20 安装lx-music-desktop.v0.18.2.x64.deb 失败

### ISSUE THREAD

**Issue by HappyHuYun** [lyswhut/lx-music-desktop#220]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
DeepinV20 安装lx-music-desktop.v0.18.2.x64.deb 失败！
因为是小白不知道怎么解决！

安装失败后详情如下，之前用DeepinV15成功使用！

Selecting previously unselected package lx-music-desktop.
(Reading database ... 208863 files and directories currently installed.)
Preparing to unpack .../lx-music-desktop.v0.18.2.x64.deb ...
Unpacking lx-music-desktop (0.18.2-90) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for lastore-daemon (5.0.6-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for bamfdaemon (0.5.4-1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.62) ...
An error occurred while applying changes: dpkg: dependency problems prevent configuration of lx-music-desktop:
 lx-music-desktop depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package lx-music-desktop (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 lx-music-desktop

**Comment by lyswhut** [comment]
> Package libappindicator3-1 is not installed.

自己尝试Google这个错误
