### ISSUE TITLE
[Bug]: Some of the sorting tags at the top of the playlist page are hardcoded

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-desktop#2202]
Is it possible to implement translations of this?

I noticed that the mobile edition has associated i18n keys, but forgot if they were used.

![1](https://github.com/user-attachments/assets/51cb91af-8419-401a-9a52-3e574111a493)

**Comment by lyswhut** [comment]
Since the online resources come from Chinese music platforms, it is impossible to i18n all the content.
This comes from the name of the online music platform, so let's keep it as it is.
