### ISSUE TITLE
添加一个设置音量的功能

### ISSUE THREAD

**Issue by zj8331182** [lyswhut/lx-music-desktop#221]
主流的播放器基本都有这个功能，就是可以单独设置播放器的音量，有的时候边听歌边收微信语音消息的时候这个音量还得来回调挺费劲

**Comment by lyswhut** [comment]
下一首按钮左侧的横条就是

**Comment by zj8331182** [comment]
啊，好吧，看到了，那加一个音量的小图标吧，现在这个太不容易发现了
