### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by qiang-edmodo** [lyswhut/lx-music-desktop#222]
![image](https://user-images.githubusercontent.com/54658586/83856635-73c70f80-a74c-11ea-9f3c-a5d92a3a3c0c.png)
请教一下这种标签是UI库吗？如果是的话，在哪里引入的？

**Comment by lyswhut** [comment]
这些是 `src\renderer\components` 下的组件，在`src\renderer\main.js`以全局的方式导入
