### ISSUE TITLE
是否可以增加iOS App 越狱版本，可提供技术支持

### ISSUE THREAD

**Issue by zhenguanqing** [lyswhut/lx-music-desktop#223]
是否可以增加iOS App越狱版本，可提供技术支持，wx：zhenguanqing

**Comment by lm2343635** [comment]
也可以通过其他方式分发，比如这个
https://altstore.io

**Comment by lm2343635** [comment]
@zhenguanqing 
我这两天也想搞这个，想移植到iPad用，一起搞？
加个微信啊，id就是github的id

**Comment by lyswhut** [comment]
MAC版可以运行在移动端上？

**Comment by lm2343635** [comment]
iOS套个浏览器的壳，可行性是有的

**Comment by lyswhut** [comment]
软件依赖Node.js的http请求、文件写入等功能，不是只靠浏览器就能运行的

**Comment by lm2343635** [comment]
能否把这些放到真实的服务器中，让iOS依赖于服务器运行，或者iOS应用内部启动一个node服务器

**Comment by lyswhut** [comment]
nodejs的功能是在本地调用的，这个项目的代码并不能在移动端上使用，需要创建一个新项目重现开发，关于移动端的更多信息看：https://github.com/lyswhut/lx-music-desktop/issues?q=%E7%A7%BB%E5%8A%A8%E7%AB%AF

**Comment by lilin87788** [comment]
ios 不需要分发的，这个项目面向程序员，我们ios程序员自己给自己分发就足够了，也避免一些法律问题。
