### ISSUE TITLE
建议添加到brew cask里面

### ISSUE THREAD

**Issue by li1191863273** [lyswhut/lx-music-desktop#224]
建议添加到brew cask里面

**Comment by lyswhut** [comment]
我没有用MAC，我不计划去做这件事，但如果你有兴趣的话可以提交PR帮忙完成

**Comment by ncihnegn** [comment]
You can use my tap
```brew tap ncihnegn/formulae && brew cask install lx-music-desktop```

**Comment by li1191863273** [comment]
Thank you

**Comment by magicdawn** [comment]
$ brew tap ncihnegn/formulae && brew cask install lx-music-desktop
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.

$ brew tap ncihnegn/formulae && brew install --cask lx-music-desktop
Error: Cask 'lx-music-desktop' is unavailable: No Cask with this name exists.
