### ISSUE TITLE
无损下载功能失效

### ISSUE THREAD

**Issue by Moelty** [lyswhut/lx-music-desktop#226]
收集癖的哀嚎，无损下载怎么没了...
![image](https://user-images.githubusercontent.com/44794550/84221592-3b3a8380-ab08-11ea-9c34-776499194e76.png)

**Comment by zhengguoxin** [comment]
我还以为只有我这样，是不是要交费了

**Comment by lyswhut** [comment]
看：https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-615234265
