### ISSUE TITLE
可否丰富歌单内容，以及多选，全选，全部播放功能

### ISSUE THREAD

**Issue by abyssdaisy** [lyswhut/lx-music-desktop#228]
= =老铁，感觉歌单里面歌都挺老的，能弄点网易云歌单进来不
以及添加多选，全选，全部播放功能

**Comment by lyswhut** [comment]
歌单列表是跟随官方动态更新的，
多选、全选看：https://github.com/lyswhut/lx-music-desktop/issues/194
