### ISSUE TITLE
音乐怎样下载 普通音质 以外的

### ISSUE THREAD

**Issue by kitkw** [lyswhut/lx-music-desktop#232]
全部音乐都只能下载 普通音质

**Comment by Clannad-AfterStory** [comment]
应该是收到pandownload事件影响，怕被抓，只能提供普通音质了╮(￣▽￣")╭

**Comment by effzmt** [comment]
下不了，很久以前就是这样的了

**Comment by kitkw** [comment]
这样子哦！！很久没用不清楚情况，以为软件问题。

**Comment by lyswhut** [comment]
重复：<https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-615234265>
