### ISSUE TITLE
打开软件后无法显示。

### ISSUE THREAD

**Issue by iamshaguar** [lyswhut/lx-music-desktop#234]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
同样的版本，2台电脑可以正常试用，剩余的几台都是正常安装后运行无法显示软件。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
希望可以给个方法。
**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
 WIN7 64

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
自行阅读常见问题解决 <https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>
