### ISSUE TITLE
搜索内容，是否可以批量添加到，试听列表呢

### ISSUE THREAD

**Issue by lei375809291** [lyswhut/lx-music-desktop#236]
rt

**Comment by pingsui** [comment]
+1，此需求非常有用，每次都需要点很多次才能加入试听列表

**Comment by jeffxjh** [comment]
+1 非常需要啊

**Comment by wjf-richard** [comment]
+1

**Comment by xiaojia90s** [comment]
看了几个人的issue，可以全选，ctrl + a，还没试别的功能

**Comment by lyswhut** [comment]
多选问题看常见问题列表多选部分：<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>
