### ISSUE TITLE
基于此项目实现的android项目

### ISSUE THREAD

**Issue by Mockingbird1234** [lyswhut/lx-music-desktop#237]
首先感谢作者开发了此音乐助手软件，由于本人目前正在学习flutter，并基于maccms开发了一款影视播放app（skapp），在使用本软件的时候发现可以把音乐集成进skapp，所以我做了此工作。
skapp可以实现从影视播放到音乐助手之间的无缝切换，源码地址：https://gitee.com/Mockingbirdcc/skapp

**Comment by lyswhut** [comment]
怎么集成？没看明白你想要干什么

**Comment by Mockingbird1234** [comment]
我是把lx-music-desktop的部分源码整成了接口，然后集成进了skapp里，感兴趣的话可以看下源码或者安装到手机体验一下。这个是项目的github地址：https://github.com/Mockingbird1234/skapp。
