### ISSUE TITLE
添加歌单播放功能

### ISSUE THREAD

**Issue by zc1249274251** [lyswhut/lx-music-desktop#238]
可能是网易云用习惯了  ，找个歌单 但是进去发现不能播放 而且也没有播放歌单里边歌曲的入口  感觉蛮奇怪的

**Comment by 448520270** [comment]
+1 希望歌单可以自动播放下去和网易云一样

**Comment by whsdaks** [comment]
+1

**Comment by storyInAugest** [comment]
+1 找到歌单，发现没有播放全部，这就难受了

**Comment by mengnan254** [comment]
+1，难受的不要不要的。

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/239
