### ISSUE TITLE
添加播放全部歌曲功能

### ISSUE THREAD

**Issue by 986244073** [lyswhut/lx-music-desktop#239]
添加播放全部歌曲功能

**Comment by xiaojia90s** [comment]
ctrl +a 右下角加

**Comment by lyswhut** [comment]
播放在线列表内的歌曲需要将它们都添加到我的列表才能播放，你可以全选列表内的歌曲然后添加到现有列表或者新创建的列表，然后去播放改列表内的歌曲。
列表多选问题看常见问题列表多选部分：<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>

**Comment by lyswhut** [comment]
以后或许会添加。
