### ISSUE TITLE
已经无法播放和下载，请排查

### ISSUE THREAD

**Issue by cdwmhcc** [lyswhut/lx-music-desktop#24]
看一下怎么回事儿，加油！

**Comment by lyswhut** [comment]
详情看：https://github.com/lyswhut/lx-music-desktop/issues/5
音乐无法播放的问题我会在这个issue更新。

**Comment by user12dd** [comment]
为什么我的落雪听不了

**Comment by Usernamegmy** [comment]
换源失败是怎吗回事

**Comment by lsbyyz** [comment]
我的换源失败，一首歌也听不了。打开我的音乐来源发现是这样的。我需要怎么做呢？
![Uploading 47adc976ad0f1b2173323887a03c89b.png…]()

**Comment by lsbyyz** [comment]
我的换源失败，一首歌也听不了。打开我的音乐来源发现是这样的。我需要怎么做呢？
![47adc976ad0f1b2173323887a03c89b](https://github.com/lyswhut/lx-music-desktop/assets/160328173/e42542a7-ed74-4293-add7-66f34f6f6121)

**Comment by lsbyyz** [comment]
我的换源失败，无法听歌和下载。打开音乐来源是这样的，我需要怎么做呢？
![47adc976ad0f1b2173323887a03c89b](https://github.com/lyswhut/lx-music-desktop/assets/160328173/f57e60cd-64f6-4edd-bfbf-55983f579d3b)

**Comment by lsbyyz** [comment]
![Uploading 47adc976ad0f1b2173323887a03c89b.png…]()
