### ISSUE TITLE
能否加一些类似于频谱的东西

### ISSUE THREAD

**Issue by trifolium-wang** [lyswhut/lx-music-desktop#241]
因为很多人听音乐非常喜欢看频谱跳动的感觉，我在mac软件上找了好久都找不到有频谱的播放器，好不容易找到一个，还是各种广告满天飞，并且质量很差，希望能在mac上加上频谱，或者全屏频谱的动态效果，或者支持新版的MacOs tarch bar上显示频谱，应该是非常好的，因为这些市面上没有。

**Comment by kiko-love** [comment]
我也觉得，不过频谱需要用bass实现，还要实现绘图的算法，这样工作量可能就会很大了，不知道作者愿不愿意搞了

**Comment by xudong1113** [comment]
不过我看到网上很多用js和html做的频谱效果还是相当不错的。

**Comment by maixiaojie** [comment]
audio API 结合 canvas 可以做出效果不错的

**Comment by lyswhut** [comment]
这需要用到高级web音频API，当前的代码未对这些API进行封装，如果要加入频谱，需要重写软件的播放功能，将其用高级web音频API代替，
但我目前没有打算去研究这些API并对其封装，这个以后再说
