### ISSUE TITLE
请添加 歌单可收藏，歌单、排行榜的歌可全选全部播放

### ISSUE THREAD

**Issue by leolee818** [lyswhut/lx-music-desktop#245]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
1、请添加 歌单可收藏，收藏列表不知道是不是这个功能，没找到怎么收藏列表。
2、歌单、排行榜的歌有个按钮全部播放（默认全选）。

**Comment by 1990chs** [comment]
附议！！！！

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/239
