### ISSUE TITLE
添加打开专辑的功能

### ISSUE THREAD

**Issue by peetteerr** [lyswhut/lx-music-desktop#246]
- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

----
- 希望搜索后，可以点击列表中某一首歌所在专辑，从而进一步打开该专辑，显示该专辑下的所有歌曲。
- 对于歌手，希望也可以点开显示该歌手下的所有歌曲。

**Comment by lyswhut** [comment]
专辑搜索暂不打算添加，以后看情况
