### ISSUE TITLE
优化随机播放功能

### ISSUE THREAD

**Issue by bashang03** [lyswhut/lx-music-desktop#249]
目前的歌曲随机功能感觉是完全随机？经常听到好几首之前刚听过的歌曲在随机模式下再次重复播放
希望能够优化一下算法，将已经播放过的歌曲t出随机范围

希望将歌曲切换功能添加到控制器（音量、下一首、暂停）界面，虽然看到之前有人提出来过被否了，但是确实在设置界面调整很麻烦，希望作者能够重新考虑一下，麻烦了

**Comment by lyswhut** [comment]
音量、歌曲切换的UI没想好怎么设计，暂不打算改进，
随机播放功能确实需要优化

**Comment by lyswhut** [comment]
已在v1.1.0做了优化
