### ISSUE TITLE
建议更新内容

### ISSUE THREAD

**Issue by Sml-del** [lyswhut/lx-music-desktop#25]
产品真的很棒，不过手头有点紧，没办法打赏作者，其实我也是学编程的，但是以现在的水平还是没法弄一个属于自己的应用程序，还希望产品再稍微改善，那个歌词啥的单独占一个页面，不用打开页面在任务栏就可以暂停音乐，我的音乐里多个收藏或者我喜欢的可以随时收藏，创建属于自己的歌单，可以播放全部，还有一个复选框点到下一页的时候添加音乐不要消失，抱歉我的不知好歹，希望作者能开发出十全十美的专属音乐软件

**Comment by lyswhut** [comment]
个人不推荐使用本软件作为常用播放器使用，本软件是为了查找歌曲，
可以用其他播放器播放

由于洛雪音乐的最初定位不是作为播放器开发的，只是为了用它来找歌。
这些功能以后可能会做，但目前暂时没有马上开发的计划。

**Comment by Sml-del** [comment]
嗯，期待，我现在还是经常用它来听音乐的




------------------ 原始邮件 ------------------
发件人: "lyswhut"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 中午12:50
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com>; 
抄送: "為妳唱情歌&#xF48B;"<1956017922@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lyswhut/lx-music-desktop] 建议更新内容 (#25)




个人不推荐使用本软件作为常用播放器使用，本软件是为了查找歌曲，
 可以用其他播放器播放
 
由于洛雪音乐的最初定位不是作为播放器开发的，只是为了用它来找歌。
 这些功能以后可能会做，但目前暂时没有马上开发的计划。

**Comment by cdwmhcc** [comment]
你也知道你不知好歹😊😄
