### ISSUE TITLE
网易云音乐都只能下载128k的，但实际上平台本身可以。

### ISSUE THREAD

**Issue by Aether1003** [lyswhut/lx-music-desktop#252]
网易云很多都可以flac格式，而洛雪的网易云歌曲均只可以下载128k的，但是在歌曲后方标明了无损，只是下载却只能下载128k。

稍微高品一点的音质下载都会显示“请求异常”。

**Comment by nkxingxh** [comment]
现在都更新了检测机制

**Comment by lyswhut** [comment]
接口限制，不支持播放/下载128k以外音质的歌曲
