### ISSUE TITLE
优化桌面歌词功能

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#254]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

桌面歌词在改变大小后，移动到任务栏过程中，上下左右边界自动增大

**其他内容**
![image](https://user-images.githubusercontent.com/63327558/88446962-1bb1ad00-ce61-11ea-9f10-329dceb70351.png)

**Comment by lyswhut** [comment]
不打算自动改变窗口大小，你自己调整窗口大小即可

**Comment by Dynamith** [comment]
@lyswhut 说法有些问题吧，这应该是个bug

**Comment by q54528** [comment]
@Dynamith 慢慢来吧，循序渐进

**Comment by Dynamith** [comment]
👌

**Comment by lyswhut** [comment]
这已在v1.0.1修复
