### ISSUE TITLE
优化自定义背景

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#256]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
自定义背景图片，和歌单歌曲的字体颜色

**其他内容**
![image](https://user-images.githubusercontent.com/63327558/88447395-5b7a9380-ce65-11ea-924b-374c03aece7d.png)
背景图
[https://www.photophoto.cn/pic/23116263.html](url)

**Comment by lyswhut** [comment]
遗憾的是，目前软件的主题架构不支持自定义字体颜色，软件内置的主题是编译代码时生成的，无法做到由用户自定义软件内的主题色
