### ISSUE TITLE
优化歌单列表搜索

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#257]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

列表搜索 英文名歌曲时没搜索到歌曲或搜索到的歌曲卡在中间很不明显
同时中文名歌曲搜索时，完全匹配的在最后面，建议放在最前面

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。
![image](https://user-images.githubusercontent.com/63327558/88447605-9b427a80-ce67-11ea-9cca-1ac9fa95515a.png)
![image](https://user-images.githubusercontent.com/63327558/88447615-b44b2b80-ce67-11ea-977e-27b4069a6f04.png)

**Comment by lyswhut** [comment]
下个版本进行下排序处理

**Comment by lyswhut** [comment]
已在v1.0.1新增该功能

**Comment by 465515119** [comment]
> 已在v1.0.1新增该功能

![image](https://user-images.githubusercontent.com/63327558/88459796-864b0300-ceca-11ea-8034-c8531e6cf331.png)
![image](https://user-images.githubusercontent.com/63327558/88459834-b85c6500-ceca-11ea-9bfb-01bb0e2bbde0.png)

这种类型 “英文名(中文) ”的歌是没有办法匹配检索吗，想是被过滤了

**Comment by lyswhut** [comment]
搜索内容尽量详细，搜索顺序按： 歌名 歌手 专辑 搜索，已经做了排序了，自己多试几次看怎么用好用，我不打算再优化了，如果想继续优化的话请提PR
