### ISSUE TITLE
导入其他电脑的设置后音频输出选项问题

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#259]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
导入其他电脑设置后音频输出出现多余选项
同时导入之后 播放歌曲时出现杂音或断音

**重现**
重现行为的步骤：
1.转到“设置-备份和恢复-所有数据“
2.点击“导出”
3.之后在另一台不同win10系统电脑上导入
4.看到错误

**截图**
![image](https://user-images.githubusercontent.com/63327558/88460321-fc049e00-cecd-11ea-9967-c2cf78e0c513.png)
![image](https://user-images.githubusercontent.com/63327558/88460378-687f9d00-cece-11ea-8c32-8db7cbb0fc65.png)

**环境：**
 电脑环境 
Windows 10 64位 1903 （详细的不记得了）
Windows 10 64位 1511 10586.104
  安装包 lx-music-desktop v1.0.1 x86_64 win_安装版

**Comment by lyswhut** [comment]
这不是多余选项，这些是你的电脑内的音频输出设备

**Comment by 465515119** [comment]
> 这不是多余选项，这些是你的电脑内的音频输出设备
额，我电脑中的输出设备中只有截图的那两个
设备管理器里面也只有这3个
![image](https://user-images.githubusercontent.com/63327558/88461584-60782b00-ced7-11ea-93ce-f43c9051af62.png)

**Comment by lyswhut** [comment]
这是正常的，你导入设置之前也会是这样，备份的设置仅是备份了你设置的设备id，如果在其他电脑上没有发现该id对应的设备，将重置为第一个默认值
