### ISSUE TITLE
歌曲下载Bug

### ISSUE THREAD

**Issue by Biteagle09** [lyswhut/lx-music-desktop#26]
在V0.6.0版本中，下载歌曲时进度条飙到200%以上，仍没有要停止的样子，但实际在磁盘里已可以正常打开播放和剪切粘贴

**Comment by lyswhut** [comment]
这种情况下最好把文件及下载记录删除，重新添加下载。
批量下载时某些情况下会出现该问题，应该是第三方下载库的问题，我已经在着手搞一个下载库了。。。

**Comment by Biteagle09** [comment]
好的

**Comment by Yu-Handsome** [comment]
有其他的下载方法吗？？这个链接下载很慢很慢

**Comment by lyswhut** [comment]
@Yu-Handsome 你是指歌曲下载慢吗？下载慢应该是你那边的网络问题

**Comment by Yu-Handsome** [comment]
不是，是下载这个软件的时候，很慢

**Comment by Yu-Handsome** [comment]
> @Yu-帅哥你是指歌曲下载慢吗？下载慢应该是你那边的网络问题

不是，是下载这个软件的时候，很慢

**Comment by lyswhut** [comment]
@Yu-Handsome 可到网盘下载，网盘下载速度快

**Comment by Yu-Handsome** [comment]
> @Yu-帅哥可到网盘下载，网盘下载速度快

哦哦，好的，谢谢啦帅哥

**Comment by lyswhut** [comment]
该问题已在0.12.0做了处理，对于之前遇到该问题的用户可以看下从0.12.0开始还会不会遇到这个问题

**Comment by lyswhut** [comment]
经过一周的使用时间，我没有收到下载问题的反馈，现在先关闭本issue，若后面有相关问题可再打开。
