### ISSUE TITLE
mac版本歌词显示bug

### ISSUE THREAD

**Issue by bjythub** [lyswhut/lx-music-desktop#261]
### 大佬，mac版本歌词显示有bug
截图：
![iShot2020-07-2610 30 28](https://user-images.githubusercontent.com/66855731/88470104-0dc85e80-cf2b-11ea-9271-c97bd4173537.png)
![iShot2020-07-2610 31 11](https://user-images.githubusercontent.com/66855731/88470112-2769a600-cf2b-11ea-979c-bf59392c78a0.png)

**Comment by lyswhut** [comment]
看常见问题 **桌面歌词** 部分：<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>

**Comment by yuanmingchen** [comment]
我的也这样，我一开始还以为是做的特效。。。。后面越看越不对劲
