### ISSUE TITLE
列表音乐无法在软件界面上直接播放

### ISSUE THREAD

**Issue by qdeduos** [lyswhut/lx-music-desktop#264]
系统环境：debian9
桌面环境：fluxbox

在软件中点出来的各种排行榜或者搜索结果，win版可以正常播放，但是到debian版中就放不了，连缓冲数据都没有。点击每首音乐后面的小耳机按钮也是同样没有反应。
但是点下载可以正常下载。

另，任务托盘图标右键菜单中只有一个“络雪音乐助手”选项，没有退出选项。想要结束进程需要
pkill lx-music-deskto 
注意不是pkill lx-music-desktop

**Comment by lyswhut** [comment]
由于软件只有我一个人在维护，时间与精力有限，Linux其他版本、桌面的兼容问题目前不打算去解决，抱歉
