### ISSUE TITLE
希望添加专辑搜索功能和文件夹分类功能

### ISSUE THREAD

**Issue by q310550690** [lyswhut/lx-music-desktop#265]
1.希望可以在歌曲列表页面右键搜索整张专辑功能
2.希望可以在下载里新增按文件夹分类 歌手\专辑（类似网易云里的文件只能分类）

**Comment by lyswhut** [comment]
1、软件没有搜索专辑的功能，而且目前没有打算添加：https://github.com/lyswhut/lx-music-desktop/issues/246
2、重复：https://github.com/lyswhut/lx-music-desktop/issues/258
