### ISSUE TITLE
对听歌的部分有点小疑惑

### ISSUE THREAD

**Issue by zhihuo0120** [lyswhut/lx-music-desktop#27]
非常喜欢这个软件。
此软件是不是不鼓励它变成音乐播放器，而只是作为下歌曲的地方？
如果是的话，我不会把它变成听歌软件。

**Comment by lyswhut** [comment]
本软件最初定位不是作为播放器开发的，只是为了用它来找歌，建议使用其他播放器播放。
当然，这只是我个人建议，你们想怎么用就怎么用，看个人喜好吧。。。

**Comment by zhihuo0120** [comment]
我觉得不错，如果稳定的话，我就拿来当音乐播放器。
比较单调，符合我的口味。
非常感谢。

**Comment by lyswhut** [comment]
这类软件不会稳定的，毕竟涉及版权，稳不稳定全看接口的
