### ISSUE TITLE
求添加全部播放

### ISSUE THREAD

**Issue by jiansite** [lyswhut/lx-music-desktop#275]
![image](https://user-images.githubusercontent.com/33872552/89035556-bf252500-d36d-11ea-820c-48380198cad9.png)
![image](https://user-images.githubusercontent.com/33872552/89035626-de23b700-d36d-11ea-9987-10d9def4d6e0.png)
热歌榜、推荐歌单等，求添加 全部播放，现在每次只能 点击一曲播放，或者一个个添加到播放列表。

**Comment by chaoqingshuai** [comment]
强烈建议添加这个功能，现在歌单都是只能一首一首的播放，极其不方便

**Comment by chenzhixian1995** [comment]
强烈建议添加这个功能！

**Comment by wkb488** [comment]
ctrl+A都不知道嘛

**Comment by chaoqingshuai** [comment]
> ctrl + A都不知道嘛

麻烦看清楚是全部播放，不是全部选中，能理解区别吗？不能理解自己百度

**Comment by chaoqingshuai** [comment]
> ctrl + A都不知道嘛

麻烦看清楚是全部播放，不是全部选中。能理解区别吗？不能理解就百度，这么浅显的东西都分不清

**Comment by wkb488** [comment]
> > ctrl + A都不知道嘛
> 
> 麻烦看清楚是全部播放，不是全部选中。能理解区别吗？不能理解就百度，这么浅显的东西都分不清

呵呵，要我把饭嚼好了给你直接吞？行吧，好人做到底，ctrl+A之后右键播放，这下还有问题没？这点悟性都没有就别出来丢人了

**Comment by LasyIsLazy** [comment]
有个全部播放确实会方便好多

**Comment by snowdabao** [comment]
> > > ctrl + A都不知道嘛
> > 
> > 
> > 麻烦看清楚是全部播放，不是全部选中。能理解区别吗？不能理解就百度，这么浅显的东西都分不清
> 
> 呵呵，要我把饭嚼好了给你直接吞？行吧，好人做到底，ctrl+A之后右键播放，这下还有问题没？这点悟性都没有就别出来丢人了

ctrl+A后右键是可行的。但mac下要注意，点击内容文字间隔的空白处！！文字上右键没有反应的。注意是空白处。

**Comment by lyswhut** [comment]
已在v1.1.0新增该功能
