### ISSUE TITLE
建议添加的多个功能

### ISSUE THREAD

**Issue by O-AN-drew-O** [lyswhut/lx-music-desktop#276]
# 我P了张图来表达效果
![](https://gitee.com/AN_drew/picBed/raw/master/img/new2.png)
# ①每首歌最后添加快捷删除按钮
# ②右键菜单添加清空列表按钮
# ③将当前播放直接添加到歌单
# ④音量栏添加喇叭图标

**Comment by lyswhut** [comment]
1、没必要将删除按钮放到外面
2、清空列表可全选后删除歌曲
3、右击当前播放歌曲的封面即可快速定位当前播放的歌曲位置，然后再自行添加
4、暂不打算修改音量条，以后若添加下一首歌曲切换方式时再顺带修改
