### ISSUE TITLE
首页的最小化和关闭按钮中图片不居中

### ISSUE THREAD

**Issue by czghzc** [lyswhut/lx-music-desktop#278]
首页的最小化和关闭按钮中图片不居中
首页播放条的歌词歌词字体太小,并且没有居中

**Comment by lyswhut** [comment]
提供截图，系统类型、版本，软件版本，重现步骤等内容

**Comment by czghzc** [comment]
在 Win10  64bit 和 Win7 64bit 系统上都是这样,这应该是一个普遍的问题
![2020-08-10_080959](https://user-images.githubusercontent.com/23645596/89744694-03d55c80-dae2-11ea-9a6d-c1213d28ac70.png)
之前的歌词是居中显示的,新的版本可能你变更为左对齐了,但是个人认为还是居中看着舒服一点

**Comment by lyswhut** [comment]
我在win10没有这个问题
![image](https://user-images.githubusercontent.com/20365169/89746261-5cf5be00-daeb-11ea-973d-6160e07440db.png)

虚拟机里的win7也是正常的
![image](https://user-images.githubusercontent.com/20365169/89746335-a8a86780-daeb-11ea-9342-6fba81bc11f2.png)

你是否开启了缩放等设置

现有布局居中显示歌词不好看，这里的歌词一般用作预览，想要看歌词自行到详情页或者桌面歌词看

**Comment by czghzc** [comment]
我的系统的缩放比例都是100%.
我找到问题了,软件的窗口尺寸设置为较小时会出现这种情况,其他的都不会.
![2020-08-10_093845](https://user-images.githubusercontent.com/23645596/89746751-0473f000-daee-11ea-8d5d-fcdf30d06733.png)

**Comment by lyswhut** [comment]
问题已确认

**Comment by lyswhut** [comment]
已在v1.1.0修复
