### ISSUE TITLE
导出格式

### ISSUE THREAD

**Issue by zhangsan102** [lyswhut/lx-music-desktop#279]
为什么从json格式变成了lxmc了

**Comment by lyswhut** [comment]
由于导出的原始的json格式文件太大，从v1.0.0起会对json文件进行压缩，想要自己读取该类文件，你可以将`lxmc`扩展名改为`gz`后用压缩软件解压即可获得json文件

**Comment by zhy0404** [comment]
为什么导入不了json文件

**Comment by lyswhut** [comment]
> 为什么导入不了json文件

确认JSON文件内的数据结构是否是LX所用的格式

**Comment by zhy0404** [comment]
格式是什么样子的呢！我没找到啊

**Comment by zhy0404** [comment]
> > 为什么介绍不了json文件
> 
> 确认JSON文件内部的数据结构是否是LX所用的格式

格式是什么样子的呢！我没找到啊

**Comment by lyswhut** [comment]
自己导出来按二楼的方法打开分析不就知道了吗？

**Comment by bk201sama** [comment]
不方便导入
