### ISSUE TITLE
【建议】点击歌词并展开歌词

### ISSUE THREAD

**Issue by chillgoor** [lyswhut/lx-music-desktop#28]
首先感谢开发者！
目前软件（v0.6.0）不支持展开歌词的功能（可能我的使用方法不对？）
很希望能添加此功能
预期行为：
1. 点击主页面歌词位置
2. 展开歌词在主页面（右边白色部分）
3. 歌词支持自动/手动滚动
4. 高亮正在播放的位置的歌词部分

**Comment by lyswhut** [comment]
个人不推荐使用本软件作为常用播放器使用，本软件是为了查找歌曲，
可以用其他播放器播放

由于洛雪音乐的最初定位不是作为播放器开发的，开发它是为了找歌。
这些功能以后可能会做，但目前暂时没有马上开发的计划。
