### ISSUE TITLE
新版不能下载歌曲了吗？

### ISSUE THREAD

**Issue by qin9125** [lyswhut/lx-music-desktop#291]
好久没更新刚刚更新了1.0.1发现不能下载了？
![image](https://user-images.githubusercontent.com/32502941/90252000-519aed80-de71-11ea-84f0-72a5dcf06117.png)

**Comment by Killea** [comment]
![image](https://user-images.githubusercontent.com/5551824/90260005-e7eef500-de18-11ea-8a36-87672472adea.png)
请close

**Comment by HackerGBD** [comment]
怎么下载无损的呀？
