### ISSUE TITLE
推荐添加创建歌单功能

### ISSUE THREAD

**Issue by smlz-one** [lyswhut/lx-music-desktop#30]
只有一个试听列表有点不方便，推荐添加一个自行创建歌单的功能

**Comment by lyswhut** [comment]
问题重复，
个人不推荐使用本软件作为常用播放器使用，本软件是为了查找歌曲，
可以用其他播放器播放。

软件内部已预留多播放列表扩展，后续应该会加，目前试听列表与下载列表是相互独立的两个列表。
