### ISSUE TITLE
添加设置功能:关闭自动更新

### ISSUE THREAD

**Issue by youyiqin** [lyswhut/lx-music-desktop#300]
**描述您想要的解决方案**
每次开启应用都会自动更新是否有新版本,但是在某些用户看来,实在是没有必要,我理解新版本优化和修复了一些bug,亦或是增加了新功能.但是对于够用就行的用户来说,开启应用看到更新消息是不好的用户体验.

**另外**
给我们一些自由吧~

**Comment by youyiqin** [comment]
您好,我在设置里没有看到跳过自动检查更新的设置,因此才来发issue的.谢谢.

**Comment by lyswhut** [comment]
不需要自动更新的话请使用绿色版，[v0.17.0](https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md#0170---2020-03-15) 以后已新增忽略当前新版本按钮：
> 新增发现新版本更新失败弹窗的忽略提醒按钮，忽略提醒后，以后同一个版本再失败时将不会弹窗提醒，但仍可到设置-版本更新手动点开更新弹窗查看该版本详情
