### ISSUE TITLE
某易音乐搜索结果无法翻页的问题

### ISSUE THREAD

**Issue by fg4084** [lyswhut/lx-music-desktop#301]
在Mac平台使用，在某易音乐标签下搜索了一个专辑，发现只能显示前20项，没有翻页按钮
<img width="1130" alt="Xnip2020-09-03_09-58-17" src="https://user-images.githubusercontent.com/57426883/92062753-061e9400-edcc-11ea-91ed-96c59f1bfcf4.png">

**Comment by lyswhut** [comment]
软件搜索的只是单曲，官网的单曲搜索也只有20条记录：<https://music.163.com/#/search/m/?s=love%20101%3A%20101%20ways&type=1>
