### ISSUE TITLE
建议：添加播放本地音乐功能/一键导入歌单

### ISSUE THREAD

**Issue by kingqqwx** [lyswhut/lx-music-desktop#302]
本地存了几百首歌无法导入，如果一首一首保存是很大的工作量。
如果能支持一键导入歌单就更棒了！您辛苦

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/247

**Comment by 0mayfly0** [comment]
是的，希望能够出现一个批量导入，最好可以是分到不同的区域，按照文件夹来导入，然后导入到不同文件夹可以有不同的区域。
类似于PotPlayer播放器那样管理。但是PotPlayer好像不能显示嵌入在歌里面的歌词。我从网易云下载了一些歌，歌词和歌是嵌在一起的，用PotPlayer只能播放音乐，不能显示歌词。很苦恼。。。。
