### ISSUE TITLE
建议添加用户云同步功能

### ISSUE THREAD

**Issue by chuwe1** [lyswhut/lx-music-desktop#310]
记住收藏和播放列表，比较方便。

**Comment by lyswhut** [comment]
云同步需要用到服务器，由于本项目不盈利，所以不会有该功能。

**Comment by MFuching** [comment]
webDAV同步呢

**Comment by OrzMiku** [comment]
webdav呢？

**Comment by zeplee** [comment]
这个音乐软件用了好久啦，就是平板和手机没法同步，歌单差异越来越大，希望可以参考下开源  的阅读软件使用了webdav功能，可以连接坚果云同步
