### ISSUE TITLE
希望添加桌面歌词悬浮功能

### ISSUE THREAD

**Issue by wangqunsheng** [lyswhut/lx-music-desktop#311]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
什么歌词悬浮？

**Comment by wangqunsheng** [comment]
哈喽我看了一下，是有的，希望可以有样式选择，比如网易云的，就是两句，而不是一整片








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 晚上9:09
收件人:&nbsp;"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送:&nbsp;"Da.爆炸～"<1227326164@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] 希望添加桌面歌词悬浮功能 (#311)





 
什么歌词悬浮？

**Comment by wangqunsheng** [comment]
大佬我错了，我功能刚使用还不太熟悉，给你们添乱了，发现歌词框也是可以调整的







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 晚上9:09
收件人:&nbsp;"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送:&nbsp;"Da.爆炸～"<1227326164@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] 希望添加桌面歌词悬浮功能 (#311)





 
什么歌词悬浮？
