### ISSUE TITLE
例如：音乐无法播放

### ISSUE THREAD

**Issue by 123ABCDF11345** [lyswhut/lx-music-desktop#314]
- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
在1.0.0升级到1.1.1时下载完成安装包开始升级时成功卸载旧版本，但没有安装新版本

**重现**
重现行为的步骤：
1.自动下载更新
2.点击“ 重启软件更新”
3.给予旧版本卸载程序（old-uninstall）管理员权限
4.等待10分钟后，仍然没有安装新版本

**预期行为**
更新

**环境：**
  -操作系统及版本：Windows 10 64位 20H4
  -软件安装包及版本：Windows 64位安装版 1.0.0

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/196
