### ISSUE TITLE
求一个【搜索歌单】功能，能通过关键字搜索相关歌单。

### ISSUE THREAD

**Issue by xxxxyp** [lyswhut/lx-music-desktop#315]
**解决方案检查**

-  [x]我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
-  [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
求一个【搜索歌单】功能，能通过关键字搜索相关歌单。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
已有歌单分类，歌单搜索暂不打算做，这需要接口以及新的UI设计

**Comment by InoriHimea** [comment]
哈哈，这是个好需求

**Comment by lyswhut** [comment]
已在v2.0.0新增
