### ISSUE TITLE
macOS下锁定歌词无法再调整歌词设置，如何取消桌面歌词锁定？

### ISSUE THREAD

**Issue by bashang03** [lyswhut/lx-music-desktop#316]
点锁定之后，无法取消锁定，彻底无法调节桌面歌词设置
退出lx之后重开也默认之前的状态
![image](https://user-images.githubusercontent.com/35508406/93786400-dbed2300-fc61-11ea-9e1b-ee432747df74.png)

**Comment by lyswhut** [comment]
在设置找桌面歌词解锁

**Comment by lyswhut** [comment]
在v1.2.0可以右击开关桌面歌词按钮 锁定/解锁 歌词
![image](https://user-images.githubusercontent.com/20365169/94598226-3d943980-02c1-11eb-89ec-efbde838cfee.png)
