### ISSUE TITLE
建议改一下设置里的导出导入说明

### ISSUE THREAD

**Issue by kuronekonano** [lyswhut/lx-music-desktop#317]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索 issue 列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

- [x] 我已阅读导入导出部分代码逻辑，你们确实实现了所有列表包括 defaultlits，lovelist，userlist 的导出导入

- [x] 我已搜索 issue 列表 包括close的，以前有人提过这事，你们也回复了“一直都有导出功能”
- [x] 我已阅读更新日志
**描述您想要的解决方案**
有个妹子跟我说你们的播放器很好用，但是导出不了收藏列表，我读了下代码发现导出逻辑**确实能实现收藏列表的导出**，妹子跟我说：“就 这个软件很奇怪 他自带的功能可以导出试听列表 但是不能导出我的收藏”。
我看了下设置里的导出选项说明，无论是列表导出还是全量导出只写了【设置和试听列表】，你不是导出了收藏列表吗？
所以建议在导出导入的位置说明一些你们导出了啥，不然用户以为只能导出试听和设置。。。
**描述您考虑过的替代方案**
为了用户体验，详细的写一下说明吧。。。用户真的是写啥就信啥，同时我发现妹子并没有试过这个导出功能。。。否则她会发现导出的不仅仅是试听列表
![T)I5AAZ`EK5GU}D4DIL(@YT](https://user-images.githubusercontent.com/33979917/93917812-0a403080-fd3e-11ea-95b0-0ea43f7a7de2.png)
![QZU}1}SAU{V`_6R7CWNUUHG](https://user-images.githubusercontent.com/33979917/93918493-04971a80-fd3f-11ea-9e34-d584b845edaf.png)

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by kuronekonano** [comment]
![T)I5AAZ`EK5GU}D4DIL(@YT](https://user-images.githubusercontent.com/33979917/93918742-58a1ff00-fd3f-11ea-92d0-5fc87570adf2.png)

**Comment by lyswhut** [comment]
导出列表的同时，试听、收藏列表一直都是一起导出的：[](https://github.com/lyswhut/lx-music-desktop/blob/526b5fe140e6614cee5a80ad3578ce279d7d3bc3/src/renderer/views/Setting.vue#L699)
我试了下也可以正常导出与导入，至于你说的这个问题，请提供软件版本、重现步骤等信息

**Comment by lyswhut** [comment]
呃，你是说功能描述不清楚是吧？
由于最初软件只有试听列表，所以描述导出的列表说的是试听列表，
但后面加了收藏列表、用户列表等功能后，忘了更新这个描述，我下个版本更新下描述

**Comment by kuronekonano** [comment]
是的，是功能描述，感谢~

**Comment by lyswhut** [comment]
已在v1.2.0修正导入导出的描述
