### ISSUE TITLE
试听列表重复收藏会删除收藏列表的歌曲

### ISSUE THREAD

**Issue by ruomubingfeng** [lyswhut/lx-music-desktop#318]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
试听列表重复收藏会删除收藏列表的歌曲
**重现**
重现行为的步骤：
1.试听列表在某一歌曲上右键选择添加到收藏
2.试听列表在同一一歌曲上右键选择移动到收藏
3.收藏内歌曲消失
4.看到错误

**预期行为**
不会重复收藏或者覆盖掉之前收藏的歌曲

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[Windows 10 64位 家庭版]
  -软件安装包及版本：[Windows 64位绿色版 1.2.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
抱歉，之前issue太多没注意到这个问题，
谢谢反馈👍👍，下个版本修复🍻

**Comment by lyswhut** [comment]
已在v1.4.0修复
