### ISSUE TITLE
建议：添加排序功能

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#321]
- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**简要描述：**
    在分类名右侧添加“△▽”符号
    例下：
![无标题](https://user-images.githubusercontent.com/70054392/94883333-fc588100-049c-11eb-8c58-7b6bee6bf2ad.png)

**具体功能建议：**
(横线只是为了便  于  阅  读)

----按下1次时：
--------按字母表顺序从前到后（A-#）排序
--------“△”符号亮起
----按下2次时：
--------按字母表顺序从后到前（#-A）排序
--------“▽”符号亮起
----按下3次时：
--------还原原来的排序
--------全符号熄灭

**谢谢！**

**Comment by hs10123116** [comment]
同意增加排序功能！

**Comment by lyswhut** [comment]
将会添加手动排序功能，A-#这种不打算添加

**Comment by lyswhut** [comment]
已在v1.6.0添加自定义顺序功能。
多选排序时在调整顺序后，还将会按照你多选的顺序排序
