### ISSUE TITLE
左上角长方形小区域大量类似白色闪烁马赛克

### ISSUE THREAD

**Issue by gzqx** [lyswhut/lx-music-desktop#322]
**解决方案检查**

- [x ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
安装后左上角大量类似白色闪烁马赛克，大约在窗口八分之一大小

**重现**
重现行为的步骤：
自从安装后即发生，当界面发生重新加载的时候就会出现，比如滚动或者切换面板，在确认协议界面极其严重几乎不消失，进入后（尤其是调整了几次窗口大小后）逐渐缓解，但仍偶有闪烁

**预期行为**
不出现这一白斑

**截图**
![截图](https://user-images.githubusercontent.com/24262751/94994165-38234180-0596-11eb-8de4-b1f426c668c3.png)

**环境：**
  -操作系统及版本：Fedora Plasma 32.0
  -软件安装包及版本： lx-music-desktop.v1.2.0.x64.rpm

**其他内容**
暂无

**Comment by lyswhut** [comment]
Ubuntu、Debian系统没有该问题，其他Linux版有问题暂时不打算解决，
这看起来是缺少某些运行库或者不支持GUP渲染导致的？

**Comment by lyswhut** [comment]
尝试下载最新版本(v1.6.0)添加`-dha`参数运行
