### ISSUE TITLE
搜索的时候按回车键给个反馈，有时候没感觉

### ISSUE THREAD

**Issue by MemoryCollection** [lyswhut/lx-music-desktop#323]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by lyswhut** [comment]
你想要什么反馈？

**Comment by lyswhut** [comment]
你说的应该是 https://github.com/lyswhut/lx-music-desktop/issues/386
下个版本会添加，由于存在相同issue，现在我关掉它
