### ISSUE TITLE
更新永远是失败的

### ISSUE THREAD

**Issue by lystormenvoy** [lyswhut/lx-music-desktop#324]
![image](https://user-images.githubusercontent.com/6795312/95682873-71a12000-0c1a-11eb-9cf9-2037e8825d16.png)
从来都是打开软件直接提示失败，有什么方法找出原因？

**Comment by lyswhut** [comment]
目前只有windows 安装版才能自动更新，但是如果你的所在网络环境访问GitHub很慢或者无法访问的话，也会出现更新失败的情况

**Comment by lystormenvoy** [comment]
> 目前只有windows 安装版才能自动更新，但是如果你的所在网络环境访问GitHub很慢或者无法访问的话，也会出现更新失败的情况

了解，挂着梯子。不过是绿色版

**Comment by hejun041** [comment]
为什么放着放着下一首就连接失败了，只有重启客户端才可以继续播放
