### ISSUE TITLE
鼠标在软件窗口上移动时软件闪烁

### ISSUE THREAD

**Issue by leekbillow** [lyswhut/lx-music-desktop#326]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
鼠标在软件窗口上移动，软件窗口会闪烁，从窗口外移入窗口内或者从某个区域移入另一个区域时会发生。

**重现**
重现行为的步骤：
1.打开软件
2.在软件窗口上移动鼠标
3.看到错误

**预期行为**
不发生闪烁情况。

**截图**
![QQ录屏20201013114456_1](https://user-images.githubusercontent.com/43409097/95814193-61895d80-0d4c-11eb-9e15-0aaac380a88e.gif)

**环境：**
  -操作系统及版本：Windows 7 64位
  -软件安装包及版本：[lx-music-desktop-v1.2.0-x86_64-Setup.exe](https://github.com/lyswhut/lx-music-desktop/releases/tag/v1.2.0)

**Comment by lyswhut** [comment]
对于软件启动后，可以在任务栏看到软件，但软件界面在桌面上无任何显示，或者整个界面偶尔闪烁的情况。
解决办法：下载`.NET Framework 4.7.1`或**更高**版本安装即可(建议安装最新版，若安装过程中遇到问题可尝试自行百度解决)。
微软官方下载地址：<https://dotnet.microsoft.com/download/dotnet-framework>
下载`Runtime(运行时)`版即可

**Comment by leekbillow** [comment]
> 对于软件启动后，可以在任务栏看到软件，但软件界面在桌面上无任何显示，或者整个界面偶尔闪烁的情况。
> 解决办法：下载`.NET Framework 4.7.1`或**更高**版本安装即可(建议安装最新版，若安装过程中遇到问题可尝试自行百度解决)。
> 微软官方下载地址：https://dotnet.microsoft.com/download/dotnet-framework
> 下载`Runtime(运行时)`版即可

下载后发现我已经安装了4.8版本了，又选择了“修复”选项，仍然出现这个问题

**Comment by lyswhut** [comment]
若还是不行可尝试以下操作：
- 更新显卡驱动
- 尝试将绿色版的软件放在桌面或我的文档运行

**Comment by leekbillow** [comment]
> 若还是不行可尝试以下操作：
> 
> * 更新显卡驱动
> * 尝试将绿色版的软件放在桌面或我的文档运行

还是失败了……可能我的系统有些问题吧

**Comment by lyswhut** [comment]
尝试安装/更新下运行库：<https://github.com/abbodi1406/vcredist/releases>
再不行我也没办法了

**Comment by leekbillow** [comment]
看来还是不行……只能等框架改进了吧

**Comment by AWEkn1** [comment]
我还有一种方案，在软件启动之前，在桌面上右键，选择个性化，然后选一个Windows 7 Basic或者Windows经典，然后启动软件，启动之后，将主题改为Windows 7，就没有了闪烁。不过按这个方法会有黑框，目前没法解决。

**Comment by AWEkn1** [comment]
> 

可以吗？
