### ISSUE TITLE
播放整个歌单或排行榜

### ISSUE THREAD

**Issue by gdzl-xcs** [lyswhut/lx-music-desktop#327]
播放在线列表内的歌曲需要将它们都添加到我的列表才能播放，你可以全选列表内的歌曲然后添加到现有列表或者新创建的列表，然后去播放该列表内的歌曲。

我按照上面的要求继续操作，但是还是不行。
加入列表之后是灰色的

**Comment by zhanglanzhu521** [comment]
我也没找到怎么播放整个榜单，，，，

**Comment by gdzl-xcs** [comment]
> 我也没找到怎么播放整个榜单,,,,
好像可以收藏整个榜单，但是收藏之后的榜单在爱心的地方不能播放

**Comment by mayday5555** [comment]
之前多选之后列表右下角有个小浮窗可以批量添加试听的，现在怎么没了

**Comment by lyswhut** [comment]
> 之前多选之后列表右下角有个小浮窗可以批量添加试听的，现在怎么没了

多选后右击

**Comment by chishen666** [comment]
> > 之前多选之后列表右下角有个小浮窗可以批量添加试听的，现在怎么没了
> 
> 多选后右击

CTRL+A后右击播放

**Comment by lyswhut** [comment]
播放整个歌单可以在歌单详情点击标题右侧的播放按钮，排行榜可以右击排行榜名字的菜单中点播放，这两种播放操作都是不将歌曲加入列表的临时播放方式，
若想加入列表播放可以先点击收藏再去我的列表找到这个列表播放，
或者全选所有歌曲加到已有列表播放
