### ISSUE TITLE
没有下载按钮

### ISSUE THREAD

**Issue by WaveWSBS** [lyswhut/lx-music-desktop#328]

**Comment by WaveWSBS** [comment]
是取消下载功能了么

**Comment by WaveWSBS** [comment]
![image](https://user-images.githubusercontent.com/68324220/96332071-abe44480-1094-11eb-948f-f8d07304adc2.png)

**Comment by lyswhut** [comment]
v1.0.0起默认关闭下载功能，若要开启需到设置开启

**Comment by WaveWSBS** [comment]
OK，了解On Oct 17, 2020 16:41, lyswhut <notifications@github.com> wrote:

v1.0.0起默认关闭下载功能，若要开启需到设置开启
