### ISSUE TITLE
1.2.1 Linux 版窗口边缘显示不正常

### ISSUE THREAD

**Issue by SamLukeYes** [lyswhut/lx-music-desktop#329]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
更新 1.2.1 版本后，窗口边缘会显示黑框和白框。

**重现**
重现行为的步骤：
1. 下载 lx-music-desktop-v1.2.1-x64.AppImage
2. `chmod +x lx-music-desktop-v1.2.1-x64.AppImage`
3. 运行 lx-music-desktop-v1.2.1-x64.AppImage
4. 窗口的边缘出现了黑框和会随鼠标移动而闪烁的白框

**预期行为**
窗口边缘正常显示，不应该有黑框和白框。

**截图**
![2020-10-18 11-04-05 的屏幕截图.png](https://i.loli.net/2020/10/18/MpgJ9AeIGt317sP.png)

**环境：

  -操作系统及版本：Manjaro 20.2 (unstable branch), Linux 5.8.14-arch1-2-surface, GNOME 3.38.1
  -软件安装包及版本：Linux 64位 1.2.1 AppImage

**Comment by SamLukeYes** [comment]
刚才试了一下 AUR 中的 `lx-music-desktop-bin`，问题依旧

**Comment by lyswhut** [comment]
是的

**Comment by lyswhut** [comment]
已发布v1.2.2，你再试试看

**Comment by SamLukeYes** [comment]
更新 1.2.2 后显示正常了

**Comment by m2cc** [comment]
最新版1.4.0还是有黑色阴影边框，不知道咋解决
