### ISSUE TITLE
添加几个小功能

### ISSUE THREAD

**Issue by Jw121X** [lyswhut/lx-music-desktop#33]
1、目前只有最小化到任务栏和关闭按钮，这让强迫症怎么办，我就想放在右下工具栏！！0^0

2、希望可以新增一下播放界面，每次想看看歌词啥的都是最下面的一句话，希望可以像其他播放器那种，点击一下可以放大。

3、有手机版吗，想把QQ网易淘汰掉

**Comment by lyswhut** [comment]
1、2：还是那句话，本软件仅用于查找歌曲，不建议用来当日常播放器使用。

3：目前没有手机版，最后说句里牌坊的话，，请支持正版音乐！！
