### ISSUE TITLE
网易云音乐歌单对应错误

### ISSUE THREAD

**Issue by loubth** [lyswhut/lx-music-desktop#332]
# 错误
打开歌单不是与网站打开的歌单不一致
## 测试歌单
https://music.163.com/#/album?id=3420143

**Comment by lyswhut** [comment]
你确定你这个是歌单？
![image](https://user-images.githubusercontent.com/20365169/96409802-76686400-1218-11eb-9d70-3e55a6c59d39.png)

**Comment by loubth** [comment]
呃 不好意思 专辑这样的是不支持的是吗 打扰了

**Comment by lyswhut** [comment]
是的，仅支持打开歌单
