### ISSUE TITLE
在TOP榜添加批量播放功能呀

### ISSUE THREAD

**Issue by roulen100** [lyswhut/lx-music-desktop#334]
希望添加批量播放，或批量添加到收藏夹呀。

**Comment by lyswhut** [comment]
排行榜这边的按钮不懂放哪好，自己手动全选再添加吧

**Comment by yangzaiDL** [comment]
TOP 榜 一键播放 ，可以放在右键 加一个播放当前列表的按钮吗 ，如果可以的话
![image](https://user-images.githubusercontent.com/19410495/104690472-73a9dc00-573f-11eb-9701-bbdab9122722.png)
