### ISSUE TITLE
1.添加下载全选功能 。2.在一个下载源下载失败后自动在另一个下载源重新下载。

### ISSUE THREAD

**Issue by 15876953523** [lyswhut/lx-music-desktop#339]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
添加下载全选功能和在一个下载源下载失败后自动在另一个下载源重新下载

**其他内容**
无

**Comment by 15876953523** [comment]
1.添加歌单下载全选功能。2.在一个下载源下载失败后自动在另一个下载源重新下载。

**Comment by lyswhut** [comment]
1、重复：https://github.com/lyswhut/lx-music-desktop/issues/270
2、暂不计划添加自动换源的功能
