### ISSUE TITLE
第一次解压，打开点击，界面完全卡住了

### ISSUE THREAD

**Issue by kuanjing** [lyswhut/lx-music-desktop#34]
1、点击试听列表后点击不到“排行榜，歌单，搜索，下载管理，和设置”，
2、如果我点击一首歌添加到“试听列表”中，其他的“排行榜，歌单，搜索，下载管理，和设置”都可以点击

**Comment by lyswhut** [comment]
谢谢反馈，不过该问题已在issue列表中：https://github.com/lyswhut/lx-music-desktop/issues/31，下次请先查看想要反馈的问题是否已经存在再创建issue，谢谢合作！

**Comment by kuanjing** [comment]
哦，感谢
