### ISSUE TITLE
鼠标来回滑动时，主界面会闪来闪去

### ISSUE THREAD

**Issue by xiaoming140** [lyswhut/lx-music-desktop#341]
**解决方案检查**

- [ x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
win7 之前没有，好像是这个月才发生，在打开软件是，鼠标滑动，主界面会闪来闪去

**Comment by lyswhut** [comment]
建议按照常见问题说的解决，不行我也没办法了，
https://github.com/lyswhut/lx-music-desktop/issues/326
