### ISSUE TITLE
【功能建议】增加已购买音乐的播放

### ISSUE THREAD

**Issue by 346673164** [lyswhut/lx-music-desktop#342]
你好，在使用软件的时候。扣扣音源的话发现如果是绿钻专享则能正常播放。
但是如果是数字专辑、单曲需要购买的则无法播放。这样就无法听到自己已经购买的单曲、专辑了

可否设置QQ音乐登录，或者cookie填写。发现有数字专辑或者音源获取失败的时候 使用登录的线路获取。

再次感谢作者做出了这么优秀的作品~

**Comment by lyswhut** [comment]
目前不计划在软件内部添加直接获取音乐链接的功能，
建议把歌曲都下载下来再听
