### ISSUE TITLE
歌曲封面嵌入问题

### ISSUE THREAD

**Issue by lincf0912** [lyswhut/lx-music-desktop#348]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
下载的歌曲可以看见封面，但是导入OS X的音乐后，歌曲的插图没有显示封面。

**重现**
重现行为的步骤：
1.开启下载功能和封面嵌入
2.下载完毕后导入MAC的音乐

**预期行为**
导入OS X的音乐后，显示插图封面

**截图**

**环境：**
  -操作系统及版本：macOS 10.15.7
  -软件安装包及版本：lx-music-desktop-1.3.0.dmg

**其他内容**
使用lx-music-desktop-1.0.1.dmg版本是可以达到预期效果的。升级之后就不行了。

**Comment by lyswhut** [comment]
已在v1.4.0修复

**Comment by lincf0912** [comment]
使用v1.4.0 和 v1.4.1 问题未解决，依然是文件有封面，导入音乐后没有封面。
<img width="923" alt="image" src="https://user-images.githubusercontent.com/10151410/100198500-e57f5980-2f36-11eb-9205-89f257b969d2.png">

这是使用v1.0.1版本下载的音乐，没有问题。
<img width="991" alt="image" src="https://user-images.githubusercontent.com/10151410/100198897-71918100-2f37-11eb-9d58-51742a242737.png">

**Comment by Jechin** [comment]
同样出现这个问题
