### ISSUE TITLE
歌词界面

### ISSUE THREAD

**Issue by 1045683477** [lyswhut/lx-music-desktop#35]
**描述您想要的解决方案**
1.想看完整的歌词，可以跟着歌曲滚动，似乎没有，只有进度条下唱一句放一行歌词
2.图标有时间可以美化下

**描述您考虑过的替代方案**
1.点击歌曲的图片可以看到歌词
2.可以把歌词放桌面上显示，类似于 QQ 音乐的哪种功能

**其他内容**
喜欢这个简洁的播放器，加油💪
φ(゜▽゜*)♪

**Comment by lyswhut** [comment]
本软件仅用于查找歌曲，不建议用来当日常播放器使用。
洛雪音乐的最初定位不是作为播放器开发的，因此无收藏列表无界面歌词。
