### ISSUE TITLE
添加黑暗模式皮肤、例如暗黑版微信一样的暗黑，现在都是白色皮肤太亮了

### ISSUE THREAD

**Issue by blueshirt666** [lyswhut/lx-music-desktop#350]

**Comment by jetwong88** [comment]
正想说，希望提供一个黑色边框的纯色主题，既然有人发这个帖子了。那就再顶一下吧。
不管是深色模式还是主题设计，希望尝试一下吧，现在确实太亮了。

**Comment by Ananius** [comment]
希望增加黑暗模式,跟随系统自适应

**Comment by lyswhut** [comment]
大概配了个黑色主题，包含在下个版本的更新中，
跟随系统换肤的暂不打算去实现

![image](https://user-images.githubusercontent.com/20365169/114668490-65b22a00-9d33-11eb-8155-f2c32d552425.png)
![image](https://user-images.githubusercontent.com/20365169/114668530-71055580-9d33-11eb-9446-c26f52dbefa7.png)

**Comment by Ananius** [comment]
用心了.支持.

**Comment by jetwong88** [comment]
感谢，这个黑色的主题看起来就很好了，够用了。

**Comment by lyswhut** [comment]
已在v1.9.0添加黑色皮肤“黑灯瞎火”
