### ISSUE TITLE
歌单收藏后无法播放

### ISSUE THREAD

**Issue by Snoopy008** [lyswhut/lx-music-desktop#351]
**描述错误**
歌单收藏后无法播放

**重现**
重现行为的步骤：
1、随便找一个歌单收藏后
2、点击我的列表
3、显示了刚刚收藏的歌单，但是歌单里面的歌曲都是置灰状态无法播放

**预期行为**
随便点击一首应该可以播放的

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。
<img width="927" alt="image" src="https://user-images.githubusercontent.com/18001368/98184666-e2033e80-1f45-11eb-8c1f-37cc219b2f94.png">

**环境：**
  -操作系统及版本：macOS Catalina 10.15.7
  -软件安装包及版本：1.3.0

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/125
