### ISSUE TITLE
deepin20 Linux下添加托盘菜单

### ISSUE THREAD

**Issue by w190322** [lyswhut/lx-music-desktop#354]
设置中开启“关闭时最小化到系统托盘”后，最小化到右下托盘，右键图标只有打开主面板的选项，未提供Windows下那样右键小图标退出软件功能。没有这个功能很不方便。

**Comment by lyswhut** [comment]
已在v1.4.0添加了托盘菜单，但是我在虚拟机里的Debian 10测试发现启用托盘时会出现两个图标，Ubuntu 18.10则无此问题

**Comment by w190322** [comment]
deepin20是国内基于debian10做的一个，您看是否可以整个deepin20虚拟机排查一下问题？我这里目前是右键托盘小图标，只有一行“lxyyzs”，没有其他选项



---原始邮件---
发件人: "lyswhut"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 晚上7:32
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"w190322"<1206136915@qq.com&gt;;
主题: Re: [lyswhut/lx-music-desktop] deepin20 Linux下无法退出的问题 (#354)




 
已在v1.4.0添加了托盘菜单，但是我在虚拟机里的Debian 10测试发现启用托盘时会出现两个图标，Ubuntu 18.10则无此问题

**Comment by lyswhut** [comment]
前面搞错了，我前面说的Debian 10其实是Deepin 20：
![image](https://user-images.githubusercontent.com/20365169/99876867-c8940f00-2c34-11eb-85cb-3e5c81feea6e.png)

在Deepin 20下有两个托盘菜单，其中一个是程序自己的，另一个貌似是这个系统的桌面自己加上去的

**Comment by w190322** [comment]
我这边1.3版本在物理机上，就只有一个托盘图标，右击显示如图



---原始邮件---
发件人: "lyswhut"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 晚上8:06
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"w190322"<1206136915@qq.com&gt;;
主题: Re: [lyswhut/lx-music-desktop] deepin20 Linux下无法退出的问题 (#354)




 
前面搞错了，我前面说的Debian 10其实是Deepin 20：
 
 
在Deepin 20下有两个托盘菜单，其中一个是程序自己的，另一个貌似是这个系统的桌面自己加上去的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "lyswhut"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 晚上8:06
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"w190322"<1206136915@qq.com&gt;;
主题: Re: [lyswhut/lx-music-desktop] deepin20 Linux下无法退出的问题 (#354)




 
前面搞错了，我前面说的Debian 10其实是Deepin 20：
 
 
在Deepin 20下有两个托盘菜单，其中一个是程序自己的，另一个貌似是这个系统的桌面自己加上去的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "lyswhut"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 晚上8:06
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"w190322"<1206136915@qq.com&gt;;
主题: Re: [lyswhut/lx-music-desktop] deepin20 Linux下无法退出的问题 (#354)




 
前面搞错了，我前面说的Debian 10其实是Deepin 20：
 
 
在Deepin 20下有两个托盘菜单，其中一个是程序自己的，另一个貌似是这个系统的桌面自己加上去的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "lyswhut"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 晚上8:06
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"w190322"<1206136915@qq.com&gt;;
主题: Re: [lyswhut/lx-music-desktop] deepin20 Linux下无法退出的问题 (#354)




 
前面搞错了，我前面说的Debian 10其实是Deepin 20：
 
 
在Deepin 20下有两个托盘菜单，其中一个是程序自己的，另一个貌似是这个系统的桌面自己加上去的

**Comment by w190322** [comment]
确实，更新了一下1.4，托盘有两个图标



---原始邮件---
发件人: "lyswhut"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 晚上8:06
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"w190322"<1206136915@qq.com&gt;;
主题: Re: [lyswhut/lx-music-desktop] deepin20 Linux下无法退出的问题 (#354)




 
前面搞错了，我前面说的Debian 10其实是Deepin 20：
 
 
在Deepin 20下有两个托盘菜单，其中一个是程序自己的，另一个貌似是这个系统的桌面自己加上去的

**Comment by lyswhut** [comment]
关于deepin20下出现两个图片图标的问题，我在deepin15.11下测试是正常的，但deepin20就会出现这个问题，以下是两者的效果图：

![2](https://user-images.githubusercontent.com/20365169/118915338-60ae4f00-b95f-11eb-8afe-cac581fa023a.png)
![1](https://user-images.githubusercontent.com/20365169/118915357-65730300-b95f-11eb-8eb6-1b7425f9e815.png)

在Ubuntu18.10下下手正常的，所以这应该是deepin20桌面的问题，现在我将关闭这个issue

**Comment by lyswhut** [comment]
看到deepin 20.5发布了，试了下，发现托盘图标不会再出现两个的问题了：
![image](https://user-images.githubusercontent.com/20365169/161392176-67e9ef64-fd54-4f4d-b07a-8ca8fbf34011.png)
