### ISSUE TITLE
上一首图标鼠标悬浮提示“下一首”

### ISSUE THREAD

**Issue by xinjiyier** [lyswhut/lx-music-desktop#357]
当前版本：1.3.0 
复现路径：
播放任何一首歌曲，然后将鼠标悬浮到上一首图标，可以看到提示为“下一首”

![image](https://user-images.githubusercontent.com/18064887/99035456-ae19c000-25ba-11eb-9927-c1274e7b3ddb.png)

**Comment by lyswhut** [comment]
已在v1.4.0修复
