### ISSUE TITLE
搜索之后可以点击歌手的名字或专辑的名字进行下一步搜索

### ISSUE THREAD

**Issue by zhghoi** [lyswhut/lx-music-desktop#358]
如题
搜索之后可以点击歌手的名字或专辑的名字进行下一步搜索
方便查看歌手全部歌曲和整张专辑里的歌曲
谢谢！

**Comment by chenwuxin123** [comment]
白嫖还那么多要求

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/272
