### ISSUE TITLE
您好，看到您的项目很牛，想深入学习一下，但是关于node.js 的一些接口不太明白

### ISSUE THREAD

**Issue by zhangsandoit** [lyswhut/lx-music-desktop#359]
<img width="1041" alt="截屏2020-11-13下午5 32 32" src="https://user-images.githubusercontent.com/17157074/99057106-47a29b00-25d6-11eb-8ed5-562cc8b7b774.png">

我按照dart语言的开发方式 发现一些node.js 里面的接口 不知道怎么转换，您有关于项目的相关文档吗

另外 我在用charles重复请求mp3地址的时候发现 用同样的数据无法进行二次请求 报404 您的接口里面是有相关的请求校验吗

**Comment by lyswhut** [comment]
本项目音乐接口无文档且非开源，https://github.com/lyswhut/lx-music-desktop/issues/282
GitHub有一些接口项目，建议尝试去搜索查看
