### ISSUE TITLE
API文档和ARM架构Build

### ISSUE THREAD

**Issue by 123ABCDF11345** [lyswhut/lx-music-desktop#362]
**解决方案检查**
- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**I Want**
①希望能够开源解析API，或者提供API文档（目前的API需要自己去读代码，对于不熟悉这种语言的前端的不太友好）(如果有所顾虑可不可以考虑小范围付费传播）
②增加ARM架构的二进制文件编译

**Comment by lyswhut** [comment]
1、重复：https://github.com/lyswhut/lx-music-desktop/issues/359
2、你需要ARM架构什么格式的包？

**Comment by zhangsandoit** [comment]
移动设备的包

**Comment by lyswhut** [comment]
Electron仅用于构建桌面程序，更多信息自行Google

**Comment by songtao1873** [comment]
可以加一个 arm版本的Windows包吗
