### ISSUE TITLE
希望添加功能：1.无法加载的歌曲自动跳过；2.搜索和播放本地音乐；3.歌单里已下载的音乐，直接播放本地音乐，而不是重新加载网络资源。

### ISSUE THREAD

**Issue by 136131902** [lyswhut/lx-music-desktop#364]
希望添加功能：
1.无法加载的歌曲自动跳过；
![image](https://user-images.githubusercontent.com/23472715/99232395-d1e43c80-282c-11eb-8aaa-1b2825122215.png)
2.搜索和播放本地音乐；
3.歌单里已下载的音乐，直接播放本地音乐，而不是重新加载网络资源。

**Comment by lanyun712** [comment]
1，3同意，2的话我记得可有可无，当然，有的话更好

**Comment by willaytoun** [comment]
三个功能都挺实用的，添加播放本地音乐可以不用来回切应用省不少事，支持添加

**Comment by erenyega** [comment]
下载的歌曲和在线的不能用一个播放器听，这好吗？这不好...

**Comment by hs10123116** [comment]
完全同意这三个功能！

**Comment by Danielma0203** [comment]
+1（doge）

**Comment by 0mayfly0** [comment]
强烈要求把 2 带上
并且希望是能够按照添加 文件夹 的方式添加
添加进来以后还能够以 文件夹 格式存在，别跟其他添加进来的歌曲混在一起。

**Comment by lyswhut** [comment]
已在v2.0.0新增播放本地歌曲功能
