### ISSUE TITLE
强烈建议加一个多选功能

### ISSUE THREAD

**Issue by timo-coco** [lyswhut/lx-music-desktop#365]
![微信截图_20201117112735](https://user-images.githubusercontent.com/44496088/99342983-fe996200-28c7-11eb-93e7-9f08440ae344.png)
选择歌曲过后可进行添加歌单、删除、批量播放等操作

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/270
