### ISSUE TITLE
可以听歌但无法下载

### ISSUE THREAD

**Issue by chenlez** [lyswhut/lx-music-desktop#366]
听歌没有问题，但所有的歌都下载不了，下载状态全部显示ENOENT: no sich file or direct ory, mkdlr

不知道是不是我在海外的原因，但之前都没问题

**Comment by lyswhut** [comment]
看提示信息啊，这种错误可以尝试更改歌曲保存路径

**Comment by chenlez** [comment]
> 看提示信息啊，这种错误可以尝试更改歌曲保存路径

解决了！原来是我手贱改了Mac用户名...感谢！
