### ISSUE TITLE
纯音乐歌词滞留（麻麻我的纯音乐有歌词了！）

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#368]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
麻麻我的纯音乐有歌词了！
在打开一首有歌词的音乐后切换纯音乐时歌词滞留。

**重现**
重现行为的步骤：
1.转到一首有歌词的音乐
2.向下滚动歌单到一首纯音乐
3.看到错误：歌词滞留

**预期行为**
纯音乐不显示歌词

**错误GIF**
![test](https://user-images.githubusercontent.com/70054392/99880188-d786bb80-2c4c-11eb-8257-8912daded18c.gif)

**环境：**
  -操作系统及版本：Windows 10 64位
  -软件安装包及版本：lx-music-desktop v1.4.0 x86_64 win_安装版

**其他内容**
LXNB!

**Comment by Danielma0203** [comment]
![test](https://user-images.githubusercontent.com/70054392/99880231-2e8c9080-2c4d-11eb-8a07-b7bad77604a2.gif)

**Comment by Danielma0203** [comment]
![屏幕截图 2020-11-21 230213](https://user-images.githubusercontent.com/70054392/99880303-a2c73400-2c4d-11eb-8717-497506fd87df.png)

![屏幕截图 2020-11-21 230206](https://user-images.githubusercontent.com/70054392/99880321-b4a8d700-2c4d-11eb-879e-9c37edc534c2.png)

![屏幕截图 2020-11-21 230116](https://user-images.githubusercontent.com/70054392/99880326-b96d8b00-2c4d-11eb-9ac0-ce9eef667d03.png)

**Comment by lyswhut** [comment]
我这边重现不了你这个问题，你可以说下具体怎么触发这个bug吗
![GIF](https://user-images.githubusercontent.com/20365169/99881333-1409e580-2c54-11eb-9998-1b7ae5fd2fc4.gif)

**Comment by Danielma0203** [comment]
经测试
貌似只有一些wy源会触发？

**Comment by Danielma0203** [comment]
Turn Down For ??? - TØm、DJ Snake、Lil Jon

**Comment by Danielma0203** [comment]
试试这首测试音乐？经测试，貌似其他的音乐不会触发。额……奇怪的现象

**Comment by lyswhut** [comment]
还真可以重现。。

**Comment by lyswhut** [comment]
找到问题了，有歌词翻译的歌曲与无歌词的音乐间切换会有这个问题，下个版本修复，谢谢反馈👍

**Comment by Danielma0203** [comment]
我也测试了
就只有有翻译的英文歌曲会出现

**Comment by Danielma0203** [comment]
刚刚想要汇报，您就已经找出了问题😂
谢谢！

**Comment by lyswhut** [comment]
重新打开，修复了再关闭吧

**Comment by lyswhut** [comment]
已在v1.4.1修复该问题
