### ISSUE TITLE
添加功能：搜索结果列表当前播放曲目高亮显示

### ISSUE THREAD

**Issue by ifu25** [lyswhut/lx-music-desktop#369]
## 期望增加的功能

搜索结果`列表`当前播放曲目`高亮显示`。

## 需求背景

搜索一首音乐后列出很多结果，不停点击试听寻找想要的曲目，最终找到想要的音乐想下载，结果`当前正在播放的音乐`在`列表`中是哪一首看不出来，而`下载按钮`只在`列表`后面有，所以非常不方便查找是哪一首。

## 代替方案

如果列表上不能高亮显示当前播放曲目，那在当前播放曲目进度条及控制按钮后面加个`下载按钮`也是很 ok 的。

**Comment by Danielma0203** [comment]
鼠标右键曲目封面可以定位到列表

**Comment by lyswhut** [comment]
2楼的回答是正解

**Comment by ifu25** [comment]
> 鼠标右键曲目封面可以定位到列表

突然发现现在最新版 1.8.2 又不行了，无法找到当前正在播放的音乐所在位置，在我的试听列表右键也无效🤨
