### ISSUE TITLE
没有下载按钮

### ISSUE THREAD

**Issue by sivanWu0222** [lyswhut/lx-music-desktop#370]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
没有下载按钮

**预期行为**
之前使用了另一个版本后面有下载按钮，现在怎么突然没有了呢
**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。
![PFbZ5M](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/PFbZ5M.png)
**环境：**
  -Mac 10.14.6：[例如：Windows 10 64位 18362.156]
  -lx-1.2.0：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
无

**Comment by sivanWu0222** [comment]
解决方案：在设置选项页中找到 ![F5tcPr](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/F5tcPr.png) 并勾选

**Comment by zeqinjie** [comment]
勾選也不能下載？

**Comment by sivanWu0222** [comment]
> 勾選也不能下載？

可以下载的，勾选之后，歌曲后面会有一个下载按钮
