### ISSUE TITLE
1.4.0版本，窗口边缘有黑色阴影，deepin linux 20 1003版本，不知道是什么原因。

### ISSUE THREAD

**Issue by m2cc** [lyswhut/lx-music-desktop#371]
![截图录屏_选择区域_20201125095133](https://user-images.githubusercontent.com/17061984/100172873-40e42400-2f04-11eb-94e9-137f86cfdb4e.png)

**Comment by lyswhut** [comment]
最新版的deepin并未发现黑色阴影的问题：https://github.com/lyswhut/lx-music-desktop/issues/354

**Comment by m2cc** [comment]
> 最新版的deepin并未发现黑色阴影的问题：#354

添加 -nt 参数启动无异常。否则有黑影。
![截图录屏_选择区域_20201213183055](https://user-images.githubusercontent.com/17061984/102009305-8791a500-3d71-11eb-9978-96bce56f4a28.png)

**Comment by fjj739964256** [comment]
我也出现了一次，1.5.0绿色版，win10 64 用的春节的皮肤，切换了一次窗口后发现边框变黑、字体变模糊。重启软件后该现象消失，暂时无法复现，不知是什么原因引起。

**Comment by fjj739964256** [comment]
![image](https://user-images.githubusercontent.com/33320479/102060818-a2c1ea80-3e2d-11eb-8661-6219ad50c05d.png)
复现了，原因大概是小霞音乐搜索弹出的验证界面，导致出现黑框和字体模糊（我特喵瞬间近视！！）。点击任何按钮没有用，只能重启应用解决。

**Comment by lyswhut** [comment]
出现黑边框尝试重启下软件，
或者干脆加`-nt`参数启动（这个模式下将失去透明效果，桌面歌词不可用）

**Comment by lyswhut** [comment]
尝试下载最新版本添加`-dha`参数运行
