### ISSUE TITLE
deepen V20设置关闭时最小化到系统托盘后在系统托盘会显示两个图标，取消后在选中会再增加图标

### ISSUE THREAD

**Issue by lijianxc** [lyswhut/lx-music-desktop#377]
deepen V20设置关闭时最小化到系统托盘后在系统托盘会显示两个图标，取消后在选中会再增加图标，不知道是系统问题还是软件问题
![未命名](https://user-images.githubusercontent.com/74767631/100607451-ec96d500-3345-11eb-9f95-f766eb61d0f6.jpg)

**Comment by lyswhut** [comment]
Ubuntu没有这个问题，deepen才有这个问题，估计是deepen的桌面与electron的托盘冲突了：https://github.com/lyswhut/lx-music-desktop/issues/354

**Comment by haonanq666** [comment]
我是arch + dde，确认有此问题。不勾选「最小化到系统托盘」只显示一个，但是无法这个图标隐藏界面（右击->隐藏主界面 无反应）。

**Comment by haonanq666** [comment]
@lijianxc  我研究出了临时的解决办法，安装一个假的```libappindicator-gtk3```可解决。

挑任意目录，```目录/PKGBUILD``` 内容如下：
```
pkgname='libappindicator-gtk3-dummy'
pkgver=19.0
pkgrel=1
arch=(any)
conflicts=('libappindicator-gtk3=12.10.0.r296')
provides=('libappindicator-gtk3=12.10.0.r296') 
```
在目录运行```makepkg -si```, 询问要不要替换libappindicator选择「是」，然后重启音乐助手就行了。

**Comment by lyswhut** [comment]
两个托盘图标的问题看：https://github.com/lyswhut/lx-music-desktop/issues/354#issuecomment-844660287
