### ISSUE TITLE
可以编译一个arm的版本吗？

### ISSUE THREAD

**Issue by Charles-Wong-Phoenix** [lyswhut/lx-music-desktop#380]
想自己编译来着，但是我的板子上配置不好node.js环境
能麻烦做一个linux arm版本吗？

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/362
> 你需要ARM架构什么格式的包？

**Comment by Charles-Wong-Phoenix** [comment]
> 重复：#362
> 
> > 你需要ARM架构什么格式的包？

.deb

**Comment by lyswhut** [comment]
有`armv7l`与`arm64`两种，你要哪种：https://www.electron.build/cli.html#targetconfiguration

**Comment by Charles-Wong-Phoenix** [comment]
> 有`armv7l`与`arm64`两种，你要哪种：https://www.electron.build/cli.html#targetconfiguration

>>  arm64.

**Comment by lyswhut** [comment]
刚才尝试编译了v1.5.0-beta版，你可以去下载看看：https://bintray.com/lyswhut/lx-music-desktop/lx-music-desktop/1.5.0-beta#files

**Comment by Charles-Wong-Phoenix** [comment]
> 刚才尝试编译了v1.5.0-beta版，你可以去下载看看：https://bintray.com/lyswhut/lx-music-desktop/lx-music-desktop/1.5.0-beta#files

>> 我的是chromebook，Linux子系统是arm64，完美运行。

**Comment by lyswhut** [comment]
已在v1.5.0新增构建arm64架构的deb包
