### ISSUE TITLE
某些酷狗源歌单链接无法打开

### ISSUE THREAD

**Issue by Faith-YSQ** [lyswhut/lx-music-desktop#381]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
未垮源的情况下打不开歌单，麻烦附上歌单源及歌单地址

**Comment by Faith-YSQ** [comment]
酷狗   歌单地址：https://t.kugou.com/1rCYF16wmV2
绿色版win64位

**Comment by Faith-YSQ** [comment]
之前的版本应该是可以的，因为五音助手还是1.3.0的，可以引入歌单

**Comment by Faith-YSQ** [comment]
老版本是可以的

**Comment by lyswhut** [comment]
酷狗歌单无法导入的问题昨晚已经确认了，是在v1.4.0更新的`修复kg源歌曲信息带有单引号等特殊字符被转义的问题`导致的，下个版本修复

**Comment by lyswhut** [comment]
已在v1.5.0修复
