### ISSUE TITLE
大佬，没快捷键是硬伤

### ISSUE THREAD

**Issue by mzyd** [lyswhut/lx-music-desktop#385]
网易云的全局快捷键真香啊

**Comment by haonanq666** [comment]
![image](https://user-images.githubusercontent.com/52809502/101637566-ef0ac600-39fa-11eb-8143-238c78ae7dfd.png)
是这个么？还是网易云有更多的快捷键？

**Comment by mzyd** [comment]
都不是，是我瞎了 /手动捂脸
