### ISSUE TITLE
优化歌单更新功能

### ISSUE THREAD

**Issue by H-Tung** [lyswhut/lx-music-desktop#387]
**解决方案检查**

- [x] 我已阅读[常见问题](<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索[issue列表](<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
目前从链接获取歌单并收藏后不能再次更新歌单,需要再次从歌单界面粘贴链接更新
因为我的习惯是把每日推荐收藏到"我喜欢"里面,然后在洛雪里再听一遍,喜欢的下载下来...

希望能在保存歌单时保存其链接信息,在收藏界面允许右击更新歌单信息

**Comment by TotalLau** [comment]
支持 刚需！

**Comment by lyswhut** [comment]
已在v1.5.0新增更新歌单的功能，该功能仅对直接从歌单详情页点`收藏`按钮收藏的歌单有效
