### ISSUE TITLE
音乐可以播放却不能下载

### ISSUE THREAD

**Issue by jswnlinyu** [lyswhut/lx-music-desktop#391]
**解决方案检查**

- [X ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [X ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
音乐可以播放却不能下载

**重现**
重现行为的步骤：
1.转到“ 搜索”
2.搜索“evermore”
3.选择源“咪咕音乐”
4:下载音乐  willow高品质 | Taylor Swift
3.打开下载列表
4.看到错误

**预期行为**
下载成功。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。
![image](https://user-images.githubusercontent.com/53430542/102001390-cfdaa400-3d2c-11eb-89c7-acde259a004b.png)

**环境：**
  -操作系统及版本：Windows 10 64位 专业版 18632.1256
  -软件安装包及版本：洛雪音乐助手1.4.1官方版

**其他内容**
无

**Comment by lyswhut** [comment]
尝试更改歌曲下载目录

**Comment by jswnlinyu** [comment]
知道了，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: lyswhut<mailto:notifications@github.com>
发送时间: 2020年12月13日 11:52
收件人: lyswhut/lx-music-desktop<mailto:lx-music-desktop@noreply.github.com>
抄送: Daniel LIN<mailto:jswnlinyu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [lyswhut/lx-music-desktop] 音乐可以播放却不能下载 (#391)


尝试更改歌曲下载目录

―
