### ISSUE TITLE
洛雪音乐助手打开窗口全黑

### ISSUE THREAD

**Issue by YaoLaiGang** [lyswhut/lx-music-desktop#394]
**描述错误**

打开音乐助手后，窗口全黑，什么都没有。

**重现**
只需点击或者使用命令打开洛雪音乐助手

**截图**

![image](https://user-images.githubusercontent.com/15951265/102066690-13203a00-3e35-11eb-9bd4-b7c00891958c.png)

**环境：**
![image](https://user-images.githubusercontent.com/15951265/102066795-38ad4380-3e35-11eb-9091-2199acf5e9af.png)
![image](https://user-images.githubusercontent.com/15951265/102066873-55497b80-3e35-11eb-9e3f-091c373df95e.png)

**其他内容**

多次重装均是这种状况，不是很清楚问题的原因，但是我用命令启动报如下error：
![image](https://user-images.githubusercontent.com/15951265/102067001-7dd17580-3e35-11eb-91c6-7d46e5ef18e2.png)
我也去目录看了，确实没有对应的文件

**Comment by lyswhut** [comment]
尝试加`-nt`参数启动

**Comment by YaoLaiGang** [comment]
> 尝试加`-nt`参数启动

问题已解决，应该是使用源安装的包安装有问题，我再release下载重装之后恢复正常
