### ISSUE TITLE
使用代理导致音乐无法播放

### ISSUE THREAD

**Issue by duzexing** [lyswhut/lx-music-desktop#395]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

由于之前使用**代理**，导致现在在不使用代理的情况下会导致所有歌都无法播放，只能在使用代理时才能正常使用软件

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 19041.685]
  -软件安装包及版本：[例如：Windows 64位安装版 1.5.0]

**其他内容**

**Comment by duzexing** [comment]
重置网络设置，更新或重装软件等方法均不能解决。切换网络可以正常使用，但使用现在网络的情况下不使用代理则无法正常使用软件。

**Comment by duzexing** [comment]
> **解决方案检查**
> 
> * [x]  我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)
> * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=))
> 
> **描述错误**
> 
> 由于之前使用**代理**，导致现在在不使用代理的情况下会导致所有歌都无法播放，只能在使用代理时才能正常使用软件
> 
> **环境：**
>   -操作系统及版本：[例如：Windows 10 64位 19041.685]
>   -软件安装包及版本：[例如：Windows 64位安装版 1.5.0]
> 
> **其他内容**

**Comment by duzexing** [comment]
> **解决方案检查**
> 
> * [x]  我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)
> * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=))
> 
> **描述错误**
> 
> 由于之前使用**代理**，导致现在在不使用代理的情况下会导致所有歌都无法播放，只能在使用代理时才能正常使用软件
> 
> **环境：**
>   -操作系统及版本：[例如：Windows 10 64位 19041.685]
>   -软件安装包及版本：[例如：Windows 64位安装版 1.5.0]
> 
> **其他内容**

**Comment by lyswhut** [comment]
尝试切换网络（如切换到移动网络）访问

**Comment by uruseikyo** [comment]
我也碰到了同样的问题，
是否是因为软件第一次运行之后自动修改了注册表还是哪里的内容，
导致后面即使回到大陆IP也无法播放？

**Comment by duzexing** [comment]
> 我也碰到了同样的问题，
> 
> 是否是因为软件第一次运行之后自动修改了注册表还是哪里的内容，
> 
> 导致后面即使回到大陆IP也无法播放？

是的，我也认为应该是这个问题，但是不知道修改的是注册表什么地方……

**Comment by duzexing** [comment]
> 尝试切换网络（如切换到移动网络）访问
切换网络后可以正常播放，但是再次切换之前的IP任然不能使用，有没有方法可以用之前的IP播放

**Comment by lyswhut** [comment]
IP被服务器限制了，过段时间再试吧，

**Comment by uruseikyo** [comment]
> > 尝试切换网络（如切换到移动网络）访问
> > 切换网络后可以正常播放，但是再次切换之前的IP任然不能使用，有没有方法可以用之前的IP播放

今天尝试了删除痕迹。

1. 用everything搜索全硬盘的lx-music
2. 把搜索到的一切全部删除，包括安装包，包括解压文件夹，以及包括C盘的roaming app文件夹
3. 一切删除干净后，关机
4. 断开网络
5. 开机，此时没有网络，用手机当热点，于是可以保证，这一定是一个全新的IP，以及一台完全没有任何lx-music软件痕迹的电脑
6. 用电脑连上手机热点
7. 下载最新版的1.5.0版的lx-music
8. 解压，运行exe，此时，跳出了同意协议界面，那么，基于此，我可以认为，lx-music软件应该成功地把这台电脑识别为全新电脑了，我此时松了口气，认为问题应该可以解决了。


# **10. 仍然失败，也就是说，在新电脑（重新同意使用协议），新IP（手机热点）的情况下，仍然无法使用软件。**


11.下一步：下次如果有空的话，我找找时间试试伪装mac地址吧，今天实在筋疲力竭了。

**Comment by duzexing** [comment]
> > > 尝试切换网络（如切换到移动网络）访问
> > > 切换网络后可以正常播放，但是再次切换之前的IP任然不能使用，有没有方法可以用之前的IP播放
> 
> 今天尝试了删除痕迹。
> 
> 1. 用everything搜索全硬盘的lx-music
> 2. 把搜索到的一切全部删除，包括安装包，包括解压文件夹，以及包括C盘的roaming app文件夹
> 3. 一切删除干净后，关机
> 4. 断开网络
> 5. 开机，此时没有网络，用手机当热点，于是可以保证，这一定是一个全新的IP，以及一台完全没有任何lx-music软件痕迹的电脑
> 6. 用电脑连上手机热点
> 7. 下载最新版的1.5.0版的lx-music
> 8. 解压，运行exe，此时，跳出了同意协议界面，那么，基于此，我可以认为，lx-music软件应该成功地把这台电脑识别为全新电脑了，我此时松了口气，认为问题应该可以解决了。
> 
> # **10. 仍然失败，也就是说，在新电脑（重新同意使用协议），新IP（手机热点）的情况下，仍然无法使用软件。**
> 11.下一步：下次如果有空的话，我找找时间试试伪装mac地址吧，今天实在筋疲力竭了。

用everything删除还有重置电脑网络设置的方法我都试过了不能解决，不过很诡异的一件事情是我之前使用的SSTAP那个代理供应商跑路了，今天换了一个V2rayN，然后用了一天发现他莫名其妙的就好了……

**Comment by duzexing** [comment]
> > > 尝试切换网络（如切换到移动网络）访问
> > > 切换网络后可以正常播放，但是再次切换之前的IP任然不能使用，有没有方法可以用之前的IP播放
> 
> 今天尝试了删除痕迹。
> 
> 1. 用everything搜索全硬盘的lx-music
> 2. 把搜索到的一切全部删除，包括安装包，包括解压文件夹，以及包括C盘的roaming app文件夹
> 3. 一切删除干净后，关机
> 4. 断开网络
> 5. 开机，此时没有网络，用手机当热点，于是可以保证，这一定是一个全新的IP，以及一台完全没有任何lx-music软件痕迹的电脑
> 6. 用电脑连上手机热点
> 7. 下载最新版的1.5.0版的lx-music
> 8. 解压，运行exe，此时，跳出了同意协议界面，那么，基于此，我可以认为，lx-music软件应该成功地把这台电脑识别为全新电脑了，我此时松了口气，认为问题应该可以解决了。
> 
> # **10. 仍然失败，也就是说，在新电脑（重新同意使用协议），新IP（手机热点）的情况下，仍然无法使用软件。**
> 11.下一步：下次如果有空的话，我找找时间试试伪装mac地址吧，今天实在筋疲力竭了。

用everything删除还有重置电脑网络设置的方法我都试过了不能解决，不过很诡异的一件事情是我之前使用的SSTAP那个代理供应商跑路了，今天换了一个V2rayN，然后用了一天发现他莫名其妙的就好了……

> > > 尝试切换网络（如切换到移动网络）访问
> > > 切换网络后可以正常播放，但是再次切换之前的IP任然不能使用，有没有方法可以用之前的IP播放
> 
> 今天尝试了删除痕迹。
> 
> 1. 用everything搜索全硬盘的lx-music
> 2. 把搜索到的一切全部删除，包括安装包，包括解压文件夹，以及包括C盘的roaming app文件夹
> 3. 一切删除干净后，关机
> 4. 断开网络
> 5. 开机，此时没有网络，用手机当热点，于是可以保证，这一定是一个全新的IP，以及一台完全没有任何lx-music软件痕迹的电脑
> 6. 用电脑连上手机热点
> 7. 下载最新版的1.5.0版的lx-music
> 8. 解压，运行exe，此时，跳出了同意协议界面，那么，基于此，我可以认为，lx-music软件应该成功地把这台电脑识别为全新电脑了，我此时松了口气，认为问题应该可以解决了。
> 
> # **10. 仍然失败，也就是说，在新电脑（重新同意使用协议），新IP（手机热点）的情况下，仍然无法使用软件。**
> 11.下一步：下次如果有空的话，我找找时间试试伪装mac地址吧，今天实在筋疲力竭了。

用everything删除还有重置电脑网络设置的方法我都试过了不能解决，不过很诡异的一件事情是我之前使用的SSTAP那个代理供应商跑路了，今天换了一个V2rayN，然后用了一天发现他莫名其妙的就好了……

**Comment by 502729517hjh** [comment]
V2rayN实测可以使用

**Comment by uruseikyo** [comment]
> > > > 尝试切换网络（如切换到移动网络）访问
> > > > 切换网络后可以正常播放，但是再次切换之前的IP任然不能使用，有没有方法可以用之前的IP播放
> > 
> > 
> > 今天尝试了删除痕迹。
> > 
> > 1. 用everything搜索全硬盘的lx-music
> > 2. 把搜索到的一切全部删除，包括安装包，包括解压文件夹，以及包括C盘的roaming app文件夹
> > 3. 一切删除干净后，关机
> > 4. 断开网络
> > 5. 开机，此时没有网络，用手机当热点，于是可以保证，这一定是一个全新的IP，以及一台完全没有任何lx-music软件痕迹的电脑
> > 6. 用电脑连上手机热点
> > 7. 下载最新版的1.5.0版的lx-music
> > 8. 解压，运行exe，此时，跳出了同意协议界面，那么，基于此，我可以认为，lx-music软件应该成功地把这台电脑识别为全新电脑了，我此时松了口气，认为问题应该可以解决了。
> > 
> > # **10. 仍然失败，也就是说，在新电脑（重新同意使用协议），新IP（手机热点）的情况下，仍然无法使用软件。**
> > 11.下一步：下次如果有空的话，我找找时间试试伪装mac地址吧，今天实在筋疲力竭了。
> 
> 用everything删除还有重置电脑网络设置的方法我都试过了不能解决，不过很诡异的一件事情是我之前使用的SSTAP那个代理供应商跑路了，今天换了一个V2rayN，然后用了一天发现他莫名其妙的就好了……

我长期未开机，
今天也是开机，
重新换了一个v2ray的节点，
也是自动好了，，，不过用的是今天新下载的1.6.1版本。
虽然很奇怪但是，  issue closed.

**Comment by cjydayang** [comment]
@lyswhut 我也遇到了使用代理一直无法加载的问题，提示“所有歌曲都提示 请求异常😮，可以多试几次，若还是不行就换一首吧。。。” 

- ts.tempmusic.tk 可以正常ping通，解析到的ip是97.64.37.235
- 我的代理是配置到路由器的，路由器关闭代理后可以正常加载
