### ISSUE TITLE
希望添加试听列表清空功能

### ISSUE THREAD

**Issue by Guitly-X** [lyswhut/lx-music-desktop#397]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

希望添加试听列表清空功能，或者在设置加个试听列表清空功能选项，对强迫症是一个福音，谢谢
**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
自行看[常见问题](https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)的多选部分
