### ISSUE TITLE
希望在主界面添加一个空格暂停/播放的功能

### ISSUE THREAD

**Issue by ye-hm** [lyswhut/lx-music-desktop#398]
希望在主界面添加一个空格暂停/播放的功能，用起来比较顺手

**Comment by lyswhut** [comment]
你可以设置快捷键达到你的目的

**Comment by ye-hm** [comment]
是啊哈哈哈哈哈，我傻了。感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月26日(星期六) 下午3:58
收件人:&nbsp;"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送:&nbsp;"那么神秘美丽"<122835722@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] 希望在主界面添加一个空格暂停/播放的功能 (#398)





 
你可以设置快捷键达到你的目的
