### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by boatdragon** [lyswhut/lx-music-desktop#400]
1.希望可以添加一个导入其他平台歌单的功能，如果可以实现的话
2.希望可以添加批量操作的功能
3.目前排行榜加载不出来，希望可以修复一下

**Comment by boatdragon** [comment]
补充一下排行榜没问题，是我自己犯傻了😂

**Comment by lyswhut** [comment]
1、在歌单界面可以导入对应平台的歌单
2、批量操作去看软件常见问题

**Comment by boatdragon** [comment]
感谢，问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyswhut"<notifications@github.com&gt;; 
发送时间: 2021年1月3日(星期天) 下午3:13
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;; 
抄送: "2628689562"<2628689562@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lyswhut/lx-music-desktop] 几个小建议 (#400)





 
1、在歌单界面可以导入对应平台的歌单
 2、批量操作去看软件常见问题
