### ISSUE TITLE
桌面歌词无法正常显示

### ISSUE THREAD

**Issue by dzgg001** [lyswhut/lx-music-desktop#401]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

笔记本windows10系统 软件更新了最新版本1.5.0后 软件自带桌面歌词功能无法自动显示且无法开启(点击开启无反应) 之前版本是OK的 然后发现我的台式机windows10上更新1.5.0后也发生了类似问题

**预期行为**

希望能修复桌面歌词功能

**环境：**
  -操作系统及版本：[例如：Windows 10 64位]
  -软件安装包及版本：[例如：Windows 64位安装版 1.5.0]

**Comment by lyswhut** [comment]
我电脑就是win10，桌面歌词是正常的，而且也没见其他人反馈这个问题，这个大概率是你电脑的环境问题，你最后正常的版本是多少？

**Comment by dzgg001** [comment]
> 我电脑就是win10，桌面歌词是正常的，而且也没见其他人反馈这个问题，这个大概率是你电脑的环境问题，你最后正常的版本是多少？

台式的是1803(OS内部版本17134.228)
笔记本是1909(OS内部版本18363.1198)
都已彻底关闭了系统自动更新
笔记本上此灾情尤为严重 点击什么都无法开启桌面歌词…

**Comment by dzgg001** [comment]
> > 我电脑就是win10，桌面歌词是正常的，而且也没见其他人反馈这个问题，这个大概率是你电脑的环境问题，你最后正常的版本是多少？
> 
> 台式的是1803(OS内部版本17134.228)
> 笔记本是1909(OS内部版本18363.1198)
> 都已彻底关闭了系统自动更新
> 笔记本上此灾情尤为严重 点击什么都无法开启桌面歌词…

其中 台式桌面歌词显示方式本身没什么变化 但下方任务栏时不时/偶尔会单独出现一个“桌面歌词显示”任务 如果点击关闭 那桌面歌词也就消失了 原来的版本除了在桌面显示滚动歌词外 是不会出现在任务栏的 其实这个都还好啦 关键是笔记本上的不知为啥死活打不开桌面歌词显示…
