### ISSUE TITLE
请适配apple m1

### ISSUE THREAD

**Issue by yuzhou-xiao** [lyswhut/lx-music-desktop#402]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
这个还需要再等一段时间，
Electron 11起才支持MAC arm64的构建，然而Electron 9以后的版本的透明窗口有问题，需要等他们修复：`https://github.com/electron/electron/issues/25153`

**Comment by yuzhou-xiao** [comment]
electron 11 发布了

**Comment by yuzhou-xiao** [comment]
> 这个还需要再等一段时间，
> Electron 11起才支持MAC arm64的构建，然而Electron 9以后的版本的透明窗口有问题，需要等他们修复：`https://github.com/electron/electron/issues/25153`

11发布了

**Comment by JingleDingDang** [comment]
现在已经支持了吧，我的M1现在能用了，暂时没发现什么问题

**Comment by lyswhut** [comment]
已在v1.10.0开始添加mac arm64位包的构建，但未测试可用性，你可以去发布页面下载测试

**Comment by hot-blood-monkey** [comment]
> 已在v1.10.0开始添加mac arm64位包的构建，但未测试可用性，你可以去发布页面下载测试

为啥我安装 arm64 的，打开显示「“lx-music-desktop”已损坏，无法打开。 您应该将它移到废纸篓。」

**Comment by yanyudalao** [comment]
> 

我的也是，但升级到montery后可以正常使用了。但是建议还是修复一下这个问题。montery对于8G乞丐版的MAC来说非常容易卡，我已经回到11.6.2了。

**Comment by lyswhut** [comment]
安装不了看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#mac-os%E6%97%A0%E6%B3%95%E5%90%AF%E5%8A%A8%E8%BD%AF%E4%BB%B6%E6%8F%90%E7%A4%BA-lx-music-desktop-%E5%B7%B2%E6%8D%9F%E5%9D%8F
