### ISSUE TITLE
我能否用你开源的代码改造为移动端

### ISSUE THREAD

**Issue by lunious** [lyswhut/lx-music-desktop#405]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
随意，但音乐播放链接的获取建议使用其他开源项目的代码
