### ISSUE TITLE
添加当前播放列表，定位当前播放歌曲在当前列表位置

### ISSUE THREAD

**Issue by lgdlkq** [lyswhut/lx-music-desktop#406]
希望能添加右下角类似酷狗等播放器的当前播放歌单等列表显示，点开歌单或当前播放列表时可以直接定位到当前播放的歌曲在列表的哪个位置。

**Comment by lyswhut** [comment]
目前暂不考虑添加当前播放列表的显示，
播放歌曲定位重复：https://github.com/lyswhut/lx-music-desktop/issues/369
