### ISSUE TITLE
搜索结果列表双击不支持播放的歌曲会导致切歌

### ISSUE THREAD

**Issue by MarineKing12** [lyswhut/lx-music-desktop#407]
搜索的搜索的结果双击播放，无论是点哪一首，都是同一首歌放，就是一打开出现的那一首。

**Comment by lyswhut** [comment]
没看懂你这是什么操作

**Comment by HankelBao** [comment]
遇到相同问题：
系统：Linux 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64 GNU/Linux
使用的AppImage安装，版本1.6.0，打开后使用AppImageLauncher做了integration，过后如论尝试播放任何曲目播放列表都不会更新

**Comment by HankelBao** [comment]
@MarineKing12 似乎双击并不能播放所有歌曲，只有带有试听符号的歌曲才是可以播放的

**Comment by lyswhut** [comment]
请说下具体的重现步骤

**Comment by HankelBao** [comment]
举个例子，搜索十年并切换到TX Music的tab，其中所有曲目都只有添加进播放列表一个选项，没有试听选项。

双击于其中（没有试听选项的，在以上的例子中为TX Music中的“十年”）的曲目后，曾经成功播放的曲目会作为替代被播放。此外，似乎lx-music安装后第一次搜索的曲目会永久作为代替的播放曲目。

**Comment by lyswhut** [comment]
若目标源的歌曲不支持播放，双击的行为会变成搜索，若支持播放则会直接播放

**Comment by lyswhut** [comment]
目前存在搜索结果列表双击不支持播放的歌曲会导致切歌的问题，预期的行为是双击不支持播放的歌曲时将不进行任何操作

**Comment by MarineKing12** [comment]
> 目前存在搜索结果列表双击不支持播放的歌曲会导致切歌的问题，预期的行为是双击不支持播放的歌曲时将不进行任何操作
是的，应该是这个问题。都是切最近的一首能播放的。然而我搜索结果都是不能播放的，所以应该都切到同一首歌

**Comment by MarineKing12** [comment]
> 目前存在搜索结果列表双击不支持播放的歌曲会导致切歌的问题，预期的行为是双击不支持播放的歌曲时将不进行任何操作

是的，应该是这个问题。都是切最近的一首能播放的。然而我搜索结果都是不能播放的，所以应该都切到同一首歌

**Comment by lyswhut** [comment]
该问题已在v1.8.0修复
