### ISSUE TITLE
添加QQ音乐的无损下载

### ISSUE THREAD

**Issue by weigaozu** [lyswhut/lx-music-desktop#41]
目前的QQ音乐不能下载无损格式。呵呵。

**Comment by lyswhut** [comment]
接口不支持，有什么问题吗？

**Comment by weigaozu** [comment]
哦，这样啊。QQ音乐上的无损资源还是非常好。能加上吗？呵呵。

**Comment by lyswhut** [comment]
抱歉，我不是接口作者，这不是我说加就加的，软件只是根据接口所支持的源来显示是否能获取响应音质，接口不支持就算我显示可以获取也没用。。。
之前QQ音乐连普通音质都不支持，现在至少支持普通音质的试听，如果想要无损可以去QQ音乐官方播放器下载！
