### ISSUE TITLE
关于接口的问题

### ISSUE THREAD

**Issue by xvzhenduo** [lyswhut/lx-music-desktop#410]
可以看一看http://www.musictool.top/ 和 http://tool.yijingying.com/musictools/ 他们的接口可以用

**Comment by lyswhut** [comment]
这个也是要经过人家接口作者的允许才能调的

**Comment by InoriHimea** [comment]
这种何不直接用软件下载歌曲然后用本地播放器放，不然直接写个脚本拉去二进制流也行哦

**Comment by xvzhenduo** [comment]
谢谢

**Comment by lyswhut** [comment]
已计划添加自定义接口的功能：https://github.com/lyswhut/lx-music-desktop/issues/409
