### ISSUE TITLE
无法下载歌曲

### ISSUE THREAD

**Issue by ZhiboWong** [lyswhut/lx-music-desktop#411]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

请问最新版本1.5版本怎么找不到下载按钮了呀？还不如我之前零点几的版本。原来的版本只能下载标准音质，我以为新版本可以下载高品质音质就更新了，结果新版本更差劲

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**

**Comment by JHeLiu** [comment]
最新版本 下载按钮默认被隐藏，需要去设置里面开启下载功能

**Comment by ZhiboWong** [comment]
已解决。无论是原来的版本还是最新版本，都只能下载普通品质歌曲。祝新年快乐！
