### ISSUE TITLE
建议优化音量，电脑音量在20%，该软件调到2%戴上耳机就很响了

### ISSUE THREAD

**Issue by githuberiex** [lyswhut/lx-music-desktop#412]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
这个还真不懂怎么优化，音量是按百分比来的，想要再小的音量建议直接直接调小电脑的系统声音或者调整声音合成器的声音
