### ISSUE TITLE
1.6版win10播放无声音

### ISSUE THREAD

**Issue by onwingslnz** [lyswhut/lx-music-desktop#413]
1.5版本播放没问题，但是刚刚跟新1.6，播放条显示播放，但是没有声音

**Comment by lyswhut** [comment]
系统版本多少

**Comment by heyblip** [comment]
> 系统版本多少
64位，同没有声音

**Comment by lyswhut** [comment]
详细的系统版本号，打开“运行”输入`winver`的版本号

**Comment by heyblip** [comment]
> 详细的系统版本号，打开“运行”输入`winver`的版本号

笔记本2004(OS内部版本19041.488)

**Comment by xpsu** [comment]
+1，薛定谔的没声音，我甚至以为自己电脑坏了
设备：华为荣耀Magic BookPro 2020 锐龙版
软件版本：1.6.0
系统版本：Win10 20H2 19042.685

**Comment by onwingslnz** [comment]
Windows 10 版本20H2 (OS 內部版本 19042.685）

**Comment by maimengmeng** [comment]
1901 (OS 內部版本 18363.1256）播放无声音

**Comment by lyswhut** [comment]
都是win10的吗。。

**Comment by lyswhut** [comment]
刚发布v1.6.1版本去修复这个问题了，你们更新试下

**Comment by maimengmeng** [comment]
> 刚发布v1.6.1版本去修复这个问题了，你们更新试下

已修复，谢谢！

**Comment by xpsu** [comment]
> 刚发布v1.6.1版本去修复这个问题了，你们更新试下

已修复，感谢~

**Comment by lyswhut** [comment]
从v1.7.0起已修复该问题
