### ISSUE TITLE
是否考虑增加功能：将搜索结果批量加入试听列表

### ISSUE THREAD

**Issue by Minetang** [lyswhut/lx-music-desktop#416]
个人觉得如果想听某一个歌手的全部歌曲，搜索出来还要一首一首的添加进播放列表很麻烦

**Comment by jetwong88** [comment]
可以参考一下网易云的搜索播放逻辑，目前这样的搜索+试听列表的添加规则，是用的有点别扭。搜索出来的歌，有些不一定是我会下次还想听的，但只要播放一次，就增加到现有试听列表中了。可试听列表中的歌，有些是我还想循环听的，但我只需要这些歌存在于试听列表就可以了，并不需要收藏。有些只是搜索的时候听了一下，我还要手动的去试听列表中删除了。

**Comment by Minetang** [comment]
可以转换一下概念：下次还会听的歌就放入我的收藏，试听列表随时可替换或增加歌曲；
在搜索结果页面，增加批量操作和播放全部按钮，这两个按钮操作后直接替换当前试听列表；
若只播放单曲，则按你现有的逻辑将其加入试听列表
具体可参考下图：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 晚上10:25
收件人:&nbsp;"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送:&nbsp;"江山"<908980904@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] 是否考虑增加功能：将搜索结果批量加入试听列表 (#416)





 
可以参考一下网易云的搜索播放逻辑，目前这样的搜索+试听列表的添加规则，是用的有点别扭。搜索出来的歌，有些不一定是我会下次还想听的，但只要播放一次，就增加到现有试听列表中了。可试听列表中的歌，有些是我还想循环听的，但我只需要这些歌存在于试听列表就可以了，并不需要收藏。有些只是搜索的时候听了一下，我还要手动的去试听列表中删除了。

**Comment by lyswhut** [comment]
1、批量添加看常见问题的多选部分；
2、试听列表就只是一个临时列表，想要循环听的可以加到其他列表。
