### ISSUE TITLE
添加删除列表功能

### ISSUE THREAD

**Issue by NingboWang** [lyswhut/lx-music-desktop#417]
只能添加而无法删除某一个列表，感觉这是一个被需要的功能，老大哥能不能考虑考虑添加这个功能
![](https://ftp.bmp.ovh/imgs/2021/01/c505c47eaacf0e13.png)

**Comment by lyswhut** [comment]
右击**自定义列表**可弹出右键菜单进行操作

**Comment by NingboWang** [comment]
哇，我居然没试我自己的，妄想改软件的，太傻了，那你读过消息就把我的issue删了吧，搁这太乱，哈哈
