### ISSUE TITLE
建议添加下一首播放功能。

### ISSUE THREAD

**Issue by ye-hm** [lyswhut/lx-music-desktop#418]
可参考网易云，插到当前播放列表的下一首

**Comment by fantasyx** [comment]
非常不方便，一个转接都不能顺位播放。

**Comment by lyswhut** [comment]
v1.7.0已添加“稍后播放”的功能，可在右键菜单使用

**Comment by ye-hm** [comment]
太有心了，感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 下午2:19
收件人:&nbsp;"lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;;
抄送:&nbsp;"那么神秘美丽"<122835722@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-desktop] 建议添加下一首播放功能。 (#418)





 
v1.7.0已添加“稍后播放”的功能，可在右键菜单使用
