### ISSUE TITLE
看不到“我的收藏”本地播放列表 

### ISSUE THREAD

**Issue by yh6441** [lyswhut/lx-music-desktop#42]
**描述错误**
看不到“我的收藏”本地播放列表 

**预期行为**
可以播放本地音乐

**环境：**
  -操作系统及版本：Windows 10 64位 
  -软件安装包及版本：Windows 64位绿色版 7.0.0]

**Comment by lyswhut** [comment]
怎么看不到？是左侧导航看不到还是无法添加歌曲到收藏列表？
截图看看，0.7.0开始新增我的收藏列表

**Comment by yh6441** [comment]
截图看下面的链接
https://share.weiyun.com/5Ov0mhD

**Comment by lyswhut** [comment]
你理解错了，软件不支持添加本地文件，收藏列表跟试听列表一样，区别是在在线音乐列表点击播放时歌曲会自动添加到试听列表播放，收藏列表需要手动添加歌曲进来
