### ISSUE TITLE
快速切换歌曲时, 会出现播放的歌曲和界面展示的歌曲不一致问题

### ISSUE THREAD

**Issue by HAndy2013** [lyswhut/lx-music-desktop#420]
**重现**
重现行为的步骤：
1.导入歌单到"我的列表"
2.开始播放列表中的歌曲
3.快速点击"下一首"按钮

> ps, 问题并不能100%按照此步骤复现, 但是我在日常使用中, 经常会出现快速切歌时导致的此问题.

**预期行为**
例如歌单中有 
1. a 
2. b 
3. c
4. d

四首歌,  从第一首开始播放, 快速点击下一首到第四首歌, 播放的歌曲和界面展示的应该一致. 
目前出现的情况是: 界面显示的是第四首, 而播放的是第三首歌. 

**环境：**
  -操作系统及版本：Windows 10 Pro 19041.746
  -软件安装包及版本：1.6.1 绿色版

**Comment by lyswhut** [comment]
已在v1.7.0修复该问题
