### ISSUE TITLE
桌面歌词的透明度增加/减小按钮好像实现的功能是反的

### ISSUE THREAD

**Issue by lijunhan0** [lyswhut/lx-music-desktop#421]
桌面歌词的透明度增加/减小按钮好像实现的功能是反的。

**Comment by lyswhut** [comment]
减少透明度歌词将会变亮，增加透明度将会变透明，看起来没毛病啊

**Comment by lijunhan0** [comment]
> 减少透明度歌词将会变亮，增加透明度将会变透明，看起来没毛病啊

感觉传统意义上的增加/减少是指透色彩百分比吧...100%为纯色，0%为透明。

不过如果您认为这样……
