### ISSUE TITLE
希望可以添加桌面歌词自定义字体 颜色 描边等功能

### ISSUE THREAD

**Issue by Garan902** [lyswhut/lx-music-desktop#422]
如题

**Comment by InoriHimea** [comment]
其实我也有这个想法，不过我感觉颜色这玩儿还不如搞卡拉OK歌词，就是qrc还没解开，css3这玩意儿是真的太难写了

**Comment by Garan902** [comment]
还有一个问题就是目前的桌面歌词中文翻译是在原文上面的，不太符合使用习惯（一般翻译在原文下面） 希望可以考虑修改下

**Comment by lyswhut** [comment]
v1.8.0将会对歌词做改进，会将歌词翻译放到原文下面

**Comment by Garan902** [comment]
再补充一个歌词相关的，希望可以把原文和译文同时高亮，目前只有原文高亮

**Comment by lyswhut** [comment]
已在v2.0.0新增
