### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by TonyYhang** [lyswhut/lx-music-desktop#423]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

去掉聚合搜索里的虾米音乐或增加选项是否需要，验证麻烦。。

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
虾米的滑块验证跳转流程改了，下个版本修复

**Comment by lyswhut** [comment]
v1.7.0已修复虾米滑块验证，由于原来的虾米热搜词获取不了了，所以移除了热搜词的加载

**Comment by lyswhut** [comment]
打完那句话突然想起来我只处理了windows、Linux下的滑块验证问题，mac的忘了修🤣

**Comment by lyswhut** [comment]
v1.7.1已修复mac下滑块验证问题
