### ISSUE TITLE
排行榜添加和歌单一样的列表播放功能

### ISSUE THREAD

**Issue by vijay-pj** [lyswhut/lx-music-desktop#424]
目前排行榜列表当中没有播放列表中全部歌曲的功能，如图
![image](https://user-images.githubusercontent.com/31239643/105794437-03644b80-5fc6-11eb-9bd6-bebdbef21332.png)
希望k可以在排行榜的列表中添加和歌单中一样的列表播放的功能，如图
![image](https://user-images.githubusercontent.com/31239643/105794526-28f15500-5fc6-11eb-83ec-31bb7d0a963a.png)

**Comment by chaochunbuaimei** [comment]
的确，很不方便

**Comment by zly49** [comment]
可以Ctrl+A 在右键添加到稍后播放

**Comment by lyswhut** [comment]
v1.10.0起已对排行榜界面添加播放、收藏整个排行榜功能，可以右击排行榜名字后，在弹出的右键菜单中使用。注：收藏、播放存在分页的排行榜时需等待操作完成后才能切换排行榜，不然会导致操作中断。
