### ISSUE TITLE
例如：添加榜单顺序播放功能等

### ISSUE THREAD

**Issue by chaochunbuaimei** [lyswhut/lx-music-desktop#425]
添加榜单顺序播放功能等

**Comment by lyswhut** [comment]
v1.10.0开始可以右击排行榜名字去播放/收藏排行榜列表，但需要注意的是：收藏、播放存在分页的排行榜时需等待操作完成后才能切换排行榜，不然会导致操作中断。

**Comment by beilly** [comment]
建议播放添加右上角更显眼的播放和收藏按钮。
