### ISSUE TITLE
能否提供无损音质下载

### ISSUE THREAD

**Issue by qqsir-dev** [lyswhut/lx-music-desktop#427]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

目前好像只有普通音质下载，能否提供无损音质呢？

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/180
