### ISSUE TITLE
添加歌曲详情界面点击歌名/歌手直接搜索功能

### ISSUE THREAD

**Issue by TonyYhang** [lyswhut/lx-music-desktop#428]
**描述您想要的解决方案**

在歌曲详情界面添加点击歌名/歌手直接进行聚合搜索功能，或者设置歌名/歌手文字为可复制。
![image](https://user-images.githubusercontent.com/74899599/106349984-6bd86300-630d-11eb-81ed-aedff59413d2.png)

**Comment by lyswhut** [comment]
在这里可以点击名字自动复制
![image](https://user-images.githubusercontent.com/20365169/106350284-7136ad00-630f-11eb-8375-85f2e2db35ec.png)

**Comment by TonyYhang** [comment]
啊我这才发现 ฅ(=>_<=)ฅ
