### ISSUE TITLE
<!--桌面歌词不能移动到副屏->

### ISSUE THREAD

**Issue by jswnlinyu** [lyswhut/lx-music-desktop#430]
**描述错误**

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 20h2]
  -软件安装包及版本：[例如：1.6.1 安装版]

**Comment by lyswhut** [comment]
设置的桌面歌词设置有个开关

**Comment by jswnlinyu** [comment]
找到了，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: lyswhut<mailto:notifications@github.com>
发送时间: 2021年1月30日 19:20
收件人: lyswhut/lx-music-desktop<mailto:lx-music-desktop@noreply.github.com>
抄送: Daniel LIN<mailto:jswnlinyu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [lyswhut/lx-music-desktop] <!--桌面歌词不能移动到副屏-> (#430)


设置的桌面歌词设置有个开关

―

**Comment by Misaka-Mikoto-Tech** [comment]
啊，这个限制建议默认关闭
