### ISSUE TITLE
每次搜索歌曲的时候都提示流量异常。

### ISSUE THREAD

**Issue by buyi1net** [lyswhut/lx-music-desktop#431]
Sorry, we have detected unusual traffic from your network.

**Comment by lyswhut** [comment]
可以提供截图看看吗？或者尝试切换网络环境，比如切换到移动网络试试

**Comment by buyi1net** [comment]
后来没有提示这个错误信息了。不知道为啥自己好了。谢谢您的回复！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: lyswhut<mailto:notifications@github.com>
发送时间: 2021年3月6日 22:47
收件人: lyswhut/lx-music-desktop<mailto:lx-music-desktop@noreply.github.com>
抄送: buyi1net<mailto:buyi1net@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [lyswhut/lx-music-desktop] 每次搜索歌曲的时候都提示流量异常。 (#431)


可以提供截图看看吗？或者尝试切换网络环境，比如切换到移动网络试试

―

**Comment by lyswhut** [comment]
那我现在关闭该issue

**Comment by buyi1net** [comment]
辛苦了！

发件人: lyswhut<mailto:notifications@github.com>
发送时间: 2021年3月6日 22:51
收件人: lyswhut/lx-music-desktop<mailto:lx-music-desktop@noreply.github.com>
抄送: buyi1net<mailto:buyi1net@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [lyswhut/lx-music-desktop] 每次搜索歌曲的时候都提示流量异常。 (#431)


那我现在关闭该issue

―
