### ISSUE TITLE
MACBOOK PRO 2019 16" 打开后花屏

### ISSUE THREAD

**Issue by 861** [lyswhut/lx-music-desktop#432]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
花屏

**重现**
打开后，点击左侧第三个按钮后直接花屏

**预期行为**
修复花屏

**截图**
<img width="1018" alt="WX20210131-111705@2x" src="https://user-images.githubusercontent.com/7991297/106392056-e2c93680-63b5-11eb-8ae3-b365e6d42998.png">
**环境：**
  -操作系统及版本：[例如：mac catalina ]
  -软件安装包及版本：[例如：1.7.1 安装版]

**Comment by lyswhut** [comment]
驱动的问题？尝试添加`-dha`参数启动
