### ISSUE TITLE
【添加功能】建议添加音效插件的导入使用功能

### ISSUE THREAD

**Issue by realfan-wing** [lyswhut/lx-music-desktop#434]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
添加一个导入dll音效插件的功能，比如pitchwheel弯音轮插件等等

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
由于软件技术架构的限制，目前导入dll的方式是无法实现的，而且目前不支持设置音效，这是相似的问题：
https://github.com/lyswhut/lx-music-desktop/issues/403
