### ISSUE TITLE
1.7.1版本中音乐可搜索到，但无法试听与下载

### ISSUE THREAD

**Issue by linux0ne-su** [lyswhut/lx-music-desktop#435]
1、为局域网通过代理访问外网
2、http://ts.tempmusic.tk能在浏览器打开，浏览器显示404 Not Found.
3、音乐可以搜索到，但无法试听与下载，换源亦同

有什么需要测试的命令，可随时发送，我随即报送结果
系统为win7 64

**Comment by lyswhut** [comment]
使用代理导致的问题的话可以看：
- https://github.com/lyswhut/lx-music-desktop/issues/5#issuecomment-590387746
- https://github.com/lyswhut/lx-music-desktop/issues/395

**Comment by dufengming2008** [comment]
可以下载哦，要在设置里打开下载功能哦
![image](https://user-images.githubusercontent.com/48039362/107107730-f66d1500-686d-11eb-8980-39f02d455dbc.png)
