### ISSUE TITLE
右击封面无法定位歌曲位置

### ISSUE THREAD

**Issue by lauthrul** [lyswhut/lx-music-desktop#436]
进入歌单，选择某一歌单，点击播放，返回，再进其他页面操作，右击当前播放歌曲封面，无法定位歌曲位置，也无法知道当前播放的是哪个歌单。

**Comment by lyswhut** [comment]
右击封面定位歌曲的功能只对播放“我的列表”里的歌曲时有效

**Comment by lauthrul** [comment]
> 右击封面定位歌曲的功能只对播放“我的列表”里的歌曲时有效

那对于上面描述的这种情况，要怎么知道当前播放的是哪个歌单呢？

**Comment by lyswhut** [comment]
目前无法知道，但你可以点击音量条右边的心添加当前歌曲到我的列表里
