### ISSUE TITLE
ARM32支持&新的启动参数

### ISSUE THREAD

**Issue by 123ABCDF11345** [lyswhut/lx-music-desktop#437]
- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

添加对ARM32的支持（armf)(最好为v7)（现有架构为ARM64)
想在树莓派上实现音乐播放
包的格式无所谓，能跑起来就行
谢谢！

#### 2021-2-4补：
目前想在开机启动时自动运行软件，不用VNC登陆到图形界面，已经实现了一部分，但是软件打开以后没法操作播放，还是需要手动VNC点击播放按钮
```bash
env DISPLAY=:0 /usr/bin/xterm -e /opt/lx-music-desktop/lx-music-desktop
```
希望可以加上一个启动参数，打开自动播放音乐（列表中的）或者自动播放指定歌单的音乐？（这个歌单最好是URL直接获取第三方歌单的，也可以是软件内我收藏的音乐），谢谢！

**Comment by 123ABCDF11345** [comment]
> 1. 下个版本添加对架构deb格式包的构建；`armv7l`
> 2. 播放歌单需要指定源及歌单链接，播放我的列表可以指定列表位置或列表名称，或者你有什么好的想法吗？
>    传参例子：
>    
>    * `./lx-music-desktop -play="source=kw&link=链接、ID"`
>    * `./lx-music-desktop -play="source=myList&index=位置"`
>    * `./lx-music-desktop -play="source=myList&name=名字"`

嗯，这样就可以啦。谢谢！

**Comment by lyswhut** [comment]
等功能加上了再关

**Comment by lyswhut** [comment]
该功能已在v1.8.0新增，使用方法看Readme.md的"启动参数"部分
