### ISSUE TITLE
[功能请求]：增加网易云电台源

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#438]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
增加网易云电台音乐
可以以打开歌单的形式打开电台

**描述您考虑过的替代方案**
也可以新增加菜单栏如“打开电台音乐”

**其他内容**
谢谢大佬👏

**Comment by lyswhut** [comment]
要加这个电台模块的话要么所有源都加，要么都不加，目前不计划单独为一个源新开模块，这个以后再说吧。。。
