### ISSUE TITLE
有没有关闭更新的选项

### ISSUE THREAD

**Issue by syscca** [lyswhut/lx-music-desktop#439]
有没有关闭自动更新的选项
每次打开提示更新，失败。

**Comment by SamLukeYes** [comment]
可以手动安装更新
https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E6%9B%B4%E6%96%B0

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/300
