### ISSUE TITLE
除了音乐文件，还在下到了一些无法删除的乱码文件和文件夹

### ISSUE THREAD

**Issue by jenningszheng** [lyswhut/lx-music-desktop#441]
# 环境
- Win10
- lx-music-desktop-v1.7.1-x86_64

# 遇到的问题
将U盘（也就是截图里的E盘）设置为下载路径，然后逐个下载多个音乐。下着下着，突然U盘内多了很多乱码文件夹和文件，这些文件夹和文件都无法打开，也无法删除，删除时会提示“位置不可用”。

# 我采取的措施
- 虽然很多乱码文件夹和文件无法删除也无法打开，但是已下载好的音乐文件是可以正常播放的。于是我将.mp3文件都移出U盘，并且将U盘格式化，然后所有乱码文件夹和文件都消失了。
- 接着我将软件升级到最新的1.7.1版本。（升级前的版本号忘记了）
- 再次逐个下载多个音乐，然后又发生了同样的问题。

# 问题截图

![QQ20210207-0](https://user-images.githubusercontent.com/26386756/107148924-d124f780-6990-11eb-8ca5-58156e19adc8.png)

**Comment by Danielma0203** [comment]
刷新一下会发生甚么事？

**Comment by jenningszheng** [comment]
> 刷新一下会发生甚么事？

刷新后那些乱码文件夹和文件依然存在，没有任何改变。

**Comment by lyswhut** [comment]
不建议直接下载到U盘，因为U盘的读写速度相对较慢，下载过程中很容易导致I/O被占满，
我这边没有你说的乱码文件，但是批量下载的时候电脑会卡顿，鼠标滑动起来都不顺畅了
