### ISSUE TITLE
歌词显示乱码

### ISSUE THREAD

**Issue by xinjiyier** [lyswhut/lx-music-desktop#443]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
咪咕搜索 the one , 点击播放 那个男人（无损）   The one    我是歌手第三季第十期
![图片](https://user-images.githubusercontent.com/18064887/108585409-5f32b200-7383-11eb-941f-8ddd1fde8835.png)

可以看到歌词显示乱码。

**预期行为**
歌词正常显示

**截图**
![图片](https://user-images.githubusercontent.com/18064887/108585463-b2a50000-7383-11eb-9c1d-2379804155a6.png)
![图片](https://user-images.githubusercontent.com/18064887/108585470-b9337780-7383-11eb-9a2b-9125cfc2893b.png)

**环境：**
  -操作系统及版本:  [Windows 10 64位]
  -软件安装包及版本：[例如：1.7.1 ]

**Comment by lyswhut** [comment]
这首歌的歌词编码问题，正常情况下咪咕的歌词是UTF-8编码，而这首歌的歌词是GBK编码：`http://d.musicapp.migu.cn/prod/file-service/file-down/5374c8e0f2e20a96df952a8b075279ac/de13dd4b1122378133e65793a243d579/062f65b04d78ffacc9bc9e428988d29b`
