### ISSUE TITLE
优化歌词及评论功能

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#444]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
1.在歌曲播完后自动刷新评论以适合下一首歌曲
2.有些歌曲没有歌词、评论、热评，时显示“无歌词/评论/热评”
3.增加字体可选项

**其他内容**
![crash](https://user-images.githubusercontent.com/70054392/108615357-40452600-743e-11eb-93df-57effaa31e0c.gif)
![屏幕截图 2021-02-21 115921](https://user-images.githubusercontent.com/70054392/108615358-40ddbc80-743e-11eb-957f-05d5c73288ef.png)

**Comment by lyswhut** [comment]
1、切歌时不自动刷新评论时故意为之，防止正在看评论时歌曲播放完就自动刷新评论的不好体验，想要刷新评论可以点击上面的刷新按钮刷新
2、正常情况下无评论是应该会显示没有评论的提示，无评论会显示加载失败的问题请反馈是哪个源的哪首歌；
3、歌词字体设置以后再说

**Comment by lyswhut** [comment]
> > 
> 
> 个人建议: 能否把刷新按钮换成"固定"功能, 固定:不自动刷新评论,保持当前歌曲的评论 不固定:刷新到当前歌曲的评论,并且开启自动刷新评论
> 
> 原因在于,想仔细看某首歌的评论情况相对比较少(个人体验) 而每次听到某首歌,想看评论时,都要刷新下,感觉好麻烦(懒)

后面看情况添加
