### ISSUE TITLE
我的列表及相关列表添加全部播放功能

### ISSUE THREAD

**Issue by CCWAY** [lyswhut/lx-music-desktop#446]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
详情看常见问题的“播放整个歌单或排行榜”部分
