### ISSUE TITLE
有手机版本吗

### ISSUE THREAD

**Issue by xiaosh-h** [lyswhut/lx-music-desktop#447]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by Ginnam** [comment]
同问，不过可能是做安卓，ios版本难度太大了吧，作者就一个人光是更新已经很强了

**Comment by Danielma0203** [comment]
这个好像之前作者说过

**Comment by Danielma0203** [comment]
在这#104
