### ISSUE TITLE
请求增加导入用户自己的歌单功能，比如导入QQ音乐和网易云音乐歌单的功能

### ISSUE THREAD

**Issue by yuanmingchen** [lyswhut/lx-music-desktop#45]
**描述您想要的解决方案**
请求增加导入用户自己的歌单功能，比如导入QQ音乐和网易云原因的功能。

**描述您考虑过的替代方案**
比如通过歌单的url导入，或者其他音乐软件那样输入QQ号和网易云音乐的uid就可以一键导入所有歌单的功能。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by lyswhut** [comment]
问题重复：https://github.com/lyswhut/lx-music-desktop/issues/7
后面考虑添加，若有问题请到上面issue讨论！
