### ISSUE TITLE
双击歌曲名称无法播放或切歌

### ISSUE THREAD

**Issue by tjubuntu** [lyswhut/lx-music-desktop#450]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

在下载界面，双击歌名无法播放

**重现**
重现行为的步骤：
1.转到“下载”
2.双击“歌曲名”列中的任意一首歌的名字，无法正常播放或者切换正在播放的歌曲

**预期行为**

双击歌名可以正常切歌或启动播放当前歌曲

**截图**

![image](https://user-images.githubusercontent.com/5626367/109242801-c1256880-7816-11eb-88fe-ba5d7161e30d.png)

**环境：**
  -操作系统及版本：Windows 10企业版 64位 19042.804
  -软件安装包及版本：1.7.1 

**其他内容**

**Comment by lyswhut** [comment]
可选中文本的区域双击不应该播放，这是正常行为，想要双击播放需在不可选中文本的区域双击
