### ISSUE TITLE
obs在采集桌面歌词窗口时为空，希望能够使其能够被采集

### ISSUE THREAD

**Issue by QJZX** [lyswhut/lx-music-desktop#451]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

桌面歌词的窗口感觉很精美，想直播时营造个不错的效果层，但obs采集时为空白窗口。

**描述您考虑过的替代方案**

本想看看是不是vue的机制导致的无解bug，然而半天也没参透vue，(￣_￣|||)
想请教一下，是不是因为vue透明窗口而导致采集失败。

**其他内容**

如果不是vue的bug，希望能在下个版本使其能被采集

**Comment by lyswhut** [comment]
我下载了你说的软件试了下，确实捕获不了桌面歌词，不过可以你将这个属性设置为`false`即可成功捕获，这个属性的作用是控制桌面歌词窗口的标题是否在任务栏显示：
https://github.com/lyswhut/lx-music-desktop/blob/51964e51c6b0e88213d9552f7b5e6c69454d8ccb/src/main/modules/winLyric/index.js#L110
