### ISSUE TITLE
软件打开出现黑边，歌词出现黑影

### ISSUE THREAD

**Issue by JankingHuang** [lyswhut/lx-music-desktop#452]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
软件打开出现黑边，歌词出现黑影

**截图**

![image](https://user-images.githubusercontent.com/47512530/109625257-109ec800-7b7a-11eb-95ba-d5e2cc62a54b.png)

**环境：**
  -操作系统及版本：Linux openSUSE Leap 15.2 x86_64 
  -软件安装包及版本：1.7.1 安装版

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/371

**Comment by JankingHuang** [comment]
```bash
 lx-music-desktop -dt 
18:04:34.633 › App starting...
Gtk-Message: 18:04:34.710: Failed to load module "appmenu-gtk-module"
init
18:04:35.163 › Checking for update
18:04:35.164 › Checking for update...
18:04:35.251 › Error: Error: ENOENT: no such file or directory, open '/opt/lx-music-desktop/resources/app-update.yml'
18:04:35.253 › Error in auto-updater.
Unhandled Rejection at: Promise  Promise {
  <rejected> [Error: ENOENT: no such file or directory, open '/opt/lx-music-desktop/resources/app-update.yml'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/opt/lx-music-desktop/resources/app-update.yml'
  }
}
 reason:  [Error: ENOENT: no such file or directory, open '/opt/lx-music-desktop/resources/app-update.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/lx-music-desktop/resources/app-update.yml'
}
18:04:35.257 › Error: ENOENT: no such file or directory, open '/opt/lx-music-desktop/resources/app-update.yml'
```
`-dha` 和`-dt`都无法解决歌词显示的问题，但是软件黑边没有了。
![image](https://user-images.githubusercontent.com/47512530/109632473-0a144e80-7b82-11eb-89b0-23a65be9eb38.png)

**Comment by lyswhut** [comment]
Linux的话建议优先尝试使用`-dha`运行，若无效再尝试使用`-dt`，
`-dt`仅用于解决主窗口的黑边问题，对桌面窗口无效
详情看常见问题的`Linux 系统下桌面歌词窗口异常`说明去解决，若还是无法解决那我爱莫能助

**Comment by JankingHuang** [comment]
谢谢
