### ISSUE TITLE
音乐收藏图标

### ISSUE THREAD

**Issue by UncleBrown** [lyswhut/lx-music-desktop#455]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.播放任意歌曲
2.点击播放栏中收藏按钮（爱心图标）
3.显示收藏成功，但是图标与未收藏一致，无法区分

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[  MBP Mojave 10.14.6 ]
  -软件安装包及版本：[ LX 1.7.1 ]

**其他内容**

**Comment by lyswhut** [comment]
那个按钮其实是歌曲添加按钮，是为了将当前播放的歌曲添加到我的列表中，不是“收藏列表”专用的，不过可以添加一个当前歌曲是否已在列表中的状态：
![image](https://user-images.githubusercontent.com/20365169/110209933-2db0ff00-7eca-11eb-8a52-b6e3825b3618.png)
若歌曲已在列表中则列表名变灰色，不能再添加

**Comment by lyswhut** [comment]
作为代替解决方案，已在v1.8.0对歌曲添加弹窗内的歌曲列表显示进行优化，若当前歌曲已在列表中则列表名不可点击
