### ISSUE TITLE
添加歌词保存格式为ANSI编码格式

### ISSUE THREAD

**Issue by TomLiu-GitHub** [lyswhut/lx-music-desktop#456]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

下载的歌词在部分车载安卓系统中出现中文乱码

**描述您考虑过的替代方案**

下载保存歌词时将格式改为ansi

**其他内容**

**Comment by lyswhut** [comment]
ANSI编码是ASCII的扩展，在不同的语言环境下显示的内容将会不一样（即乱码），在ANSI编码下中文将使用GBK编码格式，所以你想要歌词支持保存为GBK编码格式吗？

**Comment by TomLiu-GitHub** [comment]
感谢回复
ansi的中文是不是gbk我不在这里争辩,
结果是utf8在车载安卓系统中乱码,另存为ansi格式的不会乱码

**Comment by TomLiu-GitHub** [comment]
![Uploading image.png…]()

**Comment by TomLiu-GitHub** [comment]
![image](https://user-images.githubusercontent.com/32833966/110227878-b5812280-7f37-11eb-9c4c-72c8e3608a4a.png)

**Comment by lyswhut** [comment]
你可以试下转成GBK能不能用，中文的ANSI一般就是GBK格式存的

**Comment by TomLiu-GitHub** [comment]
存gbk也会乱码的,歌词不仅有中文,还有英文,日文,韩文.只有存ansi可以

**Comment by lyswhut** [comment]
如果确实要保存特定的编码格式的话，将会使用[iconv-lite](https://github.com/ashtuchkin/iconv-lite)去转码，这是它支持的转码格式：
https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

**Comment by TomLiu-GitHub** [comment]
经过测试,车载设备只支持ansi格式,设置utf8也是乱码,另存为ansi编码的显示正常

**Comment by lyswhut** [comment]
你试下 GB2312、GBK，按理说是可以的：

> 在简体中文Windows操作系统中，ANSI 编码代表 GBK 编码；在英文Windows操作系统中，ANSI 编码代表 ASCII编码；在繁体中文Windows操作系统中，ANSI编码代表Big5；在日文Windows操作系统中，ANSI 编码代表 Shift_JIS 编码。

引用自：<https://blog.csdn.net/BlackPlus28/article/details/82793659>

> 2.默认情况下，Window记事本默认编码为ANSI(汉字表示即为GBK编码，0~127号下GBK编码与ANSI编码一样)。

引用自：<https://blog.csdn.net/fengdl123/article/details/52059393>

**Comment by lyswhut** [comment]
@TomLiu-GitHub 你试试这个文件，把这个文件的后缀名改成`lrc`，随便找一首歌的歌词替换成这个它，然后放到车机上看看正不正常：
[不该用情 - 大笨.txt](https://github.com/lyswhut/lx-music-desktop/files/7028501/-.txt)

**Comment by lyswhut** [comment]
可以在设置选择以GBK格式存储
