### ISSUE TITLE
漫步者蓝牙耳机线控冲突导致耳机直接关机

### ISSUE THREAD

**Issue by soysaucemo** [lyswhut/lx-music-desktop#457]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

使用漫步者EDIFER W200BT经典版 蓝牙耳机，连接笔记本蓝牙播放音乐，在开启 洛雪音乐 时，蓝牙耳机直接关机（正常关机会报语音“关机”，这种情况不会有任何提示）

**重现**
重现行为的步骤：
1.笔记本（magicbook 2019AMD版+win10pro 1909）连接EDIFER W200BT经典版 蓝牙耳机（据了解不少漫步者蓝牙耳机都有类似情况）
2.开启“洛雪音乐”软件，播放音乐，或 切换歌曲，或其他音量等动作（与蓝牙耳机自动线控相关）
3.此时蓝牙耳机直接关机，无任何提示
4.重新开启蓝牙耳机，连接笔记本后，继续播放，会再次自动关机

**预期行为**

提供临时关闭高级媒体控制线控的选项，比如新增一个启动参数“-hmkh”，加载如下参数
`if (global.envParams.cmdParams.hmkh) app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling')`
我关闭后，暂时只发现无法通过蓝牙耳机控制播放状态（暂停/开始）这个影响，其他软件操作正常

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18363.1379]
  -软件安装包及版本：[例如：1.8.0 绿色版]

**其他内容**

1. 依据之前确认的情况，疑似(漫步者)蓝牙耳机与chrome系列内核的冲突，如chrome浏览器、edge新版浏览器等都会出现类似情况（网页有媒体播放时触发蓝牙耳机关机），可参考zhihu问答如下：
https://www.zhihu.com/question/361141859
2. 针对浏览器的规避方法是在flags页面关闭Hardware Media Key Handling
![屏幕截图 2021-03-07 141257](https://user-images.githubusercontent.com/34964159/110230919-41527900-7f4f-11eb-9b2f-9a8169c617a2.png)
3. 针对electron编写的程序，建议在ready之前加载如下参数关闭对应功能：
`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling')`
参考 #https://github.com/electron/electron/issues/18253#issuecomment-589542934
4. 建议将例外运行参数放在软件的设置菜单内，减少用户操作难度

**Comment by lyswhut** [comment]
我使用漫步者W3去测试，蓝牙切歌、加减音量都没问题，
如果只是漫步者这个品牌的部分型号耳机这样的话，可以考虑添加该设置你说的这个启动参数，并在FAQ记录解决方案，
因为用的少，就不在设置界面新增设置项了

**Comment by soysaucemo** [comment]
> 我使用漫步者W3去测试，蓝牙切歌、加减音量都没问题，
> 如果只是漫步者这个品牌的部分型号耳机这样的话，可以考虑添加你说的这个启动参数，并在FAQ记录解决方案，
> 因为用得少，就不在设置界面新增设置项了

了解~~我有几个蓝牙耳机，另外那个杂牌的（pdd几块钱的）都没事，就edifer这个w200bt有存在这个坑爹的问题，还真可能是特别型号才有的问题。
配置这个其实是有朋友（不熟悉带参数运行的概念）操作起来不方便，我看看自己直接硬编码一个给他吧~

**Comment by lyswhut** [comment]
因为我这边无法重现问题，你确定只要加`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling')`就可以了吗？

**Comment by lyswhut** [comment]
我刚试了下，添加`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling')`对耳机并无影响，切歌、播放暂停都没问题（前面说的加减音量是搞错了，并没有加减音量。。。）

**Comment by soysaucemo** [comment]
> 我刚试了下，添加`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling')`对耳机并无影响，切歌、播放暂停都没问题（前面说的加减音量是搞错了，并没有加减音量。。。）

今天下午gayhub卡爆了。。。
我录屏了一下，before是1.8.0的原版运行，开始蓝牙连接正常，一点播放耳机直接关机，但是电脑没发现（估计还没刷新），一直向w200bt耳机输出，然后过了10s左右反应过来，切换为笔记本自带音箱输出，win10的蓝牙设置也显示为断开状态。

https://user-images.githubusercontent.com/34964159/110237481-475c5000-7f77-11eb-9709-f7d9388806d3.mp4

after是我自己添加上面的参数后运行的情况，期间蓝牙耳机一直正常连接

https://user-images.githubusercontent.com/34964159/110237480-43c8c900-7f77-11eb-8b29-d6d77dab882e.mp4

**Comment by lyswhut** [comment]
下个版本新增启动参数`-dhmkh`，此参数将禁用Chromium的Hardware Media Key Handling特性，用于解决漫步者部分型号耳机与本程序冲突导致耳机意外关机的问题

**Comment by lyswhut** [comment]
已在v1.9.0添加`-dhmkh`启动参数

**Comment by RobertChou** [comment]
> 已在v1.9.0添加`-dhmkh`启动参数

请问这个参数是已经默认添加了吗，还是在设置里有选项，我也是漫步者耳机，遇到相同问题，现在用的落雪最新版

**Comment by lyswhut** [comment]
默认不会添加，需要自己在快捷方式添加此参数，然后用此快捷方式启动软件就行了
