### ISSUE TITLE
请求增加仅下载歌词的功能

### ISSUE THREAD

**Issue by yuanmingchen** [lyswhut/lx-music-desktop#46]
**描述您想要的解决方案**
请求增加仅下载歌词的功能，因为有的时候已经下载了歌曲，只想下载歌词，但是还是要与歌曲一起下载才行，比较慢，还会占用服务器的网络资源。

**描述您考虑过的替代方案**
右键增加仅仅 下载歌词功能，或者在 点击下载弹出的选项框里增加一项，除了不同音质的选项以外，再增加一个仅下载歌词。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by lyswhut** [comment]
直接重新下吧。。
只单独下歌词的需求不多。。
