### ISSUE TITLE
添加开机自启功能

### ISSUE THREAD

**Issue by 905407220** [lyswhut/lx-music-desktop#461]
**解决方案检查**

- [x]我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
-[x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

开机自启动功能

**描述您考虑过的替代方案**

开机自启动功能

**其他内容**

开机自启动功能

**Comment by lyswhut** [comment]
你可以百度“开机启动设置”来设置软件开机启动
