### ISSUE TITLE
Window10 更新无法自动安装

### ISSUE THREAD

**Issue by ooo-o-ooo** [lyswhut/lx-music-desktop#462]
**解决方案检查**

- [x ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
window10 无法自动安装更新

**重现**
重现行为的步骤：
点击在线更新，更新之后程序下载到本地磁盘，同时删除本地文件

但是无法安装。
导致需要手动安装

**预期行为**
正常安装

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]

**Comment by Danielma0203** [comment]
+1
在线下载成功，后来我授予了一个“……uninstall……”(具体记不清了)的管理员权限，
结果不但新的没装上，反而把旧的1.8.1给卸载了XD

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/196

建议安装在当前用户目录，不要为所有用户安装，
或者安装在不需要管理员权限的目录

**Comment by Tim-Paik** [comment]
可否检测到安装在需要管理员权限的目录时提权？
要不然直接终止更新
要不然点一下自动更新反而软件没了也挺奇怪XD
（PS：lx真好用

**Comment by lyswhut** [comment]
> 可否检测到安装在需要管理员权限的目录时提权？

考虑到部分人在没有管理员权限的环境下运行的情况，现在发布的都是用户版的安装包，没有发布管理员版的，管理员版的安装包每次安装都要求获取管理员权限，现在安装包的版本也太多了，不想再分别编译管理员版与用户版了。
