### ISSUE TITLE
增加深色模式(与系统深色模式联动)

### ISSUE THREAD

**Issue by jing-cim** [lyswhut/lx-music-desktop#463]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/350
