### ISSUE TITLE
【已解决】能够播放音乐但是没有出现下载的标志（箭头）

### ISSUE THREAD

**Issue by oakspell** [lyswhut/lx-music-desktop#464]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ 歌单界面”
2.点击“ 歌曲”
3.向下滚动到“ 歌单底部”
4.看到错误

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[Windows 10 64位 18362.156]
  -软件安装包及版本：[1.8.2 安装版]

**其他内容**

**Comment by Randonyld** [comment]
请问怎么解决的

**Comment by oakspell** [comment]
软件默认下载功能是关闭的，需要自行在设置里开启下载

**Comment by Randonyld** [comment]
> 软件默认下载功能是关闭的，需要自行在设置里开启下载

谢谢
