### ISSUE TITLE
搜索评书的时候，返回结果不是按顺序返回的

### ISSUE THREAD

**Issue by Killea** [lyswhut/lx-music-desktop#466]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

问题就是搜索评书的时候，返回结果不是按顺序返回的，如果能返回所有结果后排序显示就比较完美了。
![image](https://user-images.githubusercontent.com/5551824/111526260-e5e56f80-8734-11eb-89fb-4aef4460e97d.png)

**重现**
重现行为的步骤：
直接搜索大明演义，如图

**预期行为**

**截图**

**环境：**
  -操作系统及版本：ubuntu 20+
  -软件安装包及版本：1.8.2

**其他内容**
想要搜索‘大明演绎00’， 搜素结果完全不沾边。

**Comment by lyswhut** [comment]
除了聚合搜索以外，单个源的搜索是没有对搜索结果进行重新排序的，这个顺序就是音乐平台返回的顺序，这个问题与软件无关
