### ISSUE TITLE
歌词读取问题

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#469]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

几首歌曲出现歌词错误的情况。
出现与#445中格式相近的，用中括号括起来的数据。

**重现**
以这首金曲为例：网易源的Never Gonna Give You Up - Rick Astley
1.打开歌曲页面
2.向下滚动到底部
![image](https://user-images.githubusercontent.com/70054392/111864197-84bed580-899a-11eb-8f6d-41d084430b3e.png)
3.看到错误

歌曲详情页：
https://music.163.com/#/song?id=18520488   （gayhub叕卡了，上传不了图片

**预期行为**
正常显示歌词

**环境：**
软件安装包及版本：win 1.8.2安装版

**Comment by lyswhut** [comment]
我这边没有这个问题哦，你尝试下删除这首歌重新搜索添加看看还会不会这样？
![image](https://user-images.githubusercontent.com/20365169/111865196-868b9780-89a0-11eb-9fe3-b4b34dee03c6.png)

**Comment by Danielma0203** [comment]
不会了！（薛定谔的歌词
不过不太稳定
