### ISSUE TITLE
QQ音乐的热门排行榜切换不了页面，一直在第一页~

### ISSUE THREAD

**Issue by demonlzxgg** [lyswhut/lx-music-desktop#47]
**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by demonlzxgg** [comment]
写错了，是歌单列表切换不了   点了其他页码还是显示第一页的歌单~

**Comment by lyswhut** [comment]
谢谢反馈！
将在下个版本修复！

**Comment by lyswhut** [comment]
该问题已在0.8.0中修复
