### ISSUE TITLE
现在不能导入其它平台的歌单吗

### ISSUE THREAD

**Issue by Skyline5723** [lyswhut/lx-music-desktop#471]
现在不能导入其它平台的歌单吗

**Comment by ZerOri** [comment]
好像是不行……找了一番没发现这个功能，只能导入软件备份的歌单，这就有点尴尬了

**Comment by boatdragon** [comment]
可以导入啊，在歌单界面，你选择哪个平台就会有哪个平台的导入选项卡

**Comment by JingleDingDang** [comment]
企鹅音乐平台歌单今天没导入成功 https://y.qq.com/n/yqq/album/003x3ARJ2XHUDx.html

**Comment by lyswhut** [comment]
歌单导入问题在常见问题也有记录
