### ISSUE TITLE
可以加一个 arm版本的Windows包吗

### ISSUE THREAD

**Issue by songtao1873** [lyswhut/lx-music-desktop#473]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
请求添加 arm64版本的 Windows安装包

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
下个版本添加Windows arm64位免安装版的构建

**Comment by songtao1873** [comment]
> **解决方案检查**
> 
> * [ ]  我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)
> * [ ]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=))
> 
> **描述您想要的解决方案**
> 请求添加 arm64版本的 Windows安装包
> 
> **描述您考虑过的替代方案**
> 
> **其他内容**

**Comment by lyswhut** [comment]
已在v1.9.0添加Windows arm64位免安装版的构建

**Comment by songtao1873** [comment]
请求添加arm64 exe安装包的构建, 以方便添加使用winget 为arm64架构命令行安装的支持, 可以不添加自动更新程序, 谢谢

**Comment by lyswhut** [comment]
不是已经加了吗？

**Comment by songtao1873** [comment]
release里面只有7z免安装包, winget暂时不支持这种安装方式, 不过很多人star了 standalone的issue, 官方没有正面回复, 所以现阶段想支持应该还得需要exe安装包

**Comment by lyswhut** [comment]
你是想要安装版的包啊😅，那我下个版本再添加win arm安装版的构建吧。。

**Comment by songtao1873** [comment]
> 你是想要安装版的包啊😅，那我下个版本再添加win arm安装版的构建吧。。

哈哈,非常感谢

**Comment by lyswhut** [comment]
win arm64位安装版已在v1.11.0开始添加构建，但是忘了禁用自动更新了。。。

**Comment by songtao1873** [comment]
好的, 谢谢.
