### ISSUE TITLE
关于相关api的支持

### ISSUE THREAD

**Issue by AdorableParker** [lyswhut/lx-music-desktop#474]
我正在实现一个点歌项目，需要能够获取到QQ音乐平台的歌曲文件的地址(短期内能播放就行的那种)
> 类似于`http://ws6.stream.qqmusic.qq.com/C4000031D9ua0bJxN2.m4a?guid=1616931721&vkey=720F691106B3411D955DFB96BF4C188A0FA278C550CF44078506FAD555F7E2EDCAEBAB465D569E73D4C97FF2DA59354BD97D7220107E647D`

折腾了半天解决不了vkey和guid两个值的获取
能指导一下您这个项目的相关处理方式作为参考吗

**Comment by lyswhut** [comment]
抱歉，软件使用的是第三方API接口，我无法为你解答该问题
