### ISSUE TITLE
歌单增加“播放全部”按钮

### ISSUE THREAD

**Issue by yikexiaoyao** [lyswhut/lx-music-desktop#48]
作者您好，冒昧打扰，我想提一个功能建议，希望增加“全部播放”按钮，这样功能会更人性化，不然要手动添加比较麻烦，希望您能解决一下，非常感谢，在此表达敬意，我们会一直支持您，再次感谢

**Comment by yikexiaoyao** [comment]
您好，冒昧打扰，我想问一下为什么音乐播放没有记忆缓存功能，试听列表音乐播放没有缓存记忆功能，下次重启软件无法继续播放，只能从头再来，希望帮忙改进，非常感谢，辛苦了

**Comment by lyswhut** [comment]
软件技术架构原因，我无法控制歌曲缓存，想要离线听可以进行下载

**Comment by yikexiaoyao** [comment]
好的，非常感谢

**Comment by lyswhut** [comment]
@yikexiaoyao 我发现在歌单加入播放/添加全部按钮意义不大，完全可以**全选**后添加或播放，而且歌单内的歌曲一般没有第二页，第一页就把所有歌曲显示完
