### ISSUE TITLE
网易云音乐歌单貌似又无法解析了

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#480]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

小蜗歌单无法解析

**重现**
重现行为的步骤：
1.转到“ 歌单”侧边按钮
2.点击“右上角，切回到小蜗音乐”
3.点击打开小蜗音乐歌单
4.输入任意云歌单链接:https://music.163.com/playlist?id=5480619834
5."列表加载中"，之后就一直加载不出来

**预期行为**

正常加载

**截图**

![image](https://user-images.githubusercontent.com/20263103/114330519-79fbf880-9b74-11eb-84b9-e8d7bf2e922c.png)

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 19042.906]
  -软件安装包及版本：[1.8.2 安装版]

**Comment by lyswhut** [comment]
你那边的网络问题吧，我这边可以正常打开
![image](https://user-images.githubusercontent.com/20365169/114690573-6a81d880-9d49-11eb-9ccf-f53c11da9033.png)

**Comment by ameaninglessname** [comment]
我不清楚遇到了什么问题,这边依然无法打开,
请问有没有日志什么的可以帮助我排查问题?

**Comment by xfdj** [comment]
试试用小芸歌单打开

**Comment by ameaninglessname** [comment]
> 
> 
> 试试用小芸歌单打开

这个可以打开！ @lyswhut 这是bug么

**Comment by ameaninglessname** [comment]
> 
> 
> 试试用小芸歌单打开

谢谢！这个可以打开了。所以是我弄混了？
那小蜗是啥播放器？

**Comment by jiurou** [comment]
> > 试试用小芸歌单打开
> 
> 谢谢！这个可以打开了。所以是我弄混了？
> 那小蜗是啥播放器？

设置里能显示原名

**Comment by ameaninglessname** [comment]
> 
> 
> > > 试试用小芸歌单打开
> > 
> > 
> > 谢谢！这个可以打开了。所以是我弄混了？
> > 那小蜗是啥播放器？
> 
> 设置里能显示原名

谢谢，打扰了，是我弄错歌单入口了
