### ISSUE TITLE
可以添加一个每日推荐的功能吗？

### ISSUE THREAD

**Issue by Yu-Xiao-Sheng** [lyswhut/lx-music-desktop#481]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

比如说根据我最近喜欢的风格，然后去每天推荐类似风格的音乐。

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
音乐平台的推荐功能是根据你听的歌曲去推荐歌曲，但洛雪不会记录你的听歌记录，所以该功能目前不考虑添加
