### ISSUE TITLE
抖音热歌榜请求支持顺序播报

### ISSUE THREAD

**Issue by yaoyuanyy** [lyswhut/lx-music-desktop#482]
每次听抖音热歌榜，试听第一首后播放的下一首不是抖音热歌榜的第二首歌曲，而是其他的歌曲。
诉求：抖音热歌榜选择第一首后，自动从上到下的播放整个榜单列表

**Comment by 1502541503** [comment]
对 这个问题很严重  老是听着听着就没歌了

**Comment by lyswhut** [comment]
v1.10.0开始可以右击排行榜名字去播放/收藏排行榜列表，但需要注意的是：收藏、播放存在分页的排行榜时需等待操作完成后才能切换排行榜，不然会导致操作中断。
