### ISSUE TITLE
可以开发安卓的客户端吗？

### ISSUE THREAD

**Issue by dawn-cgj** [lyswhut/lx-music-desktop#490]
现在安卓端好几个APP，但是版权各不同，经常往返于几个app之间。
如果能够开发一个集成各平台版权的客户端就好了

**Comment by 1103409364** [comment]
> 现在安卓端好几个APP，但是版权各不同，经常往返于几个app之间。
> 如果能够开发一个集成各平台版权的客户端就好了

安卓应该有的，你找找看，找到了告诉我。我知道一个歌词适配.apk 下歌还可以

**Comment by lyswhut** [comment]
项目链接：https://github.com/lyswhut/lx-music-mobile
