### ISSUE TITLE
收藏歌单内歌曲下载全部歌曲

### ISSUE THREAD

**Issue by Snoopy008** [lyswhut/lx-music-desktop#493]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
 在收藏歌单页面添加全部下载按钮，现在想要下载歌曲只能一首一首点击下载按钮，希望能增加批量下载的功能 

**描述您考虑过的替代方案**
 在我的收藏列表右击收藏的歌单名称弹出选项列表，选项列表添加下载全部歌曲功能 

**其他内容**

**Comment by Snoopy008** [comment]
从v0.18.0起，列表多选需要键盘配合，想要多选前需按下Shift或Ctrl键然后再鼠标点击想要选中的内容即可触发多选机制，其中Shift键用于连续选择，Ctrl键用于不连续选择，Ctrl+a用于快速全选。

例子一：想要选中1-5项，则先按下Shift键后，鼠标点击第一项，再点击第五项即可完成选择；
例子二：想要选中1项与第3项，则先按下Ctrl键后，鼠标点击第一项，再点击第三项即可完成选择；
例子三：想要选中当前列表的全部内容，键盘先按下Ctrl键不放，然后按a键，即可完成选择。
用Shift或Ctrl选择时，鼠标点击未选中的内容会将其选中，点击已选择的内容会将其取消选择，若想全部取消选择，在不按Shift或Alt键的情况下，随意点击列表里的一项内容即可全部取消选择。(P.S：Ctrl键对应Mac OS上的Command键)

注：选完后可用鼠标右击弹出右键菜单操作已选的内容

Mac command+A 全选，然后command不松右击列表选择下载即可

**Comment by RamboPan** [comment]
> 从v0.18.0起，列表多选需要键盘配合，想要多选前需按下Shift或Ctrl键然后再鼠标点击想要选中的内容即可触发多选机制，其中Shift键用于连续选择，Ctrl键用于不连续选择，Ctrl+a用于快速全选。
> 
> 例子一：想要选中1-5项，则先按下Shift键后，鼠标点击第一项，再点击第五项即可完成选择； 例子二：想要选中1项与第3项，则先按下Ctrl键后，鼠标点击第一项，再点击第三项即可完成选择； 例子三：想要选中当前列表的全部内容，键盘先按下Ctrl键不放，然后按a键，即可完成选择。 用Shift或Ctrl选择时，鼠标点击未选中的内容会将其选中，点击已选择的内容会将其取消选择，若想全部取消选择，在不按Shift或Alt键的情况下，随意点击列表里的一项内容即可全部取消选择。(P.S：Ctrl键对应Mac OS上的Command键)
> 
> 注：选完后可用鼠标右击弹出右键菜单操作已选的内容
> 
> Mac command+A 全选，然后command不松右击列表选择下载即可

感谢这个回答，我还说看 faq ，没有明白怎么进入多选模式。
