### ISSUE TITLE
锁定歌词之后必须从软件设置界面解锁，希望锁定歌词后鼠标移到歌词上能有按钮解除锁定

### ISSUE THREAD

**Issue by isszk** [lyswhut/lx-music-desktop#494]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
桌面锁定后，你可以右击托盘菜单来解锁，或者设置全局快捷键解锁（v1.9.0的桌面歌词全局快捷键失效，下个版本修复）
