### ISSUE TITLE
排行榜

### ISSUE THREAD

**Issue by 95579580** [lyswhut/lx-music-desktop#496]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
v1.10.0开始可以右击排行榜名字去播放/收藏排行榜列表，但需要注意的是：收藏、播放存在分页的排行榜时需等待操作完成后才能切换排行榜，不然会导致操作中断。
