### ISSUE TITLE
添加歌单的功能

### ISSUE THREAD

**Issue by liao6964799** [lyswhut/lx-music-desktop#50]
本人原先使用酷我音乐，有一个自己的歌单，不知道该如何导入到该软件里！ 我知道有另外一个软件是通过搜索歌单的网址，然后就可以实现添加歌单里的歌曲，好像目前这个软件还没有这功能吧？

**Comment by liao6964799** [comment]
我尝试在搜索框 输入 歌单网址  啥都没有，增加一个这功能吧，实用！

**Comment by lyswhut** [comment]
问题重复：https://github.com/lyswhut/lx-music-desktop/issues/7
后面会添加该功能，我现在关闭本issue
