### ISSUE TITLE
搜索栏闪动

### ISSUE THREAD

**Issue by xinggsf** [lyswhut/lx-music-desktop#500]
软件刚启动时，经常定位不到搜索栏，表现为移动到搜索栏后整个窗口隐藏；
另外，在歌曲列表和搜索栏移动鼠标，窗口闪动

上述问题存在已经好几个版本

win7-x64、win8-x64都有如此表现

**Comment by lyswhut** [comment]
看常见问题 界面异常（界面显示不完整） 部分解决
