### ISSUE TITLE
搜索的时候希望,能搜索歌单

### ISSUE THREAD

**Issue by xiao-baiY** [lyswhut/lx-music-desktop#501]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
已在v2.0.0新增
