### ISSUE TITLE
歌词在多显示屏的情况下拖拽歌词界面不能从显示屏1拖到显示屏2

### ISSUE THREAD

**Issue by paiguFK** [lyswhut/lx-music-desktop#502]
**解决方案检查**
检查了没有类似问题

**描述错误**
多个显示屏不能把歌词拖到另一个显示器上

**重现**
重现行为的步骤：
显示歌词
从显示器1拖拽到显示器2,
发现歌词界面就靠在显示器1的边缘上

**预期行为**
可以拖过去

**截图**
无

**环境：**
  -操作系统及版本：[Windows 10 64位 专业版]
  -软件安装包及版本：[1.9.0-安装版]

**其他内容**
无

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/281
