### ISSUE TITLE
添加功能：播放搜索出来的列表

### ISSUE THREAD

**Issue by Xm17** [lyswhut/lx-music-desktop#503]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
比如我现在搜索凤凰传奇
![image](https://user-images.githubusercontent.com/27048404/118129542-e47fad00-b42e-11eb-9870-7afaeba9298b.png)
我点击下一首ji就变成我自己的歌曲 不是列表中的下一首，能不能修改为播放搜索列表的

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
需要将歌曲添加到“我的列表”才能播放，详情看常见问题播放整个排行榜或歌单部分
