### ISSUE TITLE
[报告BUG]不稳定音频及无法下载

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#504]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

1.   有时歌曲出现“该歌曲没有可播放的音频”字样，
接着重新尝试播放后又可以播放。
![image](https://user-images.githubusercontent.com/70054392/118343582-805b0700-b55c-11eb-8b77-bbedb7134bc6.png)

2.   这些重新播放的歌曲下载选项出现问题（如下图
![image](https://user-images.githubusercontent.com/70054392/118343697-f19aba00-b55c-11eb-85c7-4abfc31183e8.png)

**重现**
重现行为的步骤：
由于音频不稳定，有时不会出现错误
1.此处选用 网易源“GOODRAGE (Long.ver) - EBIMAYO”
   https://music.163.com/#/song?id=1356124893
2.禁用歌曲循环
3.尝试，可能出现错误
4.若未出现错误，转到设置清理列表缓存，重做第三步
  如果一直未出现，您还可以尝试其他网易源的歌曲。

**预期行为**
预期可以正常播放音频并下载
若出现“该歌曲没有可播放的音频”进行重试以及刷新下载界面

**环境：**
  -操作系统：Windows 10
  -软件安装包及版本：1.9.0 安装版

**其他内容**

我这里还测出来网易源这些歌曲，希望对您有帮助。

样本歌单：“【Phigros】游戏原声（详情见简介）”
样本容量：92
问题歌曲数量：7
所占比例约：13.142%

问题歌曲：
GOODRAGE (Long.ver) - EBIMAYO
Lyrith -迷宮リリス- - LeaF
Dead Soul (Long.ver) - Sound Souler
ENERGY SYNERGY MATRIX (Long.ver) - Tanchiky
Reimei - 影虎。
MOBILYS - Dachs
Break Through The Barrier - lixound

**Comment by lyswhut** [comment]
已在v1.10.0中修复，你可以验证一下

**Comment by Danielma0203** [comment]
> 该问题已在v1.10.0中修复，你可以验证一下


修复了但是没有完全修复XD

行为：可以一次播放音乐
           但是仍没有下载按钮

视频：
        https://user-images.githubusercontent.com/70054392/118961779-485a2680-b997-11eb-8b74-682b6eb947a0.mp4

**Comment by Danielma0203** [comment]
已经重启软件及清理列表

**Comment by lyswhut** [comment]
忘了说了，你要把原来有问题的歌曲从小我的列表移除掉，然后重新从在线列表添加
