### ISSUE TITLE
什么时候出iOS版

### ISSUE THREAD

**Issue by LoveJessyChen** [lyswhut/lx-music-desktop#505]
快点开发

**Comment by haifengzuishuai** [comment]
可以下载后导入

**Comment by xiaolingjng** [comment]
这个软件按常理不可能能进入AppStore的

**Comment by LoveJessyChen** [comment]
> 这个软件按常理不可能能进入AppStore的

我只需要ipa的越狱版本

**Comment by VBaboon** [comment]
开源变成讨要，你可真逗。有本事自己开发。作者免费给你打工？

**Comment by shianyuan** [comment]
> 开源变成讨要，你可真逗。有本事自己开发。作者免费给你打工？

吃枪炮了吗？那你来开源这里干嘛，全球人给你打工？

**Comment by VBaboon** [comment]
> > 开源变成讨要，你可真逗。有本事自己开发。作者免费给你打工？
> 
> 吃枪炮了吗？那你来开源这里干嘛，全球人给你打工？

保持正常的反馈，恳求作者开发新功能，不是这种态度。还要求快点开发。看着来气。

**Comment by rzb-y** [comment]
这款软件受众群体本来就小，只做ipa的话更少人用…… 况且楼主你这态度是来逼着人家开发的吗？

**Comment by LoveJessyChen** [comment]
> 这款软件受众群体本来就小，只做ipa的话更少人用…… 况且楼主你这态度是来逼着人家开发的吗？

你闭嘴吧

**Comment by VBaboon** [comment]
好好一个国内开源环境尽被这些人坏心情

**Comment by Danielma0203** [comment]
在这里讨论罢
https://github.com/lyswhut/lx-music-mobile/issues/1
别互相喷了（泪

**Comment by lyswhut** [comment]
看：https://github.com/lyswhut/lx-music-mobile/issues/1#issuecomment-846647504

**Comment by LoveJessyChen** [comment]
> 好好一个国内开源环境尽被这些人坏心情

这个软件不太行 这个作者真没用

**Comment by VBaboon** [comment]
> > 好好一个国内开源环境尽被这些人坏心情
> 
> 你闭嘴吧

@lyswhut 这种人 直接封了吧 
刚刚邮件提醒 他还发了
![image](https://user-images.githubusercontent.com/7813958/119282641-0407a880-bc6d-11eb-93cc-3184d0277605.png)

**Comment by lyswhut** [comment]
@VBaboon 还说了更激进的，已经提醒过他了，再搞事情直接ban
