### ISSUE TITLE
你好，在软件的更新提示界面的网盘跳转会打不开网页，用的还是原来的蓝奏云网址。

### ISSUE THREAD

**Issue by Mechrevo892574** [lyswhut/lx-music-desktop#506]
![image](https://user-images.githubusercontent.com/45324316/118953465-6c196e80-b98f-11eb-828e-bdd7a4b3c6fd.png)

**Comment by lyswhut** [comment]
链接是硬编码进去的，新版已经更新这个链接了：
https://github.com/lyswhut/lx-music-desktop/blob/7ec7023d1bc5a4a4504c17633287e608fe24692d/src/renderer/components/material/VersionModal.vue#L49
