### ISSUE TITLE
歌单图标无法显示

### ISSUE THREAD

**Issue by springzfx** [lyswhut/lx-music-desktop#51]
能正常上网，但图标无法显示，请问是bug吗，该如何找到原因
![Screenshot_20191013_184742](https://user-images.githubusercontent.com/8992037/66714480-f4b24f00-ede9-11e9-98ca-347a2a6a1acb.png)
系统：Archlinux

**Comment by lyswhut** [comment]
其他源的歌单可以正常显示吗？

**Comment by springzfx** [comment]
> 其他源的歌单可以正常显示吗？

都不能显示图片，我下载的是appimage

**Comment by springzfx** [comment]
刚刚突然又都显示了，奇了怪了

**Comment by springzfx** [comment]
Gif有30秒，稍微有点儿长。。。

**Comment by lyswhut** [comment]
这应该是网络问题吧。。。部分访问不了应该是你那边的网络访问酷狗服务器有问题
