### ISSUE TITLE
单曲循环、顺序播放哪去了？

### ISSUE THREAD

**Issue by RHongwei** [lyswhut/lx-music-desktop#516]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

更新最近两个版本后，单曲循环、顺序播放等没有了。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

![image](https://user-images.githubusercontent.com/19774276/119788491-a8146e00-be7e-11eb-9c4f-b93e18d0610e.png)
![image](https://user-images.githubusercontent.com/19774276/119788541-b2366c80-be7e-11eb-8219-57f94ac6732e.png)

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]

**其他内容**

**Comment by lyswhut** [comment]
评论图标右边的那个不是吗？
