### ISSUE TITLE
企鹅部分vip音乐加载失败

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#517]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

有一部分vip音乐加载失败

**重现**
重现行为的步骤：
搜索  アマデウス-伊藤加奈子

**截图**

![image](https://user-images.githubusercontent.com/63327558/119795288-eb1c2300-bf0a-11eb-9f97-ffb3e8cb1ae8.png)

**环境：**
  -操作系统及版本：Windows 10 64位 18362.1500]
  -软件安装包及版本：[1.10.2 安装版]

**其他内容**

**Comment by lyswhut** [comment]
建议换源，若是独家的那就暂时没法了
