### ISSUE TITLE
提醒一下，加入QQ源要是用的人多了，可能会被腾讯发现并律师函哦...

### ISSUE THREAD

**Issue by HIhosi** [lyswhut/lx-music-desktop#52]
**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by lyswhut** [comment]
QQ源仅支持普通音质，用于作为试听用，想要高品质或无损需要到QQ客户端下载。。。
