### ISSUE TITLE
新的网易云音乐320k音质获取渠道

### ISSUE THREAD

**Issue by Tinhone** [lyswhut/lx-music-desktop#521]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**
网易云音乐320k，flac格式下载

**描述您考虑过的替代方案**
http://tool.liumingye.cn/music/?page=searchPage

**其他内容**
![图片](https://user-images.githubusercontent.com/81268244/119839963-25031e80-bf37-11eb-934d-79c5a8f6ccb7.png)

**Comment by lyswhut** [comment]
有接口的情况下，你可以编写自定义源去让lx支持320k、flac音质
