### ISSUE TITLE
歌词显示优化功能

### ISSUE THREAD

**Issue by DreamNextHeart** [lyswhut/lx-music-desktop#526]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

歌词显示不习惯，目前PC端显示歌词方式，对工作造成很大不便

**描述您考虑过的替代方案**

能多一个选择，比如像主流播放器一般双行错开显示歌词

**其他内容**

![image](https://user-images.githubusercontent.com/48338548/120057224-02c2eb00-c074-11eb-92ec-f0246b017268.png)

**Comment by lyswhut** [comment]
你可以缩放歌词窗口，目前暂不打算实现这种双行的歌词
