### ISSUE TITLE
开发【PWA】Web app.

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#527]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

开发PWA版本，以便能够在ChromeOS上使用。

**Comment by lyswhut** [comment]
此项目依赖nodejs，网络请求需要可以跨域，这些因素导致web app需要依赖其他技术实现，精力有限，不打算开发
