### ISSUE TITLE
音量概率性无法精确调节

### ISSUE THREAD

**Issue by SingSky** [lyswhut/lx-music-desktop#53]
**描述错误**
音量概率性不能精确调节

**重现**
重现行为的步骤：
1.播放任意一首歌曲
2.尝试对当前音量进行细微调节（增大或减小）
3.有概率会出现音量乱跳。

**预期行为**
音量条应当正常调节至光标处。

**截图**
https://i.postimg.cc/QMxZ8HLv/test.gif

**环境：**
  -操作系统及版本：macOS Mojave 10.14.6
  -软件安装包及版本：mac版0.7.0

**Comment by lyswhut** [comment]
之前发现了这个问题，忘了修复。。下个版本修复

**Comment by lyswhut** [comment]
该问题已在0.8.0中修复
