### ISSUE TITLE
> mac m1 上，用 arm64.dmg 包安装，无法打开，报异常「已损坏，无法打开」

### ISSUE THREAD

**Issue by hot-blood-monkey** [lyswhut/lx-music-desktop#530]
> 已在v1.10.0开始添加mac arm64位包的构建，但未测试可用性，你可以去发布页面下载测试

为啥我安装 arm64 的，打开显示「“lx-music-desktop”已损坏，无法打开。 您应该将它移到废纸篓。」

_Originally posted by @hot-blood-monkey in https://github.com/lyswhut/lx-music-desktop/issues/402#issuecomment-852210837_

**Comment by lyswhut** [comment]
有人反馈arm64 dmg包可以在m1上运行哦，是不是下载的过程中安装包损坏的问题

**Comment by hh23485** [comment]
我这里也打不开
![image](https://user-images.githubusercontent.com/14577931/121762610-9bc02e80-cb69-11eb-8d94-b797d2dcf671.png)

**Comment by LdxxdL** [comment]
sudo xattr -d com.apple.quarantine /Applications/lx-music-desktop.app

**Comment by hot-blood-monkey** [comment]
刚使用了可以 厉害了

**Comment by hot-blood-monkey** [comment]
> 我这里也打不开
> ![image](https://user-images.githubusercontent.com/14577931/121762610-9bc02e80-cb69-11eb-8d94-b797d2dcf671.png)
老哥 这个帖子下有人提供了解决方法

**Comment by freshzhy** [comment]
> 
官方Git上说因为软件没有签名，所以被MAC系统禁止运行，如果你已经打开了通用 > 信任任何来源安装后还是报错，那么在终端里执行以下命令：
sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app
输入你的电脑密码即可。

**Comment by heyzzqq0103** [comment]
> > 
> 
> 官方Git上说因为软件没有签名，所以被MAC系统禁止运行，如果你已经打开了通用 > 信任任何来源安装后还是报错，那么在终端里执行以下命令： sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app 输入你的电脑密码即可。

完美解决！可以解决！

**Comment by qianxingstudio** [comment]
这个完美解决，
