### ISSUE TITLE
音乐无法下载，下载状态显示 “read ECONNRESET” 、“下载失败”

### ISSUE THREAD

**Issue by HyberLinker** [lyswhut/lx-music-desktop#532]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

下载歌曲，下载状态显示 “read ECONNRESET” 、“下载失败”

**重现**
重现行为的步骤：
1.开启下载设置
2.搜索歌曲
3.点击下载按钮
4.去“下载”查看下载状态
5.切换“音乐来源”，重试下载步骤
6.依然出现错误提示

**预期行为**

**截图**

**环境：**
  -操作系统及版本：Windows 10 企业版 64位 
  -软件安装包及版本：lx-music-desktop-v1.10.2-win_x64-green.7z

**其他内容**

**Comment by lyswhut** [comment]
看[常见问题](https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)
