### ISSUE TITLE
添加播放本地音乐功能

### ISSUE THREAD

**Issue by lv-sang** [lyswhut/lx-music-desktop#536]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

给洛雪音乐软件添加上播放本地音乐的功能，虽然作者的初衷是音乐下载器，但是这款软件哪怕作为播放器也不为过，所以希望作者大大可以添加上本地播放的功能

**描述您考虑过的替代方案**

**其他内容**

**Comment by luo-chuan** [comment]
同求

**Comment by Yensan** [comment]
对。我本地库很大，几十个 G，周杰伦全集……
很喜欢洛雪音乐。
既然都有下载功能了……那么为什么不先做本地音乐文件呢，不是很理解

**Comment by lyswhut** [comment]
已在v2.0.0新增
