### ISSUE TITLE
例如：我如何做，可以搞一个iPhone版本？

### ISSUE THREAD

**Issue by LONGDDSF** [lyswhut/lx-music-desktop#537]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
移动端的问题请去移动端项目讨论：https://github.com/lyswhut/lx-music-mobile/issues
