### ISSUE TITLE
添加播放本地音乐功能

### ISSUE THREAD

**Issue by clownstar** [lyswhut/lx-music-desktop#54]
**描述您想要的解决方案**
简洁明了地描述您要发生的事情。
添加播放本地音乐功能，非下载的也可以播放，目前只能播放下载的，本地已存在的没法导入播放

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by lyswhut** [comment]
洛雪音乐的最初定位不是作为播放器开发的，它主要用于**查找歌曲**，软件的播放功能仅用于试听，不建议用作为常用播放器使用，因此无桌面、界面歌词，不可自定义列表、添加本地播放文件播放等。
