### ISSUE TITLE
添加列表排序功能

### ISSUE THREAD

**Issue by qq790978763** [lyswhut/lx-music-desktop#542]
在导入不同平台歌单的时候，有些歌曲已经重复添加，我希望能通过名称排序筛选出重复添加的歌曲或者可以通过其他的方式给我找出相同的歌曲

**Comment by lyswhut** [comment]
目前不打算添加自动排序，如果想要排序可以使用多选功能配合排序使用，顺序将会按照你选中歌曲的顺序进行排序

已在v1.14.0添加重复歌曲列表
