### ISSUE TITLE
列表上很多音乐无法播放

### ISSUE THREAD

**Issue by Lj2021** [lyswhut/lx-music-desktop#543]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]

**其他内容**

**Comment by Felo-Z** [comment]
同样的问题

**Comment by Lj2021** [comment]
下载也无法下载了

**Comment by lyswhut** [comment]
尝试按照常见问题的方法去解决
