### ISSUE TITLE
请求一个可以把榜单中的所有音乐一键添加到试听列表的功能

### ISSUE THREAD

**Issue by Louis209** [lyswhut/lx-music-desktop#544]
![捕获](https://user-images.githubusercontent.com/65349532/121772606-e614d000-cba8-11eb-8388-ef8e66db244e.PNG)
![捕获](https://user-images.githubusercontent.com/65349532/121772620-02b10800-cba9-11eb-9c16-82a5df49debb.PNG)
一段时间没用就优化的这么好了
总体来说这款音乐播放器可以和YesPlayMusic不相上下了

**Comment by Louis209** [comment]
用户可以自由开启这个功能，不必再配合按键

**Comment by lyswhut** [comment]
v1.10.0起已添加排行榜的直接播放与收藏功能，详情看v1.10.0的更新日志：https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md

**Comment by CrBoysen** [comment]
1.10.0的排行榜播放功能能不能再完善一下，至少加个临时列表，不然播放排行榜的时候只能上一曲和下一曲，一选择排行榜里的其他曲面的时候就变成试听列表了

**Comment by lyswhut** [comment]
> 1.10.0的排行榜播放功能能不能再完善一下，至少加个临时列表，不然播放排行榜的时候只能上一曲和下一曲，一选择排行榜里的其他曲面的时候就变成试听列表了

你可以右击排行榜收藏到我的列表，然后去我的列表找到这个排行榜播放
