### ISSUE TITLE
网易云音乐无法导入歌单（已阅读常见问题）

### ISSUE THREAD

**Issue by fsyj-123** [lyswhut/lx-music-desktop#545]
**问题描述**
网易云音乐歌单导入问题，当需要导入的歌单的歌曲数量过多（一次测试：328首歌曲），会出现导入歌单加载失败的问题
尝试了多个歌单，歌曲数量在100左右的歌单成功导入，当待导入歌单的歌曲数量为328首时，无法导入。

**歌单链接**
https://music.163.com/#/playlist?id=586494734&userid=411940182&creatorId=411940182

**截图**
![image](https://user-images.githubusercontent.com/65690779/121905254-8c550700-cd5c-11eb-8efd-71c0138e37d2.png)
![image](https://user-images.githubusercontent.com/65690779/121905388-b0b0e380-cd5c-11eb-859b-2adb6b1fd5c6.png)

**环境：**
  -操作系统及版本：[Windows 10 64位]

**Comment by lyswhut** [comment]
由于网易 “我喜欢” 歌单不能在未登录的情况下访问，但支持打开自己创建的歌单

**Comment by Shawn509** [comment]
> 由于网易 “我喜欢” 歌单不能在未登录的情况下访问，但支持打开自己创建的歌单
> 你在浏览器开个隐身窗口打开你上面发的链接，会发现打不开并提示404
先把“我喜欢的音乐”直接收藏到一个歌单里面，然后就能打开了。

**Comment by Shawn509** [comment]
先把“我喜欢的音乐”直接收藏到一个歌单里面，然后就能打开了。
