### ISSUE TITLE
无法Ping通 http://ts.tempmusic.tk

### ISSUE THREAD

**Issue by sharpFD** [lyswhut/lx-music-desktop#548]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
上海电信，无法Ping通域名ts.tempmusic.tk，为什么会存在这样的问题，作者部署机器是国内机房还是国外机房，运营商是哪个，以后是否有多地部署，负载均衡计划，或者使用中间nginx做一层代理。

**重现**
重现行为的步骤：
搜歌，播放，出现getAddressInfoError

**预期行为**
正常播放

**截图**
无

**环境：**
无

**其他内容**
无

**Comment by sharpFD** [comment]
添加host后已生效

**Comment by lyswhut** [comment]
ping 的时候不要加`http://`
