### ISSUE TITLE
测试接口无法播放

### ISSUE THREAD

**Issue by everything411** [lyswhut/lx-music-desktop#549]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

使用测试接口无法播放，抓包显示接口返回400和404
此外切换到临时接口也不行，提示`Api is not found`

**重现**
重现行为的步骤：
打开软件，播放任意歌曲

**预期行为**

歌曲播放

**截图**

![图片](https://user-images.githubusercontent.com/32010059/122878243-1c510d00-d36a-11eb-88fe-82ab60637355.png)

最初返回400
![图片](https://user-images.githubusercontent.com/32010059/122877949-c3817480-d369-11eb-8a76-f990c5110174.png)
后来返回404
![图片](https://user-images.githubusercontent.com/32010059/122877994-d09e6380-d369-11eb-8140-3d633cd00b29.png)

**环境：**
  -操作系统及版本：Windows 10 64位 19043
  -软件安装包及版本：1.10.2 绿色版

**其他内容**

**Comment by lyswhut** [comment]
换成临时接口用着先吧，404的问题需要换IP

**Comment by lyswhut** [comment]
已恢复正常
