### ISSUE TITLE
国外无法播放了

### ISSUE THREAD

**Issue by chaojidafanqie** [lyswhut/lx-music-desktop#55]
前几个版本还可以听歌甚至下载。
新版本海外听不了也下载不了了。 不管什么源都不能使用。

**Comment by lyswhut** [comment]
该问题解决顺序如下：

1. 尝试更新到最新版本
2. 尝试切换其他歌曲（或直接搜索该歌曲），若全部歌曲都无法试听与下载则进行下一步
3. 尝试到设置-接口来源切换到其他接口
4. 尝试切换网络，比如用手机开热点（目前存在某些网络无法访问接口服务器的情况）
5. 若还不行请到这个链接查看详情：<https://github.com/lyswhut/lx-music-desktop/issues/5>
6. 若没有在第5条链接中的第一条评论中看到接口无法使用的说明，则应该是你网络无法访问接口服务器的问题，如果接口有问题我会在那里说明。

想要知道是不是自己网络的问题可以看看`https://ts.tempmusic.tk`能不能在浏览器打开，浏览器显示404是正常的，如果不是404那就证明所在网络无法访问接口服务器。
若网页无法打开或打来不是404，则应该是DNS的问题，可以尝试以下办法：

1. 改成自动获取试试
2. 手动把DNS改一下，不要用360的DNS，可以把DNS改成`114.114.114.114`、`8.8.8.8`
3. 软件设置里面的代理不要勾起来

**Comment by chaojidafanqie** [comment]
谢谢你的耐心回复。我等回家再试试

**Comment by chaojidafanqie** [comment]
切换测试接口可以使用了

**Comment by lyswhut** [comment]
👌
