### ISSUE TITLE
Api is not found

### ISSUE THREAD

**Issue by 2428856708** [lyswhut/lx-music-desktop#550]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
点击播放，最下边报“Api is not found”
或
音乐列表的中的歌曲轮番播放，都报“Api is not found”

**预期行为**

正常播放

**截图**

上传报错

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.10.2 安装版]

**其他内容**

**Comment by lyswhut** [comment]
尝试切换到测试接口
