### ISSUE TITLE
作者能否解释一下软件首次启动为何要调用摄像头？

### ISSUE THREAD

**Issue by cjydayang** [lyswhut/lx-music-desktop#551]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

软件启动时被安全软件检测到调用过摄像头，请问作者此事你是否知情？

**预期行为**

暂时还没有抓包分析是否有上传相关信息的操作，只是想简单确认一下：
如果是设计如此，请给出原因；如果你不知情，可以当作bug处理。

**截图**

![image](https://user-images.githubusercontent.com/24446099/123009202-da1ddf00-d3ee-11eb-87d1-d58f9967a360.png)

**环境：**
  -操作系统及版本：Windows 10 pro 64位 19042.1052
  -软件安装包及版本：1.10.2

**Comment by lyswhut** [comment]
看常见问题“杀毒软件提示有病毒或恶意行为”部分

**Comment by cjydayang** [comment]
ok 已知悉
