### ISSUE TITLE
优化程序坞(dock)处 icon 大小

### ISSUE THREAD

**Issue by hejianghu** [lyswhut/lx-music-desktop#552]
程序坞(dock) 处 icon 有点偏大，看起来有点突兀，能否稍微调小一点？
![image](https://user-images.githubusercontent.com/75015513/123391546-b7e2b780-d5ce-11eb-9f8b-7dd093d5c22d.png)

**Comment by hocko333** [comment]
+1

**Comment by lyswhut** [comment]
我不了解这里需要多大边距的图标，MAC版也有存在这个问题，有没有人知道这两个系统下的图标边距？

**Comment by hejianghu** [comment]
@lyswhut 看了一下 chrome 的图标，图形本身只占据图片的 3/4 左右：
![image](https://user-images.githubusercontent.com/75015513/144862391-c4f09c3b-5f6c-4300-b040-53b7e4e775ce.png)
而 lx 这边，貌似占据了整个图片的尺寸：
![image](https://user-images.githubusercontent.com/75015513/144862590-f4f83c90-d97b-40c7-adc4-bbbd0d4b48bb.png)
感觉可以用 ps 把图片尺寸缩小到原来的 3/4，然后再把画布放大到原本的尺寸，应该就好了

**Comment by lyswhut** [comment]
好的，回头我试试

**Comment by lyswhut** [comment]
已在这个版本进行了图标调整，你们可以看看：https://github.com/lyswhut/lx-music-desktop/actions/runs/1563512279

**Comment by hejianghu** [comment]
感觉好了不少，但好像又稍小了一点点，不过也 ok，感谢大佬！
![image](https://user-images.githubusercontent.com/75015513/147414494-71f8de18-9772-4363-8e6c-dbfb00b4a4f3.png)
