### ISSUE TITLE
优化安装包green功能

### ISSUE THREAD

**Issue by duansheli** [lyswhut/lx-music-desktop#553]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

目前的情况： 
软件包 lx-music-desktop-v1.10.2-win_x64-green.7z 
虽然是个解压版，免安装 
但软件的数据是存放在 user_home、app_data 目录（猜的，具体啥目录没研究）下的 

这样的好处是 有两个解压版本 v1.2 v1.3时
无论打开哪一个 都能使用同一个收藏列表

**不好的点是： 重装系统或拷到其他电脑时，无法同步收藏列表
这个问题 只能通过导出播放列表 导入播放列表 的按钮来同步**

能否支持为 数据存放在软件包的根目录 
这样系统重装 或者 解压到移动硬盘 播放列表随软件包移动 
不用再 导出 导入

**Comment by lyswhut** [comment]
软件数据存储目录：`%HOMEPATH%\AppData\Roaming\lx-music-desktop`
软件更新文件下载目录：`%HOMEPATH%\AppData\Local\lx-music-desktop-updater`

暂不打算提供这些目录的修改，但是你可以收藏软件数据存储目录，迁移的时候顺便迁移即可，或者使用备份与恢复功能。
