### ISSUE TITLE
希望能添加网易云电台

### ISSUE THREAD

**Issue by S1ing** [lyswhut/lx-music-desktop#554]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

希望能添加网易云电台

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/438
