### ISSUE TITLE
除了小蜗音乐外，其他的音乐都播放不了额。

### ISSUE THREAD

**Issue by xiac72145** [lyswhut/lx-music-desktop#555]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

![image](https://user-images.githubusercontent.com/63084009/123535425-45044880-d756-11eb-9a69-538350be3da0.png)

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]

**其他内容**

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/209
