### ISSUE TITLE
希望  增添播放列表的功能；列表循环功能     批量下载功能

### ISSUE THREAD

**Issue by Jeremy-stu** [lyswhut/lx-music-desktop#556]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
这些问题都可以看[常见问题](https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)解决
