### ISSUE TITLE
Windows11上显示不正常，一片白色，什么都看不清。

### ISSUE THREAD

**Issue by shanyan-wcx** [lyswhut/lx-music-desktop#557]
![image](https://user-images.githubusercontent.com/58252651/123925480-88142500-d9bd-11eb-9bae-6de736f47e9f.png)

**Comment by lyswhut** [comment]
我在虚拟机安装的win11上测试是正常的：
![image](https://user-images.githubusercontent.com/20365169/123938070-5d2fce00-d9c9-11eb-915e-45425ba42cf3.png)

**Comment by shanyan-wcx** [comment]
我也是虚拟机Win11，其他软件都正常，就洛雪不正常

**Comment by shanyan-wcx** [comment]
我看你图片里设置界面还是老版本的，是不是因为你的系统版本不是最新的所以正常？

**Comment by lyswhut** [comment]
你的系统版本号又是多少，是不是驱动的问题？
