### ISSUE TITLE
安卓版有计划吗

### ISSUE THREAD

**Issue by hezhizheng** [lyswhut/lx-music-desktop#56]
**描述您想要的解决方案**
简洁明了地描述您要发生的事情。

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by lyswhut** [comment]
已列入计划，不过事情比较多，还没开始开发，预计要等一两个月才会出
