### ISSUE TITLE
建议：添加支持m3u文件功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#560]
**解决方案检查**

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

建议：
①洛雪音乐可以加载m3u文件，并保存到音乐列表
②洛雪音乐可以保存播放列表为m3u文件

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
1、目前不支持播放本地音乐
2、音乐平台的歌曲链接有时效性，几个小时链接就会失效
综上，m3u文件不适用本软件
