### ISSUE TITLE
求大佬分离ui

### ISSUE THREAD

**Issue by aaxx255** [lyswhut/lx-music-desktop#563]
啊，太好看了。大佬威武。

**Comment by lyswhut** [comment]
什么分离UI？没懂你意思

**Comment by aaxx255** [comment]
> 什么分离UI？没懂你意思

啊。。打字手滑了。是分享。
这个ui是真好看。谢谢大佬 。

**Comment by lyswhut** [comment]
不懂你想要怎么分享，此UI是我看了设计网站上别人的设计稿后根据自己的想法搞的，并没有做设计稿
