### ISSUE TITLE
音乐无法播放

### ISSUE THREAD

**Issue by j2501987804** [lyswhut/lx-music-desktop#566]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
m1 很多都没法播放，只有小部分可以

**重现**
重现行为的步骤：
搜索周杰伦的歌

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]

**其他内容**

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/41771911/125386065-3c567800-e3ce-11eb-99df-8ccb115bc96d.png">

**Comment by gbolin** [comment]
mac上也无法播放

**Comment by lyswhut** [comment]
去设置清下缓存，对于提示`getaddrinfo EAI AGAIN ts.tempmusic.tk`或`无法连接服务器`的看：<https://github.com/lyswhut/lx-music-desktop/issues/5#issuecomment-830508233>
