### ISSUE TITLE
单击锁定的歌词之后lx music主界面无法点击的情况

### ISSUE THREAD

**Issue by November-Hello** [lyswhut/lx-music-desktop#569]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
单击锁定的歌词之后lx music主界面没有变化，但是点击会将点击响应移动到底下那个应用窗口，如果底下是桌面就会响应桌面的点击。
如下图，这个是我单击锁定的歌词后，在只打开lx music的窗口的情况下，右键主界面的情况。

**重现**
重现行为的步骤：
1.锁定桌面歌词
2.在lx music主窗口的最前端，歌词后面没有窗口的情况下，单击桌面的锁定歌词
3.然后回到主界面发现无法点击

**预期行为**

主界面响应我的点击

**截图**

![image](https://user-images.githubusercontent.com/78646351/126062062-d3ba0153-5963-48c2-a3ae-9f17e3308acd.png)

**环境：**
  -操作系统及版本：Windows 10 64位 19042.1110
  -软件安装包及版本：1.1.0安装版

**其他内容**

恢复这个问题也很简单，可以点击其他窗口再点击lx music主界面，也可以点击任务栏下面的lx music恢复

**Comment by lyswhut** [comment]
我这边win 10 21H1没能重现

**Comment by November-Hello** [comment]
> 我这边win 10 21H1没能重现

额，我再测试了一下，是点击桌面才会出现这种情况。

https://user-images.githubusercontent.com/78646351/126093310-c86fef50-c542-4994-959e-c6b66ece7890.mp4

**Comment by November-Hello** [comment]
> 我这边win 10 21H1没能重现

不好意思我知道了，我装了一个第三方的电脑桌面，人工桌面。是这个桌面存在的时候才会出现这个问题
