### ISSUE TITLE
添加当前播放歌曲下载功能

### ISSUE THREAD

**Issue by luoqiz** [lyswhut/lx-music-desktop#57]
伟大滴程序猿，期望在播放这添加下载按钮。这样就不用每次去试听列表再去查找了，三克油！！！
![image](https://user-images.githubusercontent.com/22161059/67375437-31820100-f5b5-11e9-8f96-47d5e7bd7cb8.png)

**Comment by lyswhut** [comment]
改成在列表定位播放歌曲好点吧？

**Comment by luoqiz** [comment]
那更好啊

**Comment by lyswhut** [comment]
将在下个版本添加该功能，点击播放栏进度条左侧的歌曲封面后，将跳转到当前播放歌曲所在列表中歌曲的位置

**Comment by luoqiz** [comment]
666

**Comment by lyswhut** [comment]
已在0.9.0版本添加该功能

**Comment by luoqiz** [comment]
ok
