### ISSUE TITLE
安卓车机显示界面有缺失

### ISSUE THREAD

**Issue by johnnyeecker** [lyswhut/lx-music-desktop#570]
你好作者：
      安卓车机安装了安卓版的后，目前（只）发现一个问题：播放音乐时没有播放控制条，就是没有歌曲缩略图，播放、暂停，下一曲那一条操作按钮，导致无法进行播放控制，要想停止播放只能结束任务。
       这个软件很好，希望修复bug。

**Comment by lyswhut** [comment]
安卓的问题去安卓项目那边反馈，界面问题请附上图片
