### ISSUE TITLE
建议使用WebRTC实现P2P资源传输

### ISSUE THREAD

**Issue by gaoxiaohu2008** [lyswhut/lx-music-desktop#571]
**解决方案检查**

- [ x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

为了软件能够长远的使用，避免端口封锁后变成无资源可播放。

**描述您考虑过的替代方案**

由于软件使用Web框架实现的，建议使用webRTC实现P2P的资源传输，这样就可以长久的拥有播放资源 ，持续的使用 。

**其他内容**

**Comment by lyswhut** [comment]
除非播放下载列表的歌曲， 不然软件播放的歌曲都是来自各个音乐平台的在线资源，按目前的方式不适合P2P传输，况且这个功能也需要服务器支持，最后我个人对这玩意也不是很了解，综上不打算实现，但是如果谁有兴趣去实现也是欢迎讨论与提交PR的。
现在我先暂时关闭改issue，如果有人确实要做的话我再打开它
