### ISSUE TITLE
现在最新版本的不能下载歌曲了吗

### ISSUE THREAD

**Issue by LTonJin** [lyswhut/lx-music-desktop#576]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by songlai** [comment]
设置里打开下载设定

**Comment by lyswhut** [comment]
v1.0.0起默认关闭下载功能，需到设置开启
