### ISSUE TITLE
添加： 当鼠标点一首歌的时候 这首歌播放完毕 播放此列表的下一首歌曲 。

### ISSUE THREAD

**Issue by shy113** [lyswhut/lx-music-desktop#577]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
看常见问题 播放整个歌单或排行榜 部分
