### ISSUE TITLE
歌词显示花屏

### ISSUE THREAD

**Issue by fancyistyle** [lyswhut/lx-music-desktop#578]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

歌词花屏

**重现**
重现行为的步骤：

1.没有关闭歌词显示界面，退出软件
2.再次打开的时候就会发现重现弹出的歌词花屏

**预期行为**

不显示任何歌词，或出现上次停下的内容歌词

**截图**

![2021-07-29 11-03-20 的屏幕截图](https://user-images.githubusercontent.com/34431955/127425254-d30c1b6c-6175-4041-a051-137bd627f287.png)

**环境：**
  -操作系统及版本：unbuntu 20.04
  -软件安装包及版本：lx-music-desktop.v1.11.0.x64.rpm

**其他内容**

**Comment by lyswhut** [comment]
我在虚拟机里的Ubuntu 18.10上测试是正常的，我使用的是deb版安装包
![GIF](https://user-images.githubusercontent.com/20365169/127428985-7959273a-fb00-4123-9264-cdef2aed3ff0.gif)

**Comment by fancyistyle** [comment]
那可能是我的有一次强行退出，留下了缓存吧，我重新安发现也没用

**Comment by lyswhut** [comment]
尝试添加启动参数`-dha`运行

**Comment by gangdan12** [comment]
我win7sp未启用aero效果下，也有残影；添加 -dt -dha 命令可解决。但是没法不开启aero效果下正常显示，这个可以解决吗？

**Comment by lyswhut** [comment]
> 我win7sp未启用aero效果下，也有残影；添加 -dt -dha 命令可解决。但是没法不开启aero效果下正常显示，这个可以解决吗？

window 7下的界面异常时系统缺少某些系统更新导致的，尝试按照常见问题说的去解决，不行那就不行了，更新系统可能会解决问题

**Comment by lyswhut** [comment]
据我装了多个发行版的linux来看，在某些linux上会有这个问题，同一个发行版（如Ubuntu、Deepin）的不同版本，有些是可以正常显示，有些却不行，可以尝试更新linux或桌面解决？
