### ISSUE TITLE
能加个自动更新的功能吗？

### ISSUE THREAD

**Issue by Light--** [lyswhut/lx-music-desktop#579]
每次更新都下重新手动下载安装？

**Comment by lyswhut** [comment]
目前只有windows安装版可以自动更新，若你所在地区的网络连接GitHub异常也可能会导致更新下载失败

**Comment by Light--** [comment]
> 目前只有windows安装版可以自动更新，若你所在地区的网络连接GitHub异常也可能会导致更新下载失败

谢谢，我用的LINUX版，不过这个软件真的很棒！就是有时候发现不能分享歌曲，打开链接失效了
