### ISSUE TITLE
希望添加新建歌单的功能

### ISSUE THREAD

**Issue by yuanmingchen** [lyswhut/lx-music-desktop#58]
**描述您想要的解决方案**
希望添加新建歌单的功能，因为目前导入各大音乐源歌单之后只能把歌曲都导入到软件自带的“我的收藏”歌单里，导致各个歌单各种类型的的歌曲都混在一起了，希望增加新建歌单功能，方便对歌曲和歌单分类管理

**Comment by lyswhut** [comment]
目前暂无添加自定义列表的计划，详情请看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD
