### ISSUE TITLE
安卓手机上蓝牙耳机的各种操作在洛雪的app上无法正常工作

### ISSUE THREAD

**Issue by sdoughnut** [lyswhut/lx-music-desktop#580]
**解决方案检查**

- 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
在安卓手机，蓝牙耳机的各种操作无法在洛雪app上正常工作，诸如暂停歌曲，下一首，上一首这些操作，统统无法工作，在其他音乐app可以正常操作

**预期行为**
希望能解决以上问题

**环境：**
  -操作系统及版本：手机一加6，系统安卓10，蓝牙耳机为Oppo Enco Free2
  -软件安装包及版本：LX Music 0.5.3

**Comment by lyswhut** [comment]
移动端的问题去移动端项目提issue
