### ISSUE TITLE
请优化平台的音乐分类名称，什么“小蜗音乐”，“小球音乐”真的看不出来是哪个平台（哦设置里可以设置啊那没事了）

### ISSUE THREAD

**Issue by lingkaihang** [lyswhut/lx-music-desktop#586]
**解决方案检查**

- [ x ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ x ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

如标题

**描述您考虑过的替代方案**

目前只认出“小芸音乐”是网易云音乐，可以把各个音乐的名称替换成具体的平台，像什么酷狗音乐啊，QQ音乐啊，网易云音乐啊之类的

**其他内容**

![1628169492(1)](https://user-images.githubusercontent.com/80158532/128356443-d6a6c735-810d-446a-b435-3e2049c27572.png)
（关于网站目前音乐平台的名字）

**Comment by Jyuaan** [comment]
小蜗: 酷我
小枸: 酷狗
小秋: QQ
小芸: 网易
小蜜: 咪咕

不用平台原名可能怕版权? 这些"昵称"的确不是在所有地方都同音，不好分辨，我用普通话念一遍才能分出来。

**Comment by BaiShou** [comment]
设置里面可以设置啊

**Comment by lingkaihang** [comment]
> 设置里面可以设置啊

刚刚看到了，谢谢提醒
