### ISSUE TITLE
希望添加听歌识曲功能！！

### ISSUE THREAD

**Issue by lingkaihang** [lyswhut/lx-music-desktop#587]
**解决方案检查**

- [ x ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ x ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

添加听歌识曲功能（因为此软件可以同时搜索到五个音乐平台的音乐，范围广，不做听歌识曲可惜了）

**描述您考虑过的替代方案**

无

**其他内容**

无

**Comment by lyswhut** [comment]
没研究过这个，也没计划去研究，建议使用其他软件代替
