### ISSUE TITLE
希望新增功能<窗口大小手动调整>

### ISSUE THREAD

**Issue by richild999** [lyswhut/lx-music-desktop#592]
可以手动设置窗口尺寸或者是可以手动拖动边框调整窗口大小，而非现有的固定形式。

**Comment by lyswhut** [comment]
软件使用了透明窗口，根据electron的[文档说明](https://www.electronjs.org/docs/api/frameless-window#透明窗口)：

> 透明窗口不可调整大小。 在某些平台上，将 resizable 设置为 true 可能会使透明窗口停止工作。
