### ISSUE TITLE
优化内存占用

### ISSUE THREAD

**Issue by saber421123** [lyswhut/lx-music-desktop#598]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

![image](https://user-images.githubusercontent.com/68185051/129508730-81b2b43b-f87f-48b0-b763-fee2b5eda2e6.png)
![image](https://user-images.githubusercontent.com/68185051/129508738-324fe547-5ce8-4ca4-9deb-f1ed240cc15f.png)
希望能解决这内存占用,太大了吧,快赶上谷歌这内存霸主了

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
electron应用本来就是包含了一个chromium在里面，这是v1.12.2的chromium版本号：
![image](https://user-images.githubusercontent.com/20365169/129509567-5727120d-f8f5-485f-ab9b-76e82464efbb.png)

在我电脑上运行一般内存占用在360M左右，峰值在四五百左右（不操作一段时间会降到300左右）
你可以观察下内存占用情况，如果一直只曾不减的话那可能有内存泄漏的问题，这样的话，说下操作步骤我排查下

**Comment by Saberzw421123** [comment]
好的,如果这是正常值之内就行,另外我想提个小意见,就是搜索的时候能过滤那些无用的歌曲吗,并且下载歌曲的时候也不提醒该歌曲时候已经下载过,如果把这改善改善就完美了

**Comment by lyswhut** [comment]
已下载过的同源同音质歌曲在添加到下载列表时会被过滤掉
