### ISSUE TITLE
其他TAB页面没有播放和下载按钮

### ISSUE THREAD

**Issue by Momohanfeng** [lyswhut/lx-music-desktop#599]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

在设置中打开“启用下载功能”，但是只能在第一个Tab(小蜗)中出现 播放和下载 按钮，其他Tab都没有 播放和下载 按钮。

**重现**
重现行为的步骤：
1.转到“设置”
2.点击“ 启动下载功能”
3.回到搜索，随意搜索一首歌
4.然后在不同Tab中切换，查看 列表中的播放和下载按钮

**预期行为**
 步骤4中其他的Tab搜索出的list item中是否可以出现播放和下载按钮，是否是因为版权和vip的问题？

**截图**
![bug1](https://user-images.githubusercontent.com/4652023/129829519-03598e1c-f5a4-44b4-95aa-d19dc0013146.png)

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 19043.1165]
  -软件安装包及版本：[desktop 1.12.2 green]

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/209
