### ISSUE TITLE
关于0.33版本在Windows10系统播放的歌曲与界面显示不一致的问题反馈

### ISSUE THREAD

**Issue by wenzhi2020** [lyswhut/lx-music-desktop#6]
复现方法:
1.播放的歌曲没有调用出来(可能API问题或者网络问题)
2.重新选择歌曲播放

环境:
Windows10
备注:
如果按照我的复现方法应该就是一个必现的问题
如果歌曲的播放都是能够正常播放的话,那么这个问题是不存在的
我怀疑现在接口是一个临时接口导致的这个问题

**Comment by lyswhut** [comment]
之前的messoer接口没有这个问题吗？
复现方法是不是这样：

1. 点击播放歌曲A，播放状态显示歌曲链接获取中
2. A歌曲链接还没获取完成时点击播放歌曲B

能说详细点吗？

**Comment by wenzhi2020** [comment]
> 之前的messoer接口没有这个问题吗？
> 复现方法是不是这样：
> 
> 1. 点击播放歌曲A，播放状态显示歌曲链接获取中
> 2. A歌曲链接还没获取完成时点击播放歌曲B
> 
> 能说详细点吗？
> 这个临时接口服务器请求比较慢。

1.之前的接口没有这个问题
2.你的复现方法完全正确,我就是这样子操作的出现我反馈的情况
3.是的这个接口请求比较慢,同时我发现貌似好多歌曲都是没有办法获取到了

**Comment by lyswhut** [comment]
我这边测并没有发现你说的这个问题，回头我再检查下代码吧。
不过发现了Bug，当播放到一半发现缓存的歌曲链接失效时，重新刷新URL的过程中歌词仍然在播放的问题。

**Comment by lyswhut** [comment]
刚试了下，确实在某些情况下会播放之前点击的歌，回头找原因修复

**Comment by lyswhut** [comment]
已在0.6.1版本中修复了个请求超时的bug，由于某些情况下请求仍然无法终止，不知道这个问题还会不会出现，若仍然出现欢迎反馈！

**Comment by wenzhi2020** [comment]
> 已在0.6.1版本中修复了个请求超时的bug，由于某些情况下请求仍然无法终止，不知道这个问题还会不会出现，若仍然出现欢迎反馈！

**Comment by wenzhi2020** [comment]
> > 已在0.6.1版本中修复了个请求超时的bug，由于某些情况下请求仍然无法终止，不知道这个问题还会不会出现，若仍然出现欢迎反馈！

**Comment by lyswhut** [comment]
进过那么久的使用，我这边没有再遇到该问题出现，也没有看到有人反馈，我现在关闭该issue，若后面再遇到该问题可重新打开！
