### ISSUE TITLE
0.9.0版本运行出错

### ISSUE THREAD

**Issue by cdwmhcc** [lyswhut/lx-music-desktop#60]
**描述错误**
运行后提示以下错误：
![image](https://user-images.githubusercontent.com/8030134/67629296-8ae87980-f8ae-11e9-9718-b1cf7f39c19b.png)

**重现**
重现行为的步骤：
1. 下载lx-music-desktop-0.9.0.dmg安装
2. 运行后即可重现。

**环境：**
  -操作系统及版本：macOS 10.15 和 macOS10.13.6

**Comment by lyswhut** [comment]
感谢反馈！这个bug影响所有平台的版本，首次安装就会出现！

**Comment by cdwmhcc** [comment]
> 感谢反馈！这个bug影响所有平台的版本，首次安装就会出现！

lyswhut@qq.com  你的这个邮箱给你发了一封邮件，你看一下。

**Comment by lyswhut** [comment]
该问题已在0.9.1修复
