### ISSUE TITLE
什么时候出IOS版

### ISSUE THREAD

**Issue by leo3162** [lyswhut/lx-music-desktop#600]
希望能出IOS版

**Comment by tommany** [comment]
同求啊。。。。。。。

**Comment by AnthonyYMH** [comment]
加一，同求ios

**Comment by Accroid** [comment]
同求！

**Comment by sunkx2015** [comment]
+1

**Comment by virtualvmw** [comment]
+1

**Comment by renji001** [comment]
同求

**Comment by LoveJessyChen** [comment]
+1
谁有能力 能拉一个带出一个ipa自己解决也行

**Comment by lyswhut** [comment]
可以看这里：https://github.com/lyswhut/lx-music-mobile/issues/84#issuecomment-1070250325

**Comment by erikjamesgz** [comment]
【 拼好歌 】一个致敬洛雪音乐的小程序版音乐播放器，填补 iOS & 鸿蒙平台空白，让好音乐无处不在

https://github.com/erikjamesgz/phg-music
