### ISSUE TITLE
[功能请求]音源显示所在地区无法使用

### ISSUE THREAD

**Issue by Danielma0203** [lyswhut/lx-music-desktop#601]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**问题**
(人在国外刚下飞机.jpg
歌曲显示请求异常，经查看音源由于版权保护，所在地区无法使用。

**描述您想要的解决方案**

有无办法选择访问位置或其他方法解决位置问题
**描述您考虑过的替代方案**

对这样的歌曲进行筛选删除

**其他内容**

**Comment by lyswhut** [comment]
你是怎么知道是音源版权保护的问题导致的呢？如果是这样的话可以搭个国内代理
