### ISSUE TITLE
lx-music-desktop 已损坏，无法打开

### ISSUE THREAD

**Issue by zhangqingxi** [lyswhut/lx-music-desktop#602]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
brew install lx-music-desktop-1.12.2-arm64.dmg
安装完成 提示软件已损坏

**Comment by jiachangyang1025** [comment]
+1

**Comment by lyswhut** [comment]
作为MAC用户不知道这些常见问题的吗？
终端里输入`sudo xattr -rd com.apple.quarantine /Applications/lx-music-desktop.app`，然后输入你的电脑密码

还可以参考：<https://blog.csdn.net/for641/article/details/104811538>

**Comment by liujunzheng** [comment]
有一个最简单的操作方法：打开文件夹，点击文件夹窗口左侧 应用程序，然后找到对应的APP，然后右键->打开。
这种右键打开的方式，跟通过设置开启隐私安全（不管是终端还是设置中开启），都是一样的效果。:tada:

**Comment by zhangqingxi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
