### ISSUE TITLE
设置了关闭软件时不退出最小化到托盘，但用快捷键“退出程序”时，是真的退出了程序😂

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#603]
这个应该不算bug，是使用逻辑上的问题

![image](https://user-images.githubusercontent.com/20263103/130318233-a69b5435-ee09-43ea-8a1b-b0214b8abc0d.png)
![image](https://user-images.githubusercontent.com/20263103/130318243-66f6964b-1c9f-464c-92ab-d76bcf07fd03.png)

我想做的就是，用快捷键：从托盘，呼出洛雪，切歌，然后切最小化到托盘

我希望它这里的退出可以 使用“关闭软件时不退出最小化到托盘”的设置

**Comment by ameaninglessname** [comment]
我想做的可以用全局快捷键实现
![image](https://user-images.githubusercontent.com/20263103/130318365-12fac321-0cd6-4711-905f-c1e0c97df5fe.png)

**Comment by lyswhut** [comment]
你想要使用软件内快捷键来隐藏程序？
“退出程序的”的快捷键会忽略是否开启托盘设置直接退出程序，这是符合逻辑的。
下个版本会优化下最小化程序的软件内快捷键，如果已启用托盘，则隐藏程序，否则最小化程序。

**Comment by lyswhut** [comment]
已在v1.13.0添加该功能
