### ISSUE TITLE
可以添加一个通过本地图片自定义主题的功能吗

### ISSUE THREAD

**Issue by ReefPan** [lyswhut/lx-music-desktop#608]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/256
