### ISSUE TITLE
添加多选功能和搜索某个歌手，能直接听当前列表的歌~

### ISSUE THREAD

**Issue by HuangJiaxin8** [lyswhut/lx-music-desktop#609]
比如搜索周杰伦的时候，我想多选几个歌曲，一起添加到我的歌单里，但是我现在只能一个个添加，希望添加这个多选功能。

比如搜索周杰伦，可以选择多选，为等待要听的。

**Comment by lyswhut** [comment]
多选功能、播放整个列表等操作看常见问题，歌手、歌单等搜索功能以后看情况添加
