### ISSUE TITLE
希望添加一个把歌词放在桌面上的功能

### ISSUE THREAD

**Issue by 1572365765** [lyswhut/lx-music-desktop#61]
有时候做别的事情想看歌词，但是必须要打开窗口才能看到歌词，类似酷狗那样的歌词显示方式会比较方便

**Comment by lyswhut** [comment]
目前无添加桌面歌词的计划，详情看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD
