### ISSUE TITLE
增加当前页面过滤搜索，及播放量显示功能，谢谢。

### ISSUE THREAD

**Issue by glamout** [lyswhut/lx-music-desktop#610]
1. 现在的搜索是全局搜索，希望可以在当前页面搜索。比如，打开某歌单后，可以在该歌单内搜索。
2. 可否显示每首歌的播放量统计？

谢谢。

**Comment by lyswhut** [comment]
1、列表搜索只支持对“我的列表”搜索，在我的列表按`Ctrl + f`即可调出搜索框，暂不打算支持在线列表的列表搜索
2、我的列表里的歌曲没有记录播放量，也不打算记录，在线列表的话，由于现有音乐平台接口似乎没有返回播放量这个值
