### ISSUE TITLE
可以把软件的设置和歌单数据  设置目录。

### ISSUE THREAD

**Issue by rushpixy** [lyswhut/lx-music-desktop#611]
这样在不同电脑可以用坚果云同步。特别是工作电脑和家里电脑之间。

**Comment by lyswhut** [comment]
软件数据存储目录：`%HOMEPATH%\AppData\Roaming\lx-music-desktop`
软件更新文件下载目录：`%HOMEPATH%\AppData\Local\lx-music-desktop-updater`
暂不打算支持更改这些目录
