### ISSUE TITLE
无损、高品质播放下载什么时候恢复

### ISSUE THREAD

**Issue by jiansite** [lyswhut/lx-music-desktop#614]
无损、高品质播放下载什么时候恢复？

**Comment by albertmawk** [comment]
无损、高品质下载不了.只有128K

**Comment by 121104115wyb** [comment]
同问，128k下载后，听起来和在线的音质有明显区别，能不能再稍微提高下音乐品质，

**Comment by meinvtuzai** [comment]
期待出320K

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749
