### ISSUE TITLE
win7下页面出现显示异常

### ISSUE THREAD

**Issue by jswnlinyu** [lyswhut/lx-music-desktop#615]
**解决方案检查**

- [ x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
显示页面不全并闪烁

**截图**

![捕获4](https://user-images.githubusercontent.com/53430542/132078233-beb1f91e-789a-46b6-8182-ee4b4bba200e.PNG)
![捕获5](https://user-images.githubusercontent.com/53430542/132078238-1718228e-4b2b-4c87-a17f-29b52f78abf4.PNG)
![捕获](https://user-images.githubusercontent.com/53430542/132078239-698cc748-30db-43b2-b9da-93e73466154c.PNG)
![捕获2](https://user-images.githubusercontent.com/53430542/132078242-b50bc469-71fd-47df-9b1b-6820cd6a655b.PNG)
![捕获3](https://user-images.githubusercontent.com/53430542/132078243-00ce45b0-9686-4039-84bf-ea039379ba78.PNG)

环境：win7专业版 sp1
软件 1.12.2安装板
**其他内容**

**Comment by lyswhut** [comment]
看常见问题

**Comment by lyswhut** [comment]
是在不行要么加`-dt`参数运行，要么升级系统

**Comment by lunakite** [comment]
> 

嗯，加了這個參數，貌似解決，目前沒有再出問題。
