### ISSUE TITLE
例如：添加【下载.flac无损音乐】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#617]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

可以自由选择能够下载的所有音质

**描述您考虑过的替代方案**

可以自由选择能够下载的所有音质

**其他内容**

可以自由选择能够下载的所有音质

**Comment by lyswhut** [comment]
软件是支持的，是内置的接口不支持下载
