### ISSUE TITLE
例如：添加【下载MV】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#618]
**解决方案检查**

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

列出MV的所有画质，供用户自主选择并下载

**描述您考虑过的替代方案**

列出MV的所有画质，供用户自主选择并下载

**其他内容**

列出MV的所有画质，供用户自主选择并下载

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/356
