### ISSUE TITLE
网易云 “我喜欢的歌单” 导入失败

### ISSUE THREAD

**Issue by lluststicker** [lyswhut/lx-music-desktop#620]
将网易云 “我喜欢的歌单” 导入至 LX Music 内显示 “加载失败” ，是 Bug 还是网易云本身的原因呢？（所有 LX Music 端导入显示相同错误提示，且只有 “我喜欢的歌单” 无法识别，其余自建歌单可以使用。）

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/545
但v1.13.0起提供了打开这类歌单的方法，详情看更新日志
