### ISSUE TITLE
建议托盘图标适配浅色主题

### ISSUE THREAD

**Issue by Macrohard-X** [lyswhut/lx-music-desktop#621]
适应浅色主题，添加黑色图标。

**Comment by lyswhut** [comment]
可以在设置改图标颜色

**Comment by Macrohard-X** [comment]
> 可以在设置改图标颜色

但是是白色的，浅色主题的话需要黑色的

**Comment by lyswhut** [comment]
![image](https://user-images.githubusercontent.com/20365169/132131468-db44b6a3-e648-416a-bc66-8e99ce08c64f.png)

**Comment by Macrohard-X** [comment]
强迫症：建议把“纯色”改成“白色”，并把“原色”放在前面
![image](https://user-images.githubusercontent.com/58348680/144883457-9b15c4ef-caef-4e9b-adf8-0d9816c73d1a.png)

**Comment by lyswhut** [comment]
下个版本修改为白色，原色放在最后，
强迫症不应该全选第一个选项吗，选项不整齐多不好看😂
