### ISSUE TITLE
希望添加功能：跳过歌曲前后时间段、禁止检查更新

### ISSUE THREAD

**Issue by Killyice** [lyswhut/lx-music-desktop#624]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

1. 我家楼下在装修，只能拿音乐抵消噪声，但是歌曲切换中间有很长的间隔，需要长达十几秒才能续上，希望增加“**全局性质的跳过首尾**”功能，不然感觉自己要扑街了。
    就像一些电视放电视剧那样，切掉前后的主题曲和广告啥的；希望可以增加个“时间滑块”或者“数字输入框”来选择跳过时间。
    我知道搞智能的找那啥子音频振幅啥的可能很麻烦，我也不指望，能加个滑块已经很好了，比如“**固定长度**”或“**百分比**”跳过。

2. 我知道有绿色版，我以前也装的绿色版，但我现在装的是安装版，，我也知道有好几个人提了这问题。
    但还是真心希望可以加个“**不再检查更新**”按钮，每次打开都弹更新提示真的会把人逼疯的，尤其是急着开音乐的时候。

**描述您考虑过的替代方案**

真的真的真的没想到替代方案；我反正不能不用吧¿
嗯，十分感谢；
说完了。

**其他内容**

**Comment by lyswhut** [comment]
如果你那边获取歌曲链接慢的话，你可以把歌曲下载下来听，
不想要更新功能的话，可以使用绿色版，出现新版本弹窗可以点击忽略当前版本

**Comment by Killyice** [comment]
> 如果你那边获取歌曲链接慢的话，你可以把歌曲下载下来听，
> 不想要更新功能的话，可以使用绿色版，出现新版本弹窗可以点击忽略当前版本

您应该没看懂我的问题，我说的是两首乐曲中间的过渡间隔，每首歌都是从低谷到高潮再到低谷，所以能不能跳过部分低谷阶段

**Comment by lyswhut** [comment]
不能直接跳到高潮部分播放
