### ISSUE TITLE
歌曲播放界面右上角的三个按钮,长按时气泡提示闪烁

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#627]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

长按“最小化按钮 - ”， 浮出的文字说明“隐藏详情页...” 显示隐藏显示，反复2-3次。

**重现**
重现行为的步骤：
复现稍微有点麻烦
1.转到“歌曲播放界面”
2.**直接，迅速**将鼠标移到“最小化按钮”，并且进行，“长按”操作
3.看到错误

**预期行为**

浮出的文字说明正常显示

**截图**

![image](https://user-images.githubusercontent.com/20263103/132937765-6df5e779-1b33-4f17-9699-0349cda8c469.png)

**其他内容**

目测是因为，on mouse hover和 on long pressed事件，有些冲突关系

对了，顺便一提，《初见》这首歌，刚刚给我切换来源，直接换人了，现在播放的并不是刘美麟唱的，是翻唱。
有解决办法么

**Comment by ameaninglessname** [comment]
歌曲问题解决了，之前是在小蜗音乐搜索添加，播的有问题，刚刚在小苟音乐重新搜索，正常了，应该是小蜗的版权没了哈哈哈

**Comment by lyswhut** [comment]
可以录个屏或GIF吗？

**Comment by ameaninglessname** [comment]
> 
> 
> 可以录个屏或GIF吗？

![tooltip issue](https://user-images.githubusercontent.com/20263103/132941804-bcf5e97d-9db0-4181-903b-fd0d0b5ce4d1.gif)

**Comment by lyswhut** [comment]
你这是长按着是吧？
我这边也这样，不知道是不是electron的问题，鼠标长按后，即使鼠标没有移动，仍会触发mouse move事件，
下个版本稍微做下处理就行了

**Comment by ameaninglessname** [comment]
> 你这是长按着是吧？
> 我这边也这样，不知道是不是electron的问题，鼠标长按后，即使鼠标没有移动，仍会持续触发mouse move事件，
> 下个版本稍微做下处理就行了

是的，长按，Nice～

**Comment by lyswhut** [comment]
已在v1.14.0修复
