### ISSUE TITLE
我的列表中不显示歌单内的歌曲列表

### ISSUE THREAD

**Issue by icemanpro** [lyswhut/lx-music-desktop#628]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

在“歌单”中点击“播放”，可以正常播发，但在“我的列表”中看不到这歌单中歌曲列表。重启程序后，可以直接播放，但“我的列表”中依然看不到歌曲列表。

**预期行为**

**截图**

![微信截图_20210913134120](https://user-images.githubusercontent.com/1924688/133029767-e27a5d80-2b5c-4e7b-8e45-720a2a692f53.png)

**环境：**
  -操作系统及版本：[Windows 2019]
  -软件安装包及版本：[1.13.0]

**其他内容**

**Comment by buvta** [comment]
希望添加“定位”功能 #616

**Comment by lyswhut** [comment]
歌单的播放按钮、排行榜的播放按钮都不会将歌曲添加到试听列表，这种播放方式无法查看列表歌曲
定位当前播放歌曲相关问题：
https://github.com/lyswhut/lx-music-desktop/issues/369
https://github.com/lyswhut/lx-music-desktop/issues/436

**Comment by lyswhut** [comment]
v1.16.0起已允许进入临时播放列表，即：使用歌单详情页、排行榜名称右键菜单的“播放”按钮播放歌曲时，可右击播放封面进入此临时列表
