### ISSUE TITLE
最近出现歌曲长时间加载链接问题

### ISSUE THREAD

**Issue by QuXiang-code** [lyswhut/lx-music-desktop#630]
歌曲一直显示加载歌曲链接，大概几分钟后才开始播放；包括下载也是一直显示获取URL中，几分钟后才下载成功

**Comment by 1059393848** [comment]
![image](https://user-images.githubusercontent.com/63888995/133464380-a6590e10-b4ee-4dd0-a245-b4d44a4ed543.png)
我这里显示无法下载

**Comment by 1059393848** [comment]
![image](https://user-images.githubusercontent.com/63888995/133464606-d3e348bf-e2a0-49bc-82ff-01db37345a8c.png)

**Comment by 1059393848** [comment]
接口显示无法访问，请问怎么办

**Comment by QuXiang-code** [comment]
> 接口显示无法访问，请问怎么办

这种情况单纯是没版权听不了，换一首，尽量用测试接口

**Comment by QuXiang-code** [comment]
解决了，校园网是移动，换成手机热点就可以了

**Comment by 1059393848** [comment]
同校园网问题，校园网联通的，换热点解决了，谢谢
