### ISSUE TITLE
新增歌詞簡繁轉換功能

### ISSUE THREAD

**Issue by Vic-Chang** [lyswhut/lx-music-desktop#631]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

如同設置內的語言語言一樣。

於設置>歌詞設置內新增 「繁體中文」 選項，勾選後顯示歌詞時將簡體中文之歌詞轉為繁體中文顯示。

**Comment by lyswhut** [comment]
当设置繁体中文时，自动转繁体歌词会不会好点？

**Comment by Vic-Chang** [comment]
> 当设置软件语言设置为繁体中文时，自动转繁体歌词会不会好点？

這樣也是很棒的設計。其實我一開始就是以為只要設置內的「語言」選擇繁體中文後，歌詞也將自動轉為繁體中文。

但看到無反應後才發覺這可能只是單純的 UI 語言設置。

如果未來這個 Feature 能跟設置的「語言」合併的話也是很淺顯易懂的。

**Comment by lyswhut** [comment]
包含此功能的测试版：https://github.com/lyswhut/lx-music-desktop/actions/runs/1248284416
此功能预计包含在v1.14.0的更新中

**Comment by lyswhut** [comment]
已在v1.14.0正式添加此功能
