### ISSUE TITLE
有安卓版么

### ISSUE THREAD

**Issue by Oliver-WYF** [lyswhut/lx-music-desktop#635]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by cresentboy** [comment]
有的，你看看作者主页面就知道了。。。

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-mobile
