### ISSUE TITLE
我不小心删了一个收藏夹，怎么恢复。。。。

### ISSUE THREAD

**Issue by Light--** [lyswhut/lx-music-desktop#637]
急，，，在线等。。。
 ubuntu版本  1.12.2

攒了好久的喜欢的歌，全选播放点成了全选删除，，，，我太难了。。。

**Comment by lyswhut** [comment]
不小心删掉了歌单？如果没有备份的话，那找不回了。。

**Comment by Light--** [comment]
> 设置底部有备份与恢复

自动定时备份不好么。。为啥需要我操作
