### ISSUE TITLE
下载完成的音乐无法使用洛雪播放？

### ISSUE THREAD

**Issue by wstansea** [lyswhut/lx-music-desktop#64]
**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
不支持添加播放本地音乐，详情看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD
