### ISSUE TITLE
在歌曲详情页添加音量控制条

### ISSUE THREAD

**Issue by hlc1209** [lyswhut/lx-music-desktop#646]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

在歌曲详情页添加音量控制条

**描述您考虑过的替代方案**

**其他内容**

比较喜欢开着详情页看歌词，详情页界面中没有音量调节的话颇有不便

**Comment by lyswhut** [comment]
已在v1.16.0添加
