### ISSUE TITLE
有个大神改编了您开发的应用程序，促进大神之间的学习与交流

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#648]
有个大神改编了您开发的应用程序，可以下载.flac。
在下方链接中，促进大神之间的学习与交流。
https://www.sixyin.com/544.html

**Comment by lyswhut** [comment]
主要扩展了一个接口而已，如果你有接口也可以扩展

**Comment by 1457384613gh** [comment]
> 主要扩展了一个接口而已，如果你有接口也可以扩展

为什么五音的接口可以下载更多.flac，而您的不行啊？好不容易出现一首歌，有.flac的选项，结果下载下来还是mp3文件。
