### ISSUE TITLE
咪咕源失效

### ISSUE THREAD

**Issue by jackdafu** [lyswhut/lx-music-desktop#65]
咪咕：接口失效了，URL过期
酷狗：VIP完整只能下128K，VIP试听（如：周杰伦）以及需购买专辑（如：YOUNG -蔡徐坤）经测试，都无法下。
网易：能下128K，需购买专辑（如：王晨艺）不能下载
QQ：VIP（试听+完整）与需购买专辑全都能下128K，何时能下无损

国内七大收了6个，干脆把最后一个的虾米也收了吧！

——版本v0.9.1 @lyswhut

**Comment by lyswhut** [comment]
谢谢反馈！
1. 咪咕失效问题之前已收到反馈，已确认是由接口改动后，软件处理逻辑没有更改导致的，这将在下个版本修复；
2. 酷狗源问题是由于接口失效导致的，请耐心等待接口修复；
3. 由于接口只支持网易、QQ的128k，这不是软件的问题，后面如果接口支持其他音质软件将会同步开放；
4. 由于目前接口不支持虾米URL的获取，所以软件没收录虾米，后续看情况添加。

**Comment by jackdafu** [comment]
作者回复迅速！网易的接口API，128k先不谈，需购买专辑的音乐下载是真的没辙？

**Comment by lyswhut** [comment]
经测试酷狗源恢复了，
我也不懂哪些需要购买专辑，想听哪首歌直接搜，这个源听不了就换一个，只要能听就行了，
再者有些源的歌曲听不了也是接口那边的问题，这跟QQ网易不支持非128K音质是一个道理。

**Comment by lyswhut** [comment]
咪咕源失效问题已在`0.10.0`修复
