### ISSUE TITLE
音乐播放没有声音

### ISSUE THREAD

**Issue by github2sean** [lyswhut/lx-music-desktop#650]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

电脑 是 MAC pro 13 ,音乐播放没有声音，但是QQ音乐播放就有声音，不知道内置的是什么音乐播放器，网上找了一个办法说是执行 sudo kill -9 `ps ax|grep 'coreaudio[a-z]' |awk '{print $1}'` 后可以，实验确实有效，但是过一段时间播放仍然没有声音，不知道算不算bug! 然后下了同样开源的 yesMusic 也是没有声音，QQ，酷我，播放有声音，不清楚是不是系统的问题还是软件的问题。

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]

**其他内容**

**Comment by lyswhut** [comment]
尝试调整进度条上方的音量条，或者去设置选择音频输出设备，若这些都无法解决，那这可能是你系统或electron的问题

**Comment by awi668** [comment]
> 尝试调整进度条上方的音量条，或者去设置选择音频输出设备，若这些都无法解决，那这可能是你系统或electron的问题

不知道什么时候把声音关完了，看到这里解决了！

**Comment by 437049211** [comment]
apple M1 偶尔会出现播放没有声音，其他软件播放音乐正常，重启就能解决。o(╥﹏╥)o

**Comment by MissGS** [comment]
> 尝试调整进度条上方的音量条，或者去设置选择音频输出设备，若这些都无法解决，那这可能是你系统或electron的问题

在设置>播放设置>音频输出 改变输出设备 已经解决😊
