### ISSUE TITLE
收藏，歌单提供搜索功能

### ISSUE THREAD

**Issue by DavinciDevil** [lyswhut/lx-music-desktop#651]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

如标题，希望在收藏，歌单处提供独立的搜索功能

**描述您考虑过的替代方案**

**其他内容**

**Comment by Cra2yChan** [comment]
能在搜索歌单吗？比如我想搜索带“粤语”字眼的歌单，请问是否有这个功能呢？
