### ISSUE TITLE
桌面歌词无法移动到副屏幕

### ISSUE THREAD

**Issue by phoben** [lyswhut/lx-music-desktop#654]
当拥有两个显示器时，桌面歌词无法使用鼠标移动到副屏幕；
此时用WIN自带快捷键 Win + Shift + ← 可以强制移到另一块屏幕，但是只要鼠标点击歌词，就会自动回到主屏幕！

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/430
