### ISSUE TITLE
無法更新

### ISSUE THREAD

**Issue by PC3500** [lyswhut/lx-music-desktop#66]
**描述错误**
按"立即重啟更新",然後他卸載了,然後就沒有然後了
**重现**
重现行为的步骤：
1.跳出更新訊息
2.按"立即重啟更新"
3.然後他卸載了
4.然後就沒有更新了...

**预期行为**
應該要更新完,然後自動開啟新版的阿

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**环境：**
  -操作系统及版本：Windows 10 64位 18362.418
  -软件安装包及版本：lx-music-desktop-v0.8.0-x64_x86

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
你安装的时候是不是以管理员权限安装的？卸载后没有管理员权限安装不了的原因。。

**Comment by PC3500** [comment]
對，但希望以後版本能自動偵測安裝路徑，不然我全家一起用的，還要一個一個裝(更新)很麻煩

lyswhut <notifications@github.com> 於 2019年10月30日 週三 下午8:55 寫道：

**Comment by lyswhut** [comment]
你别装在C盘就好了，这样自动安装时就不需要管理员权限，
或者装在你用户名的文件夹下（软件默认的安装路径）也可以，
现在你可以卸载掉重装，如果装在C盘就直接默认路径就好，或者装在其他盘
