### ISSUE TITLE
触摸屏无法移动桌面歌词

### ISSUE THREAD

**Issue by mohuanzun233** [lyswhut/lx-music-desktop#660]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

触摸屏无法移动桌面歌词

**重现**
重现行为的步骤：
1.打开“ 桌面歌词”
2.无法移动
4.看到错误

**预期行为**

触摸屏可以移动歌词

**截图**

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]
windows10 64位 21H2
1.14.1安装版

**其他内容**

**Comment by mohuanzun233** [comment]
@lyswhut 报告作者，已测试，歌词的移动已经可以使用，可是大小的切换还是无法进行，不清楚是不是我的操作问题（不懂弄）。

**Comment by lyswhut** [comment]
拖动歌词窗口的边缘才是调整大小
