### ISSUE TITLE
建议出安卓版本的客户端

### ISSUE THREAD

**Issue by thirteen13Floor** [lyswhut/lx-music-desktop#665]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by cresentboy** [comment]
安卓版本不是早就有了吗，看看人家的主页有那么难吗
