### ISSUE TITLE
GNOME下无法与系统媒体控制集成

### ISSUE THREAD

**Issue by 2o181o28** [lyswhut/lx-music-desktop#667]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

完全无法与系统媒体控制集成。二分到是[更新 Electron 到 v15.2.0](https://github.com/lyswhut/lx-music-desktop/commit/8b0fc9bf5f7f12417c767fdab469cf568bc1f03b)这次commit引入的问题。估计是新版本electron的bug。

不知道Windows下的系统媒体控制是显示在什么地方的，故不清楚这个Bug在Windows上有没有。

**环境：**
  -Ubuntu 20.04
  -lx-music-desktop 1.15.0

**Comment by lyswhut** [comment]
此问题已在v1.15.1修复
