### ISSUE TITLE
是否可以添加支持导入YouTube播放列表

### ISSUE THREAD

**Issue by iSkyJIE** [lyswhut/lx-music-desktop#668]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**Comment by lyswhut** [comment]
抱歉，目前没有支持这个功能的打算
