### ISSUE TITLE
UI 问题

### ISSUE THREAD

**Issue by aaronlinus** [lyswhut/lx-music-desktop#669]
自更新至1.15版本过后UI出现浓厚的黑宽边，还有内容模糊( please refer to link below for image).
https://mega.nz/file/YdUQWJRL#GRPesMjX5GmCltMJGAo4wD8zasIjAwPcWgeWbI4GcNY

**Comment by lyswhut** [comment]
是更新到electron v15导致的，某些win 10系统会出现这个问题，
你可以尝试更新显卡驱动或者将系统更新到最新，我这边的win 10 21H1没有这个问题

**Comment by aaronlinus** [comment]
嗯，如你所说的添加了 -dha 过后问题已解决， 谢谢 ：）



> 是更新到electron v15导致的，某些win 10系统会出现这个问题， 你可以尝试更新显卡驱动或者将系统更新到最新，我这边的win 10 21H1没有这个问题 对于这个版本你还可以尝试添加`-dha`或`-dt`等启动参数看看能否解决
