### ISSUE TITLE
制作移动端

### ISSUE THREAD

**Issue by conkyliu** [lyswhut/lx-music-desktop#67]
考虑到用户的便捷性，想参与开发移动端的开发，本人技术栈是react+dva+antd+rn+小程序，如果可以的话，麻烦回复下，谢谢。

**Comment by lyswhut** [comment]
非常欢迎大佬的参与！
移动端计划使用RN开发，
但由于目前花在移动端的时间不多，项目环境还没有搭建完成，
等到时候发布后欢迎提交PR哦！
