### ISSUE TITLE
项目拉取下来，你npm run dev 报错怎么解决

### ISSUE THREAD

**Issue by sun-unc** [lyswhut/lx-music-desktop#670]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://cdn.npm.taobao.org/tmp-promise/-/tmp-promise-3.0.3.tgz
npm ERR! 404 
npm ERR! 404  'tmp-promise@https://registry.npm.taobao.org/tmp-promise/-/tmp-promise-3.0.3.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sununc/.npm/_logs/2021-10-31T07_54_50_391Z-debug.log

请问怎解决？感谢

**Comment by lyswhut** [comment]
淘宝源 `npm install` 出现404则一般情况下是当前使用的包还没有被淘宝从npm同步过去，你可以将npm源设置回官方源即可解决，若官方源安装慢可以给npm配代理
