### ISSUE TITLE
绿色版本的更新，只需要上传 app.asar 文件，然后覆盖到旧版本的目录

### ISSUE THREAD

**Issue by zhujinrun** [lyswhut/lx-music-desktop#671]
**描述您想要的解决方案**
绿色版本的更新，只需要上传 app.asar 文件，然后覆盖到旧版本的目录，这样就可以避免重复下载整个软件的压缩包。

**附加图片**
![image](https://user-images.githubusercontent.com/39542198/139617217-de94dd10-f609-4aae-8676-10a9debf8bfa.png)
![image](https://user-images.githubusercontent.com/39542198/139617172-05b68b6e-41ef-4bae-87ca-4274717822a5.png)

**Comment by lyswhut** [comment]
只更新app,asar其实只相当于只更新前端部分的代码，electron没有被更新，在某些情况下会有问题，如果更新了electron，会导致API对不上，并且原生模块的代码是根据electron 内置的nodejs版本去编译的，nodejs ABI对不上将会无法运行。
但如果没有更新electron，只替换这个文件应该不会有啥问题，但还是不建议这要去做。

网盘上的所有安装包都是从GitHub Releases下载后上传的，所以MD5应该也是对得上的，我不打算单独提取这个文件上传。
