### ISSUE TITLE
建议加入p2p和dht功能

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [lyswhut/lx-music-desktop#672]
加入p2p模块可以不使用服务器进行听歌和下载，并且建议是dht，这样在没有中心服务器的环境下也可以用。

参考：btsync

**Comment by lyswhut** [comment]
本软件没有服务器，除了音乐链接的获取，列表内容、音频、图片等数据全部来自对应音乐平台，音频的获取也是根据对应平台上的歌曲ID去获取的音频，P2P的方式与现有工作方式完全不同，不打算去实现
