### ISSUE TITLE
建议PC版试听列表添加清空功能

### ISSUE THREAD

**Issue by Soil5** [lyswhut/lx-music-desktop#673]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

PC版试听列表没有清空功能

**描述您考虑过的替代方案**

建议PC版试听列表添加清空功能

**其他内容**

**Comment by Soil5** [comment]
建议PC版试听列表添加清空功能

**Comment by lyswhut** [comment]
看**常见问题-列表多选**部分进行歌曲多选删除
