### ISSUE TITLE
Mac 更新1.15.0后 控制中心无法显示播放情况

### ISSUE THREAD

**Issue by Interesting993** [lyswhut/lx-music-desktop#675]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
之前用1.14版本，控制中心音乐播放区域能正常显示当前播放情况，同时可以通过耳机操控播放/暂停，前后切换。
更新1.15.0后发现，控制中心的音乐播放区域不再显示当前播放的情况了。如图：
![image](https://user-images.githubusercontent.com/81305677/139780789-06328b2e-f8cc-42c1-aea5-cf5417ec92a1.png)

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

希望能正常播放

**截图**

![image](https://user-images.githubusercontent.com/81305677/139780836-20599c50-e7ab-447d-b48e-739a61bda383.png)

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：1.0.0 安装版]
Mac Book Pro 11.4系统

**其他内容**

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/667

**Comment by lyswhut** [comment]
此问题已在v1.15.1修复
