### ISSUE TITLE
关于“下载完成” 与 音乐无法下载

### ISSUE THREAD

**Issue by FreeXMelody** [lyswhut/lx-music-desktop#676]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

若下载完成栏存在下载历史记录为100% 即下载状态为 【下载完成】的音乐 ， 实际文件夹中对应歌曲并不存在 ， 但重新下载并不会完成， 需要删除这条历史记录才能完成下载。

**重现**
重现行为的步骤：
存在历史记录的情况且对应目录不存在所需下载音乐，点击下载音乐

**预期行为**

判断目录是否存在对应音乐，判断是否下载【完成下载】

**截图**

**环境：**
  -操作系统及版本：Microsoft Windows 10 专业版 Build 19043 64 位
  -软件安装包及版本：1.15.0

**其他内容**

无

**Comment by lyswhut** [comment]
若下载列表存在相同源且同音质或同类型的下载任务，将跳过此任务的创建，不打算添加对文件是否存在的检查，因为这涉及IO操作，比较耗时，如果批量添加下载的话，会造成大量IO操作，导致添加的时候软件会卡顿。

作为代替的解决方案，如果你更改了下载位置或者重新下载歌曲，下载前你可以清空下载列表再进行下载操作

**Comment by FreeXMelody** [comment]
好滴了解了~ ... 感谢答复 希望未来能有更好的解决方案😄
