### ISSUE TITLE
搜索结果添加播放列表功能

### ISSUE THREAD

**Issue by IT-Tagore** [lyswhut/lx-music-desktop#677]
在官方一些软件支持搜索歌手，歌手的歌单支持播放列表。但是落雪只能搜歌，比如我在search里搜索周杰伦，搜索结果全是周杰伦的歌，这时候无法播放下方列表，当点击下方列表一首歌播放时，此时播放完还是会继续播放试听列表里的歌。

**Comment by ltybenet** [comment]
`CTRL + A`

**Comment by lyswhut** [comment]
目前只支持搜索歌曲名，不支持搜索 歌手、歌单、专辑，
播放列表的歌曲看常见问题列表多选部分
