### ISSUE TITLE
可以增加一个最小化后台运行的功能吗？

### ISSUE THREAD

**Issue by josephine-bamboo** [lyswhut/lx-music-desktop#68]
您好：
       使用了这个音乐播放器之后，觉得非常好用，非常方便，音乐源也很多，非常赞叹~
另外，因为听歌的时候，有时候想做一些其他的事情，但是又不想程序显示在任务栏里，所以想问问，是否可以增加一个功能，就是最小化或者关闭时，可以选择是让程序在后台运行的效果呢？就是可以在右下角的隐藏图标里显示就可以了，这样的功能，不知道能不能考虑增加一个呢？

**Comment by lyswhut** [comment]
目前暂无添加最小化到托盘的计划，详情请看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD
