### ISSUE TITLE
昨天更新的M1版本的安装包，无法安装

### ISSUE THREAD

**Issue by AFalseAlarm** [lyswhut/lx-music-desktop#680]
昨天位于蓝奏云盘，在20:26更新的V1.15.2版本的lx-music-desktop-1.15.2-arm64.dmg文件，下载后显示被损坏

**Comment by a1ooha** [comment]
sudo xattr -d com.apple.quarantine /Applications/lx-music-desktop.app

**Comment by AFalseAlarm** [comment]
多谢！

**Comment by AiKier** [comment]
赞，今天1.15.3 也出现这个问题 还好看到了这个提问。
执行命令后解决问题了。

**Comment by minminaya** [comment]
完美，解决问题

**Comment by Honglin22** [comment]
> sudo xattr -d com.apple.quarantine /Applications/lx-music-desktop.app

怎么用啊

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/602
