### ISSUE TITLE
[Bug]: macOS Monterey无法打开软件

### ISSUE THREAD

**Issue by px123zx** [lyswhut/lx-music-desktop#681]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常打开

### 实际行为

您无法打开应用程序“lx-music-desktop”，因为这台Mac不支持此应用程序。

### Lx Music 版本

1.15.2

### 操作系统版本

macOS 12.0.1

**Comment by wdkGitHub** [comment]
我的可以

**Comment by TsVanco** [comment]
“lx-music-desktop” is damaged and can’t be opened. You should move it to the Trash.

m1-pro-chip, Monterey 12.0.1

**Comment by px123zx** [comment]
更新1.15.3后正常打开

**Comment by DaneHou** [comment]
M1 PRO， macOS  Monterey 12.1后，最新的版本不可以用了~（更新之前的1.12的版本好像还能打开的样子， 更新完直接说damage了~最近的几个版本也都不可以用~

**Comment by suliveevil** [comment]
提示已损坏的解决方案：

终端 app 内运行以下代码
```shell
sudo xattr -d com.apple.quarantine /Applications/lx-music-desktop.app
```
就能正常打开使用了

**Comment by DaneHou** [comment]
> 提示已损坏的解决方案：
> 
> 终端 app 内运行以下代码
> 
> ```shell
> sudo xattr -d com.apple.quarantine /Applications/lx-music-desktop.app
> ```
> 
> 就能正常打开使用了

谢谢！

**Comment by bigqlmz** [comment]
> 提示已损坏的解决方案：
> 
> 终端 app 内运行以下代码
> 
> ```shell
> sudo xattr -d com.apple.quarantine /Applications/lx-music-desktop.app
> ```
> 
> 就能正常打开使用了

nice！！！！！
