### ISSUE TITLE
[Feature]: 希望添加K歌功能

### ISSUE THREAD

**Issue by Leijingtao-svr** [lyswhut/lx-music-desktop#683]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望添加K歌功能

### 描述你想要的解决方案

像全民K歌

**Comment by lyswhut** [comment]
抱歉，目前不打算添加这种功能
