### ISSUE TITLE
[Feature]: 歌曲列表导出能不能增加导出txt格式

### ISSUE THREAD

**Issue by sanzhixiong666** [lyswhut/lx-music-desktop#684]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

软件有了导出列表功能，但是导出的格式是lxmc格式，这是洛雪软件专用的文件格式吗？

### 描述你想要的解决方案

能不能增加导出txt格式选项啊，也算一种备份功能，确保自己的歌曲列表不会出现问题，比如，软件突然崩溃或其他原因导致软件中的所有数据、列表清空了就找不到了。。

**Comment by lyswhut** [comment]
已在v1.16.0新增将我的列表导出为TXT、CSV格式的功能，
注：目前不支持将这些格式的备份导入到LX Music中

**Comment by sanzhixiong666** [comment]
太棒了   @来来回回
