### ISSUE TITLE
建议将mac下最小化快捷键改为command+m

### ISSUE THREAD

**Issue by mysalter** [lyswhut/lx-music-desktop#685]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议将mac下最小化快捷键改为command+m，mac电脑大多数软件最小化的快捷键都是cmd+m，建议修改一致，cmd+w通常是关闭窗口，用起来别扭

### 描述你想要的解决方案

建议将mac下最小化快捷键改为command+m，mac电脑大多数软件最小化的快捷键都是cmd+m，建议修改一致，cmd+w通常是关闭窗口，用起来别扭

### 描述你考虑过的替代方案

建议将mac下最小化快捷键改为command+m，mac电脑大多数软件最小化的快捷键都是cmd+m，建议修改一致，cmd+w通常是关闭窗口，用起来别扭

**Comment by lyswhut** [comment]
这些快捷键都是可以自己改的
