### ISSUE TITLE
[Feature]: Mac下菜单栏点击逻辑问题

### ISSUE THREAD

**Issue by Ariczh** [lyswhut/lx-music-desktop#686]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

音乐播放器在开始播放后通常是在后台工作的，使用时通常是选歌后直接点击其他窗口做其他事，而不会特意最小化播放器窗口。
此时如果点击菜单栏图标只会唤出菜单，也没有唤出主界面的选项，必须先选择隐藏主界面后，再次点击图标。

### 描述你想要的解决方案

希望改成当主界面不在前台时点击菜单栏图标直接唤出主界面（类似QQ、微信）。如技术上无法实现，或可考虑在菜单中增加“打开主界面”的选项，用于将主界面切换至前台

### 附加信息

Macos monterey 12.0.1

**Comment by lyswhut** [comment]
你说的菜单栏是指哪里？托盘菜单？
没看到你想要的操作是怎么样的，其他软件的操作又是怎么样的

**Comment by Ariczh** [comment]
写的时候有点混乱了。
我是指mac顶部的菜单栏。
当微信（或者QQ、FDM等）没有关闭、最小化，只是因为切换到了其他应用而不在前台时，点击顶部托盘菜单中的微信icon，会立即唤出微信界面，开始操作，一共操作一次；
当Telegram（或者Parallels Desktop等）没有关闭、最小化，只是因为切换到了其他应用而不在前台时，点击顶部托盘菜单中的微信icon，会唤出一个菜单，点击第一项，开始操作，一共操作两次；
而当lxmusic没有关闭、最小化，只是因为切换到了其他应用而不在前台时，点击顶部托盘菜单中的洛雪icon，会唤出一个菜单，菜单中只能选择隐藏主界面，我需要再点击一次icon才能唤出主界面开始操作，需要操作三次；
这样会真的有点麻烦。

**Comment by lyswhut** [comment]
已在v1.19.0优化
