### ISSUE TITLE
播放列表搜索功能

### ISSUE THREAD

**Issue by 17356282982** [lyswhut/lx-music-desktop#688]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望作者大大能加个和移动版一样的播放列表搜索功能，而不是直接在线搜索

### 描述你想要的解决方案

感谢作者一直以来坚持的免费无广告以及积极维护更新，这样一个聚合类音乐软件可以说是福音

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/651
