### ISSUE TITLE
[Bug]: desktop1.15.2升1.15.3时，被卸载，软件被删除

### ISSUE THREAD

**Issue by zhtzzhsy** [lyswhut/lx-music-desktop#689]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

desktop1.15.2升1.15.3时，被卸载，软件被删除

### 实际行为

desktop1.15.2升1.15.3时，被卸载，软件被删除

### Lx Music 版本

1.15.2

### 操作系统版本

windows 10 21H1

### 附加信息

打开软件提示有新版本，就让其自动更新，前几个版本自动更新总失败，无法下载更新，1.15.2升1.15.3时，很快就下载了，但随后这个软件就没了，所有东西都没了，只好重新下载了最新版本

**Comment by zhtzzhsy** [comment]
desktop1.15.2升1.15.3时，被卸载，软件被删除

**Comment by lyswhut** [comment]
看常见问题-软件更新部分

**Comment by RoyRao2333** [comment]
> 看常见问题-软件更新部分

macOS 12.0.1, M1 Pro, 从1.15.1升级到1.15.3后提示文件损坏无法打开，但是设置里允许了任意来源

![image](https://user-images.githubusercontent.com/31413093/143453293-3b94a0eb-f7ba-4710-8b18-af857caa8862.png)

**Comment by liruishan1995** [comment]
我也是这样直接被卸载了
