### ISSUE TITLE
打开网易云歌单一直在加载中

### ISSUE THREAD

**Issue by blmulang** [lyswhut/lx-music-desktop#69]
问题已解决，是我看错了，以为是网易云id；因为之前用的一个网页版的解析是用网易云账号id去解析自己的歌单的，所以就一看到id就填上自己的账号id了   飘~~~~

-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·-·

**描述错误**
如题，
问题gif图：[传送](https://ibb.co/K9Qwv07)
**重现**
重现行为的步骤：
1.转到“歌单-打开网易云歌单-输入id”
2.点击“→”
3.向下滚动到“没有滚动”
4.看到错误

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
https://ibb.co/K9Qwv07
![录制_2019_11_02_21_04_01_623](https://user-images.githubusercontent.com/48040829/68071456-724bf800-fdb5-11e9-8ad1-67b23684a3ac.gif)

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
歌单ID对应的歌单不存在就打不开，我试了下你这个歌单ID在网页版歌打开，显示404：<https://music.163.com/#/playlist?id=300342835>

**Comment by blmulang** [comment]
> 歌单ID对应的歌单不存在就打不开，我试了下你这个歌单ID在网页版歌打开，显示404：[https](https://music.163.com/#/playlist?id=300342835) ://music.163.com/#/playlist?id=300342835[](https://music.163.com/#/playlist?id=300342835)

没有啊，这个id就是我的歌单啊 0.0
https://music.163.com/#/user/home?id=300342835
![2019-11-02_220033](https://user-images.githubusercontent.com/48040829/68072053-57c94d00-fdbc-11e9-8659-c8eb8b7ceff7.png)

**Comment by blmulang** [comment]
> 歌单ID对应的歌单不存在就打不开，我试了下你这个歌单ID在网页版歌打开，显示404：[https](https://music.163.com/#/playlist?id=300342835) ://music.163.com/#/playlist?id=300342835[](https://music.163.com/#/playlist?id=300342835)

是不是歌单需要设置成为公开的啊  0.0  我好像都设置成隐藏得了；
但是我在这个网上是可以读取的，我邮件发那个网址给作者大大吧，不然这样会有宣传其他家的嫌疑

**Comment by lyswhut** [comment]
肯定要公开啊，不公开怎么读取？

**Comment by blmulang** [comment]
> 肯定要公开啊，不公开怎么读取？


天 我知道是怎么回事了；原来是每个歌单都有一个id  。。。（刚刚发邮件准备标注图片的时候才发现）
呆滞.jpg   
谢谢作者大大，你这个只要输入歌单id就行了，我输的那个id是我的网易云id；晕囖；之前那个网址是输入网易云id解析的；

![2019-11-02_221006](https://user-images.githubusercontent.com/48040829/68072258-b42d6c00-fdbe-11e9-9955-fcf5d81780b2.png)

**Comment by lyswhut** [comment]
是的，你输入整个链接也会自动识别出ID，或者直接输入ID也行
