### ISSUE TITLE
[Feature]: 请取消自动更新模块

### ISSUE THREAD

**Issue by 123leehom** [lyswhut/lx-music-desktop#691]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

# 请取消自动更新模块，不用打开就后台自动下载就行，基本上是下不下来的

### 描述你想要的解决方案

# 请取消自动更新模块，不用打开就后台自动下载就行，

### 描述你考虑过的替代方案

# 请取消自动更新模块，不用打开就后台自动下载就行，

### 附加信息

# 请取消自动更新模块，不用打开就后台自动下载就行，

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/300
