### ISSUE TITLE
[Feature]: 自定义播放列表中，可以点击按照歌手、歌曲名、专辑、时长排序

### ISSUE THREAD

**Issue by rzn848** [lyswhut/lx-music-desktop#692]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

自定义播放列表中，可以点击按照歌手、歌曲名、专辑、时长排序

### 描述你想要的解决方案

自定义播放列表中，可以点击按照歌手、歌曲名、专辑、时长排序

**Comment by lyswhut** [comment]
已在v1.16.0新增此功能，在右击我的列表名后弹出的菜单中使用
