### ISSUE TITLE
[Feature]: 歌单里边添加下载按钮

### ISSUE THREAD

**Issue by virtualvmw** [lyswhut/lx-music-desktop#693]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

歌单里边的列表内的歌能不能增加一个下载按钮

### 描述你想要的解决方案

在歌单里边听的歌还需要在去搜索一下才能下载太麻烦了

**Comment by lyswhut** [comment]
尝试切去设置切换到测试接口
