### ISSUE TITLE
[Bug]: 为何启用了下载，仍不见歌曲边出现下载按钮？

### ISSUE THREAD

**Issue by cxigit** [lyswhut/lx-music-desktop#694]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

lx-music-desktop-v1.15.3-win_x64-green.7z
启用下载后，应该出现下载按钮，可以下载才是的吧？

### 实际行为

![image](https://user-images.githubusercontent.com/91277031/144365186-9bc59145-b791-431e-9264-028ba768ae68.png)

### Lx Music 版本

1.15.3

### 操作系统版本

win10 21h2

**Comment by 43217878** [comment]
设置-音乐来源-选择测试接口。
