### ISSUE TITLE
[Feature]: 什么时候加入账户功能呢，我手机 电脑都在用这个，但是收藏列表却不能同步。。。

### ISSUE THREAD

**Issue by Light--** [lyswhut/lx-music-desktop#697]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

如题你懂

### 描述你想要的解决方案

无缝同步

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/310
作为代替方案你可以使用本地网络的同步功能
