### ISSUE TITLE
新增歌单导入功能

### ISSUE THREAD

**Issue by Lrvineshaw** [lyswhut/lx-music-desktop#7]

**Comment by lyswhut** [comment]
目前找的接口对网易支持不是很友好，该功能待定

**Comment by Wangzhiran** [comment]
后期会考虑导入账号功能吗？

**Comment by lyswhut** [comment]
@Wangzhiran 这个有空可以研究下，账号歌单导入功能。

**Comment by lyswhut** [comment]
打开外部歌单功能已在0.8.0中添加。

目前打开歌单有两种方式：
- 歌单链接解析，软件会自动从链接中提取歌单ID（目前仅适配了网页版的歌单链接）
- 直接输入歌单ID

若遇到链接里存在歌单ID但无法解析的歌单链接，欢迎在本issue列出该链接，我会添加对其解析。
目前不支持直接从账号中导入。

**Comment by g595693877** [comment]
酷狗歌单无法解析    
https://s.kugou.com/3AYRz38uPV3

**Comment by lyswhut** [comment]
@g595693877 由于酷狗用户自建歌单与官方歌单的获取方式不一样，所以不支持酷狗用户自建歌单打开

**Comment by juzer-q** [comment]
解析后建议能批量操作

**Comment by lyswhut** [comment]
@juzer-q 一直都可以批量操作

**Comment by 2498966969** [comment]
还是希望能添加酷狗歌单解析，https://t2.kugou.com/4AiXf78wiV3

**Comment by lyswhut** [comment]
v0.18.0已支持导入酷狗用户自定义歌单

**Comment by CHIKAKANA** [comment]
希望加入 网易云音乐歌单导入 功能

**Comment by xushuhui** [comment]
网易云歌单无法导入，歌单id：2015235754

**Comment by lyswhut** [comment]
目前歌单导入已支持所有平台，现关闭该issue，如果出现无法导入的歌单链接再重开issue

**Comment by AfreyAwsome** [comment]
用的pc版本, 好像没法批量的输入网易云的歌单id啊,几个不同的歌曲id中用啥分割符?试过空格, 输不了, 逗号,分号,识别不了
