### ISSUE TITLE
[Feature]: 建议添加歌单快捷删除歌曲功能

### ISSUE THREAD

**Issue by LYYZZ** [lyswhut/lx-music-desktop#701]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

播放歌单音乐时，如果想删除该音乐需要在列表中找到后点击从列表删除，过于繁琐。

### 描述你想要的解决方案

在"添加当前音乐到..."界面添加一个功能，第一次点击歌单为添加音乐至歌单，再次点击改为从歌单中移除该音乐，参考网易云音乐，酷狗音乐等音乐播放软件播放页面中的“我喜欢”按钮。

### 附加信息

![屏幕截图 2021-12-06 221618](https://user-images.githubusercontent.com/41326810/144861790-91abd1d5-4785-41e7-8639-e1f082dac377.png
![屏幕截图 2021-12-06 221539](https://user-images.githubusercontent.com/41326810/144861837-97541d07-6cf4-49c3-8f42-8914d65230ab.png)
)

**Comment by lyswhut** [comment]
右击播放封面可以快速定位正在播放的歌曲

**Comment by LYYZZ** [comment]
感谢指导



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 下午2:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lyswhut/lx-music-desktop] [Feature]: 建议添加歌单快捷删除歌曲功能 (Issue #701)





 
右击播放封面可以快速定位正在播放的歌曲
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyswhut** [comment]
详情看：https://lyswhut.github.io/lx-music-doc/desktop/faq/hotkey
