### ISSUE TITLE
[Feature]: 黑色主题，搜索结果翻页数字看不清

### ISSUE THREAD

**Issue by ananas-hebo** [lyswhut/lx-music-desktop#702]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![0E6F27B6-F4FF-4ADD-A4DF-5DC254F5843F](https://user-images.githubusercontent.com/5362672/144973974-b48a5306-a7b2-4b15-a2d6-1922f5a4f2c5.png)

### 描述你想要的解决方案

希望换下显眼的颜色

**Comment by lyswhut** [comment]
![image](https://user-images.githubusercontent.com/20365169/144979491-7050a8a1-515d-4b09-a8fb-53bf49eb9759.png)

**Comment by ananas-hebo** [comment]
![A82EA109-80FF-4B1C-9810-A91A9392FC03](https://user-images.githubusercontent.com/5362672/145143736-f9de35cc-9085-46d4-b09d-dc81e4b50167.png)

@lyswhut 
“排行榜”和 "我的列表"的选中也有类似问题，麻烦修改一下，赞。

**Comment by lyswhut** [comment]
由于黑色皮肤的主次主题色太相近了，对目前的主题架构来说，这里改不了，就这样吧

**Comment by ananas-hebo** [comment]
> 由于黑色皮肤的主次主题色太相近了，对目前的主题架构来说，这里改不了，就这样吧

OK
