### ISSUE TITLE
[Feature]: 无法下载无损音乐

### ISSUE THREAD

**Issue by hackingchen** [lyswhut/lx-music-desktop#703]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

每次下载的都是128K的MP3文件

### 描述你想要的解决方案

希望能下载无损文件，FLAC或者APE

**Comment by meinvtuzai** [comment]
无损应该不会，320起码可以有，这个确实可以。

**Comment by wssw2001** [comment]
我也是一样的只有普通音质

**Comment by Jin-bao** [comment]
在很早的版本说过了，版权问题吧，就不提供下载了

**Comment by InoriHimea** [comment]
实质就是通过走代理接口获取下载地址，必须要有带有会员账号的cookie的接口才能下载对应服务，我记得因为被警告，所以公开的应该都暂停了。可以自己搭建自己的接口

**Comment by Jacky-Bruse** [comment]
> 实质就是通过走代理接口获取下载地址，必须要有带有会员账号的cookie的接口才能下载对应服务，我记得因为被警告，所以公开的应该都暂停了。可以自己搭建自己的接口

请教这个有教程吗？

**Comment by iamyx123** [comment]
添加第三方音源可以无损下载 https://www.6yit.com/8498.html

**Comment by Jacky-Bruse** [comment]
> 添加第三方音源可以无损下载 https://www.6yit.com/8498.html

感谢指路，有效，厉害

**Comment by jorismq** [comment]
> 添加第三方音源可以无损下载 https://www.6yit.com/8498.html

感谢大神

**Comment by vehosah** [comment]
链接已经死了

**Comment by vehosah** [comment]
> 添加第三方音源可以无损下载 https://www.6yit.com/8498.html

链接已经死了

**Comment by vehosah** [comment]
> 

我们该怎么做？
