### ISSUE TITLE
[Feature]: 顺序播放，循环播放不播放列表，只播放缓存

### ISSUE THREAD

**Issue by xiaojunbusi** [lyswhut/lx-music-desktop#704]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

随机播放跟顺序播放功能，只能播放之前播放过得缓存，不是列表内（一个列表就点一首，只会一直循环一首）

### 描述你想要的解决方案

正在播放的歌曲想增加一个明亮条显示，我都找不到我听的歌到列表的哪里了

**Comment by lyswhut** [comment]
没看懂你问题描述的意思，
解决方案的描述可以使用右击播放封面快速定位播放的歌曲功能代替

**Comment by xiaojunbusi** [comment]
就是顺序播放列表跟随机播放的功能，他体现在试听列表。假设我在听抖音排行版的音乐里面随便选了一首播放，播放结束他的随机播放是我曾经点过得歌曲（试听列表），不是抖音热歌榜内的列表清单

**Comment by lyswhut** [comment]
在线列表的歌曲需要将它们添加到我的列表才能播放，这是LX的规则，
你还可以看常见问题 播放整个歌单或排行榜 部分
