### ISSUE TITLE
[Feature]: 播放歌单的时候自动将循环模式转为列表循环

### ISSUE THREAD

**Issue by HamiLemon** [lyswhut/lx-music-desktop#707]
### 解决方案检查

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

点了歌单中的播放，过了好一会儿才反应过来在歌单的第一首循环

### 描述你想要的解决方案

播放歌单的时候自动将循环模式转为列表循环

**Comment by lyswhut** [comment]
由于播放整个歌单、排行榜时，实际上是将这些歌曲添加到一个临时的列表播放，这不应该忽略切歌模式的设置；
至于要等一会才播放时因为如果列表被分成了多页时，会等待其他页的歌曲加载完才播放，但这个问题下个版本会解决，解决方式是：先播放已加载的当前页内的歌曲，然后加载其余部分，最后再更新播放列表

**Comment by HamiLemon** [comment]
非常感谢您的回复
