### ISSUE TITLE
[Feature]: 大佬请问原本需要VIP才能听的歌，在这里是怎么听到的，是之前在自己的后端做了备份吗

### ISSUE THREAD

**Issue by lvming6816077** [lyswhut/lx-music-desktop#708]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

大佬请问原本需要VIP才能听的歌，在这里是怎么听到的，是之前在自己的后端做了备份吗

### 描述你想要的解决方案

大佬请问原本需要VIP才能听的歌，在这里是怎么听到的，是之前在自己的后端做了备份吗

**Comment by yuanjingde** [comment]
api解析

**Comment by lyswhut** [comment]
第三方API解析
