### ISSUE TITLE
[Feature]: 排行榜功能支持一键加入播放清单

### ISSUE THREAD

**Issue by mrjesen** [lyswhut/lx-music-desktop#709]
### 解决方案检查

- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题
- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案

### 问题描述

排行榜功能支持一键加入播放清单

### 描述你想要的解决方案

排行榜功能支持一键加入播放清单

### 描述你考虑过的替代方案

排行榜功能支持一键加入播放清单

### 附加信息

排行榜功能支持一键加入播放清单

**Comment by lyswhut** [comment]
使用右击排行榜名字的菜单或者全选添加
