### ISSUE TITLE
[Bug]: 希望音乐列表 每一行 任意位置都触发 右键事件

### ISSUE THREAD

**Issue by zhwandzcx** [lyswhut/lx-music-desktop#712]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

我的列表和收藏列表 分为  行   和  列  ,
希望 每一行 任意位置都触发  右键事件.

### 实际行为

![image](https://user-images.githubusercontent.com/42031122/147930936-c0f6aebc-5ffe-4e6f-8af2-6e80292b1f6b.png)

### Lx Music 版本

1.16.0

### 操作系统版本

win10  1909

**Comment by lyswhut** [comment]
这是故意这么做的，当鼠标变成文本选择状态时，鼠标右击将取消右键菜单的弹出，行为变成复制已选择的文本。
你选中列表内的一些文字，然后在文本内右击后再粘贴一下就知道了
