### ISSUE TITLE
[Bug]: 海外更新1.16后无法使用

### ISSUE THREAD

**Issue by z81220** [lyswhut/lx-music-desktop#713]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

更新后显示api is not found  也没有耳机试听的符号
更新前可以听歌曲网页不能听的歌 现在也不能听了

重新下载1.15.3一直提示无法更新1.16.0

### 实际行为

更新

### Lx Music 版本

1.16.0

### 最后正常的版本

1.15.3

### 操作系统版本

WIN10

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/550
