### ISSUE TITLE
[Bug]: 歌曲切换了，评论没有自动刷新，需要手动点击刷新按钮

### ISSUE THREAD

**Issue by YingYuanCao** [lyswhut/lx-music-desktop#714]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

歌曲切换了，评论没有自动刷新，需要手动点击刷新按钮

### 实际行为

![image](https://user-images.githubusercontent.com/31400166/148005528-c0a4f2fe-8c57-4b97-b5ab-060810b2127c.png)

### Lx Music 版本

1.16.0

### 操作系统版本

Win11

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/444
