### ISSUE TITLE
[Feature]: 不走代理

### ISSUE THREAD

**Issue by Hbisedm** [lyswhut/lx-music-desktop#715]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

windows本地开启代理，但是软件没有选项可以选择不走本地代理，导致我不得不关闭代理才可以听音乐

### 描述你想要的解决方案

增加选项，不走代理

**Comment by lyswhut** [comment]
目前软件设置里的代理仅对接口请求有效，图片、音频、更新等还是走系统代理。下个版本将新增两个代理相关的启动参数：
- `-proxy-server` 设置代理服务器，代理应用的所有流量，例：`-proxy-server=127.0.0.1:1081`（不支持设置账号密码）。注：应用内“设置-网络-代理设置”仅代理接口请求的流量，优先级更高
- `-proxy-bypass-list` 以分号分隔的主机列表绕过代理服务器，例：`-proxy-bypass-list="<local>;*.google.com;*foo.com;1.2.3.4:5678`（与`-proxy-server`一起使用才有效）。注：此设置对应用内接口请求无效

**Comment by lyswhut** [comment]
已在v1.17.0新增，详细使用看FAQ的启动参数部分
