### ISSUE TITLE
[Feature]: 搜索列表支持顺序播放全部搜索结果

### ISSUE THREAD

**Issue by DomiDing** [lyswhut/lx-music-desktop#716]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望搜索列表能够支持顺序播放全部搜索结果

### 描述你想要的解决方案

暂无

**Comment by lyswhut** [comment]
列表多选问题看常见问题 列表多选部分
