### ISSUE TITLE
如何能让软件更绿色便携？

### ISSUE THREAD

**Issue by hozt81413** [lyswhut/lx-music-desktop#717]
windows版怎样才能更便携？能不能把所有配置文件都保存到软件目录而非AppData\Roaming目录？

**Comment by sikongconglu** [comment]
绿色版可以实现把缓存都放在软件根目录吗？而不是放到appdata里面

**Comment by lyswhut** [comment]
目录是可以改，但有两个问题需要考虑：
- 如果改了的话，已经在用的人就会出现问题，不是所有人都知道怎么解决这个更改导致的问题
- 现在各平台各版本的包是统一构建的，需要解决对绿色版的区分打包

现在我能想到的比较好的方法是添加启动参数的形式指定目录，默认还是存在用户目录下，这个方案可以解决以上两个问题，或者你们还有其他idea？

**Comment by sikongconglu** [comment]
> 目录是可以改，但有两个问题需要考虑：
> 
> * 如果改了的话，已经在用的人就会出现问题，不是所有人都知道怎么解决这个更改导致的问题
> * 现在各平台各版本的包是统一构建的，需要解决对绿色版的区分打包
> 
> 现在我能想到的比较好的方法是添加启动参数的形式指定目录，默认还是存在用户目录下，这个方案可以解决以上两个问题，或者你们还有其他idea？

这个方案行

**Comment by hozt81413** [comment]
这简单了，若启动时检测到软件目录下有portable文件夹就把所有文件保存到里面，没有就按默认。

**Comment by lyswhut** [comment]
> 这简单了，若启动时检测到软件目录下有portable文件夹就把所有文件保存到里面，没有就按默认。

这个主意不错，回头我会看看这样做有没有问题

**Comment by lyswhut** [comment]
下个版本将新增：
Windows平台下，若程序目录下存在`portable`目录，则自动使用此目录作为数据存储目录

**Comment by 715670119** [comment]
> 下个版本将新增： Windows平台下，若程序目录下存在`portable`目录，则自动使用此目录作为数据存储目录

感谢大佬，极端绿软强迫症的我表示爱了爱了 @lyswhut ，嗷对了，还有一件事~~软件图标可以更加高大上一点，大佬如果忙的话，您可以征集一下网友的设计投稿，高手在民间哦~

**Comment by lyswhut** [comment]
已在v1.17.0新增

> 软件图标可以更加高大上一点，大佬如果忙的话，您可以征集一下网友的设计投稿，高手在民间哦~

这个看情况
