### ISSUE TITLE
[Feature]: 请问下载歌曲可不可以弄一下音质，想下载无损的

### ISSUE THREAD

**Issue by ssr1282185158** [lyswhut/lx-music-desktop#718]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

请问下载歌曲可不可以弄一下音质，想下载无损的

### 描述你想要的解决方案

请问下载歌曲可不可以弄一下音质，想下载无损的

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749
