### ISSUE TITLE
[Bug]: v1.7.1歌词获取失败

### ISSUE THREAD

**Issue by heaven0324** [lyswhut/lx-music-desktop#719]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

许久未用，发现没有歌词，提示“歌词获取失败”；但是评论区是可以更新的

### 实际行为

歌词获取失败，好像是普遍行为，并非是某几首歌这样

### Lx Music 版本

1.7.1

### 最后正常的版本

1.7.1

### 操作系统版本

win7

### 附加信息

![1](https://user-images.githubusercontent.com/42191777/148242625-e06811ea-dcff-4269-8b5f-0f7723ae2c61.png)
![2](https://user-images.githubusercontent.com/42191777/148242647-662a9d15-8e37-4961-b353-27f5da06b8bb.png)

**Comment by lyswhut** [comment]
升级到最新版本
