### ISSUE TITLE
桌面歌词功能

### ISSUE THREAD

**Issue by heyapei** [lyswhut/lx-music-desktop#72]
大佬，能不能加上一个桌面歌词的功能！工作时间听歌需要桌面歌词配合一下！感谢大佬的贡献

**Comment by lyswhut** [comment]
目前无添加桌面歌词的计划，详情看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD

**Comment by heyapei** [comment]
谢谢

发送自 Windows 10 版邮件应用

发件人: lyswhut
发送时间: 2019年11月9日 17:27
收件人: lyswhut/lx-music-desktop
抄送: heyapei; Author
主题: Re: [lyswhut/lx-music-desktop] 桌面歌词功能 (#72)

目前无添加桌面歌词的计划，详情看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD
