### ISSUE TITLE
[Feature]: APP 名称

### ISSUE THREAD

**Issue by iam3ddy** [lyswhut/lx-music-desktop#720]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![Xnip2022-01-06_06-53-26](https://user-images.githubusercontent.com/21017389/148301345-4643a3b1-fe7e-4563-8359-ba65730547d5.png)

安装的macOS arm版
个人感觉不好看。

### 描述你想要的解决方案

请考虑用洛雪音乐助手.app或洛雪音乐.app

谢谢

**Comment by lyswhut** [comment]
已经尝试修改显示的名称为`LX Music`，但是不知道行不行，可以试试测试版：https://github.com/lyswhut/lx-music-desktop/actions/runs/2084379496

**Comment by lyswhut** [comment]
已在v2.0.0将其修改成`LX Music`
