### ISSUE TITLE
[Feature]: 为什么只能下载128k的音质呢？

### ISSUE THREAD

**Issue by rocker18** [lyswhut/lx-music-desktop#721]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

可以下载320k吗？

### 描述你想要的解决方案

可以下载320k吗？

**Comment by jming0618** [comment]
请问找到解决办法了吗？怎么下载高音质的

**Comment by meinvtuzai** [comment]
不能下载就失去意义了，唉，320应该有，无损不指望

**Comment by youmoxiaozi** [comment]
可以的，刚刚试出来的。
多选要下载的歌曲，右键下载。

**Comment by Macrohard-X** [comment]
> 可以的，刚刚试出来的。 多选要下载的歌曲，右键下载。

只是界面没修改，实际上还是128KB

**Comment by Celcnu** [comment]
同问 是已经关闭这个功能了吗

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/180#issuecomment-622405749
