### ISSUE TITLE
[Feature]: 最新版本不支持MAC OS 10.15.7，能否支持下？

### ISSUE THREAD

**Issue by Kilims** [lyswhut/lx-music-desktop#722]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

当前哪个release版本可以在Mac OS 10.15.7下使用呢？

### 描述你想要的解决方案

支持Mac OS 10.15.7

**Comment by lyswhut** [comment]
根据electron的[文档说明](https://www.electronjs.org/zh/docs/latest/tutorial/support#macos)：

> 支持macOS 10.11 (El Capitan) 以及更高版本

你是否用错安装包？

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/732
