### ISSUE TITLE
[Feature]: 增加列表多选歌曲添加到播放列表

### ISSUE THREAD

**Issue by ab358568** [lyswhut/lx-music-desktop#724]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

各位大大能不能增加列表多选歌曲添加到播放列表，最好能不用选直接播放歌手的所有歌曲(最好不播放重复的歌曲)

### 描述你想要的解决方案

*

**Comment by xl-link** [comment]
unsubscribe




xllink
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 上午8:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lyswhut/lx-music-desktop] [Feature]:  (Issue #724)





 
解决方案检查
  
 我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)，但没有找到解决方案
 
 我已搜索issue列表(https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&amp;q=)，但没有发现类似的问题
  
问题描述
 
各位大大能不能增加列表多选歌曲添加到播放列表，最好能不用选直接播放歌手的所有歌曲(最好不播放重复的歌曲)
 
描述你想要的解决方案
  

  
描述你考虑过的替代方案
 
No response
 
附加信息
 
No response
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xl-link** [comment]
unsubscribe


xllink
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 上午8:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lyswhut/lx-music-desktop] [Feature]:  (Issue #724)





 
解决方案检查
  
 我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)，但没有找到解决方案
 
 我已搜索issue列表(https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&amp;q=)，但没有发现类似的问题
  
问题描述
 
各位大大能不能增加列表多选歌曲添加到播放列表，最好能不用选直接播放歌手的所有歌曲(最好不播放重复的歌曲)
 
描述你想要的解决方案
  

  
描述你考虑过的替代方案
 
No response
 
附加信息
 
No response
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyswhut** [comment]
列表多选问题看常见问题 列表多选部分

**Comment by danshuzhsh** [comment]
ios版本
