### ISSUE TITLE
[Bug]: 在打开桌面歌词后主界面窗口无法选中和操作

### ISSUE THREAD

**Issue by Roverflower** [lyswhut/lx-music-desktop#725]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

打开桌面歌词后，主界面的功能可以继续操作

### 实际行为

当打开桌面歌词后，偶尔会出现无法对软件的主界面进行任何操作，点击界面范围内的区域会选至桌面，但歌词可正常操作；但如果锁定桌面歌词则无法对任何界面进行操作。此问题出现在15.8和16.0中。

### Lx Music 版本

1.16.0

### 操作系统版本

Windows 10 专业版 20H2 19042.1348 Windows Feature Experience Pack 120.2212.3920.0

**Comment by lyswhut** [comment]
似乎是electron的聚焦问题，有时候窗口激活事件没有被触发，这时候你可以随便点一下任务栏的程序切换下应该就行了

**Comment by lyswhut** [comment]
v2.0.0中已移除窗口穿透的管理，此问题应该已得到修复
