### ISSUE TITLE
[Bug]: MAC落雪音乐1.160点击了我的列表后是所有icon都无法点击

### ISSUE THREAD

**Issue by shuaibaobao123** [lyswhut/lx-music-desktop#726]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

打开软件点击我的列表后切换搜索

### 实际行为

无法点击任何信息

### Lx Music 版本

1.16.0

### 最后正常的版本

1.16.0

### 操作系统版本

mac monterey 12.0

**Comment by lyswhut** [comment]
有重现步骤？

**Comment by shuaibaobao123** [comment]
1.删除原先原有软件信息
2.安装最新版信息1.16.0
3.打开软件，点击我的列表，再次点击设置、搜索
实际结果：
无法点击
预期结果：
可以点击操作

**Comment by shuaibaobao123** [comment]
而且每次更新软件都不成功
![image](https://user-images.githubusercontent.com/59220825/149466664-9c8e8fe8-6bfd-454f-bd43-4c1d7fcce853.png)

**Comment by lyswhut** [comment]
> 1.删除原先原有软件信息 2.安装最新版信息1.16.0 3.打开软件，点击我的列表，再次点击设置、搜索 实际结果： 无法点击 预期结果： 可以点击操作

我这边没能重现，是否有录屏？

软件更新现在只有windows安装版才能更新，其他的都会提示更新失败

**Comment by Spider-DT** [comment]
Hello @lyswhut 
---
这边 win10，在Github 上下载的便携版，解压后，软件内：
1. 点击图标没有反应
2. 加载曲库失败
3. 搜索歌曲名后，试听列表中无法播放

**Comment by Snoopy008** [comment]
我也是，搜索歌曲点击单曲双击播放无响应，点击右侧试听按钮也没有响应，点击单个歌单，点击右侧播放是可以播放的，1.16.0版本Mac存在问题，回到版本1.15.1就正常了。

**Comment by shuaibaobao123** [comment]
https://user-images.githubusercontent.com/59220825/149929620-b8f21356-558b-4bd1-9e87-0dfcb6a7589e.mov

复现录屏

**Comment by shuaibaobao123** [comment]
> > 1.删除原先原有软件信息 2.安装最新版信息1.16.0 3.打开软件，点击我的列表，再次点击设置、搜索 实际结果： 无法点击 预期结果： 可以点击操作
> 
> 我这边没能重现，是否有录屏？
> 
> 软件更新现在只有windows安装版才能更新，其他的都会提示更新失败

已经上传复现录屏

**Comment by lyswhut** [comment]
去下载测试版看看：https://github.com/lyswhut/lx-music-desktop/actions

**Comment by lyswhut** [comment]
这个问题应该已过时，现在我先关闭它，仍有问题再反馈
