### ISSUE TITLE
通过歌词调整播放进度

### ISSUE THREAD

**Issue by ljwrnd** [lyswhut/lx-music-desktop#727]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

无法通过拖动歌词改变歌曲播放进度。

### 描述你想要的解决方案

希望能通过拖动歌词改变歌曲播放进度。
![屏幕截图 2022-01-10 181208](https://user-images.githubusercontent.com/97397870/148749318-c329a899-5944-4ffe-b07f-859f65c371a9.png)

拖动歌词后点击右侧播放按钮即可从当前歌词开始播放。

**Comment by lyswhut** [comment]
已在v1.19.0新增，但此功能默认关闭，需到设置开启
