### ISSUE TITLE
歌词滚动进度

### ISSUE THREAD

**Issue by ljwrnd** [lyswhut/lx-music-desktop#729]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

歌词变色进度与滚动进度不一样。

### 描述你想要的解决方案

希望歌词变色与向上滚动同时进行。

**Comment by lyswhut** [comment]
为了减少激活歌词时对视觉的干扰，所以在v1.16.0起添加了延迟歌词的滚动，现在眼睛更容易跟踪激活的歌词，但这可能需要一点时间去适应

**Comment by ljwrnd** [comment]
但是桌面歌词如果只显示单行歌词滚动会有延迟
![屏幕截图 2022-01-16 142611](https://user-images.githubusercontent.com/97397870/149649808-6189c768-9bb6-41b4-af9e-1e0df1ce1987.png)

**Comment by lyswhut** [comment]
桌面歌词可以考虑加个设置去控制是否延迟滚动

**Comment by ljwrnd** [comment]
okok

**Comment by ljwrnd** [comment]
能看看727吗

**Comment by lyswhut** [comment]
> 桌面歌词可以考虑加个设置去控制是否延迟滚动

已在v1.17.0新增该选项



> 能看看727吗

那个先搁置
