### ISSUE TITLE
更新1.16.0版本后，原下载列表被清空

### ISSUE THREAD

**Issue by hnxiaoyuan** [lyswhut/lx-music-desktop#730]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

更新最新版本后，应该保留原来的下载列表

### 实际行为

更新最新版本后，原来的下载列表被清空了。。

### Lx Music 版本

1.16.0

### 操作系统版本

Windows10

**Comment by Hunterfish** [comment]
我重启一下就好了

**Comment by hnxiaoyuan** [comment]
@Hunterfish 我重启了，好像还是空的，，没有恢复。。。

**Comment by lyswhut** [comment]
从什么版本升级上来会出现这个问题？

**Comment by kunbo-Jiang** [comment]
并且切换不到其他页面

**Comment by lyswhut** [comment]
无法切换到其他页面的问题尝试下载测试版：https://github.com/lyswhut/lx-music-desktop/actions
