### ISSUE TITLE
[bug]: mac os桌面歌词出现旧的字体阴影

### ISSUE THREAD

**Issue by ziyun444** [lyswhut/lx-music-desktop#731]
https://user-images.githubusercontent.com/50004679/149071495-4c06a6e8-731c-44ce-9583-84be2b386029.mp4

mac系统下桌面歌词和阴影不同步，从推出桌面歌词功能开始，就一直有这个问题。

**Comment by ziyun444** [comment]
mac系统下桌面歌词和阴影不同步，从桌面启动功能，就一直有这个问题。

**Comment by lyswhut** [comment]
常见问题有记录，这是electron的问题
这个后面可能会修复：https://github.com/electron/electron/issues/32450

**Comment by amazing-bye** [comment]
貌似我把卡拉ok式关了后就没事了

**Comment by wxdhd121** [comment]
我目前使用遇到同样的问题，阴影在调整桌面歌词窗口大小之后会消失，所以可不可以在软件识别为mac版本后，在切换每行歌词的时候刷新一次窗口？
版本1.20.0
![image](https://user-images.githubusercontent.com/46323092/164584824-e9dbdcd6-d198-417c-a0ca-9260ea0631a3.png)

**Comment by lyswhut** [comment]
> 我目前使用遇到同样的问题，阴影在调整桌面歌词窗口大小之后会消失，所以可不可以在软件识别为mac版本后，在切换每行歌词的时候刷新一次窗口？

刷新窗口会闪烁，electron那边也没有好的解决方案，现在这个问题被搁置了，
当然，如果不使用阴影效果，那就不会有这个问题了，后面有空再看看怎么处理吧

**Comment by ZiLoong-L** [comment]
> > 我目前使用遇到同样的问题，阴影在调整桌面歌词窗口大小之后会消失，所以可不可以在软件识别为mac版本后，在切换每行歌词的时候刷新一次窗口？
> 
> 刷新窗口会闪烁，electron那边也没有好的解决方案，现在这个问题被搁置了， 当然，如果不使用阴影效果，那就不会有这个问题了，后面有空再看看怎么处理吧

在最新版本，如果把阴影颜色改为全透明，依然会出现旧字体的阴影残留。

**Comment by zclorne** [comment]
@lyswhut 您好，我的mac上也出现了这个阴影残留问题，也根据已知信息了解了一下。
我的理解是歌词窗体创建的时候根据文字留下了阴影，但并不是每次歌词滚动都会留下阴影，所以频繁刷新或者说重建窗体不是一个好的解决方案。
由于问题就出在窗体创建的一瞬间，那么是否可以先将窗体创建完成，再显示歌词呢？因为根据观察，在切换至下一首歌曲时阴影并不会刷新，仍然还是原有阴影。
不知道我的理解是否有误，也不知道该方案是否具有可行性？

**Comment by SmallMousePP** [comment]
曲线救国 。。。。
<img width="378" alt="image" src="https://github.com/lyswhut/lx-music-desktop/assets/44832826/d0de0da8-9980-4fc8-aa9a-a6285aaf103e">

![image](https://github.com/lyswhut/lx-music-desktop/assets/44832826/00cdf8a0-ec0a-4508-8531-c336632a0021)

但是打开一下客户端就会刷一行歌词阴影，切歌就没了。。

**Comment by lyswhut** [comment]
已在 2.8.0-beta 版做了处理，可以试试是否能解决，如果仍有问题可以直接反馈：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by SmallMousePP** [comment]
- 测试了下默认颜色：
- ![iShot_2024-04-28_10 09 23](https://github.com/lyswhut/lx-music-desktop/assets/44832826/cbb2f931-a48a-4aac-8e00-3845355a767a)
- 设置未播放和阴影为透明效果：
- ![image](https://github.com/lyswhut/lx-music-desktop/assets/44832826/081623f3-3b93-40b4-a1bc-e289ec60be3b)
- 感觉比原来的好很多，但应该还可以优化动画更自然些，辛苦作者了

**Comment by zclorne** [comment]
#1869 已提交PR尝试解决这个问题

**Comment by lyswhut** [comment]
试试最新的beta版，应该已经彻底解决了

**Comment by zclorne** [comment]
> 试试最新的beta版，应该已经彻底解决了

MacOS Sonoma 14.4.1, M1 测试，已正常。 🎉
期待正式版
