### ISSUE TITLE
系统问题

### ISSUE THREAD

**Issue by logicwang** [lyswhut/lx-music-desktop#732]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

安装新版本1.6.0之后现实与mac os版本无法兼容，仅支持11.0以上
显示内容（您使用的是macOS 10.15.7。该应用程序要求macOS 11.0或更高版本。）

### 描述你想要的解决方案

您使用的是macOS 10.15.7。该应用程序要求macOS 11.0或更高版本。
与版本无法兼容

### 描述你考虑过的替代方案

建议更新版本能与老macos系统兼容

### 附加信息

aa

**Comment by lyswhut** [comment]
根据electron的[文档说明](https://www.electronjs.org/zh/docs/latest/tutorial/support#macos)：

> 支持macOS 10.11 (El Capitan) 以及更高版本

你是否用错安装包？

**Comment by logicwang** [comment]
没有，就在这个库里面下载的dmg

**Comment by lyswhut** [comment]
最后可以安装的版本是多少？

**Comment by logicwang** [comment]
emm解决了，现在在云盘那个链接里面下载出来能使用了0.0

**Comment by lyswhut** [comment]
网盘的包也是从release下载后上传的，那应该是你从GitHub下载的过程中安装包损坏了
