### ISSUE TITLE
[Feature]: 不喜欢功能 和喜欢 ❤️ 功能

### ISSUE THREAD

**Issue by he3210** [lyswhut/lx-music-desktop#735]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

1. 添加 "不喜欢" 🚫 按钮。下次如果再播放到该歌曲就自动跳过。数据保存在本地磁盘

2. "喜欢" ❤️ 按钮操作繁琐，需要点击 ❤️  -> 弹窗 -> 选择歌曲列表。
3. "喜欢"后，❤️ 按钮没有任何变化，有时候都不知道收藏了没有，又重新收藏一遍

4. 这 2 个按钮最好能配置全局快捷键

5. 还有一个其它功能。 mac 下可以提供这个配置项吗？  ：关闭在 dock 中展示 icon 
     因为音乐软件一般在后台运行，可以直接把软件入口放到桌面顶部右侧菜单栏

### 描述你想要的解决方案

2. 直接把歌曲加到我的收藏，或提供一个配置项：默认添加的歌曲列表
3. 点击 ❤️后，可以用红色填充按钮

**Comment by lyswhut** [comment]
播放器的心状按钮实际上是一个“添加到...”按钮，已收藏的歌曲在歌曲收藏弹窗中列表名会是灰色，
 "不喜欢"功能、全局收藏的快捷键可以考虑
