### ISSUE TITLE
[Feature]: 希望能出 Android的 apk 包

### ISSUE THREAD

**Issue by crownclownwl** [lyswhut/lx-music-desktop#736]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

很好的软件希望能出 Android的 apk 包

### 描述你想要的解决方案

出 Android的 apk 包

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-mobile
