### ISSUE TITLE
[Feature]: 更新已收藏的在线列表时，始终重新加载，不再使用缓存

### ISSUE THREAD

**Issue by baichenyu** [lyswhut/lx-music-desktop#737]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

更新后应该同步歌单的，而且再次通过链接进入这个歌单歌曲的数目应该能与实际数量一样。

### 实际行为

收藏的歌单更新按钮点击没反应，然后在链接打开处打开该歌单还是收藏时的状态。也就是说两种方法都不能实时获取歌单。

### Lx Music 版本

1.15.0

### 最后正常的版本

无

### 操作系统版本

Windows 10 家庭中文版

### 附加信息

![image](https://user-images.githubusercontent.com/42993779/149859566-8ccc6a48-88f9-4495-abeb-22764b606b71.png)
![image](https://user-images.githubusercontent.com/42993779/149859870-d77e95f3-56b5-4cf1-8994-b98ab2655e1c.png)
![706d534e58d27ddd65f62b8f0adc47b](https://user-images.githubusercontent.com/42993779/149859898-389e71e7-0dad-48e1-b11d-d9b0c4dd88ea.jpg)

**Comment by lyswhut** [comment]
歌单被缓存了，重启软件再点更新即可，下个版本点更新将跳过缓存

**Comment by lyswhut** [comment]
已在v1.17.0解决该问题
