### ISSUE TITLE
[Bug]: 绿色免安装版更新到1.16.0，小秋音乐查询后返回空列表

### ISSUE THREAD

**Issue by Minakami-Mio-Yuko** [lyswhut/lx-music-desktop#739]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

其他音乐源输入查询条件后正常返回列表，唯独小秋音乐返回空列表

### 实际行为

如图，其他音乐源输入查询条件后正常返回列表，唯独小秋音乐返回空列表
![image](https://user-images.githubusercontent.com/57891992/149875198-39543caf-a3e2-4079-bff9-b6e47936c12c.png)
![image](https://user-images.githubusercontent.com/57891992/149875232-94966111-0ba0-446f-af05-00f2d5ded0f8.png)
![image](https://user-images.githubusercontent.com/57891992/149875325-9721d64e-9c98-4766-bbf8-c694b6740076.png)

### Lx Music 版本

1.16.0

### 最后正常的版本

1.16.0

### 操作系统版本

Windows10专业版21H1

**Comment by fff12138848** [comment]
我的1.14.1也有这种情况

**Comment by kongyijilafumi** [comment]
* 我也是这种情况
![image](https://user-images.githubusercontent.com/56569970/150075464-f53c60a2-99f2-4c84-aa54-976b8844b642.png)
![image](https://user-images.githubusercontent.com/56569970/150075525-0e7bf934-72ab-40f9-ba67-29e82f6ee939.png)

**Comment by IceBear-12** [comment]
2022年01月19日，macOS 10.15，LX Music版本1.16.0，同样情况，只有企鹅音乐相关音源无法检索到。

**Comment by lyswhut** [comment]
已在v1.17.0修复
