### ISSUE TITLE
【建议】一点小建议

### ISSUE THREAD

**Issue by YesHub** [lyswhut/lx-music-desktop#74]
1，希望增加歌单搜索功能
2， 希望为搜索结果添加一个随机排序选项。比如搜索某个关键词排序都是一样的，排前面的都已经听腻了，能随机排序就好了。。。
3， 感觉可以像google搜索一样整个【I'm Feeling Lucky】  随机一些不同类目的歌曲。

**Comment by lier1999** [comment]
希望有桌面歌词!!~!!!!!

**Comment by lyswhut** [comment]
@YesHub 
1、歌单搜索可以实现，但感觉用处并不是很大，软件已经内置有各个平台的歌单分类，在歌单界面点击左上角的按钮可以展开歌单分类；
2、由于是调用音乐平台的接口，这些平台并没有这样的功能，变通的方法是可以用随机页数代替，但目前没有做该功能的计划；
3、该功能同第二条一样，这些平台并没有这样的功能，所以该功能无法实现。

**Comment by lyswhut** [comment]
@lier1999 目前无添加桌面歌词的计划，详情看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD
