### ISSUE TITLE
[Feature]: 关于听歌和下载功能的建议

### ISSUE THREAD

**Issue by CloverAn** [lyswhut/lx-music-desktop#740]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

在使用歌单或者随机听歌的时候，如果听到好听的歌曲，需要敲歌曲名，然后才能下载。为了确保下载的是同一首歌，还需要在听一遍。

### 描述你想要的解决方案

在界面下方，歌曲播放控制地方，增加当前歌曲的下载功能，理论上后端接口应该是已经写好的，可能UI上有一些工作量。

**Comment by lyswhut** [comment]
你可能想要的是定位当前播放的歌曲：https://github.com/lyswhut/lx-music-desktop/issues/369

**Comment by CloverAn** [comment]
> 你可能想要的是定位当前播放的歌曲：#369

好的，谢谢。但是这个高亮，并不高亮啊，看不见（尴尬）

**Comment by lyswhut** [comment]
某些主题的高亮确实不明显
