### ISSUE TITLE
[Feature]: VIP等权限 歌曲标识

### ISSUE THREAD

**Issue by FreeXMelody** [lyswhut/lx-music-desktop#741]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

因为经常是为了找到一首VIP歌曲或是源站已经灰掉(下架 \ 无版权   通常是小蜗音乐( wyy )  的歌曲
在歌单中如果可以一眼识别哪些歌曲属于以上描述的情况  , 可以方便的选择音乐进行下载
(嗯其实就是针对VIP歌曲进行下载 , 如果有一个标识也不错

### 描述你想要的解决方案

源平台的显示方式
![Snipaste_2022-01-22_10-18-17](https://user-images.githubusercontent.com/25904979/150621221-7df42284-63ba-49e2-9f88-56158606fc3e.png)
预期效果 呼好像专辑对应不上w...
![Snipaste_2022-01-22_10-20-56](https://user-images.githubusercontent.com/25904979/150621529-b59d7e19-7486-4cc4-b7a0-9b7278b3aa83.png)

### 描述你考虑过的替代方案

歌曲信息似乎无法对应 
或许可以 通过歌手 歌曲 对应的时间 与搜索匹配  
与源平台比较 将可能的权限曲目放在搜索结果的前位.
(歌单中处理的话, 即源站音乐如果有标识 同步标识

### 附加信息

开发者们辛苦啦

**Comment by lyswhut** [comment]
不计划去标识平台无版权歌曲，自动换源功能已存在，当歌曲链接获取失败时自动换源，播放的时候如果出现`try toggle source`就表明正在自动换源
