### ISSUE TITLE
[Feature]: 请教现在只支持kugo歌单了吗？

### ISSUE THREAD

**Issue by youmoxiaozi** [lyswhut/lx-music-desktop#742]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

想导入抑云歌单

### 描述你想要的解决方案

想导入抑云歌单

**Comment by IceBear-12** [comment]
macOS 版本 10.15.7，LXMusic版本1.17.0，同样无法导入WYY音乐歌单，显示倒入失败。
📎：https://music.163.com/playlist?id=85782327&userid=77824913

**Comment by lyswhut** [comment]
歌单导入问题看常见问题解决
