### ISSUE TITLE
[疑问]: 我在更新到1.17.0版本后，新建portable目录，原来的userdata会清空么？

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#744]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我原来用的是x64-setup的安装包，新建portable目录后，软件的歌单数据设置都没了，这还好因为我跟手机重新同步一下就好了。
对于没有用手机端的人来说，这可能是个问题。

我的疑问主要是出于数据安全的考虑，原来的数据是否已被正确移除？
（我用everything搜了，应该是清楚了，只是想确认下）

### 描述你想要的解决方案

最好能把老数据迁移过来

**Comment by lyswhut** [comment]
不会，你可以手动去以下相应目录将数据复制覆盖回`portable/userData`中

> 默认情况下，软件的数据存储在：
>
> Windows：`%APPDATA%/lx-music-desktop`
> Linux：`$XDG_CONFIG_HOME/lx-music-desktop` 或 `~/.config/lx-music-desktop`
> macOS：`~/Library/Application/lx-music-desktop`
> 
> 在Windows平台下，若程序目录下存在`portable`目录，则自动使用此目录作为数据存储目录（v1.17.0新增）。

**Comment by ameaninglessname** [comment]
好的

**Comment by ameaninglessname** [comment]
我升级到1.17.1 setup 64版本时，它自动把软件目录移除的时候，顺便把portable目录也删了，这是符合预期的么？

portable的安装包会删么？还是说安装逻辑是不一样的

**Comment by ameaninglessname** [comment]
歌单的搜索，除了ctrl + f呼出， 有按钮的方式么？

**Comment by lyswhut** [comment]
> 我升级到1.17.1 setup 64版本时，它自动把软件目录移除的时候，顺便把portable目录也删了，这是符合预期的么？

这是给绿色版用的，安装版升级时会先卸载旧版再安装，所以安装版不建议使用这个功能

>  歌单的搜索，除了ctrl + f呼出， 有按钮的方式么？

无
