### ISSUE TITLE
[Feature]: 如何设置为 系统默认播放器

### ISSUE THREAD

**Issue by knItalian** [lyswhut/lx-music-desktop#745]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![截图20220123205857](https://user-images.githubusercontent.com/32791144/150679601-28e0a765-ca04-4e70-a425-19f466d38da4.png)

win10设置里 没有该软件的选项啊 
怎么能设置为默认的音乐播放器

### 描述你想要的解决方案

一键设置为默认播放器

**Comment by lyswhut** [comment]
不支持播放本地音乐，设置默认播放器没意义
