### ISSUE TITLE
[Feature]: 支持苹果m1芯片

### ISSUE THREAD

**Issue by gitstliu** [lyswhut/lx-music-desktop#746]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

支持苹果m1芯片

### 描述你想要的解决方案

支持苹果m1芯片

**Comment by suliveevil** [comment]
看看这个 issue
https://github.com/lyswhut/lx-music-desktop/issues/681#issuecomment-1019284071
