### ISSUE TITLE
[Bug]: Mac M1开启桌面歌词后无法把歌词窗口移动到外接的显示器上

### ISSUE THREAD

**Issue by Jerrywang77** [lyswhut/lx-music-desktop#748]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

[Bug]: Mac M1开启桌面歌词后无法把歌词窗口移动到外接的显示器上

### 实际行为

[Bug]: Mac M1开启桌面歌词后无法把歌词窗口移动到外接的显示器上

### Lx Music 版本

11.5.2

### 操作系统版本

mac m1 11.5.2

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/430
