### ISSUE TITLE
希望在播放 control bar 上添加 播放顺序控制，更方便一些，谢谢

### ISSUE THREAD

**Issue by imotoboy** [lyswhut/lx-music-desktop#75]

**Comment by lyswhut** [comment]
control bar是什么？

**Comment by sandianyue** [comment]
> control bar是什么？

播放的控制条吧😀 是有丶简陋 界面整体还好 很小清新

**Comment by lyswhut** [comment]
音量位置的控制条？
去设置那里切换吧，本来这软件就不是播放器

**Comment by biuabiu** [comment]
> 音量位置的控制条？
> 去设置那里切换吧，本来这软件就不是播放器

他说的应该是类似"随机","顺序","单曲循环"这种播放控制按钮吧

**Comment by lyswhut** [comment]
若想更改歌曲切换方式，需到设置界面更改，目前不计划在音量条旁边添加歌曲切换方式按钮
