### ISSUE TITLE
导入本地音乐播放

### ISSUE THREAD

**Issue by wluckcn** [lyswhut/lx-music-desktop#750]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

是否可以添加本地音乐进行播放？

### 描述你想要的解决方案

支持导入本地音乐，最常用的格式即可

**Comment by X-Kay** [comment]
臣附议

**Comment by xiyank521** [comment]
+1

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by luo-chuan** [comment]
附议

**Comment by weizidong** [comment]
附议

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by sunjun0207** [comment]
对，本地.mp3格式文件，这个无法导入播放

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by oreak** [comment]
居然不能导入本地音乐播放？

**Comment by klaylin** [comment]
有吗有吗

**Comment by oreak** [comment]
> 有吗有吗

暂时没有 已经放弃，转入 网易云音乐 ，目前非常好

**Comment by Manning233** [comment]
强烈建议支持导入本地歌曲功能

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by lyswhut** [comment]
已在v2.0.0新增

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。
