### ISSUE TITLE
[Feature]: 导入歌单不支持华为音乐

### ISSUE THREAD

**Issue by snow212-cn** [lyswhut/lx-music-desktop#756]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

导入歌单不支持华为音乐链接

### 描述你想要的解决方案

添加华为音乐支持
https://portal-drcn.music.dbankcloud.cn/music-apph5-service/h5/index.html#/musicshare/4?id=85844&shareChannel=copyLink

华为、荣耀手机自带音乐，存了太多的歌单，无法导入，很是麻烦

**Comment by lyswhut** [comment]
目前没有支持华为音乐的计划，仅支持kw/kg/tx/wy/mg这几个平台，你可以想办法将歌曲迁移到这些平台再导入
