### ISSUE TITLE
[Bug]:版本1.17.1使用yarn安装electron 9.4.4报404

### ISSUE THREAD

**Issue by ruomubingfeng** [lyswhut/lx-music-desktop#757]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装成功

### 实际行为

![image](https://user-images.githubusercontent.com/45985854/152712149-ee303df4-e327-48ca-8f6d-5dc2044a4e87.png)

### Lx Music 版本

1.17.1

### 操作系统版本

win 10 

### 附加信息

![image](https://user-images.githubusercontent.com/45985854/152712290-fb30504f-2bc6-415d-a645-6a4d921a07dd.png)
https://npm.taobao.org/mirrors/electron
这个链接下的版本最低版本是12.2.3，已经没有9.4.4的版本

**Comment by lyswhut** [comment]
你的锁文件有问题，1.17.1用的electron版本是13.6.8：
https://github.com/lyswhut/lx-music-desktop/blob/e3dddb9288ae00abc6e10c6e2a34c9984e38763b/package.json#L196

**Comment by ruomubingfeng** [comment]
确认了，是package.json文件的问题
