### ISSUE TITLE
[Feature]: 能否在搜索结果列表中高亮显示正在播放的音乐

### ISSUE THREAD

**Issue by baisi525** [lyswhut/lx-music-desktop#759]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![image](https://user-images.githubusercontent.com/52341078/153343964-fd37bb1e-2de4-45d9-bf9a-cc0a2c78e806.png)
这种时候，我不知道正在播放哪一首

### 描述你想要的解决方案

播放列表中没有高亮显示正在播放的音乐

**Comment by ZCShou** [comment]
同样期待可以高亮显示当前播放条目，不仅仅是搜索列表。目前没有一个当前播放列表，导致根本不知道正在播放那些音乐

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/616#issuecomment-1003527187
