### ISSUE TITLE
[Feature]: 通过Scheme URL唤起程序并进行搜索

### ISSUE THREAD

**Issue by mining-id** [lyswhut/lx-music-desktop#761]
lxmusic://search="突然的自我 - 伍佰"

好像不起作用，提示如下：
<img width="811" alt="image" src="https://user-images.githubusercontent.com/94845005/154010252-02f7bba0-0eea-4f9b-a878-da7ce510574c.png">

说明文档：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E5%90%AF%E5%8A%A8%E5%8F%82%E6%95%B0

请问大佬正确的写法是什么呢？感谢！

**Comment by lyswhut** [comment]
目前Scheme URL只支持：
- `songlist/open` 打开歌单
- `songlist/play` 播放歌单
- `music/play` 播放歌曲

启动参数调用与Scheme URL调用是不同的两个东西，目前还不支持使用Scheme URL的方式进行搜索，但可以在下班版本添加它

**Comment by mining-id** [comment]
@lyswhut  哦，感谢大佬回复！
期待可以支持，这样就可以用alfred这种软件快速唤起并搜索了😄

**Comment by lyswhut** [comment]
下个版本与Scheme URL相关的更改：

- 新增Scheme URL对音乐搜索的调用支持
- 新增Scheme URL以url传参的方式调用

文档说明：

## Scheme URL支持

从v1.17.0起支持 Scheme URL，可以使用此功能从浏览器等场景下调用LX Music，我们开发了一个[油猴脚本](https://github.com/lyswhut/lx-music-script#readme)配套使用<br>
脚本安装地址：<https://greasyfork.org/zh-CN/scripts/438148><br>
以下是目前可用的Scheme URL调用方式：

- URL统一以`lxmusic://`开头
- 此技术目前只支持 Windows、Mac系统
- 若无特别说明，源的可用值为：`kw/kg/tx/wy/mg`
- 若无特别说明，音质的可用值为：`128k/320k/flac/flac32bit`

目前支持两种传参方式：

- 通过`data`传参，以经过URL编码的JSON数据传参，例：`lxmusic://music/play?data=xxxx`，其中`xxxx`为经过URL编码后的JSON数据，支持复杂的参数调用
- 通过`URL`传参，适用于简单传参的调用，不需要转成JSON格式，例：`lxmusic://music/search/xxxx`，但仍然需要对数据进行URL编码，只适应于简单参数调用（v1.18.0新增）

### `data`方式传参

以经过URL编码的JSON数据传参，例：`lxmusic://music/play?data=xxxx`，其中`xxxx`为经过URL编码后的JSON数据，JSON数据内容取决于下表的参数部分

| 描述 | URL | 参数
| --- | --- | ---
| 打开歌单 | `songlist/open` | `source<String>`（源，必须）<br>`id<String/Number>`（歌单ID，可选）<br>`url<String>`（歌单URL，可选）其中ID与URL必需传一个
| 播放歌单 | `songlist/play` | `source<String>`（源，必须）<br>`id<String/Number>`（歌单ID，可选）<br>`url<String>`（歌单URL，可选）其中`id`与`url`必需传一个<br>`index<Number>`（播放第几首歌，可选，从0开始）
| 搜索歌曲 | `music/search` | `keywords<String/Number>`（要搜索的内容，必须）<br>`source<String>`（源，可选）
| 播放歌曲 | `music/play` | `name<String>`（歌曲名，必传）<br>`singer<String>`（艺术家名，必传）<br>`source<String>`（源，必传）<br>`songmid<String/Number>`（歌曲ID，必传）<br>`img<String>`（歌曲图片链接，选传）<br>`albumId<String/Number>`（歌曲专辑ID，选传）<br>`interval<String>`（格式化后的歌曲时长，选传，例：`03:55`）<br>`albumName<String>`（歌曲专辑名称，选传）<br>`types<Object>`（歌曲可用音质数组，必传，<br>数组格式：`[{"type": "<音质>", size: "<格式化后的文件大小，选传>", hash: "<kg源必传>"}]`，<br>例：`[{"type": "128k", size: "3.56M"}, {"type": "320k", size: null}]`）<br><br>以下为平台特定参数：<br>`hash<String>`（歌曲hash，kg源必传）<br>`strMediaMid<String>`（歌曲strMediaMid，tx源必传）<br>`albumMid<String>`（歌曲albumMid，tx源专用，选传）<br>`copyrightId<String>`（歌曲copyrightId，mg源必传）<br>`lrcUrl<String>`（歌曲lrcUrl，mg源专用，选传）

### `URL`方式传参

由于URL传参只适用于简单传参场景，所以目前只支持以下功能的调用：

| 描述 | URL | 参数
| --- | --- | ---
| 搜索歌曲 | `music/search/{source}/{keywords}` | `source`（源，可选）<br>`keywords`（要搜索的内容，必须）<br>例：`music/search/kw/xxx`、`music/search/xxx`
| 打开歌单 | `songlist/open/{source}/{id/url}` | `source`（源，必须）<br>`id/url`（歌单ID或歌单URL，必须）<br>例：`songlist/open/kw/123456`

**Comment by lyswhut** [comment]
已在v1.18.0新增此功能

**Comment by mining-id** [comment]
@lyswhut  感谢大神！！！恭祝大神身体健康！！！

**Comment by mining-id** [comment]
做了个alfred workflow，没啥技术含量，小白可以安装使用

<img width="701" alt="image" src="https://user-images.githubusercontent.com/94845005/160272932-58970fbc-26de-44be-88e6-7b78f8a00ddc.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/94845005/160272995-f89211a7-2ce0-48a6-a8e1-c36024f9fe64.png">


### 下载

[lx-music.zip](https://github.com/lyswhut/lx-music-desktop/files/8357167/lx-music.zip)
