### ISSUE TITLE
[Feature]: 一些建设性功能

### ISSUE THREAD

**Issue by reidwang** [lyswhut/lx-music-desktop#763]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

1、增加正在播放列表
2、增加排行榜一键加入到播放列表中

### 描述你想要的解决方案

1、增加正在播放列表
2、增加排行榜一键加入到播放列表中

**Comment by lyswhut** [comment]
> 1、增加正在播放列表

https://github.com/lyswhut/lx-music-desktop/issues/369
https://github.com/lyswhut/lx-music-desktop/issues/616#issuecomment-1003527187

> 2、增加排行榜一键加入到播放列表中

https://github.com/lyswhut/lx-music-desktop/issues/709

**Comment by NR556china** [comment]
这些都有的，排行榜名称右键就可以播放
