### ISSUE TITLE
[Feature]: 提一个小建议

### ISSUE THREAD

**Issue by X-Kay** [lyswhut/lx-music-desktop#765]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

1、手机版、PC版均不能添加本地音频；
2、手机版导入配置文件时，建议增加一个检索功能（如果麻烦，当我放屁）

### 描述你想要的解决方案

1、手机版、PC版均不能添加本地音频；
2、手机版导入配置文件时，建议增加一个检索功能（如果麻烦，当我放屁）

**Comment by lyswhut** [comment]
> 1、手机版、PC版均不能添加本地音频；
以后可能会考虑，目前无计划添加

> 2、手机版导入配置文件时，建议增加一个检索功能（如果麻烦，当我放屁）
没看懂什么意思

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by lyswhut** [comment]
> 就是导入时的【搜索】功能

还是没懂什么意思，而且手机版只支持导入歌单备份文件，不支持导入设置备份

**Comment by lyswhut** [comment]
PC端已在v2.0.0新增添加本地歌曲播放功能
