### ISSUE TITLE
[Feature]: 歌单随机乱序排列

### ISSUE THREAD

**Issue by findstused** [lyswhut/lx-music-desktop#766]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在的列表随机歌曲数量多或者列表多时会不太随机。

### 描述你想要的解决方案

除了升序和降序，可以增加列表中歌曲排列方式为随机乱序，然后顺序播放或列表循环实现随机效果。以前Foobar经常用的排序。

**Comment by findstused** [comment]
还有我的列表创建后就不能排序，这个强迫症啊，一直想拖拽它

**Comment by lyswhut** [comment]
> 现在的列表随机歌曲数量多或者列表多时会不太随机。

随机播放会[随机整个列表播放](https://github.com/lyswhut/lx-music-desktop/issues/249)，已播放的歌曲将不会再参与随机，但如果你不是使用“上一首”、“下一首”功能切歌时，会清空已播放列表

> 还有我的列表创建后就不能排序，这个强迫症啊，一直想拖拽它

https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md#1160---2022-01-01

> 我的列表新增拖动调整位置功能，按住Ctrl键（Mac上对应Command键）的时候将进入“拖动模式”，此时可以拖动列表的位置来调整顺序
