### ISSUE TITLE
[Feature]: 希望可以添加音量控制

### ISSUE THREAD

**Issue by 136887487** [lyswhut/lx-music-desktop#767]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

: 希望可以添加音量控制，有时候只有调整系统音量还是不方便，能在软件里控制音量就好了

使用设备：mac系统

### 描述你想要的解决方案

希望可以添加音量控制

**Comment by lyswhut** [comment]
进度条上方的横条就行音量条
