### ISSUE TITLE
[Feature]: 建议增加播放页滚动歌词字体大小调节

### ISSUE THREAD

**Issue by NR556china** [lyswhut/lx-music-desktop#768]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

播放页面的滚动歌词字体大小是固定的不能调节，建议改为可调节的。像桌面歌词那样。以此来解决歌词有的人觉得小的问题

### 描述你想要的解决方案

在播放详情页（第二页面）的播放栏上面增加歌词控制按钮，点击后可以有第二菜单，调节+/-，以及文本选择

**Comment by lyswhut** [comment]
想在详情页加入设置弹窗，用来控制歌词字体大小、对齐方式等，
但是不懂要把这个打开设置弹窗的按钮放在哪，放在右上角跟控制按钮一起会不好看，放在下面的控制按钮栏又觉得不太合适

**Comment by lyswhut** [comment]
已在v1.19.0新增，详情页内使用键盘的+-即可调整字体大小
