### ISSUE TITLE
下载歌单功能，

### ISSUE THREAD

**Issue by SMTEC886** [lyswhut/lx-music-desktop#77]
比如说， 我现在下载了这个歌单的内容， 一会下载其他歌单的内容

下载完之后这两个歌单的内容会混在一起， 可以不可以添加一个就是那种自动保存歌单名文件夹的功能。

下载歌单的时候u,自动创建一个文件夹， 把歌曲保存到里面

**Comment by lyswhut** [comment]
现在软件没有下载某个歌单的概念，都是全选后混在一起下载的，
这个功能用的不多，时间有限，目前暂不考虑开发

**Comment by getso-guo** [comment]
我是等这个歌单下完了，调整下载地址然后再下。
