### ISSUE TITLE
[Feature]: 建议添加任务栏控制按钮

### ISSUE THREAD

**Issue by Meteor666s** [lyswhut/lx-music-desktop#770]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

任务栏添加任务栏控制按钮
![屏幕截图 2022-02-19 175425](https://user-images.githubusercontent.com/100011081/154796228-52a2bff6-dc11-4ff4-a09d-d6def3f27b71.png)

### 描述你想要的解决方案

任务栏添加任务栏控制按钮
![屏幕截图 2022-02-19 175408](https://user-images.githubusercontent.com/100011081/154796232-cb0e6ab0-01a6-4bab-9521-479ef4f67255.png)

**Comment by lyswhut** [comment]
已在v1.18.0新增此功能
