### ISSUE TITLE
[Feature]: 锁屏任务栏控制

### ISSUE THREAD

**Issue by ebenrose78** [lyswhut/lx-music-desktop#771]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

锁屏状态下，音乐还可以播放，希望能够增加控制按钮

### 描述你想要的解决方案

锁屏状态下还能快进后退暂停

**Comment by lyswhut** [comment]
你确定你说的是说的是PC端？
而且PC也支持锁屏下的切歌

**Comment by ebenrose78** [comment]
是的，就是这种场景。

**Comment by lyswhut** [comment]
Windows 10在锁屏界面时可以正常弹窗播放控制栏的，也可以控制播放器暂停、上下曲：

![image](https://user-images.githubusercontent.com/20365169/184614183-60879aec-9e51-4e42-94e7-27104b1716ce.png)

**Comment by ebenrose78** [comment]
需要打开什么配置信息么？我是WIN10，但是锁屏弹不出控制栏

**Comment by lyswhut** [comment]
我在我电脑以及虚拟机上的win 10都是可以尝试显示的，你们电脑为啥不行我就不知道了

**Comment by ameaninglessname** [comment]
当前版本看已经正常了，不知道啥时候好的：
![image](https://github.com/lyswhut/lx-music-desktop/assets/20263103/4cd54945-409b-43b6-90d2-b62d96cabee6)

Edition	Windows 11 Pro
Version	22H2
Installed on	‎4/‎12/‎2023
OS build	22621.1848
Experience	Windows Feature Experience Pack 1000.22642.1000.0

lx-music : 2.2.2
