### ISSUE TITLE
[Feature]: 接口调用问题

### ISSUE THREAD

**Issue by yanglimo521** [lyswhut/lx-music-desktop#772]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

你好前辈，请问咱们的第三方接口怎么在哪里找啊。
比如我想搜索 “”张学友“” 请问调用的是那个接口。

### 描述你想要的解决方案

无

### 描述你考虑过的替代方案

无

### 附加信息

无

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/359
