### ISSUE TITLE
[Bug]: Windows便携版还是会在C:\Users\XXX\AppData\Roaming目录下生成文件

### ISSUE THREAD

**Issue by hozt81413** [lyswhut/lx-music-desktop#773]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在Windows平台下，使用最新版本，程序目录下存在 portable 目录，则自动使用此目录作为数据存储目录

### 实际行为

在C:\Users\XXX\AppData\Roaming\目录下继续生成lx-music-desktop目录，里面有一空目录Dictionaries，并且删除C:\Users\XXX\AppData\Roaming\lx-music-desktop后下次启动仍会继续生成。

### Lx Music 版本

1.17.1

### 操作系统版本

Windows 11

**Comment by lyswhut** [comment]
这个是Electron相关的问题，即使禁用了拼写检查，此文件夹仍会被创建并自动下载字典，
目前无法阻止此目录自动生成，但可以通过调用 [`setSpellCheckerDictionaryDownloadURL()`](https://www.electronjs.org/docs/api/session#sessetspellcheckerdictionarydownloadurlurl) 将字典下载地址指向一个错误的地址使其下载失败，来阻止字典的下载，相关问题：

- https://github.com/electron/electron/issues/28598
- https://github.com/electron/electron/issues/22995
- https://github.com/electron/electron/issues/32314
