### ISSUE TITLE
[Feature]: 主题能否根据系统的深浅色自动切换？

### ISSUE THREAD

**Issue by loveis0** [lyswhut/lx-music-desktop#774]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在的主题一共有十四套之多，但都不能根据当前系统的浅色模式或深色模式自动切换，比如深色模式的系统，如果当前是亮色主题那还是亮色，它不能系统切到深色模式的同时自动变成深色模式，总不能白天晚上用不同的模式，每次都让用户自己手动切换吧？

### 描述你想要的解决方案

希望能增加一个“跟随系统”的选项

### 描述你考虑过的替代方案

或者让用户自定义浅色和深色各自的主题

**Comment by HaoTian22** [comment]
另外建议任务栏按钮的也能跟随系统主题，不然亮色主题很难看清任务栏控制按钮
![image](https://user-images.githubusercontent.com/48882584/155838960-8401891c-08c8-469b-bf47-59a2464fa415.png)

**Comment by lyswhut** [comment]
已在v1.19.0新增
