### ISSUE TITLE
[Feature]: 歌词显示罗马音

### ISSUE THREAD

**Issue by Meteor666s** [lyswhut/lx-music-desktop#775]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

歌词显示能不能不止能翻译，而是多加一个显示罗马音功能，主要翻译日语、粤语、韩语

### 描述你想要的解决方案

![QQ截图20220225132249](https://user-images.githubusercontent.com/100011081/155659231-08fe22ce-9e56-420e-a1dd-79aad80bd3a4.png)
![QQ截图20220225132547](https://user-images.githubusercontent.com/100011081/155659239-f143af09-730d-4aa7-a984-22297bbe326b.png)

**Comment by lyswhut** [comment]
现有歌词接口只能获取到歌词与翻译，无法拿到其他类型的歌词，如果有人能提供获取这些内容的接口我可以实现它

**Comment by lyswhut** [comment]
得益于`https://github.com/Binaryify/NeteaseCloudMusicApi/pull/1523`，下个版本将支持显示网易源的罗马音歌词

**Comment by lyswhut** [comment]
已在v1.21.0新增网易源罗马音
