### ISSUE TITLE
[Feature]: 在底部翻页添加输入栏，实现快速跳转页数

### ISSUE THREAD

**Issue by shunliu9527** [lyswhut/lx-music-desktop#777]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

每次打开歌单列表的时候都是在第一页，想多翻几页比较慢
想点击末尾处的页数，不小心点到了最后一页的按键

### 描述你想要的解决方案

在底部的页码处添加输入框，可以快速跳转页数
或者改变一下上/下页按键与最前/后一页位置

### 附加信息

![image](https://user-images.githubusercontent.com/49864283/155830725-f42ccf95-9dbf-41b5-b4ea-585141823f34.png)

**Comment by lyswhut** [comment]
你只要记住最外面的是下一页就行了，
至于你说的每次打开歌单都是第一页的问题，可以添加记住上次翻页的功能
