### ISSUE TITLE
[Bug]: 1.18.0 arm版在M1 Max 安装后无法打开，报文件已经损坏

### ISSUE THREAD

**Issue by strivecheng** [lyswhut/lx-music-desktop#778]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望可以打开

### 实际行为

1.18.0 arm版在M1 Max 安装后无法打开，报文件已经损坏。
但是安装非arm版的可以使用

### Lx Music 版本

1.18.0

### 操作系统版本

Macos Monterey 12.2.1

**Comment by simida0852** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/602
