### ISSUE TITLE
[Feature]: 添加歌曲多选功能

### ISSUE THREAD

**Issue by CrazyAMon** [lyswhut/lx-music-desktop#779]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有没有全选功能 方便选取 还有就是能歌单播放 单点就进试听列表离去了 只能点一次上面的播放按键再点下一首 下一首

### 描述你想要的解决方案

歌曲多选 方便删除下载  歌单列表播放

**Comment by lyswhut** [comment]
看常见问题列表多选部分
