### ISSUE TITLE
（已解决）除酷我音乐和聚合外其他搜索无法试听和下载

### ISSUE THREAD

**Issue by enuff** [lyswhut/lx-music-desktop#78]
**描述错误**
除酷我音乐和聚合外其他搜索无法试听和下载

**重现**
1.在搜索面板下
2.选择酷狗音乐、qq音乐、网易音乐...
3.无法找到下载和试听的按钮
4.收藏进试听列表
5.如下面截图所示全部按钮灰色，无法点击

**预期行为**
其他搜索引擎应该可以试听和下载的。

**截图**
![image](https://user-images.githubusercontent.com/39972255/69030302-18346f00-0a12-11ea-9e00-f22eaaf710ba.png)

**环境：**
  -操作系统及版本：Windows 10 64位 17763.737
  -软件安装包及版本：Windows 64位绿色版 0.12.0

**Comment by lyswhut** [comment]
设置-切换接口

**Comment by enuff** [comment]
感谢这么迅速的回复，问题已解决，感谢
