### ISSUE TITLE
[Feature]: 任务栏歌词显示

### ISSUE THREAD

**Issue by Awesome-Shawn** [lyswhut/lx-music-desktop#782]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望添加可以在Windows任务栏常驻歌词显示的功能，桌面歌词太占空间，而任务栏空间充裕，更加美观实用。

### 描述你想要的解决方案

两种方案：
1、可以参考macos系统一款软件LyricsX的效果
2、将现有的桌面歌词功能改进，使其可以只显示播放中的那一句歌词，配合修改字体大小、位置等功能粗略实现其效果

**Comment by lyswhut** [comment]
目前electron没有在win任务栏、mac状态栏设置文本的API
