### ISSUE TITLE
[Feature]: 请增加播放一个“播放全部”功能

### ISSUE THREAD

**Issue by wangb08** [lyswhut/lx-music-desktop#784]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

请增加一个**播放全部**的功能。搜索获得歌曲列表需要一首首地点击播放，这个很不方便。尤其是通过**歌手名**搜索时，一般人往往会直接选取听所有歌曲。而目前版本需要一首一首的单独点击播放。如果加入一个**播放全部**功能就可以方便很多。

### 描述你想要的解决方案

在搜素结果页面加入**播放全部**功能。

**Comment by lyswhut** [comment]
多选问题看常见问题多选部分
