### ISSUE TITLE
[Feature]: 希望增加 我的列表 中的歌曲搜尋

### ISSUE THREAD

**Issue by WZZan** [lyswhut/lx-music-desktop#787]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

mobile版 有列表內的歌曲搜尋，希望PC版也能添加。

### 描述你想要的解决方案

希望增加 我的列表 中的歌曲搜尋

**Comment by lyswhut** [comment]
## 可用的鼠标、键盘快捷操作

- 鼠标**右击**播放栏的歌曲图片封面可以**定位**当前播放的歌曲
- 鼠标**右击**播放栏进度条上的`LRC`按钮可以锁定/解锁桌面歌词
- 歌曲搜索框、歌单链接输入框内鼠标**右击**可以将当前剪贴板上的文字粘贴到输入框内
- 鼠标**右击**搜索界面中的单条搜索历史可以将其移除
- 歌曲列表内的文字在选中后，鼠标**右击**可以复制已选中的文字，此功能只对搜索、歌单、排行榜、我的列表中的列表有效
- 鼠标在播放详情页内**右键双击**可以关闭播放详情页
- 鼠标**左击**播放栏上的歌曲名字可以将它复制
- 在歌单详情页按**退格键**可以返回歌单列表
- 歌曲列表中可以使用`Ctrl`、`Shift`键进行多选，这类似Windows下的文件选择，详情看常见问题列表多选部分
- **在我的列表内可以使用`Ctrl + f`键打开搜索框进行列表内歌曲搜索，搜索框按`Esc`键可以关闭搜索框**
- 在我的列表按住`Ctrl`键可以进入**列表拖动模式**，此时可以用鼠标拖动列表调整列表的位置
- 编辑列表名时按`Esc`键可以取消编辑
