### ISSUE TITLE
为什么下载音乐只有普通音质呀

### ISSUE THREAD

**Issue by CaliInn-Li** [lyswhut/lx-music-desktop#788]
但与此同时播放界面显示可以播放无损(SQ标记)，如果可以下载更高音质的话该怎么操作？
<img width="1130" alt="截屏2022-03-03 上午9 52 06" src="https://user-images.githubusercontent.com/40906144/156481065-6cbe2289-7cc1-4f70-865e-adc45c151e06.png">

**Comment by liazylee** [comment]
应该是版权问题

**Comment by LionZzzi** [comment]
用第三方音乐源就有无损的

**Comment by ZhangHouhou** [comment]
意思是 在线听 可以 无损音质  , 下载确实低音质吗?

**Comment by CaliInn-Li** [comment]
> 意思是 在线听 可以 无损音质 , 下载确实低音质吗?

意思是界面上显示SQ，但是下载选项里却只有普通音质

**Comment by myww0v0** [comment]
> 用第三方音乐源就有无损的

第三方音乐源是啥？其他的音乐平台？

**Comment by DavidSnowd** [comment]
我也很疑惑，只有普通的

**Comment by myww0v0** [comment]
> > > 用第三方音乐源就有无损的
> > 
> > 
> > 第三方音乐源是啥？其他的音乐平台？
> 
> https://www.6yit.com/8498.html 自己看下教程,很简单的

ok谢谢，我看看

**Comment by djzts** [comment]
加入第三方（6音）之后原来的测试接口就不能用了。。。

**Comment by supermt1986** [comment]
我个人比较关心的是在线播放时候的音质是现实的音质，还是说和下载一样是最普通的音质
