### ISSUE TITLE
一直出现connect ECONNREFUSED 127.0.0.1:80，无能播放

### ISSUE THREAD

**Issue by amazing-bye** [lyswhut/lx-music-desktop#789]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常播放

### 实际行为

换dns后不能上网，有开过代理软件，但是不知道怎么清理，退出代理软件依然无济于事。网络换成手机热点后就能正常听歌了。

### Lx Music 版本

1.18

### 操作系统版本

macos12.3 beta3

### 附加信息

不知道有什么办法能够重置一下网络，mac系统的。

**Comment by lyswhut** [comment]
MAC的话，尝试在终端执行下 `Nslookup ts.tempmusic.tk` 看输出什么？

**Comment by amazing-bye** [comment]
ok了，我新加了host后就正常使用了
