### ISSUE TITLE
请问可以给Banner增加自定义字体吗？

### ISSUE THREAD

**Issue by AceCodex** [lyswhut/lx-music-desktop#79]
首先，非常感谢作者的辛勤劳动，这是一款体验很棒的App！我很喜欢它！

这个可能是个任性的要求：请问，App在左上角的"洛雪音乐助手"，可否增加字体样式供使用者自定义字体？

如，在根目录增加font文件夹，启动时程序扫描文件夹中字体文件，如果有则使用文件夹内字体。如果有多个就提醒字体文件混乱，然后使用默认字体；或者让使用者选择使用哪个受支持的字体。

谢谢！

**Comment by lyswhut** [comment]
logo的字体是用ps导出的svg格式，所以软件中显示的logo是以图片的形式显示的，无法用字体更改。
主观上的就将就用吧，这个问题不影响使用。
