### ISSUE TITLE
[Bug]: 1.18.0 版本，AirPods 只有一个有声音，切换到其他软件测试耳机是好的

### ISSUE THREAD

**Issue by zhaoxuezhi** [lyswhut/lx-music-desktop#790]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

1.18.0 版本，AirPods 左耳有声音，右耳没声音

### 实际行为

1.18.0 版本，AirPods 左耳有声音，右耳没声音

### Lx Music 版本

1.18.0

### 操作系统版本

macOS 12.1

**Comment by lyswhut** [comment]
问题解决了吗？
我没使用mac，这个问题我无法帮你

**Comment by zhaoxuezhi** [comment]
已解决，设置下声道就可以了，感谢~

**Comment by zhaoxuezhi** [comment]
> 问题解决了吗？ 我没使用mac，这个问题我无法帮你

已解决，设置下声道就可以了，感谢~
