### ISSUE TITLE
[Feature]: 有没有考虑后期加IOS手机版支持呢

### ISSUE THREAD

**Issue by bingbaicai** [lyswhut/lx-music-desktop#791]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有没有考虑后期加IOS手机版支持呢
thanks 

### 描述你想要的解决方案

有没有考虑后期加IOS手机版支持呢

### 描述你考虑过的替代方案

有没有考虑后期加IOS手机版支持呢

**Comment by lyswhut** [comment]
移动端目前仅支持android，没有支持IOS的计划
