### ISSUE TITLE
[Feature]: 播放页面能不能提供一个全屏的展示效果呢？

### ISSUE THREAD

**Issue by kinggggg** [lyswhut/lx-music-desktop#792]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

在考察了很多个音乐播放器后，发现都没有音乐波形的展示！直到找到了『落雪音乐』！但是其播放页面的窗口不能全屏，不能沉浸式的倾听自己的心爱的音乐

### 描述你想要的解决方案

播放页面能不能提供一个全屏的展示效果呢

**Comment by lyswhut** [comment]
已在v1.19.0新增
