### ISSUE TITLE
[Feature]: 希望添加 只搜尋無損音質 的按鈕

### ISSUE THREAD

**Issue by WZZan** [lyswhut/lx-music-desktop#793]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

在搜尋歌手名時  常會有同樣的歌曲出現(不同音質) 希望能添加選擇音質的選項 

### 描述你想要的解决方案

感謝大佬

**Comment by lyswhut** [comment]
怎么样选择音质？
搜索结果是对应音乐平台返回的，无法控制是否只搜某种音质的歌曲
