### ISSUE TITLE
[Feature]: 能否添加暂停时音量渐变功能

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [lyswhut/lx-music-desktop#794]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

播放/暂停时音量是立即开始/停止的

### 描述你想要的解决方案

像网易云音乐之类的软件播放/暂停时音量是渐入渐出的，能否添加这个功能呢？

**Comment by lyswhut** [comment]
声音淡入淡出需要用到高级音频API，但目前它还存在[一些问题](https://github.com/lyswhut/lx-music-desktop/issues/764#issuecomment-1041291542)，所以这个功能暂不考虑添加
