### ISSUE TITLE
[Bug]: mac版桌面歌词出现残影

### ISSUE THREAD

**Issue by leo-je** [lyswhut/lx-music-desktop#795]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

显示当前歌曲歌词

### 实际行为

显示之前歌曲的歌词残影
![image](https://user-images.githubusercontent.com/29834148/157571812-b64d6a5a-de69-45ca-92c6-6feb4f8279dc.png)

### Lx Music 版本

1.18.0 (1.18.0)

### 操作系统版本

mac Catalina 10.15.7

**Comment by mining-id** [comment]
同样的问题：
![image](https://user-images.githubusercontent.com/94845005/158014906-cdf6280c-7bfd-4741-948b-b1e583d6203a.png)

版本：1.18
操作系统：macos Monterey  12.2.1

**Comment by FFzt** [comment]
<img width="400" alt="Snipaste_2022-03-12_20-36-24" src="https://user-images.githubusercontent.com/37873312/158018184-deebb572-7594-40b5-9a03-92c017039619.png">
同样的问题

**Comment by HsunGong** [comment]
建议先看看之前的issue再提问，不要重复提问。

相关问题见：

LX-desktop：
- https://github.com/lyswhut/lx-music-desktop/issues/261
- 【FAQ文档】https://github.com/lyswhut/lx-music-desktop/issues/261#issuecomment-663931787
- 【部分解决问题】https://github.com/lyswhut/lx-music-desktop/issues/731

Electron：https://github.com/electron/electron/issues/32450

@lyswhut 请问能否将这些相关issue合并？

**Comment by lyswhut** [comment]
@HsunGong 一堆重复的，懒得管了。。。等如果修好了再统一关了吧
