### ISSUE TITLE
[Bug]: 切换不同分辨率的显示器窗口尺寸不能恢复到正常大小

### ISSUE THREAD

**Issue by williamherry** [lyswhut/lx-music-desktop#796]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

打开软件时接外接显示器,软件窗口大小正常, 拔掉外接显示器,由于外接显示器分辨率和笔记本屏幕不同,软件窗口尺寸变大(正常), 再接上外接显示器,软件窗口应该回到正常大小

### 实际行为

软件窗口没有恢复到正常大小

### Lx Music 版本

1.18.0

### 操作系统版本

Windows 10 1909

**Comment by lyswhut** [comment]
你说的步骤顺序我没怎么看懂，建议使用1、2、3等序号来描述，
这个问题看起来是electron/Chromium的问题

**Comment by williamherry** [comment]
后续没再出现这个问题, 可能是偶尔才会出现, 没法稳定复现我先关闭吧
