### ISSUE TITLE
[Bug]: 导入的网易云音乐的歌单右键 <歌单详情页> 跳转地址错误

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [lyswhut/lx-music-desktop#798]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

导入了一个歌单 https://music.163.com/#/playlist?id=7327109165&userid=1062457
，然后重命名了此歌单，右键此歌单 <歌单详情页>，应该跳转到原歌单地址

### 实际行为

实际跳转地址为 https://music.163.com/#/playlist?id=https://music.163.com/#/playlist?id=7327109165&userid=1062457
网页显示 404

### Lx Music 版本

1.18.0

### 操作系统版本

windows 11 Microsoft Windows [版本 10.0.22478.1012]

**Comment by lyswhut** [comment]
已在v1.19.0修复
