### ISSUE TITLE
[Bug]: 音频可视化

### ISSUE THREAD

**Issue by Four-way-Xeon** [lyswhut/lx-music-desktop#799]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在lx设置选择了音频输出设备后一直按我设置的运行

### 实际行为

没开音频可视化：    在设置选择了音频输出设备后一直正常，在win切换成和软件内不同的音频输出后正常。
点开歌曲（之前已经开启音频可视化或者点开歌曲后再开音频可视化）：  会强制切到win选的音频输出并随着我在win的切换而切换。关掉软件再直接播放，不点开歌曲的页面是正常的，一点开歌曲界面就会切换至win里面所选择的音频输出。

### Lx Music 版本

1.18.0

### 操作系统版本

win 10 20h2

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/764
