### ISSUE TITLE
需要付费的数字专辑是不是无法下载与播放？

### ISSUE THREAD

**Issue by GitHubChenLin** [lyswhut/lx-music-desktop#80]
**描述错误**
需要付费的数字专辑是不是无法下载与播放？下载与播放歌曲均显示请求异常。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 ]
  -软件安装包及版本：[例如：Windows 64位绿色版 0.12.0]

**Comment by lyswhut** [comment]
详情看：https://github.com/lyswhut/lx-music-desktop/issues/65
