### ISSUE TITLE
[Feature]: 希望添加播放队列

### ISSUE THREAD

**Issue by DanielToyama** [lyswhut/lx-music-desktop#800]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望添加播放队列问题，否则无法知道与修改稍后播放列表内容

### 描述你想要的解决方案

能够修改稍后播放列表（如QQ音乐此功能
![无标题](https://user-images.githubusercontent.com/53430542/158047505-a847b075-95cb-4f6c-a2be-0cf30bb64a0e.png)
）

**Comment by shaokuuipo** [comment]
支持，这是个实用功能。

**Comment by Greyh4t** [comment]
希望增加，现在搜索歌手出来歌曲后想添加到正在播放的队列中都没办法添加
