### ISSUE TITLE
[Feature]: 能否增加歌单搜索功能

### ISSUE THREAD

**Issue by aboluo12138** [lyswhut/lx-music-desktop#804]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

没有歌单搜索功能，推荐的歌单有时找不到自己喜欢的类型

### 描述你想要的解决方案

增加歌单搜索功能

**Comment by ShiftWang** [comment]
+1

**Comment by Delta-in-hub** [comment]
+1

**Comment by 940850475** [comment]
直接在列表界面Ctrl+F就行啊

**Comment by xiaoqi18** [comment]
希望在歌单页 增加搜索歌单的功能

**Comment by aboluo12138** [comment]
> 直接在列表界面Ctrl+F就行啊

我的意思是能够通过关键字搜索相应歌单

**Comment by lyswhut** [comment]
已在v2.0.0新增
