### ISSUE TITLE
[Feature]: 加入自动播放下一首的功能

### ISSUE THREAD

**Issue by ni94wei1** [lyswhut/lx-music-desktop#806]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在会一直重复播同一首, 好几个版本了.

### 描述你想要的解决方案

播放一个列表,或者歌单的时候, 能够顺序播放下一首

**Comment by sunny7010** [comment]
![image](https://user-images.githubusercontent.com/52040067/159150743-5562af7e-08cd-414a-824e-2f791ba8fad3.png)
b不好意思，但仍建议您检查一下眼睛

**Comment by lyswhut** [comment]
## 音乐播放列表机制

1. 默认情况下，播放搜索列表、歌单列表、排行榜列表的歌曲时会自动将该歌曲添加到“我的列表”的试听列表后再播放，手动将歌曲添加到试听列表，再去试听列表找到这首歌点播放是等价的
2. 如果你想要播放多首歌曲，需要使用多选功能（若不知道如何多选请看常见问题）多选后，将歌曲这些歌曲添加到“我的列表”播放，或使用稍后播放功能播放
3. 第2条适用于搜索列表、歌单列表、排行榜列表、我的列表中的歌曲
4. 对于歌单详情列表，除了可以使用第2条的方式播放外，你可以点击详情页上面的播放按钮临时播放当前歌单，或点击收藏将当前歌单收藏到“我的列表”后再去播放
5. 对于排行榜详情列表，除了可以使用第2条的方式播放外，你可以在右击排行榜名字后弹出的菜单中，播放或收藏整个排行榜，这与第四条的歌单中的播放、与收藏按钮功能一致
6. v1.18.0及之后新增了“双击列表里的歌曲时自动切换到当前列表播放”设置，默认关闭，此功能仅对歌单、排行榜有效

**Comment by ni94wei1** [comment]
> ![图片](https://user-images.githubusercontent.com/52040067/159150759-448e01a6-853c-4eab-ac09-07abff50c805.png) 建议您检查一下眼睛

没事别瞎JB喷  作者说了 1.18.0才加入的功能要去 设置里开.

**Comment by sunny7010** [comment]
呵，1.18都是一个月前的东西了
