### ISSUE TITLE
[Feature]: 全屏状态下功能不完整

### ISSUE THREAD

**Issue by sunny7010** [lyswhut/lx-music-desktop#807]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![Snipaste_2022-03-20_14-18-23](https://user-images.githubusercontent.com/52040067/159151029-ce3ac4e5-f14e-4ab5-bfd4-1a1e32981d79.png)
全屏状态下收回详情的按钮消失，我认为双击右键收回不够方便

### 描述你想要的解决方案

无

**Comment by lyswhut** [comment]
只剩一个关闭详情页按钮在那不好看，或者有什么好的想法？
右上角的关闭详情页按钮我基本不用过，习惯在任意地方双击返回

**Comment by sunny7010** [comment]
可以用左键单击某个位置代替实现，左键相对使用频率更高（我是这样的）

**Comment by lyswhut** [comment]
已在v1.20.0的播放详情页新增退出按钮
