### ISSUE TITLE
[Feature]: 希望公布歌曲搜索接口API

### ISSUE THREAD

**Issue by hfhzzdx** [lyswhut/lx-music-desktop#808]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望作者发布下歌曲搜索接口API,目前在玩QQ机器人,没有找到好用的歌曲搜索接口,希望作者可以提供下软件使用的接口

### 描述你想要的解决方案

RT

**Comment by traceless0929** [comment]
自己去播放器或者官网抓也行啊，或者看下这个项目的源代码自己找下地址呀，开源的代码都在这自己还不会找么

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/359
