### ISSUE TITLE
背景设置

### ISSUE THREAD

**Issue by wwdboy** [lyswhut/lx-music-desktop#809]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前只能设置主题颜色

### 描述你想要的解决方案

能不能增加自定义图片背景功能？

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/256
