### ISSUE TITLE
无法下载无损或320K

### ISSUE THREAD

**Issue by getso-guo** [lyswhut/lx-music-desktop#81]
**描述错误**
无法下载无损或320K

**重现**
100%

**预期行为**
希望能下载无损或320K，最好支持wav的无损格式

**截图**
本地截图不知道怎么上传

**环境：**
mac

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by lyswhut** [comment]
什么源？
不支持wav格式，
不知道怎么传图片就问百度。

**Comment by getso-guo** [comment]
0.12.0版本，网易和qq都是一样，

**Comment by getso-guo** [comment]
320K和无损图标是灰的，点不了

**Comment by lyswhut** [comment]
详情看：https://github.com/lyswhut/lx-music-desktop/issues/65#issuecomment-547538013

**Comment by getso-guo** [comment]
好吧，谢谢
