### ISSUE TITLE
[Bug]: 无法加载网易云中“XXX喜欢的音乐”这种类型的歌单

### ISSUE THREAD

**Issue by O3OTZ** [lyswhut/lx-music-desktop#811]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在打开小芸音乐歌单中输入网易云“XXX喜欢的音乐”歌单分享链接，应为成功加载。

### 实际行为

在打开小芸音乐歌单中输入网易云“XXX喜欢的音乐”歌单分享链接，可为加载失败。

### Lx Music 版本

1.19.0

### 操作系统版本

Windows 21H2

**Comment by lbcmiao** [comment]
好像是因为“XXX喜欢的音乐”是属于私人歌单，没法读取到，暂时可以迂回操作，在电脑版网易云音乐全选“XXX喜欢的音乐”里面的歌曲然后收藏到一个新的空白歌单，然后分享这个新歌单的链接给lx-music加载。

**Comment by duyananbryce** [comment]
需要在歌单链接后面添加页面token

**Comment by O3OTZ** [comment]
> 

没懂添加什么，该怎么添加，谢谢。

**Comment by duyananbryce** [comment]
请查看下面链接中，图中所示的步骤，我按照这个步骤成功了
https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/49799935/165213991-1b9a000f-9f28-47ee-b308-b31fb239a545.png">

**Comment by O3OTZ** [comment]
> 请查看下面链接中，图中所示的步骤，我按照这个步骤成功了 https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md
> 
> <img alt="image" width="1101" src="https://user-images.githubusercontent.com/49799935/165213991-1b9a000f-9f28-47ee-b308-b31fb239a545.png">
谢谢啊。
