### ISSUE TITLE
[Feature]: 试听列表

### ISSUE THREAD

**Issue by buemary** [lyswhut/lx-music-desktop#812]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

可以试听列表中选中歌曲中的删除功能独立出来吗

### 描述你想要的解决方案

![20220325203123](https://user-images.githubusercontent.com/71556783/160121494-58b39911-9cad-4ade-95be-d744ee39c59e.png)

**Comment by lyswhut** [comment]
为什么要放出来？
批量删除可以使用多选功能，看常见问题列表多选部分
