### ISSUE TITLE
[Bug]: 搜索总是卡住

### ISSUE THREAD

**Issue by FangJunpeng** [lyswhut/lx-music-desktop#813]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

以前搜索很流畅

### 实际行为

![image](https://user-images.githubusercontent.com/35372823/160283939-c92b42e7-9ab3-4950-85ce-c95b04f333ac.png)
搜索总是卡住

### Lx Music 版本

1.19.0

### 操作系统版本

win 10 20H2

**Comment by lyswhut** [comment]
你网络的问题，我这边是正常的，尝试切换网络或开代理：https://github.com/lyswhut/lx-music-desktop/issues/94
