### ISSUE TITLE
[Bug]: 配套脚本在网易云音乐 VIP单曲下无操作按钮

### ISSUE THREAD

**Issue by dHvpkntUJa** [lyswhut/lx-music-desktop#814]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

.

### 实际行为

![image](https://user-images.githubusercontent.com/102517173/160376217-ae3f1c46-f8d2-468e-9fff-a3a52b2e832a.png)

### Lx Music 版本

1.19.0

### 操作系统版本

MacOS 12.3

### 附加信息

脚本版本是0.2.8

**Comment by lyswhut** [comment]
下次关于脚本的问题请去脚本仓库提：https://github.com/lyswhut/lx-music-script

**Comment by lyswhut** [comment]
已在v0.2.9修复，更新脚本即可

**Comment by dHvpkntUJa** [comment]
> 已在v0.2.9修复，更新脚本即可

我试了一下，网易云音乐开通会员和没开会员/未登录是不一样的，0.2.9只适用于开通会员的情况
![image](https://user-images.githubusercontent.com/102517173/160418681-6e28793f-22b0-4ddc-afab-050c3cd68b33.png)


在0.2.8基础上改成收藏前面插入比较合适，u-btni-fav，beforebegin
![image](https://user-images.githubusercontent.com/102517173/160417957-97e5a6d4-35c0-4d7c-b857-b05ccdb106d5.png)

**Comment by lyswhut** [comment]
刚才发现了，试试0.2.10

**Comment by dHvpkntUJa** [comment]
> 刚才发现了，试试0.2.10

OK了
