### ISSUE TITLE
[Feature]: VST音效插件支持

### ISSUE THREAD

**Issue by NaughtDZ** [lyswhut/lx-music-desktop#815]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

老早下mp3本地听歌的时代的时候就喜欢给winamp挂一个激励或者其他的vst效果器嘿嘿。希望这个软件也能支持加载vst效果器，最好能支持到vst3 64位的咯。

### 描述你想要的解决方案

类似于winamp或者daw类软件那种，给一个界面可以自己挂载vst音效插件，哪怕只能挂载一个也行。

### 描述你考虑过的替代方案

在lx里下载完歌曲，然后用winamp挂载vst听歌

**Comment by lyswhut** [comment]
查了下相关的库，发现了这个：https://github.com/micbuffa/WebAudioPlugins

看起来这类技术对web audio来说仍不成熟，而且我对这方面不了解，所以这个我暂时先关闭，如果有人感兴趣可以重新打开这个问题讨论或提供PR
