### ISSUE TITLE
[Feature]: 增加升降调功能

### ISSUE THREAD

**Issue by Meteor666s** [lyswhut/lx-music-desktop#816]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有些歌曲升降调会更加好听，能不能增加一个升降调的功能

### 描述你想要的解决方案

有些歌曲升降调会更加好听，能不能增加一个升降调的功能

**Comment by lyswhut** [comment]
- https://github.com/lyswhut/lx-music-desktop/issues/769
不要重复提issue，谢谢合作！
涉及web audio高级API的都先搁置，对这方面不熟悉，看得头大，或者谁有兴趣可以提PR添加
