### ISSUE TITLE
[Feature]: 希望把Mac版的软件名字改成“落雪音乐”

### ISSUE THREAD

**Issue by psspfizlk** [lyswhut/lx-music-desktop#818]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

**希望把Mac版的软件名字改成“落雪音乐”，“lx-music-desktop“这个名字太长了……**

### 描述你想要的解决方案

希望把Mac版的软件名字改成“落雪音乐”，“lx-music-desktop“这个名字太长了……

**Comment by lyswhut** [comment]
已经尝试修改显示的名称为`LX Music`，但是不知道行不行，可以试试测试版：https://github.com/lyswhut/lx-music-desktop/actions/runs/2084379496

**Comment by wjt123125** [comment]
确实，强迫症看这么长的名字，难受

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by lyswhut** [comment]
已在v2.0.0将显示的名字改为`LX Music`
