### ISSUE TITLE
[Bug]: v1.19 搜索页 网易云歌曲 添加到收藏列表 播放提示api not found

### ISSUE THREAD

**Issue by GoldTest** [lyswhut/lx-music-desktop#820]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

[Bug]: v1.19 搜索页 网易云歌曲 添加到收藏列表 播放提示api not found

### 实际行为

[Bug]: v1.19 搜索页 网易云歌曲 添加到收藏列表 播放提示api not found

### Lx Music 版本

1.19

### 最后正常的版本

没有

### 操作系统版本

win 10 21H1 19043.1586

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/550
