### ISSUE TITLE
[Bug]: 窗口尺寸设置对应的字体大小在启动后不生效

### ISSUE THREAD

**Issue by Four-way-Xeon** [lyswhut/lx-music-desktop#824]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

我的窗口尺寸选的是 较小 ，但关闭软件重新打开后软件字体会变大

### 实际行为

自1.19.0开始，软件打开后字体会偏大，在调大窗口尺寸后再调小能与之前版本一样

### Lx Music 版本

1.19.0

### 最后正常的版本

1.18.0

### 操作系统版本

win 10 20h2

### 附加信息

正常（与之前版本一致）
![正常](https://user-images.githubusercontent.com/98648088/162612491-0621daf3-04f3-4c28-bf81-0a5d3a314fa5.png)
现在打开软件：
![软件打开后](https://user-images.githubusercontent.com/98648088/162612536-f5d81d13-787b-4c27-8bc2-6d289842bd6c.png)

**Comment by lyswhut** [comment]
此问题已在测试版中修复：https://github.com/lyswhut/lx-music-desktop/actions
此修复将包含在下个版本中

**Comment by lyswhut** [comment]
已在v1.20.0修复
