### ISSUE TITLE
[Feature]: 单击即可选中歌曲

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#826]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我在想批量删除 试听列表中的歌曲时，
进行了“点击 歌单第一首歌 - shift + 点击 歌单最后一首歌”操作时，发现歌曲并没有被选择上。
而这个操作 在Windows的比如文件浏览器里，是可以的，
然后意识到落雪的设定是“shift + 点击” 才能开始选中歌曲，
就稍微有点反“直觉”。

我不是第一次经历这个情况了，所以想反馈一下，是否需要调整还是看作者大大。

### 描述你想要的解决方案

单击歌曲 即 清除之前选择 + 选择当前歌曲

**Comment by lyswhut** [comment]
LX需要使用多选按键（Shift或Ctrl）才能进入选择模式选择内容，
而Windows下不需要按任何键就可以选中单文件，
所以选择机制会略有不同，这个暂时不打算去改

**Comment by Meteor666s** [comment]
想要删除试听列表的所有歌曲直接ctrl+a不就全选了吗

**Comment by ameaninglessname** [comment]
> 想要删除试听列表的所有歌曲直接ctrl+a不就全选了吗

确实，但也有删除部分列表的时候
