### ISSUE TITLE
[Feature]: 增加在全屏状态下使用Esc退出全屏的功能

### ISSUE THREAD

**Issue by sunny7010** [lyswhut/lx-music-desktop#827]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

如题

### 描述你想要的解决方案

如题

**Comment by lyswhut** [comment]
已在v1.21.0新增
