### ISSUE TITLE
[Feature]: 希望作者坚持自己的想法，不要被各种需求带偏，保持初心，加油！

### ISSUE THREAD

**Issue by 947612227** [lyswhut/lx-music-desktop#828]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

加油！

### 描述你想要的解决方案

加油！

**Comment by lyswhut** [comment]
谢谢支持，但是请不要开与软件问题不相关的issue！
