### ISSUE TITLE
win安装版无法安装

### ISSUE THREAD

**Issue by liowang** [lyswhut/lx-music-desktop#83]
**描述错误**
在下载页面下载好lx-music-desktop-v0.12.0-x64_x86-Setup.exe之后，打开按步骤安装，在选好安装在哪个文件夹之后点安装就会提示安装已终止，安装程序并未成功的运行完成

**截图**
![批注 2019-11-25 130421](https://user-images.githubusercontent.com/58159100/69513917-98b01e00-0f84-11ea-8dc8-bd69cae85d99.png)

**环境：**
  -操作系统及版本：Windows 10 64位 18362.156
  -软件安装包及版本：例如：Windows 64位安装版 0.12

**Comment by lyswhut** [comment]
常见问题的处理方法看了吗？

**Comment by lyswhut** [comment]
@liowang 你是怎么解决的呢？
请不要把问题改成这种没有意义的名字，因为你的问题别人可能也会遇到，这时如果他们刚好看到这个问题，而你又把你的解决方案分享出来，会对他们有很大的帮助，谢谢！

**Comment by liowang** [comment]
问了个常见问题里有解决方法的问题，作者回了句常见问题看了吗，然后我去常见问题里看了下，真有，根据里面的方法最后解决了。这问题没有任何参考价值，所以编辑了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyswhut"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 晚上11:21
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;; 
抄送: "我何必说谎、"<wangzishuosb@vip.qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lyswhut/lx-music-desktop] 已解决 (#83)




@liowang 你是怎么解决的呢？
 请不要把问题改成这种没有意义的名字，因为你的问题别人可能也会遇到，这时如果他们刚好看到这个问题，而你又把你的解决方案分享出来，会对他们有很大的帮助，谢谢！

**Comment by lyswhut** [comment]
并不是没有参考价值，有些人也是不看常见问题的，但可能会在issue这边看到，所以麻烦你还是把问题编辑回去吧
