### ISSUE TITLE
[Feature]: 您好，怎么区分开发环境和生产环境

### ISSUE THREAD

**Issue by puchenhui** [lyswhut/lx-music-desktop#832]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

事件描述：我最近在开发electron过程中，遇到了问题，在git上刚好看到你的项目有用类似的写法，我clone下来打印process.env.NODE_ENV发现是有值，但我的却有问题，不知道是不是我写的有问题。
我的问题：我想在打包的时候，来区分开发环境和生产环境。
我的问题描述：我安装了cross-env组件，并且声明了NODE_ENV，在打包的时候命令是这样的：
```json
"scripts": {
    "build-dev": "cross-env NODE_ENV=development electron-builder --config.directories.output=dev_out",
    "build-prod": "cross-env NODE_ENV=production electron-builder --config.directories.output=prod_out"
  }
```
但打包后，我发现process.env.NODE_ENV是undefind

### 描述你想要的解决方案

我希望在业务逻辑中通过判断process.env.NODE_ENV来区分不同的环境，调取不同的接口

### 描述你考虑过的替代方案

我在项目启动的时候添加`set NODE_ENV=development`，在项目中打印process.env.NODE_ENV是有值的，但在打包的时候这样写，结果却是undefind

### 附加信息

![image](https://user-images.githubusercontent.com/28975452/164129002-a8353e4e-96a3-43ab-a625-6690d5ab36ae.png)

**Comment by lyswhut** [comment]
用了webpack，打包时代码中用到的环境变量名称会被webpack硬编码替换成当时相应的环境变量值，你看我打包命令会发现只在使用webpack打包时才设置`NODE_ENV`

**Comment by puchenhui** [comment]
我对webpack不太懂，我看到您的pack.js和runner-dev.js都在第一个声明了环境，然后在下面写了一些代码，但我感觉在我的项目中，我只想获取到环境变量。我试了你的写法，但不起作用。麻烦您指点一下我，谢谢。
```json
"scripts": {
    "start": "set NODE_ENV=development && electron .",
    "build-dev": "node ./build/dev_build.js && electron-builder --config.directories.output=dev_out ",
    "build-prod": "node ./build/prod_build.js && electron-builder --config.directories.output=prod_out"
  },
```
dev_build.js
```javascript
process.env.NODE_ENV = 'development'
```
prod_build.js
```javascript
process.env.NODE_ENV = 'production'
```

**Comment by lyswhut** [comment]
我设置`process.env.NODE_ENV`是在webpack构建源代码时用的，构建完毕后，当时的环境变量已被写入构建后的代码中，这就是为什么构建成安装包后仍然能拿到当时的环境变量值。

而electron-builder只是帮你安装包，并不会帮你把当时的环境变量写进最终的代码里

**Comment by puchenhui** [comment]
那请问下您，像我这种情况，应该怎么改呢，（我之前没有用webpack，现在为了获取环境变量才装了webpack）

**Comment by lyswhut** [comment]
不用构建工具的话，打包前把所有`process.env.NODE_ENV`替换成你想要的值

**Comment by puchenhui** [comment]
process.env.NODE_ENV在哪修改呢，我试了好几种办法，都不行

**Comment by lyswhut** [comment]
是把你代码中的所有 `process.env.NODE_ENV` **替换** 成相应的值，如果你不想使用打包工具，可以在入口文件设置一个全局变量，打包前再修改，比如开发时 `global.env = 'development'`，打包前去把它改为`global.env = 'production'`再打包就行了

鉴于此问题与LX无关，这样子讨论会给watch本存储库的人发送大量不相关的邮件，所以我现在将关闭本issue，这个话题就此结束，你自己再去研究下吧
