### ISSUE TITLE
[Bug]: 随机播放音乐，它播放的是试听列表中的音乐，而不是其他排行榜或者歌单中的音乐

### ISSUE THREAD

**Issue by xiezhoubin** [lyswhut/lx-music-desktop#833]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

随机播放音乐，它播放的是试听列表中的音乐

### 实际行为

随机播放音乐，应该要是其他排行榜或者歌单中的音乐

### Lx Music 版本

1.20.0

### 操作系统版本

win11

### 附加信息

![image](https://user-images.githubusercontent.com/75734559/164184287-1fe2066b-0176-4517-8ba0-4c18a0e52711.png)

**Comment by lyswhut** [comment]
看常见问题`音乐播放列表机制`说明
