### ISSUE TITLE
[Bug]: x64版本无法安装

### ISSUE THREAD

**Issue by yunlongzhuhuo** [lyswhut/lx-music-desktop#836]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

应该正常安装

### 实际行为

![Snipaste_2022-04-21_14-56-45](https://user-images.githubusercontent.com/88414293/164393150-ab0ffedc-be1c-417a-97cb-0392d870c237.png)
之前没有安装过任何版本的洛雪音乐助手，首次安装就出现问题。

### Lx Music 版本

1.20.0

### 操作系统版本

Windows 10 专业版 21H2

**Comment by lyswhut** [comment]
安装过程中的选项你是怎么选的？

**Comment by yunlongzhuhuo** [comment]
对不起，我打扰到你了，我知道问题出在哪了，是我没用管理员权限。

**Comment by lyswhut** [comment]
建议不要选 为所有用户安装，不然更新的时候可能会出现：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#windows-%E5%AE%89%E8%A3%85%E7%89%88%E5%9C%A8%E5%8D%87%E7%BA%A7%E5%90%8E%E5%8D%B8%E8%BD%BD%E4%BA%86%E6%97%A7%E7%89%88%E6%9C%AC%E4%BD%86%E6%B2%A1%E6%9C%89%E5%AE%89%E8%A3%85%E6%96%B0%E7%89%88%E6%9C%AC
