### ISSUE TITLE
[Feature]: 通过listary打开只有首次能带搜索关键词

### ISSUE THREAD

**Issue by zuohl** [lyswhut/lx-music-desktop#839]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

第一次通过listary打开能带上搜索关键词,已经有进程启动的情况下只是简单打开了lxmusic的窗口

D:\Program Files\lx-music-desktop\lx-music-desktop.exe -search="{query}"
通过如上的方式启动的

### 描述你想要的解决方案

每次打开都能带上参数

**Comment by zuohl** [comment]
通过urlScheme的方式实现了

**Comment by lyswhut** [comment]
目前启动参数只能使用一次，多次调用的话可以通过Scheme URL调用
