### ISSUE TITLE
请问为什么界面里的链接点了没反应？

### ISSUE THREAD

**Issue by star2056** [lyswhut/lx-music-desktop#84]
操作系统：Win7 64位
软件版本：0.11.0
问题：
点击设置界面里的各种连接都没有反应，一般不是应该弹出一个浏览器窗口的吗？
搞得我要截图然后打开浏览器对着截图手打地址……

**Comment by lyswhut** [comment]
什么链接？
关于洛雪音乐里带下划线的文字点击时是可以在浏览器打开的

**Comment by star2056** [comment]
![2019-11-25_223036](https://user-images.githubusercontent.com/26737255/69549277-eef87d80-0fd3-11ea-9887-3626939f31ce.png)
就是图片中带下划线的，我全点了，没有任何反应

**Comment by lyswhut** [comment]
你系统默认浏览器配置是不是有问题？
正常是可以打开的

**Comment by star2056** [comment]
果然是系统默认浏览器没设置好的问题
搞好后已经正常弹出了
对不起，问了个蠢问题打扰作者了
