### ISSUE TITLE
[Feature]: 添加设置开关，隐藏无法播放的条目

### ISSUE THREAD

**Issue by uaex** [lyswhut/lx-music-desktop#843]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有些歌曲虽然搜索到了，但是部分源无法播放(按钮是灰色的)

### 描述你想要的解决方案

添加开关 设置 - 搜索设置 - 隐藏无法播放的项目

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/78
