### ISSUE TITLE
[Feature]: 为啥不能同步我在酷狗音乐里的喜欢歌单

### ISSUE THREAD

**Issue by TUMENG-ANN** [lyswhut/lx-music-desktop#844]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

为什么你们的软件没有一个可以同步各大主流音乐平台的登录按钮的

### 描述你想要的解决方案

我建议应该添加一个各大主流音乐平台的登录按钮，这样方便我们能把酷狗音乐，QQ音乐的歌单同步到本软件里。还有就是登录后把你平常喜欢听的歌按照喜号来给你推荐

### 描述你考虑过的替代方案

就算不能弄这个根据你的喜好来推荐歌曲，也可以把歌单给同步过来吧？

### 附加信息

而且你们这个音乐软件不能自定义背景皮肤吗？弄来弄去都是这几种
![image](https://user-images.githubusercontent.com/102861274/165964016-578a7571-c939-4392-9de2-2ef686b5fc2c.png)

**Comment by lyswhut** [comment]
没有对接官方平台登录接口的打算，所以【根据你的喜好来推荐歌曲】也不会有，

自定义皮肤看：https://github.com/lyswhut/lx-music-desktop/issues/256
