### ISSUE TITLE
[Feature]: 能否为自动更新添加Github镜像站

### ISSUE THREAD

**Issue by penglihuamiao** [lyswhut/lx-music-desktop#845]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

类似于
cithub.icu
hub.fastgit.xyz
都是Github的镜像网站，也同样可以进行文件下载，可以在国内访问
可以访问原版Github，但是速度不过10kb/s

### 描述你想要的解决方案

添加一个可以自己设置更新源的选项

**Comment by lyswhut** [comment]
没有更改的打算，并且更新功能是通过`electron-updater`实现的，似乎它也不支持指定Github镜像站
