### ISSUE TITLE
[Bug]: 升级到1.20.0_x64后收藏的大部分歌典不能再播放

### ISSUE THREAD

**Issue by lionelfung7** [lyswhut/lx-music-desktop#846]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

小石头和孩子们的大部分歌曲，在1.18版本都能正常播放

### 实际行为

小石头和孩子们的大部分歌曲，在1.20版本都不能播放，报一个找不到源的错误。重装1.18解决，再重装1.20故障依旧，反复尝试了多遍，都是这个现象。BTW，我没有先卸载lx_music，每次都是直接安装。

### Lx Music 版本

1.20.0

### 最后正常的版本

1.18.0

### 操作系统版本

Windows 11 Pro 21H2

**Comment by lyswhut** [comment]
音乐能否播放一般与是否更新版本无关，无法播放的问题自行看常见问题解决
如果确实是这样你可以尝试去设置清空缓存
