### ISSUE TITLE
[建议]:取消勾选那两个动画效果后 下次重开软件 动画自动恢复且勾选框处于未选状态  

### ISSUE THREAD

**Issue by daxiaanyi1** [lyswhut/lx-music-desktop#847]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

另外 下载功能 能否在设置里弄个"无须每次弹窗让用户选择下载音质 默认自动选择最高音质"
因为发现不论选哪种音质 下载的都是最基础的音质 实际并没有其它高级音质的源可供下载  所以每次都弹窗让用户选择音质没什么必要 只会增加重复繁琐操作

### 描述你想要的解决方案

~~~~~~~

### 描述你考虑过的替代方案

_No response_

### 附加信息

_No response_

**Comment by lyswhut** [comment]
已在v1.21.0修复
