### ISSUE TITLE
[建议]: 下载过程 系统会持续轻微卡顿 这个问题存在很久了

### ISSUE THREAD

**Issue by daxiaanyi1** [lyswhut/lx-music-desktop#848]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

另外 可以像企鹅一样 弄一些同样的音效功能 然后再弄个用户注册 之后还能让用户同步各平台的收藏列表到本软件 这样慢慢就没人用大平台听歌了  毕竟现在都是要求vip  否则只能听片段  太垃圾了

### 描述你想要的解决方案

111111111111

**Comment by lyswhut** [comment]
下载从被开发出来到现在一直存在性能问题，这个功能其实没有开发完成，最初的时候只是做到“能用”的阶段，到后面出于版权原因考虑，下载功能现在处于维护状态，没有大改、加新功能的计划。

[音效](https://github.com/lyswhut/lx-music-desktop/issues/840)、[用户注册](https://github.com/lyswhut/lx-music-desktop/issues/531)无计划弄
