### ISSUE TITLE
[Bug]: 因为已有同名文件而导致归入暂停列表中后 如果删除这些歌曲 会导致已下载的这些音乐文件全被删掉

### ISSUE THREAD

**Issue by daxiaanyi1** [lyswhut/lx-music-desktop#849]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

由于已存在同文件而导致的暂停下载的曲目 删除应该改为清空列表才符合逻辑 而不是删除............. 这个逻辑错误存在很久很久了
各大平台的相关功能就都分为 列表中删除和删除硬盘源文件两个选项 这样才对啊
咱这个软件其实本来就不应该具备删除硬盘中已下载源文件的功能选项 只需要清空列表功能就足够了  没人会需要通过本软件去删除硬盘里下载好的音乐 谢谢

### 实际行为

1

### Lx Music 版本

1.20

### 最后正常的版本

1.20

### 操作系统版本

Windows 10

**Comment by lyswhut** [comment]
这是故意这样做的，因为在删除没有下载完成的任务时，对于那些只下载了一部分的文件是没有用的，所以会将其连同文件一起删除，这没有考虑外部添加了同名的文件到下载目录。

这应该还需要添加是否有下载进度的判断再确定是否删除文件

**Comment by lyswhut** [comment]
已在v1.21.0优化
