### ISSUE TITLE
添加对flac格式的meta信息修改

### ISSUE THREAD

**Issue by augsun** [lyswhut/lx-music-desktop#85]
建议添加下载的 flac 带上歌曲的标签<歌手, 歌名, 专辑 等等> 方便歌曲的管理, 比如用 foobar 管理就方便很多了

现在下载的flac歌曲, 导入歌库前 需要手动添加标签 实在麻烦, 看看下载的歌曲能不能拿到标签数据.

在此感谢

**Comment by lyswhut** [comment]
之前有这个功能的，但由于之前的第三方flac文件标签编辑插件有问题，然后就去掉了，
详情看更新日志：https://github.com/lyswhut/lx-music-desktop/blob/master/CHANGELOG.md#054---2019-09-09
后面再想办法加回去吧

**Comment by vsug** [comment]
可以考虑自动调用mp3tag进行修改，而不必额外添加功能

**Comment by lyswhut** [comment]
v0.18.0已重新加入该功能
