### ISSUE TITLE
[Bug]: 蓝牙耳机的暂停操作无效

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [lyswhut/lx-music-desktop#851]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

耳机型号为 WH-1000XM4, 双击右侧耳机可以让正在播放的音视频暂停，其它软件和浏览器正在播放的视频都可以暂停，lx-music也应该暂停

### 实际行为

lx-music无反应，依旧在播放

### Lx Music 版本

1.18.0

### 操作系统版本

win11 preview

**Comment by lyswhut** [comment]
默认情况下即使没有开启全局快捷键，LX在启动时也将会尝试去注册播放/暂停、上一曲、下一曲媒体控制快捷键，由于媒体控制快捷键属于全局快捷键，如果已被其他软件注册，则LX将无法再注册它们

**Comment by Misaka-Mikoto-Tech** [comment]
好的，谢谢
