### ISSUE TITLE
作者您好，这里发现有人在pdd上贩卖您的软件，该商品所谓的电脑版实质上就是您的lx_music

### ISSUE THREAD

**Issue by 2419000677** [lyswhut/lx-music-desktop#852]
https://mobile.yangkeduo.com/goods.html?goods_id=313765532808&page_from=101&pxq_secret_key=5BADF2JAABQEJAOKB6TDIL4M4P5E6Z2C5NLOSTA7SXEFDMKLZ5UA&share_uin=5CPJUSOITSZDXTJDCYAHJL5UJU_GEXDA&refer_share_id=2ea4d3a24d2845cda5107648b0eecce9&refer_share_uid=5595382795238&refer_share_uin=5CPJUSOITSZDXTJDCYAHJL5UJU_GEXDA&refer_share_channel=copy_link&refer_share_form=text

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/514
