### ISSUE TITLE
[Bug]: mac端的桌面歌词背景有重影

### ISSUE THREAD

**Issue by tyfg121** [lyswhut/lx-music-desktop#853]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

mac端的桌面歌词背景应该是白色的，如果有菜单栏歌词就更好了~！

### 实际行为

mac端的桌面歌词背景有重影

### Lx Music 版本

v1.20.0 

### 操作系统版本

macOS Big Sur 11.5.2 

### 附加信息

![image](https://user-images.githubusercontent.com/105186685/167336277-20c41db3-6e77-433e-82cb-2042062a86dc.png)

**Comment by Pei-Qi** [comment]
有解决办法吗
