### ISSUE TITLE
[Feature]: 将测试接口、下载功能设为默认

### ISSUE THREAD

**Issue by JXTang-syc** [lyswhut/lx-music-desktop#854]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我把软件下载下来的时候，发现wyy源都听不了，而且都不能下载后来才发现，是设置里的接口默认是临时接口，而且下载关闭。

### 描述你想要的解决方案

把这两个内容默认切为测试接口，下载默认打开

**Comment by lyswhut** [comment]
软件的初始设置并不是推荐的设置，这是故意这么做的，为了过滤掉部分小白用户
