### ISSUE TITLE
[Feature]: 桌面歌词永远置顶，覆盖在任务栏上方

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-desktop#855]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

Windows 11 的任务栏左边有好大一长条空，可以充分利用，显示歌词。
![image](https://user-images.githubusercontent.com/69227436/167801654-dcc1d511-247b-4b5e-a914-d59a84fd5b15.png)
调整歌词设置。
![image](https://user-images.githubusercontent.com/69227436/167802380-5ad00f00-1ea8-4aa5-b533-7ac50c5dd90a.png)
把歌词拖向任务栏，歌词可以显示在任务栏上方。
![image](https://user-images.githubusercontent.com/69227436/167802456-74c22285-611c-4f25-b5c9-631cbc17d41a.png)
倘若鼠标点击任务栏以后，任务栏会显示在歌词上方覆盖歌词。
![image](https://user-images.githubusercontent.com/69227436/167802677-12dd2a99-3965-4515-be4d-cc2ba6fd2125.png)

### 描述你想要的解决方案

每次展现下一句歌词的时候，模拟鼠标点击一次歌词。这样，就可以保证，歌词一直置顶，一直位于任务栏上方了。

### 描述你考虑过的替代方案

想要横向滚动的桌面歌词，并且永远置顶显示，可以永远显示在任务栏上方，这样可以自己拖动过去。

### 附加信息

略

**Comment by lyswhut** [comment]
![image](https://user-images.githubusercontent.com/20365169/168708740-57cb81a5-bab9-4981-8a9f-263b29942c2e.png)
尝试启用这个设置（v1.20.0新增）

**Comment by 1457384613gh** [comment]
效果很好，跟安卓的状态栏歌词很像。


https://user-images.githubusercontent.com/69227436/168727487-1df0153a-3ab4-4f43-a491-7deda6034f1a.mp4
