### ISSUE TITLE
[Feature]: Mac版本麻烦增加个可以自定义窗口大小以及全屏功能

### ISSUE THREAD

**Issue by Hbisedm** [lyswhut/lx-music-desktop#856]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

Mac版本麻烦增加个可以自定义窗口大小以及全屏功能

### 描述你想要的解决方案

Mac版本麻烦增加个可以自定义窗口大小以及全屏功能

**Comment by Hbisedm** [comment]
不是设置选项那个窗口尺寸，就限定了几个选项

**Comment by lyswhut** [comment]
出于[一些原因](https://www.electronjs.org/docs/latest/tutorial/window-customization#limitations)，没有开放自由调整窗口大小的功能，但你可以按`F11`进入全屏模式
