### ISSUE TITLE
[Feature]: 希望能加个音量大小控制

### ISSUE THREAD

**Issue by h98458** [lyswhut/lx-music-desktop#857]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

window版本，没有音量大小控制，感觉很不方便

### 描述你想要的解决方案

window版本，没有音量大小控制，感觉很不方便

**Comment by 2096779623** [comment]
![image](https://user-images.githubusercontent.com/57583560/168421122-8d930dc0-15c5-4145-a56f-6d85844bd415.png)
