### ISSUE TITLE
[Bug]: 下载

### ISSUE THREAD

**Issue by 2096779623** [lyswhut/lx-music-desktop#858]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

1.启用下载功能
2.下载歌曲
3.把歌曲的源文件删除掉重新下载
4.返回：源文件丢失或者重新下载

### 实际行为

1.启用下载功能
2.下载歌曲
3.把歌曲的源文件删除掉重新下载
4.不会进行下载操作

### Lx Music 版本

1.20.0
![image](https://user-images.githubusercontent.com/57583560/168420921-4e651c07-425f-43fd-9be6-675c34cfa65f.png)

### 操作系统版本

Windows 10 2004 专业版
![image](https://user-images.githubusercontent.com/57583560/168420930-4a554ed7-4b11-45c1-b0f6-18e80403ecfd.png)

### 附加信息

![image](https://user-images.githubusercontent.com/57583560/168420945-22cf06e6-1d9f-4787-a1e7-15999207eb31.png)

https://user-images.githubusercontent.com/57583560/168421008-722cd2b0-70fe-4535-a8d4-e9ad124abf2a.mp4

**Comment by lyswhut** [comment]
你这视频啥也看不到啊，

如果歌曲已在下载列表中，再次添加同源的相同歌曲时将会跳过添加，清理下载列表的歌曲重新添加下载任务即可
