### ISSUE TITLE
希望能添加后台播放功能

### ISSUE THREAD

**Issue by biuabiu** [lyswhut/lx-music-desktop#86]
前面看到过作者说这是一款定位下载音乐的软件 ,但是我感觉这比一般的音乐软件更清爽更好用啊
我个人是将其作为音乐软件来使用的,希望能添加后台播放的功能 , 不知道小伙伴们是不是也有这样的诉求

**Comment by lyswhut** [comment]
问题重复：https://github.com/lyswhut/lx-music-desktop/issues/68
暂不考虑添加
