### ISSUE TITLE
[Bug]: 翻译歌词显示错误

### ISSUE THREAD

**Issue by jason-bowen-zheng** [lyswhut/lx-music-desktop#860]
### 解决方案检查

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正确翻译歌词，且原文与翻译对照。

### 实际行为

以下是播放歌曲时的桌面歌词：
> 应用内的歌词显示与之相同

![err](https://user-images.githubusercontent.com/58848782/169463006-df0df5ba-28f9-4de1-bbe4-7f8a47c888af.png)

貌似歌词错位了。

### Lx Music 版本

1.20.0

### 操作系统版本

Windows 7

**Comment by lyswhut** [comment]
什么源的什么歌曲？翻译与官方的是否一致？

**Comment by jason-bowen-zheng** [comment]
是这首歌：<http://www.kuwo.cn/play_detail/51426336>。

先不论翻译的正确性。请再次细看截图：字号大的应该是歌词原文，字号小者为中文翻译，原文出现在翻译之上（这是正常情况）。

很显然，我遇到的情况并非正常情况：有些地方只有翻译，有些地方只有歌词原文，还有就是如上图最后一行歌词所示。

这是对数据的错误解析所致的还是获取的数据本身就有误呢？

**Comment by lyswhut** [comment]
我也没想明白你这歌词是来自哪个源，酷我官方的这首歌是没有翻译的，我所有源都试了后没发现你这个歌词来自哪个源，或许是原来酷我有歌词翻译的，后来去掉了🤔？
你去设置清理下列表缓存，再重新播放这首歌看看歌词是否恢复正常

**Comment by jason-bowen-zheng** [comment]
按照您的说法，清除缓存后，确实只剩原本的日语歌词。
> 不过为什么会错成这样子呢？

(我现在没用电脑，下面的截图是手机的)这首歌<http://www.kuwo.cn/play_detail/30350752>的歌词截图：

![Screenshot_2022-05-20-20-08-38-1](https://user-images.githubusercontent.com/58848782/169526034-02ca6841-ef33-4dc0-8022-6fda828067cd.jpg)

在6个小时之前（创建这个issue）的时候，其歌词的渲染亦不正常（手机上的更不正常）。
> 当然啦，源上的歌曲质量参差不齐，这个变量可控制不了。

**Comment by lyswhut** [comment]
酷我的歌词是把原文跟翻译混在一起的，而且它们混在一起的顺序也很奇怪，导致分离原文与翻译的过程中匹配出错，其实已经好几个版本改进过匹配，但还是没能完全解决，就拿你提的这首歌来说，它的歌词是这样的：
![image](https://user-images.githubusercontent.com/20365169/169533094-8b9a71f5-3d89-4bb4-af23-4eafc92c1678.png)

我再尝试去改进一下匹配吧

**Comment by lyswhut** [comment]
花了一点时间研究了下，没能搞清楚规则，所以可能存在翻译的酷我歌词暂时被禁用，将会自动换其他源的歌词，你这个问题更新到最新版本后清空下列表缓存即可恢复正常
