### ISSUE TITLE
[Feature]: Mac端太好用了 ios客户端 能给一个白包吗 自己签名 感谢感谢

### ISSUE THREAD

**Issue by Hardway2** [lyswhut/lx-music-desktop#861]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

Mac端太好用了 ios客户端 能给一个白包吗 自己签名 感谢感谢

### 描述你想要的解决方案

Mac端太好用了 ios客户端 能给一个白包吗 自己签名 感谢感谢

**Comment by lyswhut** [comment]
不计划支持IOS，但可以看：https://github.com/lyswhut/lx-music-mobile/issues/84
