### ISSUE TITLE
[Feature]: 搜索后不能双击播放

### ISSUE THREAD

**Issue by ryl793738638** [lyswhut/lx-music-desktop#862]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

搜索音乐后不能双击播放音乐，只能添加到列表才能播放

### 描述你想要的解决方案

双击就能播放音乐 默认添加到试听列表

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/209
