### ISSUE TITLE
[Feature]: 希望能增加直接点击表头进行排序

### ISSUE THREAD

**Issue by echobailin** [lyswhut/lx-music-desktop#863]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议

### 描述你想要的解决方案

列表，希望能增加直接点击表头进行排序

**Comment by 573e** [comment]
+1

**Comment by lyswhut** [comment]
要按歌手、歌曲名字排序可以通过右击列表名后弹出的菜单中使用“排序歌曲”功能，不打算将排序功能添加到表头
