### ISSUE TITLE
[Bug]: 单曲模式下，没有办法切歌

### ISSUE THREAD

**Issue by nanxiuzi** [lyswhut/lx-music-desktop#864]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

切歌之后继续单曲循环

### 实际行为

上下曲不起作用

### Lx Music 版本

1.21.0

### 操作系统版本

windows10

**Comment by lyswhut** [comment]
已在v2.0.0优化
