### ISSUE TITLE
[Feature]: 希望能批量操作列表歌曲，试听列表删除太麻烦了，Thanks.

### ISSUE THREAD

**Issue by InThe-Snow** [lyswhut/lx-music-desktop#866]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

试听列表删除太麻烦。

### 描述你想要的解决方案

希望能批量操作列表歌曲。

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/list-multiple-selection
