### ISSUE TITLE
[Bug]: mac m1无法自动升级

### ISSUE THREAD

**Issue by codeofyu** [lyswhut/lx-music-desktop#868]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

点击更新自动升级

### 实际行为

下载进度一直在处理中

### Lx Music 版本

1.17.0

### 操作系统版本

macOs Monterey  版本 12.4  MacBook Pro (13-inch, M1, 2020)

**Comment by lyswhut** [comment]
看：https://lxmusic.toside.cn/desktop/faq/update
