### ISSUE TITLE
搜索结果歌单全部播放

### ISSUE THREAD

**Issue by daijinghao** [lyswhut/lx-music-desktop#869]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

搜索结果歌单全部播放

### 描述你想要的解决方案

搜索结果歌单全部播放

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/list-play-all
