### ISSUE TITLE
建议增加收藏网址的功能

### ISSUE THREAD

**Issue by Sirius2s** [lyswhut/lx-music-desktop#87]
感谢大神
建议增加收藏网址或者榜单、歌单的功能

**Comment by lyswhut** [comment]
收藏网址？没理解

**Comment by Sirius2s** [comment]
大概是这个意思：榜单、歌单的地址能够在收藏中记录

**Comment by lyswhut** [comment]
本软件不是音乐播放器，所以没有收藏功能
详情看：https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md#%E8%BD%AF%E4%BB%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8%E5%8A%9F%E8%83%BD

**Comment by Sirius2s** [comment]
了解了。感谢
