### ISSUE TITLE
[Bug]: 升级到1.21.0_x64后收藏的大部分歌典不能再下载播放

### ISSUE THREAD

**Issue by lionelfung7** [lyswhut/lx-music-desktop#870]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常播放

### 实际行为

这个BUG我曾经提交过，被作者认为并非版本升级的问题而close。但经过我反复的测试，发现1.20和1.18确实在源下载上存在差异。进一步的测试，发现1.20开始，lx_music会去访问系统环境变量http_proxy，如果该变量中有设了一个代理的话，lx_music会使用这个proxy。更有趣的是，软件界面中也有proxy的设置，如果我在软件界面中，也设了proxy，譬如都设为127.0.0.1:7890，那么，我位于127.0.0.1:proxy上的代理，就会收到一个需要访问127.0.0.1:7980的请求。等于是两次请求proxy。这就是1.20播放失败而1.18能播放成功的原因。解决的方法很简单，就是把环境变量http_proxy清除即可。但这个环境变量我是要在别的软件中使用的，不能去除。因此只能继续使用1.18版。可能是作者版本更新同时把网络访问的底层库也更新了造成的。这个问题在很多软件中都有。譬如钉钉也是这个问题，而钉钉的开发者可能直到今天都没发现这个问题。我给他们提交过类似的BUG，他们也摸不清原因。后来我发现钉钉底层在文件上传的时候，也会偷偷摸摸的访问http_proxy环境变量，但在视频直播的时候不会。

### Lx Music 版本

1.20.0

### 最后正常的版本

1.18.0

### 操作系统版本

Windows 11 Pro 21H2

**Comment by lionelfung7** [comment]
再补充一下，因为使用的proxy是国外的，而国内的大部分源，譬如qq music之类对国外IP都是封锁的，所以才会造成下载播放的失败。而1.18版本，并不会去访问环境变量http_proxy，所以都是直接去下载源，就不会有这个问题。

**Comment by lyswhut** [comment]
刚去翻了下请求库的源码，这个库确实会自动读取环境变量的`http_proxy`与`https_proxy`配置：
https://github.com/tomas/needle/blob/e5dee92793861093bc38fc50d32444d4ad3cbcc4/lib/needle.js#L343

这有点坑，下个版本修复它

现在临时的解决方案有两个：
1. 在你的代理工具配置一下路由，国内的IP或域名让它走直连就行了

2. 这个请求库还用到了另一个环境变量`NO_PROXY`：
https://github.com/tomas/needle/blob/e5dee92793861093bc38fc50d32444d4ad3cbcc4/lib/needle.js#L195
可以将不走代理的域名设置进去多个用`,`隔开

**Comment by lyswhut** [comment]
有人在那边提issue要加这个功能，然后后面更新请求库就把这个功能加进去了：https://github.com/tomas/needle/issues/336

**Comment by lionelfung7** [comment]
> 刚去翻了下请求库的源码，这个库确实会自动读取环境变量的`http_proxy`与`https_proxy`配置： https://github.com/tomas/needle/blob/e5dee92793861093bc38fc50d32444d4ad3cbcc4/lib/needle.js#L343
> 
> 这有点坑，下个版本修复它
> 
> 现在临时的解决方案有两个：
> 
> 1. 在你的代理工具配置一下路由，国内的IP或域名让它走直连就行了
> 2. 这个请求库还用到了另一个环境变量`NO_PROXY`：
>    https://github.com/tomas/needle/blob/e5dee92793861093bc38fc50d32444d4ad3cbcc4/lib/needle.js#L195
>    可以将不走代理的域名设置进去，多个用`,`隔开

收到，非常感谢，我去尝试一下

**Comment by lyswhut** [comment]
已在v1.22.0修复
