### ISSUE TITLE
[Bug]: 关于随机播放

### ISSUE THREAD

**Issue by hozt81413** [lyswhut/lx-music-desktop#872]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

网络正常，歌单200多曲目全部有效，随机播放所有曲目

### 实际行为

随机播放总是来回那10多首，其他的手动播放后还是继续随机来回播放之前那10多首，桌面版和手机版一样的问题。

### Lx Music 版本

1.15.0

### 最后正常的版本

1.15.0

### 操作系统版本

windows 11 21H2

### 附加信息

简单来说就是随机播放总是来回播放歌单里的10多首，重启了还是那几首，哪怕歌单里有多少曲目。

**Comment by hozt81413** [comment]
Lx Music 版本
1.21.0

最后正常的版本
未知

**Comment by lyswhut** [comment]
相关问题看：https://github.com/lyswhut/lx-music-desktop/issues/766

**Comment by hozt81413** [comment]
歌曲列表约200首曲目全部是有效曲目，网络连接正常，按歌曲名升序排序，随机乱序播放，用上一首或下一首切歌，然后发现某几首歌出现的机率特别高，就算重启软件后，总有那几首歌特别高频，电脑版和手机版一样。

**Comment by lyswhut** [comment]
随机功能使用了已播放列表来标记已播放过的歌曲，整个列表的歌曲播放完毕或者切歌时才会清理已播放列表，所以理论上正常播放时是不会出现重复播放歌曲的。
我这边无法重现你说的问题，如果你确实能重现这问题，你可以说下你的详细操作步骤
