### ISSUE TITLE
[Feature]: 建议增加批量添加到收藏和批量删除

### ISSUE THREAD

**Issue by beibeiMr** [lyswhut/lx-music-desktop#875]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

在排行榜里面添加音乐不能批量添加到收藏和批量删除

### 描述你想要的解决方案

建议增加批量添加到收藏和批量删除

**Comment by lyswhut** [comment]
看：https://lxmusic.toside.cn/desktop/faq/list-multiple-selection
