### ISSUE TITLE
[Bug]: 单曲循环时上一首和下一首失效

### ISSUE THREAD

**Issue by lerdertre** [lyswhut/lx-music-desktop#877]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在单曲循环模式时，按下上一首/下一首的按钮（或快捷键）能按照列表顺序来播放上/下一首（以下称为歌曲A），播放完歌曲A后，再次将歌曲A循环播放

### 实际行为

在单曲循环模式时，按下上一首/下一首的按钮（或快捷键）不能进行切歌操作

### Lx Music 版本

1.22.0-beta

### 操作系统版本

Windows 11 版本 22000.675

**Comment by lyswhut** [comment]
重复 #877

**Comment by lyswhut** [comment]
已在v2.0.0优化
