### ISSUE TITLE
[Bug]: api not found

### ISSUE THREAD

**Issue by yangyang0223** [lyswhut/lx-music-desktop#878]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

找不到api

### 实际行为

not found

### Lx Music 版本

1.15.0

### 操作系统版本

win10

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/550
