### ISSUE TITLE
[Bug]: 歌单中呼出的搜索框不独占输入

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#879]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![image](https://user-images.githubusercontent.com/20263103/172858586-73ae3b1f-3e31-4144-aae0-5c144b9b25b9.png)
这是我的按键设置,

我希望在搜索框中输入时, 这个输入不要触发到快捷键的功能, 或者说:

当输入聚焦在搜索框时, 搜索框独占这个输入处理

### 实际行为

当我输入`e`或者`q`或者`空格`时,会触发到相关的快捷键功能

### Lx Music 版本

1.21.0

### 操作系统版本

Edition	Windows 11 Pro Version	21H2 Installed on	‎4/‎28/‎2022 OS build	22000.708 Experience	Windows Feature Experience Pack 1000.22000.708.0

**Comment by lyswhut** [comment]
我刚看了下，这个也是做了处理的，没有这个问题啊，我没能重现出来，你说下操作步骤？

**Comment by lyswhut** [comment]
重现出来了，只有上面的歌曲搜索框不会不会这样😆

**Comment by lyswhut** [comment]
已在v1.22.0修复，若仍有问题可继续留言
