### ISSUE TITLE
请问有Linux/Ubuntu的deb版本吗？

### ISSUE THREAD

**Issue by yangge8522424** [lyswhut/lx-music-desktop#88]
你好，
我看到readme有写已支持Linux，而且软件安装包说明里有说有deb文件，但我并没有找到相关的链接，是需要通过源码安装吗？
我刚接触Ubuntu，不会编译源码，能上传deb文件吗？

**Comment by SingSky** [comment]
在项目的release页面仔细寻找一下。。。

**Comment by lyswhut** [comment]
发布页有Linux包下载：https://github.com/lyswhut/lx-music-desktop/releases

**Comment by yangge8522424** [comment]
> 在项目的release页面仔细寻找一下。。。

3Q，找到了

**Comment by yangge8522424** [comment]
> 发布页有Linux包下载：https://github.com/lyswhut/lx-music-desktop/releases
嗯嗯，不好意思，没去到release界面。找到了，3Q
