### ISSUE TITLE
[Feature]: 搜索里能专辑跳转，以及导入网易云的歌单

### ISSUE THREAD

**Issue by leiyutian007** [lyswhut/lx-music-desktop#882]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议在搜索栏里能点击专辑名字跳转到专辑的所有歌曲
还有就是希望能像Musictool或者yesplaymusic一样能把网易云音乐的歌单导入，并且联动。

### 描述你想要的解决方案

跳转应该不难
 
可以看看像Musictool的扫描二维码登录，会有个歌单的地址导入

**Comment by lyswhut** [comment]
由于目前还不支持专辑功能，所以无法跳转

打开歌单可以在“歌单”界面打开，若遇到问题看：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist

**Comment by Shaoyu742698** [comment]
> 由于目前还不支持专辑功能，所以无法跳转
> 
> 打开歌单可以在“歌单”界面打开，若遇到问题看：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist
> 
> 目前没有支持账号登录的计划

目前有计划支持导入外部专辑吗？
