### ISSUE TITLE
[Feature]: 歌词置顶显示优化建议

### ISSUE THREAD

**Issue by lylllls** [lyswhut/lx-music-desktop#883]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

歌词在桌面置顶后会挡住后面的内容，但看不见歌词又难受（个人习惯）

### 描述你想要的解决方案

其他功能不变，希望增加——当鼠标移到歌词区域时，歌词自动隐藏，显示出后面的内容，类似于显示桌面功能

### 描述你考虑过的替代方案

无

### 附加信息

无

**Comment by coderzhaoziwei** [comment]
<img width="514" alt="screen capture2022-06-15 09 39 53" src="https://user-images.githubusercontent.com/70856456/173718002-9255ea60-a767-41ce-aa67-38adab6801b8.png">

虽然我设置置顶+锁定之后感觉置顶的歌词并不遮挡我的正常使用，但是这个 issue 很好啊。

鼠标 hover 之后我觉得也不用完全隐藏，让歌词不透明度达到 0.25 左右大概就够了，甚至可以让用户自己选择鼠标 hover 之后的不透明度。

不过歌词不定时出现灰色的遗留残影（当前系统：macos-arm64）是个问题，我截的这张图能看到当前歌词下方还有以前歌词的阴影，要是能修复就好了。

**Comment by lyswhut** [comment]
已在v1.22.0新增，此设置不支持linux，注：此功能存在兼容性问题，若鼠标移出后无法恢复到正常透明度，可尝试再移入移出即可恢复

**Comment by lyswhut** [comment]
@coderzhaoziwei 

> 鼠标 hover 之后我觉得也不用完全隐藏，让歌词不透明度达到 0.25 左右大概就够了，甚至可以让用户自己选择鼠标 hover 之后的不透明度。

暂不做自行调整透明度的功能，现在会固定将透明度降低到 0.05，并且这个功能未在Mac上测试，不知道效果怎么样

> 不过歌词不定时出现灰色的遗留残影（当前系统：macos-arm64）是个问题，我截的这张图能看到当前歌词下方还有以前歌词的阴影，要是能修复就好了。

看：https://github.com/lyswhut/lx-music-desktop/issues/731

**Comment by coderzhaoziwei** [comment]
@lyswhut 我 Mac 测试了一下，半透明的效果很好。但还是阴影（“纯音乐，请欣赏”是残留阴影）的存在影响了实际效果。在歌词变成半透明之后，尤其在白色背景下，阴影更加显眼了。看来，只能等 Electron 修复或者不使用文字阴影效果了。
<img width="432" alt="screen capture2022-06-20 11 35 15" src="https://user-images.githubusercontent.com/70856456/174520644-d37f62d5-2ab3-4df7-a9a2-597f5a73f322.png">
