### ISSUE TITLE
[Feature]: 能否增加蓝牙歌词显示功能

### ISSUE THREAD

**Issue by 1162957506** [lyswhut/lx-music-desktop#884]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

能否增加蓝牙歌词显示功能

### 描述你想要的解决方案

增加蓝牙显示歌词。

**Comment by lyswhut** [comment]
PC端加这个没啥用，也加不了

**Comment by tonyjona** [comment]
手机端有用，特别和车子连接蓝牙时，可在歌名位置跑马灯方式显示歌词！
