### ISSUE TITLE
[Bug]: 打开Stage Manager(新的窗口布局) 后，缩小再放大，右下部分会出现一个透明遮罩层

### ISSUE THREAD

**Issue by heer0114** [lyswhut/lx-music-desktop#887]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

出现一个透明遮罩层

### 实际行为

MacOS  Ventura   13.0 Beta版(22A5266r)  
可以说是兼容性问题吧，也可能是潜在的BUG
打开Stage Manager(新的窗口布局) 后，缩小再放大就会出现图片中的问题
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/103934050/174577880-5813f3c7-540c-4b4c-b2fd-cc134c244b2c.png">

### Lx Music 版本

1.22.0 

### 操作系统版本

MacOS  Ventura   13.0 Beta版(22A5266r)

**Comment by lyswhut** [comment]
同样是macOS的窗口阴影问题导致的，详情看：https://github.com/lyswhut/lx-music-desktop/issues/731
