### ISSUE TITLE
除了酷我音乐，其他音乐都搜不到了，mac版本

### ISSUE THREAD

**Issue by Fishlz** [lyswhut/lx-music-desktop#89]

**Comment by lyswhut** [comment]
请提供截图等信息

**Comment by hec9527** [comment]
![image](https://user-images.githubusercontent.com/28671232/71352848-58a77f80-25b2-11ea-923b-71203879f89b.png)

![image](https://user-images.githubusercontent.com/28671232/71352858-5e9d6080-25b2-11ea-9501-d5725e52197c.png)

![image](https://user-images.githubusercontent.com/28671232/71352868-66f59b80-25b2-11ea-8034-c93feee740a1.png)

确实除了酷我音乐，其他的都不能播放

**Comment by lyswhut** [comment]
设置-测试接口




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hec9527"<notifications@github.com&gt;; 
发送时间: 2019年12月23日(星期一) 晚上6:31
收件人: "lyswhut/lx-music-desktop"<lx-music-desktop@noreply.github.com&gt;; 
抄送: "落雪無痕"<lyswhut@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lyswhut/lx-music-desktop] 除了酷我音乐，其他音乐都搜不到了，mac版本 (#89)





 

 

 
确实除了酷我音乐，其他的都不能播放

**Comment by lyswhut** [comment]
@hec9527 设置-测试接口
https://github.com/lyswhut/lx-music-desktop/issues/78
