### ISSUE TITLE
[Bug]: 固定歌词后窗口与歌词叠在一起鼠标在重叠位置移动会有问题

### ISSUE THREAD

**Issue by willaytoun** [lyswhut/lx-music-desktop#892]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![111](https://user-images.githubusercontent.com/43229736/174935361-5dbfa8f3-d3e2-4c60-9926-221ebc9beba9.gif)

### 实际行为

歌词与窗口叠一起鼠标移过去会有干扰

### Lx Music 版本

1.22

### 操作系统版本

Windows10 21H1

**Comment by lyswhut** [comment]
这是1.22.0加入的“鼠标移入歌词区域时降低歌词透明度”特性导致的，下个版本会针对在不开启该特性的情况下修复该问题

注：如果启用了这个设置，则问题仍然会存在，这是electron的问题，无法修复

**Comment by lyswhut** [comment]
已在v1.22.1修复
