### ISSUE TITLE
[Bug]: 无法下载

### ISSUE THREAD

**Issue by TodayYoHoHo** [lyswhut/lx-music-desktop#894]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

音乐可以播放但是无法下载（下载键是灰色的）

### 实际行为

音乐可以播放但是无法下载（下载键是灰色的
![Snipaste_2022-06-24_23-59-34](https://user-images.githubusercontent.com/88957232/175573339-ba0fa5d8-76cb-44e8-8b1e-1154a7418927.png)
）

### Lx Music 版本

1.22.0

### 最后正常的版本

不知

### 操作系统版本

Windows11

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/78
