### ISSUE TITLE
[Feature]: 歌单中歌曲数目显示

### ISSUE THREAD

**Issue by Sporice** [lyswhut/lx-music-desktop#898]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望能在歌单名的右侧加上歌单中歌曲的数量，
可以更方便查看歌曲数量

### 描述你想要的解决方案

希望能在歌单名的右侧加上歌单中歌曲的数量，
可以更方便查看歌曲数量

### 描述你考虑过的替代方案

希望能在歌单名的右侧加上歌单中歌曲的数量，
可以更方便查看歌曲数量

### 附加信息

希望能在歌单名的右侧加上歌单中歌曲的数量，
可以更方便查看歌曲数量

**Comment by lyswhut** [comment]
已在v1.22.1新增，由于部分源的接口没有返回歌曲数量，所以不是所有源都支持显示歌曲数量（懒得找其他接口了
