### ISSUE TITLE
[Feature]: 桌面歌词在播放纯音乐时显示歌名和作者（建议）

### ISSUE THREAD

**Issue by ImAlexBlock** [lyswhut/lx-music-desktop#899]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

桌面歌词在播放纯音乐时只会显示”此歌曲为没有填词的纯音乐，请您欣赏“

### 描述你想要的解决方案

Name-singer
此歌曲为没有填词的纯音乐，请您欣赏
之类的？也可以多一点元素（？
xdddd

### 描述你考虑过的替代方案

无

### 附加信息

![QQ截图20220630112321](https://user-images.githubusercontent.com/100182486/176586447-352afa1a-d402-4d05-91c7-6b819316803e.png)

**Comment by lyswhut** [comment]
这种只有一句的歌词单调、没意义的话，可以将它隐藏起来？

**Comment by AWEkn1** [comment]
这没必要
