### ISSUE TITLE
URL过期，正在刷新URL...

### ISSUE THREAD

**Issue by beyond510** [lyswhut/lx-music-desktop#9]
今天刚安装这个软件，无论试听哪首歌都报错“URL过期，正在刷新URL..."，下载也都是”任务出错“。在“设置”里切换了接口也没好用。不知道是不是我操作的不对？？

我的系统是WIN10 64位。

**Comment by lyswhut** [comment]
你用的是不是最新版本？
目前最新版本是0.3.5，现在QQ、网易云、酷狗音源不可用。
如果是最新版本，可以尝试切换网络试试。比如用手机热点

**Comment by beyond510** [comment]
我用的是最新版本，0.3.5，并且打开了自动更新。我这个用的是台式机，没办法切换。。。崩溃了。。。我再等等吧，哈哈，可能下一个版本就好用了吧

**Comment by beyond510** [comment]
> 你用的是不是最新版本？
> 目前最新版本是0.3.5，现在QQ、网易云、酷狗音源不可用。
> 如果是最新版本，可以尝试切换网络试试。比如用手机热点

我用的是最新版本，0.3.5，并且打开了自动更新。我这个用的是台式机，没办法切换。。。崩溃了。。。我再等等吧，哈哈，可能下一个版本就好用了吧

**Comment by lyswhut** [comment]
目前是能正常使用的，可以到设置-基本设置切换接口试下
