### ISSUE TITLE
搜索到的音乐不能播放，不能下载，只能添加到视听列表和收藏【win7下】

### ISSUE THREAD

**Issue by mask2012** [lyswhut/lx-music-desktop#90]
**描述错误**
搜索到的音乐不能播放，不能下载，只能添加到视听列表和收藏

**重现**
重现行为的步骤：
1. 搜索随便一首歌
2. 在结果列表里可操作项只有+号
3. 此时不能听歌，也不能下载，只能添加

**预期行为**
预期可下载可播放

**截图**
![image](https://user-images.githubusercontent.com/6481461/69933176-be9b6c80-1508-11ea-9ae3-cffa89001555.png)

**环境：**
  -操作系统及版本：[win7 64位 绿色版 1.2.0和1.2.1都有此问题]

## 而如果从排行榜里进就有操作项
![image](https://user-images.githubusercontent.com/6481461/69933203-db37a480-1508-11ea-927f-04df8efc750d.png)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/78

**Comment by mask2012** [comment]
感谢这么快就回复了！这是个基础功能，建议放在说明里说明一下啊！
