### ISSUE TITLE
[Bug]: 下载了部分歌曲无读写权限且无法删除

### ISSUE THREAD

**Issue by jswnlinyu** [lyswhut/lx-music-desktop#901]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

应该能够正常读写歌曲（文件夹其他歌曲可支持读写）

### 实际行为

无法使用任何方法读写此文件，包括使用cmd删除，用播放器打
![屏幕截图 2022-07-04 212116](https://user-images.githubusercontent.com/53430542/177164135-3ee17a98-300f-4b9b-929e-c01dc651fba3.png)
![屏幕截图 2022-07-04 212137](https://user-images.githubusercontent.com/53430542/177164140-0cd74ead-42d1-4652-9211-2dfbce8d1810.png)
![屏幕截图(1)](https://user-images.githubusercontent.com/53430542/177164142-aa553b1c-7533-47bd-874a-5c02e5deb27b.png)
开

### Lx Music 版本

1.22.0

### 操作系统版本

win10 1909

**Comment by lyswhut** [comment]
你这是文件被其他程序占用了吧？导致此下载目录无法写入文件，尝试更换下载目录或重启电脑即可

**Comment by jswnlinyu** [comment]
不是这个下载目录读写不了文件，是一堆歌曲中就这几首歌无法读写，重启之后这几个文件凭空蒸发了，估计是卡bug了
