### ISSUE TITLE
[Bug]: qq音乐音源已无法返回搜索结果，但热榜、歌单可用，且能正常收听

### ISSUE THREAD

**Issue by kelukeka** [lyswhut/lx-music-desktop#903]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

QQ音乐音源搜正常返回结果

### 实际行为

QQ音乐音源搜无法返回结果

### Lx Music 版本

1.22.0

### 最后正常的版本

1.22.0

### 操作系统版本

Windows11 22000.778

**Comment by lyswhut** [comment]
已在v1.22.1修复
