### ISSUE TITLE
[Feature]: 可以添加本地播放功能吗？

### ISSUE THREAD

**Issue by fransewoo** [lyswhut/lx-music-desktop#904]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

可以添加本地播放功能吗？

### 描述你想要的解决方案

可以添加本地播放功能吗？

**Comment by lyswhut** [comment]
可能在以后的某个版本添加

**Comment by rom1c77** [comment]
强烈建议 添加本地播放功能。

**Comment by rom1c77** [comment]
@lyswhut 
1.  ui感觉多多少少有点牵强，建议ui重做。 尤其是大小的不能拖拽。 
2. 更新弹出的页面太大了，最好能异步线程后台更新，而不是关闭之后无法更新
3. 整个ui交互不友好
4. 希望添加本地播放功能
![image](https://user-images.githubusercontent.com/14304457/178183778-04feef00-7a69-457b-9b7a-e19d92dfa649.png)

## 描述
因为我是nas群晖用户，希望找一个播放器 能支持播放本地音乐、支持上传和下载、支持歌词等。 

感觉lx在nas群晖 音乐播放器 还是挺有市场的。

**Comment by thd2020** [comment]
强烈建议添加本地播放啊，作者大大

**Comment by zhegeshijiehuiyouai** [comment]
本地播放需求+1

**Comment by cancundeyingzi** [comment]
还真是一个本地音乐都不能导入的半成品.........绝了,,,怎么win平台没一个能用的

**Comment by AnzioCPC** [comment]
请愿人数加一，嘻嘻~

**Comment by lyswhut** [comment]
已在v2.0.0新增
