### ISSUE TITLE
[Feature]: 支持Win + 方向键 dock 窗口

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-desktop#906]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![image](https://user-images.githubusercontent.com/20263103/178147706-6706bdbb-3ab5-4832-8cec-db59af5a1d64.png)
Win11提供的更多的窗口停靠布局👆

我发现无法对落雪音乐窗口进行停靠,, 按win + ←或者 → 没反应,
这个功能是需要软件适配吗?

我看了下vs code,它支持停靠, 但没支持 上面win 11的功能--- 鼠标停靠到最大化按钮时,会出现停靠布局的选择界面

### 描述你想要的解决方案

希望支持窗口停靠功能

### 描述你考虑过的替代方案

我没考虑过这个功能的实用性,
或者是停靠之后对窗口布局的影响,
不是必须功能, 只是发现想用的时候没有

**Comment by o81018o** [comment]
洛雪的窗口不是调整不了大小吗，停靠更没有了吧
