### ISSUE TITLE
[Feature]: 两个微小改进建议

### ISSUE THREAD

**Issue by o81018o** [lyswhut/lx-music-desktop#909]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

第一个：在单曲循环模式下，单击上一首或下一首按钮，会重新播放这一首歌曲，虽然是单曲循环吧……但是点这个按钮其实是想听下一首……
第二个：对于较长的一行歌词，正在播放和未在播放时的字号不一样，因此在过渡的时候会出现有的词语突然到了下一行，挺影响视觉效果的

### 描述你想要的解决方案

第一个的话应该好改，第二个……限制长度强制换行？

**Comment by o81018o** [comment]
刚刚看了下 #877 和 #864 好像提到过第一个问题

**Comment by lyswhut** [comment]
取消歌词缩放即可，桌面歌词在歌词窗口上方的工具栏设置，播放详情页的歌词在设置-播放详情页设置

**Comment by o81018o** [comment]
啊这，简单粗暴
