### ISSUE TITLE
搜索歌曲后不能通过方向键选择回车确认

### ISSUE THREAD

**Issue by yujian410236643** [lyswhut/lx-music-desktop#91]
搜索歌曲后不能通过方向键选择回车确认

下载歌曲格式没有记忆功能

请大佬下次更新希望能加进去哈哈

**Comment by lyswhut** [comment]
1、方向键选择可以考虑添加
2、没有记忆功能没明白是什么意思

**Comment by yujian410236643** [comment]
> 1、方向键选择可以考虑添加
> 2、没有记忆功能没明白是什么意思

就是在下载的时
第一次选择三个格式中的一个
然后添加一个选项，默认以后每次下载都选择同样格式

**Comment by yujian410236643** [comment]
> > 1、方向键选择可以考虑添加
> > 2、没有记忆功能没明白是什么意思
> 
> 就是在下载的时
> 第一次选择三个格式中的一个
> 然后添加一个选项，默认以后每次下载都选择同样格式

要不然批量下很多歌曲时候需要每个歌曲都要点一遍格式

**Comment by lyswhut** [comment]
暂不考虑添加该功能，多点两下就多点两下吧

**Comment by yujian410236643** [comment]
> 暂不考虑添加该功能，多点两下就多点两下吧

哈哈好的大佬

**Comment by lyswhut** [comment]
已在0.13.0新增
