### ISSUE TITLE
[Feature]: 希望可以添加双击播放当前列表

### ISSUE THREAD

**Issue by 836469383** [lyswhut/lx-music-desktop#912]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

添加新功能

### 描述你想要的解决方案

1. 希望可以添加双击播放当前列表，比如搜索了xxx的音乐，然后双击第一首，后续播放会继续播放xxx的音乐，功能详情参考某芸hhh
2. 播放完搜索的音乐，后续播放又会从试听列表第一首开始。（比如我现在听到试听列表的最后一首，然后播放一个搜索的歌，又会从第一首开始）

**Comment by lyswhut** [comment]
> 希望可以添加双击播放当前列表，比如搜索了xxx的音乐，然后双击第一首，后续播放会继续播放xxx的音乐，功能详情参考某芸hhh

看：<https://lyswhut.github.io/lx-music-doc/desktop/faq/playlist>

> v1.18.0及之后新增了“双击列表里的歌曲时自动切换到当前列表播放”设置，默认关闭，此功能仅对歌单、排行榜有效


> 播放完搜索的音乐，后续播放又会从试听列表第一首开始。（比如我现在听到试听列表的最后一首，然后播放一个搜索的歌，又会从第一首开始）

搜索结果一般都会有很多页，直接播放整个搜索结果列表意义不大，可以自己配合多选功能选部分歌曲加入我的列表后再播放
