### ISSUE TITLE
[Feature]: 添加类似网易云音乐 心动模式

### ISSUE THREAD

**Issue by liujixu1984** [lyswhut/lx-music-desktop#915]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望添加类似网易云音乐的心动模式，根据自己的歌单随机插入推荐歌曲

### 描述你想要的解决方案

希望添加类似网易云音乐的心动模式，根据自己的歌单随机插入推荐歌曲

**Comment by lyswhut** [comment]
心动模式依赖官方平台账号登录，由官方平台根据当前账号收藏的歌曲来匹配他们的曲库实现，这样这对没有对接官方平台账号功能的LX来说基本是不可能实现的
