### ISSUE TITLE
标记下载过的歌和支持歌词的下载

### ISSUE THREAD

**Issue by blog2020** [lyswhut/lx-music-desktop#92]
感谢大佬弄的软件，太好用了。就是希望能增加两个功能：

第一个是，下载过的歌，可以标志一下，这样下次就不会下载到同样的歌了

第二个是，支持一下歌词的下载

感谢。

**Comment by lyswhut** [comment]
1、相同源的歌曲重复添加时，会自动跳过添加
2、歌词下载默认没有开启，可在设置-下载设置开启
