### ISSUE TITLE
[Feature]: 能不能添加收藏夹内歌曲的下载功能

### ISSUE THREAD

**Issue by mantiseer** [lyswhut/lx-music-desktop#920]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

能不能添加收藏夹内歌曲的下载功能

### 描述你想要的解决方案

目前看到的歌曲都是搜索内有下载选项，能不能在搜索到的歌单或者收藏的歌单或歌曲内添加下载选项

### 描述你考虑过的替代方案

就是想下载自己喜欢的歌曲，采取哪种方案都可以，感谢大大

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/78
