### ISSUE TITLE
[Bug]: 下载时文件名同名会覆盖已有文件

### ISSUE THREAD

**Issue by atooy** [lyswhut/lx-music-desktop#922]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

同名文件默认系统增加序号，或者下载增加专辑名选项

### 实际行为

同名文件会被覆盖

### Lx Music 版本

1.22.1

### 最后正常的版本

无

### 操作系统版本

Windows 10 版本21H2

### 附加信息

可以增加专辑名选项最好，最起码不要删除覆盖

**Comment by atooy** [comment]
就没有人有下载需求，碰到这个问题吗。。

**Comment by atooy** [comment]
毕竟不同音乐不同版本的文件名可能都只有一个，因为文件名一般只有音乐名和作者名两个啊，要是能加入下载专辑名就基本能解决问题了

**Comment by lyswhut** [comment]
临时的解决方法是，你可以先指定一个临时目录，下载完成再将文件移过去

**Comment by lyswhut** [comment]
已在v2.0.0新增当下载目录下存在同名文件时自动跳过该任务的设置，默认开启
