### ISSUE TITLE
[Feature]: 希望可以鼠标拖动改变歌单中歌曲的排序

### ISSUE THREAD

**Issue by K2K7K9K11** [lyswhut/lx-music-desktop#923]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望可以鼠标拖动改变歌单中歌曲的排序

### 描述你想要的解决方案

希望可以鼠标拖动改变歌单中歌曲的排序

**Comment by lyswhut** [comment]
没有为歌曲列表添加拖动跳转顺序的打算，你可以使用歌曲右键菜单的位置调整功能来调整顺序，本来的设计是允许批量调整顺序的，但现在的版本多选后无法打开位置调整窗口，下个版本修复

**Comment by lyswhut** [comment]
无法批量调整歌曲顺序问题已在v1.22.2修复，关于批量调整歌曲顺序的说明可以看常见问题：

> ### 批量调整我的列表的歌曲顺序
> 批量调整顺序还可以按你**所选中歌曲时**的顺序去调整顺序。
> 
> 例如若想要快速**翻转**列表内的歌曲顺序，可以先去到列表底部，按<kbd>shift</kbd>或者<kbd>ctrl</kbd>选中最后一首歌，然后去到列表顶部，按<kbd>shift</kbd>选中第一首歌，这时会完成**整个列表的倒序选中**，然后右击任意一首歌打开菜单选择调整顺序，输入`1`回车即可完成列表内歌曲的翻转。
> 
> 另外你还可以使用<kbd>ctrl</kbd>键来选择多个歌曲后调整顺序，这将按照你选中时的去调整歌曲的位置。

**Comment by qjr1831216791** [comment]
能否在现有的基础上增加类似于 键盘的UpDown来每次调整一个顺序？对于手机端可能需要一组图标支持这个功能，个人觉得通过输入数字来指定顺序不够直观，对于小型歌单(比如只有10-20首歌)来说不实用
