### ISSUE TITLE
[Feature]: 可以让desktop端也可以作为client连接别的desktop进行歌单同步吗

### ISSUE THREAD

**Issue by h13-0** [lyswhut/lx-music-desktop#924]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在我有个公网服务器，若干台电脑和移动设备，我想要保持这些设备歌曲同步，但是如果想要在电脑和电脑之间进行同步的话就必须有个手机作为媒介去传递歌曲。
所以我想的是电脑端能不能也可以作为client去连接别的电脑端来直接同步歌曲。
这样我就可以直接部署一个电脑端到服务器，然后我的所有电脑和移动设备都连接到这个服务器进行歌曲同步。

### 描述你想要的解决方案

我希望电脑端也可以提供向手机端那样连接指定host的电脑端的功能

### 描述你考虑过的替代方案

无

### 附加信息

无

**Comment by lyswhut** [comment]
这个以后可能会做，还会考虑做一个独立版的同步服务，可以给有服务器的人部署，还有webdav、gist等的同步，但这都是 _**理想**_

**Comment by lyswhut** [comment]
独立的同步服务项目已发布在<https://github.com/lyswhut/lx-music-sync-server>，我用的是PM2管理服务，但这不是必须的，只要将跑起来就行，至少需要PC端v2.2.0-beta.2与移动端v1.0.0-beta.5才能支持与该服务使用

**Comment by ZacZhangzhuo** [comment]
> 这个以后可能会做，还会考虑做一个独立版的同步服务，可以给有服务器的人部署，还有webdav、gist等的同步，但这都是 _**理想**_

求Gist明文同步！简单易行～
