### ISSUE TITLE
[Bug]: 下载时无论选择哪首歌曲哪个源实际都是128K

### ISSUE THREAD

**Issue by linstwwwkid** [lyswhut/lx-music-desktop#927]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

实际下载音质

### 实际行为

多选歌曲下载时虽然有音质选择，但是实际下载也是128K，单选任何歌曲下载都是128K

### Lx Music 版本

1.22.1

### 操作系统版本

win10

**Comment by Sylyia** [comment]
因为版权原因，作者关掉了无损下载，翻翻旧版本应该可以下载

**Comment by Sylyia** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/788 第三方源可以下载，这个issues里有教程链接

**Comment by luyinuo** [comment]
> #788 第三方源可以下载，这个issues里有教程链接

@Sylyia 链接已经失效
