### ISSUE TITLE
[Feature]: 一些小优化

### ISSUE THREAD

**Issue by james930321035** [lyswhut/lx-music-desktop#928]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

1.使用繁中语言，播放详情页仍有简中
![image](https://user-images.githubusercontent.com/90969133/180631867-d3ccf032-c914-4f40-b789-4f40f067a173.png)

2.歌词翻译有"【" or "】"不显示
![image](https://user-images.githubusercontent.com/90969133/180631919-0b54d978-f427-4173-95f7-92efc77654e0.png)

3.透过ctrl + mouse wheel 更改播放详情页专辑封面及音乐名称大小

4.增加Discord rich presence支持(Like Spotify)
![image](https://user-images.githubusercontent.com/90969133/180632048-de910333-de20-448e-8bdc-4b217b783c8f.png)

5.根据专辑封面变更主题与播放详情页背景
![image](https://user-images.githubusercontent.com/90969133/180632451-a7e259fe-a1c4-4b74-9871-49f8aec21589.png)

### 附加信息

都是简易的小优化  这是很棒的软体 辛苦开发者了

**Comment by lyswhut** [comment]
> 1.使用繁中语言，播放详情页仍有简中

下个版本会修复

> 2.歌词翻译有"【" or "】"不显示

你的意思是要过滤掉存在中文括号之间的内容吗？为什么要这样做？


> 4.增加Discord rich presence支持(Like Spotify)

这是添加单独的桌面小部件窗口吗？是的话以后可能会考虑

> 3.透过ctrl + mouse wheel 更改播放详情页专辑封面及音乐名称大小
> 5.根据专辑封面变更主题与播放详情页背景

这些暂不打算添加

**Comment by james930321035** [comment]
> > 2.歌词翻译有"【" or "】"不显示
> 
> 你的意思是要过滤掉存在中文括号之间的内容吗？为什么要这样做？

不是的，只是去除括号而已，有点影响美观，哈哈

> > 4.增加Discord rich presence支持(Like Spotify)
> 
> 这是添加单独的桌面小部件窗口吗？是的话以后可能会考虑

Discord RPC是Discord的功能之一，可以显示当前状态，目前像是Spotify能够像图中一样显示，您说的桌面小部件视窗也是挺好的一个方法

谢谢开发者

**Comment by lyswhut** [comment]
> 不是的，只是去除括号而已，有点影响美观，哈哈

这样的话，那不打算修改歌词的内容，怕某些情况下内容被误删

桌面小部件以后看情况添加

播放详情页“专辑名”翻译问题已在v1.22.2修复，此issue先关闭
