### ISSUE TITLE
[Feature]: 在歌曲收藏列表中添加按名称排序

### ISSUE THREAD

**Issue by cuixuanxi** [lyswhut/lx-music-desktop#929]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

能不能在歌曲收藏列表中添加按名称排序，每次找歌不太方便

### 描述你想要的解决方案

在歌曲收藏列表中添加按名称排序

**Comment by CottonCandy2004** [comment]
见https://github.com/lyswhut/lx-music-desktop/issues/863#issuecomment-1140254304
