### ISSUE TITLE
[Feature]: 添加一个可以同步到网易云或者酷狗的听歌时间功能

### ISSUE THREAD

**Issue by HG-JOk** [lyswhut/lx-music-desktop#934]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望可以把在洛雪的听歌时间同步到自己指定的音乐平台

### 描述你想要的解决方案

添加一个同步接口，同时新增一个记录当前听歌时间的功能，并且能够同步到网易云或者酷狗平台

**Comment by lyswhut** [comment]
因为没有官方平台的登录功能，所以心动模式、听歌时长等依赖账号的功能都不会有
