### ISSUE TITLE
[Bug]: 最新的两个版本打开后，界面字体模糊，v1.20.0正常

### ISSUE THREAD

**Issue by stalker110119** [lyswhut/lx-music-desktop#935]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

打开软件

### 实际行为

最新的两个版本打开后，界面字体在迷糊和清晰之间渐变，大约3-5秒一个循环。由模糊变清晰，再由清晰变模糊

### Lx Music 版本

1.22.1

### 最后正常的版本

v1.20.0

### 操作系统版本

Microsoft Windows 10 企业版 LTSC 10.0.17763 暂缺 Build 17763

**Comment by lyswhut** [comment]
https://lyswhut.github.io/lx-music-doc/desktop/interface-abnormal

> ### Windows 10、11界面异常
> 这个问题一般是硬件加速有问题导致的，尝试添加启动参数 `-dha` 启动，例如：`.\lx-music-desktop.exe -dha`，添加方法可自行百度“给快捷方式加参数”，该参数的作用是禁用硬件加速启动，没有遇到问题不要使用此参数！

**Comment by RAint0** [comment]
> https://lyswhut.github.io/lx-music-doc/desktop/faq/interface-abnormal
> 
> > ### Windows 10、11界面异常、界面无法显示
> > 尝试添加运行参数 `--disable-gpu-sandbox` 启动，例如：`.\lx-music-desktop.exe --disable-gpu-sandbox`，添加方法可自行百度“给快捷方式加参数”。
> > 若以上方法无效，则尝试将 `--disable-gpu-sandbox` 逐个换成以下参数启动，直到恢复正常为止：
> > 
> > * `--no-sandbox`
> > * `-dha`
> > * `--disable-gpu`
> > 
> > 注意：这些参数会禁用程序的某些安全特性或降低程序性能，没有遇到问题不要使用它们！
> > 对于界面无法显示，任务栏里也没看到图标，但是任务管理器里面看到进程的问题，还可尝试更换软件安装目录（对于安装版 需要先卸载再换目录安装，绿色版直接剪切移动即可，只要目录换了就行），
> > 此方法的相关讨论看：[#943 (comment)](https://github.com/lyswhut/lx-music-desktop/issues/943#issuecomment-1217832186)

最近发现这是electron的通病，可以尝试在Nvidia控制面板中关闭「平滑处理-FXAA」。这样可以顺便解决vscode，github客户端等字体模糊的问题，同时不用降低性能。

**Comment by Uhako** [comment]
> > https://lyswhut.github.io/lx-music-doc/desktop/faq/interface-abnormal
> > > ### Windows 10、11界面异常、界面无法显示
> > > 尝试添加运行参数 `--disable-gpu-sandbox` 启动，例如：`.\lx-music-desktop.exe --disable-gpu-sandbox`，添加方法可自行百度“给快捷方式加参数”。
> > > 若以上方法无效，则尝试将 `--disable-gpu-sandbox` 逐个换成以下参数启动，直到恢复正常为止：
> > > 
> > > * `--no-sandbox`
> > > * `-dha`
> > > * `--disable-gpu`
> > > 
> > > 注意：这些参数会禁用程序的某些安全特性或降低程序性能，没有遇到问题不要使用它们！
> > > 对于界面无法显示，任务栏里也没看到图标，但是任务管理器里面看到进程的问题，还可尝试更换软件安装目录（对于安装版 需要先卸载再换目录安装，绿色版直接剪切移动即可，只要目录换了就行），
> > > 此方法的相关讨论看：[#943 (comment)](https://github.com/lyswhut/lx-music-desktop/issues/943#issuecomment-1217832186)
> 
> 最近发现这是electron的通病，可以尝试在Nvidia控制面板中关闭「平滑处理-FXAA」。这样可以顺便解决vscode，github客户端等字体模糊的问题，同时不用降低性能。

好回答，我刚好遇到屏幕模糊的问题，你解决了我的问题，感谢你！
