### ISSUE TITLE
[Feature]: 歌单搜索

### ISSUE THREAD

**Issue by sorosunrain** [lyswhut/lx-music-desktop#936]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

是我没用明白怎么搜索歌单吗？

### 描述你想要的解决方案

搜索结果可以选择是单曲还是歌单

**Comment by lssb** [comment]
我也找了，， 发现好像就是没有搜索歌单的选项，不知道能不能增加这个功能？

**Comment by mmook** [comment]
是的，我也没有找到
软件做的非常棒，希望开发者能考虑下歌单的搜索。
对于我使用的场景是，曾经听过某个歌手的专辑（卡带、CD），想要再搜一下，把这个专辑所有的歌曲存到“我喜欢”

**Comment by jahem** [comment]
我也需要，突然想找前天看到的歌单，找不到了

**Comment by lyswhut** [comment]
已在v2.0.0新增
