### ISSUE TITLE
哦No...接口无法访问了！

### ISSUE THREAD

**Issue by mayjack0312** [lyswhut/lx-music-desktop#938]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

继歌曲链接获取中后：
播放部分歌曲出现Try toggle source...
下载部分歌曲出现哦No...接口无法访问了！

### 实际行为

继歌曲链接获取中后：
播放部分歌曲出现Try toggle source...
下载部分歌曲出现哦No...接口无法访问了！

### Lx Music 版本

1.22.1

### 最后正常的版本

1.22.1

### 操作系统版本

Win10 21H2 19044.1865

**Comment by lyswhut** [comment]
看常见问题：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-play-and-download
