### ISSUE TITLE
[Feature]: 将配置文件保存在单独的文件夹

### ISSUE THREAD

**Issue by jiongge** [lyswhut/lx-music-desktop#939]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我用的是绿色版，然后建了个portable\userData目录用来保存配置项，歌单，收藏什么的，，我本来是想同步这个目录在两台电脑上，换电脑后这些都还在，但是这个目录下产生了大量的日志和缓存文件

### 描述你想要的解决方案

能不能这个目录只有设置，歌单和收藏什么的，就只保存设置项里面的导出项目一样，感觉就像实时导出
或者可以设置缓存，日志目录，能不放到这个目录

**Comment by lyswhut** [comment]
你可以在你的同步软件设置只同步此目录下的.json文件，并且不同步子文件夹，如果不能设置那就暂无解决办法

要实现这个功能则需要迁移就的配置，后面看情况添加

**Comment by lyswhut** [comment]
在v2.0.0中，LX自己的配置、数据等将保存在数据目录下的`LxDatas`目录中，例如：`%APPDATA%/lx-music-desktop/LxDatas`
