### ISSUE TITLE
网易云搜不到音乐

### ISSUE THREAD

**Issue by pmbdlw** [lyswhut/lx-music-desktop#94]
**描述错误**
网易云搜不到音乐，版本0.12.1 mac版

**重现**
重现行为的步骤：
1.搜索，网易云，无数据

![image](https://user-images.githubusercontent.com/22488793/70116272-12ec4b00-16c7-11ea-8c23-50c3f52be914.png)

**Comment by lyswhut** [comment]
我试了下，我这边是可以的，
你可以看下其他源是否可以搜索，网易云及其他源歌单、排行榜是否有数据

**Comment by pmbdlw** [comment]
其他的都有，就是网易云没有，试了下测试接口和临时接口都不行。我需要关闭这个issue吗？

**Comment by lyswhut** [comment]
就只有网易云的搜索、歌单、排行榜不可以吗？如果是这样，你可以开试试开代理
