### ISSUE TITLE
[Feature]: 能否考虑支持 Last.fm Scrobbler

### ISSUE THREAD

**Issue by kiyurei** [lyswhut/lx-music-desktop#940]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

请求添加此功能用于记录音乐

### 描述你想要的解决方案

如yesplaymusic[https://github.com/qier222/YesPlayMusic](url)

**Comment by lyswhut** [comment]
目前主要是支持国内主流的音乐平台，暂无添加国外平台的计划

**Comment by kiyurei** [comment]
这不算音乐平台，仅用于记录听歌次数，国内勉强能直连（我不显示图片），但不支持国外平台就算了，谢谢回复。

**Comment by RAint0** [comment]
我通过last.fm API和LX的SSE订阅，用python写了个小脚本，现在可以实现记录的功能了。脚本已经上传到github：https://github.com/RAint0/Last.FM-4-lx-music-desktop ,不过需要一些编程知识去使用。

**Comment by RAint0** [comment]
> 这不算音乐平台，仅用于记录听歌次数，国内勉强能直连（我不显示图片），但不支持国外平台就算了，谢谢回复。

我通过last.fm API和LX的SSE订阅，用python写了个小脚本，现在可以实现记录的功能了。脚本已经上传到github：https://github.com/RAint0/Last.FM-4-lx-music-desktop ,不过需要一些编程知识去使用。
