### ISSUE TITLE
[Bug]: 小秋一栏的歌曲搜索不到了

### ISSUE THREAD

**Issue by paroc108** [lyswhut/lx-music-desktop#941]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

没有错误提示，小秋一栏的歌曲搜索不到了

### 实际行为

没有错误提示，小秋一栏的歌曲搜索不到了

### Lx Music 版本

最新

### 操作系统版本

win11

**Comment by o81018o** [comment]
六音音源也失效了

**Comment by o81018o** [comment]
其他软件的QQ音源也失效了

**Comment by o81018o** [comment]
其他软件的QQ音源也失效了，腾讯在搞事？

**Comment by lyswhut** [comment]
beta版已修复：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by lyswhut** [comment]
已在v1.22.2修复
