### ISSUE TITLE
[Feature]: 非常喜欢这款软件，安卓版是否考虑适配Pad版本，目前安卓版本在Pad上使用，图标和字体有点偏小，操作有点不便。

### ISSUE THREAD

**Issue by Amazing199** [lyswhut/lx-music-desktop#942]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

是否考虑安卓版适配Pad

### 描述你想要的解决方案

非常喜欢这款软件，安卓版是否考虑适配Pad版本，目前安卓版本在Pad上使用，图标和字体有点偏小，操作有点不便。

**Comment by lyswhut** [comment]
目前移动端没有适配高pdi屏幕，计划以后会优化，但这在短时间内不会去解决

此为PC端仓库，下次移动端的问题请去移动端仓库提，谢谢配合，现在我将此issue关闭
