### ISSUE TITLE
[Feature]: 建议调用Meting API

### ISSUE THREAD

**Issue by iamPorter** [lyswhut/lx-music-desktop#944]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

为大家所见，现在程序下载音乐只可以选择128Kbps音质。

### 描述你想要的解决方案

如果只是因为解析程序问题，建议尝试调用[Meting](https://github.com/metowolf/Meting)的解析程序——虽说可能会对程序进行一定程度上的改造。

### 附加信息

如果说是版权问题，希望能参见刘明野的工具箱里的[MyFreeMP3](http://tools.liumingye.cn/music)。寻思着两个音乐平台知名度都相当高，为什么一个缩水了一个还在正常工作呢？
如果真的是有很大的版权纠葛——维持现状。

**Comment by o81018o** [comment]
换个音源不就行了

**Comment by iamPorter** [comment]
> 换个音源不就行了

这么说的话我应该说清楚点：我是希望程序**自带**一个调用Meting API（之类）的端口实现自带服务器（新增或者替换某个服务器）对下载高清晰度音乐的支持

**Comment by lyswhut** [comment]
目前没有内置更高音质源的打算，想要其他音质可以使用自定义源，或者使用其他软件代替
