### ISSUE TITLE
歌单问题

### ISSUE THREAD

**Issue by Ggboy5656** [lyswhut/lx-music-desktop#945]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

PC端无法导入网易云，QQ音乐歌单

### 描述你想要的解决方案

PC端无法导入网易云，QQ音乐歌单

### 描述你考虑过的替代方案

NO

**Comment by lyswhut** [comment]
https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist
