### ISSUE TITLE
其他软件的QQ音源也失效了，腾讯在搞事？

### ISSUE THREAD

**Issue by paroc108** [lyswhut/lx-music-desktop#946]
其他软件的QQ音源也失效了，腾讯在搞事？
怎么回事
_Originally posted by @o81018o in https://github.com/lyswhut/lx-music-desktop/issues/941#issuecomment-1212695653_

**Comment by o81018o** [comment]
只是搜索挂了，实际音源没有失效，可以搭配洛雪的油猴辅助脚本从歌曲页直接跳转

**Comment by luzaiquan888** [comment]
> 只是搜索挂了，实际音源没有失效，可以搭配洛雪的油猴辅助脚本从歌曲页直接跳转，可能只是QQ音乐的搜索改版了？

洛雪的油猴辅助脚本在哪里能找到？最近我也碰到QQ音源失效的问题

**Comment by o81018o** [comment]
仓库的自述文件里有

**Comment by o81018o** [comment]
> > 仓库的自述文件里有
> > 在哪里，麻烦给个链接

https://greasyfork.org/zh-CN/scripts/438148

**Comment by WanterCry** [comment]
好像是因为软件调用qq音乐的搜索引擎，但是qq搜索需要登陆，然后就不能搜索了

**Comment by lyswhut** [comment]
已在v1.22.2修复
