### ISSUE TITLE
[Feature]: 在播放界面添加下载按钮以临时解决音源无法搜索问题

### ISSUE THREAD

**Issue by atooy** [lyswhut/lx-music-desktop#948]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

能不能在播放界面添加下载按钮以临时解决音源无法搜索问题

### 描述你想要的解决方案

能不能在播放界面添加下载按钮以临时解决音源无法搜索问题

**Comment by atooy** [comment]
这样配合脚本就能完整使用

**Comment by lyswhut** [comment]
beta版已修复无法搜索的问题：https://github.com/lyswhut/lx-music-desktop/actions/workflows/beta-pack.yml

**Comment by lyswhut** [comment]
暂无打算在播放界面添加下载按钮，无法搜索的问题已在v1.22.2修复
