### ISSUE TITLE
[Feature]: 我有域名，服务器，能部署在网页端吗？用域名访问那种

### ISSUE THREAD

**Issue by matthews84** [lyswhut/lx-music-desktop#949]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

想在手机用，但是是ios系统，想用网页访问，其实就只需要搜索、播放、列表、显示歌词功能

### 描述你想要的解决方案

我有域名，自己的服务器，接触最多的就是web项目，所以想试试在网页部署。

**Comment by wsdydeni** [comment]
当然是可以部署的啊

**Comment by matthews84** [comment]
> 当然是可以部署的啊
请问怎么部署呢？

**Comment by wsdydeni** [comment]
> > 当然是可以部署的啊
> > 请问怎么部署呢？

用容器部署，比如docker

**Comment by lyswhut** [comment]
设计这个应用的时候没有也不打算考虑在纯web环境下运行，所以无法在网页端运行
