### ISSUE TITLE
[Bug]: 无法导入wy源我喜欢歌单

### ISSUE THREAD

**Issue by yixier** [lyswhut/lx-music-desktop#951]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

可以正常导入在wy的歌单

### 实际行为

[无法导入wy本账号喜欢歌单直接报失败]
但是其他歌单可以导入
![图片](https://user-images.githubusercontent.com/111485252/185304957-a200c4d8-ed74-4f84-aa38-17431e2936b1.png)

### Lx Music 版本

1.12.1

### 操作系统版本

windows 10

**Comment by yixier** [comment]
![图片](https://user-images.githubusercontent.com/111485252/185305693-bd7f79f4-5d82-4128-a506-cf2dfaa4341b.png)

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist
