### ISSUE TITLE
[Bug]: 使用第三方源提示 `Error invoking remote method 'mainWindow_request_user_api': Error: failed`

### ISSUE THREAD

**Issue by tom63001** [lyswhut/lx-music-desktop#952]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

使用六音音源后，出现flac下载选项，能播放并且下载

### 实际行为

使用六音音源后，不论选择哪个音源都只能正常搜索，但是无法开始播放或者下载，
报错内容：Error invoking remote method 'mainWindow_request_user_api': Error: failed

### Lx Music 版本

1.22.2

### 操作系统版本

Windows 10 专业版 19043.1889

### 附加信息

![图像_2022-08-18_154140608](https://user-images.githubusercontent.com/24217147/185480510-e3939a4a-3d1f-49a5-a2d7-1edc460890cc.png)
![图像_2022-08-18_154200580](https://user-images.githubusercontent.com/24217147/185480562-76f609d2-3101-478d-9563-aac8a284eb29.png)

**Comment by lyswhut** [comment]
这是调用第三方源API失败时的提示信息，是源的问题，与LX本身无关

**Comment by tom63001** [comment]
好的好的，多谢解答

**Comment by Win10Q** [comment]
这个源在哪下载啊
