### ISSUE TITLE
[Bug]: 你好作者,网易云2300多首的歌单无法加载出来

### ISSUE THREAD

**Issue by HENGDUCK** [lyswhut/lx-music-desktop#953]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

1

### 实际行为

1

### Lx Music 版本

1.22.2

### 操作系统版本

Windows10 1909

### 附加信息

![微信截图_20220819154221](https://user-images.githubusercontent.com/73035215/185569300-c7f86de2-d300-4177-99aa-f104b2d14397.png)

**Comment by lyswhut** [comment]
看：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist

**Comment by HENGDUCK** [comment]
> 看：https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-open-songlist

谢谢，我开始只看了上面没有看到下面才是我需要的
