### ISSUE TITLE
[Bug]: Mac端无法播放酷狗来源的歌曲了啊？

### ISSUE THREAD

**Issue by wuzhengqiang** [lyswhut/lx-music-desktop#955]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

无论哪个系统的app端，搜索然后都应该正常试听和下载

### 实际行为

Mac端无法播放酷狗来源的歌曲了，搜索出来的全部没有试听按钮，点击加号收藏后再到收藏里面点击试听，提示api not found，但是windows版本目前没有问题。

### Lx Music 版本

1.22.1和1.22.2的mac版都有此问题

### 最后正常的版本

上周还可以，今天突然发现不行了

### 操作系统版本

mac os 12.4

**Comment by wuzhengqiang** [comment]
再仔细看了下，目前mac版只能播放酷我来源的，其他的全部不能播放了，是api改出问题了吗？急求修复啊，谢谢

**Comment by wuzhengqiang** [comment]
再仔细看了下，目前mac版搜索后只能播放酷我来源的，其他的全部没有试听按钮了，是api改出问题了吗？急求修复啊，谢谢

**Comment by qq790978763** [comment]
win端也没有kg的源

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/209

**Comment by wuzhengqiang** [comment]
> #209

好的，设置-音乐来源修改为测试接口，今晚回去试试。
