### ISSUE TITLE
[Feature]: 希望桌面端可以加上罗技键盘G610音量轴下方的四个按键的控制功能

### ISSUE THREAD

**Issue by Reminiserces** [lyswhut/lx-music-desktop#957]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望桌面端可以加上罗技键盘G610音量轴下方的四个按键的控制功能
![QQ截图20220821224428](https://user-images.githubusercontent.com/87899500/185796675-c1c15eb3-a176-4b74-b962-e630ee7f42cf.jpg)

### 描述你想要的解决方案

1

### 描述你考虑过的替代方案

1

### 附加信息

1

**Comment by lyswhut** [comment]
这看起来是媒体键，默认会注册媒体键的上、下曲、播放/暂停，如果无效则可能是被其他程序占用了，
如果不是媒体键，那你可以尝试注册全局快捷键

**Comment by Reminiserces** [comment]
收到&nbsp; 蟹蟹大大&nbsp; &nbsp;是被其他应用占用了&nbsp; 新开机就可以用了



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 22, 2022 00:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lyswhut/lx-music-desktop] [Feature]:  (Issue #957)




 
这看起来是媒体键，默认会注册媒体键的上、下曲、播放/暂停，如果无效则可能是被其他程序占用了，
 如果不是媒体键，那你可以尝试注册全局快捷键
