### ISSUE TITLE
[Bug]:拉最新的代码打包成pack:win:setup:x64，安装后无法打开，发现与官方发布的app.asar文件大小不一致，替换可以启动

### ISSUE THREAD

**Issue by earth-north** [lyswhut/lx-music-desktop#958]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

打包并安装后正常启动

### 实际行为

打包并安装后无法正常启动

### Lx Music 版本

1.22.2

### 操作系统版本

Windows 11 专业版（Windows 功能体验包 1000.22000.856.0）

**Comment by lyswhut** [comment]
`pack:win:setup:x64`只是构建安装包，没有编译源代码，所以在这之前需要先`build`，
更新信息看<https://lyswhut.github.io/lx-music-doc/desktop/use-source-code>，或者`package.json`文件内的命令

**Comment by earth-north** [comment]
谢谢您的答案
