### ISSUE TITLE
Setup.exe.blockmap这个文件怎么使用?

### ISSUE THREAD

**Issue by justbboychou** [lyswhut/lx-music-desktop#962]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

Setup.exe.blockmap这个文件怎么使用?

### 描述你想要的解决方案

Setup.exe.blockmap这个文件怎么使用?

**Comment by lyswhut** [comment]
这是构建安装包时一起生成的安装包内文件块信息，在自动更新时用于差异更新，所以不需要管它，也不需要下载它

**Comment by justbboychou** [comment]
> 这是构建安装包时一起生成的安装包内文件块信息，在自动更新时用于差异更新，所以不需要管它，也不需要下载它

3q
