### ISSUE TITLE
[Feature]: 希望添加下载页面按歌手/名称/专辑等等排序功能

### ISSUE THREAD

**Issue by jswnlinyu** [lyswhut/lx-music-desktop#964]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

如题

### 描述你想要的解决方案

使得歌曲可以重新排序而非按下载顺序排序

**Comment by lyswhut** [comment]
下载列表本质上不属于播放列表，添加排序功能没什么意义吧？后续会支持将本地音乐添加到我的列表
