### ISSUE TITLE
[Feature]: 希望能开通捐赠渠道

### ISSUE THREAD

**Issue by changBin-x** [lyswhut/lx-music-desktop#965]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望能开通捐赠渠道

### 描述你想要的解决方案

开发者不能只靠爱发电，希望能够开通捐赠渠道

**Comment by lyswhut** [comment]
此项目目前没有接受捐赠的计划，心意领了:)，谢谢！
