### ISSUE TITLE
[Feature]: 音乐无法播放

### ISSUE THREAD

**Issue by showyoulove1990** [lyswhut/lx-music-desktop#966]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

<img width="873" alt="image" src="https://user-images.githubusercontent.com/29604166/187142591-13b2e41d-99c3-4679-838e-76342d76ec03.png">

这几天开始，大部分音乐都是显示这个！

### 描述你想要的解决方案

<img width="873" alt="image" src="https://user-images.githubusercontent.com/29604166/187142666-77149e3b-3915-4e43-a94e-2b0f0a864b42.png">

**Comment by lyswhut** [comment]
按常见问题<https://lyswhut.github.io/lx-music-doc/desktop/faq/cannot-play-and-download> 无法连接到服务器的解决方案解决
