### ISSUE TITLE
[Feature]: 洛雪不可以下载歌曲了吗？

### ISSUE THREAD

**Issue by RuoCJ** [lyswhut/lx-music-desktop#969]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![image](https://user-images.githubusercontent.com/53935240/187354872-a4c86161-c9ff-44af-88b9-3af6ac4c8848.png)
右键没有下载选项

### 描述你想要的解决方案

没办法下载音乐了吗？

**Comment by 2531454360** [comment]
设置里面有一个选项，是否开启下载功能，默认关闭
自己去勾上就会显示了

**Comment by RuoCJ** [comment]
> 设置里面有一个选项，是否开启下载功能，默认关闭
> 自己去勾上就会显示了

谢谢啦

**Comment by Kelichao** [comment]
设置一下就有了，但是想问下，为什么下载按钮默认隐藏呢？

**Comment by jzfxly** [comment]
勾选后是有了，但是灰色，还是无法下载。

**Comment by Natsukifubu** [comment]
我也是下载键灰色
