### ISSUE TITLE
歌词显示

### ISSUE THREAD

**Issue by chen-can** [lyswhut/lx-music-desktop#97]
能否新增点击播放头像显示歌词页面
![image](https://user-images.githubusercontent.com/35422769/70210853-ad539980-176e-11ea-92a2-7473bb5ed76c.png)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/35
还有其他与`歌词`相关的issue：https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=%E6%AD%8C%E8%AF%8D
