### ISSUE TITLE
[Bug]: 音频可视化

### ISSUE THREAD

**Issue by iamyx123** [lyswhut/lx-music-desktop#970]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

音频可视化正常显示在播放页下方

### 实际行为

https://user-images.githubusercontent.com/88130457/187437730-5a0ecd73-0e52-47d0-a2ef-52c110ca9315.mp4

音频可视化未正确显示

### Lx Music 版本

1.22.2

### 操作系统版本

win11

**Comment by lyswhut** [comment]
没看懂你说的是什么意思
