### ISSUE TITLE
[Feature]: 希望可以增加一个竖排歌词的功能，不太喜欢横排的歌词

### ISSUE THREAD

**Issue by Meteor666s** [lyswhut/lx-music-desktop#971]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

软件内只有横排的歌词，也没有办法设置固定多行显示

### 描述你想要的解决方案

希望增加多行显示和竖排显示

**Comment by lyswhut** [comment]
已在v2.0.0新增
