### ISSUE TITLE
[Feature]: 希望可以添加歌单列表搜索功能

### ISSUE THREAD

**Issue by SmallYii** [lyswhut/lx-music-desktop#976]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

每次想找歌都得来回上下翻，不能搜索很难受

### 描述你想要的解决方案

希望在我的列表里增加搜索功能，可以搜索我歌单里的歌

**Comment by ljwrnd** [comment]
可以搜索啊 win系统Ctrl+f就能打开搜索框了

**Comment by SmallYii** [comment]
> 可以搜索啊win系统Ctrl+f打开搜索框了

原来软件里还有Ctrl+F 学到了
