### ISSUE TITLE
[Bug]: win7闪烁

### ISSUE THREAD

**Issue by justbboychou** [lyswhut/lx-music-desktop#977]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

Windows 7 下整个界面闪烁（消失又出现）
可尝试在关掉软件后，在桌面空白处鼠标右击，在弹出的菜单中选择个性化，在弹出的窗口中切换到系统内置的Aero主题，然后再启动软件看是否解决。

依然闪烁

### 实际行为

Windows 7 下整个界面闪烁（消失又出现）
可尝试在关掉软件后，在桌面空白处鼠标右击，在弹出的菜单中选择个性化，在弹出的窗口中切换到系统内置的Aero主题，然后再启动软件看是否解决。

依然闪烁

### Lx Music 版本

1.22.2

### 最后正常的版本

1.22.2

### 操作系统版本

win7

**Comment by lyswhut** [comment]
看常见问题<https://lyswhut.github.io/lx-music-doc/desktop/faq/interface-abnormal>
