### ISSUE TITLE
[Bug]: 就网易云的不能下载吗 哭了

### ISSUE THREAD

**Issue by Connor950707** [lyswhut/lx-music-desktop#978]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

就网易云的不能下载吗 哭了

### 实际行为

就网易云的不能下载吗 哭了

### Lx Music 版本

1.15.0

### 最后正常的版本

1.15.0

### 操作系统版本

WIN10

### 附加信息

就网易云的不能下载吗 哭了

**Comment by Kkwoai** [comment]
可以下载丫

**Comment by Connor950707** [comment]
> 可以下载丫

已经学会拉哈哈

**Comment by xishijt** [comment]
不止网易,下载功能好像被拔掉了

**Comment by lyswhut** [comment]
设置-下载-启用下载功能
