### ISSUE TITLE
macOS歌词显示

### ISSUE THREAD

**Issue by 37293493** [lyswhut/lx-music-desktop#98]
能否在这儿显示歌词，像QQ音乐那样，么么哒。
![WX20191205-182846](https://user-images.githubusercontent.com/30119467/70227194-25c95300-178d-11ea-9fe6-ec0872a3e0d1.png)

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/12
还有其他与歌词相关的issue：https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=%E6%AD%8C%E8%AF%8D
或看常见问题第一条
