### ISSUE TITLE
[Feature]: 下载功能没了，没有下载按钮

### ISSUE THREAD

**Issue by wqt12345** [lyswhut/lx-music-desktop#980]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

版本1.22.3，下载这个功能没了，都没有这个下载的按钮了

### 描述你想要的解决方案

添加下载功能

**Comment by wqt12345** [comment]
歌曲不能下载了

**Comment by com3dian** [comment]
可以尝试#969中提到的解决方案：https://github.com/lyswhut/lx-music-desktop/issues/969

**Comment by GreatAden** [comment]
设置里面，改成测试接口
