### ISSUE TITLE
[Bug]: 所有的音频都无法播放所有连接失效

### ISSUE THREAD

**Issue by yangkeith** [lyswhut/lx-music-desktop#981]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

所有的音频都无法播放所有连接失效

### 实际行为

所有的音频都无法播放所有连接失效

### Lx Music 版本

1.22.2

### 最后正常的版本

1.22.2

### 操作系统版本

Win11

**Comment by yangkeith** [comment]
好像还没有检测到当前最新版本

**Comment by lyswhut** [comment]
更新到1.22.3及之后的版本：

> 修复因音源的域名到期导致的音源失效的问题

**Comment by lyswhut** [comment]
更新到1.22.3及之后的版本：

> 修复因音源的域名到期导致的音源失效的问题

**Comment by yangkeith** [comment]
> 

我也是刚去官网看了一下，才知道更新了

**Comment by yangkeith** [comment]
![image](https://user-images.githubusercontent.com/18674852/188341162-815cbc61-8dca-4bb1-890c-622053f4cd08.png)
检测版本这还是一直无法获取

**Comment by lyswhut** [comment]
重启软件让它重新检测？

**Comment by yangkeith** [comment]
好像还是不行

**Comment by yangkeith** [comment]
1.22.2 就出现了

**Comment by yangkeith** [comment]
后边又能自动获取到最新版本了
