### ISSUE TITLE
[Feature]: 希望可以增加功能：支持搜索页歌曲循环播放。

### ISSUE THREAD

**Issue by Fol1vora** [lyswhut/lx-music-desktop#983]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前根据歌手搜索出的所有歌曲，并不支持在搜索页循环播放歌曲，导致我想听某个人的全部歌 只能全部添加到一个收藏夹中，才可以循环播放。希望可以增加功能：支持搜索页歌曲循环播放。

### 描述你想要的解决方案

希望增加功能：
     搜索页面根据歌曲名或者歌手名搜索出的歌曲列表，支持当前搜索页列表循环

**Comment by lyswhut** [comment]
不会添加播放整个搜索列表的功能，由于搜索结果可能会有很多数据，不会去加载所有结果播放，你可以使用多选功能将想要播放的歌曲添加到我的列表播放
