### ISSUE TITLE
[Bug]: 获取歌曲API都失效了呀，有可用的源么？

### ISSUE THREAD

**Issue by OneCodeMonkey** [lyswhut/lx-music-desktop#984]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常可播

### 实际行为

获取歌曲接口报错

### Lx Music 版本

1.21.0

### 最后正常的版本

1.21.0

### 操作系统版本

macOS Monterey 12.4

**Comment by xuberber** [comment]
更新到1.22可以解决

**Comment by OneCodeMonkey** [comment]
> 更新到1.22可以解决

ok 了，感谢感谢 ：）
