### ISSUE TITLE
[Bug]: 无法安装落雪音乐

### ISSUE THREAD

**Issue by shuaibaobao123** [lyswhut/lx-music-desktop#985]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

安装后打开落雪音乐

### 实际行为

无法打开落雪音乐
![image](https://user-images.githubusercontent.com/59220825/188569890-0ff84b7e-f204-4735-a704-42c5e4d937c0.png)

### Lx Music 版本

lx-music-desktop-1.22.3.dmg

### 操作系统版本

mac monterey 12.0

**Comment by windows7lake** [comment]
系统偏好设置->安全性与隐私->仍打开软件
进入”安全性与隐私-“后点击取消

**Comment by lyswhut** [comment]
看常见问题<https://lyswhut.github.io/lx-music-doc/desktop/faq/install-failed> ***MAC OS无法启动软件，提示 lx-music-desktop 已损坏***
