### ISSUE TITLE
[Feature]: 歌单排除重复歌曲筛查

### ISSUE THREAD

**Issue by Dododu** [lyswhut/lx-music-desktop#987]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有时同一首歌曲后面会带括号形容歌曲版本信息 类似：（live）（Explicit） 歌单排除重复的时候去除括号内容再进行对比

### 描述你想要的解决方案

歌单排除重复歌曲时除去后面括号内容再进行重复歌曲筛查

**Comment by lyswhut** [comment]
已在v2.0.0优化
