### ISSUE TITLE
[Bug]: 双显示器时歌词不能拖屏

### ISSUE THREAD

**Issue by 1873505600** [lyswhut/lx-music-desktop#989]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

我目前是由两个显示器，我希望歌词显示块可以从任意的从屏幕1放到屏幕2（不会有每个显示器只显示一部分这种情况）

### 实际行为

现在歌词默认显示到屏幕1，且无法拖出该屏幕到达屏幕2

### Lx Music 版本

1.22.3

### 操作系统版本

Windows10

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/430
