### ISSUE TITLE
下载的歌曲的详细信息里面没有标题、歌手等信息

### ISSUE THREAD

**Issue by wocaofuck** [lyswhut/lx-music-desktop#99]
首先多谢大佬的软件，良心又好用
下载的歌很多需要手动添加信息，有点麻烦，不然在本地播放器全部显示为kuwo啥的。
不是很懂怎么回事，能解决的话就好了。

**Comment by lyswhut** [comment]
你是指flac格式吗？
如果是的话，问题已重复：https://github.com/lyswhut/lx-music-desktop/issues/85
目前MP3格式是支持元数据自动设置的
