### ISSUE TITLE
[Feature]: 新增歌手搜索功能

### ISSUE THREAD

**Issue by GitHubQAQ** [lyswhut/lx-music-desktop#990]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

当前搜索歌手，无法多选播放。

### 描述你想要的解决方案

是否可以增加按照搜索出来的列表进行播放。
如搜索周杰伦，出现搜索列表（这里是否可以多选加入播放列表？）
又如搜索古典音乐，出现搜索列表，双击自动切换到当前列表。

### 描述你考虑过的替代方案

当前并不支持歌手界面音乐收录，退一步是否可以搜索后多选呢？

**Comment by lyswhut** [comment]
在线列表歌曲播放看：https://lyswhut.github.io/lx-music-doc/desktop/faq/list-play-all

**Comment by GitHubQAQ** [comment]
> 

谢谢，疑问已解决
