### ISSUE TITLE
[Feature]: 希望添加一个搜索列表添加全部播放、排行榜添加全部播放的功能，暂时这些歌曲只能一首一首点击播放

### ISSUE THREAD

**Issue by zhangliang357** [lyswhut/lx-music-desktop#992]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望添加一个搜索列表添加全部播放、排行榜添加全部播放的功能，暂时这些歌曲只能一首一首点击播放

### 描述你想要的解决方案

希望添加一个搜索列表添加全部播放、排行榜添加全部播放的功能，暂时这些歌曲只能一首一首点击播放

**Comment by lyswhut** [comment]
看常见问题：https://lyswhut.github.io/lx-music-doc/desktop/faq/list-play-all
