### ISSUE TITLE
[Bug]:不同源的同一首歌（完全相同）能被重复收藏

### ISSUE THREAD

**Issue by GuqingX** [lyswhut/lx-music-desktop#993]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

不同源同一首歌 只可被收藏一次 

### 实际行为

不同源同一首歌 可被重复收藏

### Lx Music 版本

1.22.3

### 最后正常的版本

1.22.3

### 操作系统版本

Windows 10 21H2

**Comment by lyswhut** [comment]
无法判断不同源相同歌名的歌曲是否是同一首歌，所以只能确保同源的同一首歌不能重复收藏，不过你可以使用重复歌曲功能手动删除重复歌曲，此功能可右击我的列表中的列表名使用
