### ISSUE TITLE
[Feature]: 希望手机端洛雪也能像电脑端那样导入网易云“我喜欢”歌单

### ISSUE THREAD

**Issue by GreatAden** [lyswhut/lx-music-desktop#994]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

电脑版本的洛雪在1.21版本就支持了通过链接尾部添加token以支持导入“我喜欢”歌单的内容，但是到现在手机版0.14.3还是不支持通过这种方式导入“我喜欢”歌单。而且通过同步的方式导入的歌单不能在手机端更新，大多数音乐还存在ApiNotfound无法播放的问题，希望能尽快添加此功能，并修复通过同步的歌单带来的问题

### 描述你想要的解决方案

在手机端添加支持在歌单链接后加token的方式导入网易云“我喜欢”歌单

**Comment by lyswhut** [comment]
移动端token问题重复：https://github.com/lyswhut/lx-music-mobile/issues/51
Api is not found 重复：https://github.com/lyswhut/lx-music-desktop/issues/550
