### ISSUE TITLE
[Bug]: Macos用户升级到1.22.3版本后播放出现问题，无法自动播放列表

### ISSUE THREAD

**Issue by gzaix** [lyswhut/lx-music-desktop#995]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

[Bug]: Macos用户升级到1.22.3版本后播放出现问题，无法自动播放列表
之前的版本，可以在排行榜或者收藏里面点击播放，就会自动整个目录进行播放
升级到1.22.3版本之后，发现点击播放只能播放单曲，按下一首也是播放当前，无法自动列表播放了

还有就是系统状态栏的显示功能柜一直都失效
系统版本macos 10.14.6

### 实际行为

[Bug]: Macos用户升级到1.22.3版本后播放出现问题，无法自动播放列表
之前的版本，可以在排行榜或者收藏里面点击播放，就会自动整个目录进行播放
升级到1.22.3版本之后，发现点击播放只能播放单曲，按下一首也是播放当前，无法自动列表播放了

还有就是系统状态栏的显示功能柜一直都失效
系统版本macos 10.14.6

### Lx Music 版本

1.22.3

### 最后正常的版本

1.21

### 操作系统版本

macos10.14.6

**Comment by lyswhut** [comment]
检查切歌模式：
![image](https://user-images.githubusercontent.com/20365169/191142333-ceaf4ec6-6a7f-4be6-962a-dccf0320b100.png)

**Comment by gzaix** [comment]
> 检查切歌模式： ![image](https://user-images.githubusercontent.com/20365169/191142333-ceaf4ec6-6a7f-4be6-962a-dccf0320b100.png)

感谢，确实不知道什么时候自己点到单曲循环了没注意。
