### ISSUE TITLE
[Bug]: 更新页面的下载版本，下载地址和说明在黑色模式下啥啥也看不清啊

### ISSUE THREAD

**Issue by allan-pm** [lyswhut/lx-music-desktop#996]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

非常的清晰可读。

### 实际行为

![image](https://user-images.githubusercontent.com/100672107/191473433-ed8f3a0d-9ba8-4bd4-99d7-5f916916fd5f.png)

### Lx Music 版本

1.22.2

### 最后正常的版本

忘了

### 操作系统版本

Windows 21H2

**Comment by lyswhut** [comment]
已在v2.0.0优化
