### ISSUE TITLE
[Bug]: Mac 拓展屏幕 歌词仅能在第一个屏幕拖动 不能在其他显示器显示

### ISSUE THREAD

**Issue by dobetterfe** [lyswhut/lx-music-desktop#997]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

随意拖动歌词到任意屏幕

### 实际行为

无法拖动至其他显示器

### Lx Music 版本

1.22.3

### 操作系统版本

macOS Monterey 版本12.5.1

**Comment by 14kk** [comment]
附议
