### ISSUE TITLE
[Bug]:打开qq音乐歌单时新加的歌没有出现

### ISSUE THREAD

**Issue by 465515119** [lyswhut/lx-music-desktop#999]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

输入以前打开过的音乐歌单，获取到新增的歌曲

### 实际行为

展示的列表为就歌单数据，新增的歌曲没有出现在列表里面

### Lx Music 版本

V1.22.3

### 操作系统版本

Windows 10 家庭中文版 21H2

**Comment by lyswhut** [comment]
打开过的歌单再次打开时，在重启程序前都会使用第一次打开时的列表缓存，目前的临时解决方法是收藏该歌单，然后去我的列表使用歌单更新功能更新歌单，更新歌单功能会绕过缓存重新在线拉取

**Comment by 465515119** [comment]
Received. Thanks a lot. 
谢谢我已收到您的邮件，稍后回复。
